### ISSUE TITLE
Mark OSI approval for existing BSD-1-Clause

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1005]
BSD-1-Clause is [currently on the license list](https://spdx.org/licenses/BSD-1-Clause.html). It has now been approved by OSI, see [license-discuss](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-April/004807.html).

* isOsiApproved should be set to "true"
* also, note that references to the interchangeable text `Berkeley Software Design, Inc.` should _perhaps_ be changed to `[Name of Organization]`, to reflect the decision made in the OSI approval thread

**Comment by jlovejoy** [comment]
+ 1

**Comment by jlovejoy** [comment]
created PR #1023

**Comment by jlovejoy** [comment]
i don't really think we need to change the org name - it's aesthetic really, as it's replaceable text anyway

**Comment by swinslow** [comment]
Thanks @jlovejoy! Agreed, fine with leaving org name as-is. Merged now so I'm closing this issue.
