### ISSUE TITLE
add notes to deprecated licenses as per comment in header

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1006]
I thought these were in there, but not seeing them, especially for https://spdx.org/licenses/Nunit.html and https://spdx.org/licenses/StandardML-NJ.html and any others not part of the v2 and v3.0 big changes already explained.

**Comment by jlovejoy** [comment]
what did I have in mind for this... @swinslow 
maybe follow this example - https://spdx.org/licenses/AGPL-1.0.html  (which is the minority, but a nice Note)

**Comment by jlovejoy** [comment]
put comment on all re:
- why deprecated (short version)
- what to use instead

make PR on a few and have legal team review for

**Comment by swinslow** [comment]
@jlovejoy If you don't expect to have a PR ready today for review on the legal team call, I'll plan to move this one to 3.12 since the 3.11 release will be next week. Thanks!

**Comment by swinslow** [comment]
moving to 3.12

**Comment by jlovejoy** [comment]
see PR #1180
