### ISSUE TITLE
Templated openvpn-openssl-exception

### ISSUE THREAD

**Issue by isuruf** [spdx/license-list-XML#1007]
psycopg2 uses this exception as in https://github.com/psycopg/psycopg2/blob/master/LICENSE#L14-L24

Only difference is that `OpenVPN Technologies, Inc` becomes `copyright holders` and the addition of `If you delete this exceptionstatement from all source files in the program, then also delete it here.`

**Comment by goneall** [comment]
Transferred issue from license-list-data

**Comment by swinslow** [comment]
@markatwood Can you take a look at this too?

**Comment by MarkAtwood** [comment]
I'll take it

**Comment by mbaushke** [comment]
I will note that the latest OpenSSL code base (3.0 Alpha4)
moves to the Apache 2.0 License.

**Comment by jlovejoy** [comment]
closing, as consolidated all OpenSSL variants into #1356
