### ISSUE TITLE
update definition / guidelines for exceptions 

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1022]
this was discussed on Nov 29th, 2018 (as well as other times here and there) - https://wiki.spdx.org/view/Legal_Team/Minutes/2018-11-29

Definition is: "These exceptions grant an exception to a license condition or additional permissions beyond those granted in a license; they are not stand-alone licenses." 

Came up again on May 7th 2020 call - due to question re Commons Clause addition

Should "exceptions" include anything that is designed to modify a license?
Should "exceptions" be such that they can be removed and a person can use the license as-is?

also discussed: 
https://wiki.spdx.org/view/Legal_Team/Minutes/2018-05-17
https://wiki.spdx.org/view/Legal_Team/Minutes/2018-10-18

**Comment by jlovejoy** [comment]
(we probably need to add something to license inclusion guidelines to address exceptions directly - something to work on, hence this issue)

**Comment by swinslow** [comment]
Discussed briefly on 2020-08-27 legal team call; agreed this needs more discussion and would need to be a broader conversation with the community, including the general team call if there is actually a desire for a change.

**Comment by jlovejoy** [comment]
This has the potential to be more than a documentation issue, but tagging it as such so we can review and decide if it's something to carry forward or close from the policy perspective.

**Comment by jlovejoy** [comment]
consider this with potential proposal to add ExceptionRef- (which we currently do not have). This would then force a closer look at this definition (which then impacts documentation). Also impacts license expression syntax.

License inclusion guidelines probably should recognize exceptions (they currently don't)

**Comment by swinslow** [comment]
Based on brief discussions during the 3.19 release team meetings, this is not really a "documentation" issue so much as it is a set of policy considerations, e.g.:

* should custom exceptions be permitted via ExceptionRef-? (see change proposal at https://github.com/spdx/change-proposal/issues/4)
* for exceptions on the License List itself, how should "exception" be defined?
* related to that point, how should the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md) account for exceptions?

I'm removing the 3.19 milestone and marking these as "later release." These will require discussion and input from the community if and when they will be addressed.

**Comment by swinslow** [comment]
@jlovejoy I've submitted #1883 to address codifying this as a first instance.
