### ISSUE TITLE
Open Group License

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1026]
Submitting issue on behalf of request sent to mailing list, see https://lists.spdx.org/g/Spdx-legal/message/2806:

= = = = =

Hi,

while adding identifiers to licenses used in the BSP (note: i am a
legal trainee, so wording may not be technical perfect), i stumbled
upon the The Open Group License, which does not have an identifier yet.
It is used in: xorg-app-iceauth, xorg-app-rgb, xorg-app-xauth, xorg-
app-xdm, xorg-app-xinit, xorg-app-xprop, xorg-app-xrdb, xorg-app-xset,
xorg-app-xsetroot, xorg-app-xvinfo (and maybe some more).
The wording is consistent the following (copyright holder is always The
Open Group):

COPYING

- - -

Copyright <yyyy, yyyy> <Copyright Holder>

Permission to use, copy, modify, distribute, and sell this software and
its documentation for any purpose is hereby granted without fee,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL <Copyright Holder> BE LIABLE FOR ANY CLAIM, DAMAGES
OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of <Copyright Holder>
shall not be used in advertising or otherwise to promote the sale, use
or other dealings in this Software without prior written authorization
from <Copyright Holder>.

- - -

The first paragraph is different from X11-License, therefore i do not
want to use the X11-identifier:
> Permission to use, copy, modify, distribute,
as in curl; no "including without limitation" like X11
> and sell this software and its documentation
software and documentation are not together defined as "the software"
and therefore more divided than in X11-License
> for any purpose is hereby granted without fee, provided
> that the above copyright notice appear in all copies and that both
> that copyright notice and this permission notice appear in supporting
> documentation.
X11 does not require appearance in documentation, but in substantial
parts of software.

I am hoping that you can add the License to the license list so it may
gain an identifier.
Thank you!

Felicitas Jung

**Comment by bgoldring** [comment]
Comment to help with this.

**Comment by swinslow** [comment]
Discussed on 2020-06-04 legal team call. Looks like an amalgam of ISC / HPND intro paragraph + MIT/X11 main body. Used in several still-maintained xorg applications but copyright notices date back to late 1990's. 

May want to ask Open Group for input on naming / identifiers -- do we have contacts there? OGSpecs@opengroup.org from website -- @swinslow to reach out

Calling "Open Group" may discourage others from applying to their own projects

Separate question whether [X11 license](https://spdx.org/licenses/X11.html) should have markup for 'X Consortium'

**Comment by swinslow** [comment]
I've emailed them to request their input, will let you know what I hear back (or they may feel free to respond here directly!)

**Comment by swinslow** [comment]
No response yet from email; I am moving this one to 3.11

**Comment by swinslow** [comment]
No response yet from email. I would suggest we move forward with adding this and choosing a name / identifier since we have not been able to find an upstream contact for their input.

**Comment by swinslow** [comment]
Discussed on 2020-10-22 SPDX legal team call; agreed to add and to proceed with choosing a name / identifier. Scancode uses MIT-open-group, we'll go with that here.

**Comment by jlovejoy** [comment]
@swinslow -
"MIT-open-group" is short identifier
but did we decide on a full name?

**Comment by swinslow** [comment]
I'm not sure we did, I'd suggest "MIT Open Group variant"

**Comment by RishabhBhatnagar** [comment]
I would like to work on this issue if it is not being worked upon by anyone else. 😀.

**Comment by swinslow** [comment]
All yours, thanks @RishabhBhatnagar!
