### ISSUE TITLE
Mark PHP-3.01 as OSI-approved

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1032]
see http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-May/004841.html

**Comment by lemance** [comment]
@swinslow

**Comment by swinslow** [comment]
Assigned, thank you @emmanueltournier!

The entry for PHP-3.01 is defined in https://github.com/spdx/license-list-XML/blob/master/src/PHP-3.01.xml. In that file, you'll see in line 3 `isOsiApproved="false"`. Since OSI has approved, we'll just want to change the `false` to `true`.

If you can submit a PR to make that change, that would be great :)  You should be able to do that directly in the GitHub interface while you're viewing the file, by clicking the pencil icon (Edit) on the right side, just above where the file content starts. It should prompt you at the bottom that it will create a new fork of the license-list-XML repo in your account, and a new branch for the change.

If you run into any issues, feel free to ping me again and I'm happy to weigh in. Thanks for your help!

**Comment by swinslow** [comment]
Fixed by #1041.
