### ISSUE TITLE
License for this repository could be more clear

### ISSUE THREAD

**Issue by gdgib** [spdx/license-list-XML#1044]
I notice that in `package.json` this repository is marked as being CC-0, but the GitHub algorithms don't pick that up clearly since there's no `LICENSE` file.  May I suggest using https://creativecommons.org/choose/zero/waiver to create such a file, so that this repository itself is more clearly licensed?

**Comment by gdgib** [comment]
(I'd open a PR myself, but it seems a little shady to actually contribute a license file)

**Comment by jlovejoy** [comment]
discussed on legal call 5th Nov: ok to put CC-0 to the extent anything here is copyrightable, but want to be clear we are not making an opinion or implying license files themselves are copyrightable. 

need to do a bit of research of how a license file and Github identification works as well (so moving to next release)

**Comment by jlovejoy** [comment]
also see #986

**Comment by gdgib** [comment]
Thanks for staying on top of this.  It's a very reasonable point about the licenses themselves, but it sure makes my head hurt a little.

**Comment by jlovejoy** [comment]
@gdgib - don't let it make your head hurt (even a little) - it's not worth it! ;)

**Comment by jlovejoy** [comment]
I'm going to close this, as we have #986 and I think that covers it.
