### ISSUE TITLE
Unlicense: add OSI approval?

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1046]
http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-June/004880.html

under review, to be discussed on OSI called on June 12th

**Comment by swinslow** [comment]
Approved by OSI board on June 12, just noted at http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-June/004890.html

**Comment by vmbrasseur** [comment]
ohai

I'll take this one. :-)
