### ISSUE TITLE
Travis CI running but not showing in some PRs

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1055]
Travis CI still appears to be running for all PRs, but for some it is not showing up in the checks.

For instance, see https://travis-ci.org/github/spdx/license-list-XML/pull_requests -- currently #1051 and #1053 are showing up in the list on Travis, but if you look at those PRs themselves, the checks are not showing up there (so they are not showing up as failing or passing).

@goneall I'm not sure if you might have an idea what could cause this?

**Comment by goneall** [comment]
@swinslow I took a look and indeed they are not showing up in the PR's.  The webooks are configured.  I'm not quite sure what the cause could be.

@tsteenbe @pombredanne any ideas?

**Comment by swinslow** [comment]
It looks like this has resolved itself (or maybe @goneall fixed it behind the scenes!) I'll go ahead and close the issue, and will re-open if it reoccurs.
