### ISSUE TITLE
Review ANTLR-PD for potential omission

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1056]
(copied from mailing list, see https://lists.spdx.org/g/Spdx-legal/message/2838)

= = = = =

Hello list,

I just found out that there is a deviation from
https://spdx.org/licenses/ANTLR-PD.html#licenseText to the linked text from
http://www.antlr2.org/license.html which contains the following language:

"In countries where the Public Domain status of the work may not be valid,
the author grants a copyright licence to the general public to deal in the
work without restriction and permission to sublicence derivates under the
terms of any (OSI approved) Open Source licence."

From the perspective from EU law this is an extremely important part since
it makes clear that a unrestricted license is intended if PD does not work.
This avoids (always disputable) interpretation of the PD text.

Is there any reason for the omission? Could the text be added?

Best regards,

Till

**Comment by swinslow** [comment]
Note that the original version of the ANTLR 2 License on the ANTLR site did _not_ have this additional paragraph; see e.g. http://web.archive.org/web/20130401024631/https://www.antlr2.org/license.html

I haven't done a deeper dive on the Wayback Machine yet to figure out when it was added.

Propose adding the additional paragraph but marking it as optional so that it doesn't break matches with older uses of ANTLR-PD.

**Comment by swinslow** [comment]
Discussed on 2020-07-16 legal team call, disagreed with my earlier comment -- should add as a separate license. Will use ANTLR-PD-fallback to mirror NIST-PD-fallback which was just added today.

**Comment by swinslow** [comment]
question now posted to ANTLR community at: https://groups.google.com/g/antlr-discussion/c/XmeRzJ4xUeU

**Comment by swinslow** [comment]
Received confirmation from email with project author -- new entry should include the first three paragraphs from https://www.antlr2.org/license.html, but should not include the fourth paragraph ("The Python parser generator code...")

**Comment by jlovejoy** [comment]
@swinslow , is #1079 ready to be reviewed and merged?

**Comment by swinslow** [comment]
@jlovejoy I just need to update it from 3.10 to 3.11 in the listVersionAdded -- doing that now, and also giving it a once-over to confirm otherwise looks good.

**Comment by swinslow** [comment]
ok, after tests pass this one should be good to go, if we can get a +1 from folks
