### ISSUE TITLE
Two versions of LGPL-2.1

### ISSUE THREAD

**Issue by MarkAtwood** [spdx/license-list-XML#1057]

**Comment by emmanueltournier** [comment]
I'll be looking at this one.

**Comment by emmanueltournier** [comment]
@swinslow just to clarify, we should have something like this? :

<optional>&lt;</optional>one line to give the library's name and an idea of what it does.<optional>&gt;</optional>
<optional>&lt;</optional>one line to give the library's name and a brief idea of what it does.<optional>&gt;</optional>

**Comment by swinslow** [comment]
Hi @emmanueltournier, this one will involve creating an `<alt>` tag with a match option for the two different formats. You can see examples of this, for instance, at https://github.com/spdx/license-list-XML/blob/af50167c006737d07f97c4aec779cc594b36a0b1/src/Apache-1.1.xml#L43

Let's plan to discuss during today's spdx-legal team call (if you're able to join) and I can show specifically how this would work. Thanks!

**Comment by emmanueltournier** [comment]
Hi @swinslow. I was planning to make the modification below. Let me know if you want to discuss before our next meeting. Thanks.

`<p>
	<optional>&lt;</optional>one line to give the library's name
	and <alt match="an idea">a brief idea</alt> of what it does.<optional>&gt;</optional>
        <br></br>
        Copyright (C)
        <optional>&lt;</optional>year<optional>&gt;</optional>
        <optional>&lt;</optional>name of author<optional>&gt;</optional>
 </p>`

**Comment by swinslow** [comment]
```
<alt match="an idea|a brief idea">
```
