### ISSUE TITLE
vsftpd OpenSSL exception

### ISSUE THREAD

**Issue by lal12** [spdx/license-list-XML#1058]
I've seen that there already is an exception `openvpn-openssl-exception`.
This one is basically the same just for vsftpd:

> vsftpd is licensed under version 2 of the GNU GPL.
> As copyright holder, I give permission for vsftpd to be linked to the OpenSSL
> libraries. This includes permission for vsftpd binaries to be distributed
> linked against the OpenSSL libraries. All other obligations under the GPL v2
> remain intact.

As far as I read I can submit an adding request via the webform, but this seems to be meant for new licenses not exceptions...

I am not sure if it would be suitable to add a more general "linking with openssl" exception, since I can imagine that this is not an uncommon thing. I currently found three examples (vsftpd, openvpn, deluge).

**Comment by swinslow** [comment]
@MarkAtwood - I know you're looking at some of the other OpenSSL exceptions, can you look at this as well?

**Comment by MarkAtwood** [comment]
Ill take it

**Comment by chenrui333** [comment]
Not sure about the status of this issue, I have encountered the similar license declaration in [this PR](https://github.com/Homebrew/homebrew-core/pull/68312)

```
license
-------

socat is distributed under the terms of the GNU GPLv2;
except for install-sh, which is copyright MIT, with its own license;

In addition, as a special exception, the copyright holder
gives permission to link the code of this program with
any version of the OpenSSL library which is distributed
under a license identical to that listed in the included
COPYING.OpenSSL file, and distribute linked combinations
including the two. You must obey the GNU General Public
License in all respects for all of the code used other
than OpenSSL. If you modify this file, you may extend this
exception to your version of the file, but you are not
obligated to do so. If you do not wish to do so, delete
this exception statement from your version.
```

**Comment by jlovejoy** [comment]
closing, as consolidated all OpenSSL variants into #1356
