### ISSUE TITLE
New license request: OCB [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by amallayev** [spdx/license-list-XML#1059]
**1.** License Name: License for Open-Source Software Implementations of OCB
**2.** Short identifier: OCB
**3.** License Author or steward: Phillip Rogaway
**4.** Comments: This is a license for open-source software that is missing from SPDX license list.
**5.** Standard License Header: 
**6.** URL: https://www.cs.ucdavis.edu/~rogaway/ocb/license.htm
**7.** OSI Status: Not Submitted

**Comment by johnmhoran** [comment]
I'll take this @swinslow .

**Comment by johnmhoran** [comment]
@amallayev Thank you for your new license request.  I see that the URL you provided (https://www.cs.ucdavis.edu/~rogaway/ocb/license.htm) lists three different licenses from Prof. Rogaway.

1.  Which of these licenses are you seeking to add to the SPDX License List?

2.  For each license you want to add, please provide several examples (with URLs) of how that license is being used.

**Comment by amallayev** [comment]
Hello John,

I am seeking specifically the first license in the list: “License for Open-Source Software Implementations of OCB".

https://www.cs.ucdavis.edu/~rogaway/ocb/license1.pdf

Sorry for not being elaborate.

As for the usage, parts of the libgcrypt20 obtained from OCB (confirmed with version 1.8.4-5, possibly earlier) are licensed under “Open-Source Software Implementations of OCB".

Source code can be obtained here: https://www.gnupg.org/ftp/gcrypt/libgcrypt/libgcrypt-1.8.6.tar.bz2
File licensed under OCB License 1: cipher/cipher-ocb.c

Let me know if further details will be needed.

--
Best regards,
Andrian Mallayev
Open Source Compliance Program

**Comment by johnmhoran** [comment]
Thank you @amallayev .  I've found a copy of the example file here as well:  https://github.com/gpg/libgcrypt/blob/master/cipher/cipher-ocb.c

As for the license itself (https://www.cs.ucdavis.edu/~rogaway/ocb/license1.pdf), it appears to include a patent license grant (Section 2.1), but I see no reference to a copyright license grant.  If that is indeed the case, this license may not be suitable for inclusion on the SPDX license list.  @swinslow  @jlovejoy What do you think?

**Comment by jlovejoy** [comment]
so, seems like the example is really LGPL-2.1-or-later, plus this specific patent grant/license?

**Comment by amallayev** [comment]
From what I see, it is indeed a LicenseRef case, agree.

**Comment by jlovejoy** [comment]
@amallayev - in that case, we will mark this as not approved for the SPDX License List.
Thanks for your additional info!
