### ISSUE TITLE
New license request: GD license

### ISSUE THREAD

**Issue by lal12** [spdx/license-list-XML#1060]
I found a "new license" in the image manipulation library "GD" or "libgd", I could not find any simular license in this repo.
URL: https://libgd.github.io/manuals/2.3.0/files/license-txt.html

**Comment by bgoldring** [comment]
Comment to assign.

**Comment by bgoldring** [comment]
@swinslow This version of the LibGD license is only used for LibGD. I cannot find any indication that it is used for any other project, as well it is specifically drafted referencing "gd" in the license itself. As such, it appears this license was only intended to be used with LibGD. Based on that, and the SPDX guidelines for license inclusion I would be of the recommendation it's not fit for inclusion at this time until more widespread use with other projects can be identified.

**Comment by lal12** [comment]
> @swinslow This version of the LibGD license is only used for LibGD. I cannot find any indication that it is used for any other project, as well it is specifically drafted referencing "gd" in the license itself. As such, it appears this license was only intended to be used with LibGD. Based on that, and the SPDX guidelines for license inclusion I would be of the recommendation it's not fit for inclusion at this time until more widespread use with other projects can be identified.

I don't know about the guidelines, but it seems to me that this is the case for a bunch of licenses with SPDX identifier: libpng, ntp, php, postgresql, python, ssh-openssh, vim, libpng, libtiff, imagemagick.

**Comment by jlovejoy** [comment]
@lal12 - the license inclusion guidelines are https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md

**Comment by lal12** [comment]
Well after reading the guidelines IMHO I would say that this license fits, apart from point 2 and 3 which are debatable. 

> 2. The license is structured to be generally usable by anyone. It is not specific to one project, consortium or corporation.

I would say it is structured to be generally usable by anyone. I think it is not necessary specific in terms of structure, though depending on the interpretation debatable.

> 3. The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects.

Well it is hard to know what exactly is "one significant project" though comparing it to e.g. libpng, libtiff, imagemagick I would say that about as widely used as them. 

So in my opinion if including the examples in my [previous post](https://github.com/spdx/license-list-XML/issues/1060#issuecomment-683257320) is considered correct this license should also be included. If it is considered not to be correct by the currenty guidelines anymore then the libgd license probably wouldn't be useful to include.

**Comment by swinslow** [comment]
Bumping to 3.12, Steve to take a closer look against existing list entries; Steve and Paul in favor of adding. Steve will add more details in a subsequent comment.

**Comment by jlovejoy** [comment]
+1 to add. This looks to be a package used in several Linux distros
@bgoldring - can you prepare the XML files in the next few days for the release?

**Comment by jlovejoy** [comment]
oops, we need a few more details on this one, as it wasn't submitted via the form, so bits are missing:
Full name: LibGD License
Identifier: LibGD

thoughts?

**Comment by bgoldring** [comment]
> +1 to add. This looks to be a package used in several Linux distros
> @bgoldring - can you prepare the XML files in the next few days for the release?

Do we have any guidance/documentation on doing that? I've never done it before. Thanks!

**Comment by lal12** [comment]
> oops, we need a few more details on this one, as it wasn't submitted via the form, so bits are missing:
> Full name: LibGD License
> Identifier: LibGD
> 
> thoughts?

at least in the license itself they always just refer to "gd", so I guess the "lib" part doesn't have to be in the name, but "gd" and "libgd" seem to be used more or less interchangeable.

**Comment by jlovejoy** [comment]
> at least in the license itself they always just refer to "gd", so I guess the "lib" part doesn't have to be in the name, but "gd" and "libgd" seem to be used more or less interchangeable.

good point. it does use "gd" in the license text itself. maybe we should ask some of the key contributors if they have a preference! 
@pierrejoye - we are trying to add the license for libGD to the SPDX License List - do you have any input on full name and identifier? That is:
Full name: "libGD License" or "GD License"
identifier: "LibGD" or just "GD"

@goneall - I notice we have no license identifiers with less than 3 letters. I think that is coincidental, but just checking if there is anything preventing a 2 letter identifier?

**Comment by jlovejoy** [comment]
> Do we have any guidance/documentation on doing that? I've never done it before. Thanks!

@bgoldring - see https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md 
need to sort out name question first

**Comment by goneall** [comment]
> anything preventing a 2 letter identifier?

No issue - it should be fine as long is it is unique.

**Comment by pierrejoye** [comment]
Good morning,

What do you mean by new "License"? The license is the same since day 1 as far as I can tell.

GD License should be good. What do you think? :)

**Comment by jlovejoy** [comment]
> What do you mean by new "License"? The license is the same since day 1 as far as I can tell.
"new" as in a new request to add a license to the SPDX License List :)
> 
> GD License should be good. What do you think? :)
if that works for you, then it works for us!

**Comment by pierrejoye** [comment]
Perfect then :)

Thank you for the effort!

**Comment by jlovejoy** [comment]
PR #1209
