### ISSUE TITLE
New license request: Creative Commons Attribution 3.0 United States

### ISSUE THREAD

**Issue by tillulen** [spdx/license-list-XML#1063]
**1.** License Name: Creative Commons Attribution 3.0 United States License
**2.** Short identifier: CC-BY-3.0-US
**3.** License Author or steward: Creative Commons Corporation
**4.** Comments: See below
**5.** Standard License Header: 
**6.** URL: https://creativecommons.org/licenses/by/3.0/us/legalcode
**7.** OSI Status: Not Submitted

_Comments_

I believe this US variant of the CC-BY-3.0 family is one of the more commonly used localized CC licenses. Is it widespread enough to warrant inclusion into the SPDX list? Here are a couple of data points:

- The EFF [still uses](https://www.eff.org/copyright) this license for all of their website content, so the license also covers any [datasets](https://www.eff.org/dice) they publish without assigning a license explicitly.

- A [GitHub search](https://github.com/search?q=%22creativecommons.org%2Flicenses%2Fby%2F3.0%2Fus%22&type=Code) yields on the order of 100k results (try reloading a few times, the figures are not reliable) that link to the license. Obviously, only some links represent an actual use of the license in a software project.

The license does not permit relicensing under CC-BY-4.0, so anything that is published under the CC-BY-3.0-US stays with that license forever unless an author cares to update the license.

Most of the time, this license covers some text or media content. Whenever such piece of content ends up being packaged along with a FOSS software project, we might want to describe it properly.

**Comment by swinslow** [comment]
Hi @tillulen, thanks for submitting this. I will raise this with the SPDX legal team during today's meeting for discussion.

Based on your input here, I am in favor of adding CC-BY-3.0-US to the License List. Our general approach towards the Creative Commons license jurisdiction-specific ports has been not to include them by default, but to add them if there is evidence that a particular jurisdiction port is widely used. I think the EFF and GitHub instances that you link to demonstrate widespread use that is sufficient to add it here. I'll discuss on today's meeting to get others' input as well.

**Comment by swinslow** [comment]
Discussed on 2020-10-22 legal team call, agreed to add.
