### ISSUE TITLE
vim backup files not in .gitignore

### ISSUE THREAD

**Issue by vmbrasseur** [spdx/license-list-XML#1066]
These keep coming up in my Github Desktop client when I'm committing things.

Gonna just go ahead and add a section for these to the .gitignore so they won't accidentally get added to the repo.

**Comment by vmbrasseur** [comment]
@swinslow Could you please assign me to this issue?

**Comment by swinslow** [comment]
This is great, I just recently started switching to using vim more often, and was noticing the same thing. Thanks for taking the initiative and fixing it.

Re: the issue number, I'm trying to figure out some way to work [Konqueror](https://kde.org/applications/internet/org.kde.konqueror) into a joke, but I'll just let it pass  :)

**Comment by swinslow** [comment]
Fixed in #1067.
