### ISSUE TITLE
Consider standardising CC (and other) titles?

### ISSUE THREAD

**Issue by vmbrasseur** [spdx/license-list-XML#1072]
Currently the titles of the CC licenses in the list don't exactly match the ones in the licenses themselves. For instance:

* In list: _Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO_
* In license: _Creative Commons Attribution-NonCommercial-NoDerivs 3.0 IGO_

This is a historical artefact from the bygone spreadsheet-based days of the SPDX list, but it leads to the question of whether we should change these to better reflect the actual license titles? And are there other licenses for which this is a problem?

Capturing this problem in an issue for conversation & posterity.

**Comment by swinslow** [comment]
@jlovejoy - Do you happen to recall why the original license list versions used titles for CC licenses that differed a bit from CC's own titles?

**Comment by jlovejoy** [comment]
I don't recall any specific reason or discussion on this. My guess would be... the neatness of no dashes in the full names? 

I could go either way on this one: I can see the symmetry of aligning it, but I'm not sure it really it matters as it's the full name, it's been that way for a decade - is it worth the work to update now?

**Comment by goneall** [comment]
I don't foresee any impact of this change on the tooling or license matching if you decide to make these changes.

**Comment by jlovejoy** [comment]
so, it looks like *all* the CC licenses have *no* dashes in the full name, with one exception: https://spdx.org/licenses/CC-BY-SA-3.0-AT.html

could do a PR to remove that one dash for consistency...

**Comment by jlovejoy** [comment]
fixed by #1257
