### ISSUE TITLE
New license request: Tomas [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by tomas1971** [spdx/license-list-XML#1073]
**1.** License Name: Tomas madbullortiz
**2.** Short identifier: Tomas
**3.** License Author or steward: 
**4.** Comments: 
**5.** Standard License Header: 
**6.** URL: http://13.57.134.254/app/submit_new_license/
**7.** OSI Status: Approved

**Comment by swinslow** [comment]
no license proposed; closing
