### ISSUE TITLE
update definition of "deprecated" on license page

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1082]
Question came up relating to OSI's list of retired license or licenses no longer recommended by the license steward and other flavors of that. We have generally accommodated this information in NOTES

For SPDX purposes, deprecated licenses is more about "don't use this SPDX identifier, b/c we've updated it for some reason" - not about "don't use this license"

was discussed on #711

**Comment by swinslow** [comment]
Hi @jlovejoy, is there anything here that you expect to have for the 3.11 release next week, or should I move this to 3.12?

**Comment by jlovejoy** [comment]
I think this issue pertains to maybe adding some text to the main page where the Deprecated licenses are that explains what SPDX considers "deprecated" - as it stands now, the description just goes into the why some license identifiers were deprecated. An opener sentence that defines "deprecated" would be good - maybe draft a strawman and discuss via mailing list and/or next call.

**Comment by jlovejoy** [comment]
proposed draft for first paragraph:

"While SPDX endeavors to never (rarely) change the SPDX license identifiers, sometimes there has been a compelling reasons such as to accommodate improved SPDX license expressions or we have found a duplicate license. When a license is "deprecated" on the SPDX License List, it effectively means that there is an updated license identifier and the deprecated license identifier should no longer be used. Some reasons for deprecation are as follows:" 

and then list the paragraphs re: license expressions, GNU family, etc. that already exists

**Comment by swinslow** [comment]
I like that! I would stick with "never change" rather than "rarely change" since it's that we "endeavor" not to do so. And by deprecating, we aren't really "changing" the identifiers in any case; they remain valid identifiers.

**Comment by silverhook** [comment]
I agree with both the last two comments :)

**Comment by jlovejoy** [comment]
thanks @swinslow @silverhook - revised text below (with some typo/grammar issues fixed, hopefully)


"SPDX endeavors to never change the SPDX license identifiers. However, sometimes there has been a compelling reason, such as to accommodate improved SPDX license expressions or when we have found a duplicate license. When a license is "deprecated" on the SPDX License List, it effectively means that there is an updated license identifier and the deprecated license identifier should no longer be used. Some reasons for deprecation are as follows:"

**Comment by zvr** [comment]
I'd add a word:

> When a license _identifier_ is "deprecated" ...

**Comment by swinslow** [comment]
> I'd add a word:
> 
> > When a license _identifier_ is "deprecated" ...

This is an interesting point -- I'd tend to agree with @zvr, I'd say it is the identifier that is being deprecated, not the license itself. Perhaps a nuance that doesn't matter too much but I'd go with that  :)

@jlovejoy looks good, one other tweak I would make. I think the second sentence now seems to imply that we _are_ changing the identifiers, which I don't think is correct -- we're deprecating them but they are still just as "valid" as they were pre-deprecation. So I think this is what I'd propose, including @zvr's edit, with changes in **bold**:

"SPDX endeavors to never change the SPDX license identifiers. However, sometimes there has been a compelling reason **to deprecate a license identifier**, such as to accommodate improved SPDX license expressions or when we have found a duplicate license. When a license **identifier** is "deprecated" on the SPDX License List, it effectively means that there is an updated license identifier and the deprecated license identifier, **while remaining valid,** should no longer be used. Some reasons for deprecation are as follows:"

**Comment by goneall** [comment]
@zvr @swinslow Just for clarification, can you explain the difference between having a deprecated license ID vs a deprecated license?  

I'm also wondering if we can make an assumption that there will always be another license identifier for the same license with the deprecated license ID on the SPDX license list.  In other words, we would never have a situation where we just want to no longer reference a license (e.g. some license steward wants us to remove it from the SPDX license list for some reason).   Making that assumption would help in some tooling scenarios.

**Comment by silverhook** [comment]
I think license identifier is a more correct term in practice, also because the “canonical” license texts/templates are still being worked on every now and again even after they have been added, while their IDs stay the same.

If that is an ideal situation, I’m not sure. But it’s more realistic.

**Comment by jlovejoy** [comment]
so, updated, final text is:

_SPDX endeavors to never change the SPDX license identifiers. However, sometimes there has been a compelling reason to deprecate a license identifier, such as to accommodate improved SPDX license expressions or when we have found a duplicate license. When a license identifier is "deprecated" on the SPDX License List, it effectively means that there is an updated license identifier and the deprecated license identifier, while remaining valid, should no longer be used. Some reasons for deprecation are as follows:_

@goneall 

> I'm also wondering if we can make an assumption that there will always be another license identifier for the same license with the deprecated license ID on the SPDX license list. In other words, we would never have a situation where we just want to no longer reference a license (e.g. some license steward wants us to remove it from the SPDX license list for some reason). Making that assumption would help in some tooling scenarios.

While we have never explicitly said this, it is how we have been operating for just over a decade now :)

**Comment by jlovejoy** [comment]
created PR for this in license-list-publisher repo, and @goneall and @swinslow  are aware, so I'm going to close this issue - ok?

**Comment by goneall** [comment]
Yes - I think this can be closed.
