### ISSUE TITLE
Improve the performance for license list checking and publishing

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#1085]
Currently, on each merge to the master branch we are running the [LicenseListPublisher](https://github.com/spdx/licenselistpublisher) for all of the licenses to generate the license list data and/or check the validity of the licenseXML.

With the size of the license list and the number of checks and file generated, it is now taking a significant amount of time per checkin even if only one license list XML file is changed.

Performance would be improved by 1 to 2 orders of magnitude of only the new or changed licenses are updated.

This would involve updates to the [Makefile](https://github.com/spdx/license-list-XML/blob/master/Makefile) and possibly changes to the LicenseListPublisher.

Following is an incomplete list of changes that would need to be made:

* Update the Makefile to detect which LicenseListXML files have changed
* For a normal merge, only run the LicenseListPublisher against the new changed files
  * This could be done by either copying the new/changed files into a clean directory and using that as a parameter to the LicenseListPublisher or by adding a parameter to the LicenseListPublisher to take individual file names
* Merge the new or updated LicenseListData files rather than refreshing the entire LicenseListData repo
* Handle deletions of LicenseListXML files by removing the corresponding LicenseListData representations
* Add a "CLEAN" option to force a reconstruction of the entire license list (similar to today)

**Comment by goneall** [comment]
Could use some help on this one from anyone familiar with Makefiles.

@swinslow as the person doing the license list releases, let me know if you have any other additions / updates to the list of changes

**Comment by zvr** [comment]
I can definitely help with Makefiles...
But can you, @swinslow or @goneall, describe the desired workflow? I can understand what the Makefile currently does, but it might worth it to start from a blank slate. What would be the ideal way to handle checking and publishing?

**Comment by goneall** [comment]
Here's my thoughts on the desired workflow - @swinslow feel free to add/subtract/or disagree

* On any pull request, any modifications to a license is validated
  * It is checked against the schema
  * Only the new or modified files are run through the license list publish to see if there are any errors or warning (rather than all of the licenses being check as of today)
  * Any failures block the PR until they are fixed
* On a merge or checkin to the master branch, the modifications are validated and the license list data is updated
  * same checks as in the PR
  * Only the updated licenses are reflected in the license list data repository (e.g. removed license XML files have their corresponding license list data files removed, added license XML files have their corresponding license list data files added, and any updates are reflected in the license list data)
* On a release (which could be triggered by a tag), all of the licenses are validated and the license list data is updated
  * All license files are validated
  * All of the license list data is re-created
  * License list data is updated
  * License list data is tagged

**Comment by swinslow** [comment]
@goneall I think that all makes sense. The only question I've got is about running the checks on all licenses vs. just the license(s) being added/modified in a PR.

Checking all licenses on each PR / commit does take a long time and can slow down the process. However, it also catches instances where a duplicate license is being added. Although that's rare -- and rarer still for it to happen by accident, vs. intentionally adding two different identifiers for the same license -- I'm debating whether it's still worth having those checks occur on each PR.

Open to your thoughts and also @jlovejoy if she has thoughts on this...

**Comment by goneall** [comment]
> The only question I've got is about running the checks on all licenses vs. just the license(s) being added/modified in a PR.

The proposed process is to only scan the licenses being added/modified in the PR.  The exception being on a release, everything would be checked.  I've updated the description to be a bit clearer on this.

**Comment by zvr** [comment]
OK, let me try to re-state all this, for my understanding

**Functionality**
*F1*. check that a license XML file validates against the schema
*F2*. update the `license-list-data` repo to be in sync with this repo (license files may have been added/removed/changed)
*F3*. make new release, validating and re-creating everything, and tagging the repo

**Automation**
*A1*. when a PR is submitted and it changes (or adds) an XML file, run *F1* on the file; if error, block the PR
*A2*. when the `master` branch is changed, run *F2* from master branch

**Building Blocks (tools)**
*BB1*. `licenseListPublisher`: works on complete directory; checks and generates data files. (all-in-one :-) )


Is this correct?

What about *F3* ? What's the "automation" for it?  Or can we simply have Steve or someone type a `make release` when everything is ready?

**Comment by goneall** [comment]
> A2. when the master branch is changed, run F2 from master branch

I would also add F1:

A2. when the master branch is changed, run F1 from master branch (only on changed files) and if it passes run F2 from the master branch

Also - I checked and the current version of licenseListPublish does support running against just a single file.  You just pass in the file name rather than a directory name and it will only run against that specific file.

> What about F3 ? What's the "automation" for it? Or can we simply have Steve or someone type a make release when everything is ready?

I'll leave that up to Steve in terms of the level of automation.  Right now Steve is manually tagging and updating.  The automation would be nice, but there has been some concerns expressed in the past about automating too much on releases.

**Comment by alandtse** [comment]
Given the thought to rethink the process, I would suggest looking at GitHub actions so it's handled as part of the CI. You can configure Actions to just run make so you still have a manual way to do it.

**Comment by swinslow** [comment]
Circling back on this earlier issue -- agreed with @alandtse, I think we need to explore switching to GitHub Actions. During the last license list release, Travis CI has slowed things down so much that it takes multiple hours before each build will be queued to run. I'll plan to bring this up on today's tech team call.

**Comment by swinslow** [comment]
@zvr @goneall for the earlier question about step "F3" in @zvr's draft writeup, I'm fine with there being a manual step of "make release" or something like that for me to run.

**Comment by swinslow** [comment]
Together with the changes by @goneall and @iamwillbar to get the CI moved from Travis to Github Actions, I think @goneall has made some changes to the setup so that on each PR it only checks the changed files.

It looks to me like this issue was for looking at some broader changes, and potentially moving away from the Makefile-based approach altogether, so I'll leave this open but am moving it to 3.13.

**Comment by jlovejoy** [comment]
@swinslow @goneall - is this now sort of done, fixed, or moot?

**Comment by swinslow** [comment]
I think (?) the answer is:
* partly done in that we've moved to GitHub Actions for running the license checks for each PR, and Travis CI is gone
* for pushing releases, the process _could_ be better and more automated, but none of us have time at the moment to do so  :)

In a perfect world, a lot of the steps that I do to push a release could be more automated or even fully automated. Unfortunately I don't have enough knowledge of GitHub Actions to make that happen, and I think there's a lot of competing priorities for others. So I'm leaning towards closing this one, and if in the future there's a desire and availability to further automate the release process, then we can reopen it.

I defer to others on this thread if they do actually have bandwidth to explore this -- happy to work with them on it if so!

**Comment by goneall** [comment]
My opinion is that the performance is "good enough", but it could certainly be improved.

I'm OK closing this - I certainly won't have time to work on this for the foreseeable future.

Note that there is a lot of good ideas documented in the issue, so if it does become more important, we'll want to re-open.

Pinging @zvr and @iamwillbar to see if they agree as well before closing.

**Comment by swinslow** [comment]
Thanks @goneall -- given no further comments from others since December, I'm going to go ahead and close this. Happy to re-open in the future if anyone wants to pick it up and drive it forward.
