### ISSUE TITLE
New license request: xenomai-exception-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by lsteube** [spdx/license-list-XML#1086]
**1.** License Name: Xenomai exception 2.0
**2.** Short identifier: xenomai-exception-2.0
**3.** License Author or steward: 
**4.** Comments: 
**5.** Standard License Header: 
**6.** URL: https://gitlab.denx.de/Xenomai/xenomai/blob/master/include/COPYING#L2-22
**7.** OSI Status: Not Submitted

**Comment by emmanueltournier** [comment]
Here

**Comment by swinslow** [comment]
@lsteube -- Thanks for this, are you aware if this exception is used anywhere other than the URL you sent?

**Comment by lsteube** [comment]
@swinslow as far as I know this is a Xenomai project specific license exception which appears to apply to at least the 2.x and 3.x project branches.

________________________________

**Comment by swinslow** [comment]
Discussed on 2020-11-05 legal team call, agreed that since it is limited to one project it is likely not appropriate for inclusion on the exceptions list. If you want to use a custom LicenseRef- to refer to the license + exception together, that could be an approach for you to use.
