### ISSUE TITLE
New license request: BSD-4-Clause-Shortened [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by winny-** [spdx/license-list-XML#1087]
**1.** License Name: BSD 4 Clause Shortened
**2.** Short identifier: BSD-4-Clause-Shortened
**3.** License Author or steward: Unknown
**4.** Comments: This appears only used for arpwatch. The license name is copied from the Debian license name for arpwatch. The license text is copied from arpwatch.c located in the arpwatch distribution tarball, with the comment prefixes stripped.
**5.** Standard License Header: 
**6.** URL: ftp://ftp.ee.lbl.gov/arpwatch.tar.gz https://metadata.ftp-master.debian.org/changelogs//main/a/arpwatch/arpwatch_2.1a15-7_copyright
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
@pombredanne Are you familiar with arpwatch, is this something that is widely used or reoccuring from some of the scans you've done?

**Comment by jlovejoy** [comment]
looks like this is functionally the same as BSD-4-Clause, but has some modifications in how the opening paragraph and conditions are expressed (which I don't think can be accommodated via matching guidelines)

The disclaimer is shortened, so that is a more significant change.

@winny - can you site other examples of project that use this?

**Comment by winny-** [comment]
@jlovejoy no, sorry, I believe arpwatch is alone in its adoption of this license.

**Comment by johnmhoran** [comment]
@swinslow I'll tackle this.

**Comment by swinslow** [comment]
Discussed on 2021-01-07 legal team all, agreed to add.

**Comment by jlovejoy** [comment]
@johnmhoran - will you be able to get to this one soon?

**Comment by johnmhoran** [comment]
@jlovejoy -- now that the Travis failures have been resolved, I will find time today (or over the weekend latest) to draft, push and open a PR for the .xml/.txt files.

The formatting of the [sample license text](https://metadata.ftp-master.debian.org/changelogs//main/a/arpwatch/arpwatch_2.1a15-7_copyright) is less than ideal -- subject to your guidance (@swinslow -- any thoughts as well?), I propose to format it like this:

```
License: BSD-4-Clause-Shortened

Redistribution and use in source and binary forms, with or without modification, are permitted provided that: 

(1) source code distributions retain the above copyright notice and this paragraph in its entirety, 
(2) distributions including binary code include the above copyright notice and this paragraph in its entirety in the documentation or other materials provided with the distribution, and 
(3) all advertising materials mentioning features or use of this software display the following acknowledgement:

"This product includes software developed by the University of California, Lawrence Berkeley Laboratory and its contributors.'' 

Neither the name of the University nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
```

Please advise if this is OK or if a different formatting is needed.
