### ISSUE TITLE
Dual license file format

### ISSUE THREAD

**Issue by ZhouJiatai** [spdx/license-list-XML#1091]
If my software source code is licensed under a dual license (e.g., MIT OR GPL-3.0-only). How to write a license file?

**Comment by swinslow** [comment]
Hello @ZhouJiatai, thank you for your question.

The SPDX project does not provide recommendations on how to write license files, or how to comply with particular license requirements.

However, the REUSE Software project (https://reuse.software), which builds on top of SPDX, does provide recommendations about how to structure repositories and license file texts within a project. You may want to review their specification and/or contact them with questions if it is unclear or if that is something that they can help address.
