### ISSUE TITLE
New license request: BSD-3-Clause-Modification

### ISSUE THREAD

**Issue by Moisan** [spdx/license-list-XML#1094]
Based on the license of `Supervisor`: https://salsa.debian.org/python-team/applications/supervisor/-/blob/debian/master/debian/copyright

It seems to be a BSD 3-Clause variant with an additional clause regarding modifications:
>  4.  If any files are modified, you must cause the modified files to
  carry prominent notices stating that you changed the files and
  the date of any change.

**Comment by chenrui333** [comment]
Any update on this thread? :)

**Comment by jlovejoy** [comment]
@Moisan - can you clarify where this license is used? I'm a little unclear on that. Is it only used on one project? (note, even if you don't use the Submit License tool - we still need the same info that form asks for, see https://tools.spdx.org/app/submit_new_license/ for reference :)
Thanks!

**Comment by Moisan** [comment]
I haven't seen it used in other projects but the [Fedora wiki list it as "Modification variant"](https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant). I will complete the missing information shortly, sorry about that.

**Comment by Moisan** [comment]
I cannot find any information regarding the license steward or author. What are our options at this point?

**Comment by jlovejoy** [comment]
ok, so, we did a big addition of licenses to the SPDX License List from the Fedora "good list" back in... 2013. I recall looking at this page with all the BSD variants on it, but I don't have any records of this one in particular.
Do you happen to know if it's used in Fedora today?

**Comment by jlovejoy** [comment]
(had wrong label. I suspect we won't find the steward on this one, as I think it's old??)

**Comment by Moisan** [comment]
This is the license in the [fedora package of Supervisor 4.2.1](https://koji.fedoraproject.org/koji/rpminfo?rpmID=24012723) and Fedora tagged it as "BSD and MIT".

**Comment by jlovejoy** [comment]
thanks for checking
yeah, Fedora categorizes permissive licenses that way, but we would give it its own identifier as per our matching guidelines

**Comment by swinslow** [comment]
agreed @jlovejoy, +1 to add

**Comment by swinslow** [comment]
Discussed 2021-02-18, agreed to add with identifier `BSD-3-Clause-Modification`

**Comment by johnmhoran** [comment]
I'll take this.

**Comment by swinslow** [comment]
use this as base text: https://fedoraproject.org/wiki/Licensing:BSD#Modification_Variant
