### ISSUE TITLE
Update inclusion principles to reflect intention of who applies the statement/license

### ISSUE THREAD

**Issue by vmbrasseur** [spdx/license-list-XML#1096]
We've just rejected two requests (#989 and #988) because they're things that can be applied retroactively by anyone (also they weren't licenses).

Intention of the text is that it will primarily be used by the creator/author of the work" or something like that. It'll take a bit to come up with the right wording here.

**Comment by jlovejoy** [comment]
These two examples were not licenses, hence not added to the SPDX License List. Question was whether we need an explicit statement that the SPDX License List is only for "licenses" which then might lead to defining a "license"

Considering that the License Inclusion Guidelines mention "license" over and over, this does not seem necessary.

**Comment by jlovejoy** [comment]
discussed on 17th Dec call - will leave as is and close issue

other points raised: License Inclusion Guidelines should not be edited ad hoc. They were the same for 7 years and then we took a long time to amend them. We probably want to continue with that level of care.
