### ISSUE TITLE
New license request: FAFOL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by agmlego** [spdx/license-list-XML#1098]
**1.** License Name: The Fuck Around and Find Out License v0.2
**2.** Short identifier: FAFOL
**3.** License Author or steward: boringcactus (Melody Horn)
**4.** Comments: FAFOL intends to be a license that clarifies the ground explored by the JSON license ("The Software shall be used for Good, not Evil.") by defining such terms as the domain of the author's discretion. It also furthers the concept of the SPDX-listed WTFPL while being a license that is not a hair's breadth away from being public domain. (further description from the author is at hir site https://www.boringcactus.com/2020/08/13/post-open-source.html#options)

At least one project is using this license (https://github.com/agmlego/pyNOVATime) though there are likely to be more over time as this is a very new license.
**5.** Standard License Header: 
**6.** URL: https://git.sr.ht/~boringcactus/fafol/tree/master/LICENSE.md
**7.** OSI Status: Not Submitted

**Comment by boringcactus** [comment]
oh hey, that's me! in case it helps, some additional information:
- the FAFOL v0.1 does also exist, and is more directly adapted from the JSON License, as opposed to v0.2 which is derived from the Blue Oak Model License. I'm not aware of anyone using v0.1 though.
- currently I have no plans to write a v0.3 of the license, but it is possible that I will eventually if there is some compelling reason to.
- the FAFOL v0.2 carries the spirit of the JSON License, the simplicity of the Blue Oak Model License, and the tone of the WTFPL, and so since each of those is included I believe the FAFOL can be too.
- I am *extremely* not a lawyer, this is absolutely a "crayon license," and even I am not currently using it for anything.

**Comment by swinslow** [comment]
Hi @agmlego, thanks for the submission -- and @boringcactus, thanks for the additional context as the license author!

In looking at whether or not to add a license to the [SPDX License List](https://spdx.org/licenses), we evaluate them in light of the [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). Here's my quick run-down of thoughts from holding those up to the FAFOL v0.2:

**Definitive factors**: The license does appear to meet all of these, with the note that it is not OSI-approved. Based on the current use of versioning and @boringcactus's comments above, I'm assuming for these purposes that the v0.2 text isn't planned to be modified (and that the version number would be bumped if it was).

**Other factors**: Given that, we look at the totality of the "other factors" listed in the inclusion principles:
1. From my reading, FAFOL v0.2 does _not_ substantially comply with the definitions listed here. In particular, the "Good, not Evil" requirement, combined with the primary contributors' discretion to determine its meaning and applicability, I expect would not meet the OSD or Free Software Definition if evaluated by OSI or FSF.
2. It is structured to be generally usable by anyone.
3. Based on what's shown here, it does not appear to have substantial use such that it is likely to be encountered in the wild. A search on Github shows a couple of projects using it and a couple using v0.1.
4. It does look like the license is primarily intended for free distribution of content, though the open-ended ethics statement (and particularly with the contributors' discretion to determine its scope) means that it's not really feasible to tell how limited or broad the restrictions might be in any given use.
5. Based on @boringcactus's comment, it looks like the license steward doesn't oppose its submission to the list.

For the "other factors", we look at them with a "totality of the factors" lens. Given that, based in particular on it not meeting factors 1 and 3, and the uncertainty around 4, I'm inclined to recommend that it should not be added to the License List at present. For licenses that don't meet one of the listed definitions (factor 1), we typically want to see greater evidence of broad use in the wild (factor 3). Some licenses such as [Hippocratic-2.1](https://spdx.org/licenses/Hippocratic-2.1.html) have been added on that basis, but in that case significantly greater usage was shown.

So my recommendation would be not to include it at present, but that it could be reconsidered in the future if the license shows significantly broader usage in the wild. Of course, I'm open to other thoughts from those in the SPDX legal community if they have a different view of applying the inclusion principles in this case!

**Comment by boringcactus** [comment]
yeah, the goal of versioning there was to ensure that "FAFOL v0.2" means the same thing from now until the end of time; if any future changes make sense to me, they'll go into a v0.3 of the license.

the FAFOL is a deliberate rejection of Freedom 0's "for any purpose". compliance with the OSD depends on whether or not evil is a "field of endeavor"; that's a question of philosophy more than anything, and an argument could be made that it is not (the Hippocratic License FAQ [makes a similar argument](https://firstdonoharm.dev/faq.html#doesn-t-the-hippocratic-license-violate-the-no-discrimination-and-fields-of-endeavor-terms-of-the-open-source-definition)), but the ensuing discussion would likely be unproductive and not resolve anything.

aside from that, i agree with your analysis. if i become aware of broader usage, i'll mention it here.

**Comment by agmlego** [comment]
Seems reasonable. To be honest, I mostly wanted it on SPDX because I already extensively use SPDX for other licenses, but I agree with the analysis thus far.

Thanks for the consideration!

**Comment by swinslow** [comment]
Thank you both!

@agmlego, for what it's worth, the [SPDX spec](https://spdx.github.io/spdx-spec/) defines a license identifier format that can be used for custom-defined licenses (e.g. those that aren't on the official [SPDX License List](https://spdx.org/licenses)). This is by using a "LicenseRef-" -- an identifier that starts with `LicenseRef-`, including the hyphen, followed by your choice of letters, numbers, `.` and `-`. Some examples of the format can be seen [here in the spec](https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/).

When using a LicenseRef- ID, it's of course necessary to indicate what license text that custom ID applies to. If you're looking for a semi-"official" way to do this, the [REUSE software](https://reuse.software/spec/) project has some recommendations on e.g. what to name license files and where to put them. But all of this might be more detail than what you're looking for  :)

Either way, thank you both for your feedback. I'll go ahead and close this issue, but feel free to reach out again if there is significant uptake of the license and you'd like to have it re-evaluated!
