### ISSUE TITLE
New license request: BAPL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by singerjoshua** [spdx/license-list-XML#1099]
**1.** License Name: Booz Allen Public License
**2.** Short identifier: BAPL
**3.** License Author or steward: Booz Allen Hamilton Inc.
**4.** Comments: 
**5.** Standard License Header: Unmodified Product Notice: “This software package is licensed under the Booz Allen Public License. Copyright © 20__ [Copyright Holder Name]. All Rights Reserved.”

Derivative Notice: “This software package is licensed under the Booz Allen Public License. Portions of this code are Copyright © 20__ [Copyright Holder Name]. All Rights Reserved.”
**6.** URL: https://github.com/boozallen/Public-License/blob/master/LICENSE.md
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Hi @singerjoshua, thanks for the submission.

In looking at whether or not to add a license to the [SPDX License List](https://spdx.org/licenses), we evaluate them in light of the [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). Here's my quick run-down of thoughts from holding those up to the BAPL text:

**Definitive factors**:
* The license does not appear to match another already on the license list.
* It is not OSI-approved.
* It covers the licensing of source code as well as object code / executables.
* It is not clear whether the license text is finalized, or whether it is being submitted on behalf of the license steward.
  * @singerjoshua, are you submitting this on behalf of Booz Allen? If so, are you able to confirm whether they are committed to not changing this version of the license in the future, and whether any future changes would be given a different version number?
  * I note that the license text itself contains a version number (v1.0). If it were accepted here, the version number would presumably need to be incorporated into the identifier on the license list for versioning purposes.

**Other factors**: Given that, we look at the totality of the "other factors" listed in the inclusion principles:
1. From my reading, BAPL does _not_ substantially comply with the definitions listed here. In particular, the license restrictions to internal business purposes / providing services to gov't / non-profits, and the prohibition on distribution for a fee, I expect would not meet the OSD or Free Software Definition if evaluated by OSI or FSF. See also [this comment in the BAPL repo](https://github.com/boozallen/Public-License/issues/1#issuecomment-717620877).
2. Although it is apparently structured to be generally usable by anyone, it contains explicit references and contact information for Booz Allen in the "Commercial Sales" section. The preamble also includes a service mark symbol (℠) for a phrase that appears to be a [corporate Booz Allen mark](https://www.boozallen.com/expertise/empower-people-to-change-the-world.html). This suggests that the primary intended use is for Booz Allen's own projects, not for general use by anyone.
3. The submission does not indicate details about use in the wild. A [search on Github](https://github.com/search?p=3&q=%22Booz+Allen+Public+License%22&type=Code) shows a significant number of files containing references to it (>600), though I haven't reviewed them closely to determine whether they are using this specific version of the text. Also, from a quick review it looks like many of these files are in the same handful of repos, and that they are Booz Allen's own projects.
  * @singerjoshua, do you have any details about projects other than those run by Booz Allen that are using this license?
4. It does look like the license is primarily intended for free distribution of content. However, the restriction on commercial use and distribution, or for use other than internal business purposes / services to gov't / non-profits, all cuts against this.
5. See question above about whether this was submitted on behalf of Booz Allen as the license steward.

For the "other factors", we look at them with a "totality of the factors" lens. Given that, based in particular on it not meeting factors 1 and 3, and the uncertainty around 2 and 4, I'm inclined to recommend that it should not be added to the License List at present. I expect that we would need to see much broader use in the wild by projects not affiliated with Booz Allen before it would meet factors 2 and 4 sufficiently to overcome the others. So my recommendation would be not to include it at present.

**Comment by jlovejoy** [comment]
+1 not appropriate to add. Notably, it has several references to Booz Allen within the license text, so I don't think it meets principle 2. There is also no info on why it should be added in the original submission (comments) and no follow-up. I'd suggest marking as "not accepted" and closing the issue.

**Comment by singerjoshua** [comment]
I apologize for our delayed response on this. Please go ahead and close the submission related to the BAPL as we are currently in the process of reevaluating it.

Thank you.

**Comment by jlovejoy** [comment]
@singerjoshua - thanks for the update, will do.
