### ISSUE TITLE
Review docs and update for new tools URL

### ISSUE THREAD

**Issue by vmbrasseur** [spdx/license-list-XML#1100]
>  A new URL for the SPDX online tools is now available at https://tools.spdx.org.  Please change any bookmarks or links from http://spdxtools.sourceauditor.com or http://13.57.134.254/app/ to https://tools.spdx.org.

Reference: https://lists.spdx.org/g/Spdx-legal/message/2865

**Comment by vmbrasseur** [comment]
Feel free to assign this one to me, @swinslow.

**Comment by swinslow** [comment]
Done, thank you @vmbrasseur!
