### ISSUE TITLE
New license request: Mohdhafis85 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mohdhafis322** [spdx/license-list-XML#1103]
**1.** License Name: Mohamad Hafis Mustapa
**2.** Short identifier: Mohdhafis85
**3.** License Author or steward: Mohamad Hafis bin Mustapa
**4.** Comments: Thanks for the guide
**5.** Standard License Header: SPDX
**6.** URL: http://www.swtnp.blogspot.com
**7.** OSI Status: Approved

**Comment by silverhook** [comment]
This is spam (checked the URL). Please close.
