### ISSUE TITLE
New license request: CC-BY-SA-2.0-UK [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by rpurdie** [spdx/license-list-XML#1106]
**1.** License Name: Creative Commons Attribution Share Alike 2.0 England and Wales
**2.** Short identifier: CC-BY-SA-2.0-UK
**3.** License Author or steward: 
**4.** Comments: 
**5.** Standard License Header: There is no standard license header for the license
**6.** URL: https://creativecommons.org/licenses/by-sa/2.0/uk/legalcode
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Hi @rpurdie, thanks for this! For the many combinations of translations / ports of CC licenses, the SPDX team's practice has typically been that particular translations might be considered for inclusion on the list, if there is evidence of their widespread use in practice. (This is also one of the factors that is looked at for all other licenses as well.) You can see a recent discussion of this at #931. 

Are there particular instances of CC-BY-SA-2.0-UK in use that you can point us towards, so the team can review and consider? Thanks!

**Comment by rpurdie** [comment]
Hi @swinslow, The reason for the request was that the Yocto Project documentation is under this license for historical reasons (it was originally created by a UK company). http://git.yoctoproject.org/cgit.cgi/yocto-docs We added SPDX headers, only to realise the license tag we used doesn't exist! We're therefore trying to reconcile that.

**Comment by swinslow** [comment]
Thanks @rpurdie! That's very helpful context to know.

Given the prominence of Yocto Project in various downstream distributions and projects / products (https://www.yoctoproject.org/ecosystem/yocto-project-compatible-product-showcase/ for instance, also use in AGL, etc.) I'd be in favor of adding CC-BY-SA-2.0-UK to the list.

@jlovejoy @pmadick @vmbrasseur @johnmhoran or others, would welcome your thoughts or a +1 on moving this forward. Thanks!

**Comment by rpurdie** [comment]
I should also mention that Yocto Project is trying hard to support and promote SPDX where we can, we understand the complexities of it and the need for standards like the license identifier. That is one reason we're trying to adopt that across all our repositories.

The documentation in question has been evolving for about 15 years and predates the existence of Yocto Project! Its a huge and important reference for all things Yocto Project having been maintained by a full time tech writer for much of the last decade. We've just completed a migration from docbook to sphinx and you can view the output at https://docs.yoctoproject.org/. The ~80 previous releases are here: https://docs.yoctoproject.org/releases.html#previous-release-manuals

The choice of license perhaps isn't what we'd choose today but 15 years ago it seemed like a good choice. We'd like to showcase using SPDX properly/well!

**Comment by swinslow** [comment]
Thanks @rpurdie! I'll be bringing this up on today's SPDX legal team call, and will circle back afterwards.

**Comment by swinslow** [comment]
Discussed on 2020-10-22 legal team call, agreed to add.
