### ISSUE TITLE
New license request: ASC-X12 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by sambacha** [spdx/license-list-XML#1107]
**1.** License Name: Accredited Standards Committee X12
**2.** Short identifier: ASC-X12
**3.** License Author or steward: X12.org
**4.** Comments: I am submitting this by my own accord, I am not acting on behalf of X12.org nor represent them in any capacity.
**5.** Standard License Header: Accredited Standards Committee X12 (#transaction_set), [#transaction_version]. X12 Incorporated, [MM YY]. <http: //www.x12.org>. "X12 has granted express permission for use of X12 copyrighted materials within this document."
**6.** URL: https://x12.org/products/licensing-program
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Original submission w/ original license text is at https://tools.spdx.org/app/archive_requests/81/

**Comment by emmanueltournier** [comment]
Here

**Comment by emmanueltournier** [comment]
@swinslow . Note sure I will be able to attend our meeting tomorrow so here are my comments: I looked at the X12.org website, more specifically at this page: https://x12.org/products/ip-use . I could not find any identifiable license text, or evidence that their work is available under an open-source license. The "licensing program" page decribes a bunch of commercial options to participate and/or use the X12 standards. For those reasons I don't think this request meets our acceptance criteria.

**Comment by swinslow** [comment]
Thanks @emmanueltournier! Agreed, this appears to be a commercial / proprietary licensing program that doesn't fit with the SPDX inclusion principles, agreed that this should not be added.
