### ISSUE TITLE
Alter 'new license request' template to better reflect inclusion principles? 

### ISSUE THREAD

**Issue by vmbrasseur** [spdx/license-list-XML#1108]
The current 'new license request' issue template (by way of tools.spdx.org, I believe) has these fields:

> 1. License Name: 
> 2. Short identifier: 
> 3. License Author or steward: 
> 4. Comments: 
> 5. Standard License Header: 
> 6. URL: 
> 7. OSI Status: 

It may make sense to evolve this template a bit to include more of the information needed for the inclusion principles. For instance, maybe add a field for listing example projects using the license.

What do folks think of reconsidering the fields on this template?

**Comment by goneall** [comment]
This would be an ideal time to improve the template.  We are currently testing a new implementation at http://52.32.53.255/app/

If there is consensus to add new fields, please open an issue on the [SPDX online tools repo issues list](https://github.com/spdx/spdx-online-tools/issues)

**Comment by swinslow** [comment]
Big +1 from me, in particular listing example projects using the license -- that's almost always my first question back to the requester.

I filed https://github.com/spdx/spdx-online-tools/issues/240 at @goneall's request, will close this issue and we can discuss over there.
