### ISSUE TITLE
New license request: CDL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by shujisado** [spdx/license-list-XML#1109]
**1.** License Name: Common Documentation License v1.0
**2.** Short identifier: CDL-1.0
**3.** License Author or steward: Apple Computer, Inc.
**4.** Comments: I remember it being a rather common license before Creative Commons was invented.
**5.** Standard License Header: 
**6.** URL: https://fedoraproject.org/wiki/Licensing/Common_Documentation_License
**7.** OSI Status: Not Submitted

**Comment by RishabhBhatnagar** [comment]
I would like to work on this issue.

**Comment by RishabhBhatnagar** [comment]
Hello @shujisado, thanks for the new license request. Can you provide examples or URLs for projects where this license is or was used?

For a license to be included in the spdx license list, it should have actual, substantial use, as described by the Third point under the `Other Factors` subsection of the [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md).

**Comment by shujisado** [comment]
http://dutchroll.sourceforge.net/manual.html

I can't find much.  I think there used to be some projects that used Apple's CDL, but I guess it's true that it's almost non-existent these days. The above URL was easy to find, though.

**Comment by jlovejoy** [comment]
considering this is a really old license and doesn't appear to have much use, I tend to think it's not that useful to add

**Comment by jlovejoy** [comment]
would be helpful to know if this is still used in Fedora - if yes, then that would point to adding it. Need to research that.

**Comment by swinslow** [comment]
From a quick search of the old URL for the license, found a few examples of use in practice:

- https://mirror.informatimago.com/next/developer.apple.com/documentation/Darwin/Conceptual/howto/packaging_unix_for_darwin/packaging_unix_for_darwin.html (docs originally from Apple)
- http://mirror.informatimago.com/next/developer.apple.com/documentation/Darwin/Conceptual/howto/building_xnu/building_xnu.html (docs from non-Apple)
- http://tidy.sourceforge.net/docs/Tidy_HOWTO_Template.html (docs from W3C)

**Comment by jlovejoy** [comment]
discussed on April 15th call - decided to add. even though it's old, it's on the Fedora Good list and FSF list. It's not clear if it's still used in Fedora, but given the totality, we will add.

@shujisado - can you prepare the PR to add this?  See https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md for instructions. If you can add it in the next couple weeks, then it will be part of the next release, 3.13, at the end of April.

**Comment by jlovejoy** [comment]
ping @shujisado - do you think you will be able to make the PR for this in the next couple days for the 3.13 release? Otherwise, we'll move it to the 3.14 release.

**Comment by shujisado** [comment]
It looks like I need to prepare an XML file with the license information and a TXT file with the license text. I haven't read the documentation exactly, so I think this process will take a few days.

**Comment by jlovejoy** [comment]
ok, thanks! I'll leave it as 3.13 until we actually do the release just in case (and since we are running late)

**Comment by seabass-labrax** [comment]
Hello! I volunteered to create the pull request at today's Legal Team meeting, in the hope that it might be included in time for the 3.13 release :)
