### ISSUE TITLE
New license request: OPUBL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by shujisado** [spdx/license-list-XML#1110]
**1.** License Name: Open Publication License v1.0
**2.** Short identifier: OPUBL-1.0
**3.** License Author or steward: Open Publication
**4.** Comments: I remember it being a rather common license before Creative Commons was invented.
**5.** Standard License Header: 
**6.** URL: http://opencontent.org/openpub/
**7.** OSI Status: Not Submitted

**Comment by RishabhBhatnagar** [comment]
Let me tackle this issue.

**Comment by RishabhBhatnagar** [comment]
We do have a huge number of projects in the wild that uses this license. From a quick scan, it doesn't look similar to any other license. I'm not sure about the legal terms of this license text but it matches the License Inclusion Guideline and we might add this to our license list.

**Comment by jlovejoy** [comment]
As discussed on Feb 4th call: Inclined to add license as is.
Note: The license text has two options to add restrictions. Should we add these options as well or wait until that is separately requested?
If use of additional restrictions in wild, then that would point to adding all three variants??

**Comment by jlovejoy** [comment]
that note was not clear: action item here is to do a bit of research to see if the additional restrictions have actual use in the wild. (if not, then add as default license)

**Comment by swinslow** [comment]
I'd lean towards add as-is as a standard license identifier, and then if people request additional identifiers later for the optional restrictions, then at that point we can add them.

**Comment by jlovejoy** [comment]
discussed on April 15th call - decided to add as is, as per @swinslow comment

@shujisado - can you prepare the PR to add this? See https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md for instructions. If you can add it in the next couple weeks, then it will be part of the next release, 3.13, at the end of April.

**Comment by jlovejoy** [comment]
ping @shujisado - do you think you will be able to make the PR for this in the next couple days for the 3.13 release? Otherwise, we'll move it to the 3.14 release.

**Comment by seabass-labrax** [comment]
Hello @shujisado! Having created the XML and text files for `CDL-1.0`, I'm also happy to do the same for `OPUBL-1.0`. Unless you'd particularly like to make the pull request, I'll start work on this in a few days :)

**Comment by seabass-labrax** [comment]
I've created the XML and text files in pull request #1276. Thanks for taking the time to open this issue, @shujisado! :)
