### ISSUE TITLE
New license request: nmap [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jonchang** [spdx/license-list-XML#1113]
**1.** License Name: Nmap Public Source License
**2.** Short identifier: nmap
**3.** License Author or steward: The Nmap Project
**4.** Comments: Nmap is a commonly used suite of security software.

As the Fedora project notes, the license is GPL-derived, but with substantial changes that make the interpretation substantially different:

> The nmap software contains a combination of the GPL, LGPL and BSD licenses, and does so in a way that adds very specific interpretations and exceptions to the GPL. As a result, it cannot be treated as if it were simply the GPL. This new license is sufficiently more restrictive, and is GPL-incompatible as a result (although, still Free). 

https://fedoraproject.org/wiki/Licensing/Nmap
**5.** Standard License Header: 
**6.** URL: https://svn.nmap.org/nmap/COPYING
**7.** OSI Status: Not Submitted

**Comment by karsten-klein** [comment]
Duplicate: check out #1121

**Comment by swinslow** [comment]
Thanks @karsten-klein! Closing this one and we can review the other submission in #1121 where you've already added comments.

**Comment by karsten-klein** [comment]
By now a 0.93 is available.

The diff:

![image](https://user-images.githubusercontent.com/20038021/105514874-4bd4ee00-5cd4-11eb-9b6f-9c73ad3d96b0.png)

So only version number and preamble have changed. So the change is not really on the terms and conditions, but rather informative.

I suggest to add both version as NPSL-0.92 and NPSL-0.93

Cheers,
Karsten
