### ISSUE TITLE
Typo in AGPL-3.0

### ISSUE THREAD

**Issue by spoenemann** [spdx/license-list-XML#1115]
License comparison, e.g. with `LicenseCompareHelper`, does not work for AGPL-3.0. The issue is an extraneous space in the word "sue" in line 179 of the template. The full statement containing the misspelling is as follows:

> such as an express permission to practice a patent or covenant not to s ue for patent infringement

I could find this problem in several files in this repository (templates and test files) by searching for "s ue for patent infringement".

**Comment by swinslow** [comment]
Good catch @spoenemann -- and thanks @goneall for already submitting a PR to fix this! I'll go ahead and merge it.

@spoenemann note that this will not update it on the [SPDX License List website](https://spdx.org/licenses) until the next license list release.

**Comment by spoenemann** [comment]
Thanks!
