### ISSUE TITLE
New license request: NPSL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by dcantrell** [spdx/license-list-XML#1121]
**1.** License Name: Nmap Public Source License Version 0.92
**2.** Short identifier: NPSL
**3.** License Author or steward: Gordon Lyon
**4.** Comments: There does not appear to be a standard license header block, but the nmap source code does have one it uses consistently across files.  The license is described as based on the GPL version 2.0 but with additional clarifications.  The license does not appear on the OSI list of approved licenses.

The Fedora Project has an analysis of the nmap license here:  https://fedoraproject.org/wiki/Licensing/Nmap
Of note here is that Fedora considers the license free, though GPL-incompatible.

Lastly, I put the main author of nmap as the license steward, but I cannot confirm that.  I have not actually talked to him about that.  Nmap is from Insecure.Com LLC, so that might be a better option.  Happy to help track this down and clarify things.

I suggest NPSL as the short identifier because that's what it's called in the nmap LICENSE file and by their own URL.  The license is versioned, so maybe the short identifier needs a version as well to handle future changes to the license.
**5.** Standard License Header: 
**6.** URL: https://nmap.org/npsl/npsl-annotated.html
**7.** OSI Status: Not Submitted

**Comment by karsten-klein** [comment]
Hi all,

here the results of my review:

License Inclusion Principles
- the definitive factors are addressed
- The other factors are not quite addressed. I.e. the license only applies to a given set of tools and data. Per definition the licensor is "Insecure.Com LLC and its successors and assign". A substantial use is also not monitored. Nevertheless, nmap may be regarded significant enough to add the license.

Proposed next steps:
- decide on inclusion in SPDX (I vote for yes)
- conditional: contact license steward and request commitment
- conditional: create PR

Revised attributes (see also #1113):
1. License Name: Nmap Public Source License 0.92 (change: omitted 'Version' as this is redundant; v0.92 may be an option)
2. Short identifier: NPSL-0.92 (change: added version information)
3. License Author or steward: TBD
4. Comments: There does not appear to be a standard license header block, but the nmap source code does have one it uses consistently across files. The license is described as based on the GPL version 2.0 but with additional clarifications. The license does not appear on the OSI list of approved licenses.
5. Standard License Header: <request from license steward>
6. URL: https://nmap.org/npsl/ (change: page contains backgrounds on the license; other links are easy to navigate)
https://nmap.org/npsl/npsl-annotated.html (for backgrounds)
https://svn.nmap.org/nmap/LICENSE (for the raw license text)
7. OSI Status: Not Submitted

**Comment by 9ary** [comment]
> The Fedora Project has an analysis of the nmap license here: https://fedoraproject.org/wiki/Licensing/Nmap
> Of note here is that Fedora considers the license free, though GPL-incompatible.

Just a note, this is about the old nmap license, here's Fedora's statement on this new one: https://www.mail-archive.com/devel-announce@lists.fedoraproject.org/msg02463.html.

**Comment by swinslow** [comment]
Hi @karsten-klein, thanks for your writeup - and @9ary, thanks for the additional updated link.

I agree with @karsten-klein's comments and I am a +1 on including this. I recognize from the Fedora discussion that there are reasons to think that this version likely would not meet the open source definitions, and also that the license is limited to nmap alone. However, I would say that [nmap is widely enough used](https://en.wikipedia.org/wiki/Nmap) that I think the balance tilts slightly in favor of including it.

Open to input from other legal team contributors -- @jlovejoy in particular, feel free to weigh in here.

**Comment by karsten-klein** [comment]
By now a version 0.93 is available.

The diff:

![image](https://user-images.githubusercontent.com/20038021/105516183-de29c180-5cd5-11eb-9177-31bc00ac4d29.png)

I propose to add both as NPSL-0.92 and NPLS 0.93.

Cheers,
Karsten

**Comment by jlovejoy** [comment]
Should this be added as an exception? It included GPL-2.0 in the Exhibit and states that it modifies those terms. 
note:
"Covered Software is licensed to you under the terms of the GPL (Exhibit A), with all the exceptions, clarifications, and additions noted in this Main License Body. Where the terms in this Main License Body conflict in any way with the GPL, the Main License Body terms shall take precedence. These additional terms mean that You may not distribute Covered Software or Derivative Works under plain GPL terms without special permission from Licensor."

**Comment by karsten-klein** [comment]
Hi Jilayne,

I’d argue that this case is very different. I’d regard this license as an own license. It just builds on GPL.

Cheers,
Karsten

**Comment by jlovejoy** [comment]
probably a good one to discuss on next call!

**Comment by jlovejoy** [comment]
discussed on Feb 18th legal call - see minutes
this raises a couple broader questions: is this an exception and if it doesn't fit on the exception list, should it be added as a full license, even though it incorporates the full text of an existing license (which then circles back to the license inclusion guidelines) 
more discussion needed on broader question to be done on mailing list, will leave this marked as "needs discussion" in meantime

**Comment by swinslow** [comment]
Discussed on 2021-04-15 call, not currently inclined to add 0.92 because of changes in text / restrictions as well as their apparent move to 0.93. 

Would be more inclined to add the old NMAP license at https://fedoraproject.org/wiki/Licensing/Nmap which appears to still be in use for the version of Nmap that is in Fedora now.

Closing this issue, but if there is a desire to add the old NMAP license, and/or to submit the 0.93 license for review, those can be submitted as issues for review.

**Comment by ataraxus** [comment]
Sorry for commenting on this old issue, but i wasnt able to find the NPSL or NMAP License in recent releases. After reading this issue i would have assumed it was included? I'm using Dependency Track which includes version 3.22 of this list. 

Maybe you could advise me? @swinslow

**Comment by ataraxus** [comment]
@swinslow thanks. I submitted an issue.
