### ISSUE TITLE
New license request: syncfusion [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by alamegoMS** [spdx/license-list-XML#1130]
**1.** License Name: Syncfusion commercial license
**2.** Short identifier: syncfusion
**3.** License Author or steward: syncfusion
**4.** Comments: Submitting this license as a consumer. 
Me or my organization (Microsoft) are not authors of this license.

I am not clear on the OSI status.
**5.** Standard License Header: This is a commercial product and requires a paid license for possession or use. Syncfusion’s licensed software, including this component, is subject to the terms and conditions of Syncfusion's EULA (https://www.syncfusion.com/eula/es/). To acquire a license, you can purchase one at https://www.syncfusion.com/sales/products or start a free 30-day trial here (https://www.syncfusion.com/account/manage-trials/start-trials).

A free community license (https://www.syncfusion.com/products/communitylicense) is also available for companies and individuals whose organizations have less than $1 million USD in annual gross revenue and five or fewer developers.
**6.** URL: https://www.syncfusion.com/content/downloads/syncfusion_license.pdf
**7.** OSI Status: Not Submitted

**Comment by silverhook** [comment]
Is this about the commercial or the community license?

In either case, it seems to me that both are neither FOSS, nor wide-spread enough to warrant being added to the SPDX License List.

If you need an SPDX identifier, you can simply prepend the `LicenseRef-` prefix like e.g. `LicenseRef-Syncfusion-commercial` and `LicenseRef-Syncfusion-community`.

**Comment by swinslow** [comment]
Agreed with @silverhook, discussed on 2020-12-17 legal team call, this appears to be a company's own custom license for their products and doesn't warrant inclusion on the license list.
