### ISSUE TITLE
Add docs or website details re: LicenseRef-

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1131]
There are some instances where submitted licenses are not appropriate for inclusion on the SPDX License List, but where users of SPDX could still represent those licenses via their own custom LicenseRef- ID's.

It would be great to add some language clarifying this process, either to the docs in this repo and/or on the spdx.dev website, so that we can point people to that when closing the issue so that they have more of an understanding what to do next.

**Comment by jlovejoy** [comment]
see #1250 - @swinslow - is this what you had in mind?

(separately, but related, should we add a similar statement to the IDs webpage and Appendix?)

**Comment by swinslow** [comment]
Merged in #1250, closing
