### ISSUE TITLE
New license request: C-UDA-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jeanm** [spdx/license-list-XML#1133]
**1.** License Name: Computational Use of Data Agreement v1.0
**2.** Short identifier: C-UDA-1.0
**3.** License Author or steward: Microsoft Open Data Campaign
**4.** Comments: The license was released by Microsoft's Open Data Campaign on 2019-11-07. I am not affiliated with them.

This license is becoming quite popular for academic datasets which are distributed alongside software. It allows researchers to use data for computational purposes (e.g. to train artificial intelligence / machine learning systems), and does not impose any restriction on the results. The data itself can be modified and redistributed under the same terms.

An example of why this license is so useful. For a research project I needed to use the text of several books. The publisher was willing to let me do that, but didn't want me releasing the data into the public as they were afraid a competitor might take the text and start printing their own editions of those books. By suggesting the use of this license, I was able to solve their concerns.

Examples of projects using this data:
* WLASL dataset, best paper honorable mention at WACV 2020: https://dxli94.github.io/WLASL/
* SLNSpeech dataset: http://cheertt.top/homepage/
* Microsoft American Sign Language Dataset: https://msropendata.com/datasets/edbe743b-2d96-4673-8f18-98c87bb26283
* Microsoft Speech Corpus for Indian Languages: https://msropendata.com/datasets/7230b4b1-912d-400e-be58-f84e0512985e
* Many other projects on the Microsoft Research Open Data repository: https://msropendata.com/datasets?sort=lastModified
**5.** Standard License Header: 
**6.** URL: https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md
**7.** OSI Status: Not Submitted

**Comment by jlovejoy** [comment]
Looks similar to https://spdx.org/licenses/O-UDA-1.0.html
@mlinksva - do you have any thoughts on this, since you requested O-UDA-1.0?

**Comment by swinslow** [comment]
cc @royaljust also for weighing-in, as Microsoft is license steward for the O-UDA and C-UDA licenses.

**Comment by mlinksva** [comment]
I don't really remember, but perhaps I didn't submit C-UDA-1.0 at the same time because I wasn't sure whether it qualified for inclusion. I know the inclusion principles were updated earlier this year, though I didn't follow that discussion, so maybe C-UDA-1.0 does qualify now. If so, this submission looks pretty similar to #951 so should be good to go.

Which are the current inclusion guidelines? I see https://spdx.dev/license-list/#:~:text=License%20Inclusion%20Principles which looks different from both current(?) and historical versions in https://github.com/spdx/license-list-XML/blob/d78ad74d106a3ada7aca3cbcbe111a1c48cdb045/DOCS/license-inclusion-principles.md

**Comment by jlovejoy** [comment]
@mlinksva - yeah, so, we are in the midst of updating links, which you discovered! (I just made a PR to do so #1135 )

The updated license inclusion principles are here: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md

**Comment by mlinksva** [comment]
> If the license does not substantively comply with one of the above open source definitions, then the license is primarily intended for free distribution of content (including, in the case of software, its source code) with limited restrictions, and meets other factors listed here.

I'm not certain what "with limited restrictions" applies to--distribution? C-UDA-1.0's restrictions that go beyond those typically found in open licenses are on use, not distribution, so I guess it qualifies?

**Comment by jlovejoy** [comment]
Thanks for the analysis, @swinslow 
Given the totality of the factors, I agree this weighs in favor of adding.

**Comment by swinslow** [comment]
Discussed on 2021-02-18 legal team call, no objections, agreed to add.
