### ISSUE TITLE
New license request: OPNL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Mentors4EDU** [spdx/license-list-XML#1134]
**1.** License Name: Open Innovation License
**2.** Short identifier: OPNL
**3.** License Author or steward: Stark Drones Corporation, Andrew Magdy Kamal
**4.** Comments: If you need anything, let me know and I will get back to you right away.
**5.** Standard License Header: 
**6.** URL: https://github.com/StarkDrones/OPNL/blob/main/LICENSE.md
**7.** OSI Status: Pending

**Comment by jlovejoy** [comment]
@Mentors4EDU - is this license actually in use? It's labeled as a proposal.

Please see https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md and comment as to how you think it meets the guidelines.

Also, you might want to consider a different acronym - OIN stand for the well-known patent pool for open source, the Open Innovation Network https://openinventionnetwork.com/  (in case you didn't realize)

**Comment by Mentors4EDU** [comment]
1) Hi, regarding your inquiry, they are a network/license agreement. I was going to do "OIL" but oil is a commodity and a word, therefore I thought that would be a bad idea for a license acronym and may also present unwarranted liabilities since OIL is a commodity. I also thought of OINN but thought two Ns would be more confusing, and I still think OIN should work for now.
2) Yes, the license is technologically agnostic and supports the principals behind open source software.
3) I used the word proposal given this is a new repo for the license but I have a community of over 200k developers, and also blog on Hackernoon. I have a general idea of how I'm going to garnish massive adoption and my corporation needed something like this prior for hybrid open hardware offerings. I thought it was best to get this listed on SPDX, Choose a license, and some FOSSA directories so that when people use it, the symbol in their config files is recognized by their package managers since I know lots of package managers use SPDX and such, and it is easier to get it recognized by the package managers and directories first for sake of simplicity.

**Comment by swinslow** [comment]
Discussed on 2020-12-17 legal team call, further comments to follow.

**Comment by Mentors4EDU** [comment]
> Discussed on 2020-12-17 legal team call, further comments to follow.

Thanks for the update.

**Comment by Mentors4EDU** [comment]
Hi, we have changed the identifier to OPNL to avoid any mix up w/ the Open Innovation Network as per your suggestion.

**Comment by jlovejoy** [comment]
@Mentors4EDU - good call on the identifier change as well.

I also see that you have submitted it to the OSI and there has been much discussion. In this kind of situation, we usually wait for that process to roll out for at least a couple reasons:
1) if OSI approves a license and adds it to their list, we generally add it to the SPDX License List 
2) license often get revised in the OSI approval process (and look like that may be the case here as well)

Note: if 2 happens, please keep in mind differentiating any original version that may be in use versus any new version you publish (this has been a big challenge in the past, so a word of prevention, if I may!) 

Disclaimer: I don't closely follow the OSI-license list, but happen to see this. Please do keep us posted if/when you reach a conclusion there, so we can pick this back up. I'll mark it as on-hold in the meantime.

Thanks!

**Comment by Mentors4EDU** [comment]
Hi @jlovejoy , the OSI list is kind of iffy. I withdrew my submissions for approval and instead submitted it to the **Open Knowledge Foundation** [here](https://discuss.okfn.org/t/license-approval-request-open-innovation-license-opnl-and-opnl-2-0/10134).

There was much debate mainly centered around having ethical statements in open source licenses. This has been done in the past, and I believe is one of the reasons between the Free Software Foundation vs. OSI feud, see [here](https://www.gnu.org/philosophy/free-software-for-freedom.en.html). The argument I believe was more centered towards whether or not you can have an ethical clause, if that ethical clause wasn't legally binding, or is there a thing called morally binding?

I had two counter arguments for this:
1. If the whole document is legally binding as a whole, even though I put a clause for the ethical statement, then the ethical statement isn't morally or legally restrictive. The reason being is the usage of "agrees at goodwill", which is subjective. Given human's free will capabilities, this means that technically an evil person wouldn't be restricted by this license. This is a thing I pointed out. They still didn't like the usage of agreement.
2. Version 2 was revised, and I feel as the consensus was heavily against version 1, that after spending nearly half a day of my corporate time working on a revised variation, I was barely able to seek out feedback for version 2. I decided to withdraw version 2 from the OSI board as well. Version number 2 attempts to solve the same mission statement as version 1, the only major difference is slightly simplified wording and I put my mission statement under a preamble w/ my corporate entity agreeing too it, so it removes any "asking you to agree" argument. Though, I still believe version 1 still has all its full merits of being within the full definition of open source and free software in my opinion.

Anyways many of the arguments centered against it were logical paradoxes and strawman statements. People even seemed to insinuate that the restriction now applies to myself and since version 2 makes me agree to my mission statement, that also would go against free and open source software. There was arguments on Amish people and them deciding what is ethical or not according to their believes, or examples of Chinese dissent or communist governments. If they applied the same rules to a variety of their licenses, a very slim amount of their open source licenses wouldn't be on their website. 

The idea of needing to censor a non-discriminatory ethical statement w/ illogical what ifs like what if somebody evil or wanting to build technology that commits genocide wants to use this license, doesn't this discriminate against their endeavor, is the definition of irrationality.

Anyways, I basically got a severe headache of going back and forth. They then made the argument that if I continue the thread, I might not be taking into consideration _respect to time for the team members_ which goes against their code of conduct. However, I only primarily emailed back and forth to respond with counterclaims in regards to the merits of my license. I felt regardless, my consensus didn't matter and if the license went to the approval board they would vote against it. Therefore, I withdrew my request by default.

I have henceforce, submitted to the OKF to see what they think. Outside of that strange exchange of events, the people who have been using this license like many of the ethical concepts, premise and the idea of talking about ethics more in open source and technology. Alot of people started adapting it and yesterday I just decided to also create an NPM package for it. I think many people in the open source movement are missing the mark when looking at how companies that are hailed as heroes of open source go against fair use, the Right to Repair Act, and privacy rights. Some big entities that do these things offload negative attention by sponsoring different open source software packages. I feel like this is where open source misses the mark, and that freedom and open source redistribution can be in harmony without really logically restricting anybody.

Anyways, I will see what OKF and other people say. It usually can take a few month to go through the approval process, but I'm hoping if possible that it wouldn't take too long. Without an SPDX identifier, lots of people find it difficult to add OPNL and OPNL-2 to their repos because it isn't detecting through the NPM terminal or interfaces so they have the force push it. I do believe that these two licenses fall within the definition and philosophy of open source. Even if it may take OSI a while to adapt the concept behind this because it is a bit new, I feel like the decision shouldn't be centralized based off how a few board members vs. the entire open source community feels about it.

**Comment by Mentors4EDU** [comment]
Anyways, I hope the above statement hopefully answers any concerns you have in regards to my due diligence for these licenses so far.

**Comment by jlovejoy** [comment]
This was discussed on the legal call. Here is a summary, as per the license inclusion guidelines:

Definitive factors: The license appears to meet most of these, with the note that it is not OSI-approved and given there is already a v2, the author seems to understand the importance of versioning of licenses. 

Other factors: Given that, we look at the totality of the "other factors" listed in the inclusion principles:
1) v1 does not substantially comply with the definitions listed here. The last two paragraphs create a restriction on usage. Also, the discussion on the OSI mailing list raised concerns as to this license (which resulted in v2). It doesn’t seem to have support with the Open Knowledge Foundation either.
2) It is structured to be generally usable by anyone.
3) Based on a search for the license in Github, only a couple other people/projects are using the license besides the author. (Note: planned or hoped-for use is not actual use :)
4) It does look like the license is primarily intended for free distribution of content, though the open-ended ethics statement means that it's not really feasible to tell how limited or broad the restrictions might be in any given use.
5) it was submitted by the license steward

Given that the license does not meet factors 1 and 3, and the uncertainty around 4, we don’t think it should be added to the License List.
