### ISSUE TITLE
MPL 2.0 and MPL 2.0 no copyleft have the same text

### ISSUE THREAD

**Issue by sebbonnet** [spdx/license-list-XML#1138]
Both `MPL-2.0` and `MPL-2.0-no-copyleft-exception` licence files have the same content which makes it impossible to differentiate between them when using automated tool to check licences in third party libraries.

Looking at the Mozilla [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/), it is not clear how to differentiate the two.
Q25 FAQ does mention that Exhibit A should prevail when using a full MPL 2.0 licence, but not how the licence should look like when Exhibit B should prevail.  

Notes on SPDX for the [MPL-2.0-no-copyleft-exception](https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html) suggests however that 3.3 section should be removed.
> This license was released in January 2012. This license list entry is for use when the MPL's Exhibit B, which removes the Sec 3.3 copyleft exception.

Shouldn't the 2 licences text have different content?

**Comment by jlovejoy** [comment]
Yes, the license text is the same, but the different options in the exhibits create different license obligations.
That being said, it looks like the exhibits are also the same... I will look more closely at this, as we may have introduced a mistake on this somewhere along the lines

**Comment by jlovejoy** [comment]
see PR #1179

**Comment by swinslow** [comment]
Merged, thanks all!
