### ISSUE TITLE
Reconcile names of Open Data Commons’ licenses

### ISSUE THREAD

**Issue by silverhook** [spdx/license-list-XML#1139]
We currently include all three of the Open Data Commons licenses:

- ODC Open Database License v1.0 (ODbL-1.0)
- Open Data Commons Attribution License v1.0 (ODC-By-1.0)
- ODC Public Domain Dedication & License 1.0 (PDDL-1.0)

At a first glance, one would not realise these are all three of the same origin or in any way related – especially between the _ODbL-1.0_ and _ODC-By-1.0_.

The (long) names on their [official website](https://opendatacommons.org/licenses/index.html) are also somewhat different:

- Open Data Commons Open Database License (ODbL) — “Attribution Share-Alike for data/databases”
- Open Data Commons Attribution License — “Attribution for data/databases”
- Open Data Commons Public Domain Dedication and License (PDDL) — “Public Domain for data/databases”

It might make sense to reconcile the names of ODC licenses to be more similar. At the very least to decide whether the long names are “Open Data Commons *” or “ODC *”. The mix we currently have is suboptimal.

**Comment by jlovejoy** [comment]
I'm fine with amending long names, so long as the short identifiers remain the same. I think that is what you are proposing, correct? @silverhook

**Comment by jlovejoy** [comment]
see PR #1181

**Comment by silverhook** [comment]
Sorry for the late reply. Yeah, I think amending the long names is enough. Changing short names might brake things.
