### ISSUE TITLE
New license request: EDL 1.0

### ISSUE THREAD

**Issue by rvsoni** [spdx/license-list-XML#1149]
1. License Name: Eclipse Distribution License - v 1.0
2. Short identifier: EDL 1.0
3. License Author or steward: Eclipse Foundation
4. Comments: 
5. Standard License Header:
6. URL: https://www.eclipse.org/org/documents/edl-v10.php
7. OSI Status: Yes

Following libraries are using it,
1) https://mvnrepository.com/artifact/com.sun.activation/jakarta.activation/1.2.1
2) https://mvnrepository.com/artifact/jakarta.activation/jakarta.activation-api/1.2.1

**Comment by swinslow** [comment]
Hi @rvsoni, thanks. This is identical to [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) when the [SPDX matching guidelines](https://spdx.github.io/spdx-spec/appendix-II-license-matching-guidelines-and-templates/) are taken into account.

That means we won't add a separate entry for the Eclipse Distribution License. The appropriate SPDX identifier to use for this is `BSD-3-Clause`.

**Comment by zvr** [comment]
Please also see #1683
