### ISSUE TITLE
New license request: CC-BY-SA-2.1-JP

### ISSUE THREAD

**Issue by mandel59** [spdx/license-list-XML#1155]
1. License Name: Creative Commons Attribution-Share Alike 2.1 Japan
2. Short identifier: CC-BY-SA-2.1-JP
3. License Author or steward: Creative Commons
4. Comments: The List of MJ Characters, one of fundamental data for Japanese text processing in Japan, is licensed under CC-BY-SA-2.1-JP. Some open data are also available under CC-BY-SA-2.1-JP.
5. Standard License Header: 
6. URL: https://creativecommons.org/licenses/by-sa/2.1/jp/legalcode
7. OSI Status: Not Submitted

**Comment by mandel59** [comment]
Example project URLs
- MJ文字情報一覧表 (The List of MJ Characters) <https://moji.or.jp/mojikiban/mjlist/>
- 塙町オープンデータ利用規約 (Hanawamachi Open Data Terms of Use) <http://www.town.hanawa.fukushima.jp/page/page001231.html>

**Comment by mandel59** [comment]
License Text: https://gist.github.com/mandel59/527db04e7655f28edb0e8db2bda7c328#file-gistfile1-txt

**Comment by swinslow** [comment]
Thanks for submitting this, @mandel59! 

Do you have an updated URL for the List of MJ Characters site that you linked to? I am getting a 502 Bad Gateway error when visiting https://moji.or.jp/mojikiban/mjlist/

**Comment by mandel59** [comment]
Maybe temporary unavailability? I can browse the linked page currently.

**Comment by swinslow** [comment]
It must have been -- I can view it now. Thank you!

**Comment by swinslow** [comment]
Discussed on legal team call 2021-03-04, agreed to add. @swinslow to prepare the PR.
