### ISSUE TITLE
Update BSD-3-Clause to allow matching to the included text

### ISSUE THREAD

**Issue by daeatough** [spdx/license-list-XML#1157]
**1.** License Name: V8 Project License
**2.** Short identifier: V8
**3.** License Author or steward: Google V8 Project Team
**4.** Comments: This is the license associated with V8 projects
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/95
**7.** URL(s): 
**8.** OSI Status: Not Submitted
**9.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/9f9bfda0-3234-4d50-8d66-e2b654a55d12.png

**Note:**
The license closely matched with the following license ID(s): BSD-3-Clause

**Comment by jlovejoy** [comment]
As per our matching guidelines this IS a match to BSD-3-Clause.
See: https://spdx.dev/license-list/matching-guidelines/

and note, specifically, section 2.1.3 which is visually shown via red text here https://spdx.org/licenses/BSD-3-Clause.html

the only difference I see is "Google" in clause 3 which is "replaceable"

**Comment by goneall** [comment]
Since this was submitted using the online app, the license text probably didn't match for some reason.  The license diff image isn't that helpful, it will probably require some manual investigation to figure out what it didn't match.

**Comment by jlovejoy** [comment]
as this is a match to an existing license, no new license need be added.
I will close this issue
