### ISSUE TITLE
New license request: OPNL-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Mentors4EDU** [spdx/license-list-XML#1164]
**1.** License Name: Open Innovation LIcense v2
**2.** Short identifier: OPNL-2.0
**3.** License Author or steward: Andrew Magdy Kamal, Stark Drones Corporation
**4.** Comments: Since last time we spoke, OPNL (which is also pending) have been adapted by nearly 57 software teams.
https://hackernoon.com/why-you-should-source-your-software-under-the-open-innovation-license-8cv3wmc
https://hackernoon.com/launching-the-impossible-engineering-challenge-xzs34q8
https://hackernoon.com/announcing-the-open-innovation-hackathon-for-college-students-jze3wja
Currently though, I made v2.0 due to the fact that I wanted to simplify it and reinstate it as an organization's mission statement promoting technological ethics and reinforcing terms on free redistribution. This doesn't however mean I don't believe in the first version (OPNL) or its merits. I just wanted to make a simpler one given some feedback from the open source community. I hope both identifiers could get approved as it would be easier for people to include its symbol in .config and .json files.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/96
**7.** URL(s): https://github.com/StarkDrones/OPNL/tree/main/Version%202
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://innovate.devpost.com/, https://www.herox.com/impossible

**Comment by jlovejoy** [comment]
are both version 1 and version 2 in use??

**Comment by Mentors4EDU** [comment]
Yes. Version 1 is actively in use and is the one in example projects and adapted by 57 teams (now 60). Version 2 was just released as technically the simpler variation of Version 1. I recently created a Zenodo and NPM Package for version 2 which has received about 120 downloads during the past day. I expect about 200 to 400 repos to have it within the next upcoming few month.

**Comment by Aspie96** [comment]
> OSI Status: Not Submitted

Wait, didn't you submit it and then withdraw it?

**Comment by Aspie96** [comment]
That looks like an OSI submission to me: https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-December/005042.html

**Comment by Mentors4EDU** [comment]
Hi, like I said earlier in the other pull request I submitted and withdraw it, but decided not to go w/ the voting process w/ them. I didn't know how to best word that because that wasn't an option on the form.

Best regards, Andrew

**Comment by Aspie96** [comment]
> Hi, like I said earlier in #1134 I submitted and withdraw it, but decided not to go w/ the voting process w/ them. I didn't know how to best word that because that wasn't an option on the form.

Fair enough.
I think the information I added is relevant then.

> I also want to point out that the link you inserted isn't well indexed by Google and includes personal emails regarding everybody involved.

The mailing list is public, there is nothing secret at all abut it.
You can reach the archives via the opensource.org website. The whole purpose of the archives is for them to be public.
Also it is indexed by Google, as you can easily verify, but that is not important.
When you publish to that mailing list you should already assume everything is going to be public, that's its purpose.

> Also, you have previously raised similar issues like EthicalSource/hippocratic-copyleft#1

This is completely irrelevant here. Go comment there if you want.
If you actually checked there, you would however see that **I did not downvote anybody in that issue**. The downvotes are not from me and it's very easy to verify.

> You also downvoted my other pull request

I downvoted it because I disagree with it. It is my right to use the voting system this website provides. I didn't design GitHub.

> you have made a response in regards to my license on choosealicense even though the pull request there was related to Ethical Source and didn't include any of my licenses

Thanks for pointing that out. I did notice my mistake, but I hadn't corrected it yet.
Next time, reply in the appropriate issue, please. That comment of mine has nothing to do with this issue, it's a different conversation.

> This further prevents well meaning discussion or civil discourse.

Further implies there is something else.

So far:
- I added relevant information about the OSI status of your license. By your own admission the available options didn't provide all relevant informations.
- I linked to a public mailing list which is well indexed by Google.
- Somebody else downvoted answers to my post and you for some reason are accusing me of that. Please check, it's not me.
- I used the voting system this website, which you are accepting to use, provides to manifest my disagreement with both of your PRs.
- I did make a mistake in that other issue and I will fix it.

The purpose of civil discourse is exactly to discuss what is being done. You could have disagreed with me in the correct threads and/or respectfully corrected me on the latter point. That would have been well meaning and civil discourse. For some reason you chose not to.

Best regards.

**Comment by Mentors4EDU** [comment]
1) Actually the information you added is mostly irrelevant. If you can seen the previous comments by the SPDX team in my other pull requests, they seen the OSI thread and/or are already aware it has been submitted to OSI.
2) You made a mistake not checking the full thread and therefore posted information that was generally already known. You also made a similar mistake when you didn't do enough due diligence on the choosealicense pull request. Your tone is suggesting complete and utter rejection of what I have to say that you already went on a defensive mode for issues irrelevant to it.
3) Outside of knowing that you as a general GitHub user, without legal experience, outside of the SPDX team rejects to this pull request, now new nor productive information was provided.

That said, I want to reiterate the point that the SPDX identifier is needed for:
- Reserving the OPNL and OPNL-2.0 symbols to prevent confusion in the future in config files
- Easier to add in the NPM CLI and other terminal command line interfaces that use the SPDX standard
- Many people are already using it, and **Stark Drones** might decide to release hundreds of pieces of its cloud software under it.
- It is growing, fulfills a general purpose, and with the inclusion of things like BUSL-1.1, I feel like this is closer to within the definition of open source.

Anyways, I already iterated my core points. Any counterclaims in regards to my core points and responses to them have mostly already been tackled. I feel as if plenty of due diligence on my side have been done in regards to the making of this license and my views related to it.

**Comment by Mentors4EDU** [comment]
Hi, given that the series of comments had less to do w/  this pull request and he has commented on other of my GitHub issues before, I have blocked the user. Responding back and forth to comments outside of concerns by the SPDX team is irrelevant to my time and would take forever. 
I want to reiterate the focus should be on the license, the pull request and the needed usage of an identifier.
I also want to reiterate:
```
 AND there is no objection raised from the greater SPDX-legal community within the Github issue comments
```
His disagreements back and forth on the issue made it hard to discuss core points.
Anyways, I look forward to pursing this license request.

**Comment by liuxinyu970226** [comment]
@Mentors4EDU Besides, I think the [SPDX Online Tool License requests form](https://tools.spdx.org/app/submit_new_license/) should really also have a question mark on the "OSI status" field, to explain us how to check the status of OSI submitting.

**Comment by Mentors4EDU** [comment]
> @Mentors4EDU Besides, I think the [SPDX Online Tool License requests form](https://tools.spdx.org/app/submit_new_license/) should really also have a question mark on the "OSI status" field, to explain us how to check the status of OSI submitting.

Yes, I also want to emphasize that my main point was that the original SPDX submissions were prior to OSI and that the team is already aware of the submission. Also I withdrew the OSI submission, and haven't asked to move to the OSI board approval process which is outside of community discussion. That said I would like potential OSI inclusion in the future, but this has less to do with the SPDX submissions. There are different boards within open source with different philosophies and voting procedures. This doesn't invalid the license or its need.

**Comment by jlovejoy** [comment]
This has been discussed by the SPDX-legal team, the following is a summary as per the license inclusion guidelines:

Definitive factors: The license appears to meet most of these, with the note that it is not OSI-approved and assuming that v2 text isn't planned to be modified (and that the version number would be bumped if it was).

Other factors: 
1)  v2 does substantially comply with the definitions listed here (in light of the fact that we would consider the preamble not part of the license conditions and marked as “optional”). 
2) It is structured to be generally usable by anyone.
3) Based on a search for the license in Github, it does not appear to any actual use at this point in time. While you have pointed to plans to promote the license, that is not actual use.
5) it was submitted by the license steward

For the "other factors", we look at them with a "totality of the factors" lens. Given that, based in particular on it not meeting factor 3, we don’t think it should be added to the License List at present. That it could be reconsidered in the future if the license shows significant usage in the wild.

**Comment by jlovejoy** [comment]
As a separate note - blocking someone from this issue because you don't like or don't agree with their comments is not appropriate. If any kind of moderation is needed, that should be handled by the SPDX leaders or at least be raised amongst the community. Unilateral decisions, particularly by someone who is not regularly involved in a community, is not the open source way.

**Comment by Mentors4EDU** [comment]
@jlovejoy In regards to usage, I have noted it is fairly new. So far 8 publicly available projects use it + the 82 teams that signed up for the HeroX challenge I made may use it. I do hope to quality for an identifier though, because lots of cloud software that Stark Drones has as open source may by able to use the short identifier in the configs.
In regards to blocking somebody, he has replied on multiple pull requests I have had on multiple places. Most of these pull requests in the general guidelines state that a pull request isn't the place for staying disagreement but rather open mailing list. I feel like it was a given I didn't want to continue the discussion in the actual pull request and I don't have hours of my time reply to the same guy back and forth.
I am generally okay with people stating disagreement, if it is with respect to my time and not done in a passive aggressive way. Pull requests are not the appropriate venue for that.

**Comment by Mentors4EDU** [comment]
I also want to reiterate if accepted, the OPNL2 config can be added to many software packages that Stark Drones personally runs which would then meet the 3 requirement.

**Comment by jlovejoy** [comment]
re: blocking - you have missed my point, "If any kind of moderation is needed, that should be handled by the SPDX leaders or at least be raised amongst the community."
You made a unilateral decision, that is the part that is not appropriate.

**Comment by Mentors4EDU** [comment]
Hi @jlovejoy I do apologise in that instance. Please note he also replied in places outside of my pull request on here instead. Regardless, perhaps I should have tried raising that issue first.

**Comment by jlovejoy** [comment]
re: usage - this is the chicken/egg issue we have seen before and we understand and appreciate the desire to be able to use SPDX identifiers. However, we also need to make a call and we cannot simply accept every submission that comes through because someone says they think it will be used a lot (everyone thinks that ;)

You can always use LicenseRef as per the SPDX spec in the meantime. And re-submit once there is more actual use.

**Comment by Mentors4EDU** [comment]
> re: usage - this is the chicken/egg issue we have seen before and we understand and appreciate the desire to be able to use SPDX identifiers. However, we also need to make a call and we cannot simply accept every submission that comes through because someone says they think it will be used a lot (everyone thinks that ;)
> 
> You can always use LicenseRef as per the SPDX spec in the meantime. And re-submit once there is more actual use.

Hi, my worry is I have like 225 cloud repositories for tools used by alot of developers that I may want to put the identifier in if Stark Drones decided to go that route. Plus with the people already using it, although it is not alot, questions arise in regards to what happens if somebody in the future tries submitted a license w/ the OPNL or OPNL-2 tag?

**Comment by jlovejoy** [comment]
I think it's somewhat unlikely that someone would submit a license with the same identifier - while it feels like we get a lot of submissions (b/c we are woefully behind), it's not that many and not all are accepted. 
You could also use something like LicenseRef-OPNL-2.0 in the meantime, which would be a nice set up for if/when later it is re-submitted

**Comment by jlovejoy** [comment]
(I need to close this, as we are trying to get caught up, but one additional comment as a lawyer and taking my SPDX hat off:

Given you have some a lot of use planned for this license, both by your company and encouraging its use by participants of some hackathons (as far as I can tell) - I would highly recommend having an experienced lawyer help you. Despite what many developers seems to think, we lawyers do have a specific skill and know what we are talking about :) Your license, goals, and anyone who may use the license in the future will benefit greatly.
 I'm more than happy to provide a couple recommendations (off Github and use direct message of some kind!)
