### ISSUE TITLE
New license request: VPSL-1.0.1 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by wmthornton** [spdx/license-list-XML#1168]
**1.** License Name: ViraTrace Public Source License v101
**2.** Short identifier: VPSL-1.0.1
**3.** License Author or steward: ViraTrace, LLC
**4.** Comments: The VPSL is designed to be partially-restrictive but still license proprietary source code for use by individuals and companies utilizing frameworks and software developed by ViraTrace, LLC (or subsidiaries). This is similar to the Apple Public Source License v. 1.0 in scope, but is more narrow in that it provides for mandatory legal compliance with privacy protections and regulations within the EU and US. ViraTrace is a specialist supplier of contact tracing and digital health frameworks and such a license is necessary.
**5.** Standard License Header: Portions Copyright (c) 2020-2021 ViraTrace LLC.  All Rights Reserved.

This file contains Original Code and/or Modifications of Original Code as defined in and that are subject to the ViraTrace Public Source License Version 1.0 (the 'License'). You may not use this file except in compliance with the License. Please obtain a copy of the License at https://github.com/ViraTrace/License and read it before using this file.

The Original Code and all software distributed under the License are distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND VIRATRACE HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT.  Please see the License for the specific language governing rights and limitations under the License.
**6.** License Request Url: http://tools.spdx.org/app/license_requests/97
**7.** URL(s): 
**8.** OSI Status: Not Submitted
**9.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/a1d3a2a4-ab1c-45ff-9400-255458222534.png

**Note:**
The license closely matched with the following license ID(s): Watcom-1.0

**Comment by wmthornton** [comment]
We at ViraTrace would also note that although the VPSL is restrictive, it requires ViraTrace to defend the rights of others to use the subject source code and derivatives where ViraTrace knew or knows that the code is legally challenged. It provides that ViraTrace must revoke the license to use the source code to anyone using legally dubious source and either provide a fix or attempt to procure legal rights to the code. It also prevents ViraTrace from using derivative source code directly for profit.

**Comment by wmthornton** [comment]
Wondering if there is going to be any movement on this new license/exception request?

**Comment by jlovejoy** [comment]
we are a bit overloaded at the moment and trying to go in order, thanks for you patience!

**Comment by jlovejoy** [comment]
btw, Watcom-1.0 was added to the license list in the very early days before we had license inclusion guidelines, so that it is included is not really persuasive now as we have documented inclusion guidelines

**Comment by jlovejoy** [comment]
discussed on April 15th call - declined to add for main reasons that it is entity specific, and has restrictions.
