### ISSUE TITLE
SPDX "Unicode-DFS-2016" 

### ISSUE THREAD

**Issue by ariel11** [spdx/license-list-XML#1169]
I am looking to determine if there is a valid SPDX for the LICENSE file for the ICU project - e.g. https://github.com/unicode-org/icu/blob/master/icu4c/LICENSE.

As you can see on the LICENSE file above, only the bottom portion of the LICENSE file matches everything under the "COPYRIGHT AND PERMISSION NOTICE" section of the "Unicode-DFS-2016" SPDX (except on the LICENSE file, it says "COPYRIGHT AND PERMISSION NOTICE **(ICU 58 and later)**."  

The top part of the "Unicode-DFS-2016" SPDX  (the "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE") section is not included in the ICU LICENSE file.

To adhere to the matching guidelines, thoughts on making the "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE" section of the "Unicode-DFS-2016" SPDX colored font to indicate it is optional text?  That way, the "Unicode-DFS-2016" SPDX would work for the ICU LICENSE file.

Also, noting that the https://www.unicode.org/license.html has a similar issue (it mostly fits the "Unicode-DFS-2016" SPDX, except part of the "UNICODE, INC. LICENSE AGREEMENT - DATA FILES AND SOFTWARE" section of that SPDX is not included. 

Thank you

**Comment by ariel11** [comment]
Showing diff between [ICU LICENSE file](https://github.com/unicode-org/icu/blob/master/icu4c/LICENSE) and [Unicode-DFS-2016](https://spdx.org/licenses/Unicode-DFS-2016.html).

![image](https://user-images.githubusercontent.com/17935946/104643012-8a2d3600-5660-11eb-8685-71558d581dd8.png)

**Comment by ariel11** [comment]
Showing diff between https://www.unicode.org/license.html and [Unicode-DFS-2016](https://spdx.org/licenses/Unicode-DFS-2016.html).

![image](https://user-images.githubusercontent.com/17935946/104643309-13dd0380-5661-11eb-9bf5-c5bd2cc7e213.png)

**Comment by capfei** [comment]
I get a lot of these as well and would like to know if the portion above the copyright statement is required to be "Unicode-DFS-2016" or if the SPDX text can be updated to make that part optional.

**Comment by jlovejoy** [comment]
looks like we also need to update the URL on the license page to https://www.unicode.org/license.html

**Comment by jlovejoy** [comment]
discussed on Feb 4th call: agreed it's fine to mark first 3 paragraphs as optional, but "NOTICE TO USER..." section is more legally substantive and not something we'd usually mark as optional. Yet, Unicode appears to omit that section in their own use of the license.
- more research as to if there is any use in wild of license including that paragraph (in which case, we may want to make a new variant to accommodate)
- also would be good if we can reach out to Unicode, if possible

**Comment by swinslow** [comment]
@jlovejoy to reach out to Unicode

**Comment by jlovejoy** [comment]
I have attempted to reach out to someone at Unicode - will report back shortly

**Comment by jlovejoy** [comment]
waiting to discuss more with rep from Unicode (sounds like the text in question *should* be included, but need a closer look)

**Comment by srl295** [comment]
@jlovejoy I sent you a note from Unicode in response

**Comment by srl295** [comment]
We also noticed https://opensource.org/node/1077 which has some formatting issues.

**Comment by srl295** [comment]
https://www.unicode.org/license.html is now a symlink to https://www.unicode.org/license.txt containing the same text as `LICENSE` above.
