### ISSUE TITLE
Add OSI-approved markup for CERN OHL 2.0 licenses

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1170]
These were approved by OSI on 2021-01-15: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2021-January/005066.html

**Comment by emmanueltournier** [comment]
Here

**Comment by jlovejoy** [comment]
@swinslow @emmanueltournier - do we have a PR for this?
is this same as #1173 ?

**Comment by emmanueltournier** [comment]
@jlovejoy, sorry I am not very familiar with GitHub, but I don't think I created a PR for this so I'll look into it. And it is different from #1173.

**Comment by jlovejoy** [comment]
correction this issue is about OSI-approved status only (#1173 is about adding markup)

**Comment by swinslow** [comment]
will merge #1196 #1197 and #1198 once CI is running again
