### ISSUE TITLE
New license request: CC-BY-2.5-AU

### ISSUE THREAD

**Issue by nicorikken** [spdx/license-list-XML#1171]
I tried submitting this in the web form. Got an error (attached at the end) but couldn't find where to report that error even. So I decided to skip that process altogether and just commit straight to GitHub.

**License's Full Name:** Creative Commons Attribution 2.5 Australia (CC BY 2.5 AU) 
**Short Identifier:** CC-BY-2.5-AU
**Source / URL:** https://creativecommons.org/licenses/by/2.5/au/
**Who is the license author or license steward?:** Creative Commons
**Example project URLs:** https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
**Comments:** Found it being used in the git flow documentation by Atlassian. I noticed other country-specific-variants were already included in SPDX, but not this particular variant.

**SPDX Online Tool - License request - Error:**
```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred:
Traceback (most recent call last):
File "/spdx/src/app/views.py", line 127, in submitNewLicense
  matchingIds, matchingType = utils.check_spdx_license(licenseText)
File "/spdx/src/app/utils.py", line 533, in check_spdx_license
  listedLicense = getListedLicense(licenseID)
File "/spdx/src/spdx-license-matcher/spdx_license_matcher/utils.py", line 88, in getListedLicense
  listed_license = licenseinfofactoryclass.getListedLicenseById(licenseId)
File "/usr/local/lib/python2.7/site-packages/jpype/_jpackage.py", line 62, in __call__
  raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package org.spdx.rdfparser.license.LicenseInfoFactory.getListedLicenseById is not Callable 
```

**Comment by goneall** [comment]
@nicorikken Thanks for reporting the error.  I ran into a similar issue earlier in the week.  I added an issue to the SPDX online tools repo to track: https://github.com/spdx/spdx-online-tools/issues/285

A new version of the software is planned to be released in the next day or so.

**Comment by swinslow** [comment]
Discussed on legal team call 2021-04-15, agreed to approve.

@nicorikken You can proceed now with submitting a PR containing the XML and test text file to add this. The process is documented at https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md. If you are able to submit this in the next two weeks, we can add it for the 3.13 release. Thanks!

**Comment by jlovejoy** [comment]
ping @nicorikken - do you think you will be able to make the PR for this in the next couple days for the 3.13 release? Otherwise, we'll move it to the 3.14 release.

**Comment by nicorikken** [comment]
@jlovejoy @swinslow sorry, I wasn't keeping up with my GitHub notifications. I'll create a PR :+1:
