### ISSUE TITLE
zlib-acknowledgement - add markup

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1185]
needs replaceable markup for acknowledgement text (so it can actually match to Nunit)

**Comment by jlovejoy** [comment]
@emmanueltournier is going to pick this up

**Comment by emmanueltournier** [comment]
Here

**Comment by swinslow** [comment]
adding replaceable text to copyright notice in section 1 of license

**Comment by swinslow** [comment]
@emmanueltournier I'm moving this one forward to 3.13 so that we can go ahead and get 3.12 out today. Thanks!

**Comment by emmanueltournier** [comment]
@swinslow , I lookerdat the Nunit license text from here: https://docs.nunit.org/2.6.2/license.html and I think our current markup matches it. What am I missing?

**Comment by emmanueltournier** [comment]
@jlovejoy @swinslow , the acknowledgement text actually matches the one of the NUnit license except for the copyright years and symbols. Is that all there is to fix?

**Comment by jlovejoy** [comment]
ok, having deja vu and memory failing me at the same time, but I think this is where we are at!
we have two zlib licenses:

1) https://spdx.org/licenses/Zlib.html - which states, "If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required." and does not have exact acknowledgement example

2) https://spdx.org/licenses/zlib-acknowledgement.html - which states, "If you use this software in a product, an acknowledgment (see the following) in the product documentation is required." and then has an acknowledgement example

Nunit - https://spdx.org/licenses/Nunit.html - is deprecated. I think this was because it is an exact match to #2, but for the different names in the acknowledgment example.   I believe this is why it was deprecated, but we never managed to get around to adding the markup in #2 zlib-acknowledgement

so to your question - I would markup the entire acknowledgment line - not just the specific bits - so that it doesn't matter if all the of the names are different.  Basically, the whole line that begins with "Portions..."

make sense? @swinslow - agree?

does that make sense?

**Comment by emmanueltournier** [comment]
Thanks @jlovejoy I guess that makes sense. But does that mean I shoudl add <optional > or something else?

**Comment by jlovejoy** [comment]
see #1305

**Comment by swinslow** [comment]
Closed by #1305, thanks @jlovejoy!
