### ISSUE TITLE
New license request: PD [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by freegovinfo** [spdx/license-list-XML#1194]
**1.** License Name: US Government Public Domain
**2.** Short identifier: PD
**3.** License Author or steward: US Copyright Office
**4.** Comments: CC-PDDC was deprecated by Creative Commons several years ago. Other public domain licenses listed on spdx list are software- or data related. Therefore a simple Public Domain license focused on the published works of the US government is necessary.
**5.** Standard License Header: All materials published by US Federal entities and/employees are in the Public Domain as per section 105 of the Copyright Act (17 USC 105).
**6.** License Request Url: http://tools.spdx.org/app/license_requests/103
**7.** URL(s): https://www.usa.gov/government-works
**8.** OSI Status: Pending
**9.** Example Projects: https://www.govinfo.gov/about/policies#copyright, https://www.federalregister.gov/reader-aids/government-policy-and-ofr-procedures/about-this-site#legal-status, https://www.gao.gov/copyright/, https://www.archives.gov/global-pages/privacy.html

**Comment by pombredanne** [comment]
IMHO using "pd" as a key does not convey enough about the specific of this license.
I am tracking this as https://scancode-licensedb.aboutcode.org/us-govt-public-domain.html in scancode together with  several notice variants https://github.com/nexB/scancode-toolkit/search?q=filename%3Aus-govt-public-domain+path%3Asrc%2Flicensedcode%2Fdata%2Frules&type=code

**Comment by liuxinyu970226** [comment]
Note: We call it PD-USGov(-departments) on Wikimedia sites e.g. Commons.

**Comment by andrewshadura** [comment]
The [Debian machine-readable copyright file format](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) uses `public-domain` as the short identifier for this.

**Comment by jlovejoy** [comment]
We have many times in the past discussed the concept of a general "public-domain" tag (similar to Debian's) and wrote this to clarify why this is not a good idea (from the perspective and goals of SPDX) here: https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files_(DRAFT)
(disregard "DRAFT" in that url1)

if the text that @pombredanne has captured is used in a standard way, then I can see adding it.  But I'm not clear on if that is the case?

**Comment by jlovejoy** [comment]
@freegovinfo or @pombredanne - do either of you have any idea as to the answer to my question above (which I'll revise to make clear)
Is the following text actually used in source code files?
```
17 U.S. Code $ 105. Subject matter of copyright: United States Government works

Copyright protection under this title is not available for any work of the
United States Government.
```

**Comment by freegovinfo** [comment]
here at Stanford libraries, we’re using the SPDX list of licenses for metadata of content in our digital repository. I’m a govt information librarian and have been storing US govt publications in our repository that I come across. As of now, there’s no license on the SPDX list that conforms to US federal publications. So one of the repository managers asked me to request it. I have not seen it in software source code, but it’s very common across the federal government’s web space and information products including datasets. Please let me know if you’d like me to put you in contact with our repository staff if you’d like more information on how we’re using SPDX.

James Jacobs
@freegovinfo

**Comment by swinslow** [comment]
@freegovinfo, thanks for your response. From SPDX's perspective, whether for software source code or other works like documentation, the purpose of the SPDX license list has always been centered around mapping an identifier to a single specific text that is used to express the "license" of the content. So there's been an intention in the past to avoid identifiers that would express e.g. the general concept of "this content is in the public domain" where there isn't a specific corresponding text that a license matching tool could detect and compare it against.

I think @jlovejoy's question is centered around, do you see the specific text of the 17 USC 105 statute being itself included in the works that you're looking to map to this "license"? And/or, is there other common text used across the applicable works, possibly with minor variations but generally the same or near-same text?

I'll also reach out to a contact at the LOC counsel's office to get their thoughts on this, as they might have interesting input here from their perspective.

**Comment by jlovejoy** [comment]
closing this, as no further comments. We can revisit if the US Gov comes up or wants to come up with a standard notice text.
