### ISSUE TITLE
New license request: Anarchy [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by landfillbaby** [spdx/license-list-XML#1202]
**1.** License Name: Anarchy License
**2.** Short identifier: Anarchy
**3.** License Author or steward: Lucy Phipps (submitter)
**4.** Comments: Basically a shorter, more political version of WTFPL, with an added warranty clause and only implied swearing. (That sentence alone is longer than the license itself.)
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/105
**7.** URL(s): https://github.com/landfillbaby/licenses/raw/master/pdequiv/Anarchy.txt
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/landfillbaby/png2webp

**Comment by jlovejoy** [comment]
it looks like this is only used on one project, which is the license author's project, which doesn't meet our guideline of substantial use. see https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md
also, this is not even a license, from a legal perspective.

**Comment by landfillbaby** [comment]
:)

**Comment by silverhook** [comment]
WONTFIX NOTALICENSE

**Comment by swinslow** [comment]
Agreed with @jlovejoy and @silverhook, I don't think this qualifies under the SPDX license inclusion principles, so agreed to close.
