### ISSUE TITLE
Continuous integration publish optimization for single file

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#1204]
Single file optimizations is not implemented for the publishing step done during the merge to master or push to master.

To implement this, the Makefile deploy needs to check if the only change is a modification or addition of an XML file and optionally the test file.  In this case, the files cloned from the license-list-data repo should not be deleted - the LicenseListPublisher will overwrite the changed files.  The parameter passed to LicenseListPublisher will also need to be changed to use the single XML file.

If the files changed includes multiple XML files or any deletions, the Makefile should work as it does today - delete the deployed files in the license-list-data clone and run the licenseListPublisher against the `src` directory.

**Comment by goneall** [comment]
This is related to the PR #1199

**Comment by jlovejoy** [comment]
@goneall - looks like #1199 was closed, so can we close this too?

**Comment by goneall** [comment]
> looks like #1199 was closed, so can we close this too?

I'll close this.  I think it is still an issue, but it is covered in #1085 

The description is also out of date.
