### ISSUE TITLE
Creative Commons IGO licenses

### ISSUE THREAD

**Issue by robbiemorrison** [spdx/license-list-XML#1208]
The [licenses](https://spdx.org/licenses/) page currently **omits** the following valid license that would no doubt be designated `CC-BY-NC-SA-3.0-IGO` as per:

- https://creativecommons.org/licenses/by-nc-sa/3.0/igo/legalcode

The fix should be self-evident.

**Comment by jlovejoy** [comment]
Can you please follow our https://github.com/spdx/license-list-XML/blob/master/CONTRIBUTING.md process for new licenses :) - that would be really helpful :)

**Comment by robbiemorrison** [comment]
Sure.  From my perspective, please mark this issue resolved.

**Comment by robbiemorrison** [comment]
Submission via the submit **new license tool** web interface now complete.

**Comment by swinslow** [comment]
Thanks @robbiemorrison! Closing this issue and we can review the specific request in #1210.
