### ISSUE TITLE
Deprecate one of the two bzip2 licenses, they are duplicates.

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-XML#1223]
Somehow there is a  patent commentary that has been (IMHO incorrectly) included in the SPDX text of https://spdx.org/licenses/bzip2-1.0.5.html and dropped out of the SPDX text of https://spdx.org/licenses/bzip2-1.0.6.html

Yet this statement is just that: a commentary and was never part of the actual license text. It just shows up in the doc and in some README such as here: https://sourceware.org/bzip2/1.0.5/bzip2-manual-1.0.5.html

The PATENTs statement has never been part of the LICENSE file, but is only a comment in some README and that was (imho incorrectly) taken in the SPDX text instead of using the actual correct LICENSE file text.
There is no material difference in any of the upstream official bzip2 LICENSE texts and therefore there should not be multiple bzip2 licenses at SPDX.

The attached three versions of the LICENSE texts are essentially the same.

The URLs to the original code are:
-  [1.0 of 21 March 2000.LICENSE.txt](https://github.com/spdx/license-list-XML/files/6118055/1.0.of.21.March.2000.LICENSE.txt) is from https://web.archive.org/web/*/http://www.bzip.org/1.0.1/bzip2-1.0.1.tar.gz

- [1.0.5 of 10 December 2007.LICENSE.txt](https://github.com/spdx/license-list-XML/files/6118057/1.0.5.of.10.December.2007.LICENSE.txt) is from  https://web.archive.org/web/20100405073031/http://www.bzip.org/1.0.5/bzip2-1.0.5.tar.gz

- [1.0.6 of 6 September 2010.LICENSE.txt](https://github.com/spdx/license-list-XML/files/6118056/1.0.6.of.6.September.2010.LICENSE.txt) is from https://web.archive.org/web/20161119084155/http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz

- and the latest LICENSE is now in git with a full history at https://sourceware.org/git/?p=bzip2.git;a=history;f=LICENSE;h=81a37eab7a5be1a34456f38adb74928cc9073e9b;hb=HEAD

In all cases the bzip2 LICENSE never includes this patent commentary and the official license text has never changed since 1.0 and the switch from GPL. So there should be not two but only one license.

**Comment by jlovejoy** [comment]
so, looking back, we apparently discussed this on Feb 20, 2014 - https://lists.spdx.org/g/Spdx-legal/message/817?p=,,,20,0,0,0::Created,,bzip,20,2,0,22080449 and the link to the article http://article.gmane.org/gmane.comp.licenses.spdx.legal/812/match=bzip  is probably what holds a key to why we came to this (meeting minutes don't have more info)
But that link doesn't work and the Wayback Machine is not helpful here.

I believe that article was maybe work by @dmgerman - any chance you can point us to a new location?

**Comment by swinslow** [comment]
I obviously wasn't around for the 2014 discussion  :)  But one thing I'd note is that, looking at the bzip v1.0.6 software distribution's manual, it also contained the same "patents" statement: see https://svn.python.org/projects/external/bzip2-1.0.6/manual.pdf, page 2.

I haven't done further research yet, but I'd tend to agree that either the PATENTS statement is, or is not, part of the bzip2 license regardless of version. So it probably does make sense to consolidate them and deprecate one or the other.

**Comment by swinslow** [comment]
Discussed on 2021-09-02 legal team call, Steve to contact current maintainer by email; proposal is to deprecate 1.0.5 and to add alt-text for 1.0.6 to cover the "PATENTS" statement going forward.

**Comment by swinslow** [comment]
The changes to bzip2-1.0.6 were merged in #1364, and #1387 has been submitted to deprecate bzip2-1.0.5 and add an explanatory note. So I think we can close this issue.
