### ISSUE TITLE
ISC.txt incorrectly includes a specific copyright notice

### ISSUE THREAD

**Issue by bsdimp** [spdx/license-list-XML#1224]
The ISC license, as reported by the ISC.txt file and published in the sister license-list-data repo

starts off:
```
ISC License:

Copyright (c) 2004-2010 by Internet Systems Consortium, Inc. ("ISC")
Copyright (c) 1995-2003 by Internet Software Consortium
```
Instead, it should start
```
<copyright notice>
```

This makes it needlessly difficult to write a program that will generate a full license from the indirect license. Consider:
```
/*
 * Copyright 2021 The Dude Bowling, LLC
 *
 * SPDX-License-Identifier: ISC
 * /
```
Ideally the program could replace `<copyright notice>` with `Copyright 2021 The Dude Bowling, LLC` and generate:
```
Copyright 2021 The Dude Bowling, LLC

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

There are many examples of this. MIT-CMU gets it right, all the BSD licenses have this issue. This is more important for files that have multiple authors that evolve over time. The following example wouldn't be out of place in one of the BSD projects that had gotten all the copyright holders to switch to ISC (ignore how for this example):
```
/*
 * Copyright 1994 NetBSD Foundation
 * Copyright 1995-1999 Charles M Hummings
 * Copyright 1998-2013 George W Poindexter, III
 * Copyright 2004-2020 Great Scott Productions
 * 
 * SPDX-License-Identifier: ISC
 */
```
should generate:
```
Copyright 1994 NetBSD Foundation
Copyright 1995-1999 Charles M Hummings
Copyright 1998-2013 George W Poindexter, III
Copyright 2004-2020 Great Scott Productions

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```
I know that the focus on SPDX has been going the other direction: taking a bunch of licenses, applying sophisticated matching algorithms to produce the SPDX metadata. For that purpose, though, I'd assert that this change would make it easier (or no harder) to detect this license.

**Comment by mlinksva** [comment]
I would love to see this change made, across all licenses. It's way easier for the casual reader to understand how to use/what to expect from a license if such a canonical representation doesn't display a specific copyright holder when substitution is expected/the only thing that makes sense.

**Comment by jlovejoy** [comment]
I may not be fully understanding your question/comment, but here's some info that may be helpful:
- as per the SPDX License List matching guidelines - https://spdx.dev/license-list/matching-guidelines/ - guideline 10 states that copyright notices can be ignored for purposes of matching the text of the license. This is indicated in the XML markup via the <copyrightText> tag (and which displays in red text on the SPDX License List page for easy human-viewing)
- the .txt files in the repo do not contain the markup

Does that help clarify?

**Comment by bsdimp** [comment]
I think the best way forward with this is to create a pull request with my specific change to the XML file.

**Comment by bsdimp** [comment]
The one bad thing about the current license is that it still has ISC in two places. While that is fine for the matching software, ISC isn't disclaiming anything, the copyright holders are doing the disclaiming.
https://github.com/spdx/license-list-XML/pull/1237 has the pull request.

**Comment by jlovejoy** [comment]
see further comments at #1237

**Comment by swinslow** [comment]
I also added comments at #1237 -- I'm +1 on the change in that PR.
