### ISSUE TITLE
Expose equivalentwords.txt to license-list-data

### ISSUE THREAD

**Issue by m1kit** [spdx/license-list-XML#1225]
I think it would be great if https://github.com/spdx/license-list-data includes [equivalentwords.txt](https://github.com/spdx/license-list-XML/blob/master/equivalentwords.txt) and we can access it on `https://spdx.org/licenses/equivalentwords.txt`.
This repository is mainly used for internal XML representation and is not intended for public use, right?

**Comment by goneall** [comment]
This could be implemented by updating the [Makefile](https://github.com/spdx/license-list-XML/blob/master/Makefile) to copy the file to the license list data website subdirectory when `deploy-license-data` goal is executed.
