### ISSUE TITLE
New license request: ACSL-1.4 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by boringcactus** [spdx/license-list-XML#1228]
**1.** License Name: Anti-Capitalist Software License 1.4
**2.** Short identifier: ACSL-1.4
**3.** License Author or steward: Ramsey Nasser & Everest Pipkin
**4.** Comments: It's definitely not OSD/FSD/etc compliant, but it *is* generally usable and used by many projects. The restrictions are not what most people would call "limited", though. License stewards are nasser and everestpipkin on GitHub.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/107
**7.** URL(s): https://anticapitalist.software/
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/everestpipkin/tools-list, https://github.com/antiboredom/zoom-escaper, https://github.com/ComradOrg/Comrad, https://github.com/unfrl/dug, https://sr.ht/~boringcactus/csgo-gsi/

**Comment by silverhook** [comment]
The license **does** seem to meet the _definitive factors_ of the [SPDX license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md).

Regarding the _other factors_ (in descending order of importance):

1. it is **not** compliant with any OSD, FSD, etc. definition, esp. through its limitation to be used only by “individuals and organizations that do not operate by capitalist principles”
2. it **is** structured to be used by anyone (see caveat above)
3. it **can be argued** that the license has some substantial use. A quick search shows about [140 occurrences where this license pops up on GitHub](https://github.com/search?p=15&q=This+is+anti-capitalist+software%2C+released+for+free+use+by+individuals+and+organizations+that+do+not+operate+by+capitalist+principles.&type=Code). At first glance, I did not find any important project among them. (For comparison, there seem to be [cca. 980 occurrences of the Hippocratic License](https://github.com/search?p=99&q=%22hippocratic+license%22&type=Code))
4. I would **argue that it does not** meet this criterion, as the limiting criterion seems to be quite exclusive (see quoted below)
5. I **cannot tell** what the license steward’s position is on their license being included in the SPDX License List. The submitter is not one of the stewards.

> This is anti-capitalist software, released for free use by individuals and organizations that do not operate by capitalist principles.
> […]
> 
> 2. The User is one of the following:
> a. An individual person, laboring for themselves
> b. A non-profit organization
> c. An educational institution
> d. An organization that seeks shared profit for all of its members, and allows non-members to set the cost of their labor
> 
> 3. If the User is an organization with owners, then all owners are workers and all workers are owners with equal equity and/or equal vote.
> 
> 4. If the User is an organization, then the User is not law enforcement or military, or working for or under either.

---

I would tend towards not including this license. Its limitations seem stricter than that of _Hippocratic-2.1_ and its use is also much smaller. But do not have strong feelings either way about it.

**Comment by jlovejoy** [comment]
@silverhook - thanks for the analysis which I would agree with.

I'm also a bit concerned that the intentions of the license would be extremely hard to enforce.  If someone were to use the code it in the ways the license was intended to prevent and that challenge that in court, there are holes you could drive a truck through without thinking very hard. 

While this is not explicitly one of our inclusion principles, it is something we have discussed from time to time. I'm not sure SPDX wants to "endorse" by adding to the SPDX License List something that 1) is not able to reach the goals that it intends - that feels like a disservice for people who use the license and feel strongly about the position it is trying to take; and 2) has glaring legal drafting issues

**Comment by jlovejoy** [comment]
discussed on April 29 legal call
- all agreed with the analysis and that it's too restrictive and shouldn't be added
- this license is drafted not really as a limited restriction but from a place of restriction and "only these people can use it"

**Comment by jlovejoy** [comment]
please note, you can always use LicenseRef- (see section 6 of the SPDX Spec https://spdx.dev/wp-content/uploads/sites/41/2020/08/SPDX-specification-2-2.pdf ) to identify other licenses
