### ISSUE TITLE
New license request: Programming-Unity-10.42 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by scott91e1** [spdx/license-list-XML#1236]
**1.** License Name: Programming Unity License 10.42
**2.** Short identifier: Programming-Unity-10.42
**3.** License Author or steward: Scott McCallum
**4.** Comments: Interested to have a license in the "Hippocratic" style license that deals with LGBT, AI and Ethical issues in a clear and consise manner.  The license is based on https://blueoakcouncil.org/license/1.0.0.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/108
**7.** URL(s): https://github.com/p-unity/license
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/p-unity/p-unity-python

**Comment by anthonyronda** [comment]
Hi @scott91e1 I'll be reviewing this according to the license inclusion principles.
I've just begun to look at it so please don't mind if it takes me a day or so to type it out

**Comment by scott91e1** [comment]
Thanks for the heads up.  This is my first license submission so if there are any issues or you have any suggestions to improve/tighten the language I would be happy to hear them.  Scott.

**Comment by swinslow** [comment]
Discussed on 2021-06-10 legal team call (as well as call 2 weeks ago), agreed not to add at this time based on analysis of the inclusion principles.

**Comment by scott91e1** [comment]
Thanks for this consideration of this new category of open source license.

I would like to understand, however, how the "SPDX: Hippocratic-2.1" was approved considering it includes "termination of this License for breach of the Human Rights Principles" and this is typically country-based and therefore would also be contrary to the "inclusion principles".

It seems that the "Programing-Unity-10.42" license is was rejected as it has concrete anti-discrimination provisions where "Hippocratic-2.1" is similar in spirit but is aspirational in implementation.

**Comment by anthonyronda** [comment]
@scott91e1 Your reply is very helpful, as this is my first ever review and it helps me understand where I could apply more care in crafting the review. I'm sorry for not being more verbose in my first review, as I'm still finding the right balance. @swinslow's remarks in #1098, copied here, also apply to your license application.

> For the "other factors", we look at them with a "totality of the factors" lens. Given that, based in particular on it not meeting factors 1 and 3, and the uncertainty around 4, I'm inclined to recommend that it should not be added to the License List at present. For licenses that don't meet one of the listed definitions (factor 1), we typically want to see greater evidence of broad use in the wild (factor 3). Some licenses such as Hippocratic-2.1 have been added on that basis, but in that case significantly greater usage was shown.

[Here is the link](https://github.com/search?q=hippocratic+license&type=commits) Hippocratic-2.1's submitter shared to demonstrate substantial use. They also gave 3-4 examples of use in the body of the submission itself.

I'd also like to alleviate your concerns about the implementation of the review process itself. Whether a license is "concrete" or "aspirational" isn't marked in the review process. Only the factors listed in the inclusion principles apply to my review.

**Comment by scott91e1** [comment]
Thanks for the additional information.  It's also my first license submission, so understanding the process and objectives of SPDX firsthand as a submitter is new to me.

Can the "LicenseRef-" prefix be used as the SPDX license identifier when submitting projects to PyPI.org?  I don't mind that the LGBTIQ+ license being considered an "unofficial license," but I would like to use it for my Python projects.

If this is not possible, perhaps a new prefix could be launched, "Nursery-" or similar for upcoming licenses that meet the bulk of the criteria sans adoption.

It seems to me there is a chicken-and-egg situation when launching new software licenses.

**Comment by anthonyronda** [comment]
As pydigger.com seems to show, it seems PyPI allows any string in the license field: https://pydigger.com/licenses. I see a couple entries using LicenseRef-.

> I don't mind that the LGBTIQ+ license being considered an "unofficial license,"

I understand where this misconception comes from, but the SPDX license request process does not judge licenses "official" or "unofficial." SPDX automatically accepts OSI-approved licenses, which is the only "stamp of approval" criterion for license list inclusion. My evaluation of whether your license complies with the Open Source Definition would be overwritten if the OSI approves it.

You don't need any outside organization's stamp of approval to use a text as a license, however, and SPDX does not provide a qualitative opinion on license texts. SPDX reviewers only apply the criteria of other organizations.
