### ISSUE TITLE
Missing paragraph in CAL-1.0

### ISSUE THREAD

**Issue by latk** [spdx/license-list-XML#1245]
It seems the text for the Cryptographic Autonomy License (CAL-1.0 and CAL-1.0-Combined-Work-Exception) is missing some text in section 4.1.2. The [versions on opensource.org](https://opensource.org/licenses/CAL-1.0) and in the [Holochain repository](https://github.com/holochain/cryptographic-autonomy-license/blob/2adc1d7550f1780ec5a5a3247053b801a4f31f8a/README.md) contain this paragraph which is missing in the SPDX version:

> A “Compatible Open Source License” means a license accepted by the Open Source Initiative that allows object code created using both Source Code provided under this License and Source Code provided under the other open source license to be distributed together as a single work.

However, I am not sure which document is treated as authoritative by SPDX. What is the process here?

If the above paragraph should be inserted, this would require a patch like this to both CAL variants in the SPDX database:

```diff
 to create the Modified Work. The Source Code corresponding to the 
 modifications in the Modified Work must be provided to the Recipient either 
 a) under this License, or b) under a Compatible Open Source License.
                   </p>
+                  <p>
+A "Compatible Open Source License" means a license accepted by the Open Source
+Initiative that allows object code created using both Source Code provided under
+this License and Source Code provided under the other open source license to be
+distributed together as a single work.
+                  </p>
                 </item>
                 <item>
 <optional>#### </optional><bullet>4.1.3. </bullet>Coordinated Disclosure of Security Vulnerabilities
```

**Comment by jlovejoy** [comment]
yikes, good catch!

also noticed the original URL we have is now broken :( @VanL

**Comment by jlovejoy** [comment]
see #1251 and #1252 

@swinslow - I think we should prioritize this for the upcoming release!

**Comment by VanL** [comment]
When's the next release?

**Comment by jlovejoy** [comment]
any day now

**Comment by swinslow** [comment]
@VanL 3.13 will be getting released tonight, I'm in process of pushing it now.
