### ISSUE TITLE
New license request: NLOD-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by evancharlton** [spdx/license-list-XML#1261]
**1.** License Name: Norwegian Licence for Open Government Data (NLOD) 2.0
**2.** Short identifier: NLOD-2.0
**3.** License Author or steward: Norwegian Digitalisation Agency
**4.** Comments: The first version of this (NLOD-1.0) is already in the SPDX database; this is merely a request to include version 2.0 as a separate entity.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/109
**7.** URL(s): https://data.norge.no/nlod/en/2.0/
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/NVE/regObs4/
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/5b2db5a6-2c5c-4889-814f-4c221a6eacc5.png

**Note:**
The license closely matched with the following license ID(s): NLOD-1.0

**Comment by DennisClark** [comment]
I cannot find a plain text version of this license without interspersed Comments.  If anyone can find that, please post a comment here.

**Comment by evancharlton** [comment]
I wasn't able to find it either -- I had to manually reconstruct the XML file 😞

**Comment by seabass-labrax** [comment]
Welcome to this repository, @evancharlton! Thank you for opening this issue, and especially for taking the time to create an associated pull request with the XML and plain text. This will be most useful if the license submission is accepted :)

Following the [inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) for the SPDX License List:

#### Definitive factors:

- [x] The license does not match another license already on this list.
- [x] The license does not apply only to software executables.
- [x] The license has identifiable and stable text.
- [x] The license steward appears to be committed to not modifying the license after addition to this list.

#### Other factors (roughly in order of importance):

- [ ] The license seems, at first glance, to comply with one of the free and open licenses listed in the inclusion principles. However, it has a sentence at the end of [section 2](https://data.norge.no/nlod/en/2.0/#_2_licence) that challenges this: "The Licensee shall not sub-license or transfer this licence." To me, it seems as if the licensor of NLOD-licensed content may, in the future, withhold the license from any future recipients of the content, even though the license may not be revoked from existing licensees. In this case, the license is *not* compliant with the free and open license definitions. However, this is complicated by [NLOD's section 9](https://data.norge.no/nlod/en/2.0/#_9_licence_compatibility), which states that the licensed content may be augmented and then relicensed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/legalcode), which explicitly allows propagation of the license by redistribution (see section 2(a)(5)). In conclusion, I think it is fair to say that the license isn't free or open as per the definitions, but there may be a possibility of relicensing the content to a free or open license.
- [x] The license is structured to be generally usable to anyone.
- [x] The license seems to have substantial use in Norwegian statistics: just under half of the most recent datasets listed at https://data.norge.no/ are available under this license, the others being either unlicensed or under version 1.0 of the license. With a national government behind it, I think this counts as substantial for SPDX's users!
- [x] My comments on the first factor notwithstanding, the license is clearly primarily intended for free distribution of content.
- [ ] I can't find any indication that the license steward supports or is aware of the submission to SPDX. @evancharlton, do you happen to know if the licence steward does indeed support or know of this submission?

As a side note, this license is very similar to its version 1.0 - it differs only by the addition of the Creative Commons license compatibility clause and the updated name of the relevant government ministry! I'm not sure if such changes really warrant a new major version, but then again, I will admit that 2.0 *does* sound more catchy than 1.2 ;)

My personal opinion is that the license should be accepted into the SPDX License List, especially if @evancharlton has notified the license steward of the submission.

**Comment by DennisClark** [comment]
@evancharlton    Thanks very much for creating a usable text of this license!

**Comment by evancharlton** [comment]
> I can't find any indication that the license steward supports or is aware of the submission to SPDX. @evancharlton, do you happen to know if the licence steward does indeed support or know of this submission?

Other than the email I sent a few days ago, no. I can reach out again this week (and see if I can find a better / additional points of contact to clue in). I briefly tried to find (so I could notify them) the listed steward for NLOD-1.0, but it wasn't readily apparent.

>I'm not sure if such changes really warrant a new major version

I had the same thought when I was updating the files -- I guess they don't practice [semantic versioning](https://semver.org/) in that department 😉

**Comment by swinslow** [comment]
Hi all, thanks for your comments -- particularly @evancharlton for the submission and PR, and @seabass-labrax for the extremely helpful analysis under the inclusion principles!

I agree with @seabass-labrax's feedback, with one clarification. I read the "shall not sub-license or transfer this licence" a bit differently. Personally I take that to say that the licensee is free to **redistribute** the content, but not to **sub-license** it. In other words, the recipient of the content is receiving a new "instance" of the license grant directly from the original licensor.

I believe this is similar to how the GPL family of licenses approach this -- see for instance [GPL-3.0 section 2](https://spdx.org/licenses/GPL-3.0-only.html): "Sublicensing is not allowed" (though GPL-3.0 then goes on in section 10 to provide more explicit details around this).

I guess I don't really see that language as restricting further uses. But any which way, I think you're right that the option to convert to CC-BY-4.0 handles it regardless. So in my view this adequately handles the first point.

Long winded way of saying, I'm a strong +1 to add this to the list.  :)

**Comment by swinslow** [comment]
Discussed on prior legal team call and also during 2021-06-10 call; agreed to add.

@evancharlton I'll add some feedback in the PR -- thank you!
