### ISSUE TITLE
New license request: ABST [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Angie3120** [spdx/license-list-XML#1270]
**1.** License Name: angiesbuyselltrade
**2.** Short identifier: ABST
**3.** License Author or steward: Angela pugh
**4.** Comments: 
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/113
**7.** URL(s): https://angiesbuyselltrade.com
**8.** OSI Status: 
**9.** Example Projects:

**Comment by swinslow** [comment]
Closing as off-topic.
