### ISSUE TITLE
GCC-exception-2.0 - suggestion for "replaceable text"

### ISSUE THREAD

**Issue by ariel11** [spdx/license-list-XML#1275]
Thoughts on making the "Free Software Foundation" replaceable text for non FSF projects that add the linking exception, such as this one: https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/1.0.163. 

They also changed one use of "file" to "library."  Thoughts on also making that replaceable text?

![image](https://user-images.githubusercontent.com/17935946/122132187-3bdab980-cdef-11eb-9951-f09184f4d7a9.png)

**Comment by swinslow** [comment]
Thanks @ariel11 -- I'm +1 on making the changes shown here to make those parts of the template replaceable text.

**Comment by jlovejoy** [comment]
agreed, this makes sense and I don't think "files" to "library" is a substantive change

**Comment by capfei** [comment]
@ariel11 @swinslow Forgot to respond here. 😊  I submitted #1278 to update this. Let me know if I made any mistakes since this is my first attempt.
