### ISSUE TITLE
New license request: CDLA-Permissive-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1282]
**1.** License Name: Community Data License Agreement Permissive 2.0
**2.** Short identifier: CDLA-Permissive-2.0
**3.** License Author or steward: The Linux Foundation
**4.** Comments: More examples of data sets using CDLA-Permissive-2.0 are listed in the LF's announcement at: https://linuxfoundation.org/press-release/enabling-easier-collaboration-on-open-data-for-ai-and-ml-with-cdla-permissive-20/

This is the successor to CDLA-Permissive-1.0, which is already on the SPDX License List: https://spdx.org/licenses/CDLA-Permissive-1.0.html

Also something of a successor in spirit to O-UDA-1.0: https://spdx.org/licenses/O-UDA-1.0.html

I'll follow up with a comment in the license-list-XML repo with my thoughts about this one and the License Inclusion Principles, so that I'm not asking others to do the work here  :)
**5.** Standard License Header: N/A
**6.** License Request Url: http://tools.spdx.org/app/license_requests/115
**7.** URL(s): https://cdla.dev/permissive-2-0/
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://developer.ibm.com/exchanges/data/all/project-codenet/, https://msropendata.com/datasets/0a83fb6f-a759-4a17-aaa2-fbac84577318, https://msropendata.com/datasets/feed8996-d9d4-47b9-9938-44ed298628fc

**Comment by swinslow** [comment]
OK, so, I'll want to have some other folks besides me give this a review, since clearly I'm biased  :)  But to save others from doing the work, here are my thoughts on how this stands up under the License Inclusion Principles:

**Definitive factors:**
* The submitted license must not match another license already on the SPDX License List as per the SPDX matching guidelines.
  * **response**: Yes, doesn't match anything currently on the license list. Has some similarities to [O-UDA-1.0](https://spdx.org/licenses/O-UDA-1.0.html) but is a substantially different license text.
* All OSI-approved licenses will be included on the SPDX License List.
  * **response**: Not submitted to OSI, and likely won't be, since it is intended primarily for use with open data and not software.
* Software licenses that apply only to executables and do not provide for the availability of the source code will not be included on the SPDX License List.
  * **response**: Not applicable.
* The license has identifiable and stable text; it is not in the midst of drafting.
  * **response**: Yes, the text for 2.0 is finalized and published.
* The license steward, if any, is committed to not modifying after addition to the list and to versioning new versions in the future.
  * **response**: Yes, version 2.0 is finalized and will not be modified further without changing the version number.
  
**Other factors (roughly in order of importance):**
1. The license substantially complies with one of the following open source definitions (even if not submitted for approval or these organization have not considered the license):
  * [Open Definition](http://opendefinition.org/od/2.1/en/) from the Open Knowledge Foundation
  * _(omitted others)_
  * **response**: 
    * Yes, I believe CDLA-Permissive-2.0 meets all the requirements of section 2 of the Open Definition. Note in particular that the only real "requirement" under CDLA-Permissive-2.0 when re-sharing Data is to make available the text of this agreement with the shared Data. This is an "Acceptable Condition" under 2.2.4 of the Open Definition.
    * I'd note also that it is intended to be a highly permissive license with extremely minimal obligations, and is seen as compatible with other licenses such as the Creative Commons licenses (see quote from CC in [the announcement](https://linuxfoundation.org/press-release/enabling-easier-collaboration-on-open-data-for-ai-and-ml-with-cdla-permissive-20/))
    * (separately, I'm anticipating that we will submit this to the Open Knowledge Foundation for their formal approval, but I'd prefer not to hold up the SPDX identifier for that)
2. The license is structured to be generally usable by anyone. It is not specific to one project, consortium or corporation.
  * **response**: Yes, it is usable by anyone.
3. The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects.
  * **response**: The initial announcement includes links to several data sets from IBM and Microsoft that were published under CDLA-Permissive-2.0 at launch. I'm anticipating that there will be others, but as a new license this is of course still early, so this factor is probably a partial one.
4. If the license does not substantively comply with one of the above open source definitions, then the license is primarily intended for free distribution of content (including, in the case of software, its source code) with limited restrictions, and meets other factors listed here.
  * **response**: Not applicable, given factor 1 above.
5. The license steward supports or is at least aware of and does not oppose its submission to the SPDX License List.
  * **response**: Yes. 🙋‍♂️

If you have other comments or questions, ask away.

And of course I'll offer to take the lead on prepping the XML file once this is approved.  :)

**Comment by mkdolan** [comment]
Looks good to me. My only additional comment would be to add to your response on 1 that this was also reviewed and approved by Creative Commons for compatibility specifically with CC-BY-4.0 and CC0-1.0. You made a reference to the blog post where the specific licenses are noted but I thought it might help to make it visible here too.

**Comment by seabass-labrax** [comment]
from the release announcement:
> ...collaborating to develop a license agreement that would clearly enable use, modification, and open data sharing, with a particular eye to AI and ML applications

ML, ML... Ah, yes - 'Machine Lawyers'. Watch out, @swinslow! ;)

On a more serious note, I'd say this license would be a good fit for the license list. As you've noted, its fulfilment of the 'substantial use' factor seems somewhat marginal as yet; that said, getting IBM and Microsoft involved is a great achievement - congratulations on that! That the licence is specifically designed to meet the Open Definition is a positive trait for meeting the inclusion guidelines, and due to that (along with meeting all the more technical factors, of course) my opinion would be to accept this license.

**Comment by jlovejoy** [comment]
+1 on adding it

**Comment by bsdimp** [comment]
I'm sure that we'll start to see licenses that try to curb the whole 'read all the GPL code, create a tool that knows how to code based on that corpus, but produces code with different licenses' issue that is burning up my twitter feed...

But be that as it may, I agree this should be accepted.
