### ISSUE TITLE
New license request: pkin [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by AristodamusAdairs** [spdx/license-list-XML#1290]
**1.** License Name: PkIn License
**2.** Short identifier: pkin
**3.** License Author or steward: Aitzaz Imtiaz
**4.** Comments: 
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/117
**7.** URL(s): https://github.com/AristodamusAdairs/PkIn/blob/main/LICENSE
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/JeffTheK/ubiquit/blob/main/src/Tokenizer/LICENSE, https://github.com/AristodamusAdairs/Banking-System/blob/main/LICENSE

**Comment by jlovejoy** [comment]
Hi, thanks for your license submission and welcome to the SPDX community.

I don't think this license meets the SPDX license inclusion guidelines for a couple reasons:
https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md (for references)
- it seems to be trying to place various restrictions on use and thus does not meet any of the open source definitions. 
- it is also very hard to read and doesn't make sense in a few places, as well as having some potentially legally incorrect statements. While our license inclusion guidelines don't explicitly address quality of drafting, I would implicitly consider "identifiable and stable text" to mean it should be understandable which also leans towards the requirement of being generally usable
- it appears to really only be used by you, the drafter of the license

**Comment by jlovejoy** [comment]
thanks! maybe use a license that already exists!!  ;)
