### ISSUE TITLE
New license variants: mpich2-general and mpich2-permission-only

### ISSUE THREAD

**Issue by jonassmedegaard** [spdx/license-list-XML#1292]
I argue that license `mpich2` is only really this:
> Permission is hereby granted to use, reproduce, prepare derivative works, and to redistribute to others.

I therefore propose that surrounding text be marked as optional, and maybe the `GOVERNMENT LICENSE` part be moved out as a separate license.

Reason is that some uses include only that essential part.

See https://sources.debian.org/src/openmpi/4.1.0-10/ompi/debuggers/msgq_interface.h/?hl=19#L19 and https://sources.debian.org/src/armci-mpi/0.3.1%7Ebeta-1/COPYRIGHT/?hl=11#L11 for examples of such uses.

**Comment by jonassmedegaard** [comment]
Oh.  Now I see why it is not optional: The introduction text states all of the non-disclaimers (i.e. "the notice") and the disclaimers "must be included".

I'll reframe this issue as a request to create a new license instead...

**Comment by jonassmedegaard** [comment]
I propose to create a new license:
> Permission is hereby granted to use, reproduce, prepare derivative works, and to redistribute to others.

I.e. the essential part of the existing `mpich2` license, without the (very specific) copyright statements or government license or disclaimers.

I propose to call this new license `MIT-mpich2` to indicate both how it is an MIT-style license and that its exact wording it same as the essential part of `mpich2`.

**Comment by jonassmedegaard** [comment]
Here's how Fedora [compares](https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#mpich2_variant) this newly proposed license to `MIT`:
> This is missing the "anti-publicity-use clause", and doesn't mention sublicensing, but otherwise, it is functionally identical to MIT.

(yeah, they then go on to provide the `mpich2` license content, but their comment can only possibly be about the essential part, since mandatory inclusion of a specific author certainly isn't "functionally identical to MIT")

**Comment by jlovejoy** [comment]
do you have examples where only the "permission..." line exists as the license text?

**Comment by jonassmedegaard** [comment]
Yes, the second example I provided above initially.
(yes, the text continues to list more licensing text, but I will argue that it is two separate licenses - first an MIT-ish license (with no trailing disclaimers) and then a separate BSD-ish license.

**Comment by jlovejoy** [comment]
ok, so it looks like there are 3 variants (sigh)!
- the one Fedora captured here: https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#mpich2_variant - which SPDX added to the license list back in 2013/14 when adding a bunch of Fedora licenses. Looks like it's still in use, as I found it here: https://github.com/pmodels/mpich/blob/main/COPYRIGHT (but we should probably add some markup for the authors section)
- this version, which is just the permission and disclaimer parts: https://sources.debian.org/src/openmpi/4.1.0-10/ompi/debuggers/msgq_interface.h/?hl=19#L19
- and then the permission statement only variant: https://sources.debian.org/src/armci-mpi/0.3.1~beta-1/COPYRIGHT/?hl=11#L11

Is the code under these license variants the kind of thing that is probably in all Linux distros? (if you have any idea about that)

(Reason I ask, is Fedora is looking at adopting SPDX identifiers and one of the potential challenges is the possibility of a lot of stuff like this - old permissive licenses with lots of little variations that SPDX wouldn't call a match)

**Comment by jlovejoy** [comment]
(marking as 3.14 - but I suspect we may need to discuss a bit more depending on the above question!)

**Comment by jonassmedegaard** [comment]
Sorry, I have no knowledge of the popularity of the license variations.

**Comment by jlovejoy** [comment]
pinging @pombredanne again - would love to hear what you might be seeing via Scancode on these variants!

**Comment by swinslow** [comment]
Agree with @jlovejoy's summary [here](https://github.com/spdx/license-list-XML/issues/1292#issuecomment-890256652). The three variants we're aware of appear to be:

1. [mpich2](https://spdx.org/licenses/mpich2.html) (already on SPDX license list);
2. A variant of mpich2 that omits the "This software was authored by" reference, the GOVERNMENT LICENSE section and the first sentence of DISCLAIMER; and
3. A variant which includes literally just the "Permission is hereby granted..." sentence (apparently followed by [BSD-3-Clause-Open-MPI](https://spdx.org/licenses/BSD-3-Clause-Open-MPI.html)).

I'm +1 to add 2 and 3 as separate variants. For 3 I would just include the "Permission is hereby granted" sentence and not the rest since BSD-3-Clause-Open-MPI already exists.

I wouldn't call any of these "MIT-mpich2". Probably something like "mpich2-general" for 2 and "mpich2-permission-only" for 3, though I don't feel strongly about either of those names.

**Comment by jlovejoy** [comment]
that makes sense, I agree, @swinslow

**Comment by johnmhoran** [comment]
+1 to add

**Comment by seabass-labrax** [comment]
Also in agreement to add.

**Comment by swinslow** [comment]
Discussed on 2022-02-24 legal team call, agreed to add variants 2 and 3 with the ID's mentioned at https://github.com/spdx/license-list-XML/issues/1292#issuecomment-1050028180

**Comment by swinslow** [comment]
@jonassmedegaard With these two variants approved, would you be able to create a PR with the XML files and test text files for each?

**Comment by swinslow** [comment]
No PR yet; moving to next release

**Comment by pombredanne** [comment]
@jlovejoy sorry for missing to see and reply to your pings!

Here is how the latest scancode detects these:
 
- both detected as full text of `mpich2` 
  - https://github.com/pmodels/mpich/blob/main/COPYRIGHT
    - See the scan details [COPYRIGHT.scancode.yml.txt](https://github.com/spdx/license-list-XML/files/8649444/COPYRIGHT.scancode.yml.txt)
  - https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#mpich2_variant   
    - See the scan details  [mpich2_variant.scancode.yml.txt](https://github.com/spdx/license-list-XML/files/8649447/mpich2_variant.scancode.yml.txt)

  
- detected partially as the beginning of `mpich2` from L2 to L15 and then as a `BSD-3-Clause-Open-MPI` full text afterwards
  - https://sources.debian.org/src/armci-mpi/0.3.1~beta-1/COPYRIGHT/?hl=11#L11
    - See the scan details [COPYRIGHT.1.scancode.yml.txt](https://github.com/spdx/license-list-XML/files/8649437/COPYRIGHT.1.scancode.yml.txt)

- detected (twice) as a rarer, not-yet-named "other permissive" license https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/rules/other-permissive_327.RULE .... I guess this is seen frequently enough from its use in various MPI tools. For info here is the timeline of Etnus https://totalview.io/about 
  - https://sources.debian.org/src/openmpi/4.1.0-10/ompi/debuggers/msgq_interface.h/?hl=19#L19
    - See the scan details [msgq_interface.h.scancode.yml.txt](https://github.com/spdx/license-list-XML/files/8649483/msgq_interface.h.scancode.yml.txt)

**Comment by jlovejoy** [comment]
have started #1554 to add markup to mpich2 and add one of the variants here from Debian https://sources.debian.org/src/openmpi/4.1.0-10/ompi/debuggers/msgq_interface.h/?hl=19#L19

but not sure this should be mpich2-something for name/id?? I put it as mpi-permissive for now, but need some input on this. Could also use Etnus as that seems to be the original source??
@pombredanne @jonassmedegaard @swinslow - opinions

considering holding off on the one-liner for larger reasons.

**Comment by jlovejoy** [comment]
closing for 3.18 and new issue at #1566 will retain remaining issue
