### ISSUE TITLE
New license request: DL-DE-BY-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xenon-dev** [spdx/license-list-XML#1306]
**1.** License Name: Datenlizenz Deutschland Namensnennung v2.0
**2.** Short identifier: DL-DE-BY-2.0
**3.** License Author or steward: govdata.de
**4.** Comments: Used by LGLN for open-geo-data projects
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/125
**7.** URL(s): https://www.govdata.de/dl-de/by-2-0
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://opengeodata.lgln.niedersachsen.de/#dop

**Comment by xenon-dev** [comment]
Please note: This License request was submitted by me through the online tool: "https://tools.spdx.org/app/submit_new_license/", which validates the license using the ascii codec (instead of something like UTF-8). I had to manipulate the license name a bit, in order to get it trough the filtering:
The correct name, like given on the page is: "DL-DE->BY-2.0" and would also be put in like that in license headers later on, but it would not match the given short-identifier here, which could lead to problems... Can this be somehow correct afterwards or would you think it would still work?

**Comment by seabass-labrax** [comment]
@xenon-dev, welcome to SPDX!

There are really three types of name when it comes to entries to the License List. There is the short identifier, the name which is shown on <https://spdx.org/licenses> and the `titleText`, which is only shown in the license text itself. It is perfectly fine if those names differ from each other, so no need for concern there!

Thank you for your new license request; I hope to review it soon. :)

**Comment by swinslow** [comment]
Hi @xenon-dev, 

Just a comment on the license short identifier (e.g., what would appear on https://spdx.org/licenses as @seabass-labrax noted, and also in `SPDX-License-Identifier: _______` tags as described at https://spdx.dev/ids:

The valid characters for these identifiers are letters, numbers, hyphen (`-`) and period (`.`). See [Appendix IV of the SPDX spec](https://spdx.github.io/spdx-spec/appendix-IV-SPDX-license-expressions/) for more details. That means that the `>` character wouldn't be able to be included in the identifier.

But DL-DE-BY-2.0 should be fine as an identifier (if the license is accepted to add to the License List, of course) and the full name + titleText may be able to accommodate a broader set of characters.

**Comment by jlovejoy** [comment]
I'm in favor of adding this as I think it meets the inclusion guidelines

**Comment by swinslow** [comment]
I'm also +1 to adding, I think it meets the [inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) and aligns with several other national governments' open data licenses that we've added.

**Comment by jlovejoy** [comment]
@xenon-dev - see comment above on the short identifier - just want to make sure you are aware and then we can add it!

**Comment by xenon-dev** [comment]
Is there any particular reason the accepted license was pushed to the next release? We would have like to use the check against the list to give credit to the correct license. Is there anything I could help with? Open questions?

**Comment by seabass-labrax** [comment]
@xenon-dev, thanks for bringing this up! I think it just fell through the net (sorry about that!), but I shall make the pull request for addition so that it can make it into release 3.16 :)

**Comment by seabass-labrax** [comment]
Should I include both the German and English texts in the XML, or just the German? https://www.govdata.de/dl-de/by-2-0 shows both.

**Comment by swinslow** [comment]
@seabass-labrax Given the way they're documenting it here, I would be inclined to include both. That's the same approach we took for https://spdx.org/licenses/MulanPSL-2.0.html where they did the same thing.

That said, if it's used differently in practice (e.g. if it's typically included in distributions with just the German part) then perhaps we would still include the English part as well, but mark it as optional.

**Comment by seabass-labrax** [comment]
@xenon-dev, it's committed and ready for the 3.16 release now! :) Thanks again for opening this issue. Happy Christmas! :christmas_tree:
