### ISSUE TITLE
New license request: bzip2 1.0.8

### ISSUE THREAD

**Issue by tigerswell** [spdx/license-list-XML#1315]
1. License Name: bzip2 and libbzip2 License v1.0.8
2. Short identifier: bzip2-1.0.8
3. License Author or steward: Julian Seward
4. Comments: Update of the bzip2 licenses currently on the SPDX license list
5. Standard License Header: none
6. License Request Url: (the SPDX online tool wasn't working for me for some reason)
7. URL(s): https://sourceware.org/git/?p=bzip2.git;a=blob;f=LICENSE;hb=bzip2-1.0.8
8. OSI Status: Not Submitted
9. Example Projects: https://www.sourceware.org/bzip2/

**Comment by jlovejoy** [comment]
@tigerswell - I did a license-diff and the only change I could see between this and 1.0.6 is the copyright notice year, which I would not consider as a new license (or version number...)
Did you see something different?

If not, maybe we should reach out to the license steward, since there is one and point this out (and then put a note in our Note field that 1.0.8 isn't different?)

**Comment by tigerswell** [comment]
@jlovejoy I did not see anything different, but since 1.0.5 also wasn't substantially different than 1.0.6, I wasn't sure how SPDX tracked nominal version changes. For contacting the steward, is the purpose to ask why there is a new version?

One of our programmers is using software licensed under 1.0.8, and they're using SPDX identifiers to track. If we make a note in 1.0.6 that 1.0.8 isn't different, I can recommend that he use the SPDX identifier for 1.0.6 then.

**Comment by swinslow** [comment]
@tigerswell and @jlovejoy Good points -- note also that there's a related issue open at https://github.com/spdx/license-list-XML/issues/1223, regarding whether there should be separate entries for 1.0.5 and 1.0.6 at all.

Let's plan to discuss that one and also this one at an upcoming legal team call -- I know you are out for this one, so perhaps we'll set some time for it on the call two weeks from now.

**Comment by tigerswell** [comment]
Okay, thanks @swinslow

**Comment by swinslow** [comment]
Discussed on 2021-09-02 legal team call, agreed to add markup to make bottom line replaceable text.
