### ISSUE TITLE
QPL-1.0 Link is invalid

### ISSUE THREAD

**Issue by tim-janik** [spdx/license-list-XML#1316]
The QPL-1.0 link has aged:
http://doc.qt.nokia.com/3.3/license.html

It is not reachable because doc.qt.nokia.com ceased to exist.
This looks like it is a suitable replacement link:

https://doc.qt.io/archives/3.3/license.html

**Comment by seabass-labrax** [comment]
Welcome to SPDX, @tim-janik! Thank you for bringing this to our attention, and particularly for finding a more current URL for the license! We don't remove broken cross-reference links (as they might still be useful with sites such as the Wayback Machine), but we can certainly add new ones :)
