### ISSUE TITLE
Missing required license text for GPL-2.0-with-OpenSSL-exception in cryptsetup

### ISSUE THREAD

**Issue by farislam** [spdx/license-list-XML#1324]
Hello All,
We are facing issue with GPL-2.0-with-OpenSSL-exception in cryptsetup. We need a valid license for it.

**Comment by pombredanne** [comment]
> We are facing issue with GPL-2.0-with-OpenSSL-exception in cryptsetup. We need a valid license for it.

Can you clarify what you mean?

FWIW, there are two exceptions in use: 
- to GPL https://gitlab.com/cryptsetup/cryptsetup/-/blob/master/COPYING#L342
- and to LGPL https://gitlab.com/cryptsetup/cryptsetup/-/blob/master/COPYING.LGPL#L505 

in any case this would be an exception and not a new license.

**Comment by jlovejoy** [comment]
closing, as consolidated all OpenSSL variants into #1356
