### ISSUE TITLE
AFL Licenses prior to 3.0 inconsistent OSI Approved

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#1327]
The Academic Free Licenses versions 1.0, 1.1, 2.0, and 2.1 are marked as OSI approved in the license list, however, these licenses do not show up on the [OSI list of approved licenses](https://opensource.org/licenses/alphabetical).

If there is agreement we should remove the OSI approved from these licenses, I can create a PR.

**Comment by seabass-labrax** [comment]
A quick grep of the OSI's [license-discuss](http://lists.opensource.org/pipermail/license-discuss_lists.opensource.org/) and [license-review](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/) mailing list archives doesn't yield even but a mention of older versions of the AFL, let alone an approval status! The `isOsiApproved` field in the source files also predates our move to the XML format, so there's no Git history to look back in.

Unless anyone has evidence to the contrary, I'd concur with you that the `isOsiApproved` fields should be set to false.

**Comment by seabass-labrax** [comment]
The Wayback Machine (following the `crossRef` links in our XML files) seems to indicate that the OSI *had* approved the earlier versions, but after each new release of the license had removed any mention of the previous version by overwriting their webpage.

The plot thickens! :)

**Comment by goneall** [comment]
> The Wayback Machine (following the crossRef links in our XML files) seems to indicate that the OSI had approved the earlier versions

That is interesting.  There are other licenses on the OSI website where they maintained the previous versions.  I wonder why the difference?  Is this a conscious decision by the OSI to drop support of the previous versions of the license and we should update our OSI flag in SPDX, or is this just an artifact of how they are maintaining their website?

If anyone has a contact at OSI - it would be interesting to get their read on this issue.

**Comment by vmbrasseur** [comment]
I've emailed the l-d list asking for information. If that doesn't work then maybe contacting Pamela or Fontana directly could help.

**Comment by seabass-labrax** [comment]
> I've emailed the l-d list asking for information. If that doesn't work
> then maybe contacting Pamela or Fontana directly could help.

Thank you, @vmbrasseur! It seems the OSI's API doesn't mention the
earlier version either; I'm very intrigued to hear their response on the
list.

**Comment by goneall** [comment]
@vmbrasseur Thanks for update!

So, based on this, should we remove this OSI approved from the AFL licenses prior to 3.0?

**Comment by vmbrasseur** [comment]
These licenses are probably still out there in the wild, so removing might not be the right approach. Do we have a process for handling superseded licenses?

**Comment by seabass-labrax** [comment]
In general, we wouldn't want to remove them from the SPDX License List
altogether; in this case it's more whether or not the 'OSI-approved'
metadata is appropriate for these older licenses. I think I would
personally lean towards leaving them listed as OSI-approved: Larry
confirmed that they were at one point approved, and I haven't come
across any announcement to say that the approval status was later
revoked by the OSI.

Maybe we should bring this up at a future Legal Team meeting (the next
one is on the 16th of September) - what do you think, @vmbrasseur,
@goneall?

**Comment by vmbrasseur** [comment]
+1 to leaving them as-is, unless we have a way to mark them as superseded in which case do that. (I confess I haven't looked into it yet)

Generally in favour of covering it on the next call, with the caveat that Thursday the 16th is the day of OSI's POSI conference so I won't be at the Legal Team meeting that day. Thankfully, though, I'm not required for this conversation. :-)

**Comment by jlovejoy** [comment]
oh dear, I didn't see this lengthy discussion until now. We (well, mostly me from the SPDX side and a few people on the OSI side) spent a lot of time covering this topic when we were ensuring SPDX had *all* OSI-approve licenses on the SPDX License List way back in 2011. This issue of older licenses no longer appearing on the OSI site came up a few time (for these licenses and others) and the answer was that OSI does not (or has not to date) "un" approved licenses it previously approved. Their website has changed a lot over the years and it has never seemed to be a full and accurate reflection of every license ever approved (unfortunately).

Incidentally, the answer to these questions are probably in the SPDX-legal mailing list archives :)  

Having already been down this road before, I would leave everything as it is.  If, at some point in the future, OSI decides to officially "un-approve" licenses, then we will cross that bridge.

**Comment by goneall** [comment]
Based on @jlovejoy description above, it looks like we leave this as is and close this issue.

OSI is re-activating a project to maintain a machine readable version of their list of OSI approved licenses. I've added an [issue ](https://github.com/OpenSourceOrg/licenses/issues/66) for their repo to include previous versions of AFL and closing this issue.

If I get feedback from OSI that they are no longer approved from the new issue, I'll reopen this with the new information.
