### ISSUE TITLE
New License: Jam

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1332]
This has been OSI-approved: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2021-September/005216.html

License text: 
License is hereby granted to use this software and distribute it freely,
as long as this copyright notice is retained and modifications are
clearly marked.

ALL WARRANTIES ARE HEREBY DISCLAIMED.

**Comment by jlovejoy** [comment]
best I can find for a URL is: https://web.archive.org/web/20160330173339/https://swarm.workshop.perforce.com/files/guest/perforce_software/jam/src/README

recommending:
Full name: JAM License
short identifier: JAM

**Comment by jlovejoy** [comment]
also see: https://github.com/gorlak/Jam for something current, not dependent on Wayback Machine

**Comment by latk** [comment]
The license is not yet OSI-approved. The quoted email is merely a “recommendation of the License Committee to the Board”, but the OSI Board will very likely pass the approval as recommended.

**Comment by jlovejoy** [comment]
@latk  - thanks for the clarification! We'll wait for official approval!

**Comment by mkdolan** [comment]
This appears to be a project that ended in 2014. "The company announced that version 2.6 released in August 2014 was the last Perforce Jam release." The github link from @latk appears to be someone's personal fork of the project that Perforce took down. 

Does this meet the license inclusion principles?

https://en.wikipedia.org/wiki/Perforce_Jam

**Comment by swinslow** [comment]
Not sure about OSI review status, but I'd lean towards including this. I'm not doing a full inclusion principles analysis at the moment, but very roughly:

* looks to me like it meets OSD principles -- although there isn't an explicit statement of "you may modify," it includes a requirement that modifications be clearly marked, so implicitly it appears to permit modifications
* as a historical license, although it looks to have been used primarily for Perforce Jam, it looks like that has been used as part of Boost and made its way into various other real-world projects and products, e.g.:
  * https://www.boost.org/doc/libs/1_35_0/doc/html/jam.html
  * https://www.cisco.com/c/en/us/td/docs/security/vpn_client/anyconnect/anyconnect44/license/open_source/Open_Source_Used_in_Cisco_AnyConnect_Secure_Mobility_Client_4-4.html (at 1.4.1)
  * https://static.dc.siemens.com/cnc4you/OSS_Documents/ReadMe_OSS_SinuTrain_for_SINUMERIK_Operate_4.7-ed4.htm (it's a massive list of licenses / copyrights but I see it in there)

so I'd lean towards being a +1 to add it.

**Comment by seabass-labrax** [comment]
I couldn't find a distinct license file for this 'in the wild' - it always seems to be a section in the README.

If we decide to add it, we might have to get our head around the unusually decorative copyright notice!

```
    /+\
    +\	Copyright 1993-2014 Christopher Seiwald and Perforce Software, Inc.
    \+/
```

**Comment by jlovejoy** [comment]
+1 to add now and make sure OSI knows what short identifier is for when/if they approve it (and to update OSI-approved tag at that point)

**Comment by swinslow** [comment]
Discussed on 2021-12-23 call, agreed to add

**Comment by swinslow** [comment]
Submitted #1391 to add this.

@seabass-labrax Note that I didn't add the "unusually decorative" part of the copyright notice that you helpfully mentioned [here](https://github.com/spdx/license-list-XML/issues/1332#issuecomment-990099309).  :)  

I think since the copyright text is meant to be replaceable anyway, it's likely fine to just include the actual copyright notice bit rather than the "sparkle", which would probably show up as garbage characters and look incorrect when rendered on the license list website.

**Comment by seabass-labrax** [comment]
Sounds good, @swinslow. I'm just running tests manually to see if it throws any errors when the decorative copyright notice is included.

**Comment by seabass-labrax** [comment]
All tests pass! :)

**Comment by swinslow** [comment]
phew  :)  thanks!
