### ISSUE TITLE
New license request: Community-Spec-1.0

### ISSUE THREAD

**Issue by zvr** [spdx/license-list-XML#1344]
1. License Name: Community Specification License 1.0
2. Short identifier: Community-Spec-1.0
3. License Author or steward: [Joint Development Foundation](http://www.jointdevelopment.org)
4. Comments: Used for spec writing, including SPDX :-)
5. Standard License Header:
6. License Request Url: _manually submitted as in issue_
7. URL(s): https://github.com/spdx/governance/blob/main/1._Community_Specification_License-v1.md
8. OSI Status: Not Submitted (I think)
9. Example Projects: SPDX spec

**Comment by swinslow** [comment]
@seabass-labrax looks like @zvr beat both of us to it  :)  Thank you @zvr! I'll review the PR.
