### ISSUE TITLE
documentation: how and when to use new license review template

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1348]
@seabass-labrax  made a license review template for new license issues
@vmbrasseur suggested we document when, how to use it

where should this be documented?

**Comment by jlovejoy** [comment]
we also now have a template for license decisions, so maybe the instructions for these can be combined? I don't think they need to be lengthy

**Comment by vmbrasseur** [comment]
Howdy. Commenting so I can get assigned to this one.

**Comment by jlovejoy** [comment]
closing this as it's part of #1565
