### ISSUE TITLE
New license request: Elastic-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by abernix** [spdx/license-list-XML#1349]
**1.** License Name: Elastic License 2.0 (ELv2)
**2.** Short identifier: ELv2
**3.** License Author or steward: Elasticsearch B.V.
**4.** Comments: Having an official SPDX designation would be useful!
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/127
**7.** URL(s): https://www.elastic.co/licensing/elastic-license
**8.** OSI Status: Rejected
**9.** Example Projects: https://github.com/elastic/elasticsearch, https://github.com/elastic/kibana, https://github.com/enonic/app-contentstudio-plus, https://github.com/StarRocks/starrocks

**Comment by jlovejoy** [comment]
# New submission review

## Has the license been approved by the OSI?
* No, it was submitted and rejected

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines? 
* No

### If a software license, does it apply to source code and not only to executables?
* Yes

### Does the license have identifiable and stable text, and is not in the midst of drafting?
* appears to be so

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?
* appears so, as it is versioned

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
* no, this clause put a restriction on use, "You may not provide the software to third parties as a hosted or managed service, where the service provides users with access to any substantial set of the features or functionality of the software."

### 2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
* it is used for a substantially popular project

### 3. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?
* yes, although I don't know of any other project that uses it

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?
* I think it's roughly a "source available" license with the one use restriction

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?
* not sure

## Summary of factors / outcome
* would be good to get a comment from a rep of Elastic on stability, versioning, and if any other project uses it before making a determination

**Comment by xeraa** [comment]
I work for Elastic and we would welcome the addition. Answering the open questions below:

> Has the license been approved by the OSI?

It has not been submitted to OSI (and thus not rejected) — is there another status than yes / no?

> Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

To our knowledge it is unique and the reason why Heather Meeker created it for Elastic ([related whitepaper](https://www.coss.community/cossc/elastic-license-2-0-and-the-evolution-of-open-source-licensing-3jb3)).

> Does the license have identifiable and stable text, and is not in the midst of drafting?

Yes, this is the stable license.

> Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

Yes, it is versioned.

> 2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?

Besides Elastic's own projects (including https://github.com/elastic/elasticsearch, https://github.com/elastic/kibana, https://github.com/elastic/eui,...) it is used for example in:

* https://github.com/StarRocks/starrocks
* https://github.com/airbytehq/airbyte
* https://github.com/apollographql/federation

> 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

We support it!

**Comment by jlovejoy** [comment]
re: OSI submission,  I believe our submission form does have a "not submitted" option, but that wasn't picked. In any case, thanks for the clarification.

**Comment by jlovejoy** [comment]
and there are two use restrictions which would make it not free/open:

"You may not provide the software to third parties as a hosted or managed service, where the service provides users with access to any substantial set of the features or functionality of the software.

You may not move, change, disable, or circumvent the license key functionality in the software, and you may not remove or obscure any functionality in the software that is protected by the license key."

**Comment by swinslow** [comment]
Agree with @jlovejoy's [analysis above](https://github.com/spdx/license-list-XML/issues/1349#issuecomment-964448541).

Given the usage by some significant projects, I think the balance of factors in that analysis and the follow-up comments tilts in favor of adding it to the list.

One comment: I'd lean towards "Elastic-2.0" as the short identifier, rather than "ELv2". SPDX generally uses "-X.Y" suffixes to denote licensing, and I think it will be clearer to specify "Elastic" rather than "EL" which is close to the commonly-used "EPL-2.0" (Eclipse).

**Comment by xeraa** [comment]
I don't think we plan on having minor versions of the license, but if you standardize on "-X.Y" we can go with that.

Most licenses seem to use an abbreviation that's why we thought that "EL" would make sense here.

Thanks a lot for moving this forward :)

**Comment by silverhook** [comment]
+1 on @jlovejoy’s analysis from my side, as well as on @swinslow’s naming suggestion of `Elastic-2.0`.

**Comment by jlovejoy** [comment]
+1 as to @swinslow naming suggestion for the short id, as I think this is more aligned to how the license is known. sounds ok @xeraa ?

and yes, we do tend to standardize on -X.Y as per: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md

thanks

**Comment by xeraa** [comment]
For clarity and consistency that sounds reasonable. Thank you!

**Comment by botic** [comment]
I'm thinking about releasing a project under this license and was looking for the spdx id right now. Looking at this discussion I endorse `Elastic-2.0` as short name and hope for an imminent inclusion ;)

**Comment by jlovejoy** [comment]
as per comments above - accepted to be added -using the following:
Full Name: Elastic License 2.0
Short identifier: Elastic-2.0

**Comment by swinslow** [comment]
@abernix and @xeraa, this has now been agreed to add to the license list.

The remaining step is to add an XML file for the license template, together with a test text file to test it against. The process is documented at https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md.

Would one of you be able to submit a PR to add these? The next license list release is targeted for end of January, so if you can submit it before then, it'll be included in the next release. Thanks!

**Comment by xeraa** [comment]
Thanks! I've opened https://github.com/spdx/license-list-XML/pull/1394

**Comment by abernix** [comment]
Just catching up on this, but thank you all, and thanks @xeraa for beating me to the PR!

`Elastic-2.0` indeed seems like a short-enough identifier and I support that.  It's immediately recognizable and not ambiguous.  I was merely going for as short as possible and Elastic already had coined ELv2 to some degree, so it seemed reasonable. 😸 

And one note to @jlovejoy's comment:

> re: OSI submission, I believe our submission form does have a "not submitted" option, but that wasn't picked.

Yup, that's probably my bad.  Indeed, the form does have this option.  In my own case, the actual correct option for me was "I don't know" and I just assumed it had been submitted.  I didn't actually realize that field was perhaps optional (maybe `-` is a suitable option?).  Perhaps I should have chose `-`!  Anyhow, doesn't matter now.  Thanks again all!

**Comment by swinslow** [comment]
Merged #1394 -- thank you all for your help on this one.

This will show up on the SPDX License List website beginning in the 3.16 release, currently targeted for the end of January / early February.
