### ISSUE TITLE
New license request: FDK-AAC

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1355]
Full name: Software License for The Fraunhofer FDK AAC Codec Library for Android
Short name: FDK-AAC
This license is currently used in Fedora and on the Fedora "good" license list
See text at: https://fedoraproject.org/wiki/Licensing/FDK-AAC

on behalf of @conan-kudo from email on mailing list

**Comment by jlovejoy** [comment]
Given this license has already been determined to meet the Fedora free/open guidelines and is currently used in a major Linux distro, it surely meets SPDX License List inclusion guidelines.

I recommend adding

**Comment by seabass-labrax** [comment]
I'm more than happy to take this one on, @jlovejoy! :)

**Comment by swinslow** [comment]
I'm +1 to adding this as well.

Note that I _think_ this is also on the [FSF list](https://www.gnu.org/licenses/license-list.en.html#fdk) as "free but GPL incompatible". I haven't run a compare to confirm it's the exact same text, but from a first glance it looks like it.

@seabass-labrax I wasn't able to get the 3.15 release pushed this past weekend, so if you were able to prep a PR for this, we can likely get it approved and merged at the legal team call this Thursday to include in 3.15. If that's doable from your side?  :)  Thanks as always!

**Comment by jlovejoy** [comment]
@seabass-labrax - great, thanks!  (will change milestone tag, once PR is made)
