### ISSUE TITLE
New license request: AzFOSS

### ISSUE THREAD

**Issue by azraeljd** [spdx/license-list-XML#1365]
1. License name: Azratek Free and Open Source Software License
2. Short identifier: AzFOSS
3. License author or steward: Azratek (@azratektechnology)
4. Comments:
5. Standard License Header: 
```
Copyright (c) <YEAR> <COPYRIGHT HOLDER>.
This software is freely redistributable under the terms
of the Azratek Free and Open Source Software License.

Disclaimer:
THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT ANY WARRANTY. IN NO EVENT SHALL THE
AUTHORS, CONTRIBUTORS, NOR THE COPYRIGHT HOLDERS BE LIABLE FOR ANY DAMAGE
CAUSED BY THE USE OF THIS SOFTWARE.
```
6. URL(s): https://github.com/azraeljd/azfoss
7. OSI Status: Not Submitted
8. Example Projects: https://github.com/azratektechnology/systemdog

**Comment by jlovejoy** [comment]
I have the same comments for this as for #1366 

It also appears that this is used by one project which is brand new and the license is written by the same org.

**Comment by swinslow** [comment]
+1 to @jlovejoy's comment here and in #1366, as a new license without substantial usage I wouldn't view this as meeting the license inclusion principles at present.

**Comment by silverhook** [comment]
+1 on @jlovejoy ’s comments as well.

**Comment by jlovejoy** [comment]
marking as not accepted and closing issue

**Comment by azraeljd** [comment]
Thank you for the reviews. We will revise the license and resubmit the license when it has substantial use.
