### ISSUE TITLE
New license request: AzDocu

### ISSUE THREAD

**Issue by azraeljd** [spdx/license-list-XML#1366]
1. License name: Azratek Documentation License
2. Short identifier: AzDocu
3. License author or steward: Azratek (@azratektechnology)
4. Comments: Currently, there are no projects using the AzDocu license, because the license is new.
5. Standard License Header: 
```
Copyright (c) <YEAR> <COPYRIGHT HOLDER>.
This documentation is freely redistributable under the terms
of the Azratek Documentation License.
```
6. URL(s): https://github.com/azraeljd/azdocu
7. OSI Status: Not Submitted
8. Example Projects: N/A

**Comment by jlovejoy** [comment]
Hi, thanks for the submission - I'm assuming this if for this license: https://github.com/azraeljd/azdocu/blob/main/azdocu/azdocu.txt

Considering this looks to be a brand new license, not yet in use, it wouldn't meet our guidelines related to substantial use. (see https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md )

But I also have to ask and from a lawyer's point of view - why create a new license that is effectively the same as existing licenses, but has more ambiguous terms? (e.g., what is a "compatible license"?)

**Comment by swinslow** [comment]
+1 to @jlovejoy's comment, as a new license I wouldn't view this as meeting the license inclusion principles at present.

**Comment by azraeljd** [comment]
Thank you for the reviews. We will revise the license and resubmit the license when it has substantial use.
