### ISSUE TITLE
New license request: KiCad-libraries-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by seabass-labrax** [spdx/license-list-XML#1367]
**1.** License Name: KiCad Libraries Exception
**2.** Short identifier: KiCad-libraries-exception
**3.** License Author or steward: The KiCad Project
**4.** Comments: The KiCad Libraries Exception applies to the CC-BY-SA-4.0 license. This was brought up on the FSFE's REUSE mailing list by Chris Wilson, who would like to use this exception to describe KiCad library packages. Chris asked for the ability to define custom exceptions for use with the REUSE specification, but adding this exception to the SPDX License List should satisfy this particular use-case.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/129
**7.** URL(s): https://www.kicad.org/libraries/license/
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://kicad.github.io/symbols/, https://kicad.github.io/footprints/, https://kicad.github.io/packages3d/

**Comment by swinslow** [comment]
Interesting, I hadn't seen this one before. To save folks the click-through, it's the following text:

> To the extent that the creation of electronic designs that use 'Licensed Material' can be considered to be 'Adapted Material', then the copyright holder waives article 3 of the license with respect to these designs and any generated files which use data provided as part of the 'Licensed Material'.

From poking just a bit, I see at least one example of this being used by someone other than the KiCad project itself: https://github.com/johnwinans/jb-kicad-library/blob/master/LICENSE.md (though also clearly KiCad-community-related)

I haven't thought through a full analysis yet, but gut reaction I'm cautiously a +1 on adding this. It's clearly intended as a license exception, it's structured in a way as to be usable by anyone (even if it's a fairly narrow topic area), and I know KiCad is a pretty widely used project in its space.

**Comment by silverhook** [comment]
After very quickly skimming it, from what I can tell, it waives _§3 License Conditions_  – i.e. attribution (BY) and copyleft (SA) obligations – of CC-BY-SA-4.0 when it comes to _electronic designs_ using/embedding (parts of) the KiCAD libraries. So it does seem to not be a general exception, but have a limitation to what it applies to and TBH it makes sense to me.

I think the wording is quite easy to understand, and I don’t see any holes (I wonder why they didn’t limit it to just §3.b SA, but that’s probably a practical choice in the field).

It may not be a software license, but it is an exception to a license we already have in the SPDX license list and it is in a field that’s very close to software – hardware design.

As @swinslow, I would tend to cautiously +1 on this. The only flaw I see is that it is not very broadly used outside of KiCAD. Then again, KiCAD is a pretty well known project and common tool in the OSHW community.

**Comment by silverhook** [comment]
@seabass-labrax I assumed it was to avoid etching a whole lengthy attribution list on the board, but as I’m not _that_ familiar with the PCB processes, I didn’t want to muddy any waters :)

**Comment by imciner2** [comment]
I am a member of the KiCad lead development team, and we are interested in getting this exception into the SPDX list (especially because we will be using SPDX identifiers for our upcoming plugin and content manager, which also will support distributing the EDA libraries), however we were working through a process before submitting this.

We were wanting to get a full legal review of this exception by an LF lawyer (since to our knowledge the exception hasn't had a full review, and we are now associated with the LF community bridge platform so we can request their assistance) before we submitted it to the SPDX process. Can you please hold off of progressing this into the SPDX standard until we have had time to finish our due diligence on the exception?

**Comment by swinslow** [comment]
@imciner2 sure -- I've tagged this as "waiting for steward" so we'll keep it open for now, but won't continue further with evaluating it for the SPDX list at this time. Thanks!

**Comment by seabass-labrax** [comment]
Great news, @imciner2! If we agree to add this (I'll abstain from voting since I submitted this issue), I'd be more than happy to write the XML markup.

**Comment by swinslow** [comment]
Thank you @imciner2 for the confirmation!

Seeing +1's from myself and @silverhook, any others?

**Comment by jlovejoy** [comment]
+1 to add

**Comment by swinslow** [comment]
Discussed on legal team call 2022-02-24, agreed to add.

**Comment by johnmhoran** [comment]
+1

**Comment by seabass-labrax** [comment]
Looks like all the changes needed to include this on the SPDX License List have been merged into this repository, so I'll close this issue now! :smiley:
