### ISSUE TITLE
New license request: Prosperity Public License

### ISSUE THREAD

**Issue by linkous8** [spdx/license-list-XML#1368]
1. License name: Prosperity Public License
2. Short identifier: prosperity-3.0
3. License author or steward: 
  - https://github.com/licensezero/prosperity-public-license
  - https://artlessdevices.com/
  - https://licensezero.com/
4. Comments: Used by Github's Dependabot core
5. Standard License Header:
```
The Prosperity Public License 2.0.0

Contributor: <HOLDER>

Source Code: <URL>

This license lets you use and share this software for free,
with a trial-length time limit on commercial use. Specifically:

If you follow the rules below, you may do everything with this
software that would otherwise infringe either the contributor's
copyright in it, any patent claim the contributor can license
that covers this software as of the contributor's latest
contribution, or both.

1. You must limit use of this software in any manner primarily
   intended for or directed toward commercial advantage or
   private monetary compensation to a trial period of 32
   consecutive calendar days. This limit does not apply to use in
   developing feedback, modifications, or extensions that you
   contribute back to those giving this license.

2. Ensure everyone who gets a copy of this software from you, in
   source code or any other form, gets the text of this license
   and the contributor and source code lines above.

3. Do not make any legal claim against anyone for infringing any
   patent claim they would infringe by using this software alone,
   accusing this software, with or without changes, alone or as
   part of a larger application.

You are excused for unknowingly breaking rule 1 if you stop
doing anything requiring this license within 30 days of
learning you broke the rule.

**This software comes as is, without any warranty at all. As far
as the law allows, the contributor will not be liable for any
damages related to this software or this license, for any kind of
legal claim.**
```
6. URL(s): https://github.com/licensezero/prosperity-public-license
7. OSI Status: Not Submitted
8. Example Projects: https://github.com/dependabot/dependabot-core/blob/main/LICENSE

**Comment by jlovejoy** [comment]
@linkous8 - are you intending to submit 2.0 or 3.0? You have listed 3.0 in the short identifier, but the text of 2.0?

**Comment by Pizza-Ria** [comment]
- Agreed that this does not match the [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md).

**Comment by linkous8** [comment]
Thanks for the triage guys! Will defer to your judgments on this one 🙏

**Comment by 89z** [comment]
> 



> * Agreed that this does not match the [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md).

@Pizza-Ria can you elaborate on this?

**Comment by 89z** [comment]
https://github.com/licensezero/prosperity-public-license/issues/7
