### ISSUE TITLE
Review documentation re: XML formatting

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1369]
@swinslow to review existing docs to see what we've got re: XML formatting for licenses in the list. This is a spinout of the discussion at https://github.com/spdx/license-list-XML/issues/576

**Comment by jlovejoy** [comment]
as part of this, consider list of all xml tags along with better explanation of what they are used for and any tips on using them.

- [ ] The matching guidelines have been updated to reference XML tags where necessary, but consider that along as part of the big picture
- [ ] https://github.com/spdx/license-list-XML/blob/master/schema/ListedLicense.xsd
- [ ] License list FAQs

**Comment by jlovejoy** [comment]
also note: Although the XML schema documents many of the fields, it is currently hard to read and follow. We have some documentation on the [Wiki](https://wiki.spdx.org/view/Legal_Team/Templatizing), it can be a bit hard to find.

Also see  some notes in #890

**Comment by jlovejoy** [comment]
similar/inclusive to #1289 

needs input from @goneall

**Comment by jlovejoy** [comment]
@swinslow - this seems like part of  #1289 which @zvr  are looking at. Consolidate??

**Comment by jlovejoy** [comment]
https://github.com/spdx/license-list-XML/pull/1593 includes another tip that might be good to include
