### ISSUE TITLE
New license request: testnamespace [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by FrankOliver1** [spdx/license-list-XML#1380]
**1.** License Name: testnamespace
**2.** Short identifier: testnamespace
**3.** License Author or steward: Gary O'Neall
**4.** Comments: 
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/135
**7.** URL(s): https://github.com/spdx/license-namespace-test/blob/master/testlicensenamespace.spdx.yaml
**8.** OSI Status: 
**9.** Example Projects:

**Comment by swinslow** [comment]
Marked as "test submittal", closing
