### ISSUE TITLE
New license request: zbl [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by A1996KASH** [spdx/license-list-XML#1383]
**1.** License Name: Zeblok Computational
**2.** Short identifier: zbl
**3.** License Author or steward: 
**4.** Comments: 
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/136
**7.** URL(s): https://github.com/zeblok/computational-frontend-v2
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://app.zbl-aws.zeblok.com/

**Comment by swinslow** [comment]
Hi @A1996KASH, thanks for this submission. A couple of initial questions:

* The URL you provided doesn't work -- I'm getting a 404 error. Perhaps it's a private repo? Do you have a URL to the actual license text?
* It looks like the only example project specified in the submission is for your own project. Do you have examples of other projects where this license is in use?

**Comment by jlovejoy** [comment]
note - the submission form is incomplete, including just "Hello" where the license text is supposed to be.

If we don't get a complete submission in the next week, we will close this
