### ISSUE TITLE
Add Hippocratic-3.0

### ISSUE THREAD

**Issue by Tyler887** [spdx/license-list-XML#1388]
https://tyler887.github.io/choosealicense.com/licenses/hippocratic-3.0

**Comment by jlovejoy** [comment]
@Tyler887 - can you please provide the full information for submitting a new license?  (see https://github.com/spdx/license-list-XML/blob/master/DOCS/request-new-license.md) 
As you've already created a new issue, you can add the info that would have been submitted via this form https://tools.spdx.org/app/submit_new_license/

Thanks!

(Note - Hippocratic-2.1 is already on SPDX License List. Would be helpful to know about uptake and differences for 3.0 version)

**Comment by swinslow** [comment]
full submission added in #1393, will discuss there, thank you @Tyler887!
