### ISSUE TITLE
Decide how to represent MarkDown-formatted licenses

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1395]
A few licenses in recent years have used MarkDown formatting for the "default" license text, for example:

* [BlueOak-1.0.0](https://github.com/spdx/license-list-XML/blob/master/src/BlueOak-1.0.0.xml)
* [CAL-1.0](https://github.com/spdx/license-list-XML/blob/master/src/CAL-1.0.xml)
* Elastic-2.0 (currently in PR at #1394)
* [PolyForm-Noncommercial-1.0.0](https://github.com/spdx/license-list-XML/blob/master/src/PolyForm-Noncommercial-1.0.0.xml)

We haven't had a standard way that we reflect the MarkDown formatting in the license-list-XML templates. See the related discussion at #1394.

In particular a couple of questions come to mind:
* Should section header markup (e.g. `##` in `## Notices`) be labeled as `<list><item><bullet>`, or as `<optional>`, or neither?
* Should the matching guidelines reflect that MarkDown formatting should be ignored? Is that feasible or messy?
* Do we want to include MarkDown in the templates at all, or just use plain text?

**Comment by zvr** [comment]
I believe that all formatting should be stripped and we should use plain text.

We do the same for licenses that are in HTML format, for example. We do not keep `<h1>`, `<h2>`, etc. headers, but translate them all to paragraphs.

If, for example, some project uses a plain-text version of the license (with a line simply containing `Notices`), shouldn't it be considered the same license?

And in the same way that the matching guidelines imply "strip all formatting from text in HTML (or LaTeX or Word) before matching", the same should hold for MarkDown.

**Comment by swinslow** [comment]
I'd tend to agree with @zvr here. There's two caveats why I might not though:

1. If the "canonical" version of a particular license is usually in MarkDown, then is it useful for tools if the MarkDown is expressed in the template? I'd be interested in thoughts from tooling designers -- cc @goneall @pombredanne and I'm sure others may want to way in.

2. Somewhat relatedly, to the extent that we care about having the test text files reflect the "canonical" version of a license text, we _may_ want the test text files to match the license steward's preferred version. For some licenses, this might be MarkDown. If the SPDX tools used for processing the XML templates can match against test text files in MarkDown, then this is fine -- but I'm guessing (without knowing) that this might be a heavy lift to ask of the tooling folks.

**Comment by goneall** [comment]
For the license matching, I'm thinking we should add common markdown characters to the list of text to be ignored in the same we we [ignore code comments](https://spdx.github.io/spdx-spec/v3-draft/license-matching-guidelines-and-templates/#b7-code-comment-indicators).

This would be an update to the license-matching-guidelines.

**Comment by goneall** [comment]
If the markdown characters are in the license matching guidelines, any matching tools could ignore those characters.  Then there would be no need to update the templates.

**Comment by goneall** [comment]
> Somewhat relatedly, to the extent that we care about having the test text files reflect the "canonical" version of a license text, we may want the test text files to match the license steward's preferred version. For some licenses, this might be MarkDown. If the SPDX tools used for processing the XML templates can match against test text files in MarkDown, then this is fine -- but I'm guessing (without knowing) that this might be a heavy lift to ask of the tooling folks.

If we update the SPDX license list generator application to disregard markdown text, it won't be a problem.  However, I agree that it may be problematic for some of the license matchers out there which does a simple compare against the test text file content.  

Another consideration is the test text is also used to copy the license text into source distributions.  In these cases, do we want to include the markdown or do we want to convert to text?

**Comment by pombredanne** [comment]
My 2 cents:
I would make a difference between markups based mostly on using punctuation decorations (md, rst) and markups using alpha tags (HTML).
- the upstream text is best used as is, if this is plain text or punctuation-markup. Otherwise convert to text.
- the matching guidelines should state that any kind of markup should be ignored because they do not matter.
- making the markup optional in the template does not make sense to me. Tools are very good at doing this automatically so templating is not needed.

**Comment by swinslow** [comment]
No further discussion on this recorded during the 3.19 documentation release cycle. Moving to "Later Release".

For reference, here are the topics that it looks like could be addressed if this is to be picked up again in the future:

* Should the matching guidelines [SPDX 2.3 version here](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/) be updated to explicitly state that MarkDown (and/or other common markup formats) should be ignored in license templates?
* Should there be an official policy or practice for whether MarkDown characters are included in license-list-XML templates, where the license steward includes them in the "canonical" version?

**Comment by jlovejoy** [comment]
given this is from 2022, should we close and we can always re-open if we want to revisit?  Just trying to prioritize given all we have going on...

**Comment by swinslow** [comment]
Given that it's been another 9+ months and no further action on this, I'm going to go ahead and close; can re-open if and when it becomes applicable in the future.
