### ISSUE TITLE
Remove SPDX-LL Project

### ISSUE THREAD

**Issue by Tyler887** [spdx/license-list-XML#1400]
The SPDX-LL project is just for no purpose, just something weird, would be replaced with a tracking project.

**Comment by pombredanne** [comment]
@Tyler887 Can you elaborate a little? You want to delete this project? I value your opinion, but why should we do this?

**Comment by Tyler887** [comment]
> @Tyler887 Can you elaborate a little? You want to delete this project? I value your opinion, but why should we do this? 

It's a fake project, used for no purpose. Projects **must have a purpose**. It is usally just the default contents from the "none" template. Therefore, it should be replaced by a tracking project.

**Comment by pombredanne** [comment]
@Tyler887 Are you saying that the SPDX-License List as a whole as no purpose?  I do not understand the point you are making: the purpose is stated as:

https://github.com/spdx/license-list-XML#what
>  The purpose of the SPDX License List is to enable easy and efficient identification of such licenses and exceptions in an SPDX document, in source files or elsewhere. 

What's not clear about it?

And what is what you call a "tracking project"?

**Comment by Tyler887** [comment]
> @Tyler887 Are you saying that the SPDX-License List has a whole as no purpose?  I do not understand the point you are making: the purpose is stated as:
> 
> https://github.com/spdx/license-list-XML#what
> >  The purpose of the SPDX License List is to enable easy and efficient identification of such licenses and exceptions in an SPDX document, in source files or elsewhere. 
> 
> What's not clear about it?
> 
> And what is what you call a "tracking project"?

I do not mean the SPDX license list itself; only the project in that "projects" tab. You may need to delete the project SPDX-LL in the repository (this does not mean the entire License List or this repository).

Also, a tracking project is a project used to track requests, bugs, and more stuff. I am not requesting the SPDX License List to go away or simply just end up "proprietary" - only requesting the fake GitHub Project in the Projects tab of this repository to be removed from the GitHub repository.

**Comment by pombredanne** [comment]
@Tyler887 Thanks for the clarification! It was not obvious at first. I closed the project in https://github.com/spdx/license-list-XML/projects/1 which was effectively empty and useless!
