### ISSUE TITLE
Missing CC0-1.0 copyright header

### ISSUE THREAD

**Issue by Tyler887** [spdx/license-list-XML#1401]
The copyright header from the CCWiki is:

> *<PROGRAM NAME\>* - *<DESCRIPTION\>*
> Written in *\<YEAR\>* by *\<AUTHOR NAME\>* *\<AUTHOR E-MAIL ADDRESS\>*
>
> *[other author/contributor lines as appropriate]*
> To the extent possible under law, the author(s) have dedicated all copyright
> and related and neighboring rights to this software to the public domain worldwide.
> This software is distributed without any warranty.
>
> You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see `<http://creativecommons.org/publicdomain/zero/1.0>`.

**Comment by pombredanne** [comment]
@Tyler887 Thanks... but IMHO the header is not part of the reference license text.

**Comment by Tyler887** [comment]
> @Tyler887 Thanks... but IMHO the header is not part of the reference license text.
Thanks, fixed using markdown code wrap to fully disable markdown and autolinks ;)

**Comment by jlovejoy** [comment]
we took the license text from here - https://creativecommons.org/publicdomain/zero/1.0/legalcode

I'm not sure where you are referring to that has the above text?? @Tyler887

**Comment by mlinksva** [comment]
I suspect (or trying to make sense of) the suggestion is to add a `standardLicenseHeader` element, which can be peer to `text` if the header is not found within `text`, as would be the case for CC0-1.0. I have no opinion on whether this would be valuable to add for CC0-1.0.

**Comment by mlinksva** [comment]
Oh and the text is from https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F

**Comment by jlovejoy** [comment]
Thanks @mlinksva - that makes sense. Generally, we take a strict view for what populates the StandardHeader field, as articulated here: https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md - namely, "Should only include text intended to be put in the header of source files or other files as specified in the license or license appendix when specifically delineated"

We have not, therefore, included suggestions in FAQs or other webpages.

Thus, I think we can close this.

 but curious - @Tyler887 - what did you mean by "fixed using markdown code wrap to fully disable markdown and autolinks" ?
