### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by Tyler887** [spdx/license-list-XML#1403]

**Comment by jlovejoy** [comment]
@goneall @swinslow  @zvr - do any of you know how to go about doing this?

**Comment by goneall** [comment]
Here's documentation on how to rename the branch: https://git-scm.com/book/en/v2/Git-Branching-Branch-Management

It will also require an update to the Github actions.

Also - everyone who has cloned the repo will likely need to change to the new branch, so we'll want to communicate this change to the legal team prior to making the changes.

**Comment by jlovejoy** [comment]
Thanks @goneall - we'll look into it further and make sure people are aware

**Comment by swinslow** [comment]
I'm +1 to making this change.

@goneall, do you foresee any changes needed to the License List Publisher itself, or just the branch name listed in the Github Actions config files ([here](https://github.com/spdx/license-list-XML/blob/4a53770891b29183d8c057ce2c0779a4f976fb65/.github/workflows/deploy.yaml#L4) and [here](https://github.com/spdx/license-list-XML/blob/4a53770891b29183d8c057ce2c0779a4f976fb65/.github/workflows/validate.yaml#L5))? If it's just the latter, I can make those changes once we're ready to proceed.

**Comment by goneall** [comment]
> do you foresee any changes needed to the License List Publisher itself, or just the branch name listed in the Github Actions config files

Just the latter - no changes to the LicenseListPublisher.

Thanks @swinslow !

**Comment by jlovejoy** [comment]
@swinslow @goneall - where are we at for this? should we mark for 3.19?

**Comment by swinslow** [comment]
Yup -- I'm moving it to 3.19. I had meant to do it earlier in the release cycle, so that we'd have time to clean things up if anything unexpected happened with the CI it wouldn't be right before a release. But I didn't manage to do that, sigh. With 3.19 being a docs-focused release, there should be more space for us to address this.
