### ISSUE TITLE
New license request: Baekmuk [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1405]
**1.** License Name: Baekmuk License
**2.** Short identifier: Baekmuk
**3.** License Author or steward: ?
**4.** Comments: This is a font license that is a "good" license for Fedora and appears in a handful of packages in the current Fedora release
**5.** Standard License Header: none
**6.** License Request Url: http://tools.spdx.org/app/license_requests/140
**7.** URL(s): https://fedoraproject.org/wiki/Licensing:Baekmuk?rd=Licensing/Baekmuk
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://sourcegraph.com/search?q=context:global+r:src.fedoraproject.org+file:.*%5C.spec%24+%5ELicense:%5Cs%2B.*baekmuk+TIMEOUT:120s&patternType=regexp

**Comment by swinslow** [comment]
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

No

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

Yes

### If a software license, does it apply to source code and not only to executables?

N/A - not a software license

### Does the license have identifiable and stable text, and is not in the midst of drafting?

Yes, appears to be a historical license

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

Not sure whether there is a "license steward" for this historical license

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

Yes, appears to be sort of a modified version of [HPND](https://spdx.org/licenses/HPND.html) specific to fonts, as a broadly permissive license permitting free use, redistribution and modification.

### 2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one significant project satisfies this*

Yes, appears to be used in fonts redistributed by Fedora as well as embedded in some programs in Fedora

### 3. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

Sort of? The acknowledgement in the last line is specific to the font author, but that line could be templated if it were to be used elsewhere.

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

Yes

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

See above re: license steward

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

+1 to add, as a broadly permissive historical license used in Fedora and likely elsewhere

**Comment by johnmhoran** [comment]
+1 to add

**Comment by swinslow** [comment]
Discussed on 2022-02-24 legal team call, agreed to add.

**Comment by jlovejoy** [comment]
PR #1421
