### ISSUE TITLE
New license request: Bitstream-Vera [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1406]
**1.** License Name: Bitstream Vera Font License
**2.** Short identifier: Bitstream-Vera
**3.** License Author or steward: ?
**4.** Comments: This is a font license (that I totally thought SPDX already had, but apparently not!) that is on the "good" list for Fedora and appears in many packages in the current Fedora release. Given the original URL, it also appears to be associated with Gnome, so I'd presume it appears in other distros as well.
**5.** Standard License Header: none
**6.** License Request Url: http://tools.spdx.org/app/license_requests/141
**7.** URL(s): https://web.archive.org/web/20080207013128/http://www.gnome.org/fonts/, https://docubrain.com/sites/default/files/licenses/bitstream-vera.html
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://sourcegraph.com/search?q=context:global+r:src.fedoraproject.org+file:.*%5C.spec%24+%5ELicense:%5Cs%2B.*bitstream+vera+TIMEOUT:120s&patternType=regexp

**Comment by swinslow** [comment]
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

No

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

Yes, appears to be unique

### If a software license, does it apply to source code and not only to executables?

N/A, not a software license

### Does the license have identifiable and stable text, and is not in the midst of drafting?

Yes, this is a historical license that doesn't appear to be changing.

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

Not sure whether Gnome is the "license steward" here, but this doesn't appear to be subject to change as a historical license.

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

I'd say it is, to the same extent that OFL-1.1 is.

Specifically, both have the requirement that the font may not be sold by itself, but that it may be sold as part of a larger software package (and free redistribution is also permitted). The OFL family of licenses are on the License List, and OFL is considered free by the FSF + is approved by OSI despite this restriction, so I don't see this as a blocker for Bitstream-Vera for SPDX purposes certainly.

### 2. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one significant project satisfies this*

Yes, I believe the Bitstream Vera fonts are widely used, including in Fedora as @jlovejoy noted

### 3. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

Sort of. There are several specific references to Bitstream / Vera and Gnome in the license text, though those could be templated without damaging the general structure of the license.

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

Yes

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

See above re: license steward

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

I'm +1 to add, given its generally being for free redistribution of content and widespread use.

**Comment by seabass-labrax** [comment]
I agree with the points that @swinslow made above, so I'd also be in support of adding this licence. Godot, a popular open source game engine uses this licence for its fonts, for instance.

**Comment by johnmhoran** [comment]
+1 to add

**Comment by swinslow** [comment]
Discussed on 2022-02-24 legal team call, agreed to add.

**Comment by jlovejoy** [comment]
PR #1422
