### ISSUE TITLE
What's the Contract Source source code of Panthera Inu (Thera). Contract Address 0x1b70989329d0d0c92aa24fc830849fea20000bfd

### ISSUE THREAD

**Issue by Panthera-Inu** [spdx/license-list-XML#1409]

**Comment by swinslow** [comment]
Hello, this repo is for the maintenance of the XML files for the licenses on the [SPDX License List](https://spdx.org/licenses).

It looks like this issue is referring to some sort of cryptocurrency, which is off-topic for this repo. So I'm going to close this issue.
