### ISSUE TITLE
Request to make CC-BY-3.0 Notice section optional

### ISSUE THREAD

**Issue by capfei** [spdx/license-list-XML#1413]
I've come across several examples where the license did not include "Creative Commons Notice". The top portion of the license is marked as optional and formatted in the same gray box on the CC license page.
https://creativecommons.org/licenses/by/3.0/legalcode
https://spdx.org/licenses/CC-BY-3.0.html

Examples:

- https://github.com/tok3/py_urban/blob/master/addons/shared_addons/themes/conjuction/license.txt
- https://github.com/Shibly/Symblog/blob/master/vendor/jms/di-extra-bundle/JMS/DiExtraBundle/Resources/doc/LICENSE
- https://github.com/MineDigger/minedigger.github.io/blob/master/LICENSE.txt

**Comment by jlovejoy** [comment]
@capfei - what is the proposed change here? We *should* have that top part marked as optional on all the CC licenses (and it is so on the CC-BY-3.0 example). So, all these examples align - meaning the omission of the text marked as optional in the SPDX data would still constitute a "match" to CC-BY-3.0

Was there another version where it is not marked as optional?

**Comment by capfei** [comment]
@jlovejoy I am referring to the notice at the bottom. The examples provided do not have this:

> Creative Commons Notice
>
> Creative Commons is not a party to this License, and makes no warranty whatsoever in connection with the Work. Creative Commons will not be liable to You or any party on any legal theory for any damages whatsoever, including without limitation any general, special, incidental or consequential damages arising in connection to this license. Notwithstanding the foregoing two (2) sentences, if Creative Commons has expressly identified itself as the Licensor hereunder, it shall have all rights and obligations of Licensor.
>
> Except for the limited purpose of indicating to the public that the Work is licensed under the CCPL, Creative Commons does not authorize the use by either party of the trademark "Creative Commons" or any related trademark or logo of Creative Commons without the prior written consent of Creative Commons. Any permitted use will be in compliance with Creative Commons' then-current trademark usage guidelines, as may be published on its website or otherwise made available upon request from time to time. For the avoidance of doubt, this trademark restriction does not form part of this License.
>
> Creative Commons may be contacted at http://creativecommons.org/.

**Comment by capfei** [comment]
I went ahead and created a PR, in case this gets approved. #1416

**Comment by seabass-labrax** [comment]
I'd be in support of this change :)
