### ISSUE TITLE
Remove optional text from SPDX MIT

### ISSUE THREAD

**Issue by LeoColman** [spdx/license-list-XML#1417]
In the MIT definition from SPDX (https://spdx.org/licenses/MIT.html), which corresponds to [this source file](https://github.com/spdx/license-list-XML/blob/master/src/MIT.xml) contains an optional text:

> (including the next paragraph)

This was discussed originally in #729 and implemented in #730.

I'd like to propose removing this text from the file. 

### Choose-A-License
https://choosealicense.com/licenses/mit/

Choose a license doesn't include this part in the license, even though it includes SPDX as it's source.

This is a bit of a discrepancy that we should fix. Either here or in choose a license.

### OpenSource.org

https://opensource.org/licenses/MIT

OpenSource.org doesn't include the optional text as part of the MIT license. It's listed by SPDX as "other source for this license"

**Comment by jlovejoy** [comment]
The text "including the next paragraph" is considered optional text - meaning the license can be a match (as per SPDX Matching Guidelines) if that text is there or is not. 

To get to this point, someone in the past noted that sometimes this text is included and sometimes it is not. A determination was made by the SPDX Legal team that the inclusion of this text or not does not make for a legally substantive difference and thus we did not need to add a separate license to accommodate this difference.

Preferably the reconciliation would be on the other side, but I'm not sure how that would work.

**Comment by jlovejoy** [comment]
@LeoColman - not sure what more to say here? 

Thinking about it again, I don't think anyone (Choose-a-license, OSI, or SPDX) needs to make any changes. The text has been determined to be optional (by SPDX) - thus if someone uses the license without that text, it is still a match.

I should have put in the link for our Matching Guidelines before, which may help: https://spdx.dev/license-list/matching-guidelines/ (note -these are in the process of being updated)

Thanks!

**Comment by LeoColman** [comment]
Alright!
I'm ok with this result

Thanks @jlovejoy !
