### ISSUE TITLE
APSL-2.0 Field "Standard License Header"

### ISSUE THREAD

**Issue by OliverFendt** [spdx/license-list-XML#1418]
The field "Standard License Header" in the SPDX license list contains the currently the following information:
> There is no standard license header for the license

In my opinion this shall be exchanged with the following information (= Exhibit A): 
> This file contains Original Code and/or Modifications of Original Code as defined in and that are subject to the Apple Public Source License Version 2.0 (the 'License'). You may not use this file except in compliance with the License. Please obtain a copy of the License at http://www.opensource.apple.com/apsl/ and read it before using this file.

> The Original Code and all software distributed under the License are distributed on an 'AS IS' basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, AND APPLE HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT OR NON-INFRINGEMENT. Please see the License for the specific language governing rights and limitations under the License."

The APSL defines the standard license header in section 2.2 b)
> (b) You must duplicate, to the extent it does not already exist, the notice in Exhibit A in each file of the Source Code of all Your Modifications, and cause the modified files to carry prominent notices stating that You changed the files and the date of any change; 

Thus there is a standard header defined for APSL-2.0, which is the above mentioned Exhibit A.

This is similar to MPL-1.1. The APSL-2.0 is a derived work of MPL-1.1 in my opinion.

**Comment by jlovejoy** [comment]
good catch @OliverFendt thanks! 
do you feel comfortable making a PR to update the xml file for this?

**Comment by jlovejoy** [comment]
great, thanks @OliverFendt !
