### ISSUE TITLE
Jam License was approved by OSI

### ISSUE THREAD

**Issue by smaffulli** [spdx/license-list-XML#1428]
the Jam License was approved by the OSI. Here is the link to the board minutes: https://wiki.opensource.org/bin/Main/OSI%20Board%20of%20Directors/Board%20minutes/2021/2021-09-17/
OSI website has been updated.

**Comment by jlovejoy** [comment]
great, thanks @smaffulli !!

**Comment by jlovejoy** [comment]
added PR for this at #1431

**Comment by swinslow** [comment]
Fixed in #1431, thanks all!
