### ISSUE TITLE
What license identifier can be used for LZMA SDK?

### ISSUE THREAD

**Issue by testworksau** [spdx/license-list-XML#1429]
For:
https://www.7-zip.org/sdk.html

I can find an LZMA-Exception identifier, which looks like its purpose is for NSIS rather than the LZMA SDK itself:
https://spdx.org/licenses/LZMA-exception.html

I've taken a look at:
https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files_(DRAFT)

However it is unclear (to me) as to whether we should be creating a new identifier for the LZMA SDK license text, which reads:

```
LICENSE
-------

LZMA SDK is written and placed in the public domain by Igor Pavlov.

Some code in LZMA SDK is based on public domain code from another developers:
  1) PPMd var.H (2001): Dmitry Shkarin
  2) SHA-256: Wei Dai (Crypto++ library)

Anyone is free to copy, modify, publish, use, compile, sell, or distribute the 
original LZMA SDK code, either in source code form or as a compiled binary, for 
any purpose, commercial or non-commercial, and by any means.

LZMA SDK code is compatible with open source licenses, for example, you can 
include it to GNU GPL or GNU LGPL code.
```

**Comment by seabass-labrax** [comment]
Welcome, @testworksau! This certainly looks like a candidate for a new SPDX license identifier. Whilst the statement that the LZMA SDK is placed in the public domain could be seen as sufficient by some, the "anyone is free to copy, modify, publish..." statement seems like a license in its own right.

A potential difficulty would be that there are (at least!) two texts.

The one you included in this issue:

> LZMA SDK is written and placed in the public domain by Igor Pavlov.
> 
> Some code in LZMA SDK is based on public domain code from another developers:
>   1) PPMd var.H (2001): Dmitry Shkarin
>   2) SHA-256: Wei Dai (Crypto++ library)
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or distribute the 
> original LZMA SDK code, either in source code form or as a compiled binary, for 
> any purpose, commercial or non-commercial, and by any means.
> 
> LZMA SDK code is compatible with open source licenses, for example, you can 
> include it to GNU GPL or GNU LGPL code.

...and the shorter one on <https://www.7-zip.org/sdk.html>:

> **LZMA SDK** is placed in the **public domain.**
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or distribute the original LZMA SDK code, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

Debian has yet another statement, but I'm not sure where they got theirs from!

> LZMA SDK is Copyright (C) 1999-2011 Igor Pavlov.
> 
> LZMA SDK is placed in the public domain.


In any case, while we discuss whether this should be included in the SPDX License List, you can create a custom license identifier according to [Clause 10 of the SPDX specification, version 2.2.1](https://spdx.github.io/spdx-spec/other-licensing-information-detected/). :smiley:

Hope this helps; please let me know if you have any more information! We have our next SPDX Legal Team meeting (it's open, please feel free join) in just over a week (on the 23rd of March), so it will probably be discussed then.

**Comment by testworksau** [comment]
Many thanks for the detailed feedback @seabass-labrax 

I've raised a PR - hopefully the notes within capture what I've found out through my journey of trying to unpack the various derivatives of the license that apply to the different SDK versions.

**Comment by swinslow** [comment]
Hi @testworksau, thanks for submitting this and @seabass-labrax thanks for the detailed response!

Interestingly, the main substantive bit of this ("Anyone is free to copy...") appears to be identical to the second paragraph of [Unlicense](https://spdx.org/licenses/Unlicense.html), which is also a "says it's public domain but then uses license-y language" license -- other than saying "the 
original LZMA SDK code" instead of "this software".

But the first sentence re: public domain differs from Unlicense, and the third and fourth paragraphs of Unlicense are absent altogether. So it wouldn't be a match to that ID in any case. I also agree that the LZMA-exception looks like it's inapplicable here.

I'll aim do a more formal writeup of the inclusion principles analysis, but I'm leaning towards likely being in favor of adding this one. If the legal team community agrees to add it, then we can focus in on which version(s) specifically to add.  :)  If possible I'd lean towards just one identifier, with the following primary text and with optional / replaceable text matching fields to handle any differences in the versions:

> LZMA SDK is placed in the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or distribute the original LZMA SDK code, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

**Comment by testworksau** [comment]
Thanks @swinslow 

> If possible I'd lean towards just one identifier, with the following primary text and with optional / replaceable text matching fields to handle any differences in the versions:

That may be challenging in that versions of the SDK up to 4.57 will not match on any of the primary text, and the second paragraph is only available since 9.22 (or is that the optional part you are referring to?)

Sorry for the questions, I'm quite new to this repo - maybe adding suggested changes in the PR is the most efficient way to close this out if / when agreement is reached.

**Comment by swinslow** [comment]
Thanks @testworksau! Sounds good and no worries, I'll take a closer look at it and will see what's doable (assuming it gets the +1 from the community to add). Thanks for sending the PR, and we'll see if it works as-is or if some bits should be tweaked.

**Comment by swinslow** [comment]
Discussed on 2022-04-14 legal team call, general agreement with adding license(s) with this substance, but questions about which text is the appropriate one to add (or if multiple should be added). @seabass-labrax can you drop the link here to the project, and I can reach out to them to ask their views on which one to add?

**Comment by jlovejoy** [comment]
having a look at the #1430  - the variant that give a choice of licenses should probably not be added, as those choices are mostly accommodated in SPDX and it would be a license expression, using OR operator.
But it also looks like there may be a couple exceptions in there too. So we might want to look at that separately? (sorry if this was discussed on call...)

**Comment by jlovejoy** [comment]
noting that ok to add, but more work to be done on what to add, templating, etc. 
also question as to exceptions (see PR #1430 )

@swinslow was going to maybe try to reach out to author?
