### ISSUE TITLE
New license request: "GStreamer proprietary plugins" exception

### ISSUE THREAD

**Issue by hadess** [spdx/license-list-XML#1442]
A bit of background. GNOME Videos (né "totem") is a video player for the GNOME desktop environment licensed under the GPL v2+. It uses GStreamer (LGPLv2.1+) for video playback. As was, and still is, the case, a number of video codecs are patent encumbered and can't be shipped easily in some places.

That's the reason why there are proprietary video decoding plugins available from various vendors, and which totem would like to use without causing problems by recombining, or shipping together, a GPL totem with non-free GStreamer plugins.

In 2005, we added this note to the COPYING file in totem:
```
The Totem project hereby grant permission for non-gpl compatible GStreamer
plugins to be used and distributed together with GStreamer and Totem. This
permission are above and beyond the permissions granted by the GPL license
Totem is covered by.
```

This better version was added to the Rhythmbox music player in 2008 and is a bit clearer:
```
The Rhythmbox authors hereby grant permission for non-GPL compatible
GStreamer plugins to be used and distributed together with GStreamer and 
Rhythmbox. This permission is above and beyond the permissions granted by
the GPL license by which Rhythmbox is covered. If you modify this code, you may 
extend this exception to your version of the code, but you are not obligated 
to do so. If you do not wish to do so, delete this exception statement from 
your version.
```

This exception is also used by GNOME Music, and mentioned in GStreamer's licensing documentation:
https://gstreamer.freedesktop.org/documentation/frequently-asked-questions/licensing.html?gi-language=c#licensing-of-applications-using-gstreamer

**Comment by seabass-labrax** [comment]
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

No; I see no evidence that the OSI has approved this exception.

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

Yes, it is not already on the SPDX License List.

### If a software license, does it apply to source code and not only to executables?

Yes.

### Does the license have identifiable and stable text, and is not in the midst of drafting?

The submitter expressed two distinct exceptions, but both seem to be stable.

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

I think we'll ask @hadess to answer this one :smiley:

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

Yes; it is an exception to the GPL and does not restrict use in any way.

### 2. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

No, but the language appears to be easily 'templatable'.

### 3. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this*

Yes, GNOME Videos and Rhythmbox are often pre-installed on major open source desktop distributions, such as Fedora Workstation.

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

Yes.

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

Yes, it seems! :grinning:

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

I am in favour of including this exception in the SPDX License List. It satisfies the license inclusion principles, apart from some technical details which can be resolved with templating and/or upstream coordination.

**Comment by seabass-labrax** [comment]
@hadess, welcome to SPDX! Thank you for making this request; I've left some comments above about the exception's suitability, following our [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). We have our fortnightly SPDX Legal Team meeting next Thursday, which is when we'll probably make a final decision; you're welcome to join if you would like!

**Comment by hadess** [comment]
Thanks very much for the quick review!

Before setting the license in stone (at least this version), I might want to take some time to reach out to the other users of the exception so we can agree on using the better reworded version from Rhythmbox for all the uses. Would it be helpful for the exception to be made more generic (eg. not including the project name but "this project") before voting on the inclusion?

I'm not going to be available Thursday next week, but I could definitely join on the 28th, and I would be very interested in doing so, if that's feasible on your side. What do you reckon?

**Comment by swinslow** [comment]
Thank you @hadess and thanks @seabass-labrax for the quick analysis!

@hadess yes, if totem is likely to switch to a version that the other projects are also using, that might be helpful to do first. Although the prior distributions of course will have used the prior version of the exception, if you're moving forward with the new one then we'd probably lean towards using that. In particular if it aligns with what the other projects are using, since that contributes to the "substantial use" factor that @seabass-labrax analyzed above.

As far as "templating" goes, we sometimes incorporate markup to reflect "replaceable" text such as project names into the license text XML files if and when they are accepted. So it's up to you and your community whether you use a "this project" generic formulation for the license text, or whether you stick with referencing Totem. 

Personally I tend to prefer the "generic"-style license texts whenever possible, simply because that means less customization and therefore less hassle for everyone when detecting / analyzing and complying with the license. But again, up to you and your community  :)

**Comment by jlovejoy** [comment]
thanks all - I'm marking this for the next release, but if there are subsequent changes, we may need to push it out

**Comment by Pizza-Ria** [comment]
+1 to add.

**Comment by swinslow** [comment]
Discussed on legal team call 2022-04-14, agreed to add each of these, with templating out the Rhythmbox name.

**Comment by hadess** [comment]
> I'm available this Wednesday if my presence is needed to discuss the changes I proposed above.

The meetings are Thursdays, and I've added tomorrow's to my calendar. See you then!

**Comment by seabass-labrax** [comment]
@hadess, great to hear that! :grinning:

As for this text:

> This project hereby grants permission for non-GPL compatible GStreamer plugins
> to be used and distributed together with GStreamer and this project. This
> permission is above and beyond the permissions granted by the GPL license
> by which this project is covered. If you modify this code, you may extend this
> exception to your version of the code, but you are not obligated to do so. 
> If you do not wish to do so, delete this exception statement from your version.

That's great! It would reduce the likelihood of new variants being accidentally created if other projects started using this exception, which is a good thing for software composition analysis! It would probably be wise to add templating in the SPDX License List anyway though, as then the entry would match older versions of the exception, for instance copies of GNOME Videos in more stable distributions. If someone was to copy the plain text from SPDX though (which for instance the [REUSE](https://reuse.software) tool does) they would get the new, generic version.

Does that sound good for you too? If so, I think we can get this in for the next SPDX License List release :)

**Comment by hadess** [comment]
> That's great! It would reduce the likelihood of new variants being accidentally created if other projects started using this exception, which is a good thing for software composition analysis! It would probably be wise to add templating in the SPDX License List anyway though, as then the entry would match older versions of the exception, for instance copies of GNOME Videos in more stable distributions. If someone was to copy the plain text from SPDX though (which for instance the [REUSE](https://reuse.software) tool does) they would get the new, generic version.
> 
> Does that sound good for you too? If so, I think we can get this in for the next SPDX License List release :)

That works for me. What would the next steps be, anything I can help with?

> Hmm, looks like my GNOME GitLab account has been deactivated for some reason (probably for lack of activity xD), so you'll just have to imagine my +1 on your merge request there! :)

Thanks. Let me know if you want me to find out what happened with your account, I can check that with our sysadmins.

**Comment by hadess** [comment]
References for other users of this exception:
- https://gitlab.gnome.org/GNOME/rhythmbox/-/issues/1965
- https://gitlab.gnome.org/GNOME/gnome-music/-/issues/520

**Comment by hadess** [comment]
And GStreamer documentation reference:
https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/1163

**Comment by pombredanne** [comment]
Is this exception unique and specific to GStreamer?
And is the text stable and settled or still evolving?

**Comment by pombredanne** [comment]
@seabass-labrax then this is still an evolving concern?

**Comment by jlovejoy** [comment]
Just looking over the PR for this and wanted to clarify one thing:
- the difference in terms a name (Rhythmbox) v. a generic reference (this project) does not make a need for a different exception entry as this difference is not legally substantive. In which case, we would use the "replaceable" markup to show that whether these is a specific name or generic reference, it is still a match for the license.
- but I see a substantive difference in the presense of this sentensce "If you modify this code, you may extend this
exception to your version of the code, but you are not obligated to do so. 
If you do not wish to do so, delete this exception statement from your version." which does not seem to appear on the "old" version. 

Is that right?  I'm not clear if this was what was discussed or not in terms of the decision to add two exceptions.

**Comment by hadess** [comment]
> * the difference in terms a name (Rhythmbox) v. a generic reference (this project) does not make a need for a different exception entry as this difference is not legally substantive. In which case, we would use the "replaceable" markup to show that whether these is a specific name or generic reference, it is still a match for the license.

I don't see any `replaceable` markup (I grepped for "replaceable" in the sources, and that code isn't used anywhere). I used:
```
<alt match=".+" name="project">This project</alt>
```
for the replaceable sections, which is what other licenses with replaceable parts seemed to do. If that doesn't match what you expect, can you please point me to a license definition that uses that "replaceable" markup?

> * but I see a substantive difference in the presense of this sentensce "If you modify this code, you may extend this
>   exception to your version of the code, but you are not obligated to do so.
>   If you do not wish to do so, delete this exception statement from your version." which does not seem to appear on the "old" version.

This is a clarification of `This permission are above and beyond the permissions granted by the GPL license Totem is covered by.` which makes the source code in those projects compatible with other GPLv2+ projects without the exception.

**Comment by jlovejoy** [comment]
now having re-read comments here and in the PR: It looks like the decision on 4/14 legal call was to "add each of these"  - which I assumed to mean the two variants (2005 and 2008) as included in @hadess 's first comment here.

It also seems that templatizing the name in both variants - such that whether it says Totem / this project / Rhythmbox - it will still be a match (as per guideline 2.1.3 https://spdx.dev/license-list/matching-guidelines/ ) was also decided upon.

What seems to be missing, is a discussion or decision on the short identifiers for each, which is key since we endeavor to never change these. The PR has "GPL-GStreamer-exception" and "GPL-GStreamer-exception-old" - which is a bit different than what we usually do for multiple versions, which is to use a version number or a year/date. I also thought we were trying to avoid having "GPL" or other license names in the id for the exception?

I'm sorry I missed this - not sure if this was discussed or not previously? (@swinslow @seabass-labrax - thoughts?)
but I should have caught and raised this on the last call in any case.

I'd think that for short ids, it'd be more appropriate to use:
GStreamer-exception-2005
GStreamer-exception-2008

(in the unlikely event it is changed in the future, by having the year, there is still a way to differentiate future versions as well)

**Comment by hadess** [comment]
> now having re-read comments here and in the PR: It looks like the decision on 4/14 legal call was to "add each of these" - which I assumed to mean the two variants (2005 and 2008) as included in @hadess 's first comment here.

That's what I understood as well, the 2005 variant being used for "historical purposes".

> It also seems that templatizing the name in both variants - such that whether it says Totem / this project / Rhythmbox - it will still be a match (as per guideline 2.1.3 https://spdx.dev/license-list/matching-guidelines/ ) was also decided upon.

Is there a way to test this? I wanted to avoid the original 2005 version from being "templatized" so it didn't get reused, but I can do that if it's needed.

> What seems to be missing, is a discussion or decision on the short identifiers for each, which is key since we endeavor to never change these. The PR has "GPL-GStreamer-exception" and "GPL-GStreamer-exception-old" - which is a bit different than what we usually do for multiple versions, which is to use a version number or a year/date.

Done.

> I also thought we were trying to avoid having "GPL" or other license names in the id for the exception?
>
> I'm sorry I missed this - not sure if this was discussed or not previously? (@swinslow @seabass-labrax - thoughts?) but I should have caught and raised this on the last call in any case.

I don't think we did, or it wasn't clear to me. In any case, it usually bears repeating during PR reviews because it's easy to iterate and the tools are there to keep track of the changes that are necessary and those already made.

> I'd think that for short ids, it'd be more appropriate to use: GStreamer-exception-2005 GStreamer-exception-2008

Done.

**Comment by jlovejoy** [comment]
@swinslow - can you give this thread  (and PR) a sanity check so there is another set of eyes?
I think we've resolved everything and the PR is ready to merge, but to be complete.

@hadess - once the PR is merged, I think it's fine to start using the ids even though this won't appear/be official on the SPDX License List until the next release
