### ISSUE TITLE
New license request: OGL-1.0a [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by anthonyronda** [spdx/license-list-XML#1443]
**1.** License Name: Open Game License 1.0a
**2.** Short identifier: OGL-1.0a
**3.** License Author or steward: Wizards of the Coast LLC, a subsidiary of Hasbro, Inc.
**4.** Comments: I have not confirmed whether the legal team of Wizards of the Coast LLC objects
to inclusion of the OGL in the SPDX license list. I plan to send them a link to
this page and keep you updated.

OGL has been suggested for submission before. See
https://lists.spdx.org/g/Spdx-legal/topic/22080633#1339. At that time, it was
not considered for inclusion due to a determination that it does not match the
Open Source Definition. I do not disagree with that assessment.

The OGL license text SHOULD include two statements at the beginning not included
in the text I submitted: one that describes Product Identity in the content
package, and one that describes Open Game Content in the content package. It is
largely considered that if these statements are not included, all content is
Open Game Content.

The OGL license text MUST include the titles of all Open Game Content used in
the content package under Section 15 COPYRIGHT NOTICE, along with their
publication years and authors/copyright owners.

I submit this license because my community and I have seen prolific creation and
use of new open source and closed source software packages that contain
OGL-licensed content, but often with haphazard, mixed use of SPDX IDs and readme
notices, or non-compliant (infringing) use of otherwise Open Game Content.
Ecosystems of cross-compatible OGL software packages are here, many of which are
monetized by companies and hobbyists alike, without tools to protect our
community from potential risks of infringing use of Open Game Content.

A new wave of software developers are beginning to dive into Open Game Content,
making it available for use in digital game platforms. Project URL 1 actually
leads to an Awesome List of a few notable software projects making use of OGL,
which I'll be updating throughout the week.

Project URL 2, PCGen, has been an active project for two decades, and in their
thorough compliance checking, their maintainers opt to include a different copy
of the OGL in each of its content directories. SBOM tools such as the REUSE
Software spec could greatly simplify the upkeep of such an archive. See OGL.txt
file in project URL 3, pf1e-content, for an example a single long compliant
text. This is one example where a custom compliance tool could help us identify
which lines of the COPYRIGHT NOTICE correspond to which content files.

Link 4 is one of several long-runnning websites (called "SRD websites/wikis")
that display OGL licensed text similar to wikis that display CC BY-SA content.
It is compliant with the license terms through linking a license page (in the
footer).

Use in the print publishing and PDF publishing world is widespread. Link 5 is a
game store with the OGL product filter applied, displaying 5771 OGL products.
These products typically display the license text in the first few or last few
pages of a PDF or printed book. This store recently announced a partnership with
a platform that has an ecosystem of open source and OGL content packages.

Members of our community have built tools for new developers to make compliance
easier and less confusing, including URL 6, Foundry Factory.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/144
**7.** URL(s): https://opengamelicense.org, https://web.archive.org/web/20070509222709/http://www.opengamingfoundation.org/ogl.html, https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/opengamelicense/awesome-ogl, https://github.com/PCGen/pcgen/tree/master/data, https://github.com/baileymh/pf1e-content/, https://www.d20srd.org/index.htm, https://www.drivethrurpg.com/browse.php?filters=45322_0_0_0_0, https://github.com/ghost-fvtt/foundry-factory

**Comment by anthonyronda** [comment]
A lawyer from Wizards of the Coast contacted me, 

> Hi Anthony,

> Thanks for your note. We have not had an opportunity to review and therefore decline to be included at this time. In the event that changes, we will contact SPDX directly per below. 

I'm happy to finally have received a response from them, and will rescind consideration at this time. Here's hoping for the future.

**Comment by seabass-labrax** [comment]
Keep up the good work, Anthony! Hopefully the situation can be made better in time, and it's always good to have the license steward involved.

**Comment by seabass-labrax** [comment]
Keep up the good work, Anthony! Hopefully the situation can be made better in time, and it's always good to have the license steward involved.

**Comment by anthonyronda** [comment]
Hello all!

Wizards of the Coast LLC is introducing an update to OGL 1.0a, titled OGL 1.1. I felt that this renewed interest in the OGL, after 22 years of uninterrupted use, meant that it was the right time to request their review of the SPDX license list and make an informed decision on OGL 1.0a's inclusion.

I understand that this is unusual, but the need for compliance tools feels urgent because OGL 1.1 is said to specifically bar software from reuse. My community would like to leverage existing license scanning and SBOM tools to prevent confusion/disruption of business. I've notified a contact person at Wizards of the Coast of the situation.

I've reopened this ticket for review, but if you'd prefer if I open a new ticket let me know.

**Comment by jlovejoy** [comment]
oh dear, I don't think we noticed this got re-opened! sorry @anthonyronda!

so, this is for GOL 1.0a, as in the license you originally requested, is that correct?
If so, then we can use this issue, if it is for a different license text, then a new issue would be warranted

**Comment by jlovejoy** [comment]
@anthonyronda - I just re-read this issue and realized that I think your last comment is indicating that you want to submit OGL-1.1 which is an updated version from the original submission of OGL-1.0a ??

If that is correct, could you submit a new issue (preferably via the online tool... :) for OGL-1.1 ?

**Comment by anthonyronda** [comment]
@jlovejoy This was not why the 1.0a application was re-opened, but it's moot now. Version 1.1 was not published as planned, and version 1.0a was not "deauthorized" as threatened. Seeing as we're in July and the OGL status quo has remained, I see no need to press for inclusion of OGL-1.0a at this time.
