### ISSUE TITLE
documentation: short identifier field - add bullet about "exception"

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1451]
discussed on legal call 4/28 - @karsten-klein asked about short ids for exceptions. We looked at descriptions of short names at https://github.com/spdx/license-list-XML/blob/master/DOCS/license-fields.md and it doesn't mention this.

We should probably add a bullet saying that in most cases, the exception id should include the word "exception" since that is how we've been operating.

Any other suggestions for updates??

**Comment by karsten-klein** [comment]
Exceptions have various aspects that the short id may anticipate (or not):
* The license the exception applies to (in particular if explicitly mentioned in the exception tests)
* The license version the exception applies to
* Variants of the exception (in particular if the variant is used in specific contexts)
* The version of the exception (as it may be versioned independently from the license)
* The kind of exception (linking exception, classpath exception, build-time exception, compiler exception, ...)

One should consider that exceptions may be combined in reality with different license version and therefore may show inconsistent versions:
GPL-3.0-only WITH Autoconf-exception-2.0
I would therefore not encourage to include the license version if not explicitly mentioned in the license text.

Please also consider adding conventions (or enforce the existing conventions) of the exception full names. There are variants of case and version handling on the current list.

**Comment by jlovejoy** [comment]
addressed (as applicable) in #1573 
some other ideas above from @karsten-klein  I think are beyond scope of the license-field documentation
