### ISSUE TITLE
New license request: OTP-SESY [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by bsrCh3rif07** [spdx/license-list-XML#1512]
**1.** License Name: Open Testing Project SESY License
**2.** Short identifier: OTP-SESY
**3.** License Author or steward: Team no names
**4.** Comments: This license To use this license, developers need to copy the text as provided and include in source files as applicable. If using any other licensed software in the project, retain the original license information at the top of the file, while keeping the copyright statements (if unchanged).
**5.** Standard License Header: The following text is the property of Wizards of the Coast, Inc. and is Copyright 2022 Wizards of the Coast, Inc (“Wizards”). All Rights Reserved.
**6.** License Request Url: http://tools.spdx.org/app/license_requests/147
**7.** URL(s): https://docs.google.com/document/d/1UYUp0rIuMhDnOpzSjgVeSNFerzQ9mVZxOxwzdvq8PU0/edit?usp=sharing
**8.** OSI Status: Pending
**9.** Example Projects: https://github.com/bsrCh3rif07/Flappy-RX/tree/master

**Comment by jlovejoy** [comment]
Hi @bsrCh3rif07 - a couple follow-up questions:
- you say it's "pending" for OSI Status. I would assume that means it has been submitted to OSI? If so, where in the OSI process are you?
- Can you also provide some input as to how you think this license fits the SPDX License Inclusion principles https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md 

thanks

**Comment by bsrCh3rif07** [comment]
Hi @jlovejoy - my answers :
- Yes ofc, i forget to add the OSI process.
- This was with my group a project of study, we was testing and apply some steps for security of supplychain in kubernetes.
Thanks.

**Comment by swinslow** [comment]
Having taken a closer look at this, the license text is identical to the [Wizards of the Coast Open Gaming License](https://web.archive.org/web/20070509222709/http://www.opengamingfoundation.org/ogl.html), with "Open Game License" replaced with "Open Testing Project SESY Content".

The Wizards of the Coast license was submitted for consideration as OGL-1.0a earlier this year (#1443), and withdrawn for the time being at WoC's request.

Given that, I think this should be closed and not added.

**Comment by jlovejoy** [comment]
agreed @swinslow - thanks for looking that up, I knew this seemed familiar.

I think we can close this issue then.
