### ISSUE TITLE
New license request: Minpack [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1522]
**1.** License Name: Minpack License
**2.** Short identifier: Minpack
**3.** License Author or steward: ?
**4.** Comments: This has already been approved for use in Fedora, the guidelines for which are, in a sense, stricter than SPDX License Inclusion Guidelines.

The project noted as being used in, is also included in Fedora.

I'm assuming it was not submitted to OSI, but don't really know.
**5.** Standard License Header: None
**6.** License Request Url: http://tools.spdx.org/app/license_requests/148
**7.** URL(s): http://www.netlib.org/minpack/disclaimer, https://gitlab.com/libeigen/eigen/-/blob/master/COPYING.MINPACK
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://gitlab.com/libeigen/eigen

**Comment by jlovejoy** [comment]
other links:
- https://sourcegraph.com/src.fedoraproject.org/rpms/eigen3/-/blob/eigen3.spec
- http://eigen.tuxfamily.org/index.php?title=Main_Page

**Comment by swinslow** [comment]
I don't have time for a full write-up at the moment, but +1 from me to add. This one seems annoyingly not quite the same as Apache-1.1 and a bunch of the other BSD-style licenses, but a quick poke isn't finding any variants of those currently on the license list with the specific sections 4 and 5 as this one. Seems clearly equivalent to those with just their own special disclaimer and limitation of liability language here (as one does, apparently...).

**Comment by jlovejoy** [comment]
@swinslow - I know, annoyingly similar but not enough!

@pombredanne - I'd be curious to know if you have any data on this license and where else it might be used!

**Comment by DennisClark** [comment]
It's used in http://ftp.debian.org/debian/pool/main/c/cminpack/cminpack_1.3.4.orig.tar.gz

**Comment by pombredanne** [comment]
@jlovejoy 

>  I'd be curious to know if you have any data on this license and where else it might be used!

[`minpack`](https://scancode-licensedb.aboutcode.org/minpack.html) was added to SanCode by @DennisClark before it was called even ScanCode ;) ... but there is not much I could dig from its history beside that.  This is not super frequent:  we've see it pop up in actual codebases we audit either as-is or in libeigen/eige or Apache Commons Math that vendor some of it.
https://github.com/apache/commons-math/blob/294589d7b478fe388b9a1c2e28aa37c02cb6fe18/commons-math-core/LICENCE#L239

**Comment by seabass-labrax** [comment]
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

No; it appears as though the license has never been submitted to the OSI for consideration.

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

Yes, it is unique and not already in the SPDX License List.

### If a software license, does it apply to source code and not only to executables?

Yes, it can apply to both source and binary distribution.

### Does the license have identifiable and stable text, and is not in the midst of drafting?

Yes, it appears to be historical and stable; I can find only one variant. This starts with:

> Minpack Copyright Notice (1999) University of Chicago.  All rights reserved

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

Unknown.

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

Yes, it has been considered to fulfil both the Debian Free Software Guidelines and the Fedora licensing policy by those respective organisations.

### 2. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

Yes. However, there are disclaimer and attribution notices specific to copyright holders; these may need to be marked as replaceable text.

### 3. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this*

Yes, it applies to the widely-used mathematical library Eigen, which is included in all major free software distributions.

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

Yes.

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

No, there isn't any evidence that the license steward is aware of the submission. 

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

I would strongly be favour of this license's inclusion in the SPDX License List, given its wide use and categorisation as a permissive, historical free/open source software license.

**Comment by jlovejoy** [comment]
Thanks @pombredanne @DennisClark and @seabass-labrax  for the additional help here!

So, looks like we have two votes to add it (from @swinslow and @seabass-labrax ) and I don't think my vote "counts" as I am the submitter - so can we get a third from someone else?

**Comment by DennisClark** [comment]
I vote to add the license to the SPDX LIcense LIst !

**Comment by swinslow** [comment]
Thanks @seabass-labrax for doing the work on the writeup, great comments and I agree with all of the above!

**Comment by FLJFA** [comment]
+1 to add

**Comment by jlovejoy** [comment]
files prepared with #1526
