### ISSUE TITLE
New license request: CC-BY-3.0-IGO

### ISSUE THREAD

**Issue by alanorth** [spdx/license-list-XML#1525]
*Note: I tried to submit this twice on the web submission tool, but I got an HTTP 500 error after the warning modal asked me to inspect differences.*

- **Full name**: Creative Commons Attribution 3.0 IGO
- **Short identifier**: CC-BY-3.0-IGO
- **Other web pages for license/exception**: https://creativecommons.org/licenses/by/3.0/igo/legalcode
- **Notes**: There are currently two other CC 3.0 IGO licenses in SPDX and we have [new academic publications coming out in 2022](https://link.springer.com/chapter/10.1007/978-981-16-9893-4_10) that are using this one.
- **OSI Approved**:
- **FSF Free/Libre**:
- **Text**:

<details><summary>Click to show</summary>
THE WORK (AS DEFINED BELOW) IS PROVIDED UNDER THE TERMS OF THIS CREATIVE
COMMONS PUBLIC LICENSE (“LICENSE”). THE LICENSOR (DEFINED BELOW) HOLDS COPYRIGHT
AND OTHER RIGHTS IN THE WORK. ANY USE OF THE WORK OTHER THAN AS AUTHORIZED
UNDER THIS LICENSE IS PROHIBITED.
BY EXERCISING ANY RIGHTS TO THE WORK PROVIDED HERE, YOU ACCEPT AND AGREE TO BE
BOUND BY THE TERMS OF THIS LICENSE. THE LICENSOR GRANTS YOU THE RIGHTS
CONTAINED HERE IN CONSIDERATION FOR YOUR ACCEPTANCE AND AGREEMENT TO THE
TERMS OF THE LICENSE.
1. Definitions
a. “IGO” means, solely and exclusively for purposes of this License, an organization established by a
treaty or other instrument governed by international law and possessing its own international legal
personality. Other organizations established to carry out activities across national borders and that
accordingly enjoy immunity from legal process are also IGOs for the sole and exclusive purposes
of this License. IGOs may include as members, in addition to states, other entities.
b. "Work" means the literary and/or artistic work eligible for copyright protection, whatever may be
the mode or form of its expression including digital form, and offered under the terms of this
License. It is understood that a database, which by reason of the selection and arrangement of its
contents constitutes an intellectual creation, is considered a Work.
c. "Licensor" means the individual, individuals, entity or entities that offer(s) the Work under the
terms of this License and may be, but is not necessarily, an IGO.
d. "You" means an individual or entity exercising rights under this License.
e. "Reproduce" means to make a copy of the Work in any manner or form, and by any means.
f. "Distribute" means the activity of making publicly available the Work or Adaptation (or copies of
the Work or Adaptation), as applicable, by sale, rental, public lending or any other known form of
transfer of ownership or possession of the Work or copy of the Work.
g. "Publicly Perform" means to perform public recitations of the Work and to communicate to the
public those public recitations, by any means or process, including by wire or wireless means or
public digital performances; to make available to the public Works in such a way that members of
the public may access these Works from a place and at a place individually chosen by them; to
perform the Work to the public by any means or process and the communication to the public of
the performances of the Work, including by public digital performance; to broadcast and
rebroadcast the Work by any means including signs, sounds or images.
h. "Adaptation" means a work derived from or based upon the Work, or upon the Work and other
pre-existing works. Adaptations may include works such as translations, derivative works, or any
alterations and arrangements of any kind involving the Work. For purposes of this License, wherethe Work is a musical work, performance, or phonogram, the synchronization of the Work in timed-
relation with a moving image is an Adaptation. For the avoidance of doubt, including the Work in a
Collection is not an Adaptation.
i. "Collection" means a collection of literary or artistic works or other works or subject matter other
than works listed in Section 1(b) which by reason of the selection and arrangement of their
contents, constitute intellectual creations, in which the Work is included in its entirety in unmodified
form along with one or more other contributions, each constituting separate and independent works
in themselves, which together are assembled into a collective whole. For the avoidance of doubt, a
Collection will not be considered as an Adaptation.
2. Scope of this License. Nothing in this License is intended to reduce, limit, or restrict any uses free
from copyright protection.
3. License Grant. Subject to the terms and conditions of this License, the Licensor hereby grants You a
worldwide, royalty-free, non-exclusive license to exercise the rights in the Work as follows:
a. to Reproduce, Distribute and Publicly Perform the Work, to incorporate the Work into one or more
Collections, and to Reproduce, Distribute and Publicly Perform the Work as incorporated in the
Collections; and,
b. to create, Reproduce, Distribute and Publicly Perform Adaptations, provided that You clearly label,
demarcate or otherwise identify that changes were made to the original Work.
c. For the avoidance of doubt:
i. Non-waivable Compulsory License Schemes. In those jurisdictions in which the right to
collect royalties through any statutory or compulsory licensing scheme cannot be waived,
the Licensor reserves the exclusive right to collect such royalties for any exercise by You of
the rights granted under this License;
ii. Waivable Compulsory License Schemes. In those jurisdictions in which the right to collect
royalties through any statutory or compulsory licensing scheme can be waived, the Licensor
waives the exclusive right to collect such royalties for any exercise by You of the rights
granted under this License; and,
iii. Voluntary License Schemes. To the extent possible, the Licensor waives the right to
collect royalties from You for the exercise of the Licensed Rights, whether directly or through
a collecting society under any voluntary licensing scheme.
This License lasts for the duration of the term of the copyright in the Work licensed by the Licensor. The
above rights may be exercised in all media and formats whether now known or hereafter devised. The
above rights include the right to make such modifications as are technically necessary to exercise the
rights in other media and formats. All rights not expressly granted by the Licensor are hereby reserved.
4. Restrictions. The license granted in Section 3 above is expressly made subject to and limited by the
following restrictions:
a. You may Distribute or Publicly Perform the Work only under the terms of this License. You must
include a copy of, or the Uniform Resource Identifier (URI) for, this License with every copy of the
Work You Distribute or Publicly Perform. You may not offer or impose any terms on the Work that
restrict the terms of this License or the ability of the recipient of the Work to exercise the rights
granted to that recipient under the terms of the License. You may not sublicense the Work (see
section 8(a)). You must keep intact all notices that refer to this License and to the disclaimer of
warranties with every copy of the Work You Distribute or Publicly Perform. When You Distribute or
Publicly Perform the Work, You may not impose any effective technological measures on the Work
that restrict the ability of a recipient of the Work from You to exercise the rights granted to that
recipient under the terms of the License. This Section 4(a) applies to the Work as incorporated in a
Collection, but this does not require the Collection apart from the Work itself to be made subject to
the terms of this License. If You create a Collection, upon notice from a Licensor You must, to the
extent practicable, remove from the Collection any credit (inclusive of any logo, trademark, official
mark or official emblem) as required by Section 4(b), as requested. If You create an Adaptation,
upon notice from a Licensor You must, to the extent practicable, remove from the Adaptation any
credit (inclusive of any logo, trademark, official mark or official emblem) as required by Section
4(b), as requested.b. If You Distribute, or Publicly Perform the Work or any Adaptations or Collections, You must, unless
a request has been made pursuant to Section 4(a), keep intact all copyright notices for the Work
and provide, reasonable to the medium or means You are utilizing: (i) any attributions that the
Licensor indicates be associated with the Work as indicated in a copyright notice, (ii) the title of the
Work if supplied; (iii) to the extent reasonably practicable, the URI, if any, that the Licensor
specifies to be associated with the Work, unless such URI does not refer to the copyright notice or
licensing information for the Work; and, (iv) consistent with Section 3(b), in the case of an
Adaptation, a credit identifying the use of the Work in the Adaptation. The credit required by this
Section 4(b) may be implemented in any reasonable manner; provided, however, that in the case
of an Adaptation or Collection, at a minimum such credit will appear, if a credit for all contributors to
the Adaptation or Collection appears, then as part of these credits and in a manner at least as
prominent as the credits for the other contributors. For the avoidance of doubt, You may only use
the credit required by this Section for the purpose of attribution in the manner set out above and,
by exercising Your rights under this License, You may not implicitly or explicitly assert or imply any
connection with, sponsorship or endorsement by the Licensor or others designated for attribution,
of You or Your use of the Work, without the separate, express prior written permission of the
Licensor or such others.
c. Except as otherwise agreed in writing by the Licensor, if You Reproduce, Distribute or Publicly
Perform the Work either by itself or as part of any Adaptations or Collections, You must not distort,
mutilate, modify or take other derogatory action in relation to the Work which would be prejudicial
to the honor or reputation of the Licensor where moral rights apply.
5. Representations, Warranties and Disclaimer
THE LICENSOR OFFERS THE WORK AS-IS AND MAKES NO REPRESENTATIONS OR
WARRANTIES OF ANY KIND CONCERNING THE WORK, EXPRESS, IMPLIED, STATUTORY OR
OTHERWISE, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, OR THE ABSENCE OF LATENT OR
OTHER DEFECTS, ACCURACY, OR THE PRESENCE OF ERRORS, WHETHER OR NOT
DISCOVERABLE.
6. Limitation on Liability
IN NO EVENT WILL THE LICENSOR BE LIABLE TO YOU ON ANY LEGAL THEORY FOR ANY
SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES ARISING OUT
OF THIS LICENSE OR THE USE OF THE WORK, EVEN IF THE LICENSOR HAS BEEN ADVISED OF
THE POSSIBILITY OF SUCH DAMAGES.
7. Termination
a. Subject to the terms and conditions set forth in this License, the license granted here lasts for the
duration of the term of the copyright in the Work licensed by the Licensor as stated in Section 3.
Notwithstanding the above, the Licensor reserves the right to release the Work under different
license terms or to stop distributing the Work at any time; provided, however that any such election
will not serve to withdraw this License (or any other license that has been, or is required to be,
granted under the terms of this License), and this License will continue in full force and effect
unless terminated as stated below.
b. If You fail to comply with this License, then this License and the rights granted hereunder will
terminate automatically upon any breach by You of the terms of this License. Individuals or entities
who have received Adaptations or Collections from You under this License, however, will not have
their licenses terminated provided such individuals or entities remain in full compliance with those
licenses. Sections 1, 2, 5, 6, 7, and 8 will survive any termination of this License. Notwithstanding
the foregoing, this License reinstates automatically as of the date the violation is cured, provided it
is cured within 30 days of You discovering the violation, or upon express reinstatement by the
Licensor. For the avoidance of doubt, this Section 7(b) does not affect any rights the Licensor may
have to seek remedies for violations of this License by You.
8. Miscellaneous
a. Each time You Distribute or Publicly Perform the Work or a Collection, the Licensor offers to the
recipient a license to the Work on the same terms and conditions as the license granted to Youunder this License.
b. Each time You Distribute or Publicly Perform an Adaptation, the Licensor offers to the recipient a
license to the original Work on the same terms and conditions as the license granted to You under
this License.
c. If any provision of this License is invalid or unenforceable, it shall not affect the validity or
enforceability of the remainder of the terms of this License, and without further action, such
provision shall be reformed to the minimum extent necessary to make such provision valid and
enforceable.
d. No term or provision of this License shall be deemed waived and no breach consented to unless
such waiver or consent shall be in writing and signed by the Licensor.
e. This License constitutes the entire agreement between You and the Licensor with respect to the
Work licensed here. There are no understandings, agreements or representations with respect to
the Work not specified here. The Licensor shall not be bound by any additional provisions that may
appear in any communication from You. This License may not be modified without the mutual
written agreement of the Licensor and You.
f. The rights granted under, and the subject matter referenced, in this License were drafted utilizing
the terminology of the Berne Convention for the Protection of Literary and Artistic Works (as
amended on September 28, 1979), the Rome Convention of 1961, the WIPO Copyright Treaty of
1996, the WIPO Performances and Phonograms Treaty of 1996 and the Universal Copyright
Convention (as revised on July 24, 1971). Interpretation of the scope of the rights granted by the
Licensor and the conditions imposed on You under this License, this License, and the rights and
conditions set forth herein shall be made with reference to copyright as determined in accordance
with general principles of international law, including the above mentioned conventions.
g. Nothing in this License constitutes or may be interpreted as a limitation upon or waiver of any
privileges and immunities that may apply to the Licensor or You, including immunity from the legal
processes of any jurisdiction, national court or other authority.
h. Where the Licensor is an IGO, any and all disputes arising under this License that cannot be
settled amicably shall be resolved in accordance with the following procedure:
i. Pursuant to a notice of mediation communicated by reasonable means by either You or the
Licensor to the other, the dispute shall be submitted to non-binding mediation conducted in
accordance with rules designated by the Licensor in the copyright notice published with the
Work, or if none then in accordance with those communicated in the notice of mediation.
The language used in the mediation proceedings shall be English unless otherwise agreed.
ii. If any such dispute has not been settled within 45 days following the date on which the
notice of mediation is provided, either You or the Licensor may, pursuant to a notice of
arbitration communicated by reasonable means to the other, elect to have the dispute
referred to and finally determined by arbitration. The arbitration shall be conducted in
accordance with the rules designated by the Licensor in the copyright notice published with
the Work, or if none then in accordance with the UNCITRAL Arbitration Rules as then in
force. The arbitral tribunal shall consist of a sole arbitrator and the language of the
proceedings shall be English unless otherwise agreed. The place of arbitration shall be
where the Licensor has its headquarters. The arbitral proceedings shall be conducted
remotely (e.g., via telephone conference or written submissions) whenever practicable.
iii. Interpretation of this License in any dispute submitted to mediation or arbitration shall be as
set forth in Section 8(f), above.
</details>

- **Standard License Header**:

**Comment by seabass-labrax** [comment]
Thanks for submitting this, @alanorth!

**Comment by swinslow** [comment]
+1 to adding, given our standard approach to adding CC license variants, and the indication of real-world publications using this variant.

**Comment by jlovejoy** [comment]
@alanorth - sorry for the trouble with the online submission tool - if you find that again, please do submit an issue or otherwise document where things went wrong, so we can look into it!

+1  to adding

**Comment by jlovejoy** [comment]
raised on July 14th call - accepted

**Comment by swinslow** [comment]
Discussed on 2022-07-14 legal team call, agreed to add.

@alanorth Can you submit the PR for the XML file and test text file for this one? Thanks!

**Comment by goneall** [comment]
@alanorth - sorry for the problems with the online tools.  I just tried to duplicate the problem submitting the same license text and it didn't fail - actually, it didn't show the compare modal.  If you have a way to duplicate the problem, please submit an issue at https://github.com/spdx/spdx-online-tools/issues

**Comment by swinslow** [comment]
I'll add the PR for this.

**Comment by alanorth** [comment]
@swinslow thank you, I appreciate it. I looked at the repo a few weeks ago and wasn't sure what was required to add the new license.
