### ISSUE TITLE
Add new license identifiers

### ISSUE THREAD

**Issue by ghost** [spdx/license-list-XML#1527]
(L)GPL-3.0-or-earlier
GPL-2.0-or-earlier
GPL-1.0-or-earlier
GPL-any
GPL-any-or-earlier
GPL-any-or-later

Since GPL-X-or-later is a legal license id, I figure why not the opposite, if something is under GPLv3 or any earlier version, they can go backward and combine it with an earlier version of the GPL

**Comment by bsdimp** [comment]
None of these make any sense.

GPL-1.0 isn't in use, so it would fail the 'in use' test.
It was only around for a very short time in the 90s before
the FSF replaced it and everybody, at the time, followed
to GPLv2.
Nobody uses or earlier language, so it fails that test.
And I don't think legally it makes sense, but I'm not a lawyer.
The law isn't symmetrical, alas...

**Comment by zvr** [comment]
Not only are these never used in practice, there is also no need for them.

One could already express "GPL-2.0-or-earlier" as `GPL-1.0-only OR GPL-2.0-only`,

The whole point of "or later" is dealing with future versions not already known. This makes no sense for past versions.

**Comment by seabass-labrax** [comment]
Hello @natewrench! SPDX Steering Committee member here. Thank you for raising this issue; I know I'm a little late to the discussion, but I just wanted to say we really appreciate suggestions such as yours, even if they don't draw enough consensus to be included. If you have any specific use cases that you'd like help with, please let us know and we'll try to be of assistance! :smile:
