### ISSUE TITLE
New license request: NICTA Public Software Licence 1.0

### ISSUE THREAD

**Issue by fu7mu4** [spdx/license-list-XML#1528]
- Full name: NICTA Public Software License Version 1.0
- Short identifier: NICTA-Public-Software-1.0
- Other web pages for license/exception: https://opensource.apple.com/source/mDNSResponder/mDNSResponder-320.10/mDNSPosix/nss_ReadMe.txt
- Notes: a one of variants of BSD-3-clause, I don't know which spell is better `license` or `licence` in name and text
- OSI Approved:
- FSF Free/Libre:
- Text:
```
NICTA Public Software Licence
Version 1.0

Copyright Â© 2004 National ICT Australia Ltd

All rights reserved.

By this licence, National ICT Australia Ltd (NICTA) grants permission,
free of charge, to any person who obtains a copy of this software
and any associated documentation files ("the Software") to use and
deal with the Software in source code and binary forms without
restriction, with or without modification, and to permit persons
to whom the Software is furnished to do so, provided that the
following conditions are met:

- Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimers.
- Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimers in
  the documentation and/or other materials provided with the
  distribution.
- The name of NICTA may not be used to endorse or promote products
  derived from this Software without specific prior written permission.

EXCEPT AS EXPRESSLY STATED IN THIS LICENCE AND TO THE FULL EXTENT
PERMITTED BY APPLICABLE LAW, THE SOFTWARE IS PROVIDED "AS-IS" AND
NICTA MAKES NO REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY
REPRESENTATIONS, WARRANTIES OR CONDITIONS REGARDING THE CONTENTS
OR ACCURACY OF THE SOFTWARE, OR OF TITLE, MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE, NONINFRINGEMENT, THE ABSENCE OF LATENT
OR OTHER DEFECTS, OR THE PRESENCE OR ABSENCE OF ERRORS, WHETHER OR
NOT DISCOVERABLE.

TO THE FULL EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL
NICTA BE LIABLE ON ANY LEGAL THEORY (INCLUDING, WITHOUT LIMITATION,
NEGLIGENCE) FOR ANY LOSS OR DAMAGE WHATSOEVER, INCLUDING (WITHOUT
LIMITATION) LOSS OF PRODUCTION OR OPERATION TIME, LOSS, DAMAGE OR
CORRUPTION OF DATA OR RECORDS; OR LOSS OF ANTICIPATED SAVINGS,
OPPORTUNITY, REVENUE, PROFIT OR GOODWILL, OR OTHER ECONOMIC LOSS;
OR ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL, PUNITIVE OR
EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH THIS LICENCE,
THE SOFTWARE OR THE USE OF THE SOFTWARE, EVEN IF NICTA HAS BEEN
ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

If applicable legislation implies warranties or conditions, or
imposes obligations or liability on NICTA in respect of the Software
that cannot be wholly or partly excluded, restricted or modified,
NICTA's liability is limited, to the full extent permitted by the
applicable legislation, at its option, to:

a. in the case of goods, any one or more of the following:
  i.   the replacement of the goods or the supply of equivalent goods;
  ii.  the repair of the goods;
  iii. the payment of the cost of replacing the goods or of acquiring
       equivalent goods;
  iv.  the payment of the cost of having the goods repaired; or
b. in the case of services:
  i.   the supplying of the services again; or 
  ii.  the payment of the cost of having the services supplied
       again.
```
- Standard License Header:

**Comment by jlovejoy** [comment]
Thanks @fu7mu4 - do work for or represent the NICTA?
Also, can you provide some examples of where this license is actually  used?  It looks like the link you provided is for a project, libnss_mdns - is that the only place you've come across this license?

**Comment by jlovejoy** [comment]
discussed on July 14th - this project that uses this old license, libnss_mdns, is used in Debian, most web browsers, been around for some time. It looks like the project has (somehow) changed the license to LGPL-2.1-or-later, but this license is still in circulation, so probably worth adding.
https://opencores.org/websvn/filedetails?repname=c0or1k&path=%2Fc0or1k%2Ftrunk%2Fconts%2Flibc%2Finclude%2Fstdio.h&rev=0

**Comment by Pizza-Ria** [comment]
Gowri and I will take this.

**Comment by KIRWOG** [comment]
> Gowri and I will take this.

👍

**Comment by fu7mu4** [comment]
@jlovejoy I've never seen this license at all except that https://opensource.apple.com/source/mDNSResponder/mDNSResponder-320.10/mDNSPosix/nss_ReadMe.txt

**Comment by Pizza-Ria** [comment]
# New submission review

## Has the license been approved by the OSI? No

## Definitive factors

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?  Unique enough – it is only a 41.8% match to the [Intel Open Source License - Intel](https://spdx.org/licenses/Intel.html).   Also note, the Intel License has been retired by OSI.  

### If a software license, does it apply to source code and not only to executables?

Yes -  language includes “to use and deal with the Software in source code and binary forms without restriction.”

### Does the license have identifiable and stable text, and is not in the midst of drafting?

Most likely stable as this is a license that applies to older components and no longer seems to be in active drafting.

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

We could not definitely determine who the license steward was – may no longer exist.  Searching on nicta.com.au takes one to a completely different organization:  https://data61.csiro.au/.  There is an author reference to Andrew White at Nicta in this doc:   https://opensource.apple.com/source/mDNSResponder/mDNSResponder-320.10/mDNSPosix/nss_ReadMe.txt (circa 2004).  Searching this name on LinkedIn did not reveal any definitive candidates.  

## Other factors for inclusion

### 1. Does the license substantially comply with one of the free/open content definitions?

Largely meets the Open Source Definition but for the following additional cure provisions:


If applicable legislation implies warranties or conditions, or imposes obligations or liability on NICTA in respect of the Software that cannot be wholly or partly excluded, restricted or modified, NICTA's liability is limited, to the full extent permitted by the applicable legislation, at its option, to:  
a. in the case of goods, any one or more of the following:  i. the replacement of the goods or the supply of equivalent goods; ii. the repair of the goods; iii. the payment of the cost of replacing the goods or of acquiring equivalent goods; iv. the payment of ther country to which the U.S. has embargoed goods and services. st of having the goods repaired; or b. in the case of services: i. the supplying of the services again; or ii. the payment of the cost of having the services supplied again.


### 2. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

YES.


### 3. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this*

As discussed, this project that uses this old license, libnss_mdns, is used in Debian, most web browsers, been around for some time. It looks like the project has (somehow) changed the license to LGPL-2.1-or-later, but this license is still in general circulation for foundational components deep in software stacks.  See, [OpenCores](https://opencores.org/websvn/filedetails?repname=c0or1k&path=%2Fc0or1k%2Ftrunk%2Fconts%2Flibc%2Finclude%2Fstdio.h&rev=0).  

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

YES (also note that this license removed the Intel export restrictions). 

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

Not in opposition as far as we know – unable to contact the steward.

## Summary of factors / outcome

Recommend that we approve this license per discussions in the July 14th meeting.  Determined to be in sufficient circulation that providing an identifier will serve the SPDX’s mission of software identification.

**Comment by swinslow** [comment]
Thank you @Pizza-Ria and @KIRWOG! I agree with all of your analysis and conclusions here.

I would just add that I don't view the additional limitations of liability to conflict with the Open Source Definition (though definitely open to discussing if you disagree!) Either way, I'm a +1 to add this for all of the reasons you indicated.

**Comment by jlovejoy** [comment]
+1 to add

**Comment by swinslow** [comment]
# License Inclusion Decision
## Decision:
* approved 
## Full name:
* NICTA Public Software Licence Version 1.0
## Short id:
* NICTA-1.0
## XML markup:
* no replaceable text at this time, just historical usage
## Additional rationale or notes on decision:
* N/A

**Comment by swinslow** [comment]
I'll take the XML + test text for this one to get it in for 3.18

**Comment by swinslow** [comment]
Just noting so folks are aware: The version of the license linked at https://opencores.org/websvn/filedetails?repname=c0or1k&path=%2Fc0or1k%2Ftrunk%2Fconts%2Flibc%2Finclude%2Fstdio.h&rev=0 is different from the originally-submitted one at https://opensource.apple.com/source/mDNSResponder/mDNSResponder-320.10/mDNSPosix/nss_ReadMe.txt.

I haven't reviewed the one at OpenCores in significant detail, but a couple of the substantive differences include:
* the list of granted rights in the first paragraph of each version is different; and
* the one on OpenCores includes a choice-of-law provision at the end, which the original submission does not.

Given that, since the originally-submitted version on the Apple site is the one we've focused on for this review, that's the text I'm going to add as NICTA-1.0. If someone subsequently submits the OpenCores-hosted variant for consideration, that can be explored as a different license.
