### ISSUE TITLE
New license request: ASWF Digital Assets License 1.1

### ISSUE THREAD

**Issue by zvr** [spdx/license-list-XML#1551]
- Full name: ASWF Digital Assets License version 1.1
- Short identifier: ASWF-Digital-Assets-1.1
- Other web pages for license/exception: https://github.com/AcademySoftwareFoundation/foundation/tree/main/digital_assets
- Notes:
- OSI Approved:
- FSF Free/Libre:
- Text:

ASWF Digital Assets License v1.1

License for <Asset Name> (the “Asset Name”).

<Asset Name> Copyright <Year> <Asset Owner>. All rights reserved.

Redistribution and use of these digital assets, with or without modification, solely for education, training, research, software and hardware development, performance benchmarking (including publication of benchmark results and permitting reproducibility of the benchmark results by third parties), or software and hardware product demonstrations, are permitted provided that the following conditions are met:

1. Redistributions of these digital assets or any part of them must include the above copyright notice, this list of conditions and the disclaimer below, and if applicable, a description of how the redistributed versions of the digital assets differ from the originals.

2. Publications showing images derived from these digital assets must include the above copyright notice.

3. The names of copyright holder or the names of its contributors may NOT be used to promote or to imply endorsement, sponsorship, or affiliation with products developed or tested utilizing these digital assets or benchmarking results obtained from these digital assets, without prior written permission from copyright holder.

4. The assets and their output may only be referred to as the Asset Name listed above, and your use of the Asset Name shall be solely to identify the digital assets. Other than as expressly permitted by this License, you may NOT use any trade names, trademarks, service marks, or product names of the copyright holder for any purpose.

DISCLAIMER: THESE DIGITAL ASSETS ARE PROVIDED BY THE COPYRIGHT HOLDER “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, ARE DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THESE DIGITAL ASSETS, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by swinslow** [comment]
See my comment [in the 1.0 version of the license](https://github.com/spdx/license-list-XML/issues/1550#issuecomment-1206484522) for a few details on context. Also noting that [here is a redline](https://editor.mergely.com/6W9zXGf0/?wl=1) made available by the license steward regarding the diff between 1.0 and 1.1.

**Comment by jlovejoy** [comment]
as this is the same as #1550 except the addition of "and if applicable, a description of how the redistributed versions of the digital assets differ from the originals." in the first clause, the analysis there also applies here.

**Comment by bsdimp** [comment]
The changes from #1550 don't change my analysis, though it does add an attribution requirement. here's my comment from #1550: 

+1 for inclusion, since it is open source or open source adjacent. Since it doesn't apply 100% to code, but rather data, I think it's OK since the clear guidelines for what is 'open source' don't yet have a clear analog for 'open data' though many standards are competing today...  I think that the restrictions wouldn't unduly interfere with its basic use or distribution, but could affected 'derived works', which gives me some pause, but not enough to reject.

**Comment by Pizza-Ria** [comment]
Same comment as #1550 - I don't love the restriction - "solely for education, training, research, software and hardware development, performance benchmarking (including publication of benchmark results and permitting reproducibility of the benchmark results by third parties), or software and hardware product demonstrations" - seems to be intentionally omitting any commercial endeavors although not quite sure what the scope of "software and hardware development" ... is that limited to internal use? I would be against unless this is prolifically utilized to the point that not giving it an SPDX identifier creates a hardship. @zvr indicated that all the content by ASWF is under this license but I don't know if that is enough to tip the scales in favor - defer to the rest of the group on that question.

**Comment by kestewart** [comment]
+1 for inclusion.   As we add in the dataset profile to SPDX, more of these data licenses will be showing up.    To represent software adequately these days with AI/ML components, capturing the dataset component is only going to become more important.

**Comment by swinslow** [comment]
I'm preparing the XML for this one.
