### ISSUE TITLE
New license request: Graphics-Gems [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1552]
**1.** License Name: Graphics Gems EULA
**2.** Short identifier: Graphics-Gems
**3.** License Author or steward: Eric Haines
**4.** Comments: The license is found in at least one Fedora package and undoubtedly is present in counterpart packages in other Linux distributions. While horribly worded, in my view the license meets criterion 1 (hence it is likely to be classified as 'allowed' by Fedora).
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/150
**7.** URL(s): http://www.realtimerendering.com/resources/GraphicsGems/, https://github.com/erich666/GraphicsGems/blob/master/LICENSE.md
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://webkitgtk.org/

**Comment by swinslow** [comment]
Hi @richardfontana, thanks for submitting this. At a first glance, I tend to agree that this is appropriate to add to the license list based on the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). 

I don't have time at the moment to do a [full writeup](https://github.com/spdx/license-list-XML/blob/master/DOCS/submission-response-template.md), but from a quick read of the language and given its use in WebKit + Fedora I would be a +1 to add.

As a reminder to myself or whoever else does the writeup, [here's one instance of the specific use of this license in the WebKit code](https://github.com/WebKit/WebKit/blob/6e13c5d56ebc463d6b210b6a4884e9b377f01455/Source/WebCore/platform/graphics/transforms/TransformationMatrix.cpp#L47-L54).

**Comment by jlovejoy** [comment]
# New submission review

## Definitive factors

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?
no

### If a software license, does it apply to source code and not only to executables?
yes

### Does the license have identifiable and stable text, and is not in the midst of drafting?
yes, stable

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?
appears to be the only license version, so probably n/a

## Other factors for inclusion


### 1. Does the license substantially comply with one of the free/open content definitions?
yes

### 2. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?
as written, it is specific to Graphic Gems. if other uses are found, we can accommodate that with replaceable markup for the name.

### 3. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
yes, Webkit is a major project 

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?
yes

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?
not sure

## Summary of factors / outcome
yes to add

**Comment by OliverFendt** [comment]
I am in favor to add the license to the list

**Comment by LeChasseur** [comment]
Is there any indication that modification is permitted?

**Comment by richardfontana** [comment]
> Is there any indication that modification is permitted?

Not explicitly and unambiguously. As a matter of cultural context, I believe the license (and in particular the term "use") is intended to permit modification.

**Comment by OliverFendt** [comment]
@LeChasseur good point. 
If there is no permission to modify the work and to distribute the work in modified form, this license is not conformant to the open source definition and due to this it shall not be included in the license list (at least this was what I was told (although there are already non conformant licenses element of this list))

**Comment by bsdimp** [comment]
> @LeChasseur good point. If there is no permission to modify the work and to distribute the work in modified form, this license is not conformant to the open source definition and due to this it shall not be included in the license list (at least this was what I was told (although there are already non conformant licenses element of this list))

The license reads, to me as a non-lawyer, as intending to grant permission to create derived works. It's poorly drafted with a lot of that 'reading' is implicit: (paraphrasing) You can't claim it as your own, but you can use it other works on an AS-IS, your own risk if you aren't a jerk about it...  So the intent appears to be in the right place, but I'll leave it to the legal folks if that's sufficient for inclusion or not, if the intent is plain enough, etc. I don't know what standards are generally used for cases like this.

Too bad we don't have a 'This is a bad license, don't use it in anything new" flag, though creating one would be... problematic at best?

**Comment by richardfontana** [comment]
If a license like this can't be included in the SPDX license list, that has significant implications for any community Linux distribution seeking to use SPDX identifiers to the extent possible (including Fedora). Linux distributions are full of packages with legacy informal licenses similar to this one.

**Comment by Pizza-Ria** [comment]
While acknowledging @richardfontana's point, if the "use" clause was followed by "for any purpose" then I'd be more comfortable with the very broad interpretation of "use" to include derivative works/modifications.  Not necessarily opposed to giving it an SPDX identifier but also not really convicted that it fulfills #1 of the Other Factors in the License Inclusion Principles.

**Comment by jlovejoy** [comment]
Thanks all for the interesting discussion. I have marked this as accepted.

The operative question for any new submission is: does it meet those principles?

To clarify a few points:
@LeChasseur @OliverFendt - the license inclusion guidelines were updated a couple years ago and made a bit more lenient (relating to adherence with OSD) from what you likely remember. Have a look: https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md

As to the drafting issue - yeah, well, there are lots of legal documents (contracts, licenses, etc.) that are poorly drafted. Sometimes that can lead to litigation or generally frustrate the goals of the parties. However, we manage to get things done in spite of this. :)  I'm pretty sure there are other examples that don't explicitly use "modify" or "create a derivative work" in the grant. I think of "use" gets used often because it's quite broad and more inline with plain English (rather than drafting strict adherence to terminology from the Copyright Act, for example).

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [x] approved
- [ ] not approved

## License full name

Graphics Gems License

## Short ID

Graphics Gems

## XML markup

Mark as optional the language before "EULA"

## Additional rationale or notes on decision:

_add any additional information, including optionally a summary of what is recorded in the issue comments_
