### ISSUE TITLE
New license request: SunPro [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1553]
**1.** License Name: SunPro License
**2.** Short identifier: SunPro
**3.** License Author or steward: Sun Microsystems
**4.** Comments: This is a legacy permissive license covering code in at least one Fedora package (likely others) and undoubtedly counterpart packages in other Linux distributions.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/151
**7.** URL(s): https://scancode-licensedb.aboutcode.org/sunpro.html
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://webkitgtk.org

**Comment by richardfontana** [comment]
License text:

Permission to use, copy, modify, and distribute this
software is freely granted, provided that this notice
is preserved.

**Comment by seabass-labrax** [comment]
# New submission review

## Has the license been approved by the OSI?
*All OSI-approved license will be included on the SPDX License List, regardless of other factors*

No, it doesn't seem that the OSI has reviewed this license.

## Definitive factors
*These must all be satisfied to allow inclusion in the license list*

### Is the submitted license unique, that is, it does not match another license already on the License List as per the matching guidelines?

Yes, it is not already on the SPDX License List.

### If a software license, does it apply to source code and not only to executables?

Yes, it can apply to source code as well as executables.

### Does the license have identifiable and stable text, and is not in the midst of drafting?

Yes, it is a historical license and not expected to change.

### Has the license steward, if any, committed to versioning new versions in the future and to not modify it after addition to the list?

Maybe: the license steward (Sun Microsystems) is no longer active, and their successor (Oracle) seems unlikely to modify it.

## Other factors for inclusion
*Roughly in order of descending importance*

### 1. Does the license substantially comply with one of the free/open content definitions?
*Approval by the organisation that publishes the definition is not required*

Yes, the license appears to fulfil the requirements of all the free/open content definitions used by SPDX.

### 2. Is the license structured to be generally usable by anyone, and not specific to one organisation or project?

Yes, with replaceable text for the `Developed at SunPro, a Sun Microsystems, Inc. business.` or other copyright line.

### 3. Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?
*For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this*

Yes, it is used in multiple software libraries which are available in major free software distributions. 

### 4. Is the license primarily intended to facilitate the free distribution of content with limited restrictions?

Yes; see factor 1.

### 5. Does the license steward support this submission, or is at least aware of and not in opposition of it?

There is no indication that the license steward is aware of this submission.

## Summary of factors / outcome
*Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives*

Given the status the historical usage of this license and its ongoing presence in prominent open source projects, I would strongly support the addition of this license in the SPDX License List.

**Comment by swinslow** [comment]
Thanks @seabass-labrax! Appreciate the writeup  :)  and agreed with all of the above.

**Comment by jlovejoy** [comment]
+1 to add as well. 

and I think this is a good short identifier as well

@richardfontana - do you want to take a stab at preparing the xml and .txt files? This is a good one to test on... ;)  We have some rather extensive documentation on this here https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md (which might need some fresh eyes/suggestions) or you can just look at an existing file

**Comment by jlovejoy** [comment]
I'm marking this as 3.20 due to our "3.19 documentation release plans", but if we have the files ready, we can always move up.

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by rpaouline** [comment]
+1 to add
This license is also known as "SunPro Attribution License"

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [x] approved
- [ ] not approved

## License full name

SunPro License

## Short ID

SunPro

## XML markup

None

## Additional rationale or notes on decision:

None

**Comment by jlovejoy** [comment]
do we have a link to use in webkit? I searched and can't find this...

**Comment by richardfontana** [comment]
> do we have a link to use in webkit? I searched and can't find this...

One source file has two uses:

https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/runtime/MathCommon.cpp#L47
https://github.com/WebKit/WebKit/blob/main/Source/JavaScriptCore/runtime/MathCommon.cpp#L56

That seems to originate in this ancient library:
https://netlib.org/fdlibm/index.html
It seems most or all of the files there have this license.
