### ISSUE TITLE
New license request: FSFULLRWD [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1556]
**1.** License Name: FSF Unlimited License (With License Retention and Warranty Disclaimer)
**2.** Short identifier: FSFULLRWD
**3.** License Author or steward: Free Software Foundation
**4.** Comments: It is a minimalist highly permissive license that is evidently inserted on Makefile.in files generated by GNU Automake. It resembles FSFULLR except it adds a typical GNU-style warranty disclaimer. I found it in one Fedora source package (cockpit).
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/152
**7.** URL(s): https://lists.gnu.org/archive/html/autoconf/2012-04/msg00061.html (first reference)
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://kojipkgs.fedoraproject.org//packages/cockpit/270/1.fc36/src/cockpit-270-1.fc36.src.rpm (extract the source archive)

**Comment by richardfontana** [comment]
I don't actually like "FSFULLRWD" but I figure it follows the pattern of FSFULLR (which is also bad).

**Comment by jlovejoy** [comment]
Given this is similar to a license already approved, I'm going to give it +1 to add and forego full analysis.

re: name, @richardfontana - by way of interest and history: FSFUL and FSFULLR were added to the SPDX License List as part of the 2013/14 compare to the Fedora "good" list and SPDX simply used the Fedora/Callaway short name for the SPDX short identifiers :)

**Comment by swinslow** [comment]
Also +1 to add and +1 on the feelings expressed above re: license names / IDs.

**Comment by OliverFendt** [comment]
I had a look at the new license request and have several comments.
Given the text:

> Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, # 2003, 2004, 2005, 2006, 2007, 2008, 2009 Free Software Foundation, # Inc. # This Makefile.in is free software; the Free Software Foundation # gives unlimited permission to copy and/or distribute it, # with or without modifications, as long as this notice is preserved.

> This program is distributed in the hope that it will be useful, # but WITHOUT ANY WARRANTY, to the extent permitted by law; without # even the implied warranty of MERCHANTABILITY or FITNESS FOR A # PARTICULAR PURPOSE.

1. All comment signs # shall be removed before inculsion
2. The Copyright statement shall be removed, since it belongs not to the the license text
3. The "Makefile.in" shall be marked as "not to be used for matching" since there are plenty of variations on this word out there like: > This file is free software;...

**Comment by jlovejoy** [comment]
@richardfontana - do you want to prep the files to add this? we have some instructions here: https://github.com/spdx/license-list-XML/blob/main/DOCS/new-license-workflow.md#accepted  :)

**Comment by OliverFendt** [comment]
@jlovejoy to be honest I do not understand you comment about the copyright statements.

If you look for example at the software package bash 5.1.16 there is: 

> Copyright (C) 1994-2014 Free Software Foundation, Inc.

> This Makefile.in is free software; the Free Software Foundation
   gives unlimited permission to copy and/or distribute it,
   with or without modifications, as long as this notice is preserved.

> This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY, to the extent permitted by law; without
even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

or if you look at grep 3.6 there is:

> Copyright (C) 1994-2020 Free Software Foundation, Inc.

> This Makefile.in is free software; the Free Software Foundation
gives unlimited permission to copy and/or distribute it,
with or without modifications, as long as this notice is preserved.

>  This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY, to the extent permitted by law; without
 even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE.

And there are probably another thousand different copyright statements followed by the same text and what I learned one has to provide the exact copyright statement which is in the file and not an arbitrary one and not an arbitrary one and the exact one.

Can you please explain to me why you want to keep the copyright statement as it was provided in the request?

**Comment by jlovejoy** [comment]
hi @OliverFendt - let me explain:
- I was assuming this comment is related to #1575 which I marked as related to the broader (not license-specific) issue of #1452 due to it sounds like you are using SPDX license data to generate license text 
- as per the matching guidelines, we mark any existing copyright notice with the appropriate XML tag to indicate this is not "matchable" 
- to my knowledge, we have not simply removed copyright notices from licenses as you are suggesting

I'm not saying we couldn't do that. But I don't think that is something we want to start doing without some discussion as it has bigger implications - like, would that mean we go back and remove copyright notices in all existing licenses on the SPDX License List?

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by richardfontana** [comment]
There are variants of this license that use "file" instead of "Makefile.in". For example:

https://github.com/ianlancetaylor/libbacktrace/blob/master/aclocal.m4#L5

```
# generated automatically by aclocal 1.15.1 -*- Autoconf -*-

# Copyright (C) 1996-2017 Free Software Foundation, Inc.

# This file is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
