### ISSUE TITLE
New license request: Loguru [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by oturpe** [spdx/license-list-XML#1558]
**1.** License Name: Loguru License
**2.** Short identifier: Loguru
**3.** License Author or steward: Emil Ernerfeldt <emil.ernerfeldt@gmail.com>
**4.** Comments: Simple, public domain -like license used in "Loguru: a lightweight and flexible C++ logging library".

License author has been made aware of this submission, support statement pending:
https://github.com/emilk/loguru/issues/142#issuecomment-1208604700

I am making this submission, because code under this license in used in Fedora package dosbox-staging, and Fedora's new rules for allowed licenses require submitting licenses previously considered "public domain".
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/154
**7.** URL(s): https://github.com/emilk/loguru#license
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/emilk/loguru, https://github.com/dosbox-staging/dosbox-staging/tree/main/src/libs/loguru

**Comment by oturpe** [comment]
Fedora license review: [fedora-license-data#54](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/54)

**Comment by swinslow** [comment]
Thanks @oturpe!

For the SPDX legal team reviewers, the specific text is the following: "This software is in the public domain. Where that dedication is not recognized, you are granted a perpetual, irrevocable license to copy, modify and distribute it as you see fit."

In the [loguru project's README](https://github.com/emilk/loguru#license) I see there's now (as of about half an hour ago) a dual-licensed option to also use the software under [the `Unlicense` license](https://spdx.org/licenses/Unlicense.html). But I think this should be disregarded for purposes of this submission, and just the text above used as the language for the proposed `Loguru` license submitted here.

Personally I'm +1 to add this. Not doing a full [writeup](https://github.com/spdx/license-list-XML/blob/master/DOCS/submission-response-template.md) at the moment, but this is a simple public-domain-equivalent statement with a license fallback, similar to `Unlicense`. Given its use in Fedora and dosbox together with the above, I'm in favor of adding it.

**Comment by oturpe** [comment]
Yes, the author added Unlicense as an option as result of these reviews.
For DOSBox Staging in Fedora, that opens two new avenues of solving the issue with licensing:

1. Rebase BOSBox Staging's bundled Loguru to version that allows Unlicense.
2. Package Loguru separately in Fedora, unbundle Loguru from DOSBox staging.

Thus, having this license available in SPDX for Fedora use is not as important as it still was yesterday.
Both alternatives still require development effort,
so adding this license would still be a "nice to have".

**Comment by jlovejoy** [comment]
@oturpe - do we think we still need this?
Is this license used anywhere other than just this project (do you know)?

**Comment by oturpe** [comment]
I am not aware of any other project using this license.
Most probably there is none.
