### ISSUE TITLE
templates for new license and decision

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1565]
- [x] make new license review template a bit simplified
- [x] change filenames to "template-(name).md" to make it more obvious
- [x] explain somewhere how to use templates (probably README)

**Comment by jlovejoy** [comment]
@vmbrasseur to take this one

**Comment by vmbrasseur** [comment]
Howdy. Commenting so I can get assigned to this one.

**Comment by vmbrasseur** [comment]
Hey there, folks! Apologies for the delay, but I totally forgot I'd offered to do this one. Now I need some clarification:

* This is the [license-decision-template](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-decision-template.md), yes?
* The brief is to simplify it but…it's only 11 lines as is. Could someone please provide more detail on what exactly to simplify here?

Thanks!

**Comment by jlovejoy** [comment]
"make new license review template a bit simplified" was referring to https://github.com/spdx/license-list-XML/blob/main/DOCS/submission-response-template.md - I just made a PR to make the top part an ordered list and a change in the order of factors.  So would be good to have the template reflect those changes too

 "explain somewhere how to use templates (probably README)" - really should be, "update DOCS README as needed" - https://github.com/spdx/license-list-XML/blob/main/DOCS/README.md
- the matching guidelines item is no longer relevant and the templates are really listed there - as to the latter, it'd be nice to list them and a short blurb as to how they are used?

**Comment by jlovejoy** [comment]
note #1642 is still waiting to be merged, but README should also reflect filename changes perhaps?

**Comment by vmbrasseur** [comment]
The "PR to make the top part an ordered list and a change in the order of factors" PR is #1647.

**Comment by vmbrasseur** [comment]
Okiedoke, this is ready for review over in PR #1665
