### ISSUE TITLE
Improvements or changes to license list release/publishing process

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1569]
Let's consider whether it would be possible to either:
1. enable a "preview" release of the license list, so that newly-adopted submissions are visible; and/or
2. at least document how people can find newly-adopted licenses within the license-list-data repo immediately; and/or
3. use a GitHub bot to notify about when it will be available.

**Comment by swinslow** [comment]
Also discuss whether folks "should" use identifiers prior to a release going out to the website

**Comment by swinslow** [comment]
Noted that SPDX documents currently require a numbered version of license list to be indicated

**Comment by jlovejoy** [comment]
was called, "Improvements to communicating timing between merging and publishing" - but changed to make more general, as could include discussion of updates to entire process, especially considering potential website overhaul/move to Gitbut that @seabass-labrax is working on

**Comment by jlovejoy** [comment]
additional topic: could release be "automated" and more frequent? impact on spec field? do we need spec field for license list version??

**Comment by goneall** [comment]
Some of this is already in place - I'm very overloaded with the 2.3 spec release today, but I'll try to add some pointer and comments later this week.

**Comment by swinslow** [comment]
Will likely publish documentation of release process (or summary thereof) - @swinslow to sync with @goneall briefly

**Comment by swinslow** [comment]
Following up on a few pieces of this:
* for _documenting the release process_, this is being tracked in #1568 and I will add this documentation before 3.19 is pushed.
* for _deciding whether / what to recommend re: pre-release usage of new license IDs_, this is being tracked in #1600 and won't be picked up for 3.19.
* for _a "preview" version of the license list_ prior to a release being pushed, it looks like @goneall has made this available at https://spdx.github.io/license-list-data/ (thank you @goneall!) We should add documentation about this, and I'll add it in the PR to address #1568 (noted there).
* for the _GitHub notification bot_ that @seabass-labrax has put together at #1625, this is great! I like this a lot, though I would like to get the team's input on the specific language and the conditions that cause this to be triggered. I've added #1696 to track this because I think the language relates to what we'll want to discuss at #1600 for 3.20.
* finally, for the general questions about the release process -- e.g. "should the license list be released on a more or less frequent cadence," "should it be more automated," etc., these were discussed during the 3.19 release cycle Legal Team calls. General consensus was that more frequent releases could be a good thing, but they are entirely dependent on improving the automation so that tagging a release really can be closer to push-the-button. Given that, I don't believe there's anything currently to do for this other than "it would be nice to make that better some day."

I think this means that the various pieces of this issue are either done for 3.19, or split into separate issues for 3.20. So I'm going to close and mark this issue as complete.
