### ISSUE TITLE
Remove the copyright statement from FSFUL and FSFULLR

### ISSUE THREAD

**Issue by OliverFendt** [spdx/license-list-XML#1575]
The licenses FSFUL https://spdx.org/licenses/FSFUL.html contains in the text section the following copyright statement "Copyright (C) 1992-1996, 1998-2012 Free Software Foundation, Inc." this statement shall be removed from the text section. 

Reason: there are license scanner which import the SPDX license list. Although the copyright statement shall not be used by the scanners  it is part of the text and when the scanners print the text, this wrong copyright statement is printed too, as it belongs to he text of the license currently, which is not correct in my opinion.

The same applies for https://spdx.org/licenses/FSFULLR.html the license text contains "Copyright 1996-2006 Free Software Foundation, Inc." this shall be removedfrom the text section, too.

**Comment by jlovejoy** [comment]
@OliverFendt - when you say there are license scanners that import the SPDX License List, can you provide more info as to what and how? Specifically, what is being imported - is it license text from this repo or from https://github.com/spdx/license-list-data ?

Reason I ask is that use of the SPDX license data for template licenses (which I think is what you are getting at) has been a topic of discussion in terms of whether SPDX ought to provide guidance on this. It would be helpful to understand your example. 

Some licenses have a more "generic" copyright notice, such as " (c) YEAR Author" - but if this was reproduced, it would also be wrong for any individual copyright owner and need to be updated.

**Comment by OliverFendt** [comment]
@jlovejoy The import is done roughly as follows
The licenseIds are imported from https://spdx.org/licenses/licenses.json and the texts of the licenses are imported via the  "detailsUrl" given in the licenses.json file

Yes you are absolutly right with your statement:

> Some licenses have a more "generic" copyright notice, such as " (c) YEAR Author" - but if this was reproduced, it would also be wrong for any individual copyright owner and need to be updated.


like for example the BSD-3-Clause and others and this is causing unnecessary effort and errors when doing pacakage analysis. In my opinion such statements are not part of the licenses and thus shall be removed

**Comment by bsdimp** [comment]
One of the biggest items of feedback I've had in allowing 'SPDX-ONLY' files in FreeBSD is about the copyright being part of the license text and the potential for confusion around that. I thought I'd sent in a pull request some months back to address these concerns. While the markup / xml version of the license make it clear that they are separate, the normal text rendering does not. I can see how it would cause problems like @OliverFendt describes in other contexts.

**Comment by jlovejoy** [comment]
I think this is related to #1452 so maybe we can close this issue and continue the discussion there. @OliverFendt point about having a way to omit the copyright notice altogether is something to consider. It is not part of the license and often "captured' in other ways.
