### ISSUE TITLE
Public Domain Licence needed for IANA TZ/db/code/data/zoneinfo

### ISSUE THREAD

**Issue by BrianInglis** [spdx/license-list-XML#1577]
Repo Licence links:
[Dev](https://github.com/eggert/tz/blob/main/LICENSE)
[Code](https://data.iana.org/time-zones/code/LICENSE)
[Data](https://data.iana.org/time-zones/data/LICENSE)

[Home page](https://www.iana.org/time-zones)

Text:
> Unless specified below, all files in the tz code and data (including
this LICENSE file) are in the public domain.
> 
> If the files date.c, newstrftime.3, and strftime.c are present, they
contain material derived from BSD and use the BSD 3-clause license.

**Comment by jlovejoy** [comment]
Hi @BrianInglis - I presume this is a request to add a new "license" (or, in this case, a public domain dedication) to the SPDX License List?  While you don't have to use this online form, could you please provide the equivalent information? https://tools.spdx.org/app/submit_new_license/
Thanks!

**Comment by BrianInglis** [comment]
> Hi @BrianInglis - I presume this is a request to add a new "license" (or, in this case, a public domain dedication) to the SPDX License List? While you don't have to use this online form, could you please provide the equivalent information? https://tools.spdx.org/app/submit_new_license/ Thanks!

Asks me to give some third party @goneall access to my GH account - not going to happen.

**Comment by seabass-labrax** [comment]
Welcome @BrianInglis! Thank you for submitting this license request.

As for the form on the SPDX Online Tools site, it needs temporary access to your GitHub account in order to post a new issue on this repository on your behalf. @goneall is one of the official SPDX Team Leads, and is the system administrator for the SPDX Online Tools. That said, I would completely understand if you would prefer not to risk authorising the app in this case! You can just create a new issue or modify this one manually to include this information (example from a previous request):

> 1. License Name: Bitstream Charter Font License
> 2. Short identifier: Bitstream-Charter
> 3. License Author or steward: Bitstream Inc.
> 4. Comments: The license is used in at least one Fedora package and is an allowed font license in Fedora.
> 5. Standard License Header:
> 6. License Request Url: http://tools.spdx.org/app/license_requests/153
> 7. URL(s): https://fedoraproject.org/wiki/Licensing/Charter#License_Text, https://raw.githubusercontent.com/blackhole89/notekit/master/data/fonts/Charter%20license.txt
> 8. OSI Status: Not Submitted
> 9. Example Projects: https://github.com/blackhole89/notekit/tree/master/data/fonts

Also, as it happens, we're just having a wider discussion about public domain licenses in the SPDX License List. If you're interested, you can find our mailing list archives at <https://lists.spdx.org/g/Spdx-legal/message/3202> :smiley:

**Comment by jlovejoy** [comment]
thanks @seabass-labrax - I did state above, "While you don't have to use this online form, could you please provide the equivalent information?" sigh.

In any case, I may use this example in my collection of public domain examples over at Fedora :)

**Comment by BrianInglis** [comment]
License Name:		IANA TZ/db/code/data/zoneinfo Public Domain Licence
Short identifier:	IANA-TZ-PD
License Author/Steward:
*	Arthur David Olson author
*	Paul Eggert	primary IESG-designated TZ Coordinator
*	Tim Parenti	secondary IESG-designated TZ Coordinator

Comments:	This licence is intended to be the same as for other
			software developed by US Government employees and
			released into the Public Domain in the United States
			This package is used (or adapted) in every Linux distro,
			all BSDs, MacOS, iOS, Android, and Windows store apps.
Standard License Header:
```
This file is in the public domain.
```
```
This file is in the public domain, so clarified as of
2009-05-17 by Arthur David Olson.
```
```
Unless specified below, all files in the tz code and data (including
this LICENSE file) are in the public domain.

If the files date.c, newstrftime.3, and strftime.c are present, they
contain material derived from BSD and use the BSD 3-clause license.
```
License Request Url:	
URL(s):
*	Dev	https://github.com/eggert/tz/blob/main/LICENSE
*	Code	https://data.iana.org/time-zones/code/LICENSE
*	Data	https://data.iana.org/time-zones/data/LICENSE
*	Home page	https://www.iana.org/time-zones
* 
OSI Status:		N/A
Example Projects:	tzcode tzdata tzdb

**Comment by BrianInglis** [comment]
> thanks @seabass-labrax - I did state above, "While you don't have to use this online form, could you please provide the equivalent information?" sigh.

I saw that and did so! 
I did not feel that either myself or the IESG TZ Coordinators would commit to providing the XML and other stuff that SPDX requires. 
Many projects run on volunteers for whom the code (or as in this case also, data) is the focus: supporting tangential efforts like reproducible builds and SBOM info just does not interest them. 
It is perhaps down to funded downstreams to step up and do this work that mainly benefits commercial users. 
In the case of the TZ project, that is every software company in every country, as everyone uses the ref code and/or data.

**Comment by goneall** [comment]
@BrianInglis - Just saw the thread and wanted to acknowledge the tremendous contributions of the TZ project which I have used in some of my open source projects.  Completely understand your frustration on the requirements being a volunteer organization.  We (myself included) are also volunteers and not funded by any commercial interests.  Although I originally joined the SPDX groups with a commercial interest, I am now doing this work purely for community/volunteer interests.  Since we are volunteers, we don't have any funded source to fill in the gaps.

It looks like you provided the information requested - there is no requirement to use the online tool or to trust me.  Did you want to re-open this issue?  There may be other volunteers who will do the XML work to add this public domain declaration which I think would add value to the overall community.

**Comment by goneall** [comment]
Thanks @BrianInglis

**Comment by BrianInglis** [comment]
Please also include in your consideration of public domain licences the more general situation mentioned in the Comments: 
> This licence is intended to be the same as for other software developed by US Government employees and released into the Public Domain in the United States. 

The original TZ project was hosted at elsie.nci.nih.gov as the original author Arthur David Olson worked there (originally seismo!elsie!tz, ado <AT> elsie.UUCP). 

That consideration of public domain licences should also include that the concept is recognized only in certain jurisdictions, and may be limited in those, as by Crown Copyright in Commonwealth of Nations countries where common law is recognized; and where fees or royalties must be paid for all or sometimes only commercial public domain work reproduction to an artists or authors collective or state entity; and exclude those observing European civil law codes, where certain rights may not be waived, and must be explicitly licensed. For example, the TZ project will not use the official IERS leap-seconds file for *right*/TAI time zones as it is published in France (by Univ. Paris Observatory) by an international organization and not explicitly licensed, so they feel it could jeapardize their project licensing.

**Comment by jlovejoy** [comment]
These public domain statements from the TZ project are now captured in the Fedora data and under broader discussion on the mailing list https://lists.spdx.org/g/Spdx-legal/topic/98776908 to determine how to better handle these kinds of things generally. I'm going to leave this open, but mark it as a later release, as it will be impacted by the outcome of that bigger discussion.

**Comment by BrianInglis** [comment]
For now I am going with labels like `LicenseRef-IANA-TZ-Public-Domain` (for *Cygwin* project packages) as that provides source documentation, and suggesting that approach to others in the project, where licences have been e.g. emailed to the maintainer by the author. 
[As *Cygwin* is a *Sourceware* project, so provisioned with *RedHat* provided servers, goes along *Fedora* licensing and packaging guidelines, often based on *Fedora* `spec` files and patches to drop non-free bits, we started adding variables such as `LICENCE=...`, `UPSTREAM_EMAIL=...`, etc. as functional documentation in our build files rather than maintain separate docs, our build tool maintainer picked up and formalized it with *SPDX* checks and docs, and now we get warnings if missing when we upload packages and updates, errors if incorrectly specified, and he gets complaints  if his *SPDX* checker is not up to date with your licence data! *We are all damned now!* `;^>`]

**Comment by richardfontana** [comment]
Fedora is attempting to distinguish between public domain dedications (for which the LicenseRef-Fedora-Public-Domain identifier is used) and "true public domain" which is present in all software but is sort of significantly present in certain projects or packages, the tzdata package being a good example. Some parts of tzdata are covered by public domain dedications, other substantial parts are "true" public domain. We don't have an official identifier for "true public domain" currently, the working theory being that we should ignore it except in cases where an RPM is *entirely* "true public domain".

**Comment by BrianInglis** [comment]
What is *true* public domain? 
In those jurisdictions where it exists, it should apply only to a publication out of copyright, whose term is often 70 years, so that does not apply to any code newer than that written for the Ferranti Mark 1, LEO-1, or Univac-1, but may apply to algorithms, descriptions, or information from older publications. 
Documents or software can be assigned to the public domain in jurisdictions where that has any meaning. 
In the US, all government documents published are in the public domain, and that includes software and data.  

In *tz*, public domain notices were added to many files on 2009-05-17 stating:
> This file is in the public domain, so clarified as of 2009-05-17 by Arthur David Olson.

IERS issues Bulletin C to announce (in the first fortnight of January/July) *no* (or formerly *a*) leap second at the end of the half year, and the *tz* maintainers wait for NIST to remember and issue their own file because:
```
# This file is generated automatically from the data in the public-domain
# NIST format leap-seconds.list file, which can be copied from
# <ftp://ftp.nist.gov/pub/time/leap-seconds.list>
# or <ftp://ftp.boulder.nist.gov/pub/time/leap-seconds.list>.
# The NIST file is used instead of its IERS upstream counterpart
# <https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list>
# because under US law the NIST file is public domain
# whereas the IERS file's copyright and license status is unclear.
```
The *tz* project originated with ADO at NIH so code and data was US Govt PD. 
Information was contributed to the project, derived from government legislation documented in bills, acts, laws, decrees, orders, or regulations, normally copyrighted by the government printer, extracted and translated for publication on the mailing list as a basis for updating the time zones and rules, which may be uncopyrightable data in the US, and became US Govt PD when updated in the continent/ocean files. 
Historical information was also contributed, sometimes from publications such as by *Shanks & Pottenger*, research publications referring to or quoting government sources, and government information digitized and published online. 

For *tz* you could reach out to ADO and/or Paul Eggert as these issues have been discussed at length, and well understood by some, as *they* were [sued](https://www.eff.org/cases/astrolabe-v-olson) by *Astrolabe* regarding the quotation, reference, and use of *their* time zone history data purchased from *Starcrafts*/*Astro Communication (was Computing) Services*, compiled by *Shanks & Pottenger* published by *ACS Publications* in their [*American Atlas*](https://www.amazon.ca/American-Atlas-Longitudes-Latitudes-Changes/dp/0935127380/) (weight 1.5kg) and [*International Atlas*](https://www.amazon.ca/International-Atlas-Longitudes-Latitudes-Changes/dp/0935127887) (weight 1kg) of time zone history data used by astrologers world wide, causing a shut down of the mailing list and project for months.

**Comment by jlovejoy** [comment]
I"m going to close this for now, as it was left open due to the possible discussion around Fedora's approach to public domain dedications and whether SPDX might adopt something similar. I don't think that's in bandwidth at this time, though.
