### ISSUE TITLE
MIT-CMU/PIL - "prior" not included

### ISSUE THREAD

**Issue by capfei** [spdx/license-list-XML#1578]
I found the conversations about adding PIL, but the markup for MIT-CMU was updated instead based on similarities. However, "prior" was left out in `without specific, written prior permission`, which is in PIL (in the link used as an example). It was pointed out https://lists.spdx.org/g/Spdx-legal/message/2519 but not included. Is there a reason why? If not, can it be added as optional text so it will match?

**Comment by jlovejoy** [comment]
@capfei - we are talking about https://spdx.org/licenses/MIT-CMU.html right?

and adding "prior" as optional in the last sentence of the first paragraph?

**Comment by capfei** [comment]
@jlovejoy Yep, that's it! 👍 
<img width="869" alt="image" src="https://user-images.githubusercontent.com/5489711/184902939-9ecb1143-c246-4645-b917-aa0f9b69cafe.png">

Change `written permission.` to `written <optional>prior</optional> permission.`

I will submit the PR if I get the thumbs up.

**Comment by swinslow** [comment]
I'm open to other peoples' views on whether adding "prior" could be a legally substantive difference.

That said, I note that in [HPND](https://spdx.org/licenses/HPND.html) (which I believe we included as an OSI-approved license), that entire clause appears to be marked as optional. This suggests that the presence or absence of "prior" probably doesn't make much of a difference, or at least didn't appear to for purposes of HPND.

On that basis, I'd personally be okay with adding `prior` with `<optional>` tags, but again, open to others' views on this.

**Comment by seabass-labrax** [comment]
Given that you don't have 'specific, written permission' until you do, and once you do it's additional to the licence itself, my gut reaction is that this isn't substantively different. :slightly_smiling_face:

**Comment by jlovejoy** [comment]
in my own legal drafting, I have questioned what value "prior" gives in these kinds of clauses as it is, by practicality implied like @seabass-labrax pointed out.

+1 to add the optional tag

**Comment by capfei** [comment]
PR submitted: #1581
