### ISSUE TITLE
New license request: checkmk [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jamesjer** [spdx/license-list-XML#1579]
**1.** License Name: BSD Checkmk
**2.** Short identifier: BSD-Checkmk
**3.** License Author or steward: Unknown
**4.** Comments: This license does not match any currently on the list.  The license text has not changed in the last 12 years.  It appears to be a watered down variant of the BSD family.  It is generally usable.

This license is under review for Fedora: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/56
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/155
**7.** URL(s): https://github.com/libcheck/check/blob/master/checkmk/checkmk.in
**8.** OSI Status: Unknown
**9.** Example Projects: https://github.com/libcheck/check

**Comment by richardfontana** [comment]
I'd recommend calling it just "Checkmk" rather than "BSD-Checkmk".

**Comment by seabass-labrax** [comment]
Without having done a rigorous review yet, I'm optimistic that this would satisfy [the License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md). I would also agree that it should be called 'Checkmk' :smiley:

Might the license steward actually be the Micah Cowan mentioned in the copyright statement?

> Written by Micah Cowan <micah@cowan.name>
> Copyright (c) 2006, 2010  Micah Cowan

**Comment by richardfontana** [comment]
> Also, there's a parenthetical at the end, should that be included? And what's the exact text we should do for this request. There's no steward for this license or a canonical place to grab it.
 
On the Fedora side, I'm leaning toward the view that the parenthetical is necessary for our (likely) approval of the license, even though I read it as the license drafter's (or one known licensor-user's) statement of interpretation of the previous paragraph. The full text with the second paragraph:

```
# Redistribution of this program in any form, with or without
# modifications, is permitted, provided that the above copyright is
# retained in distributions of this program in source form.
#
# (This is a free, non-copyleft license compatible with pretty much any
# other free or proprietary license, including the GPL. It's essentially
# a scaled-down version of the "modified" BSD license.)
```

**Comment by richardfontana** [comment]
We are approving this for Fedora, with the parenthetical being treated as a required part of the license text.

**Comment by swinslow** [comment]
+1 to add, given FOSS nature of license terms and clear widespread use of this code in Fedora (plus apparently packaged for all sorts of other distros, according to its README).

+1 to not using "BSD" in the name or ID.

Personally I'd go with "checkmk", lowercase c, as the ID since that appears to be the styling used by the original author.

I'd lean towards adding this with the parenthetical included and initially non-optional. If this is the only instance of this license in the wild, then it doesn't really matter. If we later run across other folks using it in other projects without the parenthetical, then we could discuss at that point whether to mark the parenthetical text as optional (which would still match with Fedora's use here).

**Comment by jlovejoy** [comment]
+1 to add and agree with @swinslow assessment re: the parenthetical

**Comment by jlovejoy** [comment]
# License Inclusion Decision
## Decision:
* approved 
## Full name:
* Checkmk
## Short id:
* checkmk
## XML markup:
* none (for now)
## Additional rationale or notes on decision:
* none

**Comment by jlovejoy** [comment]
@jamesjer - would you be willing to prepare the PR for this license? We have some (detailed) instructions here: https://github.com/spdx/license-list-XML/blob/master/DOCS/new-license-workflow.md#accepted

Let us know. Thanks!

**Comment by swinslow** [comment]
@jlovejoy I edited your comment above to change the Full Name from "Checkmk" to "Checkmk License" -- I think that's the pattern we've generally used for other similar single-project license names.
