### ISSUE TITLE
Missing GPL-2.0 equivalent of GPL-3.0-linking-exception?

### ISSUE THREAD

**Issue by decathorpe** [spdx/license-list-XML#1585]
It seems like the GPL Linking Exception was only added for GPLv3 ([here](https://github.com/spdx/license-list-XML/pull/968)), but not for GPLv2.

For example, libgit2 is a project that uses GPL-2.0-only with a linking exception:
https://github.com/libgit2/libgit2/blob/main/COPYING

Would it make sense to add GPLv2 equivalents of the existing GPL-3.0-linking-exception identifiers?

**Comment by jlovejoy** [comment]
This is actually a match to GCC-exception-2.0  :)

See the markup here that accommodates a few wording variations: https://github.com/spdx/license-list-XML/blob/main/src/exceptions/GCC-exception-2.0.xml

So, you can use the license expression:

GPL-2.0-only WITH GCC-exception-2.0

**Comment by decathorpe** [comment]
Right, that seems to be it. The different naming scheme compared to the GPLv3 equivalent just threw me off. Thanks!
