### ISSUE TITLE
Extra line in Spencer-86 test file

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#1590]
An extra line present in the test file.  This will cause test failures once the LicenseListPublisher is updated with https://github.com/spdx/Spdx-Java-Library/pull/97

The extra line is:
```
Beware that some of this code is subtly aware of the way operator precedence is structured in regular expressions. Serious changes in regular-expression syntax might require a total rethink.
```

Either the line should be removed from the test file or the line should be added as optional to the end of the Spencer-86 license XML file.

**Comment by seabass-labrax** [comment]
I don't think this is supposed to be part of the license (it's not present in the Fedora licensing wiki page either). Shall I make a PR to remove this line from the XML?

**Comment by goneall** [comment]
> I don't think this is supposed to be part of the license (it's not present in the Fedora licensing wiki page either). Shall I make a PR to remove this line from the XML?

That matches my (non-legal) opinion and would solve the matching issue.
