### ISSUE TITLE
Extra line in SSPL-1.0 test file

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#1591]
An extra line present in the test file.  This will cause test failures once the LicenseListPublisher is updated with https://github.com/spdx/Spdx-Java-Library/pull/97

The extra line is:
```
                        END OF TERMS AND CONDITIONS
```

Either the line should be removed from the test file or the line should be added as optional to the end of the SSPL-1.0.xml license XML file.

**Comment by seabass-labrax** [comment]
I'll make a PR to add this as optional text.

**Comment by goneall** [comment]
Fixed with PR #1601
