### ISSUE TITLE
Add docs re: recommendation on using license IDs

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1600]
Placeholder issues to discuss:

Consider whether to add documentation recommending e.g. "SPDX encourages the use of identifiers in SPDX short-form identifiers after a PR has been merged, but prior to the quarterly release" -- if this is a position we want to take.

**Comment by swinslow** [comment]
Note that I've added [documentation on the release process](https://github.com/spdx/license-list-XML/blob/main/DOCS/release-process.md) for 3.19.

The "Overview" part at the top includes some generally neutral details on license IDs during the interim period between merging a PR and the next actual release, so this might be a good place to update if there is additional "guidance" for use of IDs during this interim.

**Comment by jlovejoy** [comment]
@swinslow 
I just realized I had added this to the bottom of https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md

> NOTE: Once a license has been accepted and to be added to the SPDX License List and the associated files merged, it is fine to start using the SPDX identifier, even if the official release has not yet occurred.

should I update that to be more consistent with what you said in the release doc?
or can we call this good/covered and close this issue?

**Comment by swinslow** [comment]
I guess I don't love "it is fine to start using the SPDX identifier" as the text... it really kind of depends on the user's use case and what they're wanting to convey. If they want to use it in an SPDX document, then it isn't going to be fine for that purpose.

Can we maybe replace that with a link to https://github.com/spdx/license-list-XML/blob/main/DOCS/release-process.md#overview, with text something like the following? "See the [license list release process documentation](https://github.com/spdx/license-list-XML/blob/main/DOCS/release-process.md) for more details about the timing of releases and use of new IDs prior to a release."

That way we at least aren't repeating ourselves and we're just saying it in one place...?

**Comment by jlovejoy** [comment]
@swinslow - see #1842

**Comment by swinslow** [comment]
Thanks -- merged!
