### ISSUE TITLE
Cornell Lossless JPEG Library License

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1605]
I found a license in a Fedora package that is pretty close to two SPDX license list licenses: MIT-Modern-Variant and PostgreSQL, such that perhaps it can be accommodated through altering the markup for one of those two licenses. Or maybe SPDX would consider it substantively different enough to warrant a new identifier. Here is the text:

```
Copyright (c) 1993 Cornell University, Kongji Huang
All rights reserved.
 
Permission to use, copy, modify, and distribute this software and its
documentation for any purpose, without fee, and without written
agreement is hereby granted, provided that the above copyright notice
and the following two paragraphs appear in all copies of this
software.

IN NO EVENT SHALL THE CORNELL UNIVERSITY BE LIABLE TO ANY PARTY FOR
DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF CORNELL 
UNIVERSITY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

THE CORNELL UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND CORNELL UNIVERSITY HAS 
NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, 
OR MODIFICATIONS.
```

**Comment by jlovejoy** [comment]
There appear to be two key differences here:
1) the name - which is already accommodated with markup.

2) and the order (ish) of the first sentence:
(Cornell version)
"Permission 
to use, copy, modify, and distribute this software and its documentation for any purpose, 
without fee, and without written agreement 
is hereby granted,"

v.
(MIT-Modern-Variant)
"Permission is hereby granted, 
without written agreement and without license or royalty fees, 
to use, copy, modify, and distribute this software and its documentation for any purpose,"

a) "hereby granted" is at the end v. beginning of the sentence - I can't see that that changes the meaning
b) can we consider "without fee, and without written agreement" as legally substantively the same as "without written agreement and without _license or royalty_ fees"?

@swinslow @pmadick - thoughts on this one?

**Comment by jlovejoy** [comment]
@richardfontana - what is the priority on this one (and is there a corresponding Fedora Gitlab issue)?

**Comment by richardfontana** [comment]
This is very low Fedora priority. There isn't even a Gitlab issue. It's a license that I discovered when trying to research some of the Callaway umbrella categories.

**Comment by richardfontana** [comment]
> can we consider "without fee, and without written agreement" as legally substantively the same as "without written agreement and without _license or royalty_ fees"? 

Obviously you can if you interpret "fee" in the first case as meaning "license or royalty fees". The "without fee" or similar language is a common element in this broad MIT/X-and-friends family of permissive FOSS licenses, and I would assume that a version with "license or royalty fees" was an attempt to clarify something that may have been thought to be unclear to one licensor. There are other FOSS licenses that have tried to explain the prohibitions on "fees" do not mean you can't "sell (copies of the) software". I seem to remember one license in this family that was problematic because the "without fee" was moved to a location in a sentence that made more plausible an interpretation that it was a prohibition on charging for distribution. Obviously such a prohibition is seen as conflicting with FOSS definitional norms, but those didn't exist before the development of most of these licenses. 

I would assume that SPDX can't say these licenses are substantively the same without engaging in some degree of legal interpretation (not sure if that goes against the "just the facts" principle).

**Comment by jlovejoy** [comment]
yeah, I feel like the variation make for very similar meaning in terms of general understanding, but is more specific as to the kind of fees in the one case, versus being open-ended as to just fees generally in the other.

**Comment by swinslow** [comment]
I tend to agree with @richardfontana and @jlovejoy that this warrants a new identifier.

It's actually (arguably) closer to [PostgreSQL](https://spdx.org/licenses/PostgreSQL.html) as @richardfontana mentioned, with the following differences:
1. title, copyright lines and references to Cornell vs. Univ. of California (all already accommodated via markup)
2. in paragraph 1: doesn't include "and this paragraph"
3. in paragraph 1: adds "of this software" at the very end
4. in paragraph 2: omits "INCLUDING LOST PROFITS" from the disclaimer
5. in paragraph 3: "OBLIGATIONS" is singular in the last sentence

Of these, I'd say that at least 2 and 4 would pass the extremely low bar that we usually use for saying "these could arguably be substantively different." (If I was thinking about these for my personal use, I'd consider them essentially identical, but that isn't the test we use here.)  :)

So I'd be +1 to add as a separate license, probably with notes briefly indicating that it is very close to PostgreSQL.

As far as name / ID -- ugh, naming things is hard. I'd probably not just want to go with "Cornell" without more details. @richardfontana Do you happen to be able to point us to the package where this one was found?

**Comment by richardfontana** [comment]
@swinslow  This tarball seems to contain the original lossless JPEG codec released under this license (with a couple of other licenses I had found in xmedcon including the old "short" IJG license):
https://web.archive.org/web/20221025081849/http://www.dclunie.com/ljpegcornell/ljpg.tar.Z

All other uses of this license I found seem to point back to that release, e.g.:
https://mipav.cit.nih.gov/license/CopyrightInfo.html#source-dicomcomm 
https://mipav.cit.nih.gov/documentation/api/gov/nih/mipav/model/file/FileDicomJPEG.html
https://android.googlesource.com/platform/external/dng_sdk/+/refs/heads/master/source/dng_lossless_jpeg.cpp#16 (code from some Adobe software; uses "Cornell" rather than "the Cornell")
https://www.mssl.ucl.ac.uk/~mcrw/src/20050920/proto.h
https://help.landscapepro.pics/v3-third-party-credits/
https://gitlab.freedesktop.org/libopenraw/libopenraw/blob/master/lib/ljpegdecompressor.cpp#L32

**Comment by swinslow** [comment]
@richardfontana So, interestingly, here's what I'm seeing as the corresponding license text in that .Z file linked in the prior comment:

```
Copyright (c) 1993 Cornell University, Kongji Huang
All rights reserved.

Permission to use, copy, modify, and distribute this software and its
documentation for research purposes, without fee, and without written
agreement is hereby granted, provided that the above copyright notice
and the following two paragraphs appear in all copies of this
software.

IN NO EVENT SHALL THE CORNELL UNIVERSITY BE LIABLE TO ANY PARTY FOR
DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING
OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE
UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
DAMAGE.

THE CORNELL UNIVERSITY SPECIFICALLY DISCLAIMS ANY WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE
PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND THE UNIVERSITY OF
CALIFORNIA HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES,
ENHANCEMENTS, OR MODIFICATIONS.
```

Which looks very close to the text for this thread, but there's two differences, one of which matters:
* in the first sentence, instead of permission being granted "for any purposes", it is granted "for research purposes"
* in the second and third paragraphs, someone got confused when replacing university names (sometimes it's Cornell, sometimes it's University of California)

The first one of course is the issue -- this appears to limit use to "research purposes".

For the subsequent links you provided, the first two include the "research purposes" limitation, the remaining four are the "any purposes" version.

I'm assuming that the version Fedora is using is the "any purposes" text that is provided at the top of this issue?

If so, I'm +1 to add it as a new license, perhaps with the following:
* ID: `Cornell-Lossless-JPEG`
* Name: Cornell Lossless JPEG License

and if someone comes along and wants the "research purposes" version later on, then we can figure out a separate ID and name for it. How does that sound?

**Comment by jlovejoy** [comment]
that sounds like a good approach, but I'd like to hear what @richardfontana  thinks

**Comment by richardfontana** [comment]
@swinslow ah, I overlooked that. The license in the Fedora package did not have the "research purposes" limitation.

**Comment by swinslow** [comment]
Thanks @jlovejoy and @richardfontana! Given this, I'm going to mark this one as approved and I'll submit a PR shortly.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Cornell Lossless JPEG License

## License ID

Cornell-Lossless-JPEG

## XML markup

None at present

## Notes:

This is the "any purposes" version; if "research purposes" version is needed, it can be submitted and reviewed separately.

## Additional rationale or notes on decision:

N/A
