### ISSUE TITLE
New license request: IJG-short [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1606]
**1.** License Name: Independent JPEG Group License (note: I made this up)
**2.** Short identifier: IJG
**3.** License Author or steward: Thomas G. Lane / Independent JPEG Group
**4.** Comments: The license occurs in at least one Fedora package, xmedcon.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/157
**7.** URL(s): https://sourceforge.net/p/xmedcon/code/ci/master/tree/libs/ljpg/
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://sourceforge.net/projects/xmedcon/

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by swinslow** [comment]
So there actually is already an `IJG` license on the license list, at https://spdx.org/licenses/IJG.html.

It contains a bunch of extraneous beginning and end matter, but the part in the middle appears to be identical to the one submitted here, other than containing this additional sentence after the 3 clauses:

> These conditions apply to any software derived from or based on the IJG code, not just to the unmodified library. If you use our work, you ought to acknowledge us.

I think even if the beginning and end matter were considered extraneous, that sentence is probably enough to say that this submission is different from the existing `IJG` license.

@richardfontana I don't suppose you (or the Fedora community) might have suggestions for a contact at Independent JPEG Group, who might be willing to weigh in on naming for this license / identifier?

**Comment by jlovejoy** [comment]
good catch, @swinslow - looking more closely https://spdx.org/licenses/IJG.html - the beginning part is already marked as optional.

We didn't mark everything after "We specifically permit and encourage the use of ..." as optional, but that information is really about other parts of the distribution that is under different licenses... so I'm wondering if that shouldn't be part of the IJG license anyway?

**Comment by richardfontana** [comment]
@swinslow I don't think there are any significant points of contact between Fedora and the Independent JPEG group. The license I've submitted here seems to be the (or one of the) earliest versions of the license -- the first version of the software was released in 1991 (I found that release a while ago when I meant to respond to your comment, but now I can't find it on this page: https://www.ijg.org/files/

Perhaps this one can be called IJG-1991 or IJG-Original or something like that, assuming SPDX IJG can't accommodate it.

**Comment by bsdimp** [comment]
+1 for inclusion. Agnostic on means (markup on existing IJG license, or as a new one with appropriate name).

**Comment by swinslow** [comment]
+1 to add.

I do think it warrants having a separate identifier from `IJG`, given the additional language noted above. I think that's substantively different enough that adding markup for `IJG` wouldn't be appropriate (given SPDX's low threshold for this).

I'm good with @richardfontana's proposal of `IJG-1991`. I'd probably not go with `IJG-Original` on the off chance that it turns out there's a more-original version that comes out of the woodwork  :)

**Comment by jlovejoy** [comment]
+1 to add but given 1991 is in the copyright notice of the IJG on the SPDX License List, maybe we should do a word, like `IJG-acknowledge` ?

Also, the full name needs to be different from the other one already on the list, but I suppose we could mirror the id with something like, "Independent JPEG Group License - acknowledge"

**Comment by swinslow** [comment]
Sorry, my comments above were unclear. The license being proposed in this issue does NOT have the "you ought to acknowledge us" language; that's the additional language in the [existing IJG license](https://spdx.org/licenses/IJG.html).

Good point on 1991 being in both. Maybe `IJG-short`?

Note to everyone reading this, if you're drafting a variation of an existing license, please version it  :)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## License full name

Independent JPEG Group License - short

## Short ID

IJG-short

## XML markup

none

## Additional rationale or notes on decision:

add note text explaining relationship to IJG license already on list
