### ISSUE TITLE
New license request: OFFIS [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1607]
**1.** License Name: OFFIS DCMTK License (I made this up)
**2.** Short identifier: OFFIS
**3.** License Author or steward: OFFIS
**4.** Comments: The license is a legacy permissive license that occurs in at least one Fedora package.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/158
**7.** URL(s): https://sourceforge.net/p/xmedcon/code/ci/master/tree/libs/dicom/
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://sourceforge.net/p/xmedcon/

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by swinslow** [comment]
Not doing a full writeup / analysis right now, but +1 to add based on clearly being FOSS terms, as a historical / one-project license.

Also just noting my amusement at the warranty disclaimer "FREEDOM FROM ANY COMPUTER DISEASES", don't think I've seen a license frame it that way before...

**Comment by jlovejoy** [comment]
+1 to add

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

OFFIS License

## Short ID

OFFIS

## XML markup

N/A

## Additional rationale or notes on decision:

N/A
