### ISSUE TITLE
New license request: Symlinks [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1608]
**1.** License Name: Symlinks License
**2.** Short identifier: Symlinks
**3.** License Author or steward: Mark Lord
**4.** Comments: The license appears in one Fedora package and is also in Debian and presumably other Linux distributions.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/159
**7.** URL(s): https://www.mail-archive.com/debian-bugs-rc@lists.debian.org/msg11494.html
**8.** OSI Status: Not Submitted
**9.** Example Projects: Not clear that this is maintained as a public project. See: https://packages.debian.org/sid/symlinks

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by jlovejoy** [comment]
see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/5#note_1079893279

**Comment by jlovejoy** [comment]
Given this is used in both Fedora and Debian (and thus meets their respective license requirements) and clearly meets the free/open definition - I would add.

As to the start/end of the text, I think the main part that @richardfontana captured in the SPDX submission tool seems right.

**Comment by bsdimp** [comment]
Seems like a standard 'do whatever' license, so +1 for inclusion. Reads a bit sloppy, but the intent seems clear. I'll leave it to others with legal degrees to raise any issues from that...

**Comment by swinslow** [comment]
+1 to add. As noted above, easily meets the "open source-ish" prong of the license inclusion principles, and inclusion in Debian and Fedora meets requirement of broad usage.

I note that the [Debian package's copyright file](https://metadata.ftp-master.debian.org/changelogs//main/s/symlinks/symlinks_1.4-4_copyright) also includes both paragraphs as @richardfontana indicated, so also +1 in including both in the license text.

From a quick search I don't see any other instances of this for other packages, so I'm inclined to add it verbatim without markup for other projects, etc.

This makes 3 +1's, so will mark as accepted unless any material objection in next few days.

**Comment by Pizza-Ria** [comment]
+1 to above commments.
