### ISSUE TITLE
New license request: UCAR [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1613]
**1.** License Name: UCAR License (note: name created by Tom Callaway)
**2.** Short identifier: UCAR
**3.** License Author or steward: University Corporation for Atmospheric Research (presumably)
**4.** Comments: This license is found in at least one Fedora package (udunits2).
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/163
**7.** URL(s): https://github.com/Unidata/UDUNITS-2/blob/master/COPYRIGHT
**8.** OSI Status: Unknown
**9.** Example Projects: https://github.com/Unidata/UDUNITS-2

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by Pizza-Ria** [comment]
I'll take this one to work on with some of my colleagues.

**Comment by swinslow** [comment]
Great, thank you @Pizza-Ria!

**Comment by Nick-Jazz** [comment]
@ richardfontana, I ran search on Github to find use of UCAR license but could not find any. Do you have any knowledge or comments about its usage?

**Comment by richardfontana** [comment]
@Nick-Jazz see: https://github.com/spdx/license-list-XML/issues/1613#issue-1353487521

**Comment by jlovejoy** [comment]
@richardfontana - this is one of the old Fedora licenses that was "allowed" but I don't see it stating allowed on the issue here: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/29 - can you confirm?

**Comment by richardfontana** [comment]
@jlovejoy, yes - this is one of the "good" licenses from the Callaway era that doesn't have an SPDX identifier (see: https://fedoraproject.org/wiki/Licensing/UCAR).

**Comment by swinslow** [comment]
+1 to add.

This one is a mish-mash of a few existing licenses. The preamble and clauses 1-3 are a near match for BSD-3-Clause, and the disclaimer is a near match for MIT. Clause 4 is a near match of the patent termination language from the Open Software License / Academic Free License family of licenses (e.g. [OSL-3.0 section 10](https://spdx.org/licenses/OSL-3.0.html)).

Given that, I think this mix of terms / conditions itself meets the "is open source-ish" part of the license inclusion principles. And I'd view its inclusion in a Fedora project as being sufficient for broad use.

I'm fine with UCAR as the name / identifier, I don't have anything better to propose.

**Comment by jlovejoy** [comment]
agreed @swinslow - +1 to add

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name
UCAR License

## Short ID
UCAR

## XML markup
I don't think any markup is needed at this point, given it's rather old. We can add markup later if need be.
