### ISSUE TITLE
New license request: TTWL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1614]
**1.** License Name: Text-Tabs+Wrap License (name created by Tom Callaway)
**2.** Short identifier: TTWL
**3.** License Author or steward: David Muir Sharnoff, presumably
**4.** Comments: This is a simple permissive FOSS license currently found in one Fedora package.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/164
**7.** URL(s): https://fedoraproject.org/wiki/Licensing/TTWL, https://github.com/ap/Text-Tabs/blob/master/lib.modern/Text/Tabs.pm#L148
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/ap/Text-Tabs

**Comment by richardfontana** [comment]
TTWL is the short name that Fedora used for this license under the pre-SPDX Callaway system.

**Comment by richardfontana** [comment]
Fedora priority: low.

**Comment by jlovejoy** [comment]
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/27

**Comment by jlovejoy** [comment]
# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [ ] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [ ] Yes
    - [ ] No
It seems to be another old one
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No
N/A
## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [ ] No
Two given examples have different names in them, but we can accommodate that with markup.
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [ ] Yes
    - [ ] No
Package using this license is included in Fedora
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No
N/A
## Summary of factors, outcome, comments

+1 to add

**Comment by jlovejoy** [comment]
I would go with the Fedora shortname here, since it's established and doesn't conflict with anything already on the SPDX License List

**Comment by bsdimp** [comment]
I'm +1 to add. I'm unsure if the "please don't" text should be included in the license. It isn't binding, but I'm not a lawyer, so at most I can ask the qualified legal folks here.

**Comment by jlovejoy** [comment]
@bsdimp - we don't edit the licenses - take them as they are :)

**Comment by bsdimp** [comment]
I wasn't sure where the license stopped since it says 'although not required by the preceding license', hence my (poorly worded) question.

**Comment by copernicat** [comment]
I agree with the analysis above. +1 to add

**Comment by jlovejoy** [comment]
@bsdimp - it is poorly worded...

**Comment by swinslow** [comment]
Already accepted, but also adding my +1 to include.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## License full name

Text-Tabs+Wrap License 

## Short ID

TTWL

## XML markup
none, appears to be project-specific. can add markup later, if found use of elsewhere

## Additional rationale or notes on decision:

not sure about + in full name, but I think that will be ok?

**Comment by swinslow** [comment]
@jlovejoy yup, `+` in the name (not the identifier) should be fine; a couple of existing licenses like [`MITNFA`](https://spdx.org/licenses/MITNFA.html) have one.
