### ISSUE TITLE
license inclusion guidelines updates

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1624]
Consider a couple minor changes:

- [x] add numbering to top section re: definitive factors (or lettering to differentiate from bottom section
- [ ] move "substantial use" factor to second factor (instead of third) since we generally treat that as a key factor

If we say that all OSI-approved are included on the SPDX License List, would we want to extend this to licenses that have been deemed to meet the Debian Free Software Guidelines, Fedora guidelines, or Linux kernel guidance? Even if not a definitive factor, would we want to allow for a lighter-weight review of such licenses to make it faster/easier to get to acceptance?

**Comment by swinslow** [comment]
Regarding Debian / Fedora, I shared a few thoughts [here](https://lists.spdx.org/g/Spdx-legal/message/3247) on the mailing list in response to @jlovejoy's message there.

And to @Pizza-Ria's point -- yes, I also ought to re-read the guidelines they use before I just opine that they're in alignment!

For moving substantial use to second factor, I'm open to that but I think it makes sense to discuss. I think you're probably right that that better reflects our actual practice.

**Comment by seabass-labrax** [comment]
As for the numbering, +1 from me. Lettering isn't inherently supported by Markdown, so although I too would prefer letting, I'd rather compromise to have clean Markdown conversion :)

**Comment by swinslow** [comment]
@jlovejoy to submit PR for adding numbering - non-substantive

for other changes, @jlovejoy will put together change proposal for future discussion / consideration; removing "discuss" tag for the time being

**Comment by jlovejoy** [comment]
#1647  addresses this issue

**Comment by jlovejoy** [comment]
I'm closing this, as more substantive changes to the License Inclusion Guidelines (re-ordering factors or other suggestions as discussed on mailing list) need to go through Change Proposal process
