### ISSUE TITLE
Add markup to BSD-4-Clause

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1627]
add markup in 4th clause same as in 3rd clause in BSD-3-Clause to accommodated "neither the names" or "the name" variation. See first two entries here https://github.com/freedesktop/libbsd/blob/master/COPYING for example

**Comment by swinslow** [comment]
Looks good to me and I see @bsdimp agreed in the PR thread in #1630 as well, thanks @jlovejoy!
