### ISSUE TITLE
BSD-3-Clause variant that lacks initial passive-voice-agent mention of author in disclaimer paragraph

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1631]
I found this license:

```
* Copyright © 2012 Guillem Jover <guillem@hadrons.org>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL
 * THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Am I correct that this does not match BSD-3-Clause because there is nothing between the "PROVIDED" and the "AS IS"?

**Comment by jlovejoy** [comment]
ah, so it's missing the "provided _by copyright holders/name_ 'as is'"

My inclination is that this is not a substantive difference as "the author" is used later in the paragraph and omitting that in the first line doesn't really change the meaning. If others agree, then I'd defer to the markup experts as to how to accommodate a can be x, y or nothing option.

**Comment by richardfontana** [comment]
FWIW I agree that it should not be treated as a substantive difference (for SPDX identifier purposes).

**Comment by jlovejoy** [comment]
marking this for next release as I'm not sure how to do markup for this, so need someone more expert!

@zvr can you help here??

**Comment by jlovejoy** [comment]
needed for Fedora see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/72

**Comment by bsdimp** [comment]
I think the plain meaning (as read by an educated layman) isn't any different. I mean who else could be providing it AS IS if it isn't the person/author/rightsholder that's granting the license.

**Comment by swinslow** [comment]
+1 to handling this via markup in BSD-3-Clause rather than adding a new separate identifier.

As far as how to do that, here's the current bit of markup from [BSD-3-Clause.xml](https://github.com/spdx/license-list-XML/blob/b0ef20deda196ed294d15332deef26ceaa12f336/src/BSD-3-Clause.xml#L37-L38):

```
<p>THIS SOFTWARE IS PROVIDED BY <alt match=".+" name="copyrightHolderAsIs">THE COPYRIGHT HOLDERS AND
         CONTRIBUTORS</alt> "AS IS"  . . .
```

I think this could be handled by doing both of the following:
1. shifting the word "BY" into the `<alt>` tag section, so that it is part of the matched language; and
2. changing the regular expression from `.+` (meaning 1 or more characters) to `.*` (meaning 0 or more characters).

Any objections? If not, I can submit that change.

**Comment by jlovejoy** [comment]
Thanks @swinslow - makes sense to me!
