### ISSUE TITLE
New license request: HPND-Markus-Kuhn [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1636]
**1.** License Name: Markus Kuhn License (I made this up)
**2.** Short identifier: Markus-Kuhn
**3.** License Author or steward: Unknown
**4.** Comments: This minimalist permissive license covers multiple source files published by Markus Kuhn which have been used in a number of FOSS projects packaged in Linux distributions. (It is possible the license has been used by other authors and it is not clear that Markus Kuhn originated it.)
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/168
**7.** URL(s): https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=readline/readline/support/wcwidth.c;h=0f5ec995796f4813abbcf4972aec0378ab74722a;hb=HEAD#l55

**Comment by richardfontana** [comment]
```
 * Permission to use, copy, modify, and distribute this software
 * for any purpose and without fee is hereby granted. The author
 * disclaims all warranties with regard to this software.
 ```

**Comment by richardfontana** [comment]
It occurs to me that SPDX might wish to avoid using someone's name in the name of an identifier, although there is the example of the Henry Spencer licenses.

**Comment by jlovejoy** [comment]
is this allowed for Fedora?
Is this urgent or not?
@richardfontana

**Comment by richardfontana** [comment]
This is in Fedora (and is possibly assumed in an undocumented way to have been encompassed by Callaway "MIT") but has not been submitted for Fedora for inclusion in the fedora-license-data repository. I believe it is in the Red Hat internal list of approved licenses which we ultimately want to incorporate into the Fedora data. This is not urgent.

**Comment by swinslow** [comment]
+1 to add, this is a minimal permissive license and meets the FOSS-like prong of the inclusion principles, and per @richardfontana's comment is included in a variety of Linux distros. 

I note that this is essentially an extremely minimal version of [`HPND`](https://spdx.org/licenses/HPND.html). You could get to this one basically by deleting a bunch of words from HPND. Maybe `HPND-minimalist` or something like that?

**Comment by richardfontana** [comment]
@swinslow one concern about "HPND-minimalist" - my guess is that there are a large number of HPND variants out there, minimalist or otherwise, waiting to be discovered. And as far as I could tell from a search, this particular one has *only* been used by Markus Kuhn.

**Comment by swinslow** [comment]
@richardfontana fair point! `HPND-Markus-Kuhn` then, I'd suggest. And perhaps "Historical Permission Notice and Disclaimer - Markus Kuhn variant" for title.

**Comment by Pizza-Ria** [comment]
+1 to the previous post on the title and inclusion for all reasons stated above.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

Historical Permission Notice and Disclaimer - Markus Kuhn variant

## Short ID

HPND-Markus-Kuhn

## XML markup

None at present

## Additional rationale or notes on decision:

N/A
