### ISSUE TITLE
BSD-3-Clause variant with clause 3 only covering "its contributors"

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1643]
I [found](https://github.com/carltongibson/django-filter/blob/main/LICENSE) this license:
```
Copyright (c) Alex Gaynor and individual contributors.
All rights reserved.

Redistribution and use in source and binary forms, with or without 
modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this 
   list of conditions and the following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimer in the documentation 
   and/or other materials provided with the distribution.
 * The names of its contributors may not be used to endorse or promote products 
   derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR 
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON 
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

I don't think this matches to BSD-3-Clause. At a minimum I believe the BSD-3-Clause markup would need to be changed to accommodate "names" (vs. "name"), right? I am also not sure if SPDX-legal would consider this substantively different from BSD-3-Clause depending on the interpretation of "its contributors" (which might mean something different from case to case, or license notice to license notice).

This seems to be a fairly common variant on BSD-3-Clause. I found it in django-filter, a PyPI package which is packaged in Fedora as well as some Red Hat products.

**Comment by swinslow** [comment]
In line with @jlovejoy's and my comments on #1644, I think this could be accommodated with the following edit to [the existing XML](https://github.com/spdx/license-list-XML/blob/50f2139df761669d6244825699a08446a547d56b/src/BSD-3-Clause.xml#L31):

`<alt match="(The name of.+may not)|(Neither the name of.+nor the names of its contributors may)|(The names of its contributors may not)" name="organizationClause3">` 

(this would of course need to be submitted in a PR which doesn't conflict with the proposed edit in #1644)

@richardfontana To your point about "substantively different", I think we've generally if informally taken the position that a license can match regardless of the specific individuals whose names you _may not_ use. As an example, if you look at the alt-match regular expressions [a bit further down in BSD-3-Clause](https://github.com/spdx/license-list-XML/blob/50f2139df761669d6244825699a08446a547d56b/src/BSD-3-Clause.xml#L40-L41), any text will match within the part marked as "THE COPYRIGHT OWNER OR CONTRIBUTORS":

`IN NO EVENT SHALL <alt match=".+" name="copyrightHolderLiability">THE COPYRIGHT HOLDER OR CONTRIBUTORS</alt> BE LIABLE FOR . . . `

So personally I'm comfortable adding the edit above and still calling this BSD-3-Clause.

If that looks good to you and if we can get another +1, then I can go ahead and include this in a PR, together with the change for #1644.

**Comment by richardfontana** [comment]
Looks good to me.

**Comment by swinslow** [comment]
@jlovejoy @bsdimp Can either of you give a +1 for this? If so, I'll submit a PR together with the change in #1644 so that they don't conflict.

**Comment by swinslow** [comment]
note to self -- also pick up #1631 since that's also a markup change for BSD-3-Clause.

**Comment by bsdimp** [comment]
Yea, how people changed the original
```
 4. Neither the name of the University nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.
```
and the
```
THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
```
to make it less specific to the University of California is one area that's created a number of variants. Since so many different people have done this, even inside the BSD world let alone in greater open source, I suspect this won't be our last tweak here.

So I'm +1 on this. I think these changes are not legally significant enough to bother with a different license: You generally need permission of the person whose name it is you are using for anything that looks like an endorsement, so from my laymen's perspective its just a clause that reiterates this point of law, and the details of which would need to change a lot more before it's even close to a different license... but I think like an engineer and IANAL.
