### ISSUE TITLE
Bad link in request-new-license.md

### ISSUE THREAD

**Issue by daniel-parasoft** [spdx/license-list-XML#1648]
The link for "Review the license inclusion principles" item is broken.

Url points to 
https://github.com/spdx/license-list-XML/blob/main/DOCS/DOCS/license-inclusion-principles.md, note the extra DOCS section on the URL.

**Comment by jlovejoy** [comment]
Thanks @daniel-parasoft ! Where did you notice this? (feel free to submit a PR :)

**Comment by daniel-parasoft** [comment]
> Thanks @daniel-parasoft ! Where did you notice this? (feel free to submit a PR :)

Sorry, I should have given the context. It was from this page: https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md

Where do I submit this as PR?

**Comment by daniel-parasoft** [comment]
I will issue a Pull Request for this.  For me PR means "Problem Report", hence my confusion in my last comment. :)

**Comment by jlovejoy** [comment]
> I will issue a Pull Request for this. For me PR means "Problem Report", hence my confusion in my last comment. :)

Thanks! "Problem Report" - well, that's not too far off :) 
sorry, I guess I assume everyone commenting here knows at least as much as I do about using Github... but good reminder to reduce the use of abbreviations.
