### ISSUE TITLE
New license request: Kazlib [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1650]
**1.** License Name: Kazlib License (I made this up)
**2.** Short identifier: Kazlib
**3.** License Author or steward: Kaz Kylheku
**4.** Comments: This is a simple permissive FOSS legacy license that was formerly used by Kaz Kylheku for a number of source files that came to be widely reused in FOSS projects (see https://www.kylheku.com/~kaz/kazlib.html), including some packages in Fedora and other Linux distributions.
**5.** Standard License Header: None
**6.** License Request Url: http://tools.spdx.org/app/license_requests/170
**7.** URL(s): http://git.savannah.gnu.org/cgit/kazlib.git/tree/except.c?id=0062df360c2d17d57f6af19b0e444c51feb99036
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://github.com/hercules-team/augeas, https://github.com/wireshark/wireshark

**Comment by richardfontana** [comment]
```
 * Copyright (C) 1999 Kaz Kylheku <kaz@ashi.footprints.net>
 *
 * Free Software License:
 *
 * All rights are reserved by the author, with the following exceptions:
 * Permission is granted to freely reproduce and distribute this software,
 * possibly in exchange for a fee, provided that this copyright notice appears
 * intact. Permission is also granted to adapt this software to produce
 * derivative works, as long as the modified versions carry this copyright
 * notice and additional notices stating that the work has been modified.
 * This source code may be translated into executable form and incorporated
 * into proprietary software; there is no requirement for such software to
 * contain a copyright notice related to this source.
 ```

**Comment by richardfontana** [comment]
Fedora priority: low

**Comment by swinslow** [comment]
+1 to add, this is a custom license but appears to grant the necessary FOSS-like permissions. Substantial use based on inclusion in Fedora and other distros.

I'm fine with Kazlib as the identifier and Kazlib License as the name.

**Comment by jlovejoy** [comment]
+1 to add (discussed on Jan 26th call)

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

Kazlib License

## Short ID

Kazlib

## XML markup

N/A

## Additional rationale or notes on decision:

N/A
