### ISSUE TITLE
New license (or exception) request: Adobe FreeType Patent License Grant

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1651]
License text:
```
 * Copyright 2007-2013 Adobe Systems Incorporated.
 *
 * This software, and all works of authorship, whether in source or
 * object code form as indicated by the copyright notice(s) included
 * herein (collectively, the "Work") is made available, and may only be
 * used, modified, and distributed under the FreeType Project License,
 * LICENSE.TXT.  Additionally, subject to the terms and conditions of the
 * FreeType Project License, each contributor to the Work hereby grants
 * to any individual or legal entity exercising permissions granted by
 * the FreeType Project License and this section (hereafter, "You" or
 * "Your") a perpetual, worldwide, non-exclusive, no-charge,
 * royalty-free, irrevocable (except as stated in this section) patent
 * license to make, have made, use, offer to sell, sell, import, and
 * otherwise transfer the Work, where such license applies only to those
 * patent claims licensable by such contributor that are necessarily
 * infringed by their contribution(s) alone or by combination of their
 * contribution(s) with the Work to which such contribution(s) was
 * submitted.  If You institute patent litigation against any entity
 * (including a cross-claim or counterclaim in a lawsuit) alleging that
 * the Work or a contribution incorporated within the Work constitutes
 * direct or contributory patent infringement, then any patent licenses
 * granted to You under this License for that Work shall terminate as of
 * the date such litigation is filed.
 *
 * By using, modifying, or distributing the Work you indicate that you
 * have read and understood the terms and conditions of the
 * FreeType Project License as well as those provided in this section,
 * and you accept them fully.
 ```

**Comment by richardfontana** [comment]
Proposed short name: Adobe-FreeType-Patent

URL: See e.g. https://github.com/freetype/freetype/blob/master/src/psaux/psarrst.c

This license text appears on several source files in FreeType, which is packaged in Linux distributions like Fedora and widely used in commercial products. I assume Adobe provided this text in certain contributions it made to FreeType. It in a sense incorporates the FreeType license (SPDX: FTL) by reference and adds a patent license grant similar to Apache-2.0 section 3. 

I am aware of the [past issue](https://github.com/spdx/license-list-XML/issues/646) involving a variety of Google open source project patent license grant where SPDX-legal did not resolve whether language of this sort (an ancillary patent license grant supplementing the terms of a FOSS project license) would be appropriate for inclusion in the SPDX license list, and whether it is what SPDX considers an "exception". I note also that SPDX has left open an [issue ](https://github.com/spdx/spdx-spec/issues/153)from several years ago proposing that an equivalent to LicenseRef- be adopted specifically for exception-like constructs. I believe that SPDX should now address the unresolved questions raised in these issues. While Fedora could use something like LicenseRef-FTL-WITH-Adobe-FreeType-Patent to represent these terms, Fedora's policy is to request SPDX identifiers for all approved license language, and using a 'WITH' expression referencing a standard SPDX identifier inside a 'LicenseRef-' seems particularly undesirable.

Fedora priority: low.

**Comment by swinslow** [comment]
+1 to @richardfontana's comment [above](https://github.com/spdx/license-list-XML/issues/1651#issuecomment-1264383502), noting the similarity of this to the prior "and here's a patent license" texts.

I think this is worth discussing and reaching some sort of conclusion on, whether it's to consider modifying how exceptions work generally, or else to determine how we'll handle these sort of modifiers when they are tagged onto another license.

I'll mark this as needing discussion on an upcoming legal team call, though not sure whether this will be covered in the time remaining for 3.20.

**Comment by Pizza-Ria** [comment]
I do not think that this proposal aligns with #3 of the [License Exception rubric](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md#license-exceptions).

**Comment by jlovejoy** [comment]
discussed (again) on 6/22 call: looking more closely at this in light of our now articulated exception guidelines, we all agreed this doesn't not really meet those. Specifically it doesn't fit squarely in either of the two aspects of (2) and contains a restriction or limitation beyond those granted in the underlying license. It was also noted that these kinds of patent licenses seemed to have a period of popularity, but that has waned (in relation to substantial use).

**Comment by jlovejoy** [comment]
it was also acknowledged that the addition of the option to use `AdditionRef-` in license expressions provides a more concise way to potentially capture this kind of thing.
