### ISSUE TITLE
Presumed OSI website typo replicated in NTP

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1653]
The XML for NTP has
```
        <alt match=".+" name="TMname">(TrademarkedName)</alt> makes no representations about the suitability
        this software for any purpose. It is provided "as is" without express or implied warranty.
```
This copies the version on opensource.org (https://opensource.org/licenses/NTP) but at least some real-world uses of this license type have "suitability of this software" instead of the (ungrammatical/unidiomatic) "suitability this software". 

Example: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=readline/readline/support/install.sh;h=0cac004e6dce38456fc54e6e7dac614caa662e12;hb=HEAD

Common sense, and the now well-established history of faulty OSI website replications of certain license texts, and the fact that this is a legacy license type predating the founding of the OSI, all suggest that the "suitability this software" version is erroneous (however I did not attempt to search for any real-world use of that version on software).

**Comment by swinslow** [comment]
I'd suggest we edit to add "of" as an `<optional>` text section. That way, it will continue to match for both the grammatical version and the OSI website version.
