### ISSUE TITLE
New license request: CMU-Mach [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1654]
**1.** License Name: CMU Mach License (I made this up)
**2.** Short identifier: CMU-Mach
**3.** License Author or steward: Unknown, possibly Carnegie Mellon
**4.** Comments: This is a legacy permissive FOSS license which appears in source code of various packages in Fedora and other Linux distributions. It appears to be historically associated with CMU's Mach operating system project.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/172
**7.**  https://web.archive.org/web/20221118085208/https://www.cs.cmu.edu/~410/licenses.html
**8.** OSI Status: Unknown
**9.** Example Projects: https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gas/config/tc-alpha.c;h=c305acc25947061325563c603f47ebe2cac559b8;hb=HEAD#l30

Note: the link I gave in 7 now redirects so replacing that with a wayback link.

**Comment by richardfontana** [comment]
Fedora priority: Low.

**Comment by swinslow** [comment]
+1 to add. This is a simple, permissive FOSS license, with substantial use given the inclusion in Fedora. It does not match the existing [`MIT-CMU`](https://spdx.org/licenses/MIT-CMU.html) license.

Purely as FYI, I don't see the statement "Carnegie Mellon requests users of this software to return to . . . any improvements or extensions that they make" to conflict with FOSS concepts (e.g., Debian's desert island test). It's phrased as a request, not a requirement, similar to "you can buy me a beer" in [`Beerware`](https://spdx.org/licenses/Beerware.html).

**Comment by Pizza-Ria** [comment]
+1 to @swinslow - The only extra comment I'll make is that leaving out the Carnegie (c) statement ("Copyright (c) 1991,1990,1989 Carnegie Mellon University All Rights Reserved."), I got a 32% match on MIT-Open-Group.  I just wonder if we could have a more intuitive title (like CMU-MIT-Variant license) since the submission says the license name is made up anyway.  Given the # of random "extra" licenses that we're approving due to their general ubiquity in programming languages/popular distros/kernel, we are slightly undercutting the value of "controlling" the number of vanity licenses out there (although it is arguable that this isn't a vanity license if it only has a 32% match).  I'm not super-particular on this point so happy to go along with the rest of the group here but just wanted to raise if for consideration (And yes, I do recall that we aren't making legal determinations on the scope of these licenses so I may be leaning too far over the line with this general topic of discussion).

**Comment by richardfontana** [comment]
License text for convenience:

```
Copyright (c) 1991,1990,1989 Carnegie Mellon University
All Rights Reserved.

Permission to use, copy, modify and distribute this software and its
documentation is hereby granted, provided that both the copyright
notice and this permission notice appear in all copies of the
software, derivative works or modified versions, and any portions
thereof, and that both notices appear in supporting documentation.

CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS "AS IS"
CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.

Carnegie Mellon requests users of this software to return to

 Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
 School of Computer Science
 Carnegie Mellon University
 Pittsburgh PA 15213-3890

any improvements or extensions that they make and grant Carnegie Mellon
the rights to redistribute these changes.
```

Not sure if the 'request' statement at the end should be in the SPDX license text if SPDX accepts this.

**Comment by richardfontana** [comment]
>  Given the # of random "extra" licenses that we're approving due to their general ubiquity in programming languages/popular distros/kernel, we are slightly undercutting the value of "controlling" the number of vanity licenses out there (although it is arguable that this isn't a vanity license if it only has a 32% match). I'm not super-particular on this point so happy to go along with the rest of the group here but just wanted to raise if for consideration (And yes, I do recall that we aren't making legal determinations on the scope of these licenses so I may be leaning too far over the line with this general topic of discussion).

@Pizza-Ria I think it is sort of anachronistic to call this a vanity license. This comes from an era in which FOSS licensing was in its infancy and it was sort of understood that each little license would be somewhat different - there was no particular value seen in license text standardization or uniformity.  The concern about vanity licenses emerged after the early 2000s, after "open source" became a sort of distinctive brand, when many companies created their own corporate open source licenses which were usually minor variants on MPL-1.1. derivatives and somewhat confusingly-reasoned concerns were raised about how this, or OSI-approval of such licenses, might slow down commercial adoption of open source. (That turned out to be unfounded with respect to those corporate vanity licenses because if they ever covered any noteworthy software at all, such software soon became obsolete.)

I suppose I do see SPDX as playing some role in reducing the impact of vanity licensing to the extent that vanity licenses are not substantively different from some earlier model (which was usually MPL-1.1) . However often the vanity license would be substantively different by SPDX's standards. In general though I don't think it's SPDX's mission to reduce vanity licensing or minimize license proliferation.

**Comment by Pizza-Ria** [comment]
@richardfontana Fair enough - I couldn't think of a better term than "vanity" in my previous post but I guess "historical variant" makes more sense here.  I was trying to find a backdoor into creating a more informative short identifier but I'm not sure one exists within the ambit of the SPDX mission. So, I'll concede to adding this as proposed (+1).

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

CMU Mach License

## Short ID

CMU-Mach

## XML markup

None at present

## Additional rationale or notes on decision:

N/A

**Comment by jlovejoy** [comment]
we didn't address the comment above by @richardfontana re: the "CM requests..." part not needing to be part of the license. I am including it, but marking it as optional in the files to be safe
