### ISSUE TITLE
New license request: Knuth-CTAN [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1657]
**1.** License Name: Knuth CTAN License
**2.** Short identifier: Knuth-CTAN
**3.** License Author or steward: Unknown (probably not Donald E. Knuth)
**4.** Comments: This is a license that purportedly (at least as presented by the maintainers of CTAN and/or the TeXLive distribution) covers the Computer Modern TeX fonts which are distributed as part of the TeXLive distribution and redistributed in various Linux distributions.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/175
**7.** URL(s): https://ctan.org/license/knuth
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://ctan.org/tex-archive/fonts/cm

**Comment by richardfontana** [comment]
Fedora priority: **high**.

The precise licensing terms applicable to the Computer Modern fonts is a rather confusing issue. I think this license, which CTAN calls "Knuth", is an attempt (possibly with Knuth's blessing) by someone other than Knuth to reformulate a couple of past informal statements of his into a simple license text. I would suggest calling it "Knuth-CTAN" because there are at least three other statements by Knuth about licensing of TeX-related works that SPDX might wish to add to its license list someday.

**Comment by seabass-labrax** [comment]
Thank you, @richardfontana! Very enthusiastic +1 from me regarding the 'substantial use' factor of our [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md). The Computer Modern fonts are iconic by virtue of being the default typeface in TeX distributions, so I would be personally happy to see this license being included. I'll leave the thorough review to someone else though, as I'm clearly biased on this one ;)

**Comment by jlovejoy** [comment]
Interestingly, this is very, very similar in substance to https://spdx.org/licenses/Wsuipa.html (which was another Fedora license added some time ago)!

hmmm....

I'm not sure it's worth trying to markup, though. It's different enough in the wording that it'd be hard to accommodate and at that point, it seems worthy of being it's own license

In any case, +1 to add.

@richardfontana - was there a specific reason you added "CTAN" to the name? As it's simply "Knuth License" here https://ctan.org/license/knuth

**Comment by richardfontana** [comment]
@jlovejoy The issue is that there are multiple texts (some of them related in the sense that they may be efforts to explain the permission terms for the same thing, such as the Computer Modern fonts) that purport to be "a Knuth license" that I've encountered. For example, the old Fedora license wiki page had an entry for "Knuth" with a link to a different document from the CTAN document, essentially a newsletter article that informally describes some licensing terms (I think you looked at this in some of your earlier work on analyzing the Fedora license lists). That just shows that the situation is confusing and some attempt to disambiguate "Knuth" might be helpful.

**Comment by bsdimp** [comment]
There's certainly precedence with the MIT, CMU and BSD licenses: there's lots of versions and variations, most of which didn't originate at these institutions... And they vary enough we have separate license identifiers for each of at least the major variants.

**Comment by swinslow** [comment]
@jlovejoy Good point about the similarity to Wsuipa! That said, I'm inclined to add this as a separate identifier rather than try to merge it into Wsuipa.

That's partly because it would be a lot of individual tweaks to various words in order to get it to match to both; and partly because this submission speaks to both "packages" and "files" while Wsuipa only talks about files. Personally I doubt there's any meaningful difference, but for SPDX purposes I'd view them as passing the very low threshold of "could arguably be substantively different."

Given that, and @richardfontana's details on the background here, I'm +1 to add this as a separate license with identifier `Knuth-CTAN`.

@jlovejoy are you good with that? If so then I think we can mark this as approved given the +1's in this thread.

**Comment by jlovejoy** [comment]
PR #1701
