### ISSUE TITLE
New license request: Clips [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by daniel-parasoft** [spdx/license-list-XML#1658]
**1.** License Name: Clips
**2.** Short identifier: Clips
**3.** License Author or steward: Unknown
**4.** Comments: Clips is public domain software originally developed at NASA.  It is a rules engine used for creating expert systems. https://www.clipsrules.net/

We have approval from the project owner to add the Clips license to the SPDX license list: https://groups.google.com/g/clipsesg/c/-S0gR8mNEX8

Note that their is no direct link to the license text, however, it is on page 16 of the Reference Manual linked as the source / URL.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/176
**7.** URL(s): https://www.clipsrules.net/documentation/v640/bpg640.pdf
**8.** OSI Status: Unknown
**9.** Example Projects: https://www.ea.com/games/command-and-conquer/command-and-conquer-remastered, https://github.com/DrItanium/maya

**Comment by richardfontana** [comment]
There is a [clips package](https://packages.fedoraproject.org/pkgs/clips/clips/index.html) in current Fedora (which seems to be based on a sourceforge repository associated with clipsrules.net upstream) that has a couple of source files with this license. It seems to be like MIT-0 but without the 'sublicense' verb.

**Comment by jlovejoy** [comment]
Thanks for the submission @daniel-parasoft and the extra info, @richardfontana !

**Comment by jlovejoy** [comment]
Interesting it omits the reference to documentation and then adds this at the end:
"The online availability of this document, the CLIPS Reference Manual: Basic Programming Guide, implies permanent permission for anyone to read, to download, and to print out single copies for his/her own use. All other uses of this document are conditional upon the consent of the copyright owner."

**Comment by swinslow** [comment]
@jlovejoy yes -- I'm not sure I follow which part is the "Clips license". Is it just the part used for the Clips software, e.g. everything up to and including the all-caps text? Or is it the full license, including the documentation bit at the end?

I'm assuming Fedora is distributing just the software, and not this reference manual (since the last sentence appears to only permit the reference manual to be downloaded for personal use, not for redistribution).

So, would what gets added to the SPDX License List be just the software part of the license? If so, I'd be +1 to add that part, though I do want to stare at it some more and make sure it doesn't match to an existing MIT-like identifier already on the list.

**Comment by richardfontana** [comment]
This is the license text I see in two source files in the Fedora package:

```
Permission is hereby granted, free of charge, to any person obtaining    
a copy of this software and associated documentation files (the          
"Software"), to deal in the Software without restriction, including      
without limitation the rights to use, copy, modify, merge, publish,      
distribute, and/or sell copies of the Software, and to permit persons    
to whom the Software is furnished to do so.                             
                                                                         
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF              
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT   
OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY  
CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES  
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN    
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF  
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. 
```

**Comment by richardfontana** [comment]
Ahh, the license in the Fedora package is **not** the same, because the Fedora version has the "and associated documentation files", while the license @daniel-parasoft has submitted does not. As far as I can tell without actually doing a diff the first and second paragraphs are otherwise the same.

**Comment by swinslow** [comment]
Discussed on 2023-01-26 call, Steve to review the two paragraphs from Fedora and confirm they match the version from the maya example project, if so then will mark to add

**Comment by swinslow** [comment]
Confirmed that the ["Clips license" in the maya project linked above](https://github.com/DrItanium/maya/blob/master/LICENSE.CLIPS) matches the paragraphs from @richardfontana's [comment above](https://github.com/spdx/license-list-XML/issues/1658#issuecomment-1347485836) in Fedora, ignoring the separate documentation paragraph.

Given the earlier discussion, I'm going to mark this as approved using the license text from these two links.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Clips License

## License ID

Clips

## XML markup

N/A; use the license text from @richardfontana's [Dec. 12 comment in this thread](https://github.com/spdx/license-list-XML/issues/1658#issuecomment-1347485836)

## Notes:

N/A

## Additional rationale or notes on decision:

See above; if a separate ID is ultimately needed for the documentation-related paragraph, that can be addressed separately
