### ISSUE TITLE
Deprecated licences used in exceptions description

### ISSUE THREAD

**Issue by vargenau** [spdx/license-list-XML#1662]
In https://spdx.org/licenses/GCC-exception-2.0.html,
replace "Typically used with GPL-2.0+" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/GCC-exception-3.1.html,
replace "Typically used with GPL-3.0" by "Typically used with GPL-3.0-only or GPL-3.0-and-later".

In https://spdx.org/licenses/Autoconf-exception-2.0.html,
replace "Typically used with GPL-2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/Autoconf-exception-3.0.html,
replace "Typically used with GPL-3.0" by "Typically used with GPL-3.0-only or GPL-3.0-and-later".

In https://spdx.org/licenses/Bison-exception-2.2.html,
replace "Typically used with GPL-2.0 or GPL-3.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later or GPL-3.0-only or GPL-3.0-and-later".

In https://spdx.org/licenses/Font-exception-2.0.html,
replace "Typically used with GPL-2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/Qt-GPL-exception-1.0.html,
replace "Typically used with the GPL-3.0" by "Typically used with GPL-3.0-only or GPL-3.0-and-later".

In https://spdx.org/licenses/Qt-LGPL-exception-1.1.html,
replace "Used with the LGPL-2.1, which is mentioned explicitly in the exception text." by "Used with the LGPL-2.1-only, which is mentioned explicitly in the exception text."

In https://spdx.org/licenses/eCos-exception-2.0.html,
replace "Typically used with GPL-2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/389-exception.html,
replace "Specified to be associated with GPL-2.0" by "Specified to be associated with GPL-2.0-only".

In https://spdx.org/licenses/CLISP-exception-2.0.html,
replace "Typically used with GPL-2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/DigiRule-FOSS-exception.html
replace "Typically used with GPL-2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/DigiRule-FOSS-exception.html
replace "Typically used with GPL-2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/FLTK-exception.html,
replace "Specified to be associated with LGPL-2.0." by "Specified to be associated with LGPL-2.0-only or LGPL-2.0-and-later or LGPL-2.1-only or LGPL-2.1-and-later or LGPL-3.0-only or LGPL-3.0-and-later."

In https://spdx.org/licenses/i2p-gpl-java-exception.html,
replace "Typically used with GPL-2.0+" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/LGPL-3.0-linking-exception.html,
replace "It is being added as it has been used in several projects as a linking exception to LGPL-3.0." by "It is being added as it has been used in several projects as a linking exception to LGPL-3.0-only."

In https://spdx.org/licenses/mif-exception.html,
replace "Typically used with GPL-2.0 for older versions of GCC." by "Typically used with GPL-2.0-only for older versions of GCC."

In https://spdx.org/licenses/OCCT-exception-1.0.html,
replace "LGPL-2.1 with this exception" by "LGPL-2.1-only with this exception"

In https://spdx.org/licenses/openvpn-openssl-exception.html,
replace "Typically used with GPL 2.0" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/PS-or-PDF-font-exception-20170817.html,
replace "Author-suggested standard header language recommends use with AGPL-3.0" "Author-suggested standard header language recommends use with AGPL-3.0-only".

In https://spdx.org/licenses/Qwt-exception-1.0.html,
replace "Specified to be associated with LGPL-2.1." by "Specified to be associated with LGPL-2.1-only."

In https://spdx.org/licenses/u-boot-exception-2.0.html,
replace "Typically used with GPL-2.0+" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

In https://spdx.org/licenses/WxWindows-exception-3.1.html,
replace "Typically used with GPL-2.0+" by "Typically used with GPL-2.0-only or GPL-2.0-and-later".

**Comment by richardfontana** [comment]
In actuality some of these are known to be used with one of the -only or -or-later variants. For example, GCC-exception-3.1 would most likely be encountered with GPL-3.0-or-later and not with GPL-3.0-only.

**Comment by vargenau** [comment]
Thank you Richard.

Can you (and others) comment on my proposal before I create the pull request?

**Comment by jlovejoy** [comment]
thanks @vargenau - this is a good catch. Those should certainly use current ids in the examples. I think I've merged one PR related to this already, but did you want to prepare the rest? (if so, that would be greatly appreciated!!!)

**Comment by vargenau** [comment]
> thanks @vargenau - this is a good catch. Those should certainly use current ids in the examples. I think I've merged one PR related to this already, but did you want to prepare the rest? (if so, that would be greatly appreciated!!!)

Hi @jlovejoy 
I have created pull request https://github.com/spdx/license-list-XML/pull/1708
Please check everything I did is correct.
