### ISSUE TITLE
MS-LPL XML should accommodate 'and' instead of '&' in last section

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1663]
Section 3(F) of the SPDX version of MS-LPL says: "(F) Platform Limitation- The licenses granted in sections 2(A) & 2(B) extend only to the software or derivative works that you create that run on a Microsoft Windows operating system product."

However, a number of uses of this license, including by Microsoft, use "2(A) and 2(B)" rather than "2(A) & 2(B)". 
https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing/-/blob/v0.3/webrtc/LICENSE_THIRD_PARTY#L388
https://kb.acronis.com/system/files/content/2012/12/38416/mspublic.txt
https://marketplace.visualstudio.com/items/MikeBMcL.WindowsStoreDirectXGameTemplate/license

As I understand it, "&" and "and" are not equivalent under the SPDX matching guidelines.

**Comment by jlovejoy** [comment]
thanks @richardfontana - good catch and I'm surprised we haven't come across this before. 

@swinslow @goneall - would this be best dealt with via <alt> tag markup or could we add "&" and "and" to the list of equivalent words (even though & isn't a word really...)

**Comment by goneall** [comment]
> would this be best dealt with via tag markup or could we add "&" and "and" to the list of equivalent words (even though & isn't a word really...)

From a tooling perspective, the equivalent words are just text tokens, so making "&" and "and" equivalent would work.

**Comment by jlovejoy** [comment]
Thanks @goneall - I love when there is actually an easy answer.

Only problem is... out list of equivalent words is here, but I'm no longer sure how to update it? https://spdx.org/licenses/equivalentwords.txt

@swinslow probably knows this also...

**Comment by swinslow** [comment]
+1 to adding this to the "equivalent words" list.

This file lands in the License List website when I upload it as part of the release process, by copying it from license-list-data: https://github.com/spdx/license-list-data/blob/master/website/equivalentwords.txt

The "source" version is here in the license-list-XML repo, at https://github.com/spdx/license-list-XML/blob/main/equivalentwords.txt, and I assume that the License List Publisher tool pulls it over (though I haven't confirmed that).

I'll submit a PR to add this to the list!

**Comment by jlovejoy** [comment]
PR #1700 fixes this
