### ISSUE TITLE
New license request: snprintf [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1664]
**1.** License Name: snprintf
**2.** Short identifier: snprintf
**3.** License Author or steward: Patrick Powell, I guess
**4.** Comments: This is a legacy permissive license that appears in source files of many present-day FOSS projects.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/177
**7.** URL(s): https://github.com/openssh/openssh-portable/blob/master/openbsd-compat/bsd-snprintf.c#L2
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://www.openssh.com/

**Comment by richardfontana** [comment]
Fedora priority: low

**Comment by swinslow** [comment]
+1 to add. Simple historical permissive statement, broadly appears where the snprintf code is used in a variety of projects as well as commercial products.

**Comment by bsdimp** [comment]
+1 to add. Same reasons as @swinslow.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

snprintf License

## Short ID

snprintf

## XML markup

N/A

## Additional rationale or notes on decision:

N/A
