### ISSUE TITLE
New license request: Martin-Birgmeier [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1667]
**1.** License Name: Martin Birgmeier
**2.** Short identifier: Martin-Birgmeier
**3.** License Author or steward: Martin Birgmeier (?)
**4.** Comments: This is a simple permissive legacy license that is found in source files of multiple packages in present-day Linux distributions such as Fedora.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/178
**7.** URL(s): https://github.com/Perl/perl5/blob/blead/util.c#L6136
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://www.perl.org

**Comment by richardfontana** [comment]
Fedora priority: low

**Comment by swinslow** [comment]
+1 to add. Simple permissive historical license, and "it's in the Perl sources" easily meets the "substantial usage" criteria.

Minor note when adding the XML template and test text: I would suggest changing the backticks and single quotes around `as is` to just standard quotation marks.

**Comment by Pizza-Ria** [comment]
So, trying to do the diligence on this (per Richard's advice) and perhaps I have missed something but I downloaded the current stable source and ran 

`C:\Users\schalnat\Downloads\perl-5.36.0\perl-5.36.0>findstr /i /r /c:"birgmeier" *.*`

I only got one hit:  util.c:* Copyright (c) 1993 Martin Birgmeier which was the same as the one provided by the submitter.  

Is that enough to merit an SPDX identifier?  Just trying to understand if we will promote ANY license in Perl (as I then assume it is populated throughout the known Perl Programming World) or if there are other considerations?

**Comment by swinslow** [comment]
@Pizza-Ria Great question. Personally, my take is that if a license is in the perl source code itself (which appears to be the case here), then I'd view that as constituting sufficiently widespread use for that particular factor.

I'd feel differently for a license that was e.g. just used in a random Perl module on [CPAN](https://www.cpan.org/modules/index.html).

**Comment by Pizza-Ria** [comment]
Good enough for me then.  I'll also +1 for the reasons above.

**Comment by Pizza-Ria** [comment]
+ Agree with the formatting of quotes vs. backticks that @swinslow raised.

**Comment by swinslow** [comment]
Text of license, reformatted to address quotes vs. backticks:

You may redistribute unmodified or modified versions of this source
code provided that the above copyright notice and this and the
following conditions are retained.

This software is provided "as is", and comes with no warranties
of any kind. I shall in no event be liable for anything that happens
to anyone/anything when using this software.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

Martin Birgmeier License

## Short ID

Martin-Birgmeier

## XML markup

Note that single quotes / backticks are to be changed to ordinary double quotes for the markup

## Additional rationale or notes on decision:

N/A
