### ISSUE TITLE
xpp XML markup should be revised to accommodate IU Extreme! Lab Software License, Version 1.2

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1668]
One version of the Indiana University Extreme! Lab Software License v 1.2 can be seen here:
https://x-stream.github.io/mxparser/licenses.html

It differs from SPDX xpp in the following respects:

* It corrects the misspelling of "University" as "Univeristy" 
* Paragraph 4, sentence 1 of xpp says 
 ```The name "Indiana Univeristy" and "Indiana Univeristy Extreme! Lab" shall not be used to endorse or promote products derived from this software without prior written permission from Indiana University.``` 
while the corresponding sentence of the IUELSLv1.2 license has 
```The name "Indiana University" or "Indiana University Extreme! Lab" shall not be used to endorse or promote products derived from this software without prior written permission from Indiana University.``` 

Assuming SPDX-legal does not consider those differences substantive I suggest that the xpp markup be revised to accommodate the later (?) license.

**Comment by jlovejoy** [comment]
no, that would not be a different license!!  ah, typos/spelling errors... easy fix tho with some markup

**Comment by jlovejoy** [comment]
PR made at #1705

**Comment by swinslow** [comment]
#1705 is not passing the CI tests at last check, so I'm moving this forward to 3.20.

**Comment by swinslow** [comment]
#1705 was merged, so this is now complete.
