### ISSUE TITLE
Saxpath XML markup should be revised to accommodate JDOM variant

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1669]
The JDOM project (a widely used open source Java library which is packaged in Linux distributions like Fedora) uses a license that is essentially the same as SPDX Saxpath. See:
https://github.com/hunterhacker/jdom/blob/master/LICENSE.txt

(Fedora priority: low)

**Comment by jlovejoy** [comment]
agreed, the changes are only in name

the JDOM variants adds this at the end:
`This software consists of voluntary contributions made by many 
 individuals on behalf of the JDOM Project and was originally 
 created by Jason Hunter <jhunter_AT_jdom_DOT_org> and
 Brett McLaughlin <brett_AT_jdom_DOT_org>.  For more information
 on the JDOM Project, please see <http://www.jdom.org/>. 
`

but I don't see that as "part" of the license in that it's more informational. Nonetheless, I wonder if we'd need to add that as optional for matching purposes?
@goneall - thoughts?

**Comment by swinslow** [comment]
+1 to adding markup to accommodate the name and email changes.

I would lean towards omitting the additional language at the end. I agree with @jlovejoy that it's not really part of the "license" proper (notwithstanding being included in the LICENSE.txt file).
