### ISSUE TITLE
New license request: xlock [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1671]
**1.** License Name: ras2tif
**2.** Short identifier: ras2tif
**3.** License Author or steward: Unknown
**4.** Comments: This is a simple legacy permissive license which covers some source code that is present in at least one present-day major project packaged in Linux distributions like Fedora.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/179
**7.** URL(s): https://fossies.org/linux/tiff/contrib/ras/ras2tif.c
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://gitlab.gnome.org/GNOME/gimp/-/blob/master/plug-ins/file-tiff/file-tiff-save.c#L27

**Comment by richardfontana** [comment]
Fedora priority: low

**Comment by swinslow** [comment]
I believe the first paragraph of this is a match for the various markup options from [HPND](https://spdx.org/licenses/HPND.html). Language from the second paragraph appears in various forms in [Rdisc](https://spdx.org/licenses/Rdisc.html) and [DOC](https://spdx.org/licenses/DOC.html).

+1 to add.

For name / identifier, it looks like this shows up in a variety of projects. The earliest that I'm finding it referenced is [xlock](http://sillycycle.com/xlock.html) with a copyright date of 1988, so perhaps `xlock` would be more appropriate than `ras2tif` if we're picking a project name?

**Comment by jlovejoy** [comment]
discussed on Jan 26th call - agreed to add

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

xlock License

## Short ID

xlock

## XML markup

N/A

## Additional rationale or notes on decision:

N/A
