### ISSUE TITLE
New license request: libzmq-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1672]
**1.** License Name: libzmq exception
**2.** Short identifier: libzmq-exception
**3.** License Author or steward: Unknown
**4.** Comments: This is nominally an exception used with LGPL-3.0-or-later in ZeroMQ, a widely-used FOSS project. It resembles Classpath-exception-2.0 but is notable in deviating from standard GPL/LGPL exceptions in mandating inclusion of the exception in modified versions, possibly the result of a drafting oversight. (As such it is not clear it is an 'exception' as SPDX understands the term.)
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/180
**7.** URL(s): https://github.com/zeromq/libzmq#license
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://www.zeromq.org

**Comment by richardfontana** [comment]
Fedora priority: low

**Comment by swinslow** [comment]
@richardfontana Good point on the "you must extend this exception" language being different from the more permissive "you may" language of the way we've traditionally thought about exceptions. I think this one warrants being part of the broader conversation about whether to change the way we think about exceptions.

I'm marking this one as pending discussion on an upcoming legal team call.

**Comment by richardfontana** [comment]
I'm not sure whether SDPX-legal reached a decision on whether the libzmq exception should be treated as an "exception" in the SPDX exception list sense. 

While I consider this license FOSS, I am not sure I would want to see Fedora use "LGPL-3.0-or-later WITH libzmq-exception", because that would be inconsistent with other cases (predating Fedora's migration to SPDX expressions) where Fedora has created unique names for the use of nominal GPL-family licenses with non-normative (though FOSS) additional restrictions or cases where the GPL-family license is accompanied by an official restrictive, unconventional (though FOSS) gloss or interpretation. 

@jlovejoy since you are involved both in Fedora and SPDX-Legal, I thought I should call this opinion to your attention. The issue is, if SPDX adds libzmq-exception to the exception list, I think Fedora should possibly use a LicenseRef instead of the seemingly obvious SPDX license list expression.
