### ISSUE TITLE
Confusion between `GPL-x.0-only` and `GPL-x.0-or-later`

### ISSUE THREAD

**Issue by mbtools** [spdx/license-list-XML#1682]
## Background

When reviewing a GPL license file, there's quite a bit of confusion about identifying which of the two license terms applies. Is it `GPL ... only` or `GPL ... or later`?

The confusion stems from the fact that the GPL **_license text_** is identical for both options. Only when viewing the **_license notice_** (as seen in the Standard License Header on SPDX) can one identify the correct license.

## Issue

The definitions of `GPL ... or later` licenses are correct. However, the definitions of the `GPL ... only` licenses contain two flaws:

1. The text under "How to Apply These Terms to Your New Programs" incorrectly states that "any later version" might be used. 
1. The "Notes" section states that an example for the "or later" approach is included when actually the example is for the "only" approach.

## Suggested Solution

Here's an example for `GPL-3.0-only` and how the notes and how-to section should be corrected. This will make a small difference to the `GPL-3.0-or-later` license text and therefore allow for accurate identification of the license. It will make a huge difference when automating license identification.

`GPL-1.0-only` and  `GPL-2.0-only` should be corrected the same way.

https://spdx.org/licenses/GPL-3.0-only.html

Incorrect. Should say `for the "only" approach.`:

![image](https://user-images.githubusercontent.com/59966492/196567187-89d6c027-ed3c-4abd-b5e7-4b009664d08f.png)

Incorrect. Should say `, version 3.`:

![image](https://user-images.githubusercontent.com/59966492/196567339-3cb11ba9-fe4d-4502-b0a5-bddc8153c1cf.png)

Correct:

![image](https://user-images.githubusercontent.com/59966492/196567256-41c116f3-c999-406d-af53-9db2de1cf324.png)

## Licenses

- https://spdx.org/licenses/GPL-1.0-only.html (should be corrected)
- https://spdx.org/licenses/GPL-1.0-or-later.html (ok)
- https://spdx.org/licenses/GPL-2.0-only.html (should be corrected)
- https://spdx.org/licenses/GPL-2.0-or-later.html (ok)
- https://spdx.org/licenses/GPL-3.0-only.html (should be corrected)
- https://spdx.org/licenses/GPL-3.0-or-later.html (ok)

**Comment by richardfontana** [comment]
I may be misunderstanding but I think this should be directed to the Free Software Foundation as the license steward.

**Comment by mbtools** [comment]
For the "how-to apply", FSF is responsible for that. However, the "Notes" and "Standard License Header" sections are defined by SPDX ie in this repo.

**Comment by mbtools** [comment]
Yes, I was referring to the last sentence of the "Note". I interpreted it as pointing to the "Standard License Header" at the bottom of the page (which is an example). 

The way you see it makes sense. Maybe the last sentence could be more explicit:

"The example in the `How to Apply These Terms` section of the license shows..."

**Comment by jlovejoy** [comment]
ah yes, I believe we probably had a lengthy discussion around this when the FSF requested we change the identifiers. 

For the -only options, the text in the "How to Apply These Terms to Your New Programs" section of the actual license text on the FSF website shows the "or any later version" option. 

But we did make sure the Standard License Header field showed the corresponding actual header you would use for that particular option, that is -only.

The Note was supposed to explain this. but I can see where "The example in the exhibit to the license shows the license notice for the "or later" approach."
might be improved by saying, "The example in the How to Apply These Terms section of the license shows..."

If that would help, I'm happy to accept a Pull Request with that re-wording!

**Comment by mbtools** [comment]
True. Appendix is better than section. I updated the PR.
