### ISSUE TITLE
Eclipse license EDL1.0

### ISSUE THREAD

**Issue by Jan-Pleva** [spdx/license-list-XML#1683]
Hello,

Would be possible to add to SPDX database the licese from Eclipse EDL 1.0.
https://www.eclipse.org/org/documents/edl-v10.php

Right now it is recognised differently in some tools (e.g. JFrog xRay) for some components acording to the public information, which create little chaos.

For example:
https://mvnrepository.com/artifact/org.glassfish.jaxb/jaxb-runtime/2.3.6

Thank you.

**Comment by richardfontana** [comment]
This is already in the SPDX License List as BSD-3-Clause. EDL is just an Eclipse rebranding of that license.

**Comment by Jan-Pleva** [comment]
Yea, but thats just confusing, because on other sources it is represented as EDL.
E.g. on maven central.
![image](https://user-images.githubusercontent.com/71633160/198011730-9bda0f33-9484-411e-94e4-4d6ca5146840.png)
![image](https://user-images.githubusercontent.com/71633160/198011868-8d354eb1-49eb-4764-b354-d2bd750390d0.png)
![image](https://user-images.githubusercontent.com/71633160/198012177-0ee68352-db7d-4592-bdd8-740400851f12.png)
![image](https://user-images.githubusercontent.com/71633160/198012683-d892ac8d-3520-4fd7-8e55-6533ae569b7b.png)

**Comment by Jan-Pleva** [comment]
Isnt this case same as you have [ISC License](https://spdx.org/licenses/ISC.html) and [BSD Zero Clause License](https://spdx.org/licenses/0BSD.html)? 
Thay are identical, but you have in database both.

**Comment by zvr** [comment]
These two are not identical, since ISC has the obligation 

> provided that the above copyright notice and this permission notice appear in all copies.

which 0BSD does not have.

I completely agree that the correct name should be used, i.e. BSD-3-Clause instead of Eclipse Distribution License.

**Comment by zvr** [comment]
Previous request for this license (not accepted): #1149

**Comment by jlovejoy** [comment]
indeed, we had this discussion once before (thanks @zvr for finding that!) and the page cited https://www.eclipse.org/org/documents/edl-v10.php - even acknowledges that this is "New BSD License" as listed on the OSI site and the SPDX identifier is BSD-3-Clause

Why people use EDL 1.0 in various places, is beyond me, as that seems to only cause confusion. The example above even has the correct SPDX identifier in the source code! Maybe someone can correct the license field in Maven??  :)

**Comment by Jan-Pleva** [comment]
I'm afraid there will be more use of these EDL in components.

According to my understanding of the spdx mission, I should find the given license in the database with the fact that there will be a link to the correct one. So it will be there, people won't be confused, but it will refer to the right one.

Then everyone will be happy :)

**Comment by Jan-Pleva** [comment]
You can't just change 459 components, and thats just my quick search...
![image](https://user-images.githubusercontent.com/71633160/198233770-e52ce1db-9c43-42fa-a751-0e65267981c7.png)

**Comment by zvr** [comment]
So, it seems that the issue is how the site you're looking at presents license information -- not with an SPDX identifier but with arbitrary strings.
They are not even consistent: (screenshot from https://mvnrepository.com/artifact/org.eclipse.jgit/org.eclipse.jgit/6.2.0.202206071550-r)
![2022-10-27-112917_210x121_scrot](https://user-images.githubusercontent.com/136705/198248500-bedcbe92-ab01-49e9-95ba-af669dbe9051.png)

I know that there are efforts underway to have real SPDX info in Maven metadata instead of free text, but I can't report on the current state of this. Feel free to weigh in on that discussion.

**Comment by Jan-Pleva** [comment]
Anyway, it seems like a **better transparent solution** to create an EDL entity in the SPDX registry and refer to it in the context to original "New BSD License".

**Comment by zvr** [comment]
Ah, no -- as @richardfontana wrote above there cannot be two SPDX identifiers referring to the same license. This goes against the whole SPDX project mission and goals.

As shown in the link that @jlovejoy added above, even the Eclipse project themselves do not want this and say the SPDX identifier of EDL is `BSD-3 Clause`.

Not having different names referring to the same things is the whole problem that SPDX License List tries to solve.

**Comment by Jan-Pleva** [comment]
> Not having different names referring to the same things is the whole problem that SPDX License List tries to solve.
Then it seems to be all for this discussion.

**Comment by jlovejoy** [comment]
thans @Jan-Pleva for looking into this. It's a bit annoying. We could consider adding a note in the BSD-3-Clause about this, if that would help a bit?

**Comment by Jan-Pleva** [comment]
Yes, any information is counting ;)

**Comment by jlovejoy** [comment]
PR #1703
