### ISSUE TITLE
GPL2+linking_exception license

### ISSUE THREAD

**Issue by Jan-Pleva** [spdx/license-list-XML#1694]
Hello,

where you would categorize this licence
GPL2+linking_exception license
https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.20.html
Is it new?
Thank you

**Comment by richardfontana** [comment]
You have to determine what the specific exception is (there are many GPL exceptions, some of which are represented in the SPDX exception list). Assuming the one referred to there is this:
https://github.com/unbit/uwsgi/blob/master/LICENSE#L5
that appears to match to [GCC-exception-2.0](https://spdx.org/licenses/GCC-exception-2.0.html).

**Comment by jlovejoy** [comment]
+1 to what @richardfontana stated. 

@Jan-Pleva - is that the text of the exception you were referring to/asking about?

**Comment by Jan-Pleva** [comment]
Yes, it is.
Thank you.

**Comment by jlovejoy** [comment]
confirming that the exception here https://github.com/unbit/uwsgi/blob/master/LICENSE#L5 0 is a match to [GCC-exception-2.0](https://spdx.org/licenses/GCC-exception-2.0.html) - so nothing to add and closing issue
