### ISSUE TITLE
New license request: IEC-Code-Components-EULA [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by nicorikken** [spdx/license-list-XML#1695]
**1.** License Name: Code Components End-user licence agreement
**2.** Short identifier: CC-EULA
**3.** License Author or steward: International Electrotechnical Commission (IEC)
**4.** Comments: IEC CC-EULA is applicable to all 'Code Components' that are distributed along the IEC licenses. The license has been going back at least to December 2016 and is relevant for at least two Open Source projects: https://github.com/com-pas and https://github.com/openscd both using the code components of the IEC 61850 standard. Example of a Code Components distribution page: https://www.iec.ch/dyn/www/f?p=103:227:4631044159258::::FSP_ORG_ID,FSP_LANG_ID:1273,25
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/182
**7.** URL(s): https://www.iec.ch/webstore/custserv/pdf/CC-EULA.pdf, https://www.iec.ch/CCv1, https://www.iec.ch/copyright
**8.** OSI Status: Unknown
**9.** Example Projects: https://github.com/com-pas, https://github.com/openscd

**Comment by jlovejoy** [comment]
@nicorikken - the two links to example projects go to pages that list a bunch of projects - is the implication that all of those listed are under this license?

**Comment by jlovejoy** [comment]
# New submission review

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes - not entirely clear, but nothing prevents it from being applicable to source code
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [ ] Yes - appears so
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes - appears so
    - [ ] No

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes - no, there is a restriction on modifications, "The software license extends to modifications permitted under the relevant IEC standard. "
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [ ] No - really only relevant for code ("Code Components") related to IEC standards
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - unclear at this point
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes - I would say so, even though it has a restriction on types of modification
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No - 

## Summary of factors, outcome, comments

_Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives_

**Comment by swinslow** [comment]
I agree with @jlovejoy's comments above, writing here to add a few additional thoughts:
* I'm also overall +1 to add
* I'd note that the CoMPAS project that @nicorikken is part of the Linux Foundation's [LF Energy family of projects](https://www.lfenergy.org/projects/compas/), noting just as relevant to "Other factor" 3 for significance of a project where the license is being used
* If this does get added, I would however _not_ want to use the identifier `CC-EULA` for this. I think we've been fairly consistent in only using `CC` as the _starting prefix_ for Creative Commons licenses (some other licenses or exceptions may include `CC`, but I don't think as a prefix).

When I saw this issue titled `CC-EULA` my first assumption was that this would be Creative Commons-related, so I'd suggest we go instead with e.g. `IEC-Code-Components-EULA` since it really is specific to this particular work.

**Comment by jlovejoy** [comment]
@swinslow - agreed on naming, it should not start with CC

I'm going to update the issue name to avoid any further confusion on that.

I'm still a bit confused as to where this is used in the cited projects - a random poking around, I only found Apache-2.0

**Comment by swinslow** [comment]
@jlovejoy For CoMPAS, I see this at https://github.com/com-pas/compas-open-scd -- referenced in the README and with the EULA in the top level folder at https://github.com/com-pas/compas-open-scd/blob/main/CC-EULA.pdf

I suspect the actual content is part of what's in [this file](https://github.com/com-pas/compas-open-scd/blob/main/src/schemas.ts) in that repo, given the IEC copyright notices.

Another repo in the same project lists the license in a DEP5 file at https://github.com/com-pas/compas-scl-xsd/blob/develop/.reuse/dep5

**Comment by nicorikken** [comment]
@swinslow thanks for filling in while I was away. Indeed the SCD files are used to generate the code API related code. The 1:1 copy of the files is stored in https://github.com/com-pas/compas-scl-xsd with some wrapper to publish as a module.

This module is imported into the compas-core project: https://github.com/com-pas/compas-core/blob/0fa667cf07bd8665cf048b82228ebd663926f12f/pom.xml#L74-L78 and amended with some custom definitions, as described in the architecture documentation https://github.com/com-pas/compas-architecture/blob/main/technical/XSD_EXTENSIONS.md

The OpenSCD project is another project (also used inside of the CoMPAS project) https://github.com/openscd which also uses these XSD files and so is bound to the same IEC license.

All so-called 'code components' that are distributed as additions to the standard are distributed by IEC under the terms of this CC-EULA license. Some of those code components are available here: https://www.iec.ch/dyn/www/f?p=103:227:4631044159258::::FSP_ORG_ID,FSP_LANG_ID:1273,25 As you can tell it is quite some code there. It is likely that some parts of the standard will be added to the code components in the near future as well, as some trivial but essential pieces of code are not yet distributed in this way.

As this is a niche license for which there is little legal consensus, we have chosen not to include the code directly into the main repository, which is why you mainly see Apache 2.0 licensed code.

Regarding the identifier, IEC uses CC-EULA but indeed I too thought of Creative Commons when I first encountered it :smile: So I'm fine with changing it to something more meaningful. 

I have informed IEC in the past about the intention to submit it to SPDX, but that has been a while ago. Also communication with IEC about this license has been confusing at times. So now that there is a concrete request I'll inform them about it.

**Comment by swinslow** [comment]
Thanks @nicorikken! Appreciate the additional context and feedback here, that is all helpful to know.

Given the comments, I'm a firmer +1 to add, though I'd suggest we leave this pending for a week or so in order to see whether anyone from IEC decides to weigh in (as the license author / "steward"). If we don't hear back from them, I'd be in favor of adding unless there are objections to be discussed.

**Comment by swinslow** [comment]
@jlovejoy You mentioned in your original writeup that you were "mostly +1 to add, but would like to have an update on usage before making a final decision" -- are you good to give a +1 now?

**Comment by jlovejoy** [comment]
@swinslow - yes, +1 to add

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

IEC Code Components End-user licence agreement

## License ID

IEC-Code-Components-EULA

## XML markup

N/A

## Notes:

N/A

## Additional rationale or notes on decision:

N/A
