### ISSUE TITLE
Review language for CI GitHub bot to notify on accepted licenses

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1696]
@seabass-labrax has submitted #1625 to automatically add a comment when a PR is accepted (e.g. closed and labeled as accepted). This comment would inform submitters about the process for when the license ID would officially appear, etc.

I'm creating a new issue for 3.20 because I'd suggest that this should align with, and should communicate to submitters, whatever we decide is appropriate guidance for using pre-release accepted IDs for discussion in #1600.

**Comment by jlovejoy** [comment]
@swinslow is there something more to do on this?

I believe this wasn't working and @xsuchy may have fixed it??

**Comment by jlovejoy** [comment]
@swinslow - I'm closing this as it's now working
