### ISSUE TITLE
New license request: LOOP [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jamesjer** [spdx/license-list-XML#1706]
**1.** License Name: Common Lisp LOOP License
**2.** Short identifier: LOOP
**3.** License Author or steward: Unknown
**4.** Comments: The license does not exactly match any license currently on the list.  The license text has been stable for many years.  The license is known to be in use by various Common Lisp implementations.

In each known use, the license text is repeated twice, once referring to MIT and once referring to Symbolics.  The license text is similar, but not identical, to the NTP license.

There is no known license name or short identifier.  I will propose both, but am happy to have somebody choose better names.
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/183
**7.** URL(s): https://gitlab.com/embeddable-common-lisp/ecl/-/blob/develop/src/lsp/loop.lsp
**8.** OSI Status: Unknown
**9.** Example Projects: https://gitlab.com/embeddable-common-lisp/ecl/-/blob/develop/src/lsp/loop.lsp, http://git.savannah.gnu.org/cgit/gcl.git/tree/gcl/lsp/gcl_loop.lsp?h=Version_2_6_13pre, https://sourceforge.net/p/sbcl/sbcl/ci/master/tree/src/code/loop.lisp, https://github.com/cl-adams/adams/blob/master/LICENSE.md, https://github.com/blakemcbride/eclipse-lisp/blob/master/lisp/loop.lisp, https://gitlab.common-lisp.net/cmucl/cmucl/-/blob/master/src/code/loop.lisp

**Comment by richardfontana** [comment]
This arises out of a Fedora packaging issue (@jamesjer is a Fedora package maintainer), and we would request that this be treated as a 'high Fedora priority' issue.

**Comment by jlovejoy** [comment]
note, already determined to be "allowed" for Fedora, as per https://gitlab.com/fedora/legal/fedora-license-data/-/issues/93#note_1169622386

**Comment by jlovejoy** [comment]
# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [ ] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [ ] Yes
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [ ] Yes
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No

## Summary of factors, outcome, comments

_Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives_

**Comment by richardfontana** [comment]
Could [HPND-sell-variant](https://github.com/spdx/license-list-XML/blob/main/src/HPND-sell-variant.xml) be modified to accommodate this license?

Here's the LOOP license:

```
;;;> Permission to use, copy, modify and distribute this software and its
;;;> documentation for any purpose and without fee is hereby granted,
;;;> provided that the M.I.T. copyright notice appear in all copies and that
;;;> both that copyright notice and this permission notice appear in
;;;> supporting documentation.  The names "M.I.T." and "Massachusetts
;;;> Institute of Technology" may not be used in advertising or publicity
;;;> pertaining to distribution of the software without specific, written
;;;> prior permission.  Notice must be given in supporting documentation that
;;;> copying distribution is by permission of M.I.T.  M.I.T. makes no
;;;> representations about the suitability of this software for any purpose.
;;;> It is provided "as is" without express or implied warranty.
```
Here's a very similar license text that I think would match to HPND-sell-variant today:

```
;;;> Permission to use, copy, modify and distribute this software and its
;;;> documentation for any purpose is hereby granted without fee,
;;;> provided that the above copyright notice appear in all copies and that
;;;> both that copyright notice and this permission notice appear in
;;;> supporting documentation, and that the name of "M.I.T." and "Massachusetts 
;;;> Institute of Technology" not be used in advertising or publicity
;;;> pertaining to distribution of the software without specific, written
;;;> prior permission. M.I.T. makes no
;;;> representations about the suitability of this software for any purpose.
;;;> It is provided "as is" without express or implied warranty.
```

**Comment by richardfontana** [comment]
Could HPND be modified to cover this variant (it seems very close, looking at the XML)? Or is that not possible because HPND is OSI-approved?

**Comment by jlovejoy** [comment]
I don't think so. This license looks to add this sentence, "Notice must be given in supporting documentation that copying distribution is by permission of M.I.T."

**Comment by richardfontana** [comment]
OK, I was wondering if it might be viewed by SPDX as superfluous given that the license (like HPND) requires that "both that copyright notice and this permission notice appear in supporting documentation".

**Comment by bsdimp** [comment]
+1 to include. Symbolics suggests this license is quite old since they haven't been a thing since the early 90s

**Comment by seabass-labrax** [comment]
I'd be happy to prepare the XML+text for this license.

**Comment by jlovejoy** [comment]
Thanks @seabass-labrax and @bsdimp !

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## License full name

Common Lisp LOOP License

## Short ID

LOOP

## XML markup

I don't think this needs markup - if we found it used by others with a different name, we can add it then

**Comment by jlovejoy** [comment]
@jamesjer - could please prepare the PR with the xml and txt files now that this is accepted?
this may help https://github.com/spdx/license-list-XML/blob/main/DOCS/xml-fields.md

**Comment by jamesjer** [comment]
I've made an attempt.  I don't really know what I'm doing, though!

**Comment by seabass-labrax** [comment]
To @jamesjer, a personal thank you from a CL enthusiast for making this submission!
