### ISSUE TITLE
New License: xdebug

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1718]
https://github.com/xdebug/xdebug/blob/master/LICENSE is a match to https://spdx.org/licenses/PHP-3.01.html but for the names

I think we can add some markup and accommodate. 

Also wondering if the last 3 lines with the contact info are really part of the licenses or should simply be optional?

(relates to https://gitlab.com/fedora/legal/fedora-license-data/-/issues/95 )

**Comment by jlovejoy** [comment]
ugh, it appears that PHP-3.0.1 includes in clause 4, "You may indicate that your software works in conjunction with PHP by saying "Foo for PHP" instead of calling it "PHP Foo" or "phpfoo""

but the xdebug variant does not...

**Comment by swinslow** [comment]
@jlovejoy Should we move this forward to 3.21? Given that extra line in clause 4, I'm inclined to say that Xdebug is not a match to PHP-3.01.

Alternatively, it sounds like Xdebug is in Fedora, and given that + the nature of the license I would be +1 to add it to the license list as a separate license (ID `Xdebug-1.03`, name "Xdebug License, version 1.03") if there's another +1 to add it.

**Comment by jlovejoy** [comment]
@swinslow - yeah... the "extra line" is actually in PHP-3.01 and Xdebug removes it
we probably should move it forward, unless @richardfontana wants to weigh in :)

**Comment by jlovejoy** [comment]
ping for others thoughts on this one? @richardfontana @copernicat @bsdimp

**Comment by copernicat** [comment]
Since the change in clause 4 attempts to change the permission slightly compared to PHP, I agree that a new ID is warranted. +1 to add

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Xdebug License v 1.03

## License ID

Xdebug-1.03

## XML markup

none

## Notes:

Based on the PHP License v 3.01
