### ISSUE TITLE
New license request: fitsio [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#1720]
**1.** License Name: fitsio
**2.** Short identifier: fitsio
**3.** License Author or steward: Unknown
**4.** Comments: it is the license used by fitsio project (https://heasarc.gsfc.nasa.gov/docs/software/fitsio/fitsio.html), package manager inclusions, https://repology.org/project/cfitsio/packages
**5.** License Request Url: http://tools.spdx.org/app/license_requests/185
**6.** URL(s): https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node9.html
**7.** OSI Status: Unknown
**8.** Example Projects: https://heasarc.gsfc.nasa.gov/docs/software/fitsio/fitsio.html

**Comment by jlovejoy** [comment]
This is similar in spirit to https://spdx.org/licenses/NIST-PD-fallback.html but different enough to warrant a new license.

@chenrui333 - do you know if this is the only project that uses this license? Or where else this project might be incorporated?

**Comment by swinslow** [comment]
Agreed that this would warrant a separate identifier from NIST-PD-fallback.

I'm confused by the intro line "Copyright (Unpublished-all rights reserved under the copyright laws of the United States)". Is the assertion that this code is not published? That would be odd...

**Comment by jlovejoy** [comment]
@swinslow - I don't understand the point of that parenthetical either!

**Comment by chenrui333** [comment]
> I'm confused by the intro line "Copyright (Unpublished-all rights reserved under the copyright laws of the United States)". Is the assertion that this code is not published? That would be odd...

That sounds like `public domain` assertion, I saw other similar statements in other licenses.

**Comment by chenrui333** [comment]
> @chenrui333 - do you know if this is the only project that uses this license? Or where else this project might be incorporated?

yeah, I think fitsio is the only project that I am aware of such license.

**Comment by seabass-labrax** [comment]
This license is used in [Debian](https://packages.debian.org/sid/source/cfitsio) and [Fedora](https://packages.fedoraproject.org/pkgs/cfitsio/), so has substantial use in my opinion.

**Comment by seabass-labrax** [comment]
License text from Debian:

> Copyright:
> 
>   Copyright (Unpublished--all rights reserved under the copyright laws of
>   the United States), U.S. Government as represented by the Administrator
>   of the National Aeronautics and Space Administration.  No copyright is
>   claimed in the United States under Title 17, U.S. Code.
> 
> 
> Copyright files present in the sources, but not used:
> 
>   Copyright (C) 1995-2010 Mark Adler
>   Copyright (C) 1995-2010 Jean-loup Gailly
>   Copyright (C) 1990-2003 Burkhard Burow

**Comment by swinslow** [comment]
Discussed on 2023-02-09 Legal Team call, noted that this is in Fedora per Repology, permissive public domain style license + significant use based on use in NASA project; agreed to add.

**Comment by seabass-labrax** [comment]
From <https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node2.html>:

> ...the terms FITSIO and CFITSIO are interchangeable and refer to the same library.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X ] approved
- [ ] not approved

## License full name

CFITSIO License

## Short ID

CFITSIO

## XML markup

Include entire copyright notice (with odd parenthetical) in copyright tag

## Additional rationale or notes on decision:

used in project in major Linux distros

**Comment by copernicat** [comment]
I will PR this one Friday, tomorrow.

**Comment by swinslow** [comment]
Thank you @copernicat!

**Comment by copernicat** [comment]
Hi @jlovejoy or @swinslow do you happen to have a link to the instructional video handy for the next steps? I can't locate it. Thanks!
