### ISSUE TITLE
New exception: generic Autoconf-exception

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1721]
https://sourceforge.net/projects/libxosd/files/libxosd/xosd-2.2.14/xosd-2.2.14.tar.gz/download uses an exception that is very similar to Libtool-exception and I think it can be accommodated by markup.
Compare: https://spdx.org/licenses/Libtool-exception.html
to

`As a special exception to the GNU General Public License, if you
distribute this file as part of a program that contains a
configuration script generated by Autoconf, you may include it under
the same distribution terms that you use for the rest of that program.`

here is another variant: http://git.savannah.gnu.org/gitweb/?p=autoconf.git;a=blob_plain;f=build-aux/config.guess;hb=HEAD

See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/68#note_1093747760 for background

**Comment by jlovejoy** [comment]
a program or library that _is built using GNU Libtool_, you may include _this file_ under the same distribution 

a program or library that _contains a configuration script generated by Autoconf_, you may include _it_ under the same distribution

**Comment by jlovejoy** [comment]
hmmm... looking at this again, now I'm not sure...

@swinslow - thoughts?

**Comment by swinslow** [comment]
> a program or library that _is built using GNU Libtool_, you may include _this file_ under the same distribution
> 
> a program or library that _contains a configuration script generated by Autoconf_, you may include _it_ under the same distribution

I would lean towards treating those as two substantially different sets of terms. So I'd probably give them different identifiers.

**Comment by jlovejoy** [comment]
agreed @swinslow - and this came up recently (or again) in Fedora and I've found it in a number of places:
https://docs.oracle.com/cd/E17952_01/mysqld-5.5-license-com-en/license-gnu-libtool.html
https://opensource.apple.com/source/launchd/launchd-258.1/launchd/compile.auto.html
https://www3.sqlite.org/src/file?name=config.sub&ci=8074d59cf177cb91
https://launchpad.net/ubuntu/precise/+source/xmltooling/+copyright
https://tracker.debian.org/media/packages/s/sipwitch/copyright-1.9.15-3

updating labels to new license

if we could get another +1 on this (beside me, since technically, I submitted) then we can get it in for 3.20
@bsdimp @richardfontana  ??

**Comment by swinslow** [comment]
To be more specific from my earlier comment, I am +1 to add this, though also uncertain what to use as an ID / name. Might hesitate to use "Autoconf-exception" given the existing [Autoconf-exception-2.0](https://spdx.org/licenses/Autoconf-exception-2.0.html) and [Autoconf-exception-3.0](https://spdx.org/licenses/Autoconf-exception-3.0.html), and particularly since the latter has a specific name / title? But I could be convinced otherwise...

**Comment by jlovejoy** [comment]
@swinslow - yeah, I was thinking about that too. I mean it's clearly for Autoconf, so I feel like that should be in the name. I'm not sure if I'd presume it's 1.0
I do think of it as more "generic" since 2.0 specifically states "This special exception to the GPL applies to versions of Autoconf released by the Free Software Foundation."

maybe:
Autoconf-exception-generic

**Comment by swinslow** [comment]
@jlovejoy sure, that works for me!
