### ISSUE TITLE
New license request: w3m [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#1731]
**1.** License Name: w3m
**2.** Short identifier: w3m
**3.** License Author or steward: Unknown
**4.** Comments: It is a license used by w3m project, and mark package managers (https://repology.org/project/w3m/packages) marked this as MIT license, but the copy is different.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/189
**6.** URL(s): https://github.com/tats/w3m/blob/master/COPYING
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/tats/w3m

**Comment by jlovejoy** [comment]
Thanks for the submission, @chenrui333 - is the w3m project, the only project this license is used in, do you know?

**Comment by chenrui333** [comment]
@jlovejoy I think it might be the case, this is pretty old codebase.

**Comment by seabass-labrax** [comment]
Full text from w3m's GitHub repository:

> Use, modification and redistribution of this software is hereby granted,
> provided that this entire copyright notice is included on any copies of
> this software and applications and derivations thereof.
> 
> This software is provided on an "as is" basis, without warranty of any
> kind, either expressed or implied, as to any matter including, but not
> limited to warranty of fitness of purpose, or merchantability, or
> results obtained from use of this software.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

w3m License

## Short ID

w3m

## XML markup

no markup needed

## Additional rationale or notes on decision:

used in Fedora

**Comment by swinslow** [comment]
Discussed on 2023-02-09 call, simple permissive license, used in major distro, does not appear to match anything currently on the SPDX license list; agreed to add.

**Comment by copernicat** [comment]
@swinslow do you need this done today? I volunteered to proceed, but I am not sure of next steps.

**Comment by jlovejoy** [comment]
uploading videos now and can meet later to help! We are aiming to do release on Sunday!

**Comment by chenrui333** [comment]
Thanks folks!
