### ISSUE TITLE
New license request: CC-BY-NC-SA-2.0-DE

### ISSUE THREAD

**Issue by oliverpool** [spdx/license-list-XML#1735]
1.  License Name: Creative Commons Namensnennung — Nicht-kommerziell — Weitergabe unter gleichen Bedingungen 2.0
2. Short identifier: CC-BY-NC-SA-2.0-DE
3. License Author or steward: Creative Commons Corporation
4. Comments: See below
5.  Standard License Header:
6.  URL: https://creativecommons.org/licenses/by-nc-sa/2.0/de/legalcode
7.  OSI Status: Not Submitted

Comments:
This license is sometimes used in Germany. For instance https://www.dpsg1300.de/impressum/

>  Der Inhalt dieser Seite ist unter einer [Creative Commons-Lizenz](http://creativecommons.org/licenses/by-nc-sa/2.0/de/) ("Namensnennung - NichtKommerziell - Weitergabe unter gleichen Bedingungen 2.0 Deutschland") lizenziert.

Similar licenses, already available:
- [CC-BY-NC-SA-3.0-DE](https://github.com/spdx/license-list-XML/issues/1232)
- [CC-BY-NC-SA-2.0-UK](https://github.com/spdx/license-list-XML/issues/1285)

**Comment by swinslow** [comment]
+1 to add, given indicia of real-world usage and our standard process of adding CC localized licenses upon request when real usage is shown.

**Comment by jlovejoy** [comment]
agreed, +1 to add for consistency

**Comment by seabass-labrax** [comment]
I agree with @swinslow and @jlovejoy that this license should be included in the SPDX License List.

PS. Does the Deutsche Pfadfinderschaft Sankt Georg condone hilltop yodelling?

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

Creative Commons Attribution Non Commercial Share Alike 2.0 Germany  (note -- going with English name in accordance with other CC license names)

## Short ID

CC-BY-NC-SA-2.0-DE

## XML markup

needs markup for lists and bullet points, similar to other CC licenses like [CC-BY-NC-SA-2.0-DE](https://github.com/spdx/license-list-XML/blob/main/src/CC-BY-NC-SA-3.0-DE.xml)

## Additional rationale or notes on decision:

N/A

**Comment by oliverpool** [comment]
Minor feedback if your last comment is a template:
 maybe you could include a link to https://github.com/spdx/license-list-XML/blob/main/DOCS/new-license-workflow.md#if-license-is-accepted-workflow in there (when accepted)

**Comment by swinslow** [comment]
Great feedback, thank you @oliverpool! I've added #1770 as this relates to a broader conversation we've been having about improving the process documentation (as clearly it needs some work!)
