### ISSUE TITLE
New license request: FRWR [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1736]
**1.** License Name: Freely redistributable without restriction
**2.** Short identifier: FRWR
**3.** License Author or steward: Unknown
**4.** Comments: This license consists of the simple statement "Freely redistributable without restriction" (which may be used by itself or as part of a sentence such as "This table is freely redistributable without restriction". "Freely redistributable" was commonly used earlier in FOSS history as synonymous with FOSS. The origin of this license statement, in the one project where it is known to be used, seems to have involved an upstream maintainer repurposing a Fedora license metadata label. In any case, the one project where this statement is known to appear is packaged in Fedora and other Linux distributions. Fedora has approved "Freely redistributable without restriction" as a license: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/106. This was done specifically in order to submit this license to SPDX for inclusion in the SPDX license list. A further explanation is given in the Fedora Gitlab issue.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/191
**6.** URL(s): https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/array/array30.head.in#L14, https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/array/array30.head.in#L3, https://github.com/mike-fabian/ibus-table-chinese/tree/main/tables/cangjie#L21, https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/cangjie/cangjie5.txt#L29, https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/quick/quick-classic.txt#L11, https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/quick/quick3.txt#L24, https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/quick/quick5.txt#L32, https://raw.githubusercontent.com/mike-fabian/ibus-table-chinese/main/tables/wubi-jidian/wubi-jidian86.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/mike-fabian/ibus-table-chinese

**Comment by richardfontana** [comment]
This issue arises out of work being done by @mike-fabian to migrate the package license metadata for ibus-table-chinese to Fedora licensing standards including the use of SPDX identifiers. As such we consider this a high priority Fedora issue.

**Comment by swinslow** [comment]
Personally I'm +1 to add this.

I admit to some mild queasiness about the idea that the four-word phrase "Freely redistributable without restriction" will show up in the middle of other licenses and cause confusion... but a quick search on Google for that quoted phrase on `site:spdx.org` doesn't appear to show any matches to the current license list. So maybe that's not an issue.

For good measure, here's the full writeup from my view:

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [x] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [x] Yes => actually doesn't seem to appear as a phrase embedded in any current license on the list
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [x] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [x] Yes
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [] No
Not applicable -- I'm not going to say that there's a license steward for a four-word phrase  :)

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [x] Yes => as @richardfontana described above, this seems like a historical statement that might not reiterate the full set of copyright-licensable rights, but is generally understood in historical FOSS practice to mean that.
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [x] Yes
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [x] Yes => used in a package in Fedora
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [x] Yes => that's literally exactly what it says  :)
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No
Not applicable

## Summary of factors, outcome, comments

Given the above, I am +1 to add. Fine with `FRWR` as the ID, I don't have anything better. Probably worth including in the "Notes" section a brief explanation that the license text is intentionally just the 4-word phrase, to avoid confusion.

**Comment by richardfontana** [comment]
Oops, I just realized this won't solve @mike-fabian's problem because it would still (I think) be further dependent on adding FRWR to the FSF list of recognized free software licenses, which is pretty much not going to happen because that list is (AFAIK) no longer actively maintained by the FSF. I'm closing this, but might reopen at a later date.

**Comment by ramcq** [comment]
Even if the process by which the FSF might update the list that SPDX publishes has disappeared, I do believe that giving this license an official entry within the SDPX list will make other subsequent steps easier (ie seeking inclusion within the https://github.com/ximion/appstream/blob/master/data/spdx-free-license-ids.txt list) than trying to do so on the basis of a LicenseRef which is specific to Fedora.

**Comment by swinslow** [comment]
Thanks @ramcq, I'm re-opening this issue based on your comment above.

For others on the SPDX legal team (e.g. @jlovejoy @seabass-labrax @bsdimp @Pizza-Ria or others), feel free to weigh in and +1 (or not) my review above.

**Comment by bsdimp** [comment]
IAMAL, but I'm +1.
The intent is clear, even if the grant leaves much to be desired.
It's in the class of "do whatever" licenses that were widespread years ago, but have fallen into disfavor due to the flawed grants of IP and little clarity in some aspects of the grant.
Having said all that (again, I'm not a lawyer so I have no clue if it matters), I think it should be included because the intent seems clear, it has fairly wide historical usage and is similar to other "grants" that we've said yes to.

**Comment by richardfontana** [comment]
Thank you @ramcq - and I need to comment on that gnome-software issue. I will have to discuss with @jlovejoy how best to proceed with this one, particularly since we decided to create a Fedora LicenseRef- to handle (for the time being, at least) a whole category of ultra-simple, ultra-permissive nonstandard licenses.

**Comment by jlovejoy** [comment]
@richardfontana - where are we at with this one in terms of need for Fedora? (or is there a bigger cross-community discussion that still needs to be had?)

**Comment by richardfontana** [comment]
To be honest this issue was so deeply troubling to me that I had to put it out of my mind with the intention of returning to it later. I guess now it's later. :)

I ask that SPDX hold off a little while longer on this while I refresh my memory on the various problems this issue sprang from, involving multiple projects (Fedora, GNOME Software, AppStream, ibus-table-chinese).

**Comment by swinslow** [comment]
@jlovejoy Given @richardfontana's request above, I'm going to move this one to 3.23. I think if it's still pending at that point on the Fedora side, perhaps we close it then and re-open it in the future if it becomes relevant. Does that work?

**Comment by jlovejoy** [comment]
@richardfontana - should/can we close this?

**Comment by jlovejoy** [comment]
@richardfontana - given the long history on this and unclear path forward, I'm going to close this for now. If it comes up again, we can revisit!
