### ISSUE TITLE
New license request: SWI-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jamesjer** [spdx/license-list-XML#1744]
**1.** License Name: SWI-exception
**2.** Short identifier: SWI-exception
**3.** License Author or steward: Unknown
**4.** Comments: This is actually a license exception, not a license.  It has been used in conjunction with GPL-2.0-or-later.  Various projects under https://github.com/SWI-Prolog/ use this exception.  See this Fedora review for background: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/101.

The exception is almost identical to gnu-javamail-exception, except it adds the clause "compiled with a Free Software compiler".

License inclusion principles:
- The exception does not match another exception already on the SPDX License List.
- The exception has identifiable and stable text; it is not in the midst of drafting.
- The exception is structured to be generally usable by anyone. It is not specific to one project, consortium or corporation.
- The exception is used in multiple projects under the SWI-Prolog umbrella.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/193
**6.** URL(s): https://github.com/SWI-Prolog/packages-clpqr/blob/bfa80b9270274f0800120d5b8e6fef42ac2dc6a5/clpqr/class.pl
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/SWI-Prolog/packages-clpqr

**Comment by swinslow** [comment]
+1 to add. Although the SPDX license inclusion principles are more tailored towards licenses than exceptions, I think the comments above are helpful in considering it.

It certainly appears to be widely used, not just in SWI-Prolog within Fedora but also in [other projects on Github](https://github.com/search?q=%22compiled+with+a+Free+Software+compiler%22&type=code) (many of which appear to be redistributions of code from SWI-Prolog).

**Comment by jlovejoy** [comment]
+1 to add as well. It's annoyingly close to an existing exception, but I think that addition of "compiled with a Free Software compiler" warrants its own identifier.

I think the identifer that @jamesjer has chosen seems sensible too

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## License full name

SWI exception

## Short ID

SWI-exception

## XML markup

Note that this is an exception, not a license, so it goes on the Exceptions List

## Additional rationale or notes on decision:

N/A

**Comment by swinslow** [comment]
Text of exception:

As a special exception, if you link this library with other files,
compiled with a Free Software compiler, to produce an executable, this
library does not by itself cause the resulting executable to be covered
by the GNU General Public License. This exception does not however
invalidate any other reasons why the executable file might be covered by
the GNU General Public License.
