### ISSUE TITLE
New license request: MS-NET-Patent-Promise [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by omajid** [spdx/license-list-XML#1751]
**1.** License Name: ﻿Microsoft Patent Promise for .NET Libraries and Runtime Components
**2.** Short identifier: MS-NET-Patent-Promise
**3.** License Author or steward: Microsoft
**4.** Comments: This isn't technically a license. It's an addition to another license (which is MIT in the case of the one project I have seen use this license) that makes a promise not to assert any patents, given some conditions hold.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/195
**6.** URL(s): https://github.com/dotnet/runtime/blob/main/PATENTS.TXT
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/dotnet/runtime

**Comment by richardfontana** [comment]
This arises out of a Fedora package maintainer issue (@omajid maintains the Fedora package of .NET) and therefore Fedora views this as high priority. :) Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/103

This issue would require SPDX-legal to take a position on what to do about standalone patent licenses, covenants, nonasserts and the like in FOSS project code. 

See the issue I submitted earlier involving a different patent statement: https://github.com/spdx/license-list-XML/issues/1651 .  Among the reasons why this is different is that it is really entirely decoupled from the MIT license. Indeed, Microsoft was using a version of this promise long before it released .NET source code under the MIT license.

**Comment by richardfontana** [comment]
Note from the Fedora side: we are uncertain whether we want to treat this as  a normal "allowed" license or something else, and whether we want to signify the inclusion of this text in an SPDX expression in package metadata or not. It is a fairly difficult question that is related to the difficult question faced by SPDX over whether to treat these kinds of things as "exceptions" or otherwise. I would suggest closing as premature with the possibility of reopening in the future.

**Comment by swinslow** [comment]
Thanks @richardfontana. Given your comment above, I'll go ahead and close this for now, but we can definitely re-open and/or consider as a new issue down the road.

This is linked by reference from #1651 so we should see it there when we have the discussion about definition of "exceptions" going forward. Thanks!
