### ISSUE TITLE
New license request: MS-Mono-Patent-Promise [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by omajid** [spdx/license-list-XML#1752]
**1.** License Name: Microsoft Patent Promise for Mono
**2.** Short identifier: MS-Mono-Patent-Promise
**3.** License Author or steward: Microsoft
**4.** Comments: This is an addition to an existing license (MIT in this case), which grants additional patent-specific permissions, under certain legal conditions.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/196
**6.** URL(s): https://github.com/dotnet/linker/blob/main/PATENTS.TXT
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/dotnet/linker

**Comment by richardfontana** [comment]
This is similar to https://github.com/spdx/license-list-XML/issues/1751 they are probably not representable by a common license text template. For the reasons noted in the other issue I would suggest closing this for now.

**Comment by swinslow** [comment]
Thanks @richardfontana -- will close for now in line with comments in #1751, fine to re-open or open as a new issue down the road.
