### ISSUE TITLE
New license request: LCPL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by rasos** [spdx/license-list-XML#1765]
**1.** License Name: Label Commons Public License
**2.** Short identifier: LCPL-1.0
**3.** License Author or steward: Roland Alton, rasos@alton.at
**4.** Comments: This Label Commons Public Licence (LCPL) is intended to give the public the permission to use a label under certain conditions. Labels are used as a sign, term or mark and can be applied to digital media or tangible material. The usage of labels without applying a LCPL license may be restricted by other organisations or companies who claim copyright and/or register them as a trademark.
A typical use case for LCPL is clarifying usage right of a label used by a wider community. It may be protected by a so-called watchdog organisation, which could be an NGO, a trusted partner organisation or a foundation. Its role would be to claim ownership and probably even register it as a trademark. At the same time the watchdog organisation grants usage rights with only a few restrictions to the extend necessary to prevent misleading or unintended usage, such as making a business with a label of a movement or a software developer community.

More details and example see https://git.fairkom.net/legal/lcpl/

Regarding the license inclusion principles, this license has not yet been submitted, the licenses has a stable text and got feedback e.g. from the Commons Institute during the drafting phase, it has been presented publicly and it has an active steward, who is following the SPDX mailing list and is submitting the license here. The LCPL is not typically protecting software code, but the brand a software framework may be given. The intention is to avoid brand conflict or grabbing situations as we have seen it with free software projects such as Piwik/Matomo.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/197
**6.** URL(s): https://git.fairkom.net/legal/lcpl/-/blob/master/LC_by_sa.md
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://fairmove.org/

**Comment by richardfontana** [comment]
@rasos Assuming this sort of license is even within the scope of the types of instruments SPDX would normally consider for inclusion in its license list, I don't see how this license complies with certain (admittedly "non-definitive") aspects of the SPDX license inclusion principles:

"The license substantially complies with one of the following open source definitions " - the two examples of real-world use given involve invocation of "moral" restrictions which would be incompatible with the specified normative definitions of open source, and I would assume that (given the two example labels discussed) the use of such restrictions would be expected were this license to gain significant adoption.

"The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects."

The README gives two examples of uses. But both uses do not seem to be "actual", let alone "substantial". I may be misunderstanding, but it seems both the fairmove case and the Podcast for Future case involve aspirational labels, that is, labels the organizations (one of which seems to be your organization, or affiliated with your organization) are or were hoping will get adopted by third parties. It is not even clear that there is any effort to actively promote adoption of those labels. For example, it looks like PodcastForFuture was informally proposed as an idea in 2019, but no evidence it was actually adopted in any sense, and there doesn't seem to be any evidence of its being used by anyone elsewhere. Similarly, the fairmove website seems to have a lot of material (also no later than 2019?) promoting the use of the fairmove label, but no examples of any real-world use, let alone any objectively significant uses.  

 These comments are not a judgment on the license itself or what the license seems to intend to accomplish.

**Comment by seabass-labrax** [comment]
@rasos, thank you for submitting this new licence request.

Speaking personally, I am curious to know the intentions behind this licence. It appears to be a generic trademark+copyright licence to be used by charities and other non-profit organisations. However, have you considered instead a public domain waiver (like [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)) for the copyrighted content of such labels and a specific trademark permission per organisation? This would be similar to how SPDX itself does things - the SPDX Specification being under a Creative Commons licence and [with use of the SPDX trademark granted separately](https://spdx.dev/trademark/). The reason for mentioning this is that trademark law is very complex and region-specific (more so than copyright, even), with most use being permitted by law anyway, and conversely a licence isn't a guarantee of legal immunity for infringement!

**Comment by rasos** [comment]
@seabass-labrax Thanks for the feedback. The intention behind this license is to provide a tool for projects to clarify who is allowed to use its name under which conditions. I have seen so many sustainability initiatives or software projects that "lost" their name simply because they did not care about it. When some other initiative or a company found it nice or just by accident used the same name that conflict situation caused to cease the whole initiative.

To protect a trademark there are quite clear international rules and registries for most regions in the world. Agree that it may be difficult to decide if a word or a combined term is eligible to be registered  and in which class and  there are various best practices to share a brand used in different regions or application areas.

First of all, the Label Commons Public License is a tool for making clear, that the trademark issue has been taken attention and that some means have been or may be undertaken, to protect it in some regions in some classes. There will be never an unconditional sharing offer, it remains a joint effort of all users of the brand  to protect it  and to support a watchdog organisation to take appropriate measures, which can vary from just communicating that it is being in use (which makes it harder for anybody else to claim it) up to worldwide trademark registration.

In comparison to the SPDX Trademark License 1.1 the LCPL is sub-licensable, which may give another organisation in another region the option to take measures to protect the brand with a local registry. We probably should make that option more clear.  In fact the LCPL tries to offer a template for what SPDX tried to clarify with its trademark license.

@richardfontana  LCPL has been presented at a large international event for media and art in 2019 and honestly we do not know how many initiatives use it. The promoting non-profit organisation fairkom has recently launched a  Mastodon instance fairmove.net to vitalize the usage of the fairmove brand, which has been showcased at several occasions as a generic label for sustainability and activism.

**Comment by swinslow** [comment]
Below are my comments based on review of this in connection with the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md).

# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [X] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [X] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [ ] No
    - => Not applicable - doesn't appear to be intended as use for software or other similar content, rather for branding
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [ ] Yes
    - [ ] No
    - => Unclear - the license appears to include some typos and markdown formatting issues, as well as possible translation issues (e.g. "Class ist the...")
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No
    - => Unknown, though I'm assuming yes based on @rasos's submission here -- can you confirm? 

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [X] No => The license appears structured with the intent of being a template for essentially a class of licenses, with many replaceable fields. In particular, it appears to permit any licensor to impose any "moral" conditions at their own discretion: "The Licensor may announce a MORAL restriction together with the LCPL notice, such as "No usage allowed in military context"." This particular condition, and (I'd argue) the general ability to permit any such restrictions, would not comply with generally-understood free / open source principals.
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [X] Yes => although it includes some special terms specific to when it's used by fairkom as licensor
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [ ] Yes
    - [X] No => given the discussion in the comments above, I don't see any evidence of substantial non-affiliated use
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes
    - [X] No => as mentioned above, the open-ended "MORAL" restriction essentially enables any restrictions at all to be imposed by the licensor
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [X] Yes
    - [ ] No

## Summary of factors, outcome, comments

There's a separate and open question about whether it's appropriate at all to include licenses on the SPDX list which are intended primarily to license out brands and labels.

But, in this case, given the combination of this one not meeting several of the key "other factors" (in particular, not meeting "free / open" or "limited restrictions" and no evidence of substantial use), I am not in favor of adding this one to the license list, without reaching the broader question around brands / label licenses generally.

**Comment by jlovejoy** [comment]
agree with @swinslow analysis. does not seem appropriate to add given reasons stated above.

**Comment by swinslow** [comment]
Thanks @jlovejoy and all -- given the comments in this thread, I'm going to mark this one as not approved to add to the license list.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [X] not approved

## Name

N/A

## License ID

N/A

## XML markup

N/A

## Notes:

N/A

## Additional rationale or notes on decision:

See analysis in https://github.com/spdx/license-list-XML/issues/1765#issuecomment-1433798861 above, particularly regarding failure to satisfy most of the "other factors" from the license inclusion principles.

Not reaching the question for this one as to whether the SPDX License List is appropriate for "brand" licenses at all.
