### ISSUE TITLE
Add link to "next steps" workflow in decision template

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1770]
Picking up suggestion from @oliverpool at https://github.com/spdx/license-list-XML/issues/1735#issuecomment-1369044724:

When a license is accepted, we frequently use the decision template at https://github.com/spdx/license-list-XML/blob/main/DOCS/template-decision.md to record the "approved" or "not approved" decision.

Per the comment linked above, for the situations where a license is approved, it would be great to include in the template a link to documentation explaining what happens next. This might be the "If License is Accepted Workflow" section at https://github.com/spdx/license-list-XML/blob/main/DOCS/new-license-workflow.md#if-license-is-accepted-workflow, though we have discussed reworking and streamlining that document.

Other possibilities might include https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md for a shorter overview of the process, and/or https://github.com/spdx/license-list-XML/blob/main/DOCS/xml-fields.md for details on the specific XML file content.

Finally, let's also look at @seabass-labrax's PR at #1625 which would potentially automate adding a comment with a message along these lines -- in addition to the timeline, this could also include links to assist with the process.

Either way, we need to take a step back and look at the process documentation as it clearly needs a bit of streamlining and improvement.  :)  @jlovejoy would this be good to discuss at one of the next two Legal Team calls, or would this be better after we've gotten past the large number of pending requests for 3.20?

**Comment by jlovejoy** [comment]
I think I've updated some of the concepts that you mention above in terms of improving the request-new-license documentation overview. 

Adding a link to that from the decision template would be easy to do, but yeah, let's look at this all together!

**Comment by swinslow** [comment]
Discussed on legal team call 2023-02-23, agreed to add in template decision a link to workflow as mentioned above

**Comment by jlovejoy** [comment]
@swinslow - I made a PR for this. We still have the other issue open that @seabass-labrax created, but I think we can merge and close this.
