### ISSUE TITLE
BSD-3-Clause variant: "The name(s) <name> must not be used ..."

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1773]
I found this license in Apache Lucene:

```
Copyright © 2003,
Center for Intelligent Information Retrieval,
University of Massachusetts, Amherst.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

3. The names "Center for Intelligent Information Retrieval" and
"University of Massachusetts" must not be used to endorse or promote products
derived from this software without prior written permission. To obtain
permission, contact info@ciir.cs.umass.edu.

THIS SOFTWARE IS PROVIDED BY UNIVERSITY OF MASSACHUSETTS AND OTHER CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
SUCH DAMAGE.
```

I believe clause 3 is not a match to BSD-3-Clause for three reasons:

- It has "The name <entity>" rather than "The name of"
- It has "must not" rather than "may not"
- It adds a contact sentence for asking for name-use permission.

Possibly some or all of this variance can be captured by revising the BSD-3-Clause XML file but I'm not sure.

**Comment by swinslow** [comment]
Thanks @richardfontana! From a quick redline, I see one other minor difference:

* It omits "specific" before "prior written permission"

I note from [a Google search](https://www.google.com/search?client=safari&rls=en&q=%22must+not+be+used+to+endorse+or+promote+products%22+site%3Aspdx.org&ie=UTF-8&oe=UTF-8) that the literal phrase "must not be used to endorse or promote products" appears in several other BSD-3-style licenses, though each of them has additional clauses as well. (Several appear to include some version of the contact sentence.)

I sort of want to say that this could be accommodated by markup in BSD-3-Clause. But particularly given the mix of adding the specific instruction for how to obtain permission, plus the _very slightly arguable_ differences between "may not" / "must not" and the omission of "specific", I think there's an arguable case that this could potentially have a different legal effect than BSD-3-Clause. (As a practical matter, I wouldn't expect it to, but someone could make a non-frivolous argument that these are relevant differences.)

Given that, I'm inclined to add as a separate license, but could be talked out of it.

**Comment by swinslow** [comment]
Discussed on 2023-02-09 legal team call, had a general feeling that this is so close to BSD-3-Clause that we want to call it a match, but some discomfort that it may cross the threshold of being arguably substantively different to warrant a separate identifier.

Didn't really reach a decision, so others should please comment here with their thoughts  :)

**Comment by bsdimp** [comment]
@swinslow I wasn't able to make the call... What's the thing that causes it to cross the line? IANAL, but none of these seem legally different...  

Do we have a list of those items that make two nearly identical licenses be different somewhere, or is it a 'know it when I see it' standard that those with law degrees reach consensus on?

**Comment by seabass-labrax** [comment]
We certainly do have a list of *definitely* equivalent words (<https://spdx.org/licenses/equivalentwords.txt>), but it doesn't cover this case, unfortunately.

**Comment by bsdimp** [comment]
Hmmm. that list seems to be variations in spelling or spaces only...

**Comment by jlovejoy** [comment]
re: "The names "Center for Intelligent Information Retrieval" and
"University of Massachusetts" must not be used to endorse or promote products
derived from this software without prior written permission."

this is most similar to "The name of [name] may not be used... " which is accounted for already, see https://github.com/spdx/license-list-XML/blob/main/src/BSD-3-Clause.xml

In which case, this is plural v. singular - which seems obvious to accommodate. 

As for "the name of Joe may not be used" v. "the name of Joe must not be used" - I'm having a hard time seeing a difference in meaning other than the former sounding more polite. When stated in the affirmative, may v. must has a big difference, e.g.:
- you may use the name
- you must use the name
In this case, the former is permissive, but not required, whereas the latter is obligatory.

But when you switch it to "you may not... " or "you must not... " - neither is giving permission, but there is nothing being required instead either. (hopefully I'm making sense)

I'm happy to hear other thoughts here, though!

as for "specific prior written permission" v. "prior written permission" - the inclusion of "specific" seems extraneous to me, but again - happy to hear other thoughts!

**Comment by swinslow** [comment]
@jlovejoy I tend to agree with your analysis that the _practical_ difference between the two is limited.

One note to consider, though: If we add this as markup to BSD-3-Clause, one of the changes would be to include an `<optional>` tag for "To obtain permission, contact info@ciir.cs.umass.edu." (Or some variation which includes a generic email address.) If we do that, I _think_ that the "To obtain permission..." line would show up at https://spdx.org/licenses/BSD-3-Clause.html for everyone. It would show up with text color indicating it is optional, but for folks who look to the License List for getting a copy of the text, they might start expecting that this line is "part of" the standard BSD-3-Clause.

Given that, I might lean towards treating this one as a separate license identifier?

**Comment by jlovejoy** [comment]
good point @swinslow - It still sort of pains me to add a license for these changes which are pretty minor, but given the amount of markup that BSD-3-Clause is already collecting, it does sort of seem "safer" to add it...

maybe we add it as is (using Umass name, no markup) and see if this variant is found used by others?

**Comment by bsdimp** [comment]
How big a tent should 3-BSD be? And if it isn't big enough for this, then how do we partition it? And won't some other license accumulate things if we don't put it in 3bsd? Put another way, it seems a bad choice to not include it just because 3bsd is too complex without a bigger plan because there are a dozen more of these we'll see in the coming months... and what do we do with them? How do we know where to add them?

**Comment by richardfontana** [comment]
I think in this license "must not" has the same meaning as "may not" in the de facto standard BSD-3-Clause variant. 

I would lean towards accommodating this variant within BSD-3-Clause and perhaps addressing @swinslow's concern in some other way, such as discouraging people from using the License List to get copies of license texts (or else having the License List display only some sort of blessed "standard variant"?). :)

**Comment by jlovejoy** [comment]
discussed again on 6/22 - all on call agreed that in this context "must not" and "may not" have same meaning (4 lawyers on call!) and can accommodate with markup.

**Comment by jlovejoy** [comment]
coming back to this - seems like the changes were deemed equivalent to BSD-3-Clause, but the additional text "To obtain permission, contact info@ciir.cs.umass.edu." is problematic to the extent that adding this as optional will show up in the BSD-3-Clause template and this additional text has only been seen in this one variant.  

so.. I guess we are adding this as a separate license?

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [BSD 3-Clause License (variant 007)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[b]/README.md#user-content-BSD-3-Clause-License-(variant-007):~:text=BSD%203%2DClause%20License%20(variant%20007))
short name: BSD-3-Clause-007
markers: Do Not Promote Marker, General Terms Matches Marker
category: BSD
OSI status: _none_

**ScanCode**
matched id: [bsd-new](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-new.LICENSE)

**Comment**
Regarding this as a BSD 3-Clause variant. The 3rd clause extension we would regard descriptive. No specific condition or obligation. +1 to cover in existing BSD-3-Clause

**Comment by jlovejoy** [comment]
discussion on 8/22 legal call - how to accommodate extra sentence in a way (with alt tag) so that it shows the lack of this text and also accommodates the email address, instead of optional - but need to investigate how this translates to web page. 

also would mark "specific" as optional

**Comment by swinslow** [comment]
@jlovejoy See #2630 -- from some local testing it appears that include the new `<alt>` match at the end of clause 3 will not show up on the website, but will still be available in the XML / templating for matching purposes.
