### ISSUE TITLE
Typo: MERCHANTIBILITY

### ISSUE THREAD

**Issue by szepeviktor** [spdx/license-list-XML#1774]
Many occurrences: https://github.com/spdx/license-list-XML/search?q=MERCHANTIBILITY
I think it is a typo.
https://www.merriam-webster.com/dictionary/merchantability

**Comment by szepeviktor** [comment]
Thank you for your response. This is too hot for me :) I'm no businessman.

**Comment by richardfontana** [comment]
Even more curiously, the license SPDX calls Artistic-1.0 uses "merchantability" - it has that spelling on the OSI website, while the OSI website also has Artistic-1.0-Perl with the "merchantibility" spelling. This is a slightly interesting fact for those who have been trying to solve the mystery of where the Artistic-1.0 variant actually came from.

**Comment by jlovejoy** [comment]
this might be easiest dealt with by adding the two spelling variants to the "replaceable" words list, as who knows where else this might appear (nor do I want to know!)

@swinslow - thoughts?

**Comment by jlovejoy** [comment]
not really markup issue, but there isn't a better label...

**Comment by swinslow** [comment]
@jlovejoy I tend to agree... even though my dictionary tells me that "MERCHANTIBILITY" isn't the right way to spell it, it sure seems like a lot of license drafters feel otherwise! And yes, probably easiest to add to the equivalent words list rather than markup changes in a significant number of licenses.

**Comment by swinslow** [comment]
Just submitted #1792 to address this. If this is merged prior to 3.20 then the release process should replace the updated equivalent words file at https://spdx.org/licenses/equivalentwords.txt to include this (see [B.9.2 in the matching guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b9-varietal-word-spelling)).

**Comment by szepeviktor** [comment]
Thank you all for your work!

**Comment by seabass-labrax** [comment]
And thank you for reporting the issue :grinning:
