### ISSUE TITLE
New license: BSD-Attribution-HPND-disclaimer

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1775]
This is somewhat like BSD-3-Clause-Attribution but has some differences including a different disclaimer:

```
# Copyright (c) 2017 Carnegie Mellon University.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in
#    the documentation and/or other materials provided with the
#    distribution.
#
# 3. The name "Carnegie Mellon University" must not be used to
#    endorse or promote products derived from this software without
#    prior written permission. For permission or any other legal
#    details, please contact
#      Office of Technology Transfer
#      Carnegie Mellon University
#      5000 Forbes Avenue
#      Pittsburgh, PA  15213-3890
#      (412) 268-4387, fax: (412) 268-7395
#      tech-transfer@andrew.cmu.edu
#
# 4. Redistributions of any form whatsoever must retain the following
#    acknowledgment:
#    "This product includes software developed by Computing Services
#     at Carnegie Mellon University (http://www.cmu.edu/computing/)."
#
# CARNEGIE MELLON UNIVERSITY DISCLAIMS ALL WARRANTIES WITH REGARD TO
# THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS, IN NO EVENT SHALL CARNEGIE MELLON UNIVERSITY BE LIABLE
# FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```
(source: https://github.com/cyrusimap/cyrus-sasl/blob/master/COPYING )

**Comment by jlovejoy** [comment]
is this found in Fedora?

**Comment by swinslow** [comment]
@richardfontana Thanks -- yes, this looks like it is a combination of a few things:
* the preamble and clauses from [BSD-3-Clause-Attribution](https://spdx.org/licenses/BSD-3-Clause-Attribution.html)
* an added "For permission or any other legal details, please contact..." bit appended to the 3rd clause
* the disclaimer from [HPND](https://spdx.org/licenses/HPND.html)

I'm +1 to add -- simple permissive and historical license, used in Fedora / other distros.

Naming is hard. How would you feel about this?
* ID: BSD-Attribution-HPND-disclaimer
* Name: BSD with Attribution and HPND disclaimer

We could instead reference CMU, but there's already a ["CMU license"](https://spdx.org/licenses/MIT-CMU.html) on the list (which doesn't in fact reference CMU) so I'm not terribly inclined to go that direction.

**Comment by jlovejoy** [comment]
+1 to add and I think @swinslow naming suggestion seems fine

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

BSD with Attribution and HPND disclaimer

## License ID

BSD-Attribution-HPND-disclaimer

## XML markup

Not currently, could be added in the future similar to other BSD variants if other matches found in the wild

## Notes:

N/A

## Additional rationale or notes on decision:

N/A
