### ISSUE TITLE
New license request: DevWheels1 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mrj** [spdx/license-list-XML#1780]
**1.** License Name: DevWheels V1
**2.** Short identifier: DevWheels1
**3.** License Author or steward: Mark R. James
**4.** Comments: Hello,

I'd like the DevWheels Licence to be considered for listing. This is a licence that I wrote and steward, and which I use on three of my software packages.

I've read the inclusion principles, and although the licence meets all SPDX's definitive factors, the licence doesn't fully comply with either the OSI or FSF criteria, and I'm not sure how "substantially complies" is interpreted. I'm also not sure in what senses "free" is used in "the license is primarily intended for free distribution of content."

The main features of the DevWheels licence are:

1. A package is released when it's made available for use by the public,
2. If released, buildable source of the entire package must be made available,
3. Packages can be re-released (unmodified, modified, integrated, or bundled),
4. Forks, and integrations beyond standard use, must have a DevWheels licence,
5. Package owners can require payment before certain users can run either a released or a private package in a production context. These payments are distributed up derivation trees by price-increment (hopefully reflecting value-add) for both the package itself and its DevWheels-licensed dependencies,
6. The cost of an upgrade is by default the price difference between the two versions, and
7. Run licences can be transferred and sold.

It's basically AGPL with a monetary restriction on Freedom Zero if deployed. That is, preserving full freedom to tinker and share, but transferring some freedom that many users ([and licence-writers](https://www.gnu.org/philosophy/selling.html)) consider less important to aid each developer in a fair way.

[Here's](https://slashdot.org/firehose.pl?op=view&id=109187356) a further explanation of the licence.

Thank you.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/199
**6.** URL(s): https://devwheels.com/licence-text
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/mrj/jsjbridge

**Comment by richardfontana** [comment]
One of the nondefinitive factors in the inclusion principles is:

> The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects.

Can you explain how, if at all, this criterion is met?

**Comment by mrj** [comment]
Thank you Richard for your question.

My argument would be that the usefulness and uniqueness of the DevWheels Licence makes it as worthwhile as some of the 545 licences in SPDX's latest release. I don't know how many users the least popular of these has, but one of my releases with this licence has over 50,000.

The reason I made this submission is so that I can release a RubyGem without having to state a [licence-ID](https://guides.rubygems.org/specification-reference/#license=) of "Nonstandard", although RubyGems recently allowed their licence-ID to link to a file rather than be an SPDX ID.

And I suppose it's a bit like the Catch-22 of a young person having trouble getting a job because they lack experience. A standard licence is easier and more attractive to employ. I would like to advocate for my licence. This is a start.

**Comment by swinslow** [comment]
@mrj [The purpose of the SPDX License List](https://github.com/spdx/license-list-XML/blob/main/DOCS/faq.md#what-is-the-spdx-license-list) is to be "a list of commonly found licenses and exceptions used in free and open or collaborative software, data, hardware, or documentation."

For brand new licenses for which there is little or no evidence of current usage, you are welcome to seek to encourage others to use your license and to get broad adoption. But the purpose of the SPDX License List is to reflect commonly- or broadly-used licenses in open collaborative development, not as a promotional list of newly-drafted licenses that do not have such usage.

I'm not in favor of adding the license at this time. You are of course welcome to resubmit the license for consideration at some point in the future if you have seen significantly broader community uptake of it.

**Comment by mrj** [comment]
OK, thank you.
