### ISSUE TITLE
UK Open Parliament Licence v3.0 would benefit from an SPDX identifier

### ISSUE THREAD

**Issue by robbiemorrison** [spdx/license-list-XML#1781]
The following license would doubtless benefit from an SPDX identifier:

- https://www.parliament.uk/site-information/copyright-parliament/open-parliament-licence/

Note that this instrument differs from the OGL-UK-3.0:

- https://spdx.org/licenses/OGL-UK-3.0.html

See also Wikipedia:

- https://en.wikipedia.org/wiki/Parliamentary_copyright#Open_Parliament_Licence
- https://en.wikipedia.org/wiki/Open_Government_Licence#Open_Parliament_Licence

Perhaps **OPL-UK-3.0** would suit?

**Comment by jlovejoy** [comment]
Hi @robbiemorrison - can you please follow our the license submission process, as described here: https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md

Thanks!

**Comment by robbiemorrison** [comment]
Have just submitted a detailed request as suggested.

Please mark this issue as either closed or work-in-progress.

**Comment by jlovejoy** [comment]
duplicate of #1788 so closing this one
