### ISSUE TITLE
New license request: GNAT-exception

### ISSUE THREAD

**Issue by Rombobeorn** [spdx/license-list-XML#1784]
**1.** License Name: none
**2.** Short identifier: GMGPL-exception
**3.** License Author or steward: Presumably someone on the GNAT team at New York University, who may or may not work at Adacore now.
**4.** Comments: Fedora license exception review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/142

GPL 2 with this exception is known as the GNAT modified GPL or GMGPL. The exception by itself has no name that I'm aware of. As far as I can tell it originated when GNAT (the GNU NYU Ada Translator) was written at New York University. Adacore once used GMGPL for all their Ada libraries. It's much rarer now, as they have moved most of their code to GPL 3 and the GCC Runtime Library exception. I'm currently aware of two places where this exception is still used:

· Florist still has the old GMGPL – GPL 2 with this exception.

· GPRbuild includes some example code that we install as documentation in Fedora. In recent versions those files apply this exception to GPL 3.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/200
**6.** URL(s): An example chosen at random: https://github.com/AdaCore/florist/blob/master/libsrc/posix-configurable_file_limits.adb
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/AdaCore/florist, https://github.com/AdaCore/gprbuild

**Comment by jlovejoy** [comment]
This exists and has been determined to be "allowed" for Fedora

**Comment by swinslow** [comment]
+1 to add as an exception. This follows the pattern of many other exceptions on the exceptions list, just using a different technical "trigger" for the exception to apply.

For naming -- @Rombobeorn As far as you're aware, does it look like this exception originated with GNAT? If so, I'd be inclined to use the ID `GNAT-exception` since that follows the pattern that is _generally_ used on the [Exceptions list](https://spdx.org/licenses/exceptions-index.html). Or if it's more tied to another component (GNARL / FLORIST / AdaCore), any of those would work -- I'm just not familiar with the pieces of these Ada tools so I'm kind of guessing.

**Comment by Rombobeorn** [comment]
"GNAT-exception" works for me, although I don't believe it was ever used in the compiler itself, but rather in its library. The exception is written for libraries after all.

Some background might help you understand what you're deciding on. GNAT was originally a fork of GCC modified to compile Ada. It was merged back around the time when the GNU C Compiler transformed into the GNU Compiler Collection, so now GNAT is the Ada front-end of GCC.

With the compiler come a standard library and a runtime library, which are often treated together as Libgnat. (The name suggests that GNARL or Libgnarl is the part that is considered the runtime library.) This, I believe, is where this license exception originated.

A bunch of helper programs are also included with the GCC source code: Gnatmake, Gnatbind, Gnatlink, Gnatprep, Gnatclean and more. A wrapper program called "gnat" allows you to call those as "gnat make", "gnat bind" and so on. Those don't have this exception as they aren't libraries.

Development of GNAT continued in the company Ada Core Technologies, later Adacore. They have added many new libraries and tools. Some of their names contain "GNAT". Others don't. They habitually used this exception in their libraries until they started switching from GPL 2 to GPL 3.

Nowadays you'll find names containing "GNAT" all over Adacore's website. GNAT Studio is an IDE. Gnatbench is a plugin for Eclipse. Gnatcoll is a sprawling collection of libraries. These and GCC, GDB and several other tools and libraries are bundled and sold as GNAT Pro. Adacore's customers can log in to GNAT Tracker, which I guess is something like an issue tracker for support requests.

Thus "GNAT" is a little unspecific, but that's rather fitting as this exception was historically used for several libraries from Adacore.

**Comment by jlovejoy** [comment]
+1 to add, I'm agnostic on name

I think that's the 2 "votes" needed for a "used in  major distro" - @swinslow should I add the final decision info?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

GNAT exception

## License ID

GNAT-exception

## XML markup

none

## Notes:

none

## Additional rationale or notes on decision:

none

**Comment by swinslow** [comment]
@jlovejoy I'll add this one now
