### ISSUE TITLE
New license request: Brian-Gladman-3-Clause

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1785]
**1.** License Name: Brian Gladman 3-Clause License
**2.** Short identifier: brian-gladman-3-clause
**3.** License Author or steward: Unknown
**4.** Comments: It's very similar to BSD-3-Clause in spirit, with different wording in the lead-in and a shorter disclaimer.

This is included in the package SWI-Prolog which is included in Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/201
**6.** URL(s): https://github.com/SWI-Prolog/packages-clib/blob/master/sha1/brg_endian.h
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/SWI-Prolog/packages-clib/blob/master/sha1/brg_endian.h

**Comment by jlovejoy** [comment]
This license is `allowed` for Fedora, see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/112

submitted on behalf of @jamesjer

**Comment by bsdimp** [comment]
Super close to BSD-3-CLAUSE OR gpl-v2.0-or-later

**Comment by jlovejoy** [comment]
Note, the license includes a disjunctive statement to alternatively use "GPL" in the middle of the license. 

Scancode seems to have logged both this variant at https://github.com/nexB/scancode-licensedb/blob/cf386c8c87910ba43352be8c2f93da96ee39dd50/docs/brian-gladman-dual.LICENSE

and a variant without the "alternatively..." sentence here: https://scancode-licensedb.aboutcode.org/brian-gladman-3-clause.html

I'd be curious to hear from @DennisClark if both variants have been found in the wild?!?

**Comment by swinslow** [comment]
That "alternatively" bit in the middle makes this fairly similar to the [Cryptogams license](https://www.openssl.org/~appro/cryptogams/) -- [discussed on the mailing list](https://lists.spdx.org/g/Spdx-legal/topic/new_license_exception/22080938) a few years ago, but I don't think ever added to the License List.

That said, although the rest is sort of a BSD-3-Clause, the wording is definitely different and the disclaimer is unique. So although it's similar in spirit to an "OR" for BSD-3-Clause / GPL-1.0-or-later, I'd say this could stand alone as a separate license ID.

Regardless, I'm +1 to add -- historical license, clearly FOSS, in a major distro (Fedora).

I'm fine with the proposed name. For the ID, I would probably capitalize the first letters of the first and last name -- that's the pattern we've used for other license IDs that use people's names (e.g. [here](https://spdx.org/licenses/libutil-David-Nugent.html), [here (to be published in 3.20)](https://github.com/spdx/license-list-XML/pull/1753)).

**Comment by jlovejoy** [comment]
+1 to add, but still need to sort out what to do about the "alternatively..." paragraph in middle. maybe mark as optional?

@pombredanne - do you have any thoughts on the above question re: the variants included in the Scancode db?

**Comment by swinslow** [comment]
I'm marking this one as approved, with the "ALTERNATIVELY" language included since that's what was requested here. Will follow with the template decision shortly.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Brian Gladman 3-Clause License

## License ID

Brian-Gladman-3-Clause

## XML markup

N/A -- let's not mark the "alternatively" language in the middle as "optional" currently; that can always be revisited to add in markup in the future if a real-world use case warrants it following further review.

## Notes:

N/A

## Additional rationale or notes on decision:

N/A
