### ISSUE TITLE
New license request: Adacore-doc [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Rombobeorn** [spdx/license-list-XML#1787]
**1.** License Name: none
**2.** Short identifier: Adacore-doc
**3.** License Author or steward: unknown
**4.** Comments: Fedora license review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/141

This license occurs in some, but not all, documentation from Adacore. I have found it in XMLada, Gnatcoll-core and Gnatcoll-DB, which are packaged in Fedora.

The oldest instance of this sentence that I'm aware of is a part of Intermetrics' copyright notice in the Ada 95 Reference Manual: http://archive.adaic.com/standards/95lrm/LRMps/rm.ps

XMLada is older than Gnatcoll, so it looks like Emmanuel Briot copied the applicable part of the license from the Ada Reference Manual to the XMLada documentation, and later the same statement was copied to the Gnatcoll documentation, and then to Gnatcoll-DB after Gnatcoll was split. I don't know whether that makes Emmanuel Briot the license author, or someone at Intermetrics.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/202
**6.** URL(s): https://github.com/AdaCore/xmlada/blob/master/docs/index.rst, https://github.com/AdaCore/gnatcoll-core/blob/master/docs/index.rst, https://github.com/AdaCore/gnatcoll-db/blob/master/docs/index.rst
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/AdaCore/xmlada, https://github.com/AdaCore/gnatcoll-core, https://github.com/AdaCore/gnatcoll-db

**Comment by richardfontana** [comment]
Fedora priority: High.

**Comment by swinslow** [comment]
Here's the text:

Copyright (C) 2000-2002, Emmanuel Briot
Copyright (C) 2003-2011, AdaCore

This document may be copied, in whole or in part, in any form or by any
means, as is or with alterations, provided that (1) alterations are clearly
marked as alterations and (2) this copyright notice is included
unmodified in any copy.

**Comment by swinslow** [comment]
I'm +1 to add as a simple, permissive historical license used in Fedora.

I'd propose the ID `AdaCore-DOC` (capitalizing the "c" in "Core" to match AdaCore's styling, and "DOC" to mirror e.g. [the ID for `FreeBSD-DOC`](https://spdx.org/licenses/FreeBSD-DOC.html)).

Although I am +1 to add this one as-is, I do note from @Rombobeorn's note above that several further variations / extensions of this license are included in the [Ada Reference Manual](https://www.adaic.org/resources/add_content/standards/05rm/html/RM-TTL.html), dating back to 1992. I think we should treat those as separate from the AdaCore-specific request here, but just noting them in case any of those variations later come up for different license ID requests.

**Comment by Rombobeorn** [comment]
Writing "DOC" in capitals seems weird to me when it's not an initialism and there's no reason to pronounce it "dee-oh-see", but whatever. If I just get an identifier to put in the Fedora packages, I won't argue about capitalization.

**Comment by swinslow** [comment]
@Rombobeorn fair point! I'm good with AdaCore-doc.

@jlovejoy Can you give this a +1 so that we can mark this as approved?

**Comment by jlovejoy** [comment]
+1 to add

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

_record full name that will be used in the license list_

## License ID

AdaCore-doc

## XML markup

none

## Notes:

none

## Additional rationale or notes on decision:

none
