### ISSUE TITLE
New license request: HPND-sell-variant-MIT-disclaimer

### ISSUE THREAD

**Issue by dcantrell** [spdx/license-list-XML#1789]
**1.** License Name: Jim Knoble's copyright and license statement for x11-ssh-askpass
**2.** Short identifier: JIM-KNOBLE
**3.** License Author or steward: Jim Knoble <jmknoble@pobox.com>
**4.** Comments: This license was found with the x11-ssh-askpass program which is an open source program that provides a passphrase dialog box in the X environment.  It is an older program and predates the more integrated similar tools you find in GNOME and KDE these days.  Still, some users still prefer the original.

After discussing the license with other SPDX contributors, the recommendation was to submit this is a new license as it did not correctly match any known license in the SPDX database.

The original site for x11-ssh-askpass no longer exists, but the project lives on in Linux distributions and github mirrors.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/204
**6.** URL(s): https://github.com/sigmavirus24/x11-ssh-askpass/blob/master/README
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/sigmavirus24/x11-ssh-askpass

**Comment by jlovejoy** [comment]
I presume this exists in Fedora?

**Comment by richardfontana** [comment]
It is in Fedora: https://src.fedoraproject.org/rpms/x11-ssh-askpass
The related fedora-license-data issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/144

**Comment by swinslow** [comment]
Text of license:

```
by Jim Knoble <jmknoble@pobox.com>
Copyright (C) 1999,2000,2001 Jim Knoble
  
Permission to use, copy, modify, distribute, and sell this software
and its documentation for any purpose is hereby granted without fee,
provided that the above copyright notice appear in all copies and
that both that copyright notice and this permission notice appear in
supporting documentation.

+------------+
| Disclaimer |
+------------+

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
express or implied, including but not limited to the warranties of
merchantability, fitness for a particular purpose and
noninfringement. In no event shall the author(s) be liable for any
claim, damages or other liability, whether in an action of contract,
tort or otherwise, arising from, out of or in connection with the
software or the use or other dealings in the software.
```

**Comment by swinslow** [comment]
This one is interesting... the first paragraph appears to be the permission language from [`HPND-sell-variant`](https://spdx.org/licenses/HPND-sell-variant.html) (taking into account its replaceable and optional text). The disclaimer appears to be the disclaimer paragraph from [the `MIT` license](https://spdx.org/licenses/MIT.html).

I'm +1 to add -- simple permissive and historical license that basically combines pieces of two licenses currently on the list.

@jlovejoy @richardfontana For the license ID and name, how would you feel about something that nods towards the two pre-existing licenses? Something like:

- ID: `HPND-sell-variant-MIT-disclaimer`
- Name: HPND sell variant with MIT disclaimer

**Comment by bsdimp** [comment]
+1 to include. Agree on analysis and like @swinslow 's name.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

HPND sell variant with MIT disclaimer

## License ID

HPND-sell-variant-MIT-disclaimer

## XML markup

none

## Notes:

This license is comprised of parts of the permission language from HPND-sell-variant  and the disclaimer from MIT.

## Additional rationale or notes on decision:
none
