### ISSUE TITLE
New license request: HGL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by evgnomon** [spdx/license-list-XML#1790]
**1.** License Name: HGL General License
**2.** Short identifier: HGL
**3.** License Author or steward: Hamed Ghasemzadeh
**4.** Comments: The license is designed to be a short FREE software license. No other license is matching it.
It applies to code and makes sure the free status is left via distributions.
The license has been in review for a year and it has been stable for a while so we have started to use the software on our code bases. It is designed to be stable and unchanged without being dependent to specific authority.
The license is structured to be generally usable by anyone. It is not specific to one project, consortium or corporation.
The license is going to be used first by a free platform as a service maintained by Clusterlean AB (registered in Sweden).
**5.** License Request Url: http://tools.spdx.org/app/license_requests/205
**6.** URL(s): https://evgnomon.org/hgl/
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/clusterlean/

**Comment by richardfontana** [comment]
Hi, so this is a license you have drafted and the only example of its being used by anyone is a project that hasn't been released yet?

**Comment by richardfontana** [comment]
This (along with some other recent license requests) has motivated me to post the following:
https://lists.spdx.org/g/Spdx-legal/message/3306

**Comment by evgnomon** [comment]
@richardfontana All free software projects are significant since they solve problems for the author(s) and those that have the same needs. There could be a free licensed project which is not distributed yet. And distribution does not mean distribution on internet either.

@richardfontana promoting SPDX list by only adding popular licences does not help many free software distributors/users. And popular licenses do not need to be in SPDX either!

**Comment by richardfontana** [comment]
@evgnomon I do not think SPDX should be a registry only of popular licenses, but it should restrict itself to licenses actually in wide use. That could mean use on a small amount of code in one library or package that is widely included in several distributions or products for example. If you look at the licenses I have recently submitted to SPDX, most if not all of them could never be considered popular. But they are licenses that are actually encountered. If you can get your license adopted by others, or if you use it for some software that gets widely used by others, at that point it may become appropriate for your license to be added to the SPDX license list. If I understand correctly, your license isn't even used by you currently.

**Comment by swinslow** [comment]
@evgnomon Echoing @richardfontana's comments, [the purpose of the SPDX License List](https://github.com/spdx/license-list-XML/blob/main/DOCS/faq.md#what-is-the-spdx-license-list) is to be "a list of commonly found licenses and exceptions used in free and open or collaborative software, data, hardware, or documentation."

For brand new licenses for which there is little or no evidence of current usage, you are welcome to seek to encourage others to use your license and to get broad adoption. But the purpose of the SPDX License List is to reflect commonly- or broadly-used licenses in open collaborative development, not as a promotional list of newly-drafted licenses that do not have such usage.

I'm not in favor of adding the license at this time. You are of course welcome to resubmit the license for consideration at some point in the future if you have seen significantly broader community uptake of it.
