### ISSUE TITLE
New license request: Google WebM Additional IP Rights Grant (Patents)

### ISSUE THREAD

**Issue by BrianInglis** [spdx/license-list-XML#1798]
1. License Name: Google WebM Additional IP Rights Grant (Patents)
2. Short identifier: WebM-Rights
3. License Author or steward: Google WebM Project
4. Comments: Google [WebM](https://www.webmproject.org/) https://www.webmproject.org/ software including *WebP*/`libwebp` is [licensed](https://www.webmproject.org/license/) https://www.webmproject.org/license/ as *BSD-3-Clause* [licence](https://www.webmproject.org/license/software/) https://www.webmproject.org/license/software/ with an [Additional IP Rights Grant (Patents)](https://www.webmproject.org/license/additional/) https://www.webmproject.org/license/additional/
Currently using `SPDX-License-Identifier: BSD-3-Clause AND LicenseRef-Google-WebM-Additional-IP-Rights-Grant-Patents` but maybe `WITH ExceptionRef-Google-WebM-Additional-IP-Rights-Grant-Patents` would fit better if not tied to *GNU* variant model? 
6. License Request Url: 
7. URL(s): https://www.webmproject.org/license/additional/ https://www.webmproject.org/license/software/ https://www.webmproject.org/license/
8. OSI Status: Not Submitted
9. Example Projects: https://www.webmproject.org/ https://www.webmproject.org/code/ https://developers.google.com/speed/webp/ https://chromium.googlesource.com/webm/libwebp 
10. FSF Free/Libre: 
11. Full Text: Additional IP Rights Grant (Patents)
"These implementations" means the copyrightable works that implement the WebM codecs distributed by Google as part of the WebM Project.
Google hereby grants to you a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, transfer, and otherwise run, modify and propagate the contents of these implementations of WebM, where such license applies only to those patent claims, both currently owned by Google and acquired in the future, licensable by Google that are necessarily infringed by these implementations of WebM. This grant does not include claims that would be infringed only as a consequence of further modification of these implementations. If you or your agent or exclusive licensee institute or order or agree to the institution of patent litigation or any other patent enforcement activity against any entity (including a cross-claim or counterclaim in a lawsuit) alleging that any of these implementations of WebM or any code incorporated within any of these implementations of WebM constitutes direct or contributory patent infringement, or inducement of patent infringement, then any patent rights granted to you under this License for these implementations of WebM shall terminate as of the date such litigation is filed.

12. Standard License Header: Additional IP Rights Grant (Patents)

**Comment by richardfontana** [comment]
Cf.: https://github.com/spdx/license-list-XML/issues/1651

**Comment by BrianInglis** [comment]
All the previous Google patent rights grant issues have been closed with no action or decision because some Google lawyer did not respond. It's not Google's problem if they have have 3 different grants they don't want to decide anything about. You can not hold your own processes up, hoping someone in a different company is interested in making a decision and conveying that back to you, when it is a waste of their time even discussing it. 
As with #1651 SPDX needs to decide how you want to handle them - as licences, exceptions, or some new entity, label them or close them and move on. 
And as with US/Government department Public Domain grants/licences etc. if you don't decide now, that's fine, we just keep our own local labels, until someone with a bigger stake comes along later with the exact same issues.

**Comment by jlovejoy** [comment]
Discussed on March 23, 2023 legal call: discussed whether SPDX License List should include purely patent licenses, which it does not so far.
Consensus on call to add as one license in combination with the BSD-3-Clause license - e.g. BSD-3-Clause-WebM that combines the two license texts
@swinslow to reach out to Google to give a chance to weigh in

**Comment by BrianInglis** [comment]
Great! 
I will be glad to drop my ...`AND LicenseRef-Google-WebM-Additional-IP-Rights-Grant-Patents` qualifier, which annoys our/(your?) package verifier (but "passes" with complaints). 
Don't wait too long for Google: you closed #646 after waiting three years! 
Perhaps have someone convey to them, if they became members, what their monthly commitment would be in hours, if they only participated in relevant legal calls, and read the relevant background. 
And that, if they choose not to (get their legal group to) actively participate, we will all be making our own decisions about how to represent their products and licences in software BoM and supply chains.

**Comment by jlovejoy** [comment]
discussed (again) on 6/22 call: looking more closely at this in light of our now articulated exception guidelines, we agreed this doesn't not really meet those. Specifically it doesn't fit squarely in either of the two aspects of (2). It was also noted that these kinds of patent licenses seemed to have a period of popularity, but that has waned (in relation to substantial use) and Google, in particular, has stopped using this.

it was also acknowledged that the addition of the option to use `AdditionRef-` (for SPDX spec 3.0 release) in license expressions provides a more concise way to potentially capture this kind of thing.

**Comment by jlovejoy** [comment]
@BrianInglis - sorry for all the back and forth on this. In case you didn't follow the AdditionRef conversation:
Currently the SPDX spec provide `LicenseRef-` as a way to identify licenses not on the SPDX License List. But if you have, say, a license that is on the SPDX License List with exception-like additional text, you could not use:
`BSD-3-Clause WITH LicenseRef-xyz` but would have to represent the entire thing with a `LicenseRef-BSD-xyz` and capture the entirety of the text in the field for that in your SPDX doc.

As of 3.0, you will be able to use:
``BSD-3-Clause WITH AdditionRef-xyz` to represent a license on the SPDX License List modified by some other text with no definition on how it modifies the original license.

Hope that helps a little!
