### ISSUE TITLE
W3C BSD-3-Clause variant

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1827]
Not sure if this one can be accommodated by a markup change to BSD-3-Clause:

 ```
# W3C 3-clause BSD License

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

*    Redistributions of works must retain the original copyright notice, this list of conditions and the following disclaimer.
*    Redistributions in binary form must reproduce the original copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
*    Neither the name of the W3C nor the names of its contributors may be used to endorse or promote products derived from this work without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```
https://github.com/web-platform-tests/wpt/blob/e4860d02963ec4922de464b508eb1cf1c1aef27d/LICENSE.md#w3c-3-clause-bsd-license

https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html

As far as I can tell, these are the only differences relative to BSD-3-Clause:
* "source code" > "works" in clause 1
* "above copyright notice" > "original copyright notice" in clause 1 and clause 2

A web search shows considerable evidence of the wide downstream use of this license, though it seems the W3C may at least implicitly have deprecated it sometime in the past few years. ~I have not been able to confirm that it is found in any Fedora package.~ I first encountered it in an older version of the Node.js npm package abab:
https://github.com/jsdom/abab/blob/9a7867331d4346c806bd1355f45dbbbd2f832472/LICENSE.md
(note that this project has recently changed the license to something that clearly matches BSD-3-Clause)

**Comment by richardfontana** [comment]
Update: the license is found in the source code of at least one current Fedora package, nodejs (upstream: 
https://github.com/nodejs/node/blob/main/test/fixtures/wpt/resources/LICENSE )

**Comment by jlovejoy** [comment]
this seems like a reasonable markup addition

**Comment by Pizza-Ria** [comment]
I considered whether "above" and "original" could reach a different result (in the case of multiple constributions with add-on (c) statements) but I doubt that was the intent behind that choice of language.  I liked the comment that one of the files this was found in had changed to a known form of BSD.  This is an excellent practice for anything still in active development (although it doesn't solve past versions under the variant licenses).  Anyway, I'm a practically-focused +1 for the markup.

**Comment by copernicat** [comment]
+1 after our discussion in the 5/25/23 legal work group call
