### ISSUE TITLE
New license request: NIST-generic-rng [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by beldmit** [spdx/license-list-XML#1836]
**1.** License Name: Some generic NIST license
**2.** Short identifier: NIST-generic-rng
**3.** License Author or steward: NIST
**4.** Comments: The submitted license must not match another license already on the SPDX License List as per the SPDX matching guidelines.
The license has identifiable and stable text; it is not in the midst of drafting.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/207
**6.** URL(s): https://github.com/open-quantum-safe/liboqs/blob/40b01fdbb270f8614fde30e65d30e9da18c02393/src/common/rand/rand_nist.c#L1-L15
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/open-quantum-safe/liboqs/

**Comment by richardfontana** [comment]
@jlovejoy it is not included in Fedora - it is a package that has been proposed for Fedora. I believe it has not yet been approved for inclusion in Fedora based on technical criteria and it has not yet been approved for inclusion in Fedora based on legal criteria. In all likelihood if it is *not* approved for Fedora, it won't be because of this license, but I think that is all we can say. I believe it may already be in Debian though :)

**Comment by jlovejoy** [comment]
allowed for Fedora as per https://gitlab.com/fedora/legal/fedora-license-data/-/issues/157#note_1282536878

**Comment by jlovejoy** [comment]
I think this is fine to add. It does include the following sentence at the end:
"This software is not intended to be used in any situation where a failure could cause risk of injury or damage to property."
But given it's stated as "not intended to be used" - I don't interpret this as a restriction on a field of use, but more of a warning.

I find this last sentence interesting: "The software developed by NIST employees is not subject to copyright protection within the United States." - I guess the implication is that if you are in the US, you don't need a license b/c it's not copyrighted, but if you are outside of the US, then see license above??

**Comment by richardfontana** [comment]
I see the "not intended" language in this case as a badly-formulated liability disclaimer. There are a number of licenses in Fedora that have similar language. 

As for the sentence about NIST, I don't think we can assume that the software was authored entirely by NIST employees.

**Comment by jlovejoy** [comment]
@swinslow @bsdimp - care to weigh in here :)

**Comment by bsdimp** [comment]
+1 it's permissive enough and not the only license that could be drafted better...

**Comment by swinslow** [comment]
Here's the specific language so we can see it in this thread:

> NIST-developed software is provided by NIST as a public service. You may use, copy, and distribute copies of the software in any medium, provided that you keep intact this entire notice. You may improve, modify, and create derivative works of the software or any portion of the software, and you may copy and distribute such modifications or works. Modified works should carry a notice stating that you changed the software and should note the date and nature of any such change. Please explicitly acknowledge the National Institute of Standards and Technology as the source of the software.
> 
> NIST-developed software is expressly provided "AS IS." NIST MAKES NO WARRANTY OF ANY KIND, EXPRESS, IMPLIED, IN FACT, OR ARISING BY OPERATION OF LAW, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND DATA ACCURACY. NIST NEITHER REPRESENTS NOR WARRANTS THAT THE OPERATION OF THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE, OR THAT ANY DEFECTS WILL BE CORRECTED. NIST DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OF THE SOFTWARE OR THE RESULTS THEREOF, INCLUDING BUT NOT LIMITED TO THE CORRECTNESS, ACCURACY, RELIABILITY, OR USEFULNESS OF THE SOFTWARE.
> 
> You are solely responsible for determining the appropriateness of using and distributing the software and you assume all risks associated with its use, including but not limited to the risks and costs of program errors, compliance with applicable laws, damage to or loss of data, programs or equipment, and the unavailability or interruption of operation. This software is not intended to be used in any situation where a failure could cause risk of injury or damage to property. The software developed by NIST employees is not subject to copyright protection within the United States.

@jlovejoy agreed on the two last sentences. "not intended to be used" I see as a general statement about the intended purpose of use of the software (and/or potentially a warranty or liability disclaimer as @richardfontana said), and not a limitation on rights to use the software.

The "not subject to copyright protection within the United States" bit I think is related to where various US government agencies have struggled to figure out how best to articulate that some parts of the software may not be subject to copyright in the US per 17 USC 105, so they don't want to imply that a license is required for those parts. I think this is harmless here for our purposes.

Overall I'm +1 to add for the reasons stated above.

For name and ID, I note that this appears to be a more general NIST licensing statement: see https://www.nist.gov/open/copyright-fair-use-and-licensing-statements-srd-data-software-and-technical-series-publications#software. I'd be inclined not to include 'rng' in the name, and to go with something more like:

Name: NIST Software License
ID: `NIST-Software`

Of course it isn't versioned, unfortunately, but I don't think we should create a version number or date where the steward (NIST) hasn't indicated anything along those lines.

**Comment by jlovejoy** [comment]
@beldmit - could you make a PR for this, as per https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process ?

Thanks for your patience!

**Comment by jlovejoy** [comment]
nevermind @beldmit - I took care of it already!
