### ISSUE TITLE
Support "aliases" for existing license types

### ISSUE THREAD

**Issue by lkoskela** [spdx/license-list-XML#1837]
I stumbled on some third-party libraries* that had "EDL-1.0" on them, which turns out to be the Eclipse Distribution License v1.0 that's not found from SPDX's license list so I tried to submit it through the [SPDX online tool](https://tools.spdx.org/app/license_requests/) but the form rejects it based on the license text being essentially identical to BSD-3-Clause.

I get the point of "duplicates" bloating the index but then again, people do use/refer to licenses from established bodies like the Eclipse Foundation and license identifiers not found from the SPDX force me to maintain a private index of these "unknown" licenses to keep my automation scripts happy :) so I'm wondering if some kind of an "alias" system would be an acceptable compromise for tracking these "license X is really a copy of license Y" cases without bloating the SPDX License List too much?

If not, please consider overriding the duplication check on a case by case basis and add EDL-1.0 to the index?

*) At least [Eclipse LSP4J](https://projects.eclipse.org/projects/technology.lsp4j), [Eclipse Advanced Visualization Project](https://projects.eclipse.org/projects/science.eavp), and [turf-jsts](https://www.npmjs.com/package/turf-jsts) use EDL-1.0

**Comment by zvr** [comment]
This comes up from time to time...

It has been discussed and resolved in the past. To the point that:

- the [SPDX page for BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) has a note explicitly mentioning Eclipse Distribution License
- the [Eclipse page for EDL-1.0](https://www.eclipse.org/org/documents/edl-v10.php) explicitly writes that its SPDX identifier is  `BSD-3-Clause`

**Comment by lkoskela** [comment]
> the [SPDX page for BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html) has a note explicitly mentioning Eclipse Distribution License

That's exactly the information I'd like to have – but in a machine-readable format as part of the data files.

In the case of EDL-1.0, even though it's plainly readable for a human, when my script comes across a license marked as `EDL-1.0`, it would have to do a lot of questionably reliable regex matching and website crawling and fuzzy license text matching to conclude that `EDL-1.0` is indeed equivalent to `BSD-3-Clause`.

```json
{
  ...
  "licenseComments": "Note that the Eclipse Distribution License - v 1.0 (EDL 1.0) is a match to BSD-3-Clause, even though it uses a different name.",
  "licenseId": "BSD-3-Clause",
  "crossRef": [
    {
      "match": "N/A",
      "url": "https://opensource.org/licenses/BSD-3-Clause",
      "isValid": true,
      "isLive": false,
      "timestamp": "2023-02-14T14:31:36Z",
      "isWayBackLink": false,
      "order": 0
    },
    {
      "match": "false",
      "url": "https://www.eclipse.org/org/documents/edl-v10.php",
      "isValid": true,
      "isLive": true,
      "timestamp": "2023-02-14T14:31:36Z",
      "isWayBackLink": false,
      "order": 1
    }
  ],
  "seeAlso": [
    "https://opensource.org/licenses/BSD-3-Clause",
    "https://www.eclipse.org/org/documents/edl-v10.php"
  ],
  ...
}
```

If, for example, the above `crossRef` entry for EDL-1.0 would include something like `{ "rel": "identical", "licenseIdentifier": "EDL-1.0", "name": "Eclipse Distribution License - v 1.0" }`, that'd be much easier to navigate programmatically (and much more reliable, too).

I guess I'm saying, the information is there already so why not make it structured?

But yeah, I hear that this is a dead horse and has been resolved in the past. Just wanted to provide my point of view in case the prior discussion hasn't taken place with the automation aspect in mind (for which I now have a local list of "aliases" – and would have anyway because people aren't going to stop making typos and making up their custom licenses 😄).

**Comment by zvr** [comment]
The upstream should be fixed and use the correct `BSD-3-Clause` instead of the string "EDL-1.0" which is not supported or recommended by anyone (nor SPDX nor Eclipse).

**Comment by lkoskela** [comment]
👍

**Comment by jlovejoy** [comment]
+100 with what @zvr said above

it's also my observation that this is a somewhat rare or corner case. creating more tags to track something that doesn't happen that often and then requires another aspect of verification, tracking, documentation, etc. - not sure that adds a lot of value. Just use the pre-existing SPDX id...  that's what they were made for starting in 2010... :)

**Comment by jlovejoy** [comment]
@lkoskela - ok if I close this issue then?

**Comment by lkoskela** [comment]
Sure.
