### ISSUE TITLE
New exception: Autoconf macro exception

### ISSUE THREAD

**Issue by ppisar** [spdx/license-list-XML#1849]
<https://github.com/freedesktop/xorg-macros/blob/39f07f7db58ebbf3dcb64a2bf9098ed5cf3d1223/xorg-macros.m4.in#L1260>, also found in <https://www.x.org/releases/individual/app/xgamma-1.0.7.tar.xz>, uses an exception from GPL-3.0-or-later:

~~~~
As a special exception, the respective Autoconf Macro's copyright owner
gives unlimited permission to copy, distribute and modify the configure
scripts that are the output of Autoconf when processing the Macro. You
need not follow the terms of the GNU General Public License when using
or distributing such scripts, even though portions of the text of the
Macro appear in them. The GNU General Public License (GPL) does govern
all other use of the material that constitutes the Autoconf Macro.

This special exception to the GPL applies to versions of the Autoconf
Macro released by the Autoconf Archive. When you make and distribute a
modified version of the Autoconf Macro, you may extend this special
exception to the GPL to apply to your modified version as well.
~~~~

This exception looks distinct from <https://spdx.org/licenses/Autoconf-exception-2.0.html>.

It has already been approved for Fedora <https://gitlab.com/fedora/legal/fedora-license-data/-/issues/161>.

I need to add this exception to SPDX exception list and to determine an identifier. I propose "Autoconf macro exception" name.

**Comment by swinslow** [comment]
+1 to add. This one is a straightforward license exception, conceptually similar to the other Autoconf exceptions currently on the license list, but uses different language, in particular by applying to "the output of Autoconf _when processing the Macro_." It does not match to anything currently on the exceptions list as far as I can tell.

It appears to be used broadly, from a few quick searches including in at least one [Ubuntu package](https://launchpad.net/ubuntu/precise/+source/xmltooling/+copyright) and in [the GNU Autoconf software itself](https://www.gnu.org/software/autoconf-archive/ax_pthread.html).

@jlovejoy @copernicat @bsdimp and others, can we get a few additional +1's and mark this as approved?

**Comment by swinslow** [comment]
I would tend to agree with the proposed naming, with a slight tweak to align with naming for some of the other Autoconf exceptions:

Name: Autoconf macro exception
ID: `Autoconf-exception-macro`

**Comment by copernicat** [comment]
I agree with @swinslow 's assessment and short ID proposal, +1

**Comment by jlovejoy** [comment]
+1 to add as well. Thanks for the research @swinslow !

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Autoconf macro exception

## License ID

Autoconf-exception-macro

## XML markup

none needed at this point

## Notes:

"This exception is conceptually similar to the other Autoconf exceptions, but removes the language related to data portions and refers specifically to the Macro.

## Additional rationale or notes on decision:

N/A

**Comment by jlovejoy** [comment]
@swinslow - I tried to add a Note, as I thought that would be helpful, but... would appreciate your input on substance.

@ppisar - do you want to have a go at making the XML and .txt files for this? You won't be able to use the online tool, but as this is an exception, your easiest bet is to copy the pattern from one of the existing XML files for an exception :)
https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md

:)

**Comment by swinslow** [comment]
Thank you @ppisar! (And thanks @copernicat and @jlovejoy for the +1's)

The CI checks have passed, so I'm merging #1850. Thanks for the help in getting this one done quickly.
