### ISSUE TITLE
New license request: Unicode-TOU-2023

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1851]
(to be determined whether 2023, or an earlier year, is the correct one to use; should perhaps check web.archive.org to validate when the terms changed to this current version)

This is following from the discussion on the spdx-legal mailing list at https://lists.spdx.org/g/Spdx-legal/topic/97116566

In light of the discussion there, I would propose adding a new identifier `Unicode-TOU-2023`, name "Unicode Terms of Use - 2023", with the terms currently at https://www.unicode.org/copyright.html.

This is the current updated set of terms for certain material from Unicode. An earlier version of these terms is currently on the SPDX License List at [`Unicode-TOU`](https://spdx.org/licenses/Unicode-TOU.html).

I have not yet investigated this further beyond the mailing list discussion, though given the nature of the Unicode Consortium and the current entry `Unicode-TOU` already being on the License List, I think it's likely that the updated set of terms are going to be appropriate to add.

**Comment by jlovejoy** [comment]
@swinslow - I made a PR for adding the various URLs that you and Till found at #1918 

As for adding this as a new license, I'd agree that it is different enough from https://spdx.org/licenses/Unicode-TOU.html: some of the changes are really minor, but this newer version omits the phrase, "solely for informational purposes in the creation of products supporting the Unicode Standard," in clause 3 

Given we have the other Unicode licenses, I'm +1 to add (just wish they'd version their licenses and stop using the same URL!!)

**Comment by swinslow** [comment]
Thanks @jlovejoy! I've merged the PR with the additional URLs for the two existing Unicode licenses.

**Comment by jlovejoy** [comment]
closing this as the remaining question as to adding the more recent version of the Unicode license at https://www.unicode.org/license.txt is also raised in #2105 making this duplicative
