### ISSUE TITLE
New license request: UnixCrypt

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1854]
### Introduction

Simple, permissive and historical license, apparently used in early Unix crypt utility.

Terms are very close to the [ISC license](https://spdx.org/licenses/ISC.html), with the following changes:
* "for non-commercial or commercial purposes" instead of "for any purpose"
* "without fee" instead of "with or without fee"
* requires retention of "this copyright notice" rather than "the above copyright notice and this permission notice"
* does not contain the second paragraph with the all-caps disclaimer language

Is open source, historical, believe it to be widely used given the reference to the Unix crypt utility. Is also used in at least one current Python library (passlib, see below) and in projects such as JBoss and Jetty.

### License Name

UnixCrypt License

### Suggested short identifier

UnixCrypt

### URL to license text

http://web.archive.org/web/20020702043523/http://www.dynamic.net.au/christos/crypt/UnixCrypt2.txt

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

* https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/LICENSE#L70
* https://opensource.apple.com/source/JBoss/JBoss-737/jboss-all/jetty/src/main/org/mortbay/util/UnixCrypt.java.auto.html
* https://archive.eclipse.org/jetty/8.0.1.v20110908/xref/org/eclipse/jetty/http/security/UnixCrypt.html

**Comment by swinslow** [comment]
License text:

```
Copyright (c) 1996 Aki Yoshida. All rights reserved.

Permission to use, copy, modify and distribute this software
for non-commercial or commercial purposes and without fee is
hereby granted provided that this copyright notice appears in
all copies.
```

**Comment by richardfontana** [comment]
Verified that this license is in the currently-maintained Fedora packages python3-passlib and jetty.

**Comment by jlovejoy** [comment]
+1 to add as it is very permissive and used in a major distro

@copernicat @bsdimp - can we get another vote here?

**Comment by copernicat** [comment]
+1 I agree with the analysis

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

UnixCrypt License

## License ID

UnixCrypt

## XML markup

none

## Notes:

N/A

**Comment by jlovejoy** [comment]
see in Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/87
