### ISSUE TITLE
BSD-2-Clause variant: "THIS" in disclaimer without "SOFTWARE"

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1857]
```
Copyright (c) Felix Böhm
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Source: https://github.com/fb55/nth-check/blob/master/LICENSE
https://www.npmjs.com/package/nth-check
I do not believe this project is packaged in Fedora. I don't know if the license occurs elsewhere.

**Comment by swinslow** [comment]
Looks like this could be accommodated by changing the XML markup to make "SOFTWARE" optional, in the phrase "THIS SOFTWARE" both at the beginning and near the end of the disclaimer paragraph in [BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause.html).

I'm +1 to making this change. @jlovejoy @bsdimp @copernicat @Pizza-Ria @seabass-labrax can we get a couple of additional +1's?

**Comment by copernicat** [comment]
I double-checked the diffs and I agree, @swinslow. +1 to your solution.

**Comment by bsdimp** [comment]
I agree. THIS is dangling, but means, to my layman's mind, substantially the same thing.
+1 to fix this with markup.

**Comment by swinslow** [comment]
Thank you @copernicat and @bsdimp! I have a few minutes free now so I'll go ahead and submit a PR to address this.
