### ISSUE TITLE
Latest release of licenses.json is not accessible via a permalink

### ISSUE THREAD

**Issue by ssbarnea** [spdx/license-list-XML#1859]
The web page from https://spdx.org/licenses/ does only link to github repository containing the machine readable formats (like json), but it is impossible to retrieve the last release of the licenses.

At this moment the repository is updated to often (daily) even if no real changes are made.

This issue can be sorted in at least two ways:

- Add a "latest" mobile tag as part of github release pipeline, so people can have a permalink using github
- Publish the machine readable files to a website such https://spdx.org so people can load the last release from there.

**Comment by goneall** [comment]
@ssbarnea The JSON files are published to https://spdx.org.  A summary list of all licenses can be found at [https://spdx.org/licenses/licenses.json](https://spdx.org/licenses/licenses.json).  Details for an individual license can be found at https://[license-id].json where [license-id] is the license ID for the license.

You can also extract machine readable RDF data from the HTML using RDFa.  It follows the ontology defined at [https://spdx.org/rdf/terms](https://spdx.org/rdf/terms).

Also note that the releases in the data repository are tagged by release.

Let us know if this solves the problem or if there is a different machine readable format you would like to see published.
