### ISSUE TITLE
New license request: Widget [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1860]
**1.** License Name: Widget Workshop license
**2.** Short identifier: Widget
**3.** License Author or steward: Unknown
**4.** Comments: This is a legacy permissive license that is found today in at least one Fedora package, novnc; the upstream project is also distributed through NPM.

This license formerly appeared in the (now deprecated) Fedora wiki in a page collecting various licenses associated with the Fedora name "MIT", under the name "Nuclear Variant": https://fedoraproject.org/wiki/Licensing:MIT#Nuclear_Variant
I think there was an effort by SPDX to add some of the licenses listed here but I don't think this one was one of them.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/208
**6.** URL(s): https://github.com/novnc/noVNC/blob/master/core/crypto/des.js#L24
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/novnc/noVNC

**Comment by jlovejoy** [comment]
@richardfontana - is there a corresponding Fedora issue we can link to?

**Comment by richardfontana** [comment]
No, because this didn't come out of a Fedora-related activity. I can make one, though, since this license does occur in a Fedora package.

**Comment by jlovejoy** [comment]
@richardfontana - I'm not sure I gave that previous comment a thumbs up, it should have been a scratching-my-head emoticon! In any case, if it occurs in Fedora, then we can appropriately use the "used in major distro" label?

**Comment by richardfontana** [comment]
Since SPDX has been treating anything in Fedora as "used in a major distro", I think you can appropriately use that label here.

**Comment by jlovejoy** [comment]
+1 to add - it's a permissive license with a disclaimer that includes a note that it is "NOT DESIGNED OR INTENDED FOR USE OR RESALE..." - I don't see this as a restriction b/c it doesn't say it can't be used for those things, but is more of a specific disclaimer that it isn't made for that

**Comment by swinslow** [comment]
License text:

Copyright (c) 1996 Widget Workshop, Inc. All Rights Reserved.

Permission to use, copy, modify, and distribute this software
and its documentation for NON-COMMERCIAL or COMMERCIAL purposes and
without fee is hereby granted, provided that this copyright notice is kept
intact.

WIDGET WORKSHOP MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY
OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WIDGET WORKSHOP SHALL NOT BE LIABLE
FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.

THIS SOFTWARE IS NOT DESIGNED OR INTENDED FOR USE OR RESALE AS ON-LINE
CONTROL EQUIPMENT IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE
PERFORMANCE, SUCH AS IN THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, DIRECT LIFE
SUPPORT MACHINES, OR WEAPONS SYSTEMS, IN WHICH THE FAILURE OF THE
SOFTWARE COULD LEAD DIRECTLY TO DEATH, PERSONAL INJURY, OR SEVERE
PHYSICAL OR ENVIRONMENTAL DAMAGE ("HIGH RISK ACTIVITIES").  WIDGET WORKSHOP
SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY OF FITNESS FOR
HIGH RISK ACTIVITIES.

**Comment by swinslow** [comment]
+1 to add, for the reasons @jlovejoy described above.

I agree that the last paragraph is framed not as a restriction on use but rather a statement of intended purposes (or intended non-purposes, I suppose). Curiously, the language is similar to [section 10.0 of RPL-1.5](https://spdx.org/licenses/RPL-1.5.html). Not identical, so I wouldn't reference it in notes or anything; but interesting that these provisions seem to have some sort of common ancestry, and also it's a point of precedence for including provisions like these in licenses on the list.

Good with "Widget Workshop license" as the name; I'd probably suggest `Widget-Workshop` as the ID, solely to align with the original licensor's actual name. Any concerns with that?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Widget Workshop License

## License ID

Widget-Workshop

## XML markup

none

## Notes:

none

**Comment by jlovejoy** [comment]
@richardfontana - want to give a go at making the files for this one?  :)
