### ISSUE TITLE
New license request: Metamail license

### ISSUE THREAD

**Issue by jplesnik** [spdx/license-list-XML#1863]
### Introduction

I found this license in perl-MIME-Base64:

  Copyright (c) 1991 Bell Communications Research, Inc. (Bellcore)
  Permission to use, copy, modify, and distribute this material
  for any purpose and without fee is hereby granted, provided
  that the above copyright notice and this permission notice
  appear in all copies, and that the name of Bellcore not be
  used in advertising or publicity pertaining to this
  material without the specific, prior written permission
  of an authorized representative of Bellcore.	BELLCORE
  MAKES NO REPRESENTATIONS ABOUT THE ACCURACY OR SUITABILITY
  OF THIS MATERIAL FOR ANY PURPOSE.  IT IS PROVIDED "AS IS",
  WITHOUT ANY EXPRESS OR IMPLIED WARRANTIES.

It's possible that either this license is treatable as SPDX "HPND" as-is 

More details: https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/WZ6PE2OWTYFPWDNZVG4VNAZZJPT5BVIN/

### License Name

 Bellcore license

### URL to license text

https://github.com/Dual-Life/mime-base64/blob/master/Base64.xs#L12

### OSI Status

I don't know

### URL to project(s) that use license

Fedora rpm perl-MIME-Base64 - https://github.com/Dual-Life/mime-base64
Fedora rpm perl-MIME-Base64 as a sub-package of 'perl' -  https://metacpan.org/release/RJBS/perl-5.36.0/source/cpan/MIME-Base64/

**Comment by jlovejoy** [comment]
I'm +1 to add this as a new license. After reviewing the various HPND variants, it has some similarities, but is different enough that it could not be easily accommodate with more markup to those. It's clearly permissive and found in Fedora, so meets the inclusion guidelines.

I'm not sure about naming though - should we go with Bellcore or MIME-base64 as part of the id/name?

@richardfontana - do you have opinions here? :)

**Comment by richardfontana** [comment]
It is not the main licnse of MIME-base64. It apparently comes from metamail, which someone has preserved here: https://github.com/joelklabo/metamail (I didn't check closely to see if the license is the same, but it looks like it is).

So I'd suggest naming it "**metamail**". There could be other, different legacy licenses out there with Bellcore as the copyright holder.

**Comment by swinslow** [comment]
+1 to adding, and fine with "metamail License" as name and `metamail` as the ID.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

metamail License

## License ID

metamail

## XML markup

None - current usage appears to be specific to this license text and Bellcore as licensor

## Notes:

N/A

## Additional rationale or notes on decision:

simple / historical permissive license notice, used in major distro

**Comment by jlovejoy** [comment]
@jplesnik - could you make the PR to add the files for this now that it's been accepted?
