### ISSUE TITLE
New license request: vsftpd-openssl-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1870]
**1.** License Name: vsftpd OpenSSL exception
**2.** Short identifier: vsftpd-openssl-exception
**3.** License Author or steward: Unknown
**4.** Comments: another OpenSSL exception variation that we missed in the analysis previously
**5.** License Request Url: http://tools.spdx.org/app/license_requests/210
**6.** URL(s): https://git.stg.centos.org/source-git/vsftpd/blob/f727873674d9c9cd7afcae6677aa782eb54c8362/f/LICENSE, https://launchpad.net/debian/squeeze/+source/vsftpd/+copyright, https://github.com/richardcochran/vsftpd/blob/master/COPYING
**7.** OSI Status: Unknown
**8.** Example Projects: https://git.stg.centos.org/source-git/vsftpd/blob/f727873674d9c9cd7afcae6677aa782eb54c8362/f/LICENSE

**Comment by jlovejoy** [comment]
@riklescak and @lal12 - FYI

**Comment by jlovejoy** [comment]
Looks like this is present in CentOS and Ubuntu, which doesn't exactly meet our "major distro" criteria, but certainly "adjacent"

In any case, I'm +1 to add

Can I get a few others to weigh in? @richardfontana @swinslow @copernicat @bsdimp ?

**Comment by richardfontana** [comment]
This is also in Fedora https://src.fedoraproject.org/rpms/vsftpd

**Comment by copernicat** [comment]
+1 because of its presence in several Linux distributions

**Comment by richardfontana** [comment]
@jlovejoy Side comment, I am curious why CentOS and Ubuntu wouldn't meet the criteria for a major distro. Considered together, RHEL/CentOS Linux/CentOS Stream is one of the most widely used commercial Linux distributions; of course relatively few packages in it are not also in Fedora since it is derived from Fedora. Ubuntu is also one of the most widely used Linux distributions, both commercially and otherwise; though similarly, I assume relatively few Ubuntu packages are not also in Debian.

**Comment by jlovejoy** [comment]
@richardfontana - the "major distro" label was created when we updated the approval process that licenses in Fedora or Debian only needed 2 SPDX legal team members approval to add, versus 3. https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#review-process

The rationale for starting with Fedora and Debian was that both have their own license criteria. I think it was discussed that we might add more in the future.

**Comment by jlovejoy** [comment]
@swinslow - I think usually exceptions start with the permission part, not the statement as to GPL, etc.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

vsftpd OpenSSL exception

## License ID

vsftpd-openssl-exception

## XML markup

markup for project name is probably a good idea

## Notes:

_add any information that is to be included in the Notes field_

## Additional rationale or notes on decision:

_add any additional information, including optionally a summary of what is recorded in the issue comments_
