### ISSUE TITLE
New license request: TermReadKey [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jplesnik** [spdx/license-list-XML#1875]
**1.** License Name: None
**2.** Short identifier: None
**3.** License Author or steward: Unknown
**4.** Comments: I found this license in  Perl module TermReadKey.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/211
**6.** URL(s): https://github.com/jonathanstowe/TermReadKey/blob/master/README#L9-L10
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/jonathanstowe/TermReadKey

**Comment by swinslow** [comment]
Here is the requested license text:

> Unlimited distribution and/or modification is allowed as long as this copyright notice remains intact.

(I've changed the title of this issue to indicate that the name and ID is yet to be requested / determined, to avoid confusing this with the `NONE` keyword for the license syntax.)

**Comment by richardfontana** [comment]
Related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/173

**Comment by swinslow** [comment]
+1 to add as a simple / historical permissive short license notice, used in a major distro.

Probably would go with "TermReadKey License" as name and `TermReadKey` as ID since this appears to be the main component for which this particular notice is used.

**Comment by jlovejoy** [comment]
+1 to add as well

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

TermReadKey License

## License ID

TermReadKey

## XML markup

none
