### ISSUE TITLE
Update URLs for Educational Community License version 2.0

### ISSUE THREAD

**Issue by gjcoram** [spdx/license-list-XML#1876]
The page https://spdx.org/licenses/ECL-2.0.html says

Other web pages for this license
https://opensource.org/licenses/ECL-2.0 [no longer live] 

There's a new link:
https://opensource.org/license/ecl-2-0/
that is working (as of today ...)

However, in the Appendix to the actual license, there's a reference to
http://www.osedu.org/licenses/ECL-2.0
which is 404 Not Found.

I can't find an update for that link, and I don't know if OSEDU still "owns" the ECL.

**Comment by jlovejoy** [comment]
Thanks - the OSI links issue is a known issue and I believe they are working on it.
As for the old link giving a 404 - we have a policy to not remove those, as per https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md section C
