### ISSUE TITLE
New license request: Open Logistics Foundation License v1.3

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#1880]
_edited 2023-03-20 by @swinslow to update URLs_

### Introduction

This license was approved by OSI at its 2023-03-19 Board meeting, as posted at http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-March/005366.html

(Note that, although that particular thread indicated that the name was "Open Logistics License version 1.3", the preceding email thread included a [PDF summary](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/attachments/20230312/71254ca6/attachment-0001.pdf) which makes it clear that "Open Logistics Foundation License v1.3" was the name of the approved final license.)

As an OSI-approved license, it is by default approved for inclusion on the SPDX License List as described in the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md). However, we'll want to make sure there's agreement on the ID to use for the license.

### License Name

Open Logistics Foundation License v1.3

### Suggested short identifier

OLFL-1.3

### URL to license text

Corrected encoding: https://gist.github.com/marbre/86635347bf69315cfa84f32788bd80f0

_OSI approval version with incorrect encoding: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-January/005332.html_

### OSI Status

Approved

### License author or steward

Open Logistics Foundation

### URL to project(s) that use license

Not known, but irrelevant due to OSI approval

**Comment by swinslow** [comment]
A couple additional notes:

* The OSI license-review mailing list thread at http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-January/005332.html appears to include the v1.3 / approved version of the license. The Open Logistics Foundation still has the old (v1.0) version of their license on their website at https://openlogisticsfoundation.org/licenses/, but that version should _not_ be used as it was not the OSI-approved version.
* In that mailing list thread, the "bullets" for the main section numbering appear to use an encoding that got mangled by the mailing list software (e.g., `Â§1 Definitions`). We'll probably want to take a look at how the license is rendered elsewhere to see how this should be represented.

**Comment by swinslow** [comment]
@jlovejoy @bsdimp @copernicat and others, grateful for your thoughts on the license ID I proposed above. Once there's agreement on that, we can mark this as approved given the OSI approval. Thanks!

**Comment by bsdimp** [comment]
I'm agnostic on the name and +1 on inclusion even if it weren't osi approved, though it is a bit long and I don't have the chops to analyze it enough to see if there's a hidden poison pill. The intent seems right and osi approval dulls any lingering doubts.

**Comment by marbre** [comment]
@swinslow thank you for initiating the process to include the OLFL-1.3 in die SPDX License List.

> A couple additional notes:
> 
>     * The OSI license-review mailing list thread at http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-January/005332.html appears to include the v1.3 / approved version of the license. The Open Logistics Foundation still has the old (v1.0) version of their license on their website at https://openlogisticsfoundation.org/licenses/, but that version should _not_ be used as it was not the OSI-approved version.

The OSI-approved version should be available at https://openlogisticsfoundation.org/licenses/ soon, I'll drop a comment here as soon as it is.

>     * In that mailing list thread, the "bullets" for the main section numbering appear to use an encoding that got mangled by the mailing list software (e.g., `Â§1 Definitions`). We'll probably want to take a look at how the license is rendered elsewhere to see how this should be represented.

Indeed, the encoding got mangled somehow. The license that will be uploaded to https://openlogisticsfoundation.org/licenses/ will be rendered as in https://gist.github.com/marbre/86635347bf69315cfa84f32788bd80f0.

**Comment by marbre** [comment]
> The OSI-approved version should be available at https://openlogisticsfoundation.org/licenses/ soon, I'll drop a comment here as soon as it is.

The OLFL-1.3 is now available at https://openlogisticsfoundation.org/licenses/.

**Comment by jlovejoy** [comment]
+1 to add given our license inclusion guidelines state that all OSI-approved licenses will be added to the SPDX License List

short id seems sensible to me, @swinslow 

we just need to make sure that is communicated back to the OSI before they post it on their site, since I don't think we have a better process for that

**Comment by jlovejoy** [comment]
thanks for all the help here folks!
