### ISSUE TITLE
Small typo/formatting error in GPL-3.0-or-later license text

### ISSUE THREAD

**Issue by vmbrasseur** [spdx/license-list-XML#1884]
Hello, my SPDX friends! ❤️ 

I've found a small problem with the [text of GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html). Specifically, there should be a blank line before the paragraph starting "However" in section 8:

> 8. Termination.
You may not propagate or modify a covered work except as expressly provided under this License. Any attempt otherwise to propagate or modify it is void, and will automatically terminate your rights under this License (including any patent licenses granted under the third paragraph of section 11).
However, if you cease all violation of this License, then your license from a particular copyright holder is reinstated (a) provisionally, unless and until the copyright holder explicitly and finally terminates your license, and (b) permanently, if the copyright holder fails to notify you of the violation by some reasonable means prior to 60 days after the cessation.

You can see this blank line in [the license text on FSF](https://www.gnu.org/licenses/gpl-3.0.html).

Normally I'd send over a PR for this, but I'm in the middle of writing a chapter right now. I at least wanted to make sure the problem is tracked somewhere.

(oh, and I've not checked the license text for the other GPL-3.0 variants; may wanna do that)

**Comment by zvr** [comment]
Thanks, @vmbrasseur .

It's a missing `</p>`just before https://github.com/spdx/license-list-XML/blob/3dd06eff6b8278bd3cb3ff2f0460e6099b5fb69c/src/GPL-3.0-or-later.xml#L525

**Comment by jlovejoy** [comment]
@vmbrasseur !!!! good to see you back here!!  

I'll try to get a PR for this shortly. Happy writing!

**Comment by jlovejoy** [comment]
@zvr - I'm not sure there is a missing </p> tag, actually - that would mean there is a missing <p> or a lack of a pair somewhere, no?

**Comment by zvr** [comment]
Right.

In all numbered sections, we have not put the first paragraph inside `<p>` and `</p>`.

So, the issue that @vmbrasseur has reported ("no newline before However in section 8") actually occurs multiple times (e.g. "no newline before When in section 7", etc.).

The matching guidelines allow for presence/absence of newlines, so maybe it's not worth fixing it...

**Comment by jlovejoy** [comment]
@zvr @swinslow - so, I'm not sure how to fix this, but in any case, it is something that probably impacts a quite a few licenses (certainly GPL-3.0-only as well). What are your thoughts on handling this? At least going forward, if we document it, then we could go back and fix older licenses in due time?

**Comment by swinslow** [comment]
Hi all,

Thanks for raising these questions and for the discussion here. I agree with @zvr and @jlovejoy that for SPDX matching purposes, whitespace is not relevant and all whitespace is to be treated as a single blank space; see https://spdx.github.io/spdx-spec/v3.0.1/annexes/license-matching-guidelines-and-templates/#whitespace

In light of that, I think the current approach to date has been to assume that the XML templates (and downstream artifacts created from them, such as the SPDX license list website) may not exactly reflect the way that line breaks and whitespace are encoded in the original license stewards' websites and text files.

If we want to change that approach, then to @jlovejoy's point I would expect that would need to be an across-the-board revision, going through each existing license (or at a minimum all of the major ones, including all *GPL family licenses) and making sure that `<p>...</p>` and `<br />` tags are used to precisely align with license stewards' formatting.

I don't think there's currently a desire to take that on, but if someone is so inclined, then let's track that under a separate issue for an across-the-board license review. Thank you all!
