### ISSUE TITLE
New license request: Latex2e with translated notice permission

### ISSUE THREAD

**Issue by ppisar** [spdx/license-list-XML#1888]
### Introduction

This is an augmented variant of [Latex2e](https://spdx.org/licenses/Latex2e.html) license. It has been approved by Fedora project  <https://gitlab.com/fedora/legal/fedora-license-data/-/issues/176>.

This is a difference against Latex2e license:

~~~~
--- Latex2e 2023-03-21 16:55:49.575042074 +0100
+++ new 2023-03-21 16:54:18.782689780 +0100
@@ -8,4 +8,6 @@
 notice identical to this one.
 
 Permission is granted to copy and distribute translations of this manual
-into another language, under the above conditions for modified versions.
+into another language, under the above conditions for modified versions,
+except that this permission notice may be stated in a translation approved
+by the Foundation.
~~~~

### License Name

Latex2e with a translated notice permission

### Suggested short identifier

Latex2e-translated-notice

### URL to license text

https://git.savannah.gnu.org/cgit/indent.git/tree/doc/indent.texi?id=a74c6b4ee49397cf330b333da1042bffa60ed14f#n74

### OSI Status

I don't know

### License author or steward

Unknown, maybe Free Software Foundation 

### URL to project(s) that use license

<https://www.gnu.org/software/indent/>

**Comment by richardfontana** [comment]
I think it would be unfortunate to use "Latex2e" in the name of the identifier for this license, since I believe it likely predates Latex2e. Though that is probably also true of the Latex2e license.

**Comment by ppisar** [comment]
Do you have any suggestion for a better name? What about "FSF Verbatim Copying"?

**Comment by jlovejoy** [comment]
@richardfontana - ironically, I believe SPDX choose "Latex2e" as the name for https://spdx.org/licenses/Latex2e.html because it was what Fedora used and added to SPDX back in the 2014 timeframe when we added a bunch of licenses from Fedora.
see https://fedoraproject.org/wiki/Licensing/Latex2e

Given we are not going to go back and change that now, I think the name @ppisar suggested or something similar is appropriate, as it maintains the closeness of the two licenses

**Comment by jlovejoy** [comment]
oh, and I'm +1 to add for the obvious reason that this is similar to something we already have on the list and is used in a project that is used widely

**Comment by swinslow** [comment]
Also +1 to add. Given that `Latex2e` already exists on the SPDX License List as @jlovejoy mentioned, I'm fine with the proposed identifier and name here (very minor nit: I would remove "a" from the name to align generally with other similar licenses' names on the list: "Latex2e with translated notice permission")

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Latex2e with translated notice permission

## License ID

Latex2e-translated-notice

## XML markup

none

## Notes:

This license is almost the same as Latex2e, but adds a note related to translations.

**Comment by jlovejoy** [comment]
@ppisar - could you make the pull request for the files to add this to the SPDX License List now that it's been accepted?
