### ISSUE TITLE
TEST-New license request: TEST0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by HirumalPriyashan** [spdx/license-list-XML#1892]
**1.** License Name: Test Licence
**2.** Short identifier: TEST0
**3.** License Author or steward: 
**4.** Comments: This is a test license request to get familiarity with the tool.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/215
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: https://example-test.com/test

**Comment by jlovejoy** [comment]
Hi @HirumalPriyashan - what did you think of the process? Imagine if you were actually submitting a license to be included in the SPDX License List and you read this documentation https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md and then used the tool to submit your license - do you see any places for improvements?

Give me a bit to find an issue where you can then test the "other side" of the tool for when a license has been accepted.

**Comment by HirumalPriyashan** [comment]
Thanks @jlovejoy 

> do you see any places for improvements?

There seems to be lack of feedback to the user, which make the user wonder whether the request actually submitted or not. Only thing that happens after a submission is clear out the form, may be we can provide 
- a toast with a message of successful or not, additionally with the GitHub issue URL( or open a new tab)
- loading state (spinner) while the submission is happening to avoid double issues being created and notify their request is processing.

And also noticed some validations need to be done, for example even for this issue I tried to get away without specifying an author, (even though the form said to fill as `Unknown` in that case) - I think we need to validate those as well before creating a new issue.

> Give me a bit to find an issue where you can then test the "other side" of the tool for when a license has been accepted.

Looking forward to it.
In the mean time, would it be okay to created a test PR to get the grasp of tool as well?

**Comment by jlovejoy** [comment]
I just created a new test license to remind myself of what happens after you press submit and you are right, it's a bit minimal. I've added this to a guidance doc I'm creating which I'll post in our Gitter thread shortly.

In the meantime, feel free to use #1897 to test out the "other end" of the process in terms of creating a PR for the xml file from the tool

**Comment by jlovejoy** [comment]
as for the license author/steward - there often isn't one, so this field is not mandatory. We have tried to update the instructions in the form to allow for this reality... but if someone leaves it blank, it shouldn't fail the submission

**Comment by HirumalPriyashan** [comment]
> but if someone leaves it blank, it shouldn't fail the submission

In that case `(If not known, put 'Unknown')` is not needed IMO:)

> In the meantime, feel free to use https://github.com/spdx/license-list-XML/issues/1897 to test out the "other end" of the process in terms of creating a PR for the xml file from the tool

Sure, I have created a PR  using the tool.

**Comment by jlovejoy** [comment]
ah, so you are saying make the license author/steward field optional, instead of mandatory, which then requires putting something (i.e., "Unknown") in the field... that is an option. Im not sure if maybe we kept it mandatory so people didn't simply skip it. We may have had issues with people leaving things blank early on.

**Comment by HirumalPriyashan** [comment]
> make the license author/steward field optional, instead of mandatory

not exactly that, I think we can omit the text `(If not known, put 'Unknown')` attached to field name, as we treat both 'Unknown" and empty text in the same way. Or else we can put a placeholder with "Unknown" text so that users don't need to go through the step of putting "Unknown" specifically.

> kept it mandatory so people didn't simply skip it. We may have had issues with people leaving things blank early on

But even for this issue I was able to create the issue by skipping it, may be validation is failing?
