### ISSUE TITLE
New license request: MIT-Festival

### ISSUE THREAD

**Issue by tyrylu** [spdx/license-list-XML#1911]
### Introduction

It's a variant of the MIT license, and, according to https://gitlab.com/fedora/legal/fedora-license-data/-/issues/187#note_1339166066, already approved by Fedora legal.

### License Name

MIT, Festival variant

### Suggested short identifier

MIT-Festival

### URL to license text

https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#Festival_variant

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/festvox/festival, https://github.com/festvox/speech_tools

**Comment by swinslow** [comment]
Copy of license text:

  Permission is hereby granted, free of charge, to use and distribute
  this software and its documentation without restriction, including
  without limitation the rights to use, copy, modify, merge, publish,
  distribute, sublicense, and/or sell copies of this work, and to
  permit persons to whom this work is furnished to do so, subject to
  the following conditions:
   1. The code must retain the above copyright notice, this list of
      conditions and the following disclaimer.
   2. Any modifications must be clearly marked as such.
   3. Original authors' names are not deleted.
   4. The authors' names are not used to endorse or promote products
      derived from this software without specific prior written
      permission.

  THE UNIVERSITY OF EDINBURGH AND THE CONTRIBUTORS TO THIS WORK
  DISCLAIM ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
  ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT
  SHALL THE UNIVERSITY OF EDINBURGH NOR THE CONTRIBUTORS BE LIABLE
  FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
  AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
  ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
  THIS SOFTWARE.

**Comment by jlovejoy** [comment]
+1 to add given it's in a major distro, allowed for Fedora and has been on the Fedora good list of long ago. Note: SPDX didn't add all the variant shown on that page during the 2014 review, so back-filling a bit now!

**Comment by swinslow** [comment]
Also +1 to add, and fine with the name / ID proposed here (though I would omit the comma after "MIT" in the name -- just "MIT Festival Variant" to align with others on the license list)

I note that Carnegie Mellon has also used this form, https://github.com/festvox/flite/blob/master/COPYING, so we'll want to include templating for the two references to "UNIVERSITY OF EDINBURGH" in the disclaimer paragraph.

There's also a 3-clause version used a bit further down in that same file, which appears to omit the 4th numbered clause. But that version hasn't been requested here, so not including in this request.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

MIT Festival Variant

## License ID

MIT-Festival

## XML markup

University name should include `<alt>` matches for any text in two locations in the final paragraph.

## Notes:

None

## Additional rationale or notes on decision:

Used in major distro; simple permissive and historical license

**Comment by swinslow** [comment]
@tyrylu could you make a PR for this, as per https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process? Thank you!

**Comment by tyrylu** [comment]
Sure thing.
