### ISSUE TITLE
New license request: OpenSSL-linking-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#1912]
**1.** License Name: OpenSSL Linking Exception
**2.** Short identifier: OpenSSL-linking-exception
**3.** License Author or steward: Unknown
**4.** Comments: GPLv3+ variant with an exception not listed by SPDX.
We discussed it at https://gitlab.com/fedora/legal/fedora-license-data/-/issues/126 and both Richard and Jilayne suggested submitting it here.
This is close to https://spdx.org/licenses/openvpn-openssl-exception.html but differ in few points.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/224
**6.** URL(s): https://gitlab.nic.cz/datovka/datovka/-/blob/develop/COPYING
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.nic.cz/datovka/datovka/

**Comment by xsuchy** [comment]
@jlovejoy tagging you per your request.

**Comment by jlovejoy** [comment]
This is one of the variants that was not addressed in the PRs related to #1356 - note the comment in that issue that lists the variants not covered, includes:

> cryptsetup / siege / naxsi: "In addition, as a special exception, the copyright holders give permission to link the code of portions of this program with the OpenSSL library under certain conditions as described in each individual source file, and distribute linked combinations including the two.

which is same as this one. given we already decided to add the other variants, but just didn't get to adding all of them, I think we can mark this as accepted and move to making the files?
@swinslow - do you agree?

**Comment by jlovejoy** [comment]
@swinslow - thoughts on comment above?

**Comment by swinslow** [comment]
I'm +1 to add. I was about to raise a question about the ambiguity of the "under certain conditions as described in each individual source file" language, but I note @richardfontana's comments in the Fedora Legal thread and I think I am comfortable with that for SPDX listing purposes.

Agree that I'm not sure what the right name/ID should be for this one. Maybe `conditions-openssl-exception`? I don't know enough about these projects to point to any one of them with confidence as being the originator of this language...

**Comment by pombredanne** [comment]
FYI, this has been tracked as https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/openssl-exception-gpl-3.0-plus.LICENSE since 2018

**Comment by jlovejoy** [comment]
@pombredanne - you could have submitted it years ago!

unfortunately, still stuck on naming though, as the examples of projects it is used with include GPL-3.0 and GPL-2.0 so we don't want to use either in the name.

I'm inclined to use one of the earlier project names, and just go with it: `cryptsetup-OpenSSL-exception` unless anyone has any robust objections... 

This has been open for this reason for too long as it is and @xsuchy is probably not happy with me! ;)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

cryptsetup OpenSSL exception

## License ID

cryptsetup-OpenSSL-exception

## XML markup

none
## Notes:

none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
