### ISSUE TITLE
New license request: GPL-3.0-interface-exception

### ISSUE THREAD

**Issue by Enchufa2** [spdx/license-list-XML#1921]
### Introduction

GPLv3+ variant with an exception not listed by SPDX. Discussed and approved for Fedora at https://gitlab.com/fedora/legal/fedora-license-data/-/issues/191. 

### License Name

GPL-3.0 Interface Exception

### Suggested short identifier

GPL-3.0-interface-exception

### URL to license text

https://www.gnu.org/licenses/gpl-faq.en.html#LinkingOverControlledInterface

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://gitlab.mpi-magdeburg.mpg.de/software/flexiblas-release

**Comment by jlovejoy** [comment]
+1 to add and I'm surprised that we didn't have this one already, as it's on the FSF website which we did look over when adding a bunch of exception for version 2.0 of the license list.

I think the name would need some markup, as it looks like there are different names used.

**Comment by swinslow** [comment]
Also +1 to add, given use in Fedora as well as definition originating from the FSF site.

I haven't done a full compare of the language so I'm assuming for the moment that the FlexiBLAS exception is identical to the one from the FSF site, other than replacing project names, etc. Assuming it is, I'd be good with the name and ID as specified in the submission.

**Comment by Enchufa2** [comment]
Yes, it's identical but with the required replacements.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

GPL-3.0 Interface exception

## License ID

Interface-exception

## XML markup

for name of entity

## Notes:

_add any information that is to be included in the Notes field_

## Additional rationale or notes on decision:

This is listed on FSF site as a GPL-3.0 exception

**Comment by jlovejoy** [comment]
on ID, I don't think we want to include GPL-3.0, as we don't usually seem to do that and it could look funny in the full license expression:
`GPL-3.0-or-later WITH interface-exception`

v. 

`GPL-3.0-or-later  WITH GPL-3.0-interface-exception`

@swinslow - agree?

**Comment by Enchufa2** [comment]
I proposed to include GPL-3.0 because there's already the `GPL-3.0-linking-exception`, the `GPL-3.0-linking-source-exception`, etc.

**Comment by jlovejoy** [comment]
fair enough @Enchufa2 - I think we've tried to not use the license in the short identifier and name, but this would be consistent as they others are also very much GPL-3.0, section 7 specific

could you make a PR to add these as per https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process ?:)

**Comment by jlovejoy** [comment]
updated decision data above
