### ISSUE TITLE
New license request: CSPICE [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#1934]
**1.** License Name: CSPICE
**2.** Short identifier: CSPICE
**3.** License Author or steward: Unknown
**4.** Comments: A new license that I did not find matches in the SPDX license data repo, and it is used by a NASA project
**5.** License Request Url: http://tools.spdx.org/app/license_requests/226
**6.** URL(s): https://naif.jpl.nasa.gov/pub/naif/toolkit//C/MacM1_OSX_clang_64bit/packages/README (Disclaimer section)
**7.** OSI Status: Unknown
**8.** Example Projects: https://naif.jpl.nasa.gov/naif/toolkit_C.html

**Comment by jlovejoy** [comment]
This is interesting, it truly is just a disclaimer, really. 

@chenrui333 - do you know is this the only project that uses this or have you seen it before? Is this project widely used by others?

**Comment by jlovejoy** [comment]
ok, if it's only used in one project, is not even really a full license, and not a super well-known license, I'd be inclined to not add it.

**Comment by jlovejoy** [comment]
if this gets more use in the future, we can reconsider or it can be re-submitted
