### ISSUE TITLE
Online license list omits important limitations (users must know to reference XML)

### ISSUE THREAD

**Issue by recursivenomad** [spdx/license-list-XML#1935]
Presently, the [MIT License](https://spdx.org/licenses/MIT.html) appears to permit the replacement of *`this software and associated documentation files`* presumably to allow for wider non-software use of the license, as well as the replacement of *`THE AUTHORS OR COPYRIGHT HOLDERS`*.

Would you consider permitting replacement on the same strings in the [MIT No Attribution](https://spdx.org/licenses/MIT-0.html) license?

**Comment by richardfontana** [comment]
My view: While I think SPDX should make more of an attempt to "get ahead" of license XML evolution by trying to identify nonsubstantive textual variants in *actual use*, I don't think it should attempt to accommodate license text variants that can't be shown to  actually exist.

**Comment by recursivenomad** [comment]
Thanks for that perspective.  I was trying to "get ahead" of licensing a project with MIT-0 using non-software language by ensuring alignment with SPDX, but this makes sense that SPDX follows existing license implementations rather than generalizing them from the onset.

I also learned after posting this suggestion that the XML for MIT only permits *specific* replacement, and not blanket replacements as I initially believed, which also clarifies the intentions behind these matching guidelines.

As an aside, it may be helpful to developers like myself for the online SPDX License List to mention that some replaceable text is only replaceable with specific alternative strings (explicitly labelled or as a generic disclaimer).

**Comment by richardfontana** [comment]
> I also learned after posting this suggestion that the XML for MIT only permits _specific_ replacement, and not blanket replacements as I initially believed, which also clarifies the intentions behind these matching guidelines.
> 
> As an aside, it may be helpful to developers like myself for the online SPDX License List to mention that some replaceable text is only replaceable with specific alternative strings (explicitly labelled or as a generic disclaimer).

Thank you for pointing this out. I admit that I was very confused about this for a long time. SPDX-legal team, I don't know what to suggest there but the fact that @recursivenomad and I both found this unclear or confusing may suggest the need for some sort of change or clarification. 

I have basically concluded that the license text contained in the SPDX license list is of no use by itself -- anyone attempting to use the SPDX license list will need to reference the XML files to truly understand what a license list identifier means.

**Comment by swinslow** [comment]
I've had a couple of thoughts on this, but not something I've had a chance to look into addressing yet.

### option 1

On the actual rendered listings on the license list website, it would perhaps help if replaceable text fields (those in red) could be "hovered over" with a pop-up that shows the underlying regular expression for the match.

That wouldn't be perfect, and I'm sure there are more ideal user interfaces. But it could at least help to "bubble up" to users of the license list the specific regular expressions that were intended for each match.

### option 2

(also could do with or without option 1)

On each published license list HTML page, we could include a direct link back to the underlying XML source file in GitHub. That way, it's also front and center to point people to the underlying source.

Either of these would require changes to the [license list publisher](https://github.com/spdx/licenseListPublisher), and that's of course "something I'd like to look into someday..."

**Comment by recursivenomad** [comment]
> We try to encourage people to actually read the matching guidelines, but I suspect most don't. I have not come up with any better ideas as to how to give the importance of this more attention! Maybe you have some better ideas??

@jlovejoy - I think what was most confusing to me as a new user was:
- A link to explaining Matching Guidelines is not present on license text pages themselves (ie. the pages where the actual colour-coded text exists)
- The Matching Guidelines do not make clear that "replaceable text" is *specifically* replaceable text (my assumption was that "replaceable" was being used in the broadest sense of the term)

So from my initial usage, I would suggest presenting a similar note before any license text containing replaceable/omittable text, but ensuring it explains that blue text is omittable, and red text is replaceable **with specific or generic strings**.  I think it would then be very helpful to link to the XML source following this notice (as suggested by @swinslow's *option 2*), possibly explaining that such specific information can be found in the XML.

**Comment by richardfontana** [comment]
BTW I would guess that the current use of blue and red text in the license texts displayed at https://spdx.org/licenses are not perceivable by some people with color blindness.

**Comment by zvr** [comment]
@richardfontana there is a ticket for this https://github.com/spdx/LicenseListPublisher/issues/135

**Comment by zvr** [comment]
@recursivenomad I assume you know that if you want to use license texts, etc., you should be using the data published on https://github.com/spdx/license-list-data (not the internal XML files).

Having said that, I agree that our web presentation of license texts in the License List can be improved to show more information. These are issues towards https://github.com/spdx/LicenseListPublisher not this repo.

**Comment by recursivenomad** [comment]
@zvr - No, I was not made aware of this.  As somebody looking to comply with SPDX license definitions, I found the internal XML files by digging/stumbling around when I became suspicious about what specific text was permitted in replaceable strings mentioned at https://spdx.org/licenses, and assumed that the XML is the source for understanding specifically permitted replaceable strings.

The original subject of this issue did relate to XML data, but changed course following related discussion.  I will gladly close this issue and open a new one in the relevant repo you've linked, thank you for that nudge.
