### ISSUE TITLE
Grammatical Error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by BassCoder2808** [spdx/license-list-XML#1936]
Error is in the `Getting Started` section in the `CONTRIBUTING/md` in  `Make suggestions to improvement for documentation`.
We can change it to something like `Make suggestions to improve the documentation` which is more grammatically accurate

**Comment by jlovejoy** [comment]
thanks @BassCoder2808 - made PR to fix this and a couple other things I noticed in the process!
