### ISSUE TITLE
New license request: Libpri-OpenH323-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by musicinmybrain** [spdx/license-list-XML#1939]
**1.** License Name: Libpri OpenH323 exception
**2.** Short identifier: Libpri-OpenH323-exception
**3.** License Author or steward: Unknown
**4.** Comments: This exception appears in libpri, which is part of Asterisk, a prominent open-source telephony stack that is packaged in major Linux distributions, including Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/227
**6.** URL(s): https://github.com/asterisk/libpri/blob/1.6.0/README#L19-L22
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/asterisk/libpri

**Comment by musicinmybrain** [comment]
Note that the top-level asterisk project has [a similar permission](https://github.com/asterisk/asterisk/blob/20.2.1/LICENSE#L27-L28),

```
Specific permission is also granted to link Asterisk with OpenSSL, OpenH323
UniMRCP, and/or the UW IMAP Toolkit and distribute the resulting binary files.
```

but as far as I can tell libpri is the only extant project with the particular exception text submitted here.

Note also that the exception text has a typo, `entirity` for `entirety`.

**Comment by richardfontana** [comment]
Related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/75

**Comment by jlovejoy** [comment]
+1 to add, will also add official license acceptance comment next.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [x} approved
- [ ] not approved

## Name

libpri OpenH323 exception

## License ID

libpri-OpenH323-exception 

## XML markup

none at this time

## Notes:

_add any information that is to be included in the Notes field_


_add any additional information, including optionally a summary of what is recorded in the issue comments_

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@musicinmybrain - your PR looked fine. You can't edit the submission, but have to make any edits directly to the XML file (if that makes sense). Then manually add the test .txt file to the PR (so yeah, the submission tool is still a bit manual, but we are working on improving that!)

In any case, I made a new PR at #1967

**Comment by musicinmybrain** [comment]
@jlovejoy Thanks for your help!
