### ISSUE TITLE
New license request: Government of Japan Standard Terms of Use (Version 1.0)

### ISSUE THREAD

**Issue by sorairolake** [spdx/license-list-XML#1942]
### Introduction

This is applied to contents created by the Government Agencies of Japan.
This is an older version, so this is probably not used much anymore nowadays.

See also: #1925

### License Name

Government of Japan Standard Terms of Use (Version 1.0)

### Suggested short identifier

GJSTU-1.0

### URL to license text

- [English version](https://web.archive.org/web/20210507130915/https://www.kantei.go.jp/jp/singi/it2/densi/kettei/gl_betten_1_en.pdf)
- [Japanese version](https://web.archive.org/web/20210507131341/https://www.kantei.go.jp/jp/singi/it2/densi/kettei/gl_betten_1.pdf)

### OSI Status

I don't know

### License author or steward

The Cabinet Secretariat

### URL to project(s) that use license

- <https://web.archive.org/web/20160116051828/http://www.jma.go.jp:80/jma/en/copyright.html>
- <https://www.jma-net.go.jp/narita-airport/tushin/copyright.html>

**Comment by jlovejoy** [comment]
@sorairolake - given there is later version of this, is version 1.0 still in use widely?

**Comment by sorairolake** [comment]
@jlovejoy Probably, I think this version is almost not used nowadays. However, if users are already using contents under this version, the terms of this older version will continue to apply, not the latest version (term 7-b of the version 2.0).

**Comment by jlovejoy** [comment]
I'd be inclined not to add this for some of the same reasons as stated in #1925, but also b/c it's not likely to be used nowadays.

**Comment by jlovejoy** [comment]
discussed on 6/22 call: Decided to not accept similar to #1943 as the SPDX License List doesn't usually add website terms of use and there does not seem to be substantial use and main link to license is web archive link. In addition, this license includes restrictions in section 3 that would not meet any of the free/open definitions and may go a step too far (vague and potentially far-reaching)
