### ISSUE TITLE
New license request: Panaka

### ISSUE THREAD

**Issue by hoijui** [spdx/license-list-XML#1944]
### Introduction

I actually don't know if this license meets the criteria, but it is supposedly closely related to the Solderpad Hardware License (already in SPDX as an exception to the Apache license, e.g. `Apache-2.0 WITH SHL-2.0`) and the CERN-OHL-???, so I imagine it should at least be a close call for it to be legible to be included.
If it is not, I am also happy for this fact being documented in this issue for the future, though, even if the reason for not including it would be, that you currently lack the resources to check if it should be included.

### License Name

Panaka Open Hardware License (v1.0)

### Suggested short identifier

Panaka-1.0

### URL to license text

https://handibot.com/panaka-license.php#license-panaka

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/Handibot/handibot-hardware

**Comment by hoijui** [comment]
It might also make sense to make this an exception for the Apache license.

**Comment by jlovejoy** [comment]
@hoijui - thanks. This is definitely a different license than any of the Solderpad or Cern licenses. And SPDX does review open hardware licenses, as per our https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md (which you can see reference the OSHWA's definition)

I'm going to mark this for the next release, if you don't mind. We are getting down to the wire on 3.21 and have a lot of previous issues to sort out!

**Comment by jlovejoy** [comment]
@hoijui - one question in the meantime - is this only used by Handibot, do you know? One of the principles of inclusion to the SPDX License List is "significant" use, which could be many projects using it or significant project using the license. Thanks!

**Comment by swinslow** [comment]
@jlovejoy From some web searches and looking on GitHub, I'm not seeing any real indications of use of this license beyond the Handibot product.

Taking a quick look at the license text, I haven't given it a full analysis to consider its applicability under the entire set of the [License Inclusion Principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md). However, between the absence of apparent use beyond the Handibot product, together with the specific references to "ShopBot Tools®" in a few places in the license, it does feel to me like this license is presently intended and used just by this one product / project.

Given that, at present I'm more inclined to suggest that a `LicenseRef-` prefix to represent a custom license would be appropriate here, at least unless / until there is more evidence of wider usage.

**Comment by Pizza-Ria** [comment]
+ to Steve on the assertion that this is not broadly/deeply utilized.

**Comment by hoijui** [comment]
@swinslow I agree .. thanks for taking the time!

Could you maybe tell/show me how I'd do that?
Maybe directly in the related issue: to https://github.com/spdx/spdx-spec/issues/858

**Comment by jlovejoy** [comment]
@hoijui - the use of `LicenseRef-` is explained in the SPDX spec here https://spdx.github.io/spdx-spec/v2.3/other-licensing-information-detected/

**Comment by jlovejoy** [comment]
closing as not accepted
