### ISSUE TITLE
New license request: RAIL-S [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by debonx** [spdx/license-list-XML#1948]
**1.** License Name: Restricted Artificial Intelligence License for Software
**2.** Short identifier: RAIL-S
**3.** License Author or steward: Emanuele De Boni
**4.** Comments: This license intends to only protect human creativity, innovation and collaboration in software development, preventing potential unknown and unpredictable risks raised by the advent of Artificial Intelligence.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/230
**6.** URL(s): https://github.com/debonx/restricted-artificial-intelligence-licenses/blob/main/rail-s/license.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/debonx/restricted-artificial-intelligence-licenses

**Comment by swinslow** [comment]
Hello @debonx,

I am sure the team will have more questions, but for the "Example Projects" question, please provide several examples of real-world projects that are currently using this license in the form that you have requested here. The only Example Project you listed appears to be the repo for the license text itself.

This is related to the [license inclusion princples](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md) "Other Factor" 3:

> The license has actual, substantial use such that it is likely to be encountered. Substantial use may be demonstrated via use in many projects, or in one or a few significant projects. For new licenses, there are definitive plans for the license to be used in one or a few significant projects.

If this license is a brand new proposal that has not seen actual, substantial use, or if it is only used (or proposed to be used) in a few personal projects, then I expect it is highly unlikely to satisfy the license inclusion principles overall. Particularly in light of what appears to be the restrictions on use which, from a quick glance, I am expecting would not satisfy the definitions referenced in "Other Factor" 1 from the inclusion principles.

**Comment by debonx** [comment]
@swinslow thanks for the reply and clarification. I am collaborating with a relevant group of developers to start adopting it across their projects, but as you mentioned, being a brand new license, this will take sometime. Please be patient, I will collect all the needed information asap, hopefully within the next weeks.

**Comment by richardfontana** [comment]
Regarding OSI status, I believe this is the same license that was recently submitted and withdrawn from the OSI license approval process, following several reactions to the effect that the license was (if even a license properly speaking) obviously not OSD-conformant: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-April/005369.html

**Comment by richardfontana** [comment]
Separately, @debonx you may wish to note that RAIL is an acronym already in use for a different set of licenses intended for use in machine learning projects? https://www.licenses.ai/

**Comment by debonx** [comment]
> Regarding OSI status, I believe this is the same license that was recently submitted and withdrawn from the OSI license approval process, following several reactions to the effect that the license was (if even a license properly speaking) obviously not OSD-conformant: http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-April/005369.html

Yes, correct, but changes were made in the meantime and it's basically different, as that was more an extension.

I certainly wasn't aware about the licenses.ai great work and I am actually quite happy to discover that, even if they refer to a different kind of restrictions. Thanks for highlighting that!

I will then close this issue, change the references to that acronym and submit again.

**Comment by swinslow** [comment]
Thanks @debonx.

Before resubmitting, I would encourage you again to take a close look at the [SPDX License List inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md).

If your submitted license does not meet the requirements there, as determined by the SPDX legal community, then it won't be added to the [SPDX License List](https://spdx.org/licenses).

In particular, if you are drafting a brand new license that doesn't meet the Open Source Definition AND also is not in use by a _significant_ number of projects, it's highly unlikely that it will be added. If the license is going to include restrictions on use (§ 3, paragraph 3 of the text file you shared before), I highly doubt the SPDX legal community would view it as satisfying the Open Source Definition (I wouldn't view it this way, at least).

**Comment by debonx** [comment]
@swinslow Thanks for the explanation. I will try to work on adoption then, to see if there will be a use case.
