### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by yeyoguapo1** [spdx/license-list-XML#1953]
--- 24 abr. 2023 10:46:38 p. m.
--- IP (ccmni1) 10.166.123.44 
--- Connection: LTE

DNS records for 10.166.123.44

DNS server: 208.67.222.222, port 54, TCP

CNAME   The lookup  due to a network error. Repeating the lookup may be helpful.

DNAME   The lookup  due to a network error. Repeating the lookup may be helpful.

KEY   The lookup  due to a network error. Repeating the lookup may be helpful.

SPF   The lookup  due to a network error. Repeating the lookup may be helpful.

SRV   The lookup due to a network error. Repeating the lookup may be helpful.

**Comment by swinslow** [comment]
This user account also posted spam in #1949; I'm blocking further issues / PRs from this user name
