### ISSUE TITLE
New license request: LDP-1 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by adobes1** [spdx/license-list-XML#1957]
**1.** License Name: LDP General Public License v1
**2.** Short identifier: LDP-1
**3.** License Author or steward: Unknown, possibly Linux Documentation Project
**4.** Comments: This license is used in Linux man-pages.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/232
**6.** URL(s): http://web.archive.org/web/20210511064817/https://old.calculate-linux.org/packages/licenses/LDP-1
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mkerrisk/man-pages

**Comment by adobes1** [comment]
Link to related Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/211

**Comment by adobes1** [comment]
Since this license has been determined to be not-allowed for Fedora, should I close this issue?

**Comment by pombredanne** [comment]
FWIW, this been tracked so far in ScanCode as https://scancode-licensedb.aboutcode.org/ldpgpl-1.html and https://scancode-licensedb.aboutcode.org/ldpgpl-1a.html

**Comment by alejandro-colomar** [comment]
Is there anything using this license?  I don't recall having seen it in the Linux man-pages.  Please point to a file that uses it.

**Comment by alejandro-colomar** [comment]
I would like to see this license included in SPDX, but with some observations and fixes to the request:

```
1. License Name: Linux Documentation Project General Public License v1
```

(spell out LDP)

```
3. License Author or steward: Unknown, possibly Linux Documentation Project
```

Please contact them before doing this.

```
5. Comments: This license is used in Linux man-pages.
```

Please contact <linux-man@vger.kernel.org> for changes involving licenses mainly used there.

```
10. Example Projects: https://github.com/mkerrisk/man-pages
```

That URI is a mirror outdated by *years* compared to the official repository.  The mirror itself very clearly specifies that it is only a mirror, and not a source of truth.  The project is at <https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git>.

**Comment by BrianInglis** [comment]
Another snarky comment in a licence; section 2: 
> c) You must not add notes to the *Document* implying that the reader had better read something produced using `Texinfo`.

which may be an understandable overreaction to *GNU*'s somewhat overbearing antipathy to man pages, but does prohibit certain modifications which are de rigeur in *GNU* packages. 

For an extreme GNU example, see *GNU* mailutils [mail](https://git.savannah.gnu.org/cgit/mailutils.git/tree/doc/man/mail.1)(1) - 22 source lines - 11 *useful* - 24 output lines - 14 content - 5 *useful*:
> The  full documentation for `mail` is maintained as a Texinfo manual.  If
the `info` and `mail` programs are properly installed  at  your  site,  the
command
` 	info mail`
should give you access to the complete manual.

A later version of the *LDP* licence also contains the sentence:
> Any translation or derivative work of *Linux Installation and Getting Started* must be approved by the author in writing before distribution.

which is problematic for most projects, even if they do not offer translations, and *TLDP* also allows authors to add clauses to licences which prohibit modifications! 
*Is this the real Linux? Is this just fantasy?* 
Control freaks, much? Or was vandalism rife, then?

**Comment by jlovejoy** [comment]
@alejandro-colomar - do you still want to add this license to the SPDX License List? Based on the thread in linux-man mailing list, I'm not clear if perhaps it's no longer being used.

If you do want to add it, then spdx-legal needs to do an analysis against the SPDX license inclusion guidelines (which wasn't really done, since @adobes1 withdrew it)

**Comment by alejandro-colomar** [comment]
On 6/8/23 06:04, Jilayne Lovejoy wrote:
> @alejandro-colomar - do you still want to add this license to the SPDX License List? Based on the thread in linux-man mailing list, I'm not clear if perhaps it's no longer being used.

Yes, it's still being used, so I guess we need to add it.

> 
> If you do want to add it, then spdx-legal needs to do an analysis against the SPDX license inclusion guidelines (which wasn't really done, since @adobes1 withdrew it)

Please do.

Thanks,
Alex

> 
> 
> 

-- 
<http://www.alejandro-colomar.es/>
GPG key fingerprint: A9348594CE31283A826FBDD8D57633D441E25BB5
