### ISSUE TITLE
Classpath-exception-2.0: var or optional text to handle variation in reference to GPL-2.0 license?

### ISSUE THREAD

**Issue by pmonks** [spdx/license-list-XML#1973]
In [this license text that includes Classpath-exception-2.0](https://github.com/javaee/javamail/blob/master/LICENSE.txt#L746), the reference to the GPL-2.0 license includes the version number ("GNU General Public License version 2"), but the SPDX exception template only includes the license name ("GNU General Public License") which means that matching of this text via the template fails.  This was originally discovered in [this Spdx-Java-Library issue](https://github.com/spdx/Spdx-Java-Library/issues/166).

In that issue, @goneall suggested that this variation could be handled in the Classpath-exception-2.0 template via the addition of a `<var>` or `<begin/end optional>` section to the template.

**Comment by jlovejoy** [comment]
agreed, we could simply put "version 2" in an optional tag

@pmonks - do you want to prepare a PR for this?
