### ISSUE TITLE
License inclusion principles contain ambiguous use of "free"

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#1979]
I assume that submitting an issue on the License Inclusion Principles is appropriate here since it is maintained in license-list-XML.

The Principles say:

> If the license does not substantively comply with one of the above open source definitions, then the license is primarily intended for free distribution of content (including, in the case of software, its source code) with limited restrictions, and meets other factors listed here.

Maybe I have heightened sensitivity to this but I can't tell whether "free distribution of content" here means "free of charge" ("free as in beer" as some like to say) or "free as in freedom". Historically, in FOSS, "freely redistributable" was at one time somewhat commonly used (prior to 1998) to mean not "free of charge" but something like "free of [proprietary-like] license restrictions". The fact that the sentence is talking about the case where a license does not "substantively" comply with a listed free/open definition suggests that it might mean "free of charge". Further on in the Principles we have:

> At a minimum, all definitions of open source or free software include the characteristic that the source code be made available for inspection and modification and that the source code may be freely distributed.

which I think has to mean "free as in freedom" rather than "free of charge". Since this sense of "free" in the case of software and other cultural works is possibly in general decline, this probably ought to be clarified one way or another.

**Comment by jlovejoy** [comment]
Yes, it is meant to be "free as in freedom" in this case. I believe SPDX also has tried to use both terms "free software" and "open source" to accommodate the different communities who lean towards one or the other and thus be neutral in this regard.

I'm not opposed to wording updates if you think something is unclear?

**Comment by jlovejoy** [comment]
I'm going to close this, as I've referenced it to be consolidated and considered when we more generally update the License Inclusion Guidelines as per #2180
