### ISSUE TITLE
New license request: Nxlog 

### ISSUE THREAD

**Issue by mikolajek-fr** [spdx/license-list-XML#1983]
### Introduction

Request to have a clear status on the free software compatibility with this license.

### License Name

NXLog Public License v1.0

### Suggested short identifier

NXLog

### URL to license text

https://nxlog.co/nxlog-public-license

### OSI Status

I don't know

### License author or steward

NXLog

### URL to project(s) that use license

https://gitlab.com/nxlog-public/nxlog-ce
https://nxlog.co/products/nxlog-community-edition

**Comment by jlovejoy** [comment]
Hi @mikolajek-fr - I think you may be confused as to the role of the SPDX License List which is to to enable efficient and reliable identification of commonly found licenses and exceptions used in free and open or collaborative software, data, hardware, or documentation. The SPDX project is not in the business of assessing whether a license is "free software" (that would be the Free Software Foundation) or "open source" (that would be the Open Source Initiative.

Perhaps you are in the wrong place?

**Comment by Pizza-Ria** [comment]
I can take this one.

**Comment by jlovejoy** [comment]
@Pizza-Ria - not sure you need to as I'm not sure of the intentions of the submitter and they have not answered my question above, so let's wait to hear back...

**Comment by jlovejoy** [comment]
given we have not gotten an answer to the intentions here, plus this appears to be a non-free license written to be used by a specific entity, I don't think it would meet the SPDX inclusion guidelines anyway
