### ISSUE TITLE
New license request: LLGPL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1988]
**1.** License Name: Lisp exception
**2.** Short identifier: Lisp-exception
**3.** License Author or steward: Unknown
**4.** Comments: Specific exception to LGPL used in Fedora, Slime package

Although it's referred to as a "preamble", it reads more like an exception as it states that "Accordingly, the license for the open-source Lisp applications consists of this document plus the LGPL. Wherever there is a conflict between this document and the LGPL, this document takes precedence over the LGPL."
and also states the section 6 is not applicable.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/237
**6.** URL(s): http://opensource.franz.com/preamble.html
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/slime/slime/blob/master/swank/ccl.lisp

**Comment by richardfontana** [comment]
This is a pretty well known historical license/exception that had/has its own name ("LLGPL"). One question is whether it meets SPDX expectations about what should be treated as an exception as opposed to a standalone license. Another though is whether even if it is an exception in the SPDX inclusion guidelines sense, should SPDX instead put it in the license list since it was presented as having its own identity (the precedent would be LGPL-3.0, but in every other case I know of where this issue comes up it seems SPDX has opted to use a `WITH` expression where possible).

**Comment by jlovejoy** [comment]
We would put it on the exception list because it is an exception. And I think the LLGPL is fine for a name for continuity, or maybe LLGPL-exception?

LGPL-3.0 really should be so as well, which was discussed at length a few times over the years, but that ship has sailed

**Comment by richardfontana** [comment]
But is it an exception, or is it a "clarification" (the term actually used in the LLGPL)? If it's just an interpretive gloss on LGPL, that would seem to be something outside the exception/additional permission construct and more appropriate for use with AdditionRef-.

**Comment by swinslow** [comment]
I'm also struggling with seeing this as a pure "exception" in the way we've tended to require for the Exceptions List.

To me, it reads more as an interpretation of the LGPL as applied to Lisp. It doesn't read to me as saying "I, the licensor, am giving you an exception from complying with X or Y condition"; more like, "I, the licensor, read the LGPL in this way."

In that sense, it's probably closest to something like the Linux syscall note. Which is on the exceptions list, so perhaps we could get there with treating this similarly if the statement only provides permissions and doesn't impose any additional restrictions. (I've read it a couple of times and to be honest, I'm not sure whether this is the case.)

But in practice, this feels to me most like the WiX-statement in #979 which sort of languished while looking for license steward input, but for which there was hesitancy about adding to the Exceptions List. I feel similarly here, and tend to agree that an AdditionRef- might be more appropriate.
