### ISSUE TITLE
New license request: Boehm-GC [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1989]
**1.** License Name: libatomic
**2.** Short identifier: libatomic
**3.** License Author or steward: 
**4.** Comments: another minimalist MIT variant found in Fedora. 

see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/180
**5.** License Request Url: http://tools.spdx.org/app/license_requests/238
**6.** URL(s): https://fedoraproject.org/wiki/Licensing:MIT#Another_Minimal_variant_(found_in_libatomic_ops), https://github.com/uim/libgcroots/blob/master/COPYING, https://github.com/ivmai/libatomic_ops/blob/master/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/uim/libgcroots/tree/master, https://github.com/ivmai/libatomic_ops/tree/master/src/atomic_ops

**Comment by jlovejoy** [comment]
submitted on behalf of @tagoh

**Comment by swinslow** [comment]
Copy of license text for easier viewing:

```
Copyright (c) ...

THIS MATERIAL IS PROVIDED AS IS, WITH ABSOLUTELY NO WARRANTY EXPRESSED
OR IMPLIED.  ANY USE IS AT YOUR OWN RISK.

Permission is hereby granted to use or copy this program
for any purpose,  provided the above notices are retained on all copies.
Permission to modify the code and to distribute modified code is granted,
provided the above notices are retained, and a notice that the code was
modified is included with the above copyright notice.
```

**Comment by swinslow** [comment]
+1 to add as a simple, historic and broadly permissive license, found in Fedora.

For the name, based on https://github.com/ivmai/libatomic_ops/blob/724405171d08abb56ae391a85fca20088c189761/LICENSE#L52-L54 it looks like libatomic's use of this license was inherited from "the Boehm-Demers-Weiser conservative garbage collector", which appears to originate from https://www.hboehm.info/gc/ -- see https://www.hboehm.info/gc/license.txt. 

So perhaps `Boehm-GC` as ID and "Boehm-Demers-Weiser GC License" as full name?

**Comment by richardfontana** [comment]
+1 as to Boehm-GC for the short identifier. Unless Demers and Weiser would complain about being omitted :)

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Boehm-Demers-Weiser GC License

## License ID

`Boehm-GC`

## XML markup

None, suggesting keeping copyright text field minimal for this instance

## Notes:

N/A

## Additional rationale or notes on decision:

N/A

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by swinslow** [comment]
Thanks @jlovejoy, I'm fine with omitting the copyright text and sorry for being unclear.

The version from the Fedora wiki just has `Copyright (c) ...`, whereas the two example projects linked in the original submission have many lines of various copyright notices. I was trying to say "let's use the version from the Fedora wiki," but also totally fine just omitting it altogether.
