### ISSUE TITLE
New license request: dtoa [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#1990]
**1.** License Name: Lucent permissive license
**2.** Short identifier: Lucent
**3.** License Author or steward: 
**4.** Comments: Used in Fedora, see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/110

Included in SWI-Prolog which is BSD-2-clause, but also has file under this license
**5.** License Request Url: http://tools.spdx.org/app/license_requests/239
**6.** URL(s): https://github.com/SWI-Prolog/swipl-devel/blob/master/src/os/dtoa.c
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/SWI-Prolog/swipl-devel

**Comment by jlovejoy** [comment]
submitted on behalf of @jamesjer

**Comment by swinslow** [comment]
License text:

```
 * The author of this software is David M. Gay.
 *
 * Copyright (c) 1991, 2000, 2001 by Lucent Technologies.
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose without fee is hereby granted, provided that this entire notice
 * is included in all copies of any software which is or includes a copy
 * or modification of this software and in all copies of the supporting
 * documentation for such software.
 *
 * THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY.  IN PARTICULAR, NEITHER THE AUTHOR NOR LUCENT MAKES ANY
 * REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY
 * OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.
```

**Comment by swinslow** [comment]
This one is quite close to [HPND](https://spdx.org/licenses/HPND.html), but different enough that I don't think it's worth trying to further modify the markup to squeeze it in there.

+1 to add as a simple historical permissive license found in Fedora.

I wouldn't go with the name "Lucent", though, for a variety of reasons, including that there's already a [Lucent Public License](https://spdx.org/licenses/LPL-1.0.html) on the list.

Looks like the license originates with the "dtoa" package from David M. Gay: see for example https://netlib.sandia.gov/fp/g_fmt.c and https://stuff.mit.edu/afs/athena/software/texmaker_v5.0.2/qt57/doc/qtwebengine/qtwebengine-3rdparty-david-m-gay-s-floating-point-routines.html.

(There's also a "gdtoa" package with David M. Gay / Lucent which is close but appears to be a different license -- e.g. https://www.ibm.com/docs/en/icos/22.1.0?topic=terms-acknowledgment-use-dtoa-routine-gdtoa-package; https://opensource.apple.com/source/Libc/Libc-391/gdtoa/FreeBSD/gdtoa-dtoa.c.auto.html)

Given all of that -- perhaps `dtoa` as ID and "David M. Gay dtoa License" as name? Open to alternatives, but I wouldn't use "Lucent" as the ID / name, at least not standing alone.

**Comment by jlovejoy** [comment]
discussed on 6/8 call - accepted

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

David M. Gay dtoa License

## License ID

`dtoa`

## XML markup

None

## Notes:

N/A

## Additional rationale or notes on decision:

as described in issue

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
