### ISSUE TITLE
GPL-3.0-only.txt out-of-sync with XML

### ISSUE THREAD

**Issue by dorssel** [spdx/license-list-XML#1995]
My project uses FSFE REUSE, which automatically downloads licenses in TXT format from https://github.com/spdx/license-list-data.

The GPL-3.0-only.txt file contains `http` URLs, which our security scanner (DevSkim) complains about.

The original XML was altered to use `https` in this commit: https://github.com/spdx/license-list-XML/commit/c92c09fc3dd1740dc29fe726482940ebf35fb5d0. That was in May 2021. However, GPL-3.0-only.txt (and probably others) was never regenerated and predates that change.

**Comment by dorssel** [comment]
I don't quite get it. The XML is correct and contains the `https` versions of the URLs. Or is the XML repo responsible for all formats?

**Comment by goneall** [comment]
@dorssel - check the test text files (links above) - the text files are copied to the text version of the file - that may be where the inconsistency exists.

**Comment by dorssel** [comment]
Ah, I see. Those txt files are from 4 years ago, whereas the XML (this should be authoritative, right?) has changed since then.

**Comment by goneall** [comment]
> Those txt files are from 4 years ago, whereas the XML (this should be authoritative, right?) has changed since then.
 
Yes - the XML files "should be authoritative", however, to fix an issue raised where we are not formatting the text files exactly as found from the source, we use the text files at the source.

If you could create a pull request to update the .txt files - that should fix the problems.

**Comment by jlovejoy** [comment]
just so I understand the origin of this: your security scanner is complaining b/c the license text file has "http:" instead of "https:" ?? (why?)

In any case, yes, our text files should be updated accordingly. @dorssel - could you make a PR to do so?

**Comment by dorssel** [comment]
> just so I understand the origin of this: your security scanner is complaining b/c the license text file has "http:" instead of "https:" ?? (why?)

I added the DevSkim GitHub action to our build CI, and it gives a warning about using `http` instead of `https`. See: https://github.com/Microsoft/DevSkim/blob/main/guidance/DS137138.md

> In any case, yes, our text files should be updated accordingly. @dorssel - could you make a PR to do so?

Will do.
