### ISSUE TITLE
New license request: Prosperity-3.0.0

### ISSUE THREAD

**Issue by ghuntley** [spdx/license-list-XML#1996]
### Introduction

Creating request to re-review previous decisions at https://github.com/spdx/license-list-XML/pull/960#issuecomment-1581400328

### License Name

Prosperity-3.0.0

### OSI Status

I don't know

### URL to project(s) that use license

https://github.com/spdx/license-list-XML/pull/960#issuecomment-1581400328

**Comment by jlovejoy** [comment]
@ghuntley - this is not a complete submission and is missing a bunch of info - please follow the process entirely. (and it's preferred to use the SPDX Online Tool, to be honest :)

**Comment by ghuntley** [comment]
@jlovejoy can you please re-open https://github.com/spdx/license-list-XML/pull/960#issuecomment-1581400328

**Comment by jlovejoy** [comment]
#960 wasn't a complete submission to begin with, which is why I didn't re-open it (and see comment I left there) 
:)

**Comment by jlovejoy** [comment]
if you want to request a license be added to the SPDX License List, please follow the process as described here: https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md

Keep in mind, since this license was already considered at length, you will need to consider how it objectively meets the inclusion principles now, e.g., what has changed to justify re-consideration

**Comment by jlovejoy** [comment]
if no one submits this as a new license submission via the full process, using the online submission tool in the next couple weeks, I'll just close this issue (See comment above)

**Comment by donmccurdy** [comment]
@jlovejoy is it possible to submit a license request without giving your tool read+write access to all of my repositories? I'm not especially comfortable with that, as I also have access to some of my clients' codebases. 

![Screenshot 2023-09-18 at 10 17 18 AM](https://github.com/spdx/license-list-XML/assets/1848368/aef667c8-9f99-4cfa-9963-7f61b5bf6ccb)

If not, is request submission by GitHub issue acceptable?

**Comment by jlovejoy** [comment]
@donmccurdy - while the online tools is preferred, we do also have an issue template with the same fields - please be sure to fill it out thoroughly and review the inclusion guidelines as noted in the process description (as well as consider what has changed since this was submitted before. Thanks.

**Comment by jlovejoy** [comment]
@donmccurdy - I'm closing this, as I assume you will re-submit with the complete and suggested info (see comments above) via the issue template when you have time!
