### ISSUE TITLE
New license request: copyright

### ISSUE THREAD

**Issue by albertoabellagarcia** [spdx/license-list-XML#2012]
### Introduction

Although I know perfectly that this is not an open license it is necessary for making the difference with real free and open license. 

### License Name

Copyright

### Suggested short identifier

copyright

### URL to license text

https://termly.io/resources/articles/copyright-examples/#copyright-examples-types

### OSI Status

Rejected

### URL to project(s) that use license

https://termly.io/resources/articles/copyright-examples/#copyright-examples-types

**Comment by swinslow** [comment]
The page linked here appears to be text describing how copyright law works, not a license, so this is not something that would be added to the SPDX license list.
