### ISSUE TITLE
HP-1986 variant

### ISSUE THREAD

**Issue by jplesnik** [spdx/license-list-XML#2019]
I found the license below during the review of license for package [perl-Data-UUID](https://github.com/bleargh45/Data-UUID)

Here is the Fedora license review, in which it was approved for Fedora: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/239

License text:
 ** Copyright (c) 1990- 1993, 1996 Open Software Foundation, Inc.
 ** Copyright (c) 1989 by Hewlett-Packard Company, Palo Alto, Ca. &
 ** Digital Equipment Corporation, Maynard, Mass.
 ** Copyright (c) 1998 Microsoft.
 ** To anyone who acknowledges that this file is provided "AS IS"
 ** without any express or implied warranty: permission to use, copy,
 ** modify, and distribute this file for any purpose is hereby
 ** granted without fee, provided that the above copyright notices and
 ** this notice appears in all source code copies, and that none of
 ** the names of Open Software Foundation, Inc., Hewlett-Packard
 ** Company, Microsoft, or Digital Equipment Corporation be used in
 ** advertising or publicity pertaining to distribution of the software
 ** without specific, written prior permission. Neither Open Software
 ** Foundation, Inc., Hewlett-Packard Company, Microsoft, nor Digital
 ** Equipment Corporation makes any representations about the
 ** suitability of this software for any purpose.

https://github.com/bleargh45/Data-UUID/blob/master/LICENSE

Could you please accommodate this variant through a revision to the XML file for that license?

**Comment by xsuchy** [comment]
Is this this one https://github.com/spdx/license-list-XML/blob/main/src/HP-1986.xml ?

**Comment by jlovejoy** [comment]
it's very similar to HP-1986, but a few differences:
1) has additional names besides HP (easy to accommodate with markup)
2) `none of the names  ... be used` v. `the name ... not be used` (which I also think is worthy of markup, as it's more a singular v. plural wording thing)
3) `notice appears in all _source code_ copies` whereas the original omits "source code"

**Comment by swinslow** [comment]
Discussed on 2023-07-13 legal team call. For item 3 from @jlovejoy's list above, presence of "_source code_ copies" is arguably substantively different from HP-1986 so it warrants a separate identifier.

Agreed to add using the identifier `HP-1989` and name  "Hewlett-Packard 1989 License", subject to @Pizza-Ria reaching out to HP and seeing if they have a different position here. Would include notes indicating the difference from HP-1986 to this one.

**Comment by Pizza-Ria** [comment]
Will copy you and Jilayne on the email to Guarav at HP.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Hewlett-Packard 1989 License

## License ID

HP-1989

## XML markup

none at this point

## Notes:
This license is the same as HP-1986, but adds a specific provision that the "the above copyright notices and this notice appears in all source code copies" whereas HP-1986 omits "source code". 


## Next steps ##
Files to be made once HP representative has had a chance to view and weigh in

If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by Pizza-Ria** [comment]
Gaurav Gupta at HP agreed that the HP-1989 would be OK via email.
[RE_ SPDX & HP.pdf](https://github.com/spdx/license-list-XML/files/12088501/RE_.SPDX.HP.pdf)

**Comment by jlovejoy** [comment]
@jplesnik - could you prepare a PR for this now that it's been accepted?
