### ISSUE TITLE
New license request: MIT-dotnet [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2022]
**1.** License Name: none (MIT-dotnet)
**2.** Short identifier: MIT-dotnet
**3.** License Author or steward: Unknown
**4.** Comments: This is close to MIT-0 and Clips licenses. But has different wording. It is used in dotnet for some time.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/242
**6.** URL(s): https://github.com/dotnet/runtime/blob/55e1ac7c07df62c4108d4acedf78f77574470ce5/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/AttRegexTests.cs#L12-L28
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/dotnet/runtime/

**Comment by xsuchy** [comment]
Fedora review backreference https://gitlab.com/fedora/legal/fedora-license-data/-/issues/138

**Comment by richardfontana** [comment]
Maybe MIT-testregex ? MIT-Fowler?

**Comment by jlovejoy** [comment]
license text:
```
* Permission is hereby granted, free of charge, to any person obtaining a
 * copy of THIS SOFTWARE FILE (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, and/or sell copies of the
 * Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following disclaimer:
 *
 * THIS SOFTWARE IS PROVIDED BY AT&T ``AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AT&T BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ```

**Comment by jlovejoy** [comment]
it's like Clips or MIT-0 first paragraph with a BSD-like disclaimer ;-\

**Comment by swinslow** [comment]
+1 to add, as a broadly permissive / historical license that (as far as I can tell) doesn't match licenses currently on the license list.

For the name, agreed that tying it to .NET / dotnet doesn't seem to fit here. It looks like this license appears in other projects and products, e.g. https://go.dev/src/regexp/testdata/testregex.c, https://opensource.apple.com/source/Libc/Libc-1353.60.8/tests/regex/testregex.c.auto.html. `MIT-testregex` and "MIT testregex Variant" make sense to me to use here.

**Comment by jlovejoy** [comment]
+1 to add as well and agree with @swinslow name suggestion
