### ISSUE TITLE
New license request: SL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2023]
**1.** License Name: none
**2.** Short identifier: SL
**3.** License Author or steward: Toyoda Masashi
**4.** Comments: This looks like ultra permissive license, but it has "the above copyright notice has to appear in all copies" statement. 
In https://gitlab.com/fedora/legal/fedora-license-data/-/issues/162 we decided that it likely deserves its own id.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/243
**6.** URL(s): https://github.com/mtoyoda/sl/blob/master/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mtoyoda/sl

**Comment by jlovejoy** [comment]
here is the license text for convenience:

`
Copyright 1993,1998,2014 Toyoda Masashi (mtoyoda@acm.org)

Everyone is permitted to do anything on this program including copying,
modifying, and improving, unless you try to pretend that you wrote it.
i.e., the above copyright notice has to appear in all copies.
THE AUTHOR DISCLAIMS ANY RESPONSIBILITY WITH REGARD TO THIS SOFTWARE.
`

**Comment by swinslow** [comment]
+1 to add as a simple, historical / broadly permissive license. The identifier `SL` and the name "SL License" make sense to me given the context for this one.

**Comment by BrianInglis** [comment]
Mandate the identifier SL and similar confusable character sequences *always UPPERCASE* (or using some distinguishing markup, or a longer distinguished contraction) as *GH*, *SPDX*, etc. sites' CSS often use fonts with indistinguishable glyphs for commonly used alphanumeric characters. 
I often see no or minimal difference between e.g. *Sl SI S1 51* Sl SI S1 51 **Sl SI S1 51** `Sl SI S1 51` etc. especially below recommended 12-16 points sizes. 
Hopefully we never have an `SI` licence.
[I had `Sl` and `SI` swapped before correcting the order to put *SL* first in all cases!]

**Comment by copernicat** [comment]
Because of the lack of functionality of SL, I am uncertain whether it is found frequently enough in the supply chain to warrant its own SPDX identifier. Is there any data about how many distros it is present in?

**Comment by xsuchy** [comment]
It is in Fedora (the original report). It is in Debian https://packages.debian.org/sid/sl It is in EPEL. It is in Ubuntu https://packages.ubuntu.com/kinetic/sl

**Comment by jlovejoy** [comment]
Thanks for answering @copernicat 's question, @xsuchy - it is used quite widely!

I am +1 to add as well. I think we can mark this as accepted then.

**Comment by jlovejoy** [comment]
@BrianInglis - the chosen license id is all caps: SL, so if someone uses it in a source file, it would appear that way.
