### ISSUE TITLE
New license request: check-cvs [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2024]
**1.** License Name: FSFULLR-cvs
**2.** Short identifier: FSFULLR-cvs
**3.** License Author or steward: Unknown
**4.** Comments: This is the text of the license that is used in `cvs` project. It is close to https://spdx.org/licenses/FSFULLR.html but different enough to justify the new id.
Discussed in Fedora in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/202
**5.** License Request Url: http://tools.spdx.org/app/license_requests/244
**6.** URL(s): http://cvs.savannah.gnu.org/viewvc/cvs/ccvs/contrib/check_cvs.in?revision=1.1.4.3&view=markup&pathrev=cvs1-11-23#l2
**7.** OSI Status: Unknown
**8.** Example Projects: http://cvs.savannah.gnu.org/viewvc/cvs/ccvs/

**Comment by jlovejoy** [comment]
for convenience, this license states:

`Permission is granted to copy and/or distribute this file, with or without modifications, provided this notice is preserved.
`
whereas, FSFULLR states:
`This file is free software; the Free Software Foundation gives unlimited permission to copy and/or distribute it, with or without modifications, as long as this notice is preserved.`

**Comment by swinslow** [comment]
+1 to add as a historical and broadly permissive license.

For the name and identifier, although it is close to FSFULLR, I'm a little hesitant here to incorporate that ID into this version since it might imply that this particular variant originated with FSF (which seems to be the case for the other FSF* identifiers).

Perhaps `check-cvs` and "check-cvs License"? From a very cursory search I'm not finding other projects or files using this particular formulation, so maybe just use its name for this one?

**Comment by jlovejoy** [comment]
discussed on 7/13 call - accepted to add with @swinslow name suggestion

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

check-cvs License

## License ID

`check-cvs`

## XML markup

None

## Notes:

add a note indicating similarity to FSFULLR

## Additional rationale or notes on decision:

N/A

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@xsuchy - would you mind preparing the files for this one, now that it's been accepted by using the SPDX Online tool to generate the xml file by following this workflow? https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process

I know creating these files manually is probably super easy for you, but we have a GSoC student - @BassCoder2808 - working on approval this tooling and some of the updates have just been pushed. It'd be great to have some input from someone like yourself!
