### ISSUE TITLE
New license request: Texinfo-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2025]
**1.** License Name: Texinfo exception
**2.** Short identifier: Texinfo-exception
**3.** License Author or steward: Unknown
**4.** Comments: Discovered during Fedora license review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/206
This license is used in texinfo.tex file, which is packaged in automake Fedora package and bundled in many automake-driven sources.
It is at the end of GPL-3.0-or-later license there.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/245
**6.** URL(s): https://git.savannah.gnu.org/cgit/automake.git/tree/lib/texinfo.tex?h=v1.16.5#n23
**7.** OSI Status: Unknown
**8.** Example Projects: https://git.savannah.gnu.org/cgit/automake.git/tree/

**Comment by jlovejoy** [comment]
text of exception for convenience:
`As a special exception, when this file is read by TeX when processing
 a Texinfo source document, you may use the result without
 restriction. This Exception is an additional permission under section 7
 of the GNU General Public License, version 3 ("GPLv3").`

**Comment by swinslow** [comment]
+1 to add, to me this clearly meets the [License Exception principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md#license-exceptions) as a clear additional permission. The proposed name and ID look good to me.

**Comment by copernicat** [comment]
+1 to add, I agree with swinslow and also based on the assertion by xsuchy that it is "bundled in many automake-driven sources."
