### ISSUE TITLE
New license request: copyright-only-zeeff [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2027]
**1.** License Name: Copyright only - Zeeff
**2.** Short identifier: copyright-only-zeeff
**3.** License Author or steward: Jon Zeeff
**4.** Comments: Found during Fedora license review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/217
Present in project newsx
Found in
dbz/dbz-v3.c
dbz/dbz-v6.c
src/hash.c
src/mkcrc.c
src/mkcrc.rc
**5.** License Request Url: http://tools.spdx.org/app/license_requests/247
**6.** URL(s): ftp://ftp.tin.org/pub/news/utils/newsx/newsx-1.6.tar.gz
**7.** OSI Status: Unknown
**8.** Example Projects: ftp://ftp.tin.org/pub/news/utils/newsx/newsx-1.6.tar.gz

**Comment by jlovejoy** [comment]
text of license for convenience:
`Copyright 1988 Jon Zeeff (zeeff@b-tech.ann-arbor.mi.us) 
You can use this code in any manner, as long as you leave my name on it and don't hold me responsible for any problems with it.`

**Comment by swinslow** [comment]
+1 to add, as a very short and informal historical license grant statement.

I would lean towards `Zeeff` as the ID and `Zeeff License` as the name.

**Comment by jlovejoy** [comment]
+1 to add and to @swinslow name/ID suggestion
