### ISSUE TITLE
New license request: stunnel-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2039]
**1.** License Name: stunnel exception
**2.** Short identifier: stunnel-exception
**3.** License Author or steward: Unknown
**4.** Comments: This exception is used in stunnel project and has been found during Fedora License Review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/247
**5.** License Request Url: http://tools.spdx.org/app/license_requests/253
**6.** URL(s): https://github.com/mtrojnar/stunnel/blob/master/COPYING.md
**7.** OSI Status: Unknown
**8.** Example Projects: stunnel: upstream at https://www.stunnel.org/, browsable source code mirror at https://github.com/mtrojnar/stunnel/

**Comment by copernicat** [comment]
Although the project's website says it is an "OpenSSL exception", the text is quite different than the existing OpenSSL exceptions, and the SPDX diff tool shows no close matches. I agree with adding it. 
Do we want to include GPL in the license identifier as we have for other exceptions?

**Comment by richardfontana** [comment]
Note that there is likely a typo in the exception text (the "special exception" paragraph mentions LGPL in the first sentence and GPL in the second sentence).
