### ISSUE TITLE
MIT license with "and / or" instead of "and/or"

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2040]
I found a version of the MIT license in a source file for the netpbm project that is derived from an older version of a project called qoi which had the MIT presented with "and / or" rather than the standard "and/or", as you can see here: 
https://raw.githubusercontent.com/phoboslab/qoi/553eae423acba5e35fb036da4473925b4d54e94a/qoiconv.c
That upstream project has since switched to SPDX-License-Identifier lines in source files and a typographically standard version of the MIT license, but it's more likely than not that this will never propagate to the netpbm project. 

If I'm not mistaken, the "and / or" variant does not match SPDX MIT so I would propose a markup change.

**Comment by jlovejoy** [comment]
as per https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b4-whitespace - the whitespace doesn't matter for matching purposes, so this is indeed a match to MIT

will close issue :)

**Comment by richardfontana** [comment]
@jlovejoy I think you are reading https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b4-whitespace too broadly. It says: 
> All whitespace should be treated as a single blank space.

The way I read this guideline, "and / or" is the same as "and     /    or", but it is *not* the same as "and/or" since the latter has no whitespace.

**Comment by jlovejoy** [comment]
ah, good point @richardfontana - I suppose we can then accommodate these variations with markup as I don't think there is any substantive difference b/w "and/or" and "and / or"

**Comment by jlovejoy** [comment]
@richardfontana - is this associated with a Fedora gitlab issue?
