### ISSUE TITLE
New license request: CC-BY-3.0-AU [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by JoCroucher** [spdx/license-list-XML#2042]
**1.** License Name: Creative Commons Attribution 3.0 Australia
**2.** Short identifier: CC-BY-3.0-AU
**3.** License Author or steward: Creative Commons
**4.** Comments: A) CC BY 3.0 AU does not match a licence already on the SPDX License List.
B) Not an OSI-approved license.
C) Not a software license that applies only to executables and do not provide for the availability of the source code.
D) The license has identifiable and stable text; it is not in the midst of drafting. See: https://creativecommons.org/licenses/by/3.0/au/legalcode
E) Creative Commons, is committed to not modifying after addition to the list and to versioning new versions in the future.
1. The license substantially complies with an open source definition (as a Creative Commons Suite Licence)
2. The license is structured to be generally usable by anyone and is published on the Creative Commons website.
3. The license remains in common usage in Australia and is visible on numerous government websites and used as a licence for many open datasets.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/254
**6.** URL(s): 
**7.** OSI Status: Approved
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/659a59fb-d774-45ab-b86a-9a7b56643b86.png

**Note:**
The license closely matched with the following license ID(s): CC-BY-NC-2.5

**Comment by jlovejoy** [comment]
given our precedent to add CC licenses that are country specific as they are requested, I'm +1 to add. This is another CC-BY-3.0 variant for Australia. We already have CC-BY-2.5-AU and also have CC-BY-3.0, Germany, Netherlands, IGO, and US variants.

**Comment by copernicat** [comment]
+1 to add

**Comment by swinslow** [comment]
+1 to add, marking this as approved given the above approvals and our standard practice towards CC variants.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Creative Commons Attribution 3.0 Australia

## License ID

CC-BY-3.0-AU

## XML markup

List structure / bullets and optional text as used for other CC-BY-3.0 variants

## Notes:

N/A

## Additional rationale or notes on decision:

N/A

## Next steps ##

If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@JoCroucher  - would you feel comfortable making the PR for this license? See link above for process

**Comment by jlovejoy** [comment]
moving to 3.23 as we don't have a PR for this yet and the 3.22 release is about to go out

**Comment by jlovejoy** [comment]
PR now merged so closing this issue
