### ISSUE TITLE
New license request: Add older version of BSD-Attribution-HPND-disclaimer

### ISSUE THREAD

**Issue by mosvald** [spdx/license-list-XML#2044]
### How license meets inclusion principles

There is already an existing and approved license https://spdx.org/licenses/BSD-Attribution-HPND-disclaimer.html with the same text, but a different address, and is from 2017. The one I would like to get included predates it (1994-2016).

### License Name

BSD with Attribution and HPND disclaimer (1994)

### Suggested short identifier

BSD-Attribution-HPND-disclaimer-1994

### URL to license text

https://github.com/cyrusimap/cyrus-imapd/blob/master/COPYING

### OSI Status

I don't know

### License author or steward

Carnegie Mellon University

### URL to project(s) that use license

https://github.com/cyrusimap/cyrus-imapd/

**Comment by jlovejoy** [comment]
Looks like the only difference b/w this and `BSD-Attribution-HPND-disclaimer` is that this omits the word "other" in the third clause. 

`For permission or any _other_ legal details, please contact`

Other than that, there are some differences in the contact info, but that is ripe for markup.

So I guess the question is - does the existence or absence of "other" make a substantive difference or can we mark that word as optional?

I'm thinking it could be optional

**Comment by swinslow** [comment]
@jlovejoy I agree, "other" can be optional here. I don't see it as any substantive difference. Even if it were, "please contact" feels like a request rather than a license condition, so in the context I don't see any problem with accommodating this as an optional text item.
