### ISSUE TITLE
New license request: MPEG-Software-Simulation [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2049]
**1.** License Name: MPEG Software Simulation Group Disclaimer of Warranty
**2.** Short identifier: MPEG-Software-Simulation
**3.** License Author or steward: Unknown
**4.** Comments: This license is presented in netpbm package and was found during the Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/258
**5.** License Request Url: http://tools.spdx.org/app/license_requests/258
**6.** URL(s): https://sourceforge.net/p/netpbm/code/HEAD/tree/super_stable/converter/ppm/ppmtompeg/jrevdct.c#l1189
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceforge.net/p/netpbm/

**Comment by BrianInglis** [comment]
Looks like typos in the original, which should be patched to correct, as the conditions and warranties may be considered to not have been properly disclaimed: 

> The MPEG Software Simulation Group disclaims any and all warranties, 
whether express, implied, or ~statuary,~ **statutory,** including any implied warranties ~or~ **of** merchantability or of fitness for a particular purpose. 

[Implied warranty: Merchantability](https://en.wikipedia.org/wiki/Implied_warranty#Merchantability)

Does that mean MPEG statuary grants warranties on this software? 
[ISO and IEC expert group wins another Emmy Award: MPEG file format subgroup recognized for essential contribution to video and audio technology](https://www.iso.org/news/ref2741.html) and 
[Record-breaking MPEG takes two Emmy Awards: Two new Emmys go to IEC and ISO for their ground-breaking MPEG standards](https://www.iso.org/contents/news/2022/04/record-breaking-mpeg-takes-two-e.html) 
 ;^>

**Comment by Pizza-Ria** [comment]
+1 to add with reiteration of above comments + the Fedora analysis by R.F.  The only question is whether the whole thing (+ disclaimers) goes in there or if just the base "grant" is the license with the disclaimer language listed as optional.

**Comment by jlovejoy** [comment]
I'd put the text that @xsuchy put submitted and what @swinslow pasted above.

note: @xsuchy - if you use the submission tool to create the files, it's going to mess up the XML b/c of how the text got pasted in (not sure how to explain this, but would be good to document so that it might be avoided) not sure if @BassCoder2808 has any thoughts on that.

@BrianInglis - we don't correct spelling errors... we take the license text as we find it. Unless there are instances "in the wild" that are correct, then we'd accommodate both spelling "options" :)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

MPEG Software Simulation Group Disclaimer of Warranty

## License ID

MPEG-Software-Simulation

or should we shorten to `MPEG-disclaimer` ?

## XML markup

none

## Notes:

none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
marking as accepted, but would like some thoughts on id - we can just go with what @xsuchy suggested or maybe something shorter??

@richardfontana @swinslow - opinions?

**Comment by BassCoder2808** [comment]
> I'd put the text that @xsuchy put submitted and what @swinslow pasted above.
> 
> note: @xsuchy - if you use the submission tool to create the files, it's going to mess up the XML b/c of how the text got pasted in (not sure how to explain this, but would be good to document so that it might be avoided) not sure if @BassCoder2808 has any thoughts on that.
> 
hI @jlovejoy , yes the most likely reason is how the text got pasted, The likely cause is `*\` at the start of the license text as seen on the online submission tool 
https://tools.spdx.org/app/edit_license_xml/258/

**Comment by richardfontana** [comment]
Regarding the identifier, I note scancode calls this 'MPEG SSG License' and 'mpeg-ssg' https://scancode-licensedb.aboutcode.org/mpeg-ssg.html

**Comment by jlovejoy** [comment]
> Regarding the identifier, I note scancode calls this 'MPEG SSG License' and 'mpeg-ssg' https://scancode-licensedb.aboutcode.org/mpeg-ssg.html

ugh. I actually kind of like MPEG-SSG as an identifier better (scancode uses all lowercase, but given that MPEG uses all caps themselves, I'd go with that)

But then spell it out in the name... this PR has been merged, but the release hasn't been pushed.... worth updating?
