### ISSUE TITLE
New license request: BSD-3-Clause-HP [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by zdohnal** [spdx/license-list-XML#2053]
**1.** License Name: Hewlett-Packard BSD variant license
**2.** Short identifier: BSD-3-Clause-HP
**3.** License Author or steward: HP
**4.** Comments: It is BSD-3-Clause license with several changes by HP and the changes does not break open source principles. Found during license review in Fedora - https://gitlab.com/fedora/legal/fedora-license-data/-/issues/267 .

The license in COPYING file is without 'All rights reserved', but the source and header files have it, so I've copied the text from the source instead of from COPYING.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/260
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/77422b01-ae9b-4a52-a76d-8680ede4127f.png

**Note:**
The license closely matched with the following license ID(s): BSD-3-Clause

**Comment by bsdimp** [comment]
'All Rights Reserved' is part of the copyright notice, and not part of the license, per the Buenos Aires convention (https://en.wikipedia.org/wiki/Buenos_Aires_Convention). It was required on all copyright notices to preserve rights in certain Latin American countries from 1911 until the Berne convention was ratified obsoleting it in the year 2000. BSD has this phrase in it because the regents wanted to protect their rights in Central America. Since the first BSD licenses dated to the early 1980s (not ratified by the US until 1989, for example). We should move that phrase to the copyright notice given this historic detail. It has been removed from follow-on BSD projects like FreeBSD as well. See last bullet under Policy in https://www.freebsd.org/internal/software-license/ for example. If not already in that, we should make it optional text in the copyright notice.

**Comment by richardfontana** [comment]
I think the one notable difference wrt BSD-3-Clause is that the disclaimer paragraph limitation of liability sentence adds "patent infringement" to the enumeration of things for which no liability is asserted.

**Comment by jlovejoy** [comment]
@richardfontana - I think you are correct. For reference here, in the "including, but not limited to..." parenthetical - this includes "patent infringement" whereas BSD-3-Clause does not. This begs the question of how operative a non-exhaustive list of examples is? Lawyers, thoughts? @copernicat @richardfontana @swinslow @Pizza-Ria 

```
IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED 
TO, _PATENT INFRINGEMENT_; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; 
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED ...
```

**Comment by jlovejoy** [comment]
labeling it both new license request and XML markup, to show I'm not sure which it is and need discussion!

**Comment by bsdimp** [comment]
Is this close at all to other bsd plus patent disclaimers? I don't see one, but you guys are way better at finding these than i

**Comment by richardfontana** [comment]
I don't think it should be treated as equivalent to BSD-3-Clause. This reminds me of the issue of nonstandard warranty disclaimer statements in GPL notices in Linux kernel source files.

**Comment by swinslow** [comment]
I agree, I would not want to include this as matching standard BSD-3-Clause via markup.

If I were interpreting the inclusion of "patent infringement" explicitly in that list, personally I would likely conclude that there's no difference between including it or not. But that's something that is a legal interpretation or conclusion, and I think goes over the line of what we would treat as the same license for SPDX matching purposes.

I'm +1 to add it as a separate license ID. I'm kind of okay with using `BSD-3-Clause-HP` as the only other instances of this that I'm finding (from a brief search) also appear to originate from HP. Alternatively `BSD-3-Clause-hplip` might make sense as it seems like the instances I see are all part of the hplip package, e.g. https://codesearch.isocpp.org/actcd19/main/h/hplip/hplip_3.17.7+repack0-3/prnt/hpijs/dj630.h

**Comment by jlovejoy** [comment]
sounds good, thanks for the comments @swinslow and @richardfontana - I'll mark this as accepted now
