### ISSUE TITLE
New license request: glibc startup code license (LGPL with old GCC exception)

### ISSUE THREAD

**Issue by fweimer-rh** [spdx/license-list-XML#2055]
### How license meets inclusion principles

I believe this is actually a variant of *LGPL-2.1-or-later WITH GCC-exception-2.0*, but some folks believe that the exception text in SPDX has missing alternatives before it can match.

```
   Copyright (C) 1997-2023 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   In addition to the permissions in the GNU Lesser General Public
   License, the Free Software Foundation gives you unlimited
   permission to link the compiled version of this file with other
   programs, and to distribute those programs without any restriction
   coming from the use of this file.  (The Lesser General Public
   License restrictions do apply in other respects; for example, they
   cover modification of the file, and distribution when not linked
   into another program.)

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.
```

There is a variant of this license which includes an additional paragraph:

```
   Copyright (C) 2001-2023 Free Software Foundation, Inc.
   This file is part of the GNU C Library.

   The GNU C Library is free software; you can redistribute it and/or
   modify it under the terms of the GNU Lesser General Public
   License as published by the Free Software Foundation; either
   version 2.1 of the License, or (at your option) any later version.

   In addition to the permissions in the GNU Lesser General Public
   License, the Free Software Foundation gives you unlimited
   permission to link the compiled version of this file with other
   programs, and to distribute those programs without any restriction
   coming from the use of this file. (The GNU Lesser General Public
   License restrictions do apply in other respects; for example, they
   cover modification of the file, and distribution when not linked
   into another program.)

   Note that people who make modified versions of this file are not
   obligated to grant this special exception for their modified
   versions; it is their choice whether to do so. The GNU Lesser
   General Public License gives permission to release a modified
   version without this exception; this exception also makes it
   possible to release a modified version which carries forward this
   exception.

   The GNU C Library is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public
   License along with the GNU C Library; if not, see
   <https://www.gnu.org/licenses/>.
```

This raises further concerns whether this is still *LGPL-2.1-or-later WITH GCC-exception-2.0* (although if that's still a match, this is still fine with me of course).

Downstream discussion: https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/VKN5IU3HOB2LZCLWHAU7CNTOLLYRGLES/

### License Name

LGPL-2.1-or-later WITH GCC-exception-2.0

### Suggested short identifier

LGPL-2.1-or-later WITH GCC-exception-2.0

### URL to license text

https://sourceware.org/git/?p=glibc.git;a=blob;f=csu/abi-note.c;h=c2ec208e94fbe91f63d3c375bd254b884695d190;hb=HEAD

### OSI Status

Approved

### License author or steward

FSF

### URL to project(s) that use license

https://sourceware.org/git/gitweb.cgi?p=glibc.git

**Comment by jlovejoy** [comment]
<img width="627" alt="image" src="https://github.com/spdx/license-list-XML/assets/5048659/f04588f5-00d4-45fc-b42c-f9b117b31a16">

**Comment by jlovejoy** [comment]
added image above of difference from GCC-exception-2.0

My initial inclination is that this is not really ripe for markup and probably needs to be a new exception.

I am in favor of adding it, given it's significance in terms of use

**Comment by jlovejoy** [comment]
also see https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/VKN5IU3HOB2LZCLWHAU7CNTOLLYRGLES/

@fweimer-rh - is there a corresponding Fedora Gitlab issue?

**Comment by jlovejoy** [comment]
please make a Fedora Gitlab issue to track this - if it's not a match as per SPDX guidelines to GCC-exception-2.0, then that would be the wrong SPDX id to use. Also, if it gets added to SPDX as a new exception/id, we will also need to add a TOML file there :)

**Comment by Pizza-Ria** [comment]
Making it a new exception makes sense although I would accept both variants above as the same exception and just make the paragraph starting with "Note" as optional language since it doesn't add/subtract but just seems to explain what it means to have the option to use or not use this exception.  +1 for a SINGLE new exception.

**Comment by jlovejoy** [comment]
going off of @Pizza-Ria comment above, plus my revelation as to the matching variants noted above in my edited comment - would we feel comfortable adding the second paragraph as optional?

or does the inclusion of the second paragraph justify a new exception?

**Comment by swinslow** [comment]
Steve to add regular expressions for matching any of "Library General", "Lesser General" or "General" in both license references.

**Comment by swinslow** [comment]
To add a separate issue for "combined?" in last line of XML at https://github.com/spdx/license-list-XML/blob/main/src/exceptions/GCC-exception-2.0.xml, to track and fix that separately

@jlovejoy to add a separate issue for the second version given above, with the additional paragraph

**Comment by jlovejoy** [comment]
@fweimer-rh - I don't see where the second variant is from, but we would likely enter that as a new exception. Can you submit via https://tools.spdx.org/app/submit_new_license/ and include a link to where this is "in the wild" - thanks!

**Comment by jlovejoy** [comment]
this issue is for the first exception variant above and can be accommodated via markup (comments got a bit confusing)
