### ISSUE TITLE
New license request: python-ldap [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by zdohnal** [spdx/license-list-XML#2056]
**1.** License Name: Unknown
**2.** Short identifier: Unknown
**3.** License Author or steward: Unknown
**4.** Comments: The license was found during license scan in Fedora - it is present in hplip package and it was reported to fedora-license-data as https://gitlab.com/fedora/legal/fedora-license-data/-/issues/269 .

The file originates from python-ldap project, which does not have a name for the license either - https://github.com/python-ldap/python-ldap/blob/main/LICENCE .
**5.** License Request Url: http://tools.spdx.org/app/license_requests/261
**6.** URL(s): https://github.com/zdohnal/hplip/blob/master/base/ldif.py, https://sourceforge.net/projects/hplip/files/hplip/3.23.5/hplip-3.23.5.tar.gz/download
**7.** OSI Status: Unknown
**8.** Example Projects: https://developers.hp.com/hp-linux-imaging-and-printing

**Comment by richardfontana** [comment]
To clarify something for those who didn't read the Fedora issue, the project has no license text other than:
```
The python-ldap package is distributed under Python-style license.

Standard disclaimer:
   This software is made available by the author(s) to the public for free
   and "as is".  All users of this free software are solely and entirely
   responsible for their own choice and use of this software for their
   own purposes.  By using this software, each user agrees that the
   author(s) shall not be liable for damages of any kind in relation to
   its use or performance. The author(s) do not warrant that this software
   is fit for any purpose.
```
And the project separately says:
> The current maintainers assume that the license is the sentence that refers to "Python-style license" and assume this means a highly permissive open source license that only requires preservation of the text of the LICENCE file (including the disclaimer paragraph).

I.e. the current maintainers at least don't seem to interpret "Python-style" as a "same as Python" sort of licensing shorthand.

**Comment by jlovejoy** [comment]
updated issue title to make it easier to tie back to Fedora issue :)

**Comment by zdohnal** [comment]
I'm not sure whether it is relevant, but to clarify - python-ldap project, which is the original author of ldif.py file which hplip took, has two licenses, which are applied based on time when the code was accepted or based on approval of original author - so in the end, python-ldap has parts which are under MIT license (which are newer contributions or original contributors approved the license change), and some parts which are under the reported license above. But the ldif.py file stays under this old license, which I wasn't able to find license identifier for.

The hplip project itself (the project which is in Fedora and has ldif.py in its sources) uses several licenses as well, if it matters.

**Comment by richardfontana** [comment]
Right, 'HPLIP' would not be a good identifier here. 'python-ldap' would be better.

**Comment by droideck** [comment]
@mistotebe and I are python-ldap maintainers.
Personally, I'm okay with `python-ldap` name for the license. @mistotebe ?

Also, should we use https://github.com/python-ldap/python-ldap URL for the license instead?

**Comment by mistotebe** [comment]
`python-ldap` sounds appropriate if that's where the license originated, sure.

**Comment by Pizza-Ria** [comment]
I honestly don't know what to do with this language "The python-ldap package is distributed under Python-style license."  I agree it is fairly permissive but it also says that it was tested with Python 2.0 so I'm assuming that means the Python 2.0 License would have applied to that test???  That includes the BeOpen and CNRI - is that what is intended by a Python-style license?  I'm not sure that this is a specific license itself but more permission to use a python-ish license???  Currently disinclined to add.

**Comment by richardfontana** [comment]
@Pizza-Ria the basic issue here is, what does "Python-style license" mean in this case. One possible interpretation is how I'd usually approach a case of a (non-PSF) Python library being licensed as "Python", which is to suppose that the top license in the Python-2.0.1 stack applies (the PSF-2.0 license) but with all the references to "Python Software Foundation" implicitly substituted. In the case of python-ldap, however, we have what I think is a long period of the maintainers applying a looser interpretation. The maintainers note that it is basically not possible to change the license of this project and they are clearly doing their best to give it a reasonable and flexible reading.

**Comment by jlovejoy** [comment]
@droideck @mistotebe - I'm guessing that the statement `The python-ldap package is distributed under Python-style license` is something you "inherited"? 

As package maintainers, would making a call as to what that is supposed to mean (today) be possible?

It seems like it could mean: 
1) the "Python-style license" is the text below labeled "Standard disclaimer" and there's nothing more to consider
or
2) "Python-style license" refers to an existing license used in Python which applies in addition to the text below "Standard disclaimer"

**Comment by richardfontana** [comment]
@jlovejoy See my [earlier comment](https://github.com/spdx/license-list-XML/issues/2056#issuecomment-1659152763) - they have expressed their interpretation on what the license means.

**Comment by jlovejoy** [comment]
ah yes. that is still a bit unclear though? Wouldn't "only requires preservation of the text of the LICENCE file (including the disclaimer paragraph)" essentially make the statement re: "Python-style license" meaningless?

**Comment by richardfontana** [comment]
I think what they're saying is, they assume that the original licensors didn't intend "Python-style license" to mean "the actual PSF-2.0 [or Python-2.0.1, etc.] license, with implied licensor name substitutions". Rather, they are assuming the original licensors had a more vague idea in their heads of having a conventional (for the times) permissive license policy. I think that's a reasonable interpretation under the circumstances. 

Anyway, I'm not sure it matters for SPDX license inclusion purposes?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Python ldap License

## License ID

Python-ldap

## XML markup

none

## Notes:

none

## Additional rationale or notes on decision:

one question on name and id is LDAP usually capitalized? @richardfontana - do you know?

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by richardfontana** [comment]
@jlovejoy LDAP is usually capitalized when referred to as a protocol, but in this case, the reference is to a project known as "python-ldap", not "python-LDAP": 
https://www.python-ldap.org/en/python-ldap-3.4.3/  
https://pypi.org/project/python-ldap/  
https://github.com/python-ldap/python-ldap 
Therefore the identifier should be `python-ldap`.
