### ISSUE TITLE
New license request: Pbmplus [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2065]
**1.** License Name: Pbmplus License
**2.** Short identifier: Pbmplus
**3.** License Author or steward: Unknown
**4.** Comments: This package is in package netpbm that is presented in Fedora, Debian and likely others.
It has been found during License Review in Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/253

@rfontana opinion:
This is a simple, permissive legacy license, similar to the HPND template but I think the last sentence doesn't fit the template.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/262
**6.** URL(s):  https://sourceforge.net/p/netpbm/code/HEAD/tree/super_stable/netpbm.c#l8
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceforge.net/p/netpbm

**Comment by xsuchy** [comment]
Text license:
```
** Copyright (C) 1991 by Jef Poskanzer.
**
** Permission to use, copy, modify, and distribute this software and its
** documentation for any purpose and without fee is hereby granted, provided
** that the above copyright notice appear in all copies and that both that
** copyright notice and this permission notice appear in supporting
** documentation.  This software is provided "as is" without express or
** implied warranty.
```

**Comment by jlovejoy** [comment]
This is a match to HPND (as per comma markup added in #2113 but this line:
`This software is provided "as is" without express or implied warranty.`
is only the second sentence of that optional chunk of text and missing
`<copyright holder> makes no representations about the suitability of this software for any purpose.`

Which I suspect makes this a new/different license??

**Comment by swinslow** [comment]
From https://github.com/spdx/license-list-XML/blob/b6cecd96666d417e6314600156ff2ab680f79a76/src/HPND.xml#L33-L36 it looks like our current markup either requires both sentences to be present, or both to be absent.

I would rather split the `<optional>` section to separate it for each sentence, so that each one individually would be optional.

**Comment by swinslow** [comment]
After further discussion on the SPDX legal team call, I'm changing my mind. Please disregard my comment above  :)

Let's stick with what OSI has currently posted as "HPND", and not try to pull it apart. This probably does warrant a separate ID.

**Comment by swinslow** [comment]
# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - Pbmplus variant

## License ID

HPND-Pbmplus

## XML markup

None

## Notes:

Explain that this is nearly a match for HPND, but has only one of the two sentences in this particular optional tag for HPND

## Additional rationale or notes on decision:

See comments above re: why not looping in as just 'HPND'

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
