### ISSUE TITLE
New license request: BSD-Advert-Ackn-No-Redis [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by michal-josef-spacek** [spdx/license-list-XML#2066]
**1.** License Name: BSD Advertising Acknowledgement License Without Redist Acknowledgment
**2.** Short identifier: BSD-Advert-Ackn-No-Redis
**3.** License Author or steward: Unknown
**4.** Comments: I found in the license review process in Fedora another BSD license which is similar to BSD-Advertising-Acknowledgement (see https://spdx.org/licenses/BSD-Advertising-Acknowledgement.html), but without a 4 clause.

License is used in two Perl packages in Fedora from the same author.

Link to Fedora review process: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/272
**5.** License Request Url: http://tools.spdx.org/app/license_requests/263
**6.** URL(s): https://metacpan.org/release/DPARIS/Crypt-DES-2.07/source/COPYRIGHT
**7.** OSI Status: Unknown
**8.** Example Projects: https://fedoraproject.org/, https://src.fedoraproject.org/rpms/perl-Crypt-DES, https://src.fedoraproject.org/rpms/perl-Crypt-IDEA

**Comment by Pizza-Ria** [comment]
I'm OK with adding the license but I don't understand the License Name or Short Identifier.  

BSD Advertising Acknowledgement License Without Redist Acknowledgment and BSD-Advert-Ackn-No-Redis for the missing clause "4. Neither the name of the University nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.¶"

1.  It seems to be more a "Minus Endorsement Prohibition"
2.  For the short-identifier - shortening Redist to Redis seems confusion since RSAL refers to the Redis Source Available License and that's where my brain goes when I see the word Redis.

**Comment by jlovejoy** [comment]
+1 to add as well. the top part also seems to add some specifics as to attribution

for a name, how about `BSD-Advertising-Systemics`
or `BSD-Systemics'

since it uses the Systemics name in it and I'm kind of doubting we'll find this used by anyone else...

**Comment by swinslow** [comment]
+1 to add, as a separate license ID. To @jlovejoy's point, given the added language here (above "Redistribution and use in source...") I don't think this could be a match to any of the BSD variants currently on the list, as far as I can tell.

I would probably go with `BSD-Systemics` as the ID and "Systemics BSD variant license" as the name, with the naming aligning with the similar "Lawrence Berkeley National Labs BSD variant license" already on the list.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Systemics BSD variant license

## License ID

BSD-Systemic

## XML markup

none

## Notes:

_add any information that is to be included in the Notes field_



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process). 

@michal-josef-spacek - can you create a PR now that this has been accepted?

**Comment by michal-josef-spacek** [comment]
> I'm OK with adding the license but I don't understand the License Name or Short Identifier.
> 
> BSD Advertising Acknowledgement License Without Redist Acknowledgment and BSD-Advert-Ackn-No-Redis for the missing clause "4. Neither the name of the University nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.¶"
> 
> 1. It seems to be more a "Minus Endorsement Prohibition"
> 2. For the short-identifier - shortening Redist to Redis seems confusion since RSAL refers to the Redis Source Available License and that's where my brain goes when I see the word Redis.

Probably yes. I created PR as I understand the license. But I am not a specialist for licenses :-)

**Comment by michal-josef-spacek** [comment]
@jlovejoy BSD-Systemic or BSD-Systemics? :-)

**Comment by jlovejoy** [comment]
@michal-josef-spacek  good catch! yes, Systemics - will update accordingly
