### ISSUE TITLE
New license request: FBM [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2067]
**1.** License Name: FBM License
**2.** Short identifier: FBM
**3.** License Author or steward: Unknown
**4.** Comments: This is an ancient permissive FOSS license found in at least one package in Fedora Linux.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/264
**6.** URL(s): https://github.com/SWI-Prolog/packages-xpce/blob/master/src/img/gifwrite.c#L22
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/SWI-Prolog/

**Comment by richardfontana** [comment]
Reason for the proposed identifier: as far as I can tell, this license originally appeared on a library called 'FBM' (Fuzzy Bitmap, I think).

**Comment by jlovejoy** [comment]
license text:

Portions of this code Copyright (C) 1989 by Michael Mauldin.

Permission is granted to use this file in whole or in
part for any purpose, educational, recreational or commercial,
provided that this copyright notice is retained unchanged.
This software is available to all free of charge by anonymous
FTP and in the UUNET archives.

**Comment by jlovejoy** [comment]
this does not match anything currently on the SPDX License List.


+1 to add given it's used in a major distro and is already considered free/open

**Comment by Pizza-Ria** [comment]
+1 @jlovejoy's comments.

**Comment by jlovejoy** [comment]
thanks @Pizza-Ria!

@richardfontana - are you good with the name you proposed? seems fine to me...
do you want to have a go at making the files?

**Comment by richardfontana** [comment]
I am good with that name. I will try to make the files!

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

FBM License

## License ID

FBM

## XML markup

none

## Notes:

none



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
FYI - @richardfontana - if you use the online tool, it looks like a stray * got copied into the text of the license, which will add a list, list item, and bullet where they are not needed... 

we do have some great updates to the online submission tool from our GSoC student, but I don't think the tools have been updated yet...
