### ISSUE TITLE
New license request: texlive-swrule [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2068]
**1.** License Name: texlive-swrule License
**2.** Short identifier: texlive-swrule
**3.** License Author or steward: Unknown
**4.** Comments: This is a simple nonstandard permissive license found in the TeXLive distribution and in Linux distributions like Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/265
**6.** URL(s): https://ctan.math.utah.edu/ctan/tex-archive/macros/generic/misc/swrule.sty
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://ctan.math.utah.edu/ctan/tex-archive/macros/generic/misc/swrule.sty

**Comment by jlovejoy** [comment]
license text:
`The style package is copyrighted but may be used and extended in any way, as long as a pointer to the original author is maintained. The author is not liable for any problem that may or may not result from using this package. Use at your own risk.`
 
made some notes on all texlive submissions here: https://docs.google.com/document/d/1xqSwTfJJ7btkhbblrIAZxOxv0iZPmAMGar9rU7DLKC8/edit

this one is definitely unique. searched via site:https://spdx.org/licenses/  "package is copyrighted but may be used and extended in any way" and no matches

**Comment by jlovejoy** [comment]
+1 to add considering used in Fedora and probably other distros

**Comment by swinslow** [comment]
+1 to add

**Comment by swinslow** [comment]
I'm good with the name and ID @richardfontana has proposed. From some quick searches I'm not seeing any use of this license text separate from this particular instance.

**Comment by richardfontana** [comment]
I wonder if just using `swrule` would be a better identifier, similar to my comments on the other texlive submitted licenses.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

swrule License

## License ID

swrule

## XML markup

none

## Notes:

none

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
