### ISSUE TITLE
New license request: Kastrup

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2069]
**1.** License Name: texlive-Kastrup
**2.** Short identifier: texlive-Kastrup
**3.** License Author or steward: David Kastrup
**4.** Comments: This is a simple permissive FOSS license found in the TeXLive distribution and in Linux distributions like Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/266
**6.** URL(s): https://ctan.math.utah.edu/ctan/tex-archive/macros/generic/kastrup/binhex.dtx
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://ctan.math.utah.edu/ctan/tex-archive/macros/generic/kastrup/binhex.dtx

**Comment by jlovejoy** [comment]
license text:
```
Copyright(c) 2001 by David Kastrup
Any use of the code is permitted as long as this copyright 
notice is preserved in the code.
```

no matches via license-diff
No matches in Check License
No matches via site:https://spdx.org/licenses/  "Any use of the code is permitted "

+1 to add using name as suggested

**Comment by richardfontana** [comment]
Maybe a better identifier would be `binhex` :)

**Comment by swinslow** [comment]
+1 to add, fine with "Kastrup" as ID and "Kastrup License" as name?

**Comment by jlovejoy** [comment]
this is accepted, but not sure on naming as @swinslow  suggested `Kastrup` and @richardfontana suggested `binhex` and both are sort of viable given the location... tie breaker?

**Comment by xsuchy** [comment]
+1 to Kastrup :)
