### ISSUE TITLE
New license request: texlive-ulem [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2070]
**1.** License Name: texlive-ulem
**2.** Short identifier: texlive-ulem
**3.** License Author or steward: Unknown
**4.** Comments: This is a simple permissive FOSS license found in the TeXLive distribution and in Linux distributions like Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/267
**6.** URL(s): https://mirrors.ctan.org/macros/latex/contrib/ulem/README
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://mirrors.ctan.org/macros/latex/contrib/ulem

**Comment by Pizza-Ria** [comment]
I only see a 44% match to [TermReadKey License](https://spdx.org/licenses/TermReadKey.html) but I'm having a hard time believing this permissive license doesn't have a better (inconsequential delta) with something else already in SPDX.

**Comment by swinslow** [comment]
Text of license:

> Copyright 1989-2019 by Donald Arseneau (Vancouver, Canada; asnd@triumf.ca)
> 
>   This software may be freely transmitted, reproduced, or modified for any
>   purpose provided that this copyright notice is left intact.

**Comment by Pizza-Ria** [comment]
Contacted Donald Arseneau at the listed email about potentially relicensing this project under something more recognizable.  Will give it a week and if no response then I'm a +1 to add this.

**Comment by jlovejoy** [comment]
for more info on this license, see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/117

**Comment by richardfontana** [comment]
I overlooked the fact that there are three close variants that were submitted in the referenced Fedora issue:
```
This software may be freely transmitted, reproduced, or modified for any purpose provided that this copyright notice is left intact.
```
```
These macros may be freely used, transmitted, reproduced, or modified
provided that the copyright notice and this permission is retained.
```
and
```
This software may be freely used, transmitted, reproduced, or modified provided that the copyright notice and this permission is retained.
```

I don't know if SPDX would see "retained" and "left intact" as being equivalent for SPDX matching purposes.

**Comment by richardfontana** [comment]
Also Tom Callaway suggested `texlive-Arseneau` as the identifier.

**Comment by richardfontana** [comment]
Sorry but I have now split this up into three separate issues in fedora-license-data because of the possibility that SPDX will view there being (at least) three different texlive Arseneau licenses. So because this has become horribly confusing I am going to close this issue and open 3 new issues. :)
