### ISSUE TITLE
New license request: texlive-slideshow [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2071]
**1.** License Name: texlive-slideshow
**2.** Short identifier: texlive-slideshow
**3.** License Author or steward: Unknown
**4.** Comments: This is a simple permissive license found in the TeXLive distribution and in Linux distributions like Fedora. Fedora has determined that it meets its standards as FOSS.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/268
**6.** URL(s): https://mirror.las.iastate.edu/tex-archive/graphics/metapost/contrib/macros/slideshow/slideshow.mp
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://mirror.las.iastate.edu/tex-archive/graphics/metapost/contrib/macros/slideshow/slideshow.txt

**Comment by jlovejoy** [comment]
license text: 
```
Copyright 2001, Patrick TJ McPhee
everyone is welcome to use this code for any purpose, to modify it, and to copy it in whole or in part for use in other macro sets, with the conditions that this copyright notice be preserved with any significant portion of the code, and that modifications to this file be clearly marked.
```
No matches in Check License
No matches via site:https://spdx.org/licenses/  "everyone is welcome to use this code for any purpose"

**Comment by jlovejoy** [comment]
+1 to add

**Comment by richardfontana** [comment]
About naming, for this and other unique licenses coming out of reviews of TeX Live stuff: The idea of prefixing "texlive- " I think originated with some issues submitted at fedora-license-data by Tom Callaway. I don't know whether having the SPDX identifier for these things use a "texlive-" prefix is appropriate. It is a little odd since TeXLive is basically an upstream "distribution" collecting tons of stuff; not to mention that "texlive-" is in a sense an inaccurate rendering of "TeX Live" (which reflects package naming downstream in Fedora - not sure about other Linux distros; in the Fedora context I'm not sure anyone would refer to it as "TeX Live" idiomatically).

**Comment by jlovejoy** [comment]
Thanks @richardfontana for all the insight and help on naming of these... I know how much you enjoy naming licenses :)

**Comment by Pizza-Ria** [comment]
?  The sample project listed states that "the package assists in producing slides with dimensions
6.4 inches wide by 4.8 inches high, which the user is then expected to convert into a pdf file using ghostscript as a PS distiller."   Then, "After creating all the metapost figures, run the file `jobname'.ps through ghostscript, using the pdfwrite device. ghostscript comes with a batch file called ps2pdf which can be used to do this, but a sufficient command line is:
   gs -sDEVICE=pdfwrite -sOutputfile=jobname.pdf -dNOPAUSE jobname.ps quit.ps"

This SOUNDS and LOOKS to me like the ghostscript call is completely separate (I looked through the .mp files and only saw one other reference to ghostscript in a comment) but I defer to others with more expertise just to be sure this isn't a permissive license with a call to Ghostscript embedded in it.  As long as my assumption is correct then I'm +1 to add.

**Comment by swinslow** [comment]
+1 to add

Thanks for the thoughts on naming. I don't have a strong feeling here, other than (1) agree with probably not using "texlive"; and (2) probably also don't want to just use "slideshow" given that's a broader term and this is a one-off license that doesn't appear to be used anywhere else.

Perhaps "McPhee-slideshow" as ID, since that's the copyright holder's name? Or "metapost-slideshow" given the title at the top of the example?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

McPhee Slideshow License

## License ID

McPhee-slideshow

## XML markup

none

## Notes:

none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@richardfontana do you want to make the PR for this one?
and make sure you agree with name?

Note the text of the license pasted into the tool is not formatted and retains %% so you may have to fix that in the XML editor
