### ISSUE TITLE
New license request: DL-DE-ZERO-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by pathmapper** [spdx/license-list-XML#2072]
**1.** License Name: Data licence Germany - zero - v2.0
**2.** Short identifier: DL-DE-ZERO-2.0
**3.** License Author or steward: https://www.govdata.de/
**4.** Comments: It's the more permissive license (similar to CCO) of the already included  https://spdx.org/licenses/DL-DE-BY-2.0.html.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/269
**6.** URL(s): https://www.govdata.de/dl-de/zero-2-0
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://open.nrw/, https://open.nrw/dataset/alkis-liegenschaftskataster-kreis-viersen-odp, https://www.bezreg-koeln.nrw.de/system/files/media/document/file/lizenzbedingungen_geobasis_nrw.pdf

**Comment by pathmapper** [comment]
I'm happy to submit a PR for this license if the request would be approved.

**Comment by mlinksva** [comment]
I was just curious when the BY version was added, ~2 years ago https://github.com/spdx/license-list-XML/issues/1306 to save others trouble of looking it up.

**Comment by pathmapper** [comment]
`DL-DE-ZERO-2.0` is a very common and widely used licence for data from the "open data" states in Germany, e.g. the state North Rhine-Westphalia with 18 million inhabitants is using it for nearly all it's geodata.

So a lot of projects using this data are using this license:
https://github.com/search?q=https%3A%2F%2Fwww.govdata.de%2Fdl-de%2Fzero-2-0&type=code

It would be good practice to use an official SPDX identifier for projects like the following: 
https://github.com/kreis-viersen/quattromap#aktuell-verf%C3%BCgbare-dienste
https://github.com/kreis-viersen/katasteraemter-gemarkungen-fluren-nrw#lizenz-der-daten

For https://github.com/osmlab/editor-layer-index the project would like to see `DL-DE-ZERO-2.0` in the SPDX list -> https://github.com/osmlab/editor-layer-index/pull/2024

**Comment by pathmapper** [comment]
Thanks @jlovejoy, submitted a PR ->  https://github.com/spdx/license-list-XML/pull/2099
