### ISSUE TITLE
New license request: NTP like license

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2075]
### How license meets inclusion principles

The license was found in Fedora in the Tk package during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/291
It's allowed for Fedora, it has tag "license allowed".

### License Name

NTP like

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

Tk:
https://core.tcl-lang.org/tk/file?name=compat/unistd.h

**Comment by richardfontana** [comment]
This is obviously similar to `HPND` but I don't think it is a match.

**Comment by yarda** [comment]
@jlovejoy if the issue is assigned now to me, how can I push it further?

**Comment by jlovejoy** [comment]
license text:

```
Copyright 1989 Regents of the University of California Permission to use,
 * copy, modify, and distribute this software and its documentation for any
 * purpose and without fee is hereby granted, provided that the above
 * copyright notice appear in all copies. The University of California makes
 * no representations about the suitability of this software for any purpose.
 * It is provided "as is" without express or implied warranty.
 ```

**Comment by jlovejoy** [comment]
this is close to NTP, but NTP has `and that the name (TrademarkedName) not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission. ` which this license omits. 

I think this make it a different license as it is omitting a condition.

**Comment by jlovejoy** [comment]
this is actually a match to HPND

will close as license already on SPDX License List

**Comment by richardfontana** [comment]
@jlovejoy it is not a match to HPND: Excerpt:
```
<p>Permission to use, copy, modify and distribute this software and its documentation for any purpose and
         without fee is hereby granted, provided that the above copyright notice appear in all copies<optional spacing="after">,</optional>
         <optional>and</optional> that both <optional>that</optional>
         <optional>the</optional> copyright notice
         and this permission notice appear in supporting documentation<optional>, and that the name <optional>of</optional>
            <alt match=".*" name="copyrightHolder0">&lt;copyright holder&gt;</alt>
            <alt match=".*" name="orRelated">&lt;or related entities&gt;</alt>
         not be used in advertising or publicity pertaining to distribution of the software without specific, written
         prior permission</optional>. 
         <optional><alt match=".*" name="copyrightHolder1">&lt;copyright holder&gt;</alt> 
         makes no representations about the suitability of this software for any purpose. 
         <alt match="It|This software" name="subject">It</alt> 
         is provided "as is" without express or implied warranty.</optional>
      </p>
```

**Comment by jlovejoy** [comment]
I realized that the license matching tools don't do a good job of matching to HPND (and its variants) b/c there is so much that can be optional, etc.

I'm going to do an analysis of all of the open issues that have similarities to HPND together and try to write up some guidance on this. 

I also looked back at the original intention when HPND was submitted to OSI and I'm not sure that the OSI had is represented exactly right and thus, our XML markup may be a bit off...

**Comment by jlovejoy** [comment]
@richardfontana is correct, this is not a match to HPND as it omits `that both the copyright notice and this permission notice appear in supporting documentation`

sigh. new variant to add?

**Comment by jlovejoy** [comment]
as discussed on 9/14 call - the omission of this phrase is omitting a condition upon the license grant (and compliance obligation), thus not appropriate for markup. Accept as new license

**Comment by swinslow** [comment]
Discussed on legal team call 2023-09-14, agreed to add

# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - University of California variant

## License ID

HPND-UC

## XML markup

None

## Notes:

Describe differences from standard HPND options and why this doesn't fit with it

## Additional rationale or notes on decision:

_add any additional information, including optionally a summary of what is recorded in the issue comments_

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by richardfontana** [comment]
Sorry for not catching this earlier but thanks to a comment by @MarkAtwood I realize that this is from Fedora's perspective "not a license" as to the file it was identified in. So unless @yarda has found it elsewhere we will not be adding this license to fedora-license-data at this time.

**Comment by xsuchy** [comment]
@richardfontana which comment are you referring to?

**Comment by richardfontana** [comment]
This was a comment made by @MarkAtwood at a recent SPDX- legal meeting.
