### ISSUE TITLE
New license request: NTP like

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2076]
### How license meets inclusion principles

The license was found in Fedora in the Tk package during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/292
It's allowed for Fedora, it has tag "license allowed".

### License Name

NTP like

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

Tk:
https://core.tcl-lang.org/tk/file?name=generic/tkImgGIF.c

**Comment by jlovejoy** [comment]
@yarda - please fill out the SPDX submission form in full, otherwise, it creates more work :)

**Comment by jlovejoy** [comment]
link to license text: https://core.tcl-lang.org/tk/file?name=generic/tkImgGIF.c

project: giftoppm

**Comment by jlovejoy** [comment]
license text for convenience:

Copyright 1990, David Koblas.					|
Permission to use, copy, modify, and distribute this software	
and its documentation for any purpose and without fee is hereby	
granted, provided that the above copyright notice appear in all	
copies and that both that copyright notice and this permission	
notice appear in supporting documentation. This software is	
provided "as is" without express or implied warranty.

**Comment by jlovejoy** [comment]
license text for convenience:

Copyright 1990, David Koblas.					|
Permission to use, copy, modify, and distribute this software	
and its documentation for any purpose and without fee is hereby	
granted, provided that the above copyright notice appear in all	
copies and that both that copyright notice and this permission	
notice appear in supporting documentation. This software is	
provided "as is" without express or implied warranty.

**Comment by jlovejoy** [comment]
actually, this is also a match to HPND (which has made me realize, we may need to fix up the HPND markup a bit, but I'll open another issue for that)

will close and add comment to Gitlab!

**Comment by richardfontana** [comment]
@jlovejoy I don't understand why this matches `HPND`, as I [explained](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/292#note_1557749746) in the Fedora issue.

**Comment by jlovejoy** [comment]
ok, I've now re-reviewed this and it's a match to another HPND variant that we just reviewed merged, see https://github.com/spdx/license-list-XML/pull/2146

use `HPND-Pbmplus`
