### ISSUE TITLE
New license request: ssh-keyscan [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by beldmit** [spdx/license-list-XML#2077]
**1.** License Name: -
**2.** Short identifier: ssh-keyscan
**3.** License Author or steward: David Mazieres <dm@lcs.mit.edu>
**4.** Comments: This license is used in Fedora and was found during license review. See more details here: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/281
**5.** License Request Url: http://tools.spdx.org/app/license_requests/271
**6.** URL(s): https://github.com/openssh/openssh-portable/blob/master/LICENCE#L82
**7.** OSI Status: Unknown
**8.** Example Projects: https://openssh.com

**Comment by beldmit** [comment]
@jlovejoy Sorry I don't understand what are the steps expected from my side.

**Comment by Pizza-Ria** [comment]
This feels less like a license ask and more like an umbrella under which to park a few BSD variants and maybe some other similarly free licenses.  Why not just delineate each license contained in https://github.com/openssh/openssh-portable/blob/master/LICENCE#L82 separately with the appropriate identifier or request a license-id for anything odd and not already in SPDX?

**Comment by jlovejoy** [comment]
> Sorry I don't understand what are the steps expected from my side.

sorry @beldmit - just using "assigned" to indicate who submitted the license!

**Comment by jlovejoy** [comment]
license text:
```
Copyright 1995, 1996 by David Mazieres <dm@lcs.mit.edu>.

Modification and redistribution in source and binary forms is
permitted provided that due credit is given to the author and the
OpenBSD project by leaving this copyright notice intact.
```

**Comment by jlovejoy** [comment]
+1 to add as it does not match anything on the SPDX License list and is used in Fedora in a package that is likely used in many other places

**Comment by jlovejoy** [comment]
@Pizza-Ria - see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/278#note_1501510113 for more on the contents of the entire license file

**Comment by swinslow** [comment]
Also +1 to add, I don't see any matches to anything currently on the list; +1 to add as a simple permissive license.

**Comment by swinslow** [comment]
Good with `ssh-keyscan` as ID and "ssh-keyscan License" as the name, this reference in the OpenSSH distro appears to be the primary place where I'm finding this license text used based on a quick search.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

ssh-keyscan License

## License ID

ssh-keyscan

## XML markup

none

## Notes:
none

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process). 

@beldmit can you create the PR now that it's been accepted?

**Comment by xsuchy** [comment]
I drafted the PR for you.
