### ISSUE TITLE
New license request: BSD-3-Sun [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mkoncek** [spdx/license-list-XML#2081]
**1.** License Name: BSD-3-Oracle
**2.** Short identifier: BSD-3-Oracle
**3.** License Author or steward: Oracle
**4.** Comments: This license test almost matches  BSD-3-Clause-No-Nuclear-Warranty but still differs slightly and does not contain the section about nuclear facilities, it has been found in the msv project (https://github.com/xmlark/msv) which is to be packaged in Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/273
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/b4089cbb-13c3-4b20-8f10-28cedc8ca28e.png

**Note:**
The license closely matched with the following license ID(s): BSD-3-Clause-No-Nuclear-Warranty

**Comment by jlovejoy** [comment]
As mentioned, this is a very close match to https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html except that it omits the nuclear warranty at the end and has the following variations in the disclaimer section:
- adds "or liabilities" in the third sentence: "shall not be liable for damages _or liabilities_" 
- and has "AS A RESULT OF OR  RELATING TO USE, MODIFICATION OR DISTRIBUTION OF THE SOFTWARE OR ITS DERIVATIVES" instead of "AS A RESULT OF USING, MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES"

**Comment by jlovejoy** [comment]
I suspect we probably need to add this as its own license. I'd opt for using "Sun" rather than "Oracle" in the name and id since that is used in the license and where it originally came from

**Comment by richardfontana** [comment]
+1 for using 'Sun' in the name.

**Comment by bsdimp** [comment]
+1 for sun name, and needing a new ID for this. I think it meets the inclusion criteria.

**Comment by mkoncek** [comment]
I do not have a preference for the name, I can change the proposal to ...-Sun.
Also, see slight variations of the license in files:
* https://github.com/xmlark/msv/blob/b9316e2f2270bc1606952ea4939ec87fbba157f3/xsdlib/src/main/java/com/sun/msv/datatype/regexp/InternalImpl.java
* https://github.com/xmlark/msv/blob/b9316e2f2270bc1606952ea4939ec87fbba157f3/xsdlib/src/main/java/com/sun/msv/datatype/xsd/AnyURIType.java

**Comment by richardfontana** [comment]
I think the one in AnyURITYpe.java matches BSD-3-Clause as currently specified.

**Comment by jlovejoy** [comment]
> I think the one in AnyURITYpe.java matches BSD-3-Clause as currently specified.

you are correct, so let's not include that link

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

BSD 3-Clause Sun

## License ID

BSD-3-Clause-Sun

## XML markup

none at this time

## Notes:

This license is very similar to BSD-3-Clause-No-Nuclear-Warranty except it has variations in the disclaimer and omits the no-nuclear-warranty at the end.



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
fixed by #2133
