### ISSUE TITLE
New license request: Apache-1.1 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mkoncek** [spdx/license-list-XML#2082]
**1.** License Name: Apache Software License 1.1
**2.** Short identifier: Apache-1.1
**3.** License Author or steward: Unknown
**4.** Comments: This license test almost matches Apache-1.1 but still differs, it has been found in the msv project (https://github.com/xmlark/msv) which is to be packaged in Fedora.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/274
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/5b3d5f16-d173-43cc-932c-22c3fd8975de.png

**Note:**
The license closely matched with the following license ID(s): Apache-1.1

**Comment by jlovejoy** [comment]
Yes, this is a match to Apache-1.1

See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/300 for cross-ref / explanation

Thanks for checking!

**Comment by jlovejoy** [comment]
closing issue, as no further action needed
