### ISSUE TITLE
New license request: fwlw (was: texlive-Arseneau-1993) [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2086]
**1.** License Name: texlive Arseneau 1993 License
**2.** Short identifier: texlive-Arseneau-1993
**3.** License Author or steward: Donald Arseneau
**4.** Comments: This license has been found in texlive-fwlw during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/294
**5.** License Request Url: http://tools.spdx.org/app/license_requests/276
**6.** URL(s): https://mirrors.nic.cz/tex-archive/macros/latex/contrib/fwlw/README
**7.** OSI Status: Unknown
**8.** Example Projects: https://tug.org/texlive/cd /

**Comment by xsuchy** [comment]
Note that https://github.com/spdx/license-list-XML/issues/2088 and https://github.com/spdx/license-list-XML/issues/2087 and https://github.com/spdx/license-list-XML/issues/2086 are very similar but different. 
There is already https://spdx.org/licenses/preview/Dotseqn.html on the SPDX list, but this is different too.

**Comment by Pizza-Ria** [comment]
I still find it phenomenal that we don't have a closer match already SPDX approved but +1 to add it.

**Comment by richardfontana** [comment]
Possible better identifier: `fwlw`.

**Comment by jlovejoy** [comment]
why `fwlw` @richardfontana ?

I'm thinking we could combine this via markup with #2088

**Comment by richardfontana** [comment]
Relevant comment on naming: https://github.com/spdx/license-list-XML/issues/2071#issuecomment-1713034746

`fwlw` is the actual name of the LaTeX "package" where this license is found. `Arseneau` was I think suggested originally by Tom Callaway in the ancestral counterpart Fedora issue (to cover a set of textually distinct licenses associated with that author).

**Comment by jlovejoy** [comment]
if we use markup for this and #2088 - should we use something like `fwlw-ulem`for the ide and name?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

_record full name that will be used in the license list_

## License ID

_record final decision on short id to be used; **take care** as it is policy that this id never change_

## XML markup

markup to accommodate #2088 as well

## Notes:

none right now, but might update to add something about #2086 similarity

**Comment by jlovejoy** [comment]
made PR to get started, but holding on finalization of name
