### ISSUE TITLE
New license request: magaz (was: texlive-Arseneau-1999) [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2087]
**1.** License Name: texlive Arseneau 1999 License
**2.** Short identifier: texlive-Arseneau-1999
**3.** License Author or steward: Donald Arseneau
**4.** Comments: This license has been found in texlive-magaz and texlive-version during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/293
**5.** License Request Url: http://tools.spdx.org/app/license_requests/277
**6.** URL(s): https://mirrors.nic.cz/tex-archive/macros/latex/contrib/magaz/magaz.tex
**7.** OSI Status: Unknown
**8.** Example Projects: https://tug.org/texlive/

**Comment by xsuchy** [comment]
License text:
```
% Copyright 1999-2011, Donald Arseneau,   asnd@triumf.ca,  Vancouver, Canada
% This software may be freely used, transmitted, reproduced, or modified
% provided that the copyright notice and this permission is retained.
```

**Comment by xsuchy** [comment]
Note that https://github.com/spdx/license-list-XML/issues/2088 and https://github.com/spdx/license-list-XML/issues/2087 and https://github.com/spdx/license-list-XML/issues/2086 are very similar but different. 
There is already https://spdx.org/licenses/preview/Dotseqn.html on the SPDX list, but this is different too.

**Comment by Pizza-Ria** [comment]
+1 to add also cross-referencing my comment in #2070 that (c) holder was nonresponsive re a license change.

**Comment by richardfontana** [comment]
Possible better identifier: `magaz`.

**Comment by jlovejoy** [comment]
+1 to add as this is similar to #2086 and #2088, but the license condition is more specific than those, as it includes `the copyright notice and this permission is retained"

**Comment by jlovejoy** [comment]
thanks for trying @Pizza-Ria !

same question for @richardfontana  on naming as others...

**Comment by richardfontana** [comment]
Relevant comment on naming: https://github.com/spdx/license-list-XML/issues/2071#issuecomment-1713034746

**Comment by jlovejoy** [comment]
@Pizza-Ria @swinslow - do either of you have thoughts on this being distinct from #2086 and #2088 as noted above?

**Comment by swinslow** [comment]
Agreed with using `magaz` as ID as I believe we discussed on the latest legal team call.
