### ISSUE TITLE
New license request: ulem (was: texlive-Arseneau-1989) [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2088]
**1.** License Name: texlive Arseneau 1989 License
**2.** Short identifier: texlive-Arseneau-1989
**3.** License Author or steward: Donald Arseneau
**4.** Comments: This license has been found in texlive-ulem during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/117
**5.** License Request Url: http://tools.spdx.org/app/license_requests/278
**6.** URL(s): https://mirrors.ctan.org/macros/latex/contrib/ulem/README
**7.** OSI Status: Unknown
**8.** Example Projects: https://tug.org/texlive/cd/

**Comment by xsuchy** [comment]
License text: 
```
Copyright 1989-2019 by Donald Arseneau (Vancouver, Canada; [asnd@triumf.ca](mailto:asnd@triumf.ca))

This software may be freely transmitted, reproduced, or modified for any purpose provided that this copyright notice is left intact.
```

**Comment by xsuchy** [comment]
Note that https://github.com/spdx/license-list-XML/issues/2088 and https://github.com/spdx/license-list-XML/issues/2087 and https://github.com/spdx/license-list-XML/issues/2086 are very similar but different. 
There is already https://spdx.org/licenses/preview/Dotseqn.html on the SPDX list, but this is different too.

**Comment by Pizza-Ria** [comment]
+1 to add also cross-referencing my comment in https://github.com/spdx/license-list-XML/issues/2070 that (c) holder was nonresponsive re a license change.

**Comment by richardfontana** [comment]
Possible better identifier: `ulem`.

**Comment by jlovejoy** [comment]
+1 to add and use markup to combine this and #2086 

See https://docs.google.com/document/d/1xqSwTfJJ7btkhbblrIAZxOxv0iZPmAMGar9rU7DLKC8/edit for easier comparison

**Comment by jlovejoy** [comment]
@richardfontana as for identifier, why not use "texlive" in any case?

**Comment by richardfontana** [comment]
@jlovejoy for why not to use "texlive-" see: https://github.com/spdx/license-list-XML/issues/2071#issuecomment-1713034746
Alternatively maybe SPDX should adopt some fixed convention for things like this, e.g. "Any unique license found only in stuff in TeX Live will have an identifier prefixed with texlive-" (which resembles the Fedora package naming convention I guess). 

I don't think SPDX does anything analogous to "texlive-" with other license identifiers associated uniquely with things found in a particular upstream package archive.

**Comment by jlovejoy** [comment]
added PR to cover this and #2086 - need to finalize naming. Then update this to be markup change only

**Comment by jlovejoy** [comment]
discussed on 9/14 legal call - looked at all 3 of these and determined that they are just different enough in terms of interpretation of compliance obligations to warrant 3 entries.  @jlovejoy to update noted PR as such

**Comment by jlovejoy** [comment]
identifier: `ulem`
