### ISSUE TITLE
New license request: gnu-compiler-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by shtiek** [spdx/license-list-XML#2091]
**1.** License Name: LicenseRef-scancode-iolib-exception-2.0
**2.** Short identifier: gnu-compiler-exception
**3.** License Author or steward: FSF
**4.** Comments: During license review of GNU libiberty in Fedora, Fossology marked several
files as containing "LicenseRef-scancode-iolib-exception-2.0". This was submitted
to Fedora Legal for approval, which recommended filing an issue here:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/298
**5.** License Request Url: http://tools.spdx.org/app/license_requests/279
**6.** URL(s): https://sourceware.org/git?p=binutils-gdb.git;a=blob;f=libiberty/unlink-if-ordinary.c;h=e49f2f2f67bfdb10d6b2bd579b0e01cad0fd708e;hb=HEAD#l19
**7.** OSI Status: Unknown
**8.** Example Projects: https://gcc.gnu.org/, https://sourceware.org/binutils/, https://sourceware.org/gdb/

**Comment by jlovejoy** [comment]
text of exception for convenience:

As a special exception, if you link this library with files
compiled with a GNU compiler to produce an executable, this does not cause
the resulting executable to be covered by the GNU General Public License.
This exception does not however invalidate any other reasons why
the executable file might be covered by the GNU General Public License.

**Comment by jlovejoy** [comment]
<img width="545" alt="image" src="https://github.com/spdx/license-list-XML/assets/5048659/34c02006-db99-4e98-b1ac-f0a68d5922de">

**Comment by swinslow** [comment]
So here's a question:

* SWI-exception permits the exception to apply if you link the software together with files compiled with any "Free Software compiler."
* By contrast, this one only permits the exception to apply if the compiler was a "GNU compiler."

I'd tend to treat these as substantively different. This isn't a situation where e.g. the difference is in determining which files or content the exception applies to; rather, the difference is in the legal effect of the exception's scope. I'd think this is different enough to warrant a separate exception identifier (which I'd be +1 for adding as a separate ID).

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

GNU Complier Exception

## License ID

GNU-compiler-exception

## XML markup

none

## Notes:

This exception is the same as SWI-exception but delineates that the library is compiled with a GNU compiler, which is narrower than a or any free software compiler.


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by xsuchy** [comment]
s/GNU Complier Exception/GNU Compiler Exception/
