### ISSUE TITLE
add markup: Crossword

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#2093]
found another instance of [Crossword](https://spdx.org/licenses/Crossword.html) that uses a different project name at https://mirrors.ctan.org/macros/latex/contrib/gene/productbox/README

`productbox.dtx is distributed in the hope that it will be useful, but  WITHOUT ANY WARRANTY.  No  author  or  distributor  accept responsibility to anyone for the consequences of using it or for whether it serves any particular purpose or works at all, unless he says so in writing.`

`Everyone is granted permission to  copy, modify and redistribute productbox.dtx, provided this copyright notice is preserved  and
any modifications are indicated.`

**Comment by swinslow** [comment]
Looks good to me, adding in matching for the two spots with the filename.

My only other comment is that between the two paragraphs, there appears to be a stray period that also shows up in [the original source on the Fedora wiki](https://fedoraproject.org/wiki/Licensing/Crossword). Can we either remove that or mark it as optional, if we're opening up the XML markup here anyway?

**Comment by swinslow** [comment]
For what it's worth, I don't think this was in the original upstream source: see https://ctan.math.utah.edu/ctan/tex-archive/macros/latex/contrib/gene/crossword/LICENSE
