### ISSUE TITLE
New license request: lsof [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2100]
**1.** License Name: lsof License
**2.** Short identifier: lsof
**3.** License Author or steward: Victor A. Abell
**4.** Comments: This is part of lsof project (included in **every** Linux). Found during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/307
**5.** License Request Url: http://tools.spdx.org/app/license_requests/282
**6.** URL(s): https://github.com/lsof-org/lsof/blob/master/COPYING
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/lsof-org/lsof

**Comment by xsuchy** [comment]
Text of the license:
```
Copyright 2002 Purdue Research Foundation, West Lafayette,
Indiana 47907.  All rights reserved.

Written by Victor A. Abell

This software is not subject to any license of the American
Telephone and Telegraph Company or the Regents of the
University of California.

Permission is granted to anyone to use this software for
any purpose on any computer system, and to alter it and
redistribute it freely, subject to the following
restrictions:

1. Neither the authors nor Purdue University are responsible
   for any consequences of the use of this software.

2. The origin of this software must not be misrepresented,
   either by explicit claim or by omission.  Credit to the
   authors and Purdue University must appear in documentation
   and sources.

3. Altered versions must be plainly marked as such, and must
   not be misrepresented as being the original software.

4. This notice may not be removed or altered.
```

**Comment by xsuchy** [comment]
It is similar to Spencer 94. But @jlovejoy and @richardfontana agree that they differ enough to be submitted as a new one.

I am open to changing the license name and license id to something different.

**Comment by jlovejoy** [comment]
hmmm... I'm having second thoughts as to whether this is close enough to https://spdx.org/licenses/Spencer-94.html

**Comment by swinslow** [comment]
+1 to add. I think this is different enough that it shouldn't be tied to `Spencer-94`, though perhaps a comment in the "Notes" field mentioning the similarities might be appropriate.

I'm fine with `lsof` as ID and "lsof License" as suggested by the submitter.

**Comment by jlovejoy** [comment]
@InSwiss - I'd be curious to know what the license text is for Spencer-95 that you have captured?

**Comment by InSwiss** [comment]
@jlovejoy This is what we have for Spencer 95 :
Copyright (c) 1986, 1993, 1995 by University of Toronto.
Written by Henry Spencer. Not derived from licensed software.
Permission is granted to anyone to use this software for any purpose on any computer system, and to redistribute it in any way, subject to the following restrictions:

The author is not responsible for the consequences of use of this software, no matter how awful, even if they arise from defects in it.
The origin of this software must not be misrepresented, either by explicit claim or by omission.
Altered versions must be plainly marked as such, and must not be misrepresented (by explicit claim or omission) as being the original software.
This notice must not be removed or altered.

**Comment by jlovejoy** [comment]
I think it sounds like we are adding this, not markup to Spence-94?

**Comment by swinslow** [comment]
Yes, +1 to add as separate license and not try to match to Spencer-*

Good with `lsof` as ID and "lsof License" as the name
