### ISSUE TITLE
Enhance Libtool-exception to not be specific to GPL only

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2102]
### How license meets inclusion principles

Presented in Fedora (and likely other Linuxes) Found during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/312

### License Name

Libtool-exception

### Suggested short identifier

Libtool-exception

### URL to license text

https://git.savannah.gnu.org/cgit/libtool.git/tree/libltdl/lt__alloc.c#n15

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://git.savannah.gnu.org/cgit/libtool.git/tree

**Comment by xsuchy** [comment]
The `exceptions/Libtool-exception.xml` has this leading line:

`As a special exception to the GNU General Public License, if you ...`

while the license in https://git.savannah.gnu.org/cgit/libtool.git/tree/libltdl/lt__alloc.c#n15 there is

`As a special exception to the GNU Lesser General Public License, if you ...`

I suggest changing the Libtool-exception to allow any text instead of `GNU General Public License` so it can be an exception to any license.

**Comment by jlovejoy** [comment]
this is fine for adding markup - but I'd add "Lesser" as optional.  I'll comment on your PR
