### ISSUE TITLE
New license request: flex 2.6.4

### ISSUE THREAD

**Issue by submachine** [spdx/license-list-XML#2104]
### How license meets inclusion principles

flex is used in Fedora and this license was found during [license review](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/301).

The text isn't an exact match for any of the existing SPDX licenses but is a BSD style license. I can't make out if the license has a particular name or title based on the license text.

Another detail is that while the COPYING file contains the canonical form of the license, some source files contain slightly different variants. Examples of two variants I have noticed:

* `src/buf.c` contains almost the entire text with one missing paragraph:

> This basically says "do whatever you please with this software ...

* `configure.ac` skips the above paragraph along with an additional bit:

> The United States Government has rights in this work ...

### License Name

Flex 2.6.4 License (?, placeholder name)

### URL to license text

https://github.com/westes/flex/blob/master/COPYING

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/westes/flex

**Comment by karsten-klein** [comment]
At the core it is a misformatted BSD-3 Clause variant with reduced disclaimer:

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.
"3." Neither the name of the University nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.

THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.

===

At the end an additional terms are mentioned: "You are free to do whatever you please with scanners generated using flex; for them, you are not even bound by the above copyright."

**Comment by jlovejoy** [comment]
agreed @karsten-klein - it also adds at the start:

The United States Government has rights in this work pursuant
to contract no. DE-AC03-76SF00098 between the United States
Department of Energy and the University of California.

Which I take as intended to be part of the license text (not "license" technically, but more of a notice)

I'd be inclined to add as a new license and use something like `BSD-3-Clause-Flex` to be consistent with other variants like this

**Comment by InSwiss** [comment]
Reviewed this issue. It is a BSD style license – 3 clause and disclaimer is from BSD-4 shortened. The last 2 paragraphs are in addition so it can be accepted as new license. It was not found in OSA. License name ‘Flex 2.6.4 License´ suggestion isn’t very intuitive.  The earlier version of Flex also has same license so putting a versioning in name isn’t helpful. I agree with suggestions from others that it should be name with BSD -3 Clause in the name like 'BSD 3-Clause Flex modified'. We can do 'BSD 3-Clause-USG' but I am not sure if anyone else would have the same contract number as mentioned here :  "The United States Government has rights in this work pursuant to contract no. DE-AC03-76SF00098 between the United States
Department of Energy and the University of California."

**Comment by swinslow** [comment]
+1 to add with the text from the COPYING file linked above.

I'm fine with either `flex` or `BSD-3-Clause-flex` as the ID, and choosing a corresponding license name to align with either of those.

I think referencing "flex" in the ID and name is appropriate here. I probably wouldn't include the flex version number.

**Comment by submachine** [comment]
Thanks for looking at this issue. I agree with not including the version in the license name. At the time of filing this issue, the template expected a suggested name -- so I put in some placeholder text without any serious thought.

**Comment by BrianInglis** [comment]
It might be good to see if the actual primary contract IP terms could be found, but may have been issued in 1976, as papers with subcontracts from the early 1980s...2000s mention it, without any links, and may be for the initial LBNL applied energy research and efficiency and standards initiatives after the 1970s energy "crisis": see recent contract updates 
[UC/LBNL Contracts](https://www.ucop.edu/laboratory-management/contracts/lbnl/archived-contracts.html)
[UC/LBNL Contract Modifications](https://www.ucop.edu/laboratory-management/contracts/lbnl/modifications.html) 
[Latest Modification](https://www.ucop.edu/laboratory-management/_files/contracts/lbnl_k_m390.pdf)
says under 7.2(b)(1)(i) that USG gains ownership of any software, which could place the software in the PD; 
unless that software is developed other than under the contract, and LBNL, UCB, or a subcontractor attaches Restricted Computer Software Rights); 
while LBNL, UCB, or a subcontractor (depending on their terms) may request copyright to pursue commercialization.

**Comment by jlovejoy** [comment]
interesting thought @BrianInglis - but not sure who is going to track that down! 

In any case, I would read this as some copyright might be US Gov't (thus reverts to public domain) and some under the license included, as it does say it's "derived from..." so that indicates it's a mix.

In any case, the license is out there in software that is being used, so it's ripe to add to the SPDX License List!

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

BSD 3-Clause Flex variant

## License ID

BSD-3-Clause-flex

## XML markup

none at this time

## Notes:

none

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@submachine - can you prepare a PR for this?

we have some notes on the XML style here as well https://github.com/spdx/license-list-XML/blob/main/DOCS/xml-fields.md
