### ISSUE TITLE
New license request: VOL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by thebeanogamer** [spdx/license-list-XML#2106]
**1.** License Name: Volatility Software License 1.0
**2.** Short identifier: VOL-1.0
**3.** License Author or steward: Volatility Foundation
**4.** Comments: This license enforces availability of source code for both this project and any modifications. It is applied to all modern releases from the Volatility Foundation, whose tools are used widely throughout the DFIR profession.

The license is versioned, and the license steward has not made any modifications since publication. The license text does however make explicit reference to the Volatility Foundation, which could limit its usage and be grounds for rejection.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/284
**6.** URL(s): https://www.volatilityfoundation.org/license/vsl-v1.0
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/volatilityfoundation/volatility3, https://github.com/volatilityfoundation/dwarf2json

**Comment by thebeanogamer** [comment]
Note that whilst `VSL-1.0` as the SPDX code would more closely align with upstream, that SPDX code is already assigned (<https://spdx.org/licenses/VSL-1.0.html>).

**Comment by thebeanogamer** [comment]
There is also an ongoing review of this license by Fedora Legal which could be of interest (<https://gitlab.com/fedora/legal/fedora-license-data/-/issues/320>).

**Comment by jlovejoy** [comment]
thanks for the update, @richardfontana - I'm going to close this issue then. If someone later wants to (re)submit, they can always do so.
