### ISSUE TITLE
New license request: Cronyx (was X11-Fonts) [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2115]
**1.** License Name: X11-Fonts
**2.** Short identifier: X11-Fonts
**3.** License Author or steward: Unknown
**4.** Comments: Packages using this license are used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. 

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/321#note_1544774036
**5.** License Request Url: http://tools.spdx.org/app/license_requests/285
**6.** URL(s): https://gitlab.freedesktop.org/xorg/font/alias/-/blob/master/COPYING, https://gitlab.freedesktop.org/xorg/font/cronyx-cyrillic/-/blob/master/COPYING, https://gitlab.freedesktop.org/xorg/font/misc-cyrillic/-/blob/master/COPYING, https://gitlab.freedesktop.org/xorg/font/screen-cyrillic/-/blob/master/COPYING
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/font/alias/, https://gitlab.freedesktop.org/xorg/font/cronyx-cyrillic/, https://gitlab.freedesktop.org/xorg/font/misc-cyrillic/, https://gitlab.freedesktop.org/xorg/font/screen-cyrillic/

**Comment by whot** [comment]
I should note - coming up with a better name would be much appreciated.

**Comment by awilfox** [comment]
I'm thinking this one could be named Cronyx Font License, since the origin of the license seems to be Cronyx and I'm only aware of these fonts using it.  Short identifier could be Cronyx-Font.

**Comment by swinslow** [comment]
Among the four examples given, I see a couple of minor differences: 
* alias and cronyx-cyrillic versions are identical
* misc-cyrillic does not include "above" before "copyright notice"
* screen-cyrillic does not have a comma after "distributed" in the initial clause

I think all of the above are non-substantive changes and can be handled via markup in the XML.

I'm +1 to add this as a simple, historical and broadly permissive license, used in a major distro (Fedora) and in line with the license inclusion principles.

**Comment by swinslow** [comment]
I don't know the background of these licenses, but given @awilfox's comment that Cronyx is the originator of this one, I'd be okay using `Cronyx-Font` as the ID and "Cronyx Font License" as the name.

I could also go with just `Cronyx` and `Cronyx License`, because (even though these are all used for fonts) there's nothing in the license that is specific to fonts; it appears to just refer generally to "software".

**Comment by swinslow** [comment]
Here's an example where used not for fonts: https://web.mit.edu/freebsd/head/sys/i386/bios/apm.h

**Comment by jlovejoy** [comment]
hmmm... that other usage in FreeBSD on a different project kind of messes up the rationale for `Cronyx` name, but I'm not sure I have a better idea

**Comment by swinslow** [comment]
The apm.h version I just linked to above does not include "and sold", which is in the other font license versions above. Given that, I would _not_ include the apm.h variant in this one.

Let's go with `Cronyx` as ID and "Cronyx License" as name.

**Comment by jlovejoy** [comment]
+1 to add as well, agree with your naming suggestion

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Cronyx License

## License ID

Cronyx

## XML markup

yes, see notes above

## Notes:

none



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@whot - can you prepare the PR now that this has been accepted?  Thanks!
