### ISSUE TITLE
New license request: Ferguson-Twofish

### ISSUE THREAD

**Issue by ppisar** [spdx/license-list-XML#2117]
### How license meets inclusion principles

The license grants all rights and only requires retaining a copyright header in redistributed sources.
This license is used in a package which is going to be added to Fedora Linux distribution.
Fedora finds the license acceptable <https://gitlab.com/fedora/legal/fedora-license-data/-/issues/329>.

The license text:

~~~~
The author hereby grants a perpetual license to everybody to 
use this code for any purpose as long as the copyright message is included 
in the source code of this or any derived work. 
 
Yes, this means that you, your company, your club, and anyone else 
can use this code anywhere you want. You can change it and distribute it 
under the GPL, include it in your commercial product without releasing 
the source code, put it on the web, etc.  
The only thing you cannot do is remove my copyright message,  
or distribute any source code based on this implementation that does not  
include my copyright message.  
  
I appreciate a mention in the documentation or credits,  
but I understand if that is difficult to do. 
I also appreciate it if you tell me where and why you used my code.
~~~~

The license has no official name or an abbreviation. Please suggest them.

### License Name

Ferguson's Twofish

### Suggested short identifier

Ferguson-Twofish

### URL to license text

https://github.com/wernerd/ZRTPCPP/blob/master/cryptcommon/twofish.c#L113C3-L127

### OSI Status

I don't know

### License author or steward

Niels Ferguson

### URL to project(s) that use license

https://github.com/wernerd/ZRTPCPP/blob/master/cryptcommon/twofish.c#L113
https://raw.githubusercontent.com/fcorbelli/zpaqfranz/main/zpaqfranz.cpp

**Comment by swinslow** [comment]
I'm +1 to add, as a historical and permissive (if informal) license used in Fedora.

For name I'd probably suggest going with `Ferguson-Twofish` as the ID and "Ferguson Twofish License" as the name.

**Comment by jlovejoy** [comment]
agree with @swinslow  (also discussed on 9/8 working session)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Ferguson Twofish License

## License ID
Ferguson-Twofish
## XML markup

none

## Notes:

none

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process). 

@ppisar - would you mind creating the PR?
