### ISSUE TITLE
New license request: HPND-DEC [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2119]
**1.** License Name: Historical Permission Notice and Disclaimer - DEC variant
**2.** Short identifier: HPND-DEC
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. The license text is HPND with an extra preamble.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/324#note_1548850222
**5.** License Request Url: http://tools.spdx.org/app/license_requests/286
**6.** URL(s): https://gitlab.freedesktop.org/xorg/app/xkbcomp/-/blob/master/COPYING?ref_type=heads#L69
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/app/xkbcomp/

**Comment by jlovejoy** [comment]
license text:

COPYRIGHT 1990
		        DIGITAL EQUIPMENT CORPORATION
		           MAYNARD, MASSACHUSETTS
			    ALL RIGHTS RESERVED.

THE INFORMATION IN THIS SOFTWARE IS SUBJECT TO CHANGE WITHOUT NOTICE AND SHOULD NOT BE CONSTRUED AS A COMMITMENT BY DIGITAL EQUIPMENT CORPORATION.
DIGITAL MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THIS SOFTWARE
FOR ANY PURPOSE.  IT IS SUPPLIED "AS IS" WITHOUT EXPRESS OR IMPLIED
WARRANTY.

IF THE SOFTWARE IS MODIFIED IN A MANNER CREATING DERIVATIVE COPYRIGHT
RIGHTS, APPROPRIATE LEGENDS MAY BE PLACED ON THE DERIVATIVE WORK IN
ADDITION TO THAT SET FORTH ABOVE.

Permission to use, copy, modify, and distribute this software and 
its documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies 
and that both that copyright notice and this permission notice appear in supporting
documentation, 
and that the name of Digital Equipment Corporation not be
used in advertising or publicity pertaining to distribution of the
software without specific, written prior permission.

**Comment by jlovejoy** [comment]
+1 to add as while the grant part (Permission to use...) is the same as HPND, the disclaimer comes prior and is quite different

I think the name HPND-DEC seems reasonable

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - DEC variant

## License ID

HPND-DEC

## XML markup

none at this time

## Notes:

The permission grant is the same as HPND, but the disclaimer is quite different and there is a obligation related to modified versions.


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@whot - could you prepare the PR for this?
