### ISSUE TITLE
New license request: HPDN-doc-sell-variant [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by bentiss** [spdx/license-list-XML#2125]
**1.** License Name: HPND - documentation sell variant
**2.** Short identifier: HPDN-doc-sell-variant
**3.** License Author or steward: Unknown
**4.** Comments: Packages (libXext and libXtst) using this license are used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/338
**5.** License Request Url: http://tools.spdx.org/app/license_requests/291
**6.** URL(s): https://gitlab.freedesktop.org/xorg/lib/libxtst/-/blob/master/COPYING?ref_type=heads#L108-117, https://gitlab.freedesktop.org/xorg/lib/libxext/-/blob/master/COPYING?ref_type=heads#L153-162
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/lib/libXext, https://gitlab.freedesktop.org/xorg/lib/libxtst

**Comment by jlovejoy** [comment]
license text for convenience:

```
Copyright 1994 Network Computing Devices, Inc.

Permission to use, copy, modify, distribute, and sell this
documentation for any purpose is hereby granted without fee,
provided that the above copyright notice and this permission
notice appear in all copies.  Network Computing Devices, Inc.
makes no representations about the suitability for any purpose
of the information in this document.  This documentation is
provided "as is" without express or implied warranty.
```

**Comment by jlovejoy** [comment]
same text as #2124  but add "and sell" in grant

**Comment by karsten-klein** [comment]
See also https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-doc.LICENSE.

This gives you already a variant of the license.

**Comment by swinslow** [comment]
See my comment in #2124 -- +1 to add here as well, just noting should be "HPND" rather than "HPDN"

**Comment by Pizza-Ria** [comment]
The "sell" language warrants a separate ID.  +1 to add.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [x] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - documentation sell variant

## License ID

HPND-doc-sell

## XML markup

none

## Notes:

This is very similar to HPND-sell-variant but it is for documentation and alters the notice obligation.


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
