### ISSUE TITLE
New license request: HPND-export-US-label [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by carlwgeorge** [spdx/license-list-XML#2138]
**1.** License Name: MIT-ish with US Government export control warning
**2.** Short identifier: HPND-export-US-label
**3.** License Author or steward: Unknown
**4.** Comments: This license is very close to HPND-export-US, but has an additional sentence:

> Furthermore if you modify this software you must label your software as modified software and not distribute it in such a fashion that it might be confused with the original M.I.T. software.

This was brought up previously here:

https://github.com/spdx/license-list-XML/issues/1724#issuecomment-1361513366

I'm working on packaging the k5test software into Fedora, which uses this license for one of its files.  They refer to the license as MIT.  krb5 also uses this license for a portion of their source code.

https://github.com/krb5/krb5/blob/krb5-1.21.2-final/NOTICE#L1157-L1182
**5.** License Request Url: http://tools.spdx.org/app/license_requests/293
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/38c4772d-7d58-4e75-a59a-793165d87b95.png

**Note:**
The license closely matched with the following license ID(s): HPND-export-US

**Comment by jlovejoy** [comment]
license text:

Export of this software from the United States of America may
require a specific license from the United States Government. 
It is the responsibility of any person or organization contemplating 
export to obtain such a license before exporting.

WITHIN THAT CONSTRAINT, permission to use, copy, modify, and
distribute this software and its documentation for any purpose and
without fee is hereby granted, provided that the above copyright
notice appear in all copies and that both that copyright notice and
this permission notice appear in supporting documentation, and that
the name of M.I.T. not be used in advertising or publicity pertaining 
to distribution of the software without specific, written prior permission.  

_Furthermore if you modify this software you must label your software as modified software and not distribute it in such a fashion that it might be confused with the original M.I.T. software. _

Neither M.I.T., the Open Computing Security Group, nor CyberSAFE Corporation make any representations about the suitability of 
this software for any purpose.  It is provided "as is" without express 
or implied warranty.

**Comment by jlovejoy** [comment]
as compared to `HPND-export-US`, this license adds the clause in italics. I think this adds another condition and therefore makes this a new/different license.

+1 to add and I'd suggest, perhaps, `HPND-export-US-modify` (too long?) or something along those line

Note: The last clause as to representations uses the plural variant of "Neither... nor... make any representations" rather than "<name> makes no representations" but that could be accommodated with markup

**Comment by carlwgeorge** [comment]
It seems some of the information I filled out in the online tool was stripped it out.

> 6. URL(s):

- https://github.com/pythongssapi/k5test/blob/v0.10.3/K5TEST-LICENSE.txt
- https://github.com/krb5/krb5/blob/krb5-1.21.2-final/NOTICE#L1157-L1182

> 8. Example Projects:

- https://github.com/pythongssapi/k5test
- https://web.mit.edu/kerberos/www/

**Comment by Pizza-Ria** [comment]
+1 for above reasons.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

HPND with US Government export control warning and modification rqmt

## License ID

HPND-export-US-modify

## XML markup

none at this time

## Notes:

This is very similar to HPND-export-US but adds a requirement related to modifications of the code.


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@carlwgeorge - now that this has been accepted, could you create the PR for the files? (if you can't by the end of the week, let me know)
