### ISSUE TITLE
New license request: Furuseth [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2140]
**1.** License Name: None
**2.** Short identifier: Furuseth
**3.** License Author or steward: Unknown
**4.** Comments: This is a simple permissive FOSS license covering portions of OpenLDAP, packaged in all Linux distributions.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/294
**6.** URL(s): https://git.openldap.org/openldap/openldap/-/blob/master/COPYRIGHT?ref_type=heads#L39-51
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://www.openldap.org

**Comment by richardfontana** [comment]
Note: there is no Fedora issue for this but I anticipate that one will be created in the near future.

**Comment by jlovejoy** [comment]
license text:

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that this notice is preserved.
The names of the copyright holders may not be used to endorse or
promote products derived from this software without their specific
prior written permission.  This software is provided ``as is''
without express or implied warranty.

**Comment by jlovejoy** [comment]
very similar to #2141 but add can't-use-names-to-endorse part; and similar to `BSD-4.3RENO` but omits the "due credit" part.

+1 to add as new license

**Comment by swinslow** [comment]
+1 to add as new license

I don't have a good suggestion on naming, but @richardfontana's suggestion of `Furuseth` for ID makes sense given that's the earliest copyright range shown in the example, and I'm not easily finding instances of this particular license elsewhere. "Furuseth License" as the name seems to work as well.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Furuseth License

## License ID

Furuseth

## XML markup

none

## Notes:

none



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
