### ISSUE TITLE
New license request: PADL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2141]
**1.** License Name: None
**2.** Short identifier: PADL
**3.** License Author or steward: Unknown
**4.** Comments: This is a simple permissive FOSS license covering portions of OpenLDAP, packaged in all Linux distributions.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/295
**6.** URL(s): https://git.openldap.org/openldap/openldap/-/blob/master/libraries/libldap/os-local.c?ref_type=heads#L19-23
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://www.openldap.org

**Comment by richardfontana** [comment]
Note: there is no Fedora issue for this but I anticipate that one may be created in the near future.

**Comment by richardfontana** [comment]
This license resembles the `BSD-4.3RENO` Michigan variant noted in #2142 except that it adds "with or without modification".

**Comment by jlovejoy** [comment]
license text for convenience:

 Portions (C) Copyright PADL Software Pty Ltd. 1999

Redistribution and use in source and binary forms, with or without 
 modification, are permitted provided that this notice is preserved
 and that due credit is given to PADL Software Pty Ltd. This software
 is provided ``as is'' without express or implied warranty.

**Comment by jlovejoy** [comment]
it also omits "The name of ....
may not be used to endorse or promote products derived from this
software without specific written prior permission" which is present in `BSD-4.3RENO`

+1 to add as new license

**Comment by InSwiss** [comment]
+1 to add as new license but can we make the Copyright part as placeholder to be able to use in other projects? 

Portions (C) <copyright>
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that this notice is preserved
and that due credit is given to <copyright>. This software
is provided "as is'' without express or implied warranty.

**Comment by jlovejoy** [comment]
for naming, I"m thinking we can go with @richardfontana suggestion since the name is used in the text. This is in Open LDAP, but it's not another variant on the Open LDAP license as seems to only apply to this specific code.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

PDAL License

## License ID

PDAL

## XML markup

none

## Notes:

This is similar to BSD-4.3RENO and Furuseth


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by swinslow** [comment]
@jlovejoy I think the name and ID were entered incorrectly for the inclusion decision [above](https://github.com/spdx/license-list-XML/issues/2141#issuecomment-1738394734)?

It says ID as `PDAL` and name as "PDAL License", but the request and project name appear to be "PADL" (swapping A and D). Should that be corrected?

**Comment by jlovejoy** [comment]
@swinslow - good catch, apparently I have typing dyslexia - will correct above!
