### ISSUE TITLE
University of Michigan variant of BSD-4.3RENO

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2142]
This license covers [portions of OpenLDAP](https://git.openldap.org/openldap/openldap/-/blob/master/COPYRIGHT#L55-63):
```
Portions Copyright (c) 1992-1996 Regents of the University of Michigan.
All rights reserved.

Redistribution and use in source and binary forms are permitted
provided that this notice is preserved and that due credit is given
to the University of Michigan at Ann Arbor.  The name of the
University may not be used to endorse or promote products derived
from this software without specific prior written permission.  This
software is provided ``as is'' without express or implied warranty.
```
Apart from names, the only difference seems to be that `BSD-4.3RENO` has "specific written prior permission".

**Comment by jlovejoy** [comment]
Looks like it uses a different name (easy to accommodate with markup) and yes, has "specific prior written permission" instead of "specific written prior permission" - I can't imagine that variation meaning something different??

@swinslow @Pizza-Ria  - thoughts?

**Comment by swinslow** [comment]
Yes, fine to accommodate "prior written" and "written prior" via markup
