### ISSUE TITLE
Recognise a variant of the GNU-compiler-exception

### ISSUE THREAD

**Issue by submachine** [spdx/license-list-XML#2152]
The current exception text is:

            As a special exception, if you link this library with files
            compiled with a GNU compiler to produce an executable, this
            does not cause the resulting executable to be covered by
            the GNU General Public License. This exception does not
            however invalidate any other reasons why the executable
            file might be covered by the GNU General Public License.

I recently ran into a variant of this with minor changes and an additional sentence:

        As a special exception, if you link the code in this file with
        files compiled with a GNU compiler to produce an executable,
        that does not cause the resulting executable to be covered by
        the GNU Lesser General Public License.  This exception does not
        however invalidate any other reasons why the executable file
        might be covered by the GNU Lesser General Public License.
        This exception applies to code released by its copyright holders
        in files containing the exception.

This wording is used in several libio source files in glibc; e.g.:
https://sourceware.org/git?p=glibc.git;a=blob;f=libio/fputc.c;h=9ef6166dd6b5cf566c7bd591832c2b73d34e08db;hb=HEAD#l18

Can the GNU-compiler-exception XML be enhanced to match this version as well?

**Comment by submachine** [comment]
I found this while doing a license analysis for Fedora's glibc package; I brought this up for license review by Fedora (https://gitlab.com/fedora/legal/fedora-license-data/-/issues/352) where @richardfontana suggested I file an SPDX issue.

**Comment by richardfontana** [comment]
Assuming the last sentence is irrelevant, the difference here is that "GNU General Public License" is replaced with "GNU Lesser General Public License".

**Comment by submachine** [comment]
@jlovejoy I just noticed that you assigned this to me. Please let me know what (if anything) I can do to help move this issue towards a conclusion. Thanks!

**Comment by jlovejoy** [comment]
@submachine - just tracking who created issue for now!

**Comment by jlovejoy** [comment]
there is something familiar about the first variant, but haven't figured out why. I thought we had another recent submission with "Free Software" - need to look more.

**Comment by submachine** [comment]
@jlovejoy based on the milestone, do you expect there is a good chance this issue have a resolution by the end of January? Thanks!

**Comment by jlovejoy** [comment]
These are the differences b/w this variant and https://spdx.org/licenses/GNU-compiler-exception.html and my thoughts on each:
1) add "Lesser" in 2 places - this is something we've accommodated before for markup, so I think it's fine here too
2) "this library" v. "the code in this file" - I also don't think this is a substantive difference, although it could be argued to alter the scope
3) "this does" v. "that does" - not a substantive difference
4) additional sentence at the end, which I agree with @richardfontana that it doesn't add anything much (and I can't find this elsewhere), would have to be optional

I've made #2298 to potentially address this, if others agree, as this is a high-priority issue.

**Comment by swinslow** [comment]
Responding to @jlovejoy's list of differences:

* 1 - agreed, fine to accommodate
* 2 - I'm also okay with this being treated as equivalent for matching purposes. I see this as addressing "what is covered by the exception," which we have accommodated via markup in other situations (e.g. [MIT](https://spdx.org/licenses/MIT.html))
* 3 - agreed, non-substantive and can handle with markup
* 4 - also OK with incorporating this as optional text, for same reason as 2

Given this, I'm +1 to handling the variations here with markup to GNU-compiler-exception.

@jlovejoy I'll review #2298 and will merge it if it looks like it's passing tests and complete. Thanks!
