### ISSUE TITLE
New license request: NASA-FV-License-Agreement

### ISSUE THREAD

**Issue by mattiaverga** [spdx/license-list-XML#2162]
### How license meets inclusion principles

The license grant all rights, provided that the copyright notice and disclaimer of warranty appears in all copies.

### License Name

NASA FV License Agreement

### Suggested short identifier

NASA-FV-License-Agreement

### License or Exception?

license

### URL to license text

https://heasarc.gsfc.nasa.gov/docs/software/ftools/fv/doc/license.html

### OSI Status

Not Submitted

### License author or steward

Unknown

### URL to project(s) that use license

- https://heasarc.gsfc.nasa.gov/docs/software/ftools/fv/
- https://github.com/indilib/indi/blob/master/libs/fpack/fpack.h

### paste text of license here

FV License Agreement

Copyright (Unpublished--all rights reserved under the copyright laws of
the United States), U.S. Government as represented by the Administrator
of the National Aeronautics and Space Administration.  No copyright is
claimed in the United States under Title 17, U.S. Code.

Permission to freely use, copy, modify, and distribute this software
and its documentation without fee is hereby granted, provided that this
copyright notice and disclaimer of warranty appears in all copies.

DISCLAIMER: 

THE SOFTWARE IS PROVIDED 'AS IS' WITHOUT ANY WARRANTY OF ANY KIND,
EITHER EXPRESSED, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO,
ANY WARRANTY THAT THE SOFTWARE WILL CONFORM TO SPECIFICATIONS, ANY
IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE, AND FREEDOM FROM INFRINGEMENT, AND ANY WARRANTY THAT THE
DOCUMENTATION WILL CONFORM TO THE SOFTWARE, OR ANY WARRANTY THAT THE
SOFTWARE WILL BE ERROR FREE.  IN NO EVENT SHALL NASA BE LIABLE FOR ANY
DAMAGES, INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, SPECIAL OR
CONSEQUENTIAL DAMAGES, ARISING OUT OF, RESULTING FROM, OR IN ANY WAY
CONNECTED WITH THIS SOFTWARE, WHETHER OR NOT BASED UPON WARRANTY,
CONTRACT, TORT , OR OTHERWISE, WHETHER OR NOT INJURY WAS SUSTAINED BY
PERSONS OR PROPERTY OR OTHERWISE, AND WHETHER OR NOT LOSS WAS SUSTAINED
FROM, OR AROSE OUT OF THE RESULTS OF, OR USE OF, THE SOFTWARE OR
SERVICES PROVIDED HEREUNDER.

**Comment by jlovejoy** [comment]
@mattiaverga - is this from a Fedora package review? If so, can you add link to the Gitlab issue here, so we can track/connect dots?

**Comment by mattiaverga** [comment]
> nevermind, it looks like this is an exact match to [CFITSIO License (CFITSIO)](https://spdx.org/licenses/CFITSIO.html)

Oh, you're right, cfitsio and fvtools are from the same software collection and I was mislead by searching for an "FV license agreement" as the title reported...

Should I propose a PR adding just a CrossRef to the CFITSIO license file, or should I file a brand new license file with the new license name?

**Comment by jlovejoy** [comment]
@mattiaverga - we do not need a new license file b/c it is a match to CFITSIO and so you can use that id.

but yes, a PR to add the additional crossRef would be great!
