### ISSUE TITLE
New license request: Silk [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#2164]
**1.** License Name: Silk License
**2.** Short identifier: Silk
**3.** License Author or steward: Unknown
**4.** Comments: The license grant all rights, provided that the copyright notice and disclaimer of warranty appears in all copies.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/296
**6.** URL(s): https://tools.netsa.cert.org/silk/license.html
**7.** OSI Status: Unknown
**8.** Example Projects: Silk, https://tools.netsa.cert.org/silk/

**Comment by jlovejoy** [comment]
this is the GPL-2.0 with some additional information related to third party software at the bottom. I don't think that's part of the license or that they were intending to modify the GPL-2.0

As such, I wouldn't consider this a new license - am I missing something @chenrui333
