### ISSUE TITLE
New license request: AML-glslang

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2168]
**1.** License Name: NVIDIA
**2.** Short identifier: NVIDIA
**3.** License Author or steward: Unknow
**4.** Comments: This license is used in glslang. It was discovered using Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/348
**5.** License Request Url: http://tools.spdx.org/app/license_requests/299
**6.** URL(s): https://github.com/KhronosGroup/glslang/blob/main/LICENSE.txt#L949
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/KhronosGroup/glslang

**Comment by xsuchy** [comment]
<details>
<summary>Text of the license</summary>
Copyright (c) 2002, NVIDIA Corporation.

NVIDIA Corporation("NVIDIA") supplies this software to you in
consideration of your agreement to the following terms, and your use,
installation, modification or redistribution of this NVIDIA software
constitutes acceptance of these terms.  If you do not agree with these
terms, please do not use, install, modify or redistribute this NVIDIA
software.

In consideration of your agreement to abide by the following terms, and
subject to these terms, NVIDIA grants you a personal, non-exclusive
license, under NVIDIA's copyrights in this original NVIDIA software (the
"NVIDIA Software"), to use, reproduce, modify and redistribute the
NVIDIA Software, with or without modifications, in source and/or binary
forms; provided that if you redistribute the NVIDIA Software, you must
retain the copyright notice of NVIDIA, this notice and the following
text and disclaimers in all such redistributions of the NVIDIA Software.
Neither the name, trademarks, service marks nor logos of NVIDIA
Corporation may be used to endorse or promote products derived from the
NVIDIA Software without specific prior written permission from NVIDIA.
Except as expressly stated in this notice, no other rights or licenses
express or implied, are granted by NVIDIA herein, including but not
limited to any patent rights that may be infringed by your derivative
works or by other works in which the NVIDIA Software may be
incorporated. No hardware is licensed hereunder.

THE NVIDIA SOFTWARE IS BEING PROVIDED ON AN "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED,
INCLUDING WITHOUT LIMITATION, WARRANTIES OR CONDITIONS OF TITLE,
NON-INFRINGEMENT, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
ITS USE AND OPERATION EITHER ALONE OR IN COMBINATION WITH OTHER
PRODUCTS.

IN NO EVENT SHALL NVIDIA BE LIABLE FOR ANY SPECIAL, INDIRECT,
INCIDENTAL, EXEMPLARY, CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, LOST PROFITS; PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) OR ARISING IN ANY WAY
OUT OF THE USE, REPRODUCTION, MODIFICATION AND/OR DISTRIBUTION OF THE
NVIDIA SOFTWARE, HOWEVER CAUSED AND WHETHER UNDER THEORY OF CONTRACT,
TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, EVEN IF
NVIDIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
</details>

**Comment by Pizza-Ria** [comment]
This is close to https://spdx.org/licenses/AML.html but there are some differences that don't fall into the nonsubstantive variations outlined in the [Matching Guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/):

- Slightly different wording on the retention of copyright notice.
- THE NVIDIA SOFTWARE IS BEING PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR **CONDITIONS** OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED, WARRANTIES OR **CONDITIONS OF TITLE.**
- IN NO EVENT SHALL [NAME] BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL OR, **EXEMPLARY**, CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, TO, **LOST PROFITS**....

**Comment by Pizza-Ria** [comment]
So, OK to add unless someone wants to convince me otherwise.

**Comment by zvr** [comment]
If it's not significantly different, should we simply "templatize" AML so that it matches this text, as well?

**Comment by jlovejoy** [comment]
we have generally treated changes to the disclaimer as potentially substantive.  I'm not sure how I feel about the "and conditions" part
types of damages is also a tough one... need to think more on this one.

@swinslow @richardfontana - thoughts?

**Comment by richardfontana** [comment]
Isn't the different wording regarding retention of the copyright notice substantive (by typical SPDX-legal standards)?

`AML`: "if you redistribute the Apple Software **in its entirety and without modifications,** you must retain this notice and the following text and disclaimers in all such redistributions of the Apple Software."

NVIDIA license: "if you redistribute the NVIDIA Software, you must
retain the copyright notice of NVIDIA, this notice and the following
text and disclaimers in all such redistributions of the NVIDIA Software."

**Comment by swinslow** [comment]
Thank you @Pizza-Ria for the helpful summary of the differences from AML!

In my view, the addition of an explicit carveout for "EXEMPLARY" damages is enough of a possibly-substantive difference to say that this one should be separate. And to @richardfontana's point, I agree also that the absence of "in its entirety and without modifications" likely changes the obligation enough that we should treat it as separate from AML.

So I'm +1 to add it, in light of it being largely comparable to AML which is already on the list, together with its use in Fedora.

For the name and ID, that's where I'm a bit less clear what to go with. I'm guessing NVIDIA has used a lot of different licenses from time to time, so I'm hesitant to declare this one in particular as the "NVIDIA" license?

Looking at [this NVIDIA page](https://docs.omniverse.nvidia.com/install-guide/latest/common/licenses.html), which appears to list many different license texts for things that NVIDIA distributes, the only occurrence of this particular text seems to be from glslang -- the same project that @xsuchy submitted this one for. And a Google search for the initial snippet of text ("supplies this software to you in consideration of your agreement to the following terms") across nvidia.com similarly only shows this glslang usage.

Given that, how about `NVIDIA-glslang` as the ID and `NVIDIA glslang License` as the name?

**Comment by swinslow** [comment]
Discussed on 2023-10-26 legal team call. Agreed to add -- for identifier, `AML-glslang`; for license name, "AML glslang variant License"
