### ISSUE TITLE
New license request: BSD-Systemics-W3Works

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2169]
**1.** License Name: W3Works License
**2.** Short identifier: W3Works
**3.** License Author or steward: Unknow
**4.** Comments: This license is included in perl-Crypt-Blowfish. It was discovered during Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/349
**5.** License Request Url: http://tools.spdx.org/app/license_requests/300
**6.** URL(s): https://metacpan.org/release/DPARIS/Crypt-Blowfish-2.14/source/COPYRIGHT#L7
**7.** OSI Status: Unknown
**8.** Example Projects: https://metacpan.org/release/DPARIS/Crypt-Blowfish-2.14/view/Blowfish.pm

**Comment by xsuchy** [comment]
<details>
<summary>Text of the license</summary>
<pre>
Modifications and Current Implimentation Copyright (C) 2000 W3Works, LLC.
 
All rights reserved.
 
Current implimentation contains modifications made by W3Works, LLC.  The 
modifications remain copyright of W3Works, LLC and attribution for these 
modification should be made to W3Works, LLC.  These modifications and 
this copyright must remain with this package.
 
Additions to the Restrictions set out below are:
1. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product inculdes software developed by W3Works, LLC (http://www.w3works.com)
 
   NO ADDITIONAL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
   THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE EXTENDED BY THIS DISTRIBUTION.
 
   Any subsequent derrivations of this package must retainl this copyright.
</pre>
</details>

Note that there is several typos in the original license. "derrivations", "retail", "implementation",  "acknowledgement", and  "includes".

**Comment by Pizza-Ria** [comment]
This is more of a rider than a license unto itself - I wonder if we could create another category similar to the exceptions that we have been approving recently.  Otherwise, I think we would have to include both the original (as depicted in https://metacpan.org/release/DPARIS/Crypt-Blowfish-2.14/source/COPYRIGHT#L7) and the rider to have a complete license.

**Comment by Pizza-Ria** [comment]
I'd also vote for fixing the spelling errors ... unless that would cause an issue with the matching tool.

**Comment by xsuchy** [comment]
The typos can be wrapped with <alt> tag and allow both original typos and correct wording.

**Comment by jlovejoy** [comment]
so, this is a match to `BSD-Systemics` but adds to the top, this part:
===
Copyright (C) 1995, 1996 Systemics Ltd (http://www.systemics.com/)
 
Modifications and Current Implimentation Copyright (C) 2000 W3Works, LLC.
 
All rights reserved.
 
Current implimentation contains modifications made by W3Works, LLC.  The 
modifications remain copyright of W3Works, LLC and attribution for these 
modification should be made to W3Works, LLC.  These modifications and 
this copyright must remain with this package.
 
Additions to the Restrictions set out below are:
1. All advertising materials mentioning features or use of this software
   must display the following acknowledgement:
   This product inculdes software developed by W3Works, LLC (http://www.w3works.com/)
 
   NO ADDITIONAL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXTENDED BY THIS DISTRIBUTION.
 
   Any subsequent derrivations of this package must retainl this copyright.
====
and also adds:
"This library and applications are FREE FOR COMMERCIAL AND NON-COMMERCIAL USE as long as the following conditions are adhered to."

**Comment by jlovejoy** [comment]
so, yeah... I'm not really all for adding a new category of "things"... This is certainly adding another obligation re: advertising materials to the BSD-Systemics.

Given it's all contained in one file, I'm somewhat inclined to not try to parse it and add as one thing/new license

**Comment by richardfontana** [comment]
I don't think it's clear that this is really an addendum to the BSD-Systemics license in any precise sort of sense.

**Comment by swinslow** [comment]
+1 to @jlovejoy's comment above. I'm inclined to just add this as a new license with a separate identifier for the license in its entirety, e.g. all of the text of https://metacpan.org/release/DPARIS/Crypt-Blowfish-2.14/source/COPYRIGHT.

The added text is clearly an added restriction rather than an exception, so it wouldn't be appropriate to add to the [Exceptions List](https://spdx.org/licenses/exceptions-index.html).

As far as name / ID, I'm generally fine with `W3Works` as ID and "W3Works License" as name.

**Comment by swinslow** [comment]
Discussed on 2023-10-26 legal team call, agreed to use `BSD-Systemics-W3Works` as the ID and "Systemics W3Works BSD variant license" as the name.

**Comment by jlovejoy** [comment]
is it correct that this is the only instance we've seen of this and is seemingly specific to W3Works?

**Comment by richardfontana** [comment]
Yes, it may be specific to one Perl module but I'm not sure.
