### ISSUE TITLE
Possibly malformatted XML in the HPND-sell-variant

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2176]
Discovered by @richardfontana in [fedora-license-data#363](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/363#note_1581552016).

The [HPND-sell-variant.xml](https://github.com/spdx/license-list-XML/blob/main/src/HPND-sell-variant.xml) contains an `<optional>` within another `<optional>`, see line 19
```xml
<optional spacing="after">, and that the name <optional>of</optional>
...
</optional>
```

It is unclear if this was intentional or  "possibly there was an intention to make the anti-endorsement language optional?" [[1]](https://gitlab.com/fedora/legal/fedora-license-data/-/issues/363#note_1581552016)

**Comment by jlovejoy** [comment]
it is intentional, sigh... I have an entire Google document "documenting" all the various HPND variations we've been discovering, including a closer look at the original intention of the templating as per the original submission to OSI!

hoping to add some sort of write-up on this later.. :)

**Comment by jlovejoy** [comment]
to clarify: the optional "of" is intentionally nested inside the entire optional no advertising clause, as per the original submission to OSI. It has to do with accommodating "the name Joe not be used" and "the name of Joe or Joe's cousins not be used"

I think the markup is right and there's nothing to do here, but if I've missed something let me know

**Comment by richardfontana** [comment]
@jlovejoy I think I must have misread the XML, so I am pretty sure nothing to do here.
