### ISSUE TITLE
New license request: HPND-sell-variant-Matic [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2178]
**1.** License Name: HPND-sell-variant-Matic
**2.** Short identifier: HPND-sell-variant-Matic
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. This is a license used by xkeyboard-config.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/363
**5.** License Request Url: http://tools.spdx.org/app/license_requests/303
**6.** URL(s): https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/COPYING?ref_type=heads#L881
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/xserver/

**Comment by whot** [comment]
This may be a superfluous request, it's identical to the HPND-sell-variant but it excludes the `and that the name of <copyright holder> <or related entities> not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission `. That part is already optional in HPND-sell-variant but it's unclear to me if optional apply to parts or the whole optional section only.
 
It also excludes the disclaimer.

```
Permission to use, copy, modify, distribute, and sell this software
and its documentation for any purpose is hereby granted without fee,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.  Davor Matic makes no representations about
the suitability of this software for any purpose.  It is provided "as
is" without express or implied warranty.
```

**Comment by dcantrell** [comment]
This also appears similar to this license found during x11-ssh-askpass license review in Fedora:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/355

It tried to submit a new license request using the SPDX tool, but it was rejected and pointed me to this license as matching.

**Comment by jlovejoy** [comment]
This is a match to `HPND-sell-variant` indeed

@dcantrell - yours has a slight variation that I think can be accommodated via mark-up - will make new issue to track that
