### ISSUE TITLE
New license request: HPND-Adobe [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2182]
**1.** License Name: HPND-Adobe
**2.** Short identifier: HPND-Adobe
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. This is a license used by the Xorg X server.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/364
**5.** License Request Url: http://tools.spdx.org/app/license_requests/304
**6.** URL(s): https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/COPYING?ref_type=heads#L752
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/xserver/

**Comment by whot** [comment]
```
(c)Copyright 1988,1991 Adobe Systems Incorporated.
All rights reserved.

Permission to use, copy, modify, distribute, and sublicense this software and its
documentation for any purpose and without fee is hereby granted, provided that
the above copyright notices appear in all copies and that both those copyright
notices and this permission notice appear in supporting documentation and that
the name of Adobe Systems Incorporated not be used in advertising or publicity
pertaining to distribution of the software without specific, written prior
permission.  No trademark license to use the Adobe trademarks is hereby
granted.  If the Adobe trademark "Display PostScript"(tm) is used to describe
this software, its functionality or for any other purpose, such use shall be
limited to a statement that this software works in conjunction with the Display
PostScript system.  Proper trademark attribution to reflect Adobe's ownership
of the trademark shall be given whenever any such reference to the Display
PostScript system is made.

ADOBE MAKES NO REPRESENTATIONS ABOUT THE SUITABILITY OF THE SOFTWARE FOR ANY
PURPOSE.  IT IS PROVIDED "AS IS" WITHOUT EXPRESS OR IMPLIED WARRANTY.  ADOBE
DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-
INFRINGEMENT OF THIRD PARTY RIGHTS.  IN NO EVENT SHALL ADOBE BE LIABLE TO YOU
OR ANY OTHER PARTY FOR ANY SPECIAL, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY
DAMAGES WHATSOEVER WHETHER IN AN ACTION OF CONTRACT,NEGLIGENCE, STRICT
LIABILITY OR ANY OTHER ACTION ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.  ADOBE WILL NOT PROVIDE ANY TRAINING OR OTHER
SUPPORT FOR THE SOFTWARE.

Adobe, PostScript, and Display PostScript are trademarks of Adobe Systems
Incorporated which may be registered in certain jurisdictions.
```

Seems to be a variant of HPND with the trademark and training additions.

**Comment by jlovejoy** [comment]
+1 to add as new license and I don't think I'd use "HPND" in the id since it adds a whole new clause. Since it is Adobe specific, I think it's ok to use that name though

**Comment by whot** [comment]
> +1 to add as a new license, this one is also found on the old Xfree86 website at https://www.xfree86.org/4.0/LICENSE3.html (section 3.8).

ftr, that's the same source package, since the matching code pre-dates the xfree86-xorg split, that license will be in any X server fork.

> This license appears to be tied specifically to Adobe's Display PostScript code,

There is only one file in the X server that uses this license ([dix/dixutils.c](https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/dix/dixutils.c)) and it doesn't seem to have any obvious post script code. Figuring out more details here is a question for people willing to wear topees :)

>  but do you think Adobe-Display-PostScript as an ID and "Adobe Display PostScript License" as a name would be accurate(ish) here?

Yes, I think that's good enough. There is no other instance of this license in my local copy of the various xorg repositories.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Adobe Display PostScript License

## License ID

Adobe-Display-PostScript

## XML markup

none

## Notes:

none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
sorry @whot - this fell between the cracks, I fear!
