### ISSUE TITLE
New license request: DEC-3-Clause [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by whot** [spdx/license-list-XML#2183]
**1.** License Name: DEC-3-Clause
**2.** Short identifier: DEC-3-Clause
**3.** License Author or steward: Unknown
**4.** Comments: A package using this license is used in Fedora and this particular license was found during license review. See the fedora-license-data issue [1] for details. This is a license used by the Xorg X server.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/362
**5.** License Request Url: http://tools.spdx.org/app/license_requests/305
**6.** URL(s): https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/COPYING?ref_type=heads#L239
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/xserver/

**Comment by Pizza-Ria** [comment]
Found a few instances of this language including a license-ref from Scancode 2023:  [LicenseRef-scancode-broadcom-cfe](https://scancode-licensedb.aboutcode.org/broadcom-cfe.html).  Also, Broadcom Common Firmware Environment (Cfe) in an [Intel doc - 2000](https://www.intel.com/content/dam/support/us/en/documents/network-and-i-o/fabric-products/True_Scale_Products_ThirdParty_Readme_H13245_004.pdf).  

The DEC citation, however, is from 1997 so it may be the senior version.

**Comment by whot** [comment]
cc @jexposit

**Comment by jlovejoy** [comment]
+1 to add and use markup to accommodate different names found (Broadcom and DEC)
seem likely the DEC use came first, as @Pizza-Ria notes, but still a bit cloudy on naming...

**Comment by swinslow** [comment]
Text for this license:

```
Copyright 1997 Digital Equipment Corporation.
All rights reserved.

This software is furnished under license and may be used and copied only in
accordance with the following terms and conditions.  Subject to these
conditions, you may download, copy, install, use, modify and distribute
this software in source and/or binary form. No title or ownership is
transferred hereby.

1) Any source code used, modified or distributed must reproduce and retain
   this copyright notice and list of conditions as they appear in the
   source file.

2) No right is granted to use any trade name, trademark, or logo of Digital
   Equipment Corporation. Neither the "Digital Equipment Corporation"
   name nor any trademark or logo of Digital Equipment Corporation may be
   used to endorse or promote products derived from this software without
   the prior written permission of Digital Equipment Corporation.

3) This software is provided "AS-IS" and any express or implied warranties,
   including but not limited to, any implied warranties of merchantability,
   fitness for a particular purpose, or non-infringement are disclaimed.
   In no event shall DIGITAL be liable for any damages whatsoever, and in
   particular, DIGITAL shall not be liable for special, indirect,
   consequential, or incidental damages or damages for lost profits, loss
   of revenue or loss of use, whether such damages arise in contract,
   negligence, tort, under statute, in equity, at law or otherwise, even
   if advised of the possibility of such damage.

```

**Comment by swinslow** [comment]
The DEC / Digital version included in this request is close to the Broadcom/Intel version linked above, but there are some differences (e.g. different license grant and disclaimer language) that are sufficiently different that I don't think we should consider it the "same" license for present purposes.

For the DEC version being requested here, I'm +1 to add. `DEC-3-Clause` as ID and "DEC 3-Clause License" as name seem as good to me as anything else. I could be persuaded otherwise, I don't have a strong feeling here.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

DEC 3-Clause License

## License ID

DEC-3-Clause

## XML markup

none

## Notes:

none



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
