### ISSUE TITLE
New license request: FSFAP [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by fberat** [spdx/license-list-XML#2186]
**1.** License Name: FSF All Permissive License
**2.** Short identifier: FSFAP
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora and has been found during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/359

This seems to be a variant of the FSFAP without the warranty disclaimer. As stated in the URL to license text: "Older versions of this license did not have the second sentence with the express warranty disclaimer."
**5.** License Request Url: http://tools.spdx.org/app/license_requests/306
**6.** URL(s): https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_check_enable_debug.m4#L36

**Comment by swinslow** [comment]
Proposed license text for reference:

```
Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved.
```

Text of existing license [FSFAP](https://spdx.org/licenses/FSFAP.html):

```
Copying and distribution of this file, with or without modification, are
permitted in any medium without royalty provided the copyright notice
and this notice are preserved. This file is offered as-is, without any warranty.
```

**Comment by swinslow** [comment]
Interesting to note the following language from the [FSF's guidance](https://www.gnu.org/prep/maintain/html_node/License-Notices-for-Other-Files.html) on what SPDX calls FSFAP:

> Older versions of this license did not have the second sentence with the express warranty disclaimer. There is no urgent need to update existing files, but new files should use the new text.

To me, this suggests that these statements are viewed as being similar and related, but substantively different if the final sentence with the warranty is not included.

I think we have two options here:

1. modify FSFAP to make the final sentence optional; or
2. add a new license ID with only the first sentence and omitting the second.

Option 1 would be in line with how SPDX has handled [HPND](https://spdx.org/licenses/HPND.html); however, in that case the HPND template of optional texts was based on the OSI's original approval of those varying texts. So I'm not sure whether that should guide us here.

I'm inclined to go with Option 2, which I think is how we've more typically handled license variants with warranty disclaimers included vs. omitted. See for example [FSFULLR](https://spdx.org/licenses/FSFULLR.html) vs. [FSFULLRWD](https://spdx.org/licenses/FSFULLRWD.html).

If we go with Option 2, I might suggest `FSFAP-old` as identifier in light of the FSF's statement on the page linked above that the variant without the warranty disclaimer is an older version of the license.

**Comment by swinslow** [comment]
Discussed on 2023-12-14 legal team call, `FSFAP-old` for identifier and "FSF All Permissive License (older version)" for name; no objections

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

FSF All Permissive License (older version)

## License ID

FSFAP-old

## XML markup

None

## Notes:

This is an older version of FSFAP that omits the second sentence with the express warranty disclaimer. 


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@fberat -sorry this decision took so long!
Can you prepare a PR for this?

**Comment by swinslow** [comment]
Discussed further on 2023-12-14 legal team call, realized that this is the same as #2214 / #2255 -- since that was previously discussed, we're closing this one. The identifier to use will be `FSFAP-no-warranty-disclaimer`. Apologies for the conclusion!
