### ISSUE TITLE
Remove/make optional first paragraph of Caldera license

### ISSUE THREAD

**Issue by uhliarik** [spdx/license-list-XML#2195]
Hello, I would like to ask you if it is possible to make following paragraph optional or remove it entirely from https://spdx.org/licenses/Caldera.html

```
Caldera International, Inc. hereby grants a fee free license that includes the rights use, modify and distribute this named source code, including creating derived binary products created from the source code. The source code for which Caldera International, Inc. grants rights are limited to the following UNIX Operating Systems that operate on the 16-Bit PDP-11 CPU and early versions of the 32-Bit UNIX Operating System, with specific exclusion of UNIX System III and UNIX System V and successor operating systems:

32-bit 32V UNIX

16 bit UNIX Versions 1, 2, 3, 4, 5, 6, 7

Caldera International, Inc. makes no guarantees or commitments that any source code is available from Caldera International, Inc.

The following copyright notice applies to the source code files for which this license is granted.
```

This license is used in apr library but without the first paragraph - https://github.com/apache/apr/blob/trunk/LICENSE#L298C6-L298C29

The source code used here was released  for ancient versions of Unix under this BSD-like license. This was the announcement e-mail - http://www.lemis.com/grog/UNIX/

more info - https://lists.apache.org/thread/fj060sp2m0nsb07744gbd1ttb99p07ho

**Comment by richardfontana** [comment]
Discussion at Fedora License Data: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/366

**Comment by jlovejoy** [comment]
and was raised at https://lists.spdx.org/g/Spdx-legal/topic/86580130#3011

**Comment by swinslow** [comment]
@jlovejoy I'm uncertain about whether we can safely say that the first paragraph is truly non-substantive.

I note the discussion at the Fedora legal thread. But the wording of that first paragraph is weird enough that I could _arguably_ see someone having a difference of opinion about whether it imposes different obligations or restrictions when it's present.

Given that, I'm inclined to say that it should more likely be a separate license identifier. But I'm willing to be overruled on this if others feel I'm off-base here.

Would there be harm in creating a separate identifier, something like `Caldera-no-preamble`, and using that? We can include in the notes a description of the difference from standard `Caldera`. I'll volunteer to create the PR if there's agreement to take this approach.

**Comment by swinslow** [comment]
Discussed on 2024-01-11, decided to add separate identifier with ID `Caldera-no-preamble` and name "Caldera License (without preamble)"
