### ISSUE TITLE
Update HPND-sell-variant-MIT-disclaimer to allow matching to the included text

### ISSUE THREAD

**Issue by dcantrell** [spdx/license-list-XML#2196]
**1.** License Name: HPND-sell-variant-MIT-disclaimer
**2.** Short identifier: same
**3.** License Author or steward: Jim Knoble
**4.** Comments: This license is used in Fedora Linux and was found during a license review of the x11-ssh-askpass package.  Here is the corresponding issue in the fedora-license-data project:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/356

As the comments in the fedora-license-data ticket note, the text of this license is the same as the HPND-sell-variant-MIT-disclaimer license, but the two paragraphs are in a different order.  I would prefer to call this license HPND-sell-variant-MIT-disclaimer as well, but the SPDX matching rules need updating.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/307
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/39177089-9f34-4a89-926d-b9a5abb4cfc4.png

**Note:**
The license closely matched with the following license ID(s): HPND-sell-variant-MIT-disclaimer

**Comment by jlovejoy** [comment]
text of license:

Permission to use, copy, modify, distribute, and sell this software and 
its documentation for any purpose is hereby granted without fee, 
provided that the above copyright notice appear in all copies 
and 
that both that copyright notice and this permission notice appear in supporting
documentation.  

No representations are made about the suitability of this software for any purpose.  
It is provided "as is" without express or implied warranty.

**Comment by jlovejoy** [comment]
so, yeah, it's the 
"No representations are made about..."
v.
"NAME makes no representations about..."

Feels like that is prime for markup. Although I'm not sure how to do that...

**Comment by swinslow** [comment]
Discussed with @jlovejoy, agreed to add this as a new separate license ID `HPND-sell-variant-MIT-disclaimer-rev` to reflect that this has the paragraphs in reverse order.

**Comment by jlovejoy** [comment]
@goneall - not sure if you saw this, but this license is a match to one on the list with the paragraphs in reverse order (only two paragraphs). I am surprised that the matching tool picked this up, which makes me wonder if we can consider it a match??

**Comment by xsuchy** [comment]
@jlovejoy Literarly see @swinslow two comments above (From Feb7)
