### ISSUE TITLE
New license request: Add Radvd license

### ISSUE THREAD

**Issue by mosvald** [spdx/license-list-XML#2201]
### How license meets inclusion principles

This license was apparently missed from being included in the initial merge because it was thought nobody used it. It is considered as "good" on Fedora:

https://fedoraproject.org/wiki/Licensing/radvd_License
https://gitlab.com/fedora/legal/fedora-license-data/-/blob/main/data/LicenseRef-radvd.toml

fedora-license-data issue:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/369

### License Name

radvd License

### Suggested short identifier

Radvd

### License or Exception?

license

### URL to license text

https://github.com/radvd-project/radvd/blob/master/COPYRIGHT

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/radvd-project/radvd/

### paste text of license here

  The author(s) grant permission for redistribution and use in source and
binary forms, with or without modification, of the software and documentation
provided that the following conditions are met:

0. If you receive a version of the software that is specifically labelled
   as not being for redistribution (check the version message and/or README),
   you are not permitted to redistribute that version of the software in any
   way or form.
1. All terms of all other applicable copyrights and licenses must be
   followed.
2. Redistributions of source code must retain the authors' copyright
   notice(s), this list of conditions, and the following disclaimer.
3. Redistributions in binary form must reproduce the authors' copyright
   notice(s), this list of conditions, and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
4. All advertising materials mentioning features or use of this software
   must display the following acknowledgement with the name(s) of the
   authors as specified in the copyright notice(s) substituted where
   indicated:

        This product includes software developed by the authors which are 
	mentioned at the start of the source files and other contributors.

5. Neither the name(s) of the author(s) nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY ITS AUTHORS AND CONTRIBUTORS ``AS IS'' AND ANY
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by jlovejoy** [comment]
This is very close to Inner-Net-2.0 but adds back the 4th clause with advertising requirement and omits the last sentence.  

This had been on the "good" Fedora list, but we did not submit it previously b/c it wasn't clear the license still existed. 

I'm in favor of adding. As for name, I could go either way with `radvd` as per the old Fedora shortname or something along the lines of `Inner-Net-advertising` if we want to associate with the similar license

**Comment by swinslow** [comment]
Helpful context also at: https://fedoraproject.org/wiki/Licensing/Inner_Net_License

+1 to add, and I'd probably also go with `radvd` as ID and "radvd License" as name, rather than linking it to `Inner-Net`. Particularly since it sounds like radvd was the "senior" license which `Inner-Net-2.0` was essentially modifying.

**Comment by swinslow** [comment]
Discussed on 2023-10-26 legal team call. Probably doesn't make sense to reference `Inner-Net-2.0` since radvd was senior to it. Noted that radvd differs in at least some ways from BSD-4-Clause (noting additional clauses 0 and 1 at the start).

Want to do redlines comparing radvd and Inner-Net-2.0 to confirm otherwise identical. Also want to check and make sure differences between other BSD advertising licenses and radvd are noted. Will re-discuss naming / ID after those differences are clarified and confirmed.

**Comment by jlovejoy** [comment]
> This is very close to Inner-Net-2.0 but adds back the 4th clause with advertising requirement and omits the last sentence.

@swinslow - see above re: comparing Inner-Net-2.0
Given that, sounds like the decision was to add and use `ravd` for name?

**Comment by jlovejoy** [comment]
discussed on 11/9 call: go with `radvd`

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

radvd License

## License ID

radvd

## XML markup

none

## Notes:

This license is almost a match to Inner-Net-2.0, but it includes clause 4 which Inner-Net-2.0 omits.



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
