### ISSUE TITLE
New license request: g10-permissive (or FSFULLRWD markup change)

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2208]
### How license meets inclusion principles

This license was found during Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/381#note_1604577908 It is used in gcr package.
Debian calls it g10-permissive it is pretty close to https://spdx.org/licenses/FSFULLRWD.html 
Not sure if this justify as a new license or I should prepare PR with markup change for FSFULLRWD to allow this license too.

### License Name

g10-permissive

### Suggested short identifier

g10-permissive

### License or Exception?

None

### URL to license text

https://github.com/GNOME/gcr/blob/master/gck/pkcs11-trust-assertions.h

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/GNOME/gcr/

### paste text of license here

This file is free software; as a special exception the author gives
unlimited permission to copy and/or distribute it, with or without
modifications, as long as this notice is preserved.
This file is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY, to the extent permitted by law; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.

**Comment by richardfontana** [comment]
@jlovejoy My theory is this represents someone generalizing their experience of FSF/GNU *GPL exceptions, so that "special exception" to them came to mean "something different from the normal license that applies by default to this code". It looks strange to us because we're so familiar with the "special exception" language used in GNU exceptions.

BTW the "special exception" phrase is also used in a non-GPL-exception sort of sense in the text of the GPLv2 (the license text that corresponds to what SPDX calls `GPL-2.0-only` and `GPL-2.0-or-later` :) system library exception:

> However, as a special exception, the source code distributed need not include anything that is normally distributed (in either source or binary form) with the major components (compiler, kernel, and so on) of the operating system on which the executable runs, unless that component itself accompanies the executable.

**Comment by bsdimp** [comment]
I read it the same as Richard. Maybe with a bit of a twist. If one views the normal case of no copy without a signed contract allowing it... as an exception to that, you can do the following... it's really an awkward turn of phrase and I'm assuming I know what's normal that they are granting this favor..  but this all is speculation.

But if I read it quickly, I see a permissive MIT/0BSD/ISC like license. I just don't know how to interpret this phrase either. Is there some nefarious legal theory under which it could be used as a gotcha? I don't know.

**Comment by jlovejoy** [comment]
for reference:
<img width="652" alt="image" src="https://github.com/spdx/license-list-XML/assets/5048659/78e55828-be9a-4362-8cae-b0d06acda0d5">

**Comment by jlovejoy** [comment]
so, I think @richardfontana and @bsdimp are saying that the addition of "as a special exception" is not substantively different and we could make this optional

The leaves the difference of "author" v. "the Free Software Foundation" - which now that I look at it again, probably can be treated as usual for names.

file v. make.in is sort of already dealt with

and program v. fil in the last part seems also fine to make replaceable.

which would mean all of this can be handled with additional markup - agree?

**Comment by jlovejoy** [comment]
discussed on 11/9 call - agreed to use markup to accommodate this
