### ISSUE TITLE
New license request: gnome [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2209]
**1.** License Name: Old Gnome License
**2.** Short identifier: gnome
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in gcr package. It was discovered during the Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/380
**5.** License Request Url: http://tools.spdx.org/app/license_requests/310
**6.** URL(s): https://github.com/GNOME/gcr/blob/master/docs/COPYING
**7.** OSI Status: 0
**8.** Example Projects: https://github.com/GNOME/gcr/

**Comment by xsuchy** [comment]
Text of the license:

This work may be reproduced and distributed in whole or in part, in any medium, physical or electronic, so as long as this copyright notice remains intact and unchanged on all copies. Commercial redistribution is permitted and encouraged, but you may not redistribute, in whole or in part, under terms more restrictive than those under which you received it. If you redistribute a modified or translated version of this work, you must also make the source code to the modified or translated version available in electronic form without charge. However, mere aggregation as part of a larger work shall not count as a modification for this purpose.
All code examples in this work are placed into the public domain, and may be used, modified and redistributed without restriction.
BECAUSE THIS WORK IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY FOR THE WORK, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE WORK "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. SHOULD THE WORK PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY REPAIR OR CORRECTION.
IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR REDISTRIBUTE THE WORK AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE WORK, EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

**Comment by jlovejoy** [comment]
+1 to add. As for name, would it make sense to call it `GCR License` and `GCR` for the id?

**Comment by InSwiss** [comment]
This license (exact same text) is in our KB with name 'Gnome Glib Documentation License' and not sure how the name came to be but it is being used with that name for our reports.

**Comment by jlovejoy** [comment]
interesting on full name @InSwiss - I'm not seeing how it is a documentation license or a relationship with glib? maybe it's used elsewhere?

Perhaps:
full name: Gnome GCR License
and `GCR` for the id

**Comment by jlovejoy** [comment]
discussed on 11/9 call: go with `GCR-docs` as id and "Gnome GCR Documentation License"

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Gnome GCR Documentation License

## License ID

GCR-docs

## XML markup

none

## Notes:

This license is almost a match to Inner-Net-2.0, but it includes clause 4 which Inner-Net-2.0 omits.



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
