### ISSUE TITLE
New License: SAX-PD-2.0

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#2211]
We have had [SAX-PD](https://spdx.org/licenses/SAX-PD.html) on the SPDX License List for some time, as it is captured here: http://www.saxproject.org/copying.html

However, in the Fedora review, an example of just the 2.0 part of the above was found. See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/316 for more info.

Example: xml-commons-apis
Link to full source download: https://src.fedoraproject.org/lookaside/pkgs/xml-commons-apis/xml-commons-external-1.4.01-src.tar.gz/sha512/de7eb480f42915a7875c4ac6046e05df0d34039818c81c0ce80970113d72e37b42162e535a676b0ab283016837fca124414431b0a633daa22bb4d55b3da87cef/xml-commons-external-1.4.01-src.tar.gz

Should we consider whether the different components on the webpage should be individual licenses?

**Comment by richardfontana** [comment]
It looks to me like SPDX made a mistake in treating the SAX website license page as though it were a single license (or in assuming that that was a single license text to add to the license list).

**Comment by richardfontana** [comment]
I attempted to do some digging in the SAX source code.

As far as I can tell, the most recent release was SAX 2.0.2 in 2004. This has a COPYING file that says in full:

```
SAX IS FREE
-----------

I hereby abandon any property rights to SAX 2.0 (the Simple API for
XML), and release all of the SAX 2.0 source code, compiled code, and
documentation contained in this distribution into the Public Domain.
SAX comes with NO WARRANTY or guarantee of fitness for any purpose.


David Megginson
david@megginson.com
2000-05-05
```

This seems to be identical to the text in the Fedora package of xml-commons-apis except for typographical issues in the heading.

It seems an identical COPYING file was in the initial release of SAX 2.0 in 2001.

The SAX 1.0 release (2001) has this as the contents of the COPYING file:
```
Version 1.0 of the Simple API for XML (SAX), created collectively by
the membership of the XML-DEV mailing list, is hereby released into
the public domain.

No one owns SAX: you may use it freely in both commercial and
non-commercial applications, bundle it with your software
distribution, include it on a CD-ROM, list the source code in a book,
mirror the documentation at your own web site, or use it in any other
way you see fit.


			     NO WARRANTY

Because SAX is released to the public domain, there is no warranty for
the design or for the software implementation, to the extent permitted
by applicable law.  Except when otherwise stated in writing the
copyright holders and/or other parties provide SAX "as is" without
warranty of any kind, either expressed or implied, including, but not
limited to, the implied warranties of merchantability and fitness for
a particular purpose.  The entire risk as to the quality and
performance of SAX is with you.  Should SAX prove defective, you
assume the cost of all necessary servicing, repair or correction.

In no event unless required by applicable law or agreed to in writing
will any copyright holder, or any other party who may modify and/or
redistribute SAX, be liable to you for damages, including any general,
special, incidental or consequential damages arising out of the use or
inability to use SAX (including but not limited to loss of data or
data being rendered inaccurate or losses sustained by you or third
parties or a failure of the SAX to operate with any other programs),
even if such holder or other party has been advised of the possibility
of such damages.


David Megginson <sax@megginson.com>
1998-05-11
```

**Comment by jlovejoy** [comment]
so, it does seem that these are two different licenses and the HTML page just captures both.

I'm surprised no one caught this before

**Comment by jlovejoy** [comment]
labeling for discussion on call as this would mean changing an existing SPDX License entry, which is not something we do lightly. off top of head, if we did break this into the two variants, it might be wise to deprecate the existing ID and then add these as SAX-PD-1.0 and SAX-PD-2.0 since there area actually version numbers.

**Comment by jlovejoy** [comment]
discussed on 11/9 call: add 2.0 part as found in Fedora example as `SAX-PD-2.0` for identifier and leave existing id and add note that it has both

**Comment by BrianInglis** [comment]
As this is licence for SAX 2.0 should this not be labelled SAX-2.0-PD instead of SAX-PD-2.0?

**Comment by jlovejoy** [comment]
> As this is licence for SAX 2.0 should this not be labelled SAX-2.0-PD instead of SAX-PD-2.0?

well, we were trying to use the same identifier and then put the version number at the end - it seems that 2.0 represents both the version of the software and the license/dedication (unusual that they correspond!)

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

Sax Public Domain Notice 2.0

## License ID

SAX-PD-2.0

## XML markup

_describe any markup for replaceable or omitable text needed in the XML for the license_

## Notes:

This is the public domain dedication marked as 2.0 from the Sax copying.html page, which applies to version 2.0 of Sax.



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
