### ISSUE TITLE
license matching advice

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#2212]
I created a new doc, as discussed on the last SPDX-legal call, which I've gone ahead and merged to make it easier to review and iterate.

Please have a look at https://github.com/spdx/license-list-XML/blob/main/DOCS/license-match.md

and add comments here for any improvements or additions (or just make another PR!)

A couple considerations/questions:

- add link to separate file with easier view of BSD-3-Clause markup? 
- if so, should that be in same file or separate?
- more on HPND variants? I have a whole Google doc with notes on variations and display of text formatted to make it easier to see matches or not

**Comment by Pizza-Ria** [comment]
LMK if you want me to edit directly to clean up some typographical nits - tried to fork but having trouble finding the doc in my fork.  Also, a screenshot showing the dropdown would be helpful here too.

https://github.com/spdx/license-list-XML/blob/main/DOCS/license-match.md#historical-permission-and-notice-disclaimer-hpnd - maybe add a codebock with a snippet of the template to demonstrate the issue?

https://github.com/spdx/license-list-XML/blob/main/DOCS/license-match.md#bsd-3-clause - "THIS FILE" needs to be hyperlinked.

**Comment by jlovejoy** [comment]
@Pizza-Ria - not entirely sure what you mean by "a codeback with a snippet of the template" - but I was still contemplating a link to a separate document with all my notes..
at least I should add a link to the XML file for HPND!

As for the BSD-3-Clause "THIS FILE" - yeah, I don't have the link/file yet. I'd rather not link to a Google doc, but need to figure out how to make the visuals I'd like in markdown... stay tuned!

**Comment by jlovejoy** [comment]
closing this as complete, as I added more info to the doc as per list above
