### ISSUE TITLE
New license request: FSFAP-no-warranty-disclaimer

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2214]
**1.** License Name: None
**2.** Short identifier: FSFAP-no-wd
**3.** License Author or steward: Unknown
**4.** Comments: This license is identical to FSFAP except it omits the no-warranty sentence at the end.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/313
**6.** URL(s):  https://git.savannah.gnu.org/cgit/wget.git/tree/util/trunc.c?h=v1.21.3&id=40747a11e44ced5a8ac628a41f879ced3e2ebce9#n6
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://www.gnu.org/software/wget/

**Comment by jlovejoy** [comment]
license text for convenience:
``Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.
``
"This file is offered as-is, without any warranty." is included in FSFAP but not here.

sigh - this probably should be a separate license in this case

**Comment by jlovejoy** [comment]
was this also found in Fedora?

**Comment by richardfontana** [comment]
Yes, this is in Fedora in at least one package (`wget`).

**Comment by richardfontana** [comment]
Note, I originally wanted to suggest the identifier `FSFAP-no-warranty-disclaimer` but the online license submission tool limits suggested short identifiers to 25 characters apparently (see: https://github.com/spdx/spdx-online-tools/issues/512)

**Comment by InSwiss** [comment]
The name of the new license can be FSF All Permissive License (without Warranty).

**Comment by jlovejoy** [comment]
how about `FSFAP-no-disclaimer` for the id? @richardfontana 

interesting about the submission tool limit on characters - maybe not a bad thing to alert us to potentially too-long ids!

**Comment by jlovejoy** [comment]
discussed on 11/9 call - go with Richard's suggestion outside of tool limitation
