### ISSUE TITLE
Confirm and mark ICU as OSI-approved

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#2215]
Per https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-October/005431.html, the ICU license has now been approved by OSI.

Let's make sure that the license with the [ICU](https://spdx.org/licenses/ICU.html) identifier on the SPDX License List is the same one that was approved!

And then, the XML file for ICU should be updated to mark it as OSI approved.

This is a good first issue for new or recently-new contributors  :)

**Comment by richardfontana** [comment]
Oh, I just submitted https://github.com/spdx/license-list-XML/pull/2217
I have confirmed that the text on the OSI site matches the SPDX identifier template.
