### ISSUE TITLE
License for license / for repo

### ISSUE THREAD

**Issue by Maniues** [spdx/license-list-XML#2216]
Hello,
I have a question about how the SPDX license list works from a legal point of view.
Aren't the license texts covered by copyright? While some licenses e.g. GNU GPL clearly indicate user rights, MIT, BSD or Microsoft licenses do not.

Do you get permission, take advantage of exceptions in copyright law, or what? How it's working?

Finally - what license is this repository under? All source codes, XML files, etc. (yes, in some files there are a cc0 headers, but what about files without license header)?

**Comment by richardfontana** [comment]
See:
https://github.com/spdx/license-list-XML/issues/1044  
https://github.com/spdx/license-list-XML/issues/986

**Comment by jlovejoy** [comment]
generally speaking, lawyers do not consider legal texts like agreements, contracts, and licenses to be copyrightable. That would be impractical for the efficient practice of law and a detriment to clear drafting. However, some people seem to think their legal agreements should have a copyright notice on them... (which doesn't mean they should)

In any case, the answer is that you will not see a license of the license in this repo. That serves no purpose whatsoever.

However, any code does (or should, as I believe we checked this some time ago when someone raised this before) have a license notice in the file.
