### ISSUE TITLE
Revise FSFAP.xml to accommodate variant warranty disclaimer language

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2220]
`FSFAP` has this final sentence:
```
This file is offered as-is, without any warranty.
```

I found a variant that instead has this final sentence:
```
This file is offered as-is,
without warranty of any kind.
```
You can see this variant here:
https://git.savannah.gnu.org/cgit/automake.git/tree/INSTALL#n4

**Comment by jlovejoy** [comment]
@swinslow - we don't really have a protocol on review for markup (we might need to articulate that...) but this seems like a no-brainer to me and @richardfontana has already made the PR!  Agree?
