### ISSUE TITLE
New license request: LPD-document [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2223]
**1.** License Name: ScanCode calls it "Peter Deutsch Document License"
**2.** Short identifier: LPD-document
**3.** License Author or steward: L. Peter Deutsch, possibly
**4.** Comments: This is a license that seems to have originally appeared in RFCs in the 1990s. It should be understood as granting permissions for text documents comparable in scope to FOSS licenses. A minor variant of this license (adding one sentence that does not narrow its permissions) has been found covering files in one Fedora Linux package. Since this is likely the original version, I want to submit this one first.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/314
**6.** URL(s): https://scancode-licensedb.aboutcode.org/peter-deutsch-document.html, https://www.ietf.org/rfc/rfc1952.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://www.ietf.org/rfc/rfc1952.txt (not a project, I know)

**Comment by jlovejoy** [comment]
@richardfontana - to make sure I understand, this license has NOT been found in Fedora but sounds like you are submitting due to legacy in terms of having ben used prior?

**Comment by swinslow** [comment]
Discussed on legal team call 2024-01-11, consensus to treat this as equivalent to https://github.com/spdx/license-list-XML/issues/2224 with the final sentence from that one being optional.

ID: LPD-document

Name: LPD Documentation License
