### ISSUE TITLE
ICU is now OSI-approved

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#2226]
@goneall - do I need to update the XML file for ICU on this or are we somehow pulling this data in an automated way now? I can't remember, but I know it was discussed.

Also, the OSI added the URL of `https://opensource.org/license/icu-license/` instead of just having the SPDX id in the URL, which was decided and has been done since 2011 - is there a reason for this change?
see http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2023-October/005432.html

@webmink @nickvidal for awareness

**Comment by swinslow** [comment]
@jlovejoy FYI we updated the XML file already, over the weekend -- see #2215 and #2217  :)

Not sure about the URL update per your second comment, so we can see whether that warrants updates too...

**Comment by smaffulli** [comment]
There isn't yet an automated way to pull the list of licenses automatically, sorry. Glad to see that the XML file has been fixed anyway.

**Comment by xsuchy** [comment]
I propose to close this one.
