### ISSUE TITLE
New license request: HPND with MIT disclaimer [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jplesnik** [spdx/license-list-XML#2228]
**1.** License Name: MIT or HPND variant
**2.** Short identifier: None
**3.** License Author or steward: Unknown
**4.** Comments: I found the license below during the review of license for package perl-Net-DNS-SEC.  In Makefile.PL, it is marked as MIT, but it is different.

Here is the Fedora license review, in which it was approved for Fedora: 
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/397
**5.** License Request Url: http://tools.spdx.org/app/license_requests/317
**6.** URL(s): https://metacpan.org/release/NLNETLABS/Net-DNS-SEC-1.22/source/LICENSE
**7.** OSI Status: 0
**8.** Example Projects: https://metacpan.org/dist/Net-DNS-SEC

**Comment by jlovejoy** [comment]
This is pretty much `HPND-sell-variant-MIT-disclaimer` but without the sell option. Maybe just add as `HPND-MIT-disclaimer`?

**Comment by InSwiss** [comment]
+1 agree to be added as 'HPND with MIT disclaimer'

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Historical Permission Notice and Disclaimer with MIT disclaimer
## License ID
HPND-MIT-disclaimer
## XML markup
none
## Notes:
This is essentially HPND with the disclaimer from MIT license.
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
