### ISSUE TITLE
Markup for HPND (was: New license request: SMLNJ-PH [SPDX-Online-Tools])

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2238]
**1.** License Name: none
**2.** Short identifier: SMLNJ-PH
**3.** License Author or steward: Prentice Hall?
**4.** Comments: This is a legacy FOSS license that resembles `SMLNJ` but omits the anti-publicity clause. It was found in the Xaw3d library, packaged in Fedora and other Linux distributions.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/319
**6.** URL(s): https://gitlab.freedesktop.org/xorg/lib/libxaw3d/-/blob/master/include/X11/Xaw3d/Tree.h?ref_type=heads#L26-39
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://gitlab.freedesktop.org/xorg/lib/libxaw3d

**Comment by swinslow** [comment]
From a quick look, it looks like this is generally a match to HPND (taking into account its optional bits) with a couple of caveats:
1. this omits "and its documentation" in the first line
2. plurals in a few spots for the warranty, e.g. "disclaim" vs. "disclaims"
3. misspelling of "consequential" as "cosequential"

For 2 and 3, I think these are easily captured as non-substantive via markup.

For 1, I note that for other licenses (such as [MIT](https://spdx.org/licenses/MIT.html)) we've previously made markup edits permitting replaceable text for parts of licenses that describe the thing that is being licensed. (E.g. for [MIT](https://github.com/spdx/license-list-XML/blob/12e0bf432364074ca032a700e088620453966944/src/MIT.xml#L16) we match to either "this software and associated documentation files" or "this source file".) I'd lean towards permitting markup in HPND to handle this the same way.

**Comment by jlovejoy** [comment]
agree with @swinslow - this all seems fine to accommodate with markup, especially given the original intent and history of HPND.
This moves this from a new license request to XML markup, and use of HPND for the identifier in the Fedora issue
