### ISSUE TITLE
 Incorrect License Web Page Links for python-ldap

### ISSUE THREAD

**Issue by droideck** [spdx/license-list-XML#2256]
Hello,
I am one of the `python-ldap` mainteiners.
I've noticed that the license links for python-ldap in the SPDX License List XML are completely incorrect and they point to the wrong location.

They need to be updated and should point to the python-ldap project license. 
https://github.com/python-ldap/python-ldap/blob/main/LICENCE

`hplip` project is not the origin of python-ldap license.

Thank you.

**Comment by jlovejoy** [comment]
thanks @droideck - we generally don't remove old links, but add updated, new, or additional links, as per the 4th bullet in section C here: https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md

@goneall - do you have any further thoughts on this example?

**Comment by droideck** [comment]
> thanks @droideck - we generally don't remove old links, but add updated, new, or additional links, as per the 4th bullet in section C here: https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md

But the python-ldap license is a newly created one - https://github.com/spdx/license-list-XML/pull/2188

The problem is that it was initially created with the wrong links, which have no connection to the original license (which is of python-ldap). As a python-ldap mainteiner, I see that the existing links are misleading and can produce a legal issue which I'd like to avoid.

I think it will be more correct to remove old false links (which were mistakenly put there) - and set the correct one.

**Comment by jlovejoy** [comment]
ah, I didn't realize this was a new addition to the license list in any case, so these aren't "old" at all, they represent other places this same license is found. I think that's fine then
