### ISSUE TITLE
Apache-1.0 template does not match official text

### ISSUE THREAD

**Issue by sdheh** [spdx/license-list-XML#2259]
The Apache-1.0 xml template does not match https://www.apache.org/licenses/LICENSE-1.0 (see https://github.com/spdx/Spdx-Java-Library/issues/184#issuecomment-1828312068).
In bullet 5:
Template: appear in their **name**, without prior written
Official text: appear in their **names** without prior written

**Comment by jlovejoy** [comment]
good catch, @sdheh - can you prepare a PR to update this in both the XML and test TXT files?

**Comment by sdheh** [comment]
Maybe it's better if someone else does it because I need to get approval from my employer, which seems like it will take a while.
