### ISSUE TITLE
New license request: MIT-veillard-variant [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2260]
**1.** License Name: MIT Veillard Variant
**2.** Short identifier: MIT-veillard-variant
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in libxml2 package and was found during the Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/411
**5.** License Request Url: http://tools.spdx.org/app/license_requests/321
**6.** URL(s): https://raw.githubusercontent.com/GNOME/libxml2/4c2e7c651f6c2f0d1a74f350cbda95f7df3e7017/hash.c, https://github.com/GNOME/libxml2/blob/master/dict.c
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/GNOME/libxml2/

**Comment by xsuchy** [comment]
Text of the license:
Copyright (C) 2003-2012 Daniel Veillard.
 
  Permission to use, copy, modify, and distribute this software for any
  purpose with or without fee is hereby granted, provided that the above
  copyright notice and this permission notice appear in all copies.
 
  THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR IMPLIED
  WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE AUTHORS AND
  CONTRIBUTORS ACCEPT NO RESPONSIBILITY IN ANY CONCEIVABLE MANNER.

**Comment by xsuchy** [comment]
It is known to scancode https://scancode-licensedb.aboutcode.org/mit-veillard-variant Their note:
>  this is similar to the mit-taylor-variant but uses a different warranty disclaimer. This is found in the original versions of https://en.wikipedia.org/wiki/Libxml2

And the text is close to ISC.

**Comment by jlovejoy** [comment]
this is the same grant as https://spdx.org/licenses/ISC.html but a different disclaimer paragraph.

+1 to add but I'm not sure we should use MIT in the name or id b/c it's closer to ISC than to MIT??

**Comment by richardfontana** [comment]
I think `ISC-Veillard-variant` would be better than `MIT-Veillard-variant`, all else being equal.

**Comment by jlovejoy** [comment]
> I think `ISC-Veillard-variant` would be better than `MIT-Veillard-variant`, all else being equal.

agreed. not sure we really need "variant" even - @swinslow - want to weigh in or should we just go with `ISC-Veillard`?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

ISC Veillard variant

## License ID

ISC-Veillard

## XML markup

none

## Notes:

This license uses the same grant as ISC, but a different disclaimer paragraph.



## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
