### ISSUE TITLE
Apache-1.1 XML template does not match official license texts

### ISSUE THREAD

**Issue by sdheh** [spdx/license-list-XML#2270]
The Apache-1.1 XML template does not match the following texts:

- https://www.apache.org/licenses/LICENSE-1.1
- https://opensource.org/license/apache-1-1/

The mismatch is:
XML template: `please see http://www.apache.org/.`
Other texts: `please see <http://www.apache.org/>.`

**Comment by sdheh** [comment]
The title is different too for https://www.apache.org/licenses/LICENSE-1.1

The mismatch is:
XML template: `Apache License 1.1`
Other text: `The Apache Software License, Version 1.1`

**Comment by jlovejoy** [comment]
as per matching guideline B12 https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b12-license-name-or-title - title text is to be ignored for matching purposes as it is not part of the substantive license text. As such, we don't use alt tags within a `titleText` tag

I'm fine to update the title in the `titleText` tag to match to what is says at the Apache Software Foundation link, but it really shouldn't matter.

**Comment by jlovejoy** [comment]
looking at #2278 - I'm not sure what the goal is for the additional markup in the optional section at the end? @pmonks - is it to add the < > around the address?

**Comment by pmonks** [comment]
> is it to add the < > around the address?

@jlovejoy correct - that was one of the discrepancies @sdheh identified in the original description of this issue.

**Comment by jlovejoy** [comment]
ok... did a bit of research here. Long story short, the text should match to the canonical source of the license which is https://www.apache.org/licenses/LICENSE-1.1

I have now made a new PR (easier than editing @pmonks previous one) accordingly. See #2301  for more details
