### ISSUE TITLE
bzip2-1.0.6 variant with additional anti-endorsement clause

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2271]
valgrind and possibly some other projects have some source files with the following license (example: https://sourceware.org/cgit/valgrind/tree/mpi/libmpiwrap.c):
```
Copyright (C) 2006-2017 OpenWorks LLP.  All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions
   are met:

   1. Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.

   2. The origin of this software must not be misrepresented; you must
      not claim that you wrote the original software.  If you use this
      software in a product, an acknowledgment in the product
      documentation would be appreciated but is not required.

   3. Altered source versions must be plainly marked as such, and must
      not be misrepresented as being the original software.

   4. The name of the author may not be used to endorse or promote
      products derived from this software without specific prior written
      permission.

   THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
   OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
   WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
   ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
   DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
   DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
   GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
   WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
   NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
   SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

   Neither the names of the U.S. Department of Energy nor the
   University of California nor the names of its contributors may be
   used to endorse or promote products derived from this software
   without prior written permission.
```

I believe this matches `bzip2-1.0.6` but for the addition of the final paragraph adding the anti-endorsement language. Should this be treated as a match to `bzip2-1.0.6` given that there is similar BSD-vintage anti-endorsement language in clause 4? Or should it be treated as a substantively different license?

Fedora issue: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/422

**Comment by jlovejoy** [comment]
hmmm... it does seem silly to have this as a separate license b/c the additional paragraph really just mimics clause 4 with a couple specific names. We could add that as optional, but then it'd show up in the bzip-1.0.6 template and not sure if that's helpful

what are people's thoughts?

**Comment by richardfontana** [comment]
I've seen a few times now that SPDX-legal considers the effect of these kinds of decisions on the resultant appearance of autogenerated HTML versions of license templates at https://spdx.org/licenses/ and I just want to say that that seems problematic. :) The problem is in how SPDX chooses to display templates which I think ought to be overhauled (somewhat relatedly: https://github.com/spdx/LicenseListPublisher/issues/135).

**Comment by goneall** [comment]
> The problem is in how SPDX chooses to display templates which I think ought to be overhauled (somewhat relatedly: https://github.com/spdx/LicenseListPublisher/issues/135).

@richardfontana I'm actually working on an update to the license template generation this week.  What would really help is a consensus on what changes are needed and a precise description of how we would like the templates to be rendered.  I noticed a few good ideas in the issue thread but not a consensus from the legal team.  See [this issue comment](https://github.com/spdx/LicenseListPublisher/issues/165#issuecomment-1863487150) for a draft update to the templates based on another related issue.

Also note that the LicenseListPublisher is open source and contributions are welcome.  I'm sure there are people in the legal team better than myself at UI design and HTML - however, no one volunteered to address the 2 issues related to template generation - so I decided to attempt a fix.  If anyone is interested in helping, I can give you a quick tour of where the templates are and how it is rendered.

**Comment by jlovejoy** [comment]
I'm revising my thoughts on this one: clause 4 and the additional paragraph are the same restriction in that the substantive text is the same: 
Clause 4 states: `The name of the author may not be used to endorse or promote products derived from this software without specific prior written`

Where the extra paragraph replace the "name of the author" with the actual names of the authors (and thus revised the grammar) `Neither the names of the U.S. Department of Energy nor the University of California nor the names of its contributors may be used to endorse or promote products derived from this software without prior written permission.`

It seems like maybe that extra paragraph was reiterating the restriction in clause 4 by repeating it and adding the specific names. It certainly isn't adding a new term. Perhaps we don't need to accommodate this at all??

**Comment by richardfontana** [comment]
Just checking, I know this has come up with other licenses (but forget how it was dealt with): the presence or absence of "specific" before "prior written permission" is not considered a substantive difference?

**Comment by richardfontana** [comment]
Does it matter that we don't know if the U.S. Department of Energy, the
University of California (and 'contributors') are instances of "the author"? 

I wonder also if what happened here was that the language at the end is the relic of some earlier software this is based on, using a slightly different (probably BSD-family) license, and this was OpenWorks' flawed way of complying with the apparently non-recorded earlier license?

**Comment by jlovejoy** [comment]
> Just checking, I know this has come up with other licenses (but forget how it was dealt with): the presence or absence of "specific" before "prior written permission" is not considered a substantive difference?

off top of head, I think we have considered this non-substantive

**Comment by jlovejoy** [comment]
@swinslow - can you make the PR for this one?

**Comment by swinslow** [comment]
Yup, will do!
