### ISSUE TITLE
New license request: Tony Sanders license 

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2272]
### How license meets inclusion principles

It was accepted by Fedora:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/424

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

Unfortunately, there is no URL

### OSI Status

I don't know

### License author or steward

Tony Sanders

### URL to project(s) that use license

https://sendmail.org/

### paste text of license here

contrib/mailprio:
```
# Copyright 1994, 1996, Tony Sanders <sanders@earth.com>
# Rights are hereby granted to download, use, modify, sell, copy, and
# redistribute this software so long as the original copyright notice
# and this list of conditions remain intact and modified versions are
# noted as such.
#
# I would also very much appreciate it if you could send me a copy of
# any changes you make so I can possibly integrate them into my version.
```

**Comment by jlovejoy** [comment]
download with license at https://ftp.sendmail.org/sendmail.8.17.2.tar.gz
In sendmail/sendmail-8.17.2/contrib/mailprio

**Comment by jlovejoy** [comment]
Given this is used in a pretty popular package (Sendmail) and not like anything on the SPDX License List in terms of wording, I'm +1 to add

As to name, would it make sense to use:
`mailprio` for the id and `mailprio License` for the fullname?

**Comment by richardfontana** [comment]
I think `mailprio` is better here. Where an old license seems to originate with a particular known person *and* a particular known project or package, I think it is slightly better to base the identifier on the latter.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name

mailprio License

## License ID

mailprio

## XML markup

none

## Notes:

none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
