### ISSUE TITLE
New license request: ssleay-windows [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2275]
**1.** License Name: Original SSLeay License with Windows Clause
**2.** Short identifier: ssleay-windows
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in libgit2 package and has been discovered during License review in Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/425
This license is already recognized by scancode-toolkit https://scancode-licensedb.aboutcode.org/ssleay-windows
**5.** License Request Url: http://tools.spdx.org/app/license_requests/323
**6.** URL(s): https://github.com/libgit2/libgit2/blob/main/COPYING#L1030C1-L1086C36
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/libgit2/libgit2/

**Comment by xsuchy** [comment]
Text of the license:

Portions of the OpenSSL headers are included under the OpenSSL license:
Copyright (C) 1995-1998 Eric Young (eay@cryptsoft.com) All rights reserved.
This package is an SSL implementation written by Eric Young (eay@cryptsoft.com). The implementation was written so as to conform with Netscapes SSL.
This library is free for commercial and non-commercial use as long as the following conditions are aheared to. The following conditions apply to all code found in this distribution, be it the RC4, RSA, lhash, DES, etc., code; not just the SSL code. The SSL documentation included with this distribution is covered by the same copyright terms except that the holder is Tim Hudson (tjh@cryptsoft.com).
Copyright remains Eric Young's, and as such any Copyright notices in the code are not to be removed. If this package is used in a product, Eric Young should be given attribution as the author of the parts of the library used. This can be in the form of a textual message at program startup or in documentation (online or textual) provided with the package.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:


        
      Redistributions of source code must retain the copyright notice, this list of conditions and the following disclaimer.

        
      Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        
      All advertising materials mentioning features or use of this software must display the following acknowledgement: "This product includes cryptographic software written by Eric Young (eay@cryptsoft.com)" The word 'cryptographic' can be left out if the rouines from the library being used are not cryptographic related :-).

        
      If you include any Windows specific code (or a derivative thereof) from the apps directory (application code) you must include an acknowledgement: "This product includes software written by Tim Hudson (tjh@cryptsoft.com)"

THIS SOFTWARE IS PROVIDED BY ERIC YOUNG ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The licence and distribution terms for any publically available version or derivative of this code cannot be changed. i.e. this code cannot simply be copied and put under another distribution licence [including the GNU Public Licence.]

**Comment by xsuchy** [comment]
Note that Richard did some investigation: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/425#note_1698073865

**Comment by jlovejoy** [comment]
so... this is essentially the same as [`OpenSSL`](https://spdx.org/licenses/OpenSSL.html) which is a compound license (two licenses in one id - I'm pretty sure we labored over this decision way back when...) but with the order of the two parts reversed. 

I'd agree with @richardfontana  assessment in the Fedora Gitlab issue that "It's hard to see why the conjunction of the SSLeay license and the (first half of the) OpenSSL license, in that order, shouldn't be treated as equivalent to OpenSSL. But we should get SPDX to weigh in."
There is no substantive difference.

I'm not sure how we make the order reversible as that is not something our markup can accommodate.  We could of course add something in the Note, but that's not particularly helpful for scanning tools
@goneall @zvr @swinslow  - any thoughts on this?

**Comment by goneall** [comment]
I can't think of an easy way to make the order reversible without a very complicated and somewhat impractical regex.

**Comment by jlovejoy** [comment]
> I can't think of an easy way to make the order reversible without a very complicated and somewhat impractical regex.

thanks @goneall - that's what I figured. While not typical, do you think adding a Note as to allowing the reverse order would be helpful? Not tool readable, but it seems crazy to add another license for the same combo but in a different order.

Unless we broke them apart... sigh

**Comment by richardfontana** [comment]
I don't understand why you need a regex. Based on what I've seen and some common sense, I doubt most scanners even correctly implement the alt or optional tags in some of the license XML files, if they even attempt to do so. IMO the approach should not be trying to accommodate the primitive state of scanning tools, but to encourage the development of more sophisticated approaches to scanning. If there's a "note" in an XML file indicating that an alternative configuration of license texts is a match, a scanning tool should attempt to implement that. 

And SPDX gave some consideration to creating an umbrella identifier for "public domain". Wouldn't this require an XML file with a large set of alternative license texts? 

I guess Fedora could deal with this by not using `OpenSSL` and instead defining a new `LicenseRef-OpenSSL` which would encompass both SPDX `OpenSSL` as well as this variation.

**Comment by goneall** [comment]
> I don't understand why you need a regex.

The use of the license templates have been around for quite a few years and have used regexes to implement the license matching guidelines.  It is implemented in the SPDX Java tools command line and in the SPDX online tools.  There are also some users of the Java library that implement the matching guidelines in other tools (hence some of the template fixes recently submitted).  

Although agree there are quite a few scanners out there that do not implement or honor the license matching guidelines, IMO that doesn't mean we should only support the least common denominator of tool functionality.

The implication of not implementing this in the template is that this particular variant will not get matched using the license matching guidelines.  I don't know how popular this variant is - it may not be popular enough to create a practical issue.  In that case a note would be fine.

One other consideration is if this technically meets the [License Matching Guidelines](https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/) as there is no mention that the order of the paragraphs.

**Comment by zvr** [comment]
After thinking about this, maybe the easiest (and most future-proof) solution would be to consider that a license does not have a _single_ text but may have more than one associated with a short identifier.
Yes, it's a major change, but once decided it can be implemented pretty painlessly: change the XML schema, the model, add a loop while processing in the libs, etc.

**Comment by richardfontana** [comment]
@goneall Given that OpenSSL underwent a major license change to `Apache-2.0` in recent years, and also given what I think is a decline in certain practices involving copying of individual source files from project to project, it seems unlikely that this variant will be frequently encountered in the future even with the use of relatively sophisticated scanning tools. 

I think it used to be somewhat common (if disturbing) to see entire OpenSSL releases bundled in open source and proprietary codebases, but in those cases you'd encounter the 'standard' `OpenSSL` license  in the LICENSE file or whatever. Here what happened was a project used *one* source file from OpenSSL and copied over the license notices in that source file rather than the form in which the license appears in the LICENSE file. I'm guessing that is not a common scenario with respect to OpenSSL.

**Comment by goneall** [comment]
> After thinking about this, maybe the easiest (and most future-proof) solution would be to consider that a license does not have a single text but may have more than one associated with a short identifier.

Not a bad solution.  It would slow down the matching a bit, but it would solve this problem.  Due to the performance, I would strongly prefer using the `alt` and `optional` tags, but I'm OK updating the tools if we decide to go in this direction.

**Comment by zvr** [comment]
I didn't explain myself well, @goneall .  I propose we have the exact same setup we currently ave (with `alt` and `optional`, etc.), but we also allow, in extreme cases like this one, the possibility to have more than one template associated with a license.
For almost all cases there would not be a performance hit; only when nothing else works we will introduce a second template to be able to match texts significantly different than the first.

**Comment by jlovejoy** [comment]
ok, so there's a lot here and thanks for the comments!  
it sounds like, for the time being, we should add a note, which I've proposed here: https://github.com/spdx/license-list-XML/pull/2295

As for @zvr - I'm not entirely sure how that would work, or if we'd need that for more than this license (would that be a change proposal?)? But maybe we should move that idea to its own issue and discuss.

Also not sure if what @zvr is proposing and the public domain proposal I floated on the email list some time ago that @richardfontana referenced are the same?

**Comment by jlovejoy** [comment]
meant to add: just trying to move things along, as Fedora package maintainers are held-up on a number of SPDX issues, so going for the "path of least resistance" solution now. but can reconsider better options later?

**Comment by richardfontana** [comment]
> ok, so there's a lot here and thanks for the comments! it sounds like, for the time being, we should add a note, which I've proposed here: #2295
 
@jlovejoy This note is not sufficient because it doesn't account for the missing paragraph.

**Comment by jlovejoy** [comment]
good catch @richardfontana - not sure if this further breaks stuff, but I'm suggesting that can be optional as it's more informative and have added an optional tag to my PR

Of course, need other eyes on this... it's not an optimal solution, but maybe a good tie-over?
