### ISSUE TITLE
New license request: XZoom [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jopejoe1** [spdx/license-list-XML#2283]
**1.** License Name: XZoom
**2.** Short identifier: XZoom
**3.** License Author or steward: Unknown
**4.** Comments: Included in the .c file of XZoom which is packaged at Debian at https://packages.debian.org/sid/xzoom
**5.** License Request Url: http://tools.spdx.org/app/license_requests/325
**6.** URL(s): https://metadata.ftp-master.debian.org/changelogs//main/x/xzoom/xzoom_0.3-27_copyright
**7.** OSI Status: Unknown
**8.** Example Projects: https://packages.debian.org/sid/xzoom

**Comment by jopejoe1** [comment]
```
Copyright: 1995-2008 Itai Nahshon

   This program is distributed with no warranty.

   Source files for this program may be distributed freely.
   Modifications to this file are okay as long as:
    a. This copyright notice and comment are preserved and
     left at the top of the file.
    b. The man page is fixed to reflect the change.
    c. The author of this change adds his name and change
     description to the list of changes below.
   Executable files may be distributed with sources, or with
   exact location where the source code can be obtained.

```

**Comment by jlovejoy** [comment]
@jopejoe1 - is this used in a package in Debian, then? And therefore an approve license as per the DFSG?

**Comment by jopejoe1** [comment]
I'm not quite sure how the packaging on debain works but it has a package entery on the debain package site at https://packages.debian.org/sid/xzoom , i found it whiele cleaning up the generic free packages on nixos.

**Comment by jlovejoy** [comment]
Finally did a little research on this. Looks like xzoom is used in Debian (and Ubuntu). A search on some of the specific license text in Github shows it only showing up in this particular package. I don't see that it is packaged in Fedora, FWIW.

Given this +1 to add and I think we can use `xzoom` as the id

**Comment by copernicat** [comment]
+1 to add, for the reasons @jlovejoy expressed and the ID is unique

**Comment by swinslow** [comment]
+1 to add, and good with `xzoom` and ID / "XZoom License" as name

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
xzoom License
## License ID
xzoom
## XML markup
none
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
