### ISSUE TITLE
New license request: OTF2

### ISSUE THREAD

**Issue by philiptaron** [spdx/license-list-XML#2284]
### How license meets inclusion principles

This is a variant of the BSD 3-clause license used by the [OTF2 sub-component of the Score-P project](https://www.vi-hps.org/projects/score-p).

### License Name

OTF2 License Agreement

### Suggested short identifier

OTF2

### License or Exception?

license

### URL to license text

https://fossies.org/linux/misc/scalasca-2.6.1.tar.gz/scalasca-2.6.1/vendor/otf2/COPYING?m=t

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://www.vi-hps.org/projects/score-p

> OTF2 - The Open Trace Format Version 2
>
> The Open Trace Format 2 is a highly scalable, memory efficient event trace data format plus support library. It is the standard trace format for Scalasca, Vampir, and Tau and is open for other tools.
>
> OTF2 is the common successor format for the [Open Trace Format (OTF)](https://www.tu-dresden.de/zih/otf/) and the Epilog trace format. It preserves the essential features as well as most record types of both and introduces new features such as support for multiple read/write substrates, in-place time stamp manipulation, and on-the-fly token translation. In particular, it will avoid copying during unification of parallel event streams.

There isn't a public repository for contributing to this project that I could find; it's just tarballs distributed on this site.

### paste text of license here

```
                         OTF2 LICENSE AGREEMENT
                         ======================

Copyright (c) 2009-2012, RWTH Aachen University, Germany
Copyright (c) 2009-2012, Gesellschaft fuer numerische Simulation mbH
                         Braunschweig, Germany
Copyright (c) 2009-2021, Technische Universitaet Dresden, Germany
Copyright (c) 2009-2012, University of Oregon, Eugene, USA
Copyright (c) 2009-2021, Forschungszentrum Juelich GmbH, Germany
Copyright (c) 2009-2014, German Research School for Simulation Sciences GmbH,
                         Juelich/Aachen, Germany
Copyright (c) 2009-2013, Technische Universitaet Muenchen, Germany

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.

* Neither the names of
   RWTH Aachen University,
   Gesellschaft fuer numerische Simulation mbH Braunschweig,
   Technische Universitaet Dresden,
   University of Oregon, Eugene,
   Forschungszentrum Juelich GmbH,
   German Research School for Simulation Sciences GmbH, or the
   Technische Universitaet Muenchen,
  nor the names of their contributors may be used to endorse or promote
  products derived from this software without specific prior written
  permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by richardfontana** [comment]
I think this can be accommodated by a markup revision to `BSD-3-Clause` - needs to allow a variant with "nor the names of their contributors".

**Comment by philiptaron** [comment]
@richardfontana Do you have an example that's similar? I'd love to accommodate this license with the existing license that's closest to it.

**Comment by richardfontana** [comment]
@philiptaron See: clause 3 of https://github.com/spdx/license-list-XML/blob/main/src/BSD-3-Clause.xml
```
<alt match="(The name of.+may not)|(Neither the names? of.+nor the names of its contributors may)|( Neither the name of.+nor the names of its authors and contributors may)|(Neither the name of.+nor the names of contributors may)|(Neither the name.+nor the names of contributors may)|(The names of its contributors may not)|(The names of any contributors may not)|(The names of the contributors may not)|(None of the names of.+and any contributors may)|(Neither my name .+ nor the names of contributors to this code may)" name="organizationClause3">
Neither the name of the copyright holder nor the names of its contributors may</alt>
be used to endorse or promote products derived from this
<alt match="software|work" name="software">software</alt> without specific prior written permission.
```
You could submit a pull request to modify the regular expression that would capture clause 3 in the OTF2 version. I think the only issue is the "their".

**Comment by jlovejoy** [comment]
@richardfontana is right and I've updated via https://github.com/spdx/license-list-XML/commit/d101de69d20798cf712162d29f09af4ff79c0cec

(b/c I spaced and merged to main branch instead of making a PR... bad me!)

In any case, we won't need the PR you made, so I'll close that, as this is not a new license. Will also update title of issue accordingly.

**Comment by philiptaron** [comment]
Thank you both!
