### ISSUE TITLE
New license request: Fenneberg/Livingston license

### ISSUE THREAD

**Issue by nmav** [spdx/license-list-XML#2286]
### How license meets inclusion principles

This is a license is included in Fedora software (radcli / freeradius-client) and was found during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/426

### License Name

Fenneberg/Livingston license

### Suggested short identifier

FLL

### License or Exception?

license

### URL to license text

https://github.com/FreeRADIUS/freeradius-client/blob/master/COPYRIGHT#L32

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/radcli/radcli/
https://github.com/FreeRADIUS/freeradius-client

### paste text of license here

Copyright 1992 Livingston Enterprises, Inc.
Livingston Enterprises, Inc. 6920 Koll Center Parkway Pleasanton, CA  94566

Permission to use, copy, modify, and distribute this software for any
purpose and without fee is hereby granted, provided that this copyright
and permission notice appear on all copies and supporting documentation,
the name of Livingston Enterprises, Inc. not be used in advertising or
publicity pertaining to distribution of the program without specific
prior permission, and notice be given in supporting documentation that
copying and distribution is by permission of Livingston Enterprises, Inc.

Livingston Enterprises, Inc. makes no representations about the suitability
of this software for any purpose.  It is provided "as is" without express
or implied warranty.

**Comment by jlovejoy** [comment]
this is similar to other HPND variants, but adds the obligation that "notice be given in supporting documentation that
copying and distribution is by permission of Livingston Enterprises, Inc."

this does not appear in any of the existing HPND variants.

+1 to add as a new license

**Comment by swinslow** [comment]
Also +1 to add as a new license, for the reasons @jlovejoy indicated.

@jlovejoy Are we trying to capture most HPND-related licenses with an "HPND-" prefix for the ID? If so, then I would go with the following to mirror the other HPND variants:

* ID: `HPND-Fenneberg-Livingston`
* Name: Historical Permission Notice and Disclaimer - Fenneberg-Livingston variant

**Comment by swinslow** [comment]
Before going with the ID / name I mentioned, see also the discussion in #2321 -- may want to use `HPND-PPP` instead

**Comment by swinslow** [comment]
See discussion [here](https://github.com/spdx/license-list-XML/issues/2321#issuecomment-1919424836), suggesting that `HPND-Fenneberg-Livingston` might in fact be preferred for ID.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Historical Permission Notice and Disclaimer - Fenneberg-Livingston variant
## License ID
HPND-Fenneberg-Livingston
## XML markup
for name
## Notes:
This is similar to HPND but add an obligation relating notice in supporting documentation.
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by jlovejoy** [comment]
@nmav - can you make the PR for this?
