### ISSUE TITLE
New license request: GMSH-GPL-EXCEPTION [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by manisandro** [spdx/license-list-XML#2289]
**1.** License Name: GPL-2.0-or-later WITH <gmsh GPL exception>
**2.** Short identifier: GMSH-GPL-EXCEPTION
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora, and this exception was found during license review, see https://gitlab.com/fedora/legal/fedora-license-data/-/issues/427
**5.** License Request Url: http://tools.spdx.org/app/license_requests/327
**6.** URL(s): https://gitlab.onelab.info/gmsh/gmsh/-/raw/master/LICENSE.txt
**7.** OSI Status: Unknown
**8.** Example Projects: https://gitlab.onelab.info/gmsh/gmsh

**Comment by xsuchy** [comment]
Text of the exception:

 The copyright holders of Gmsh give you permission to combine Gmsh
  with code included in the standard release of Netgen (from Joachim
  Sch"oberl), METIS (from George Karypis at the University of
  Minnesota), OpenCASCADE (from Open CASCADE S.A.S) and ParaView
  (from Kitware, Inc.) under their respective licenses. You may copy
  and distribute such a system following the terms of the GNU GPL for
  Gmsh and the licenses of the other code concerned, provided that
  you include the source code of that other code when and as the GNU
  GPL requires distribution of source code.

  Note that people who make modified versions of Gmsh are not
  obligated to grant this special exception for their modified
  versions; it is their choice whether to do so. The GNU General
  Public License gives permission to release a modified version
  without this exception; this exception also makes it possible to
  release a modified version which carries forward this exception.

**Comment by jlovejoy** [comment]
+1 to add as this is distinct from any exception we already have. I'd not include any markup for now.  Naming suggested seems ok?

**Comment by swinslow** [comment]
Also +1 to add. There are several exceptions (on the list and elsewhere in the wild) that use fragments of language from this one, but I don't see any that are matches or particularly close.

The project's preferred capitalization appears to be "Gmsh", so I'd suggest:

* ID: `Gmsh-exception`
* Name: Gmsh exception

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Gmsh exception
## License ID
Gmsh-exception
## XML markup
none at this time, we can add later if we find other variants
## Notes:
This exception has been used with GPL-2/0
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
