### ISSUE TITLE
Use of <copyrightText> in Fair.xml seems incorrect

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2290]
(edited to fix markdown!)

[Fair.xml](https://github.com/spdx/license-list-XML/blob/main/src/Fair.xml#L12-L14) uses the `<copyrightText>` element to wrap this heading in the license text: "&lt;Copyright Information&gt;"

This is not a copyright notice, however, and thus is (I assume) inappropriately wrapped in `<copyrightText>`. It is using "copyright" as a synonym for "conditions for exercising copying permissions"; I assume the `<copyrightText>` element is intended solely to contain copyright notices which are not considered when analyzing matching.

**Comment by bsdimp** [comment]
Elsewhere copyright information is just the copyright notice(s). Given the context here, I'm sure that was the original intent. Since this license is vert permissive, what else could possibly be there?

**Comment by richardfontana** [comment]
Basically, "copyright" here is a synonym for "license [terms]". This was a fairly common usage in Internet-based software development communities in the 1980s and 1990s but fell out of fashion sometime in the early 21st century as I think it came to be seen as unsophisticated or incorrect. 

So, much as <copyrightText> would be inappropriate to wrap a license heading like "License Information", it should be inappropriate for "Copyright Information" in *this* context. Obviously, a license that used "Copyright Information" as part of a subsection containing copyright notices would be appropriate for <copyrightText> but that isn't what we have here.

I think the creator of the Fair.xml file erred in assuming that the words "Copyright Information" (despite the absence of any copyright notice as such) *were* a kind of copyright notice and thus ought to be in <copyrightText> -- possibly because the creator of the file was not aware of this old jargony usage of "copyright".

**Comment by jlovejoy** [comment]
I looked back at web archive and I am confident that this was intended to be a placeholder for the copyright holder of the code and thus `<copyrightText>` tag is appropriate.

Can we close this issue?

**Comment by richardfontana** [comment]
Hmm I guess you may be right, though oddly the license-discuss link on the OSI page for Fair seems to be for a different license.
