### ISSUE TITLE
New license request: ANCAP [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jaazinn** [spdx/license-list-XML#2313]
**1.** License Name: Ancap License
**2.** Short identifier: ANCAP
**3.** License Author or steward: Jason Garland
**4.** Comments: This license permits everybody except government employees from using and copying the work.

Furthermore, it opts out of legal recourse for people that fail to copy the license or credit the author, while still making it a wish that the license be copied and credit be given.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/332
**6.** URL(s): https://github.com/Ancap-License/Ancap-License
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://size.cash

**Comment by richardfontana** [comment]
I don't think this should be seen as meeting the license inclusion principles. First, the exclusion of government employees makes it non-FOSS. Second, the "example project" provided is not a project but some sort of apparently new cryptocurrency-related web application. No evidence is given of the actual use of the license.

**Comment by jlovejoy** [comment]
@jaazinn - is this a new license as indicated by the age of the repo where the license text lives?

**Comment by jaazinn** [comment]
Yes, relatively new.

I understand the argument against it being FOSS. That being said,
developers who want to opt out of recourse through the state (wish or
intention vs. threat of violence via the state) and allow everyone to use
their code that subscribes to voluntarism, do not have a choice in open
source licenses at the moment.

Technology can be a force for good and a allowing code to "vote" gives
developers power.

Cheers,
Jason

**Comment by jlovejoy** [comment]
# New submission review

* **Has the license been approved by the OSI?** _All OSI-approved license will be included on the SPDX License List, regardless of other factors_
    - [ ] Yes
    - [ ] No

## Definitive Factors

_These must all be satisfied to allow inclusion in the license list_

1. **Is the submitted license unique, that is, it does not match another license already on the License List as per the [matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines)?**
    - [ ] Yes
    - [ ] No
1. **If a software license, does it apply to source code and not only to executables?**
    - [ ] Yes
    - [ ] No
1. **Does the license have identifiable and stable text, and is not in the midst of drafting?**
    - [ ] Yes
    - [ ] No
1. **Has the license steward, if any, committed to versioning new versions and to not modify it after addition to the list?**
    - [ ] Yes
    - [ ] No

## Other factors for inclusion

*Roughly in order of descending importance*

1. **Does the license substantially comply with one of the free/open content definitions? (examples include the [Open Source Definition](https://opensource.org/osd) and the [Debian Free Software Guidelines](https://www.debian.org/social_contract#guidelines))** (_Approval by the organisation that publishes the definition is not required_)
    - [ ] Yes
    - [ ] No
1. **Is the license structured to be generally usable by anyone, and not specific to one organisation or project?**
    - [ ] Yes
    - [ ] No
1. **Does the license have substantial use such that it is likely to be encountered (ie. use in many projects, or in one significant project)?** (_For recently written licenses, definitive plans for it to be used in at least one or a few significant projects may satisfy this_)
    - [ ] Yes
    - [ ] No
1. **Is the license primarily intended to facilitate the free distribution of content with limited restrictions?**
    - [ ] Yes
    - [ ] No
1. **Does the license steward support this submission, or is at least aware of and not in opposition of it?**
    - [ ] Yes
    - [ ] No

## Summary of factors, outcome, comments

_Comments on the totality of these "other factors" in light of the SPDX License List's overall goals and objectives_

**Comment by jaazinn** [comment]
I agree it doesn't fit with your "other factors"

While perhaps not a fit now, quite a lot of software is now being built outside of the traditional judicial system. 

It may be worth positioning SPDX to support the next wave of licenses that focus on author intent, opt out of traditional judicial systems, and even (in the case of this proposal) use the license to make a statement about free trade by limiting use to others who live by the same principles.

Self regulation also needs infrastructure, and intent-based licenses will be a big part of this.

**Comment by jlovejoy** [comment]
thanks for your thoughts @jaazinn - I think that SPDX will or already does support the next wave of licenses that are being used and found in the software supply chain, whatever that may be!
