### ISSUE TITLE
Link to MulanPSL-2.0 is not correct

### ISSUE THREAD

**Issue by peter-jerry-ye** [spdx/license-list-XML#2314]
The page of [MulanPSL-2.0](https://spdx.org/licenses/MulanPSL-2.0.html) says:

> Other web pages for this license
> https://license.coscl.org.cn/MulanPSL2/ [no longer live]

And the reason is that it has an extra trailing slash. The correct one should be:

<https://license.coscl.org.cn/MulanPSL2>

**Comment by jlovejoy** [comment]
Thanks @peter-jerry-ye - I made a PR to fix!
