### ISSUE TITLE
New license request: Gnome-example-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2318]
**1.** License Name: Example usage exception
**2.** Short identifier: example-usage-exception
**3.** License Author or steward: Unknown
**4.** Comments: This exception was found during License Review in Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/438 and is used in meld and gnome-devel-docs.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/334
**6.** URL(s): https://gitlab.gnome.org/Archive/gnome-devel-docs/-/blob/master/platform-demos/C/legal.xml?ref_type=heads, http://meldmerge.org/help/
**7.** OSI Status: Unknown
**8.** Example Projects: http://meldmerge.org/, https://developer.gnome.org/

**Comment by xsuchy** [comment]
Text of the exception:

As a special exception, the copyright holders give you permission to copy, modify, and distribute the example code contained in this document under the terms of your choosing, without restriction.

**Comment by xsuchy** [comment]
Yes. It is in Gnome documentation. In the documentation (with CC-BY-SA-3.0) , there are examples of code, and the code has this exception.

**Comment by jlovejoy** [comment]
+1 to add and maybe something like `Gnome-examples-exception` ? A quick Google search didn't reveal other uses.

**Comment by swinslow** [comment]
+1 to add, with ID `GNOME-examples-exception` and name "GNOME examples exception".

The notes could probably mention "This exception has been used with CC-BY-SA-3.0."

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
GNOME examples exception
## License ID
GNOME-examples-exception
## XML markup

## Notes:
This exception has been used with CC-BY-SA-3.0.
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
