### ISSUE TITLE
New license request: Sun-PPP

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2320]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/446

> A legacy FOSS permissive license.

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

https://github.com/ppp-project/ppp/blob/master/pppd/eap.c#L7-L16

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

https://github.com/paulusmack/ppp

### paste text of license here

```
 * Non-exclusive rights to redistribute, modify, translate, and use
 * this software in source and binary forms, in whole or in part, is
 * hereby granted, provided that the above copyright notice is
 * duplicated in any source form, and that neither the name of the
 * copyright holder nor the author is used to endorse or promote
 * products derived from this software.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by swinslow** [comment]
+1 to add. seeing several instances in the wild, e.g. finding it in the following:

* https://www.watchguard.com/help/docs/fireware/12/en-US/v12_4_Copyright-Licensing_Guide.pdf
* https://software-dl.ti.com/omap/jacinto6/JACINTO6-EVM/6AK_1_2_Release/artifacts/Android_6AK_1_2_NOTICE.html
* https://downloads.hpe.com/pub/softlib2/software1/doc/p115857987/v60716/hpoaeula.pdf

All of these have the Sun copyright notice. Perhaps `Sun-PPP` as ID and "Sun PPP License" as name?

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Sun PPP License
## License ID
Sun-PPP
## XML markup
none


## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
