### ISSUE TITLE
New license request: paul-mackerras-binary

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2323]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/441

> This is pretty close to BSD-Attribution-HPND-disclaimer (closer than the other Paul Mackerras licenses seen in this issue set) and possibly could be accommodated by that identifier with some minor changes to the definitional markup.

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

https://github.com/ppp-project/ppp/blob/master/pppd/plugins/minconn.c#L6-L33

### OSI Status

I don't know

### License author or steward

Paul Mackerras

### URL to project(s) that use license

https://github.com/paulusmack/ppp

### paste text of license here

```
 * Copyright (c) 1999 Paul Mackerras. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The name(s) of the authors of this software must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission.
 *
 * 4. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by Paul Mackerras
 *     <paulus@ozlabs.org>".
 *
 * THE AUTHORS OF THIS SOFTWARE DISCLAIM ALL WARRANTIES WITH REGARD TO
 * THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS, IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
```

**Comment by jlovejoy** [comment]
this is indeed a close match to https://spdx.org/licenses/BSD-Attribution-HPND-disclaimer.html 
the only differences are the names (non-substantive)
and this variant omits the line about who to contact and address in clause 3 (which is marked as replaceable)
`For permission or any other legal details, please contact
Office of Technology Transfer
Carnegie Mellon University
5000 Forbes Avenue
Pittsburgh, PA 15213-3890
(412) 268-4387, fax: (412) 268-7395
tech-transfer@andrew.cmu.edu`

what do we think about making that part optional??

**Comment by swinslow** [comment]
Discussed on 2024-01-25 legal team call, agreed that we're comfortable with making the "please contact" part of clause 3 optional.

**Comment by yarda** [comment]
OK, I will do PR.
