### ISSUE TITLE
New license request: paul-mackerras-new

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2325]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/443

> This is sort of like a mashup of three-clause BSD with the HPND disclaimer. It is close to BSD-Attribution-HPND-disclaimer but does not quite match (particularly because it doesn't have the acknowledgement clause).

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

https://github.com/ppp-project/ppp/blob/master/pppd/chap_ms.c#L6-L28

### OSI Status

I don't know

### License author or steward

Paul Mackerras

### URL to project(s) that use license

https://github.com/paulusmack/ppp

### paste text of license here

```
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The name(s) of the authors of this software must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission.
 *
 * THE AUTHORS OF THIS SOFTWARE DISCLAIM ALL WARRANTIES WITH REGARD TO
 * THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS, IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
 * OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

**Comment by jlovejoy** [comment]
similar to https://github.com/spdx/license-list-XML/issues/2323 this license uses different names and removes the address in clause 3

but it also entirely removes clause 4 in that license which requires  redistributions of any form to retain an  acknowledgment

given this difference, I'd say this is a different license and + to add (how to name and id, tho?)

**Comment by swinslow** [comment]
See comments at #2324 for a closely related license name/ID

**Comment by jlovejoy** [comment]
id suggestion: `Mackerras-3-Clause-binary`

sounds fine to me and I don't have any better ideas! @richardfontana do you want to weigh in?

**Comment by jlovejoy** [comment]
looking at this again - maybe it should be `Mackerras-3-Clause` - by adding "binary" kind of makes me think it would be a binary-only license or something along those lines?

thoughts?

**Comment by swinslow** [comment]
I'm fine with `Mackerras-3-Clause`, these are going to be rare enough that I don't think it's a big issue if we omit the "binary" bit from this one, and #2324 has `-acknowledgment` in any case.
