### ISSUE TITLE
New license request: sun-prop-non-commercial

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2326]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/444

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

  https://github.com/ppp-project/ppp/blob/master/modules/ppp_ahdlc.c#L7-L19

### OSI Status

I don't know

### License author or steward

Sun Microsystems, Inc.

### URL to project(s) that use license

https://github.com/paulusmack/ppp

### paste text of license here

```
 * Copyright (c) 2000 by Sun Microsystems, Inc.
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation is hereby granted, provided that the above copyright
 * notice appears in all copies.  
 *
 * SUN MAKES NO REPRESENTATION OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT.  SUN SHALL NOT BE LIABLE FOR
 * ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
 * DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES
```

**Comment by jlovejoy** [comment]
this does not seem to match anything currently on the list.

+1 to add, not sure about name, but using Sun seems ok?

**Comment by copernicat** [comment]
I see this sentence is copied verbatim from the Python license https://www.python.org/doc/copyright/. Does that affect our analysis? 
About the name, it seems to me to be too much emphasis to call it Sun, because the license text shows multiple contributors. Maybe they contributed a small amount to the project under a one-off license. I will check with my open source contact formerly at Sun to see if there is any relevant history.

**Comment by copernicat** [comment]
OK, I heard back from the former Sun open source attorney, who confirmed that Sun wrote a "bunch" of open source licenses, so I'm thinking calling it just Sun might not be ideal. What do you think about SunPython or SunPPP?

**Comment by karsten-klein** [comment]
**ScanCode**
not adequate match; [sun-prop-non-commercial](https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/licenses/sun-prop-non-commercial.LICENSE) (as mentioned in issue title) contains further paragraphs. 

**{metæffekt} Universe**
canonical name: [Permission Terms (Sun Microsystems)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-(Sun-Microsystems):~:text=Permission%20Terms%20(Sun%20Microsystems))
short name: PT-Sun

**Comment by jlovejoy** [comment]
Thanks @copernicat for checking in. I realized, we already have `Sun-PPP` and `SunPro` as license ids on the license list (neither of which match this license)

As this license appears in the same project, maybe we could do something like:
`Sun-PPP-2000` or `Sun-PPP-2` 

@karsten-klein - the license you reference in ScanCode is not a match to this license. It explicitly states the software and its documentation can only be used for non-commercial purposes and has an extra paragraph in the middle. FYI and thus, we should not use a similar name as what ScanCode uses.

**Comment by swinslow** [comment]
+1 to adding this.

For ID, I tend to agree with @jlovejoy that `Sun-PPP-2000` might be the way to go, for lack of anything better. Name could be "Sun PPP License (2000)".

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Sun PPP License (2000)
## License ID
Sun-PPP-2000
## XML markup
none
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
