### ISSUE TITLE
New license request: gtkbook [was rrdtool-other-permissive]

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2332]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/449

### License Name

No idea

### Suggested short identifier

No idea

### License or Exception?

license

### URL to license text

https://github.com/oetiker/rrdtool-1.x/blob/master/src/plbasename.c#L8-L11 https://github.com/oetiker/rrdtool-1.x/blob/master/src/plbasename.h#L8-L11

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

rrdtool: https://oss.oetiker.ch/rrdtool/

https://github.com/oetiker/rrdtool-1.x

### paste text of license here

``` 
 * This code is distributed without warranty. You are free to use this
 * code for any purpose, however, if this code is republished or
 * redistributed in its original form, as hardcopy or electronically,
 * then you must include this copyright notice along with the code.
```

**Comment by zvr** [comment]
Just to be clear on the "projects that use this license" section: `rrdtool` is under GPL, and only includes a couple of files under this license.

We can ask @oetiker if he remembers where he got the file originally from. -- if you read this, hi Tobi! long time no see ;-)

Or we can ask the original author @slogan621 for the origin.

**Comment by oetiker** [comment]
Hi Alexios :) 
this was a contribution https://github.com/oetiker/rrdtool-1.x/commit/74bc7196ea251714969f9f0870242dda11233cc2
I don't know the history of the code ... but as I read it, the license in the text does not conflict with gpl ... or do you see a problem ?

**Comment by zvr** [comment]
No, don't worry, it has nothing to do with conflicts. The SPDX project maintains a list of licenses https://spdx.org/licenses/ and it gives short identifiers to them, so that people can refer to, for example `BSD-3-Clause` and we all talk about the same thing.

This issue is simply about adding the license of these files in the list. My comment is that we shouldn't be calling this something involving rrdtool (since this is GPL), but rather try to find a name pointing to the origin. For example `Syd-Logan-Permissive` or something.

**Comment by oetiker** [comment]
uff :)

**Comment by richardfontana** [comment]
This might indicate an earlier origin:
https://github.com/slogan621/gtkbook

**Comment by slogan621** [comment]
I’m cool with it being used.

These days, I license nearly everything Apache 2.0 - I could perhaps look
into re-licensing this code as Apache 2.0 as well, if that is necessary.
Apache 2.0 should be compatible with gpl in that you can incorporate it
into gpl code. In the big scheme of things, that is what this code was
intended for, unrestricted use.

Syd

**Comment by jlovejoy** [comment]
as long as this license is still out there "in the wild" then we would want to capture it. Unless I'm mistaken as to how this is used and its prevalence, I don't think re-licensing it now to Apache-2.0 can really claw back all the copies out there under this license.

**Comment by swinslow** [comment]
Discussed with @jlovejoy, agreed to use `gtkbook` as ID and "gtkbook License" as name
