### ISSUE TITLE
New license request: gpl-2.0-plus WITH rrdtool-floss-exception-2.0

### ISSUE THREAD

**Issue by yarda** [spdx/license-list-XML#2333]
### How license meets inclusion principles

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/448

### License Name

rrdtool-floss-exception-2.0

### Suggested short identifier

rrdtool-floss-exception-2.0

### License or Exception?

exception

### URL to license text

https://github.com/oetiker/rrdtool-1.x/blob/master/COPYRIGHT#L25-L90

### OSI Status

I don't know

### License author or steward

Unknown

### URL to project(s) that use license

rrdtool: https://oss.oetiker.ch/rrdtool/

https://github.com/oetiker/rrdtool-1.x

### paste text of license here

```
FLOSS License Exception 
=======================
(Adapted from http://www.mysql.com/company/legal/licensing/foss-exception.html)

I want specified Free/Libre and Open Source Software ("FLOSS")
applications to be able to use specified GPL-licensed RRDtool
libraries (the "Program") despite the fact that not all FLOSS licenses are
compatible with version 2 of the GNU General Public License (the "GPL").

As a special exception to the terms and conditions of version 2.0 of the GPL:

You are free to distribute a Derivative Work that is formed entirely from
the Program and one or more works (each, a "FLOSS Work") licensed under one
or more of the licenses listed below, as long as:

1. You obey the GPL in all respects for the Program and the Derivative
Work, except for identifiable sections of the Derivative Work which are
not derived from the Program, and which can reasonably be considered
independent and separate works in themselves,

2. all identifiable sections of the Derivative Work which are not derived
from the Program, and which can reasonably be considered independent and
separate works in themselves,

1. are distributed subject to one of the FLOSS licenses listed
below, and

2. the object code or executable form of those sections are
accompanied by the complete corresponding machine-readable source
code for those sections on the same medium and under the same FLOSS
license as the corresponding object code or executable forms of
those sections, and

3. any works which are aggregated with the Program or with a Derivative
Work on a volume of a storage or distribution medium in accordance with
the GPL, can reasonably be considered independent and separate works in
themselves which are not derivatives of either the Program, a Derivative
Work or a FLOSS Work.

If the above conditions are not met, then the Program may only be copied,
modified, distributed or used under the terms and conditions of the GPL.

FLOSS License List
==================
License name	Version(s)/Copyright Date
Academic Free License		2.0
Apache Software License	1.0/1.1/2.0
Apple Public Source License	2.0
Artistic license		From Perl 5.8.0
BSD license			"July 22 1999"
Common Public License		1.0
GNU Library or "Lesser" General Public License (LGPL)	2.0/2.1
IBM Public License, Version    1.0
Jabber Open Source License	1.0
MIT License (As listed in file MIT-License.txt)	-
Mozilla Public License (MPL)	1.0/1.1
Open Software License		2.0
OpenSSL license (with original SSLeay license)	"2003" ("1998")
PHP License			3.01
Python license (CNRI Python License)	-
Python Software Foundation License	2.1.1
Sleepycat License		"1999"
W3C License			"2001"
X11 License			"2001"
Zlib/libpng License		-
Zope Public License		2.0/2.1
```

**Comment by karsten-klein** [comment]
**ScanCode**
reference id: [rrdtool-floss-exception-2.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/rrdtool-floss-exception-2.0.LICENSE)
matched id: [generic-exception](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/generic-exception.LICENSE)
matched id: [gpl-1.0-plus](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/gpl-1.0-plus.LICENSE)
matched id: [gpl-2.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/gpl-2.0.LICENSE)

**{metæffekt} Universe**
canonical name: [RRDtool FLOSS Exception (GPL)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[r]/README.md#user-content-RRDtool-FLOSS-Exception-(GPL):~:text=RRDtool%20FLOSS%20Exception%20(GPL))
short name: RRDtool-FLOSS-Exception-GPL

**Comment by jlovejoy** [comment]
ok, so I wanted to dig a bit, b/c I really thought the original MySql exception this is based on was added to the SPDX License List https://www.mysql.com/about/legal/licensing/foss-exception/
Turns out my memory isn't completely wrong, as it was submitted: https://lists.spdx.org/g/Spdx-legal/message/538 and https://docs.google.com/spreadsheets/d/11AKxLBoN_VXM32OmDTk2hKeYExKzsnPjAVM7rLstQ8s/edit?pli=1#gid=0
but I can't find any evidence of discussion on a call or final decision, so I guess it fell through the cracks and, as it's now deprecated maybe that doesn't matter.

Turning to this exception - +1 to add as I think it meets our inclusion principles for exceptions in that:
1. It is not a stand-alone license.
2. It grants an exception to a license condition; and/or
3. it does not impose additional restrictions or limitations beyond those granted in the underlying license.
4. The exception has actual, substantial use such that it is likely to be encountered by way of it being found in a major distro

**Comment by mkdolan** [comment]
> Turning to this exception - +1 to add as I think it meets our inclusion principles for exceptions in that:

+1 as well from me.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
RRDtool FLOSS exception 2.0
## License ID
RRDtool-FLOSS-exception-2.0

## XML markup
none
## Notes:
This exception is generally used with GPL-2.0

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
