### ISSUE TITLE
New license request: BSD-2-Clause-Darwin [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by lzaoral** [spdx/license-list-XML#2335]
**1.** License Name: BSD 2-Clause "Simplified" Darwin License
**2.** Short identifier: BSD-2-Clause-Darwin
**3.** License Author or steward: Ian F. Darwin
**4.** Comments: It is used in Fedora and this license was found during license review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/457
**5.** License Request Url: http://tools.spdx.org/app/license_requests/335
**6.** URL(s): https://github.com/file/file/blob/master/COPYING
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/3d11444e-219b-4f2f-b050-cad04211e141.png

**Note:**
The license closely matched with the following license ID(s): BSD-2-Clause-Views

**Comment by jlovejoy** [comment]
This is a match to BSD-2-Clause, except the following differences:
1) it adds at the beginning: "This software is not subject to any export provision of the United States Department of Commerce, and may be exported to any country or planet."

2) it adds the good old, "immediately at the beginning of the file, without modification" in the first clause 

As to #1 - I'm pretty sure you can't simply disclaim export law in this way, so not really sure what to do about that...

as to #2, we have two other submissions with this text - https://spdx.org/licenses/libutil-David-Nugent.html and https://github.com/spdx/license-list-XML/blob/867964cc59d0b811c682b3501333fd4dd7d61eee/src/BSD-Source-beginning-file.xml
but neither match this in other ways so I lean to adding as a new license

**Comment by swinslow** [comment]
Also +1 to add. I could take a guess at their intended meaning for the export clause, but not needed to interpret here  :) Same for the "immediately at the beginning" clause, perhaps problematic in practice but I'd say not an issue for these purposes.

Fine with proposed ID, for name I'd probably go with "BSD 2-Clause - Ian Darwin variant"

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
BSD 2-Clause - Ian Darwin variant
## License ID
BSD-2-Clause-Darwin
## XML markup
none
## Notes:
This is similar to BSD-2-Clause, except it adds "immediately at the beginning of the file, without modification" in the first clause and adds an attempt to disclaim export law in the beginning.

## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
