### ISSUE TITLE
Missing dot in BSD-2-Clause-Views?

### ISSUE THREAD

**Issue by eest** [spdx/license-list-XML#2336]
Looking at the copyright text in BSD-2-Clause-Views it starts with:
https://github.com/spdx/license-list-XML/blob/d59b71b5c559f529f5a811d9bf859047f921c6a7/src/BSD-2-Clause-Views.xml#L15-L17

Comparing this with the FreeBSD license it is replacing, it looks like this:
https://github.com/spdx/license-list-XML/blob/d59b71b5c559f529f5a811d9bf859047f921c6a7/src/BSD-2-Clause-FreeBSD.xml#L18-L20

The former does not have a dot between the name of the owner and the `All rights reserved.` statement. It also claims to be 

> identical to BSD-2-Clause with the addition of the "views and conclusions" sentence at the end

but looking at BSD-2-Clause it omits the `All rights reserved.` entirely (still has the dot at the end though):
https://github.com/spdx/license-list-XML/blob/d59b71b5c559f529f5a811d9bf859047f921c6a7/src/BSD-2-Clause.xml#L9-L11

... so it seems to me at least the dot should be added, and possibly the `All rights reserved.` should be removed? The latter is possibly related to this statement at https://www.freebsd.org/internal/software-license/:

> Historically, the phrase 'All Rights Reserved.' was included in all copyright notices. The BSD releases had it to comply with the Buenos Aires Convention of 1910 in the Americas. With the ratification of the Berne Convention in 2000, it became obsolete. As such, the FreeBSD project recommends that new code omit the phrase and encourages existing copyright holders to remove it. In 2018, the project updated its templates to remove it.

**Comment by bsdimp** [comment]
The FreeBSD Project standard practice had been `Copyright YEAR Joe Programmer. All Rights Reserved.` so when this markup was changed to be generic, the '.' was removed.

`All Rights Reserved.` is in the BSD license because it pre-dates the Berne convention and was hoping to invoke the Copyright protections that the Buenos Aires convention gives for that phrase. Its use was a decade or more archaic by the time the FreeBSD project ditched it. At the time the BSD license was written, though, it was necessary to have a valid copyright in the countries that had not yet ratified the Bern conventions so as to be able to protect the IP and to grant a license at all (otherwise there'd be uncertainty over both points).

**Comment by bsdimp** [comment]
However, is this really an issue. We ignore the copyright text for the purposes of matching the license, and it's just an example.... otoh, it's easy enough to just add it back. I'm agnostic either way, and I don't see it making a legal difference but I'll defer to the lawyers to offer a legal opinion about that.

**Comment by eest** [comment]
Thanks for looking at my issue! Regarding if it is an issue or not I do not really know. I was looking for a template for the `BSD-2-Clause-Views` license to use and just noticed what looked like a discrepancy. As I wasn't sure if it is important or not I thought it was better to ask.

**Comment by jlovejoy** [comment]
@bsdimp is right in so far as the copyright notice is ignored for the purposes of license text matching - see https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b11-copyright-notice for more details.

I don't have an opinion one way or another in terms of what is sort aesthetics of this, but from a purely pragmatic standpoint: given how many issues we have open, I don't think it warrants a PR!

**Comment by jlovejoy** [comment]
so I would close this issue, meant to add above

**Comment by xsuchy** [comment]
+1 to close it as the text is ignored.
If you disagree, please open directly PR that add the dot.
