### ISSUE TITLE
Markup change for GStreamer-exception-2005

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2339]
In Fedora, we discovered [1] that package Sushi [2] contains an exception that matches GStreamer-exception-2005 [3]. But the XML in SPDX contains the wording "The Totem project hereby..." but Sushi license has " The Sushi project hereby...". The alternate wording is included in GStreamer-exception-2008 [4]. I propose that we add the `<alt>' markup that is present in the 2008 variant to the 2005 variant too, to accommodate the Sushi exception.

[1] https://gitlab.com/fedora/legal/fedora-license-data/-/issues/460
[2] https://gitlab.gnome.org/GNOME/sushi/-/blob/master/src/libsushi/sushi-font-loader.c?ref_type=heads#L17
[3] https://spdx.org/licenses/GStreamer-exception-2005.html
[4] https://github.com/spdx/license-list-XML/blob/main/src/exceptions/GStreamer-exception-2008.xml

Sushi exception:
```
 The Sushi project hereby grant permission for non-gpl compatible GStreamer
 plugins to be used and distributed together with GStreamer and Sushi. This
 permission is above and beyond the permissions granted by the GPL license
 Sushi is covered by.
```

**Comment by jlovejoy** [comment]
it also uses "is above and beyond" instead of "are above and beyond"
but correct/incorrect grammar in this case, I think can also be accommodated with markup

**Comment by jlovejoy** [comment]
as for `GStreamer-exception-2008` - we already have alt tags for the project name.

Not sure we should bother with the grammar markup there, unless we find an instance of that?
