### ISSUE TITLE
New license request: softsurfer [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2340]
**1.** License Name: softSurfer License
**2.** Short identifier: softsurfer
**3.** License Author or steward: Daniel Sunday
**4.** Comments: This was discovered during Fedora License review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/469 The license is used in lcms2 package.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/336
**6.** URL(s): https://github.com/mm2/Little-CMS/blob/master/src/cmssm.c#L207
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mm2/Little-CMS/

**Comment by xsuchy** [comment]
Text of the license:
```
Copyright 2001, softSurfer (www.softsurfer.com)
This code may be freely used and modified for any purpose                                                                                                                                
providing that this copyright notice is included with it.
SoftSurfer makes no warranty for this code, and cannot be held
liable for any real or imagined damage resulting from its use.
Users of this code must verify correctness for their application.
```

**Comment by jlovejoy** [comment]
This license was not added to SPDX when we did prior reviews of the old Fedora good list b/c we didn't think it still existed in Fedora.
See https://fedoraproject.org/wiki/Licensing/softSurfer
It is not substantially similar to anything already on the SPDX License List
+1 to add ad use `SoftSurfer` for id

**Comment by swinslow** [comment]
+1 to add with this ID

**Comment by Pizza-Ria** [comment]
A grudging +1 - I think this is another annoying variation on another license (or Frankenstein's monster of a group of licenses) that has to already be in SPDX but the DIFF tool doesn't really assess that.
