### ISSUE TITLE
New license request: CMU-Mach-nodoc [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by jrisc** [spdx/license-list-XML#2345]
**1.** License Name: CMU Mach license without notices-in-documentation clause
**2.** Short identifier: CMU-Mach-nodoc
**3.** License Author or steward: Unknown
**4.** Comments: This license is similar to the CMU Mach License, except it does not require notices to appear in supporting documentation.

This license may actually be a candidate for an exception, since it "[...] grants an exception to a license condition or additional permissions beyond those granted in the license it modifies", if we consider not mentioning notices in the documentation is an additional permission.

This license is used in Fedora, and was found during license review:
https://gitlab.com/fedora/legal/fedora-license-data/-/issues/464
**5.** License Request Url: http://tools.spdx.org/app/license_requests/339
**6.** URL(s): https://github.com/krb5/krb5/blob/krb5-1.21.2-final/NOTICE#L718-L728, https://web.mit.edu/kerberos/krb5-1.21/doc/mitK5license.html
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://web.mit.edu/kerberos/

**Comment by jlovejoy** [comment]
This is close to CMU-Mach but omits the obligation `that both notices appear in supporting documentation.` and omits the request to return improvements or extensions back to the copyright holder (last part). By omitting the obligation related to the notices in supporting documentation doesn't make it an exception (in the sense of being an additional clause that amends an existing license), it's just different than the CMU-Mach license in this way. 

I think this should be added as a new license.
Id suggestion here seems ok

**Comment by swinslow** [comment]
+1 to add, and fine with name + ID
