### ISSUE TITLE
BlueOak-1.0.0 is now OSI-approved

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#2352]
Per http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2024-January/005453.html

To update `isOsiApproved` in https://github.com/spdx/license-list-XML/blob/main/src/BlueOak-1.0.0.xml accordingly

**Comment by sskras** [comment]
Long time no see – OMG, finally!
Thanks for the news. :)
