### ISSUE TITLE
New exception request: Autoconf-exception-Gnulib (a variant of Autoconf-exception-generic?)

### ISSUE THREAD

**Issue by ppisar** [spdx/license-list-XML#2355]
### How license meets inclusion principles

An exception to GPL, very similar to Autoconf-exception-generic exception. I quote Autoconf-exception-generic here for a comparison:

~~~~
As a special exception to the GNU General Public License, if you
distribute this file as part of a program that contains a configuration
script generated by Autoconf, you may include it under the same
distribution terms that you use for the rest of that program.
~~~~

I'm not sure whether we should assign a new exception identifier, or augment XML markup for Autoconf-exception-generic.

### License Name

Autoconf Gnulib exception

### Suggested short identifier

Autoconf-exception-Gnulib

### License or Exception?

exception

### URL to license text

https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=blob;f=gnulib-tool;h=029a8cf377ad8d8f2d9e54061bf2f20496ad2eef;hb=73c74ba0197e6566da6882c87b1adee63e24d75c#l394

### OSI Status

I don't know

### License author or steward

Gnulib

### URL to project(s) that use license

This license is used for gnulib-cache.m4 file that is bundled in projects using Gnulib static library. E.g. by "time" project as "m4/gnulib-cache.m4" file in <https://ftp.gnu.org/gnu/time/time-1.9.tar.gz> archive. The "m4/gnulib-cache.m4" is a product of "gnulib-tool" program. The tool comes from Gnulib project <https://www.gnu.org/software/gnulib/>. Both pieces of software are distributed by Fedora <https://gitlab.com/fedora/legal/fedora-license-data/-/issues/473>.

### paste text of license here

~~~~
As a special exception to the GNU General Public License,
this file may be distributed as part of a program that
contains a configuration script generated by Autoconf, under
the same distribution terms as the rest of that program.
~~~~

**Comment by jlovejoy** [comment]
looking at the comparison using LicenseDiff, this seems to be just different wording/order of words with the same meaning:
1)
`this file may be distributed` as part of...
versus 
`if you distribute this file` as part of...

2)
`under the same distribution terms as` the rest of...
versus
`you may include it under the same distribution terms that you use for` the rest of...

**Comment by swinslow** [comment]
+1, sounds good to me.
