### ISSUE TITLE
New license request: Threeparttable [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2365]
**1.** License Name: Threeparttable
**2.** Short identifier: Threeparttable
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Texlive. Discovered during license review in Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/451
**5.** License Request Url: http://tools.spdx.org/app/license_requests/345
**6.** URL(s): https://fedoraproject.org/wiki/Licensing/Threeparttable
**7.** OSI Status: Unknown
**8.** Example Projects: https://ctan.org/pkg/threeparttable?lang=en

**Comment by xsuchy** [comment]
License text:
```
This file may be distributed, modified, and used in other works with just
one restriction: modified versions must clearly indicate the modification
(a name change, or a displayed message, or ?).
```

**Comment by karsten-klein** [comment]
**ScanCode**
matched: [other-permissive](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/other-permissive.LICENSE)

**{metæffekt} Universe**
canonical name: [Three Part Table License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[t]/README.md#user-content-Three-Part-Table-License:~:text=Three%20Part%20Table%20License)
short name: threeparttable

**Comment by jlovejoy** [comment]
@karsten-klein - are you in favor of adding this then? 

appreciate the input on names used in other databases. If something is recorded in {metæffekt} Universe, does that mean it has been found "in the wild? by way of audits you have done?

As for name and ID, I'd be fine with the more human-legible "Three Part Table License" for full name and am ambivalent as to dashes and capitalization (Three-Part-Table) versus none (Threeparttable)

**Comment by karsten-klein** [comment]
In this case we haven't found this on our end. We basically added it because it shows up as SPDX license request. I'll try to add the source of information to future comments.

Your ambivalence is completely understood. We were also struggling. But our policy is to preserve the information in the finding and not to invent things. For us Threeparttable appears as invented, since the license says: 

> % Three part tables: title, tabular environment, notes

Now we can struggle further on the plural 's' in tables.

**Comment by jlovejoy** [comment]
ha!, yeah, like I have said, naming is hard! Funny thing is, in the past, we would have just used what Fedora was already using. But now that Fedora is using SPDX ids... that's a bit circular. 

I did take a look at the documentation and it is referred to as `threeparttable` (no spaces) pretty consistently, so I think we can go with that.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
threeparttable License
## License ID
threeparttable
## XML markup
none (but note, I would include the notice at the top two lines as seen here https://fedoraproject.org/wiki/Licensing/Threeparttable
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
