### ISSUE TITLE
New license request: MIT-Taylor [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2370]
**1.** License Name: MIT Taylor Variant
**2.** Short identifier: MIT-Taylor
**3.** License Author or steward: Unknown
**4.** Comments: This license was discovered during license review in Fedora Linux. https://gitlab.com/fedora/legal/fedora-license-data/-/issues/476 It is used in the package pkgconf.
The license is known to scancode toolkit https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-taylor-variant.LICENSE
**5.** License Request Url: http://tools.spdx.org/app/license_requests/346
**6.** URL(s): https://github.com/pkgconf/pkgconf/blob/master/cli/main.c#L8
**7.** OSI Status: Unknown
**8.** Example Projects: http://pkgconf.org/

**Comment by xsuchy** [comment]
Text of the license:
```
Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.
 
This software is provided 'as is' and without any warranty, express or
implied.  In no event shall the authors be liable for any damages arising
from the use of this software.
```

**Comment by jlovejoy** [comment]
I've done some searching and while this has some similarities to some of the HPND variants, it's distinct, especially in that it adds an explicit disclaimer of liability.

+1 to add. As for id, could we use the project name, pkgconf - given the copyright notice in the link @xsuchy provided?

to be clear, the license at https://github.com/pkgconf/pkgconf/blob/master/cli/main.c#L8 does NOT match the license in Scancode at https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-taylor-variant.LICENSE as the disclaimer warranties and of liability is more robust in the latter.

**Comment by karsten-klein** [comment]
**ScanCode**
id: [mit-taylor-variant](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-taylor-variant.LICENSE)

**{metæffekt} Universe**
canonical name: [Permission Terms (variant 076)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-(variant-076):~:text=Permission%20Terms%20(variant%20076))
short name: PT-Var076

**Comment by xsuchy** [comment]
> +1 to add. As for id, could we use the project name, pkgconf - given the copyright notice in the link @xsuchy provided?

I am open to anything in a name. In this case and any other case. For me, it is just a unique key. I am used from databases to a number, but human readable string is better in this case. And the string can be anything. I do not have emotional bond to it :)

**Comment by jlovejoy** [comment]
@karsten-klein - are you in favor of adding, then?

As to naming - anyone know where the "taylor" comes from? Or why we wouldn't associate with the package since it seems to be specific to pkgconf?

**Comment by jlovejoy** [comment]
Given that this is NOT the same as what Scancode has and Scancode calls it `mit-taylor-variant` - I think it would not be helpful to use that or a similar name. 
Given it is in the pkgconf project, is there any reason not to just use that as the id and name?

**Comment by pombredanne** [comment]
@jlovejoy re:
> As to naming - anyone know where the "taylor" comes from? Or why we wouldn't associate with the package since it seems to be specific to pkgconf?

The name "MIT Taylor variant" came from  @quinntaylor https://github.com/quinntaylor/CHDataStructures/blob/097c0e3f4d7ae1c24266d3d03434e07b9b76f3db/source/Util.h#L6C1-L9C1 
He later switched to the ISC.

**Comment by swinslow** [comment]
+1 to add. I'm not finding anything existing on the License List that matches this, although it clearly has similar language to many other licenses.

Agreed that this is not a match for what ScanCode calls [mit-taylor-variant](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-taylor-variant.LICENSE).

I'm good with `pkgconf` as ID and "pkgconf License" as name. From some searching, pkgconf is the earliest project I've stumbled across that uses this particular license text, so I think that's fine for the ID/name.
