### ISSUE TITLE
New license request: Opencascade-exception-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by danderson** [spdx/license-list-XML#2389]
**1.** License Name: Open CASCADE Exception 1.0
**2.** Short identifier: Opencascade-exception-1.0
**3.** License Author or steward: Open Cascade S.A.S.
**4.** Comments: The exception partially relaxes the virality of the LGPL 2.1. It allows combining code from the LGPL project's header files with non-LGPL code, provided the result contains a notice that it uses or is based on opencascade software. It is similar in intent and wording to other existing exceptions (e.g. mif-exception), but no other currently listed exception that I could find is an exact match.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/350
**6.** URL(s): https://dev.opencascade.org/resources/licensing
**7.** OSI Status: Approved
**8.** Example Projects: https://dev.opencascade.org/

**Comment by danderson** [comment]
For easier reference, this is the text of the exception, which is appended to the GNU LGPL 2.1:

```
Open CASCADE Exception (version 1.0) to GNU LGPL version 2.1.

The object code (i.e. not a source) form of a "work that uses the Library" can incorporate material from a header file that is part of the Library. As a special exception to the GNU Lesser General Public License version 2.1, you may distribute such object code incorporating material from header files provided with the Open CASCADE Technology libraries (including code of CDL generic classes) under terms of your choice, provided that you give prominent notice in supporting documentation to this code that it makes use of or is based on facilities provided by the Open CASCADE Technology software.
```

Some further context: I maintain some packages in the [nixpkgs](https://nixos.org) software distribution. Nixpkgs uses SPDX license identifiers to track the licenses of the software it packages. OpenCascade is currently listed in there as LGPL-2.1-only, alongside a freeform comment apologetically noting that this is not quite true, but that there is no SPDX identifier for the OpenCascade exception. So, here I am, attempting to correct the record :)

OpenCascade is used in a number of open source projects, and as such is widely distributed in distros and such. Notable OSS users of OpenCascade are [FreeCAD](https://freecad.org), [CADQuery](https://cadquery.readthedocs.io/en/latest/), and [KiCAD](https://www.kicad.org/). I believe this fulfills the substantial use criterion, despite being an exception that applies to a single open-source project.

**Comment by jlovejoy** [comment]
this is already on the SPDX License List at https://spdx.org/licenses/OCCT-exception-1.0.html

**Comment by danderson** [comment]
Doh. Sorry for the noise, I have no idea how I managed to miss it.

**Comment by jlovejoy** [comment]
ha! it happens. the license-diff Chrome or Mozilla plug-in can be helpful, if you don't already use it!
