### ISSUE TITLE
Asterisk linking exceptions

### ISSUE THREAD

**Issue by sertonix** [spdx/license-list-XML#2390]
In the [LICENSE file of asterisk](https://github.com/asterisk/asterisk/blob/master/LICENSE) there is a custom paragraph to allow some linking:
> Specific permission is also granted to link Asterisk with OpenSSL, OpenH323
UniMRCP, and/or the UW IMAP Toolkit and distribute the resulting binary files.

I haven't found a way to express that in a spdx license identifier.

`Asterisk-exception` is for something different if I understand it correctly.

**Comment by jlovejoy** [comment]
I'm not sure this is really a specific license exception as the total of this LICENSE file seems to be to explain the licensing overview of the project and where things might be differently licensed or how to request a different license.

I think the bit you quote is referring to https://github.com/asterisk/libpri and files in that part. That exception is on the SPDX License List at https://spdx.org/licenses/libpri-OpenH323-exception.html
see https://github.com/spdx/license-list-XML/issues/1939 and related issue at https://github.com/spdx/license-list-XML/issues/1971

**Comment by karsten-klein** [comment]
This is another case for https://github.com/spdx/change-proposal/blob/main/proposals/Modifiers.md since SPDX do not support modifiers other than exceptions. I agree that the case here is not an exception as usual. Exceptions usually relief from obligations. Here we have a grant of additional permissions.

Our engine resolves the text as follows: 
License: GNU General Public License 2.0 (with Asterisk Linking Permission)
Markers: Trademark Markers, Authors View Marker

The Authors View Marker is added due to the section

> It is our belief that applications using these protocols to manage or control an 
> Asterisk instance do not have to be licensed under the GPL or a compatible license

I'm trying to convince the SPDX team for a long time now to open the modifiers to not only include exceptions, but without success. So for the time being you will have to represent the license as 

GPL-2.0-only AND LicenseRef-Asterisk-Linking-Permission

where the LicenseRef represents the additional grant text. This is also how we would represent our scanner identification in ab SPDX document.

**Comment by jlovejoy** [comment]
@karsten-klein - note that the "exceptions" on the SPDX License do/can include additional permissions as stated on https://spdx.org/licenses/exceptions-index.html 
"These exceptions grant an exception to a license condition or additional permissions beyond those granted in a license; they are not stand-alone licenses."

am I missing something?

**Comment by jlovejoy** [comment]
> Our engine resolves the text as follows:
> License: [GNU General Public License 2.0](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/%5Bg%5D/README.md#user-content-gnu-general-public-license-2.0) (with [Asterisk Linking Permission](user-content-asterisk-linking-permission))

doesn't that resolve back to this repo and issue, then?

**Comment by jlovejoy** [comment]
discussed on the last couple legal calls, as of May 9th and decided to add but use the following text:
```
Specific permission is also granted to link Asterisk with OpenSSL, OpenH323
UniMRCP, and/or the UW IMAP Toolkit and distribute the resulting binary files.

In addition, Asterisk implements several management/control protocols.
This includes the Asterisk Manager Interface (AMI), the Asterisk Gateway
Interface (AGI), and the Asterisk REST Interface (ARI). It is our belief
that applications using these protocols to manage or control an Asterisk
instance do not have to be licensed under the GPL or a compatible license,
as we believe these protocols do not create a 'derivative work' as referred
to in the GPL. However, should any court or other judiciary body find that
these protocols do fall under the terms of the GPL, then we hereby grant you a
license to use these protocols in combination with Asterisk in external
applications licensed under any license you wish.
```

suggested ID: `Asterisk-linking-protocols-exception`

**Comment by swinslow** [comment]
Discussed on 2024-05-09 legal team call, this ID (and a comparable name) makes sense to me too, given that we've already got an `Asterisk-exception` previously on the list. +1 to add

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Asterisk linking protocols exception
## License ID
Asterisk-linking-protocols-exception
## XML markup
none at this time
## Notes:
see comment above for text of exception
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
