### ISSUE TITLE
Add markup to openvpn-openssl exception

### ISSUE THREAD

**Issue by capfei** [spdx/license-list-XML#2401]
The openvpn-openssl exception was updated to accomodate psycopg2 but it looks like one difference was missed.
https://github.com/psycopg/psycopg2/blob/c34bf2f2f90fbbe65e8c4c2650734aa151ddd6ed/LICENSE#L21C50-L21C72
psycopg2:
<img width="395" alt="image" src="https://github.com/spdx/license-list-XML/assets/5489711/f5765890-7599-41f4-9537-aa54b0421740">

SPDX:
<img width="430" alt="image" src="https://github.com/spdx/license-list-XML/assets/5489711/a52ae74b-d97b-4cb4-819e-9c9489ea3aa7">

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [OpenSSL Linking Exception (LGPL; variant 002)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[o]/README.md#user-content-OpenSSL-Linking-Exception-(LGPL;variant-002):~:text=OpenSSL%20Linking%20Exception%20(LGPL;%20variant%20002))
short name: OpenSSL-Linking-Exception-LGPL-002
category: OpenSSL Linking Exception
ScanCode reference id: [openssl-exception-lgpl-3.0-plus](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/openssl-exception-lgpl-3.0-plus.LICENSE)
OSI status: _none_

**Comment**
We revised the representation of all Linking Exception to OpenSSL in our license database. The above result is an update to the previously made references. In sum we identified 11 variants of the exception and consolidated naming across the group making such type of exception immediately recognizable by their name.
