### ISSUE TITLE
dtoa markup change

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2406]
During lincense review in Fedora https://gitlab.com/fedora/legal/fedora-license-data/-/issues/485
we discovered this license:

https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/stdlib/mprec.h;hb=HEAD

used in newlib package. 

The text of license:
```
 * Copyright (c) 1991 by AT&T.
 *
 * Permission to use, copy, modify, and distribute this software for any
 * purpose without fee is hereby granted, provided that this entire notice
 * is included in all copies of any software which is or includes a copy
 * or modification of this software and in all copies of the supporting
 * documentation for such software.
 *
 * THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTY.  IN PARTICULAR, NEITHER THE AUTHOR NOR AT&T MAKES ANY
 * REPRESENTATION OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY
 * OF THIS SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.
```

The only difference is AT&T vs. Lucent on this line https://github.com/spdx/license-list-XML/blob/main/src/dtoa.xml#L20

I think this is very straightforward - I will prepare PR.

**Comment by karsten-klein** [comment]
**ScanCode**
reference id: [x11-lucent](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-lucent.LICENSE)
matched id: [x11-lucent](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-lucent.LICENSE)

**{metæffekt} Universe**
canonical name: [Permission Terms (variant 019)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-(variant-019):~:text=Permission%20Terms%20(variant%20019))
short name: PT-Var019

**Comment by jlovejoy** [comment]
looks good, thanks @xsuchy
