### ISSUE TITLE
dtoa markup or new license (OAR license)

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2408]
During Fedora license review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/488
we discovered the license in package newlib
https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/string/strsignal.c;hb=HEAD

Text of the license:
```
*  COPYRIGHT (c) 1989-2013, 2015.
 *  On-Line Applications Research Corporation (OAR).
 *
 *  Permission to use, copy, modify, and distribute this software for any
 *  purpose without fee is hereby granted, provided that this entire notice
 *  is included in all copies of any software which is or includes a copy
 *  or modification of this software.
 *
 *  THIS SOFTWARE IS BEING PROVIDED "AS IS", WITHOUT ANY EXPRESS OR IMPLIED
 *  WARRANTY.  IN PARTICULAR,  THE AUTHOR MAKES NO REPRESENTATION
 *  OR WARRANTY OF ANY KIND CONCERNING THE MERCHANTABILITY OF THIS
 *  SOFTWARE OR ITS FITNESS FOR ANY PARTICULAR PURPOSE.
```

The wording is very similar to `dtoa` license.  With two changes:

1) in fist paragraph is omitted the trailing of the paragraph: "and in all copies of the supporting
documentation for such software".

2)  In the second paragraph are committed words NEITHER, NOR LUCENT and instead of ANY is used NO.

Is this a new license? Or should it be handled by markup change to dtoa?

**Comment by karsten-klein** [comment]
**ScanCode**
reference id: [x11-oar](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-oar.LICENSE)
matched id: [x11-oar](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/x11-oar.LICENSE)

**{metæffekt} Universe**
canonical name: [X11-Style (OAR)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[x]/README.md#user-content-X11-Style-(OAR):~:text=X11%2DStyle%20(OAR))
short name: X11-OAR
Open CoDE status: approved
Open CoDE similar license id: x11-oar

**Comment by jlovejoy** [comment]
I would need consider this a different license b/c the text "and in all copies of the supporting¶
documentation for such software." constitutes an obligation which is omitted in this particular license. 

That being said, given it's similarity to other licenses overall, and use in Fedora, it seems like an obvious addition to the SPDX License List

As for a name - I'd be fine with using something with "OAR" but I'm not sure why this should be or would be tied to "X11" (note: I did not do research on where this license might be found other than the link provided above)

**Comment by xsuchy** [comment]
Ack regarding submitting as a new license.

What about:
* ID: oar
* Name: On-Line Applications Research Corporation License
* Notes: This is close to dtoa license.

**Comment by copernicat** [comment]
+1 to add, and I agree that using the corporation's name in the license seems OK here- I could not find any other licenses associated with them in a search.

**Comment by jlovejoy** [comment]
Thanks @copernicat !

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
OAR License
## License ID
OAR
## XML markup
none
## Notes:
This license is similar to dtoa, but it omits the obligation to include the notice in all copies of the supporting documentation.
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
