### ISSUE TITLE
New license request: HPND-Christian-Groessler [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by siddhesh** [spdx/license-list-XML#2409]
**1.** License Name: Historical Permission Notice and Disclaimer - Christian Groessler
**2.** Short identifier: HPND-Christian-Groessler
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora through newlib and was found during license review:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/489
**5.** License Request Url: http://tools.spdx.org/app/license_requests/354
**6.** URL(s): https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/misc/fini.c;hb=HEAD
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceware.org/git/?p=newlib-cygwin

**Comment by karsten-klein** [comment]
**ScanCode**
reference id: [codesourcery-2004](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/codesourcery-2004.LICENSE)
matched id: [codesourcery-2004](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/codesourcery-2004.LICENSE)

**{metæffekt} Universe**
canonical name: [CodeSourcery 2004](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/README.md#user-content-CodeSourcery-2004:~:text=CodeSourcery%202004)
short name: CodeSourcery-2004
Open CoDE similar license id: codesourcery-2004
Markers: No Warranty Marker

**Comment by jlovejoy** [comment]
@karsten-klein - the references you are adding are interesting, but I'm not sure if you are implying you think this license should be added to the SPDX License List? If so, could you say so explicitly? :) (that would be really helpful for showing approval from various people) Thanks!

**Comment by jlovejoy** [comment]
license text for reference:

* Copyright (C) 2004 Christian Groessler <chris@groessler.org>
 *
 * Permission to use, copy, modify, and distribute this file
 * for any purpose is hereby granted without fee, provided that
 * the above copyright notice and this notice appears in all
 * copies.
 *
 * This file is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

@siddhesh - I notice that the license text you copied for the submission has the copyright for Christian Groessler, but the link to the license in newlib has Code Sourcery in the copyright. The copyright notice does not matter for purposes of matching the license, but for naming purposes and origin, how/where did you find the Christian Groessler notice?

**Comment by jlovejoy** [comment]
in any case +1 to add, as I cannot find anything that this matches to or could match to.

**Comment by BrianInglis** [comment]
*Groessler* is credited with more changes:
```
$ grep -R Groessler
ChangeLog:2005-08-17  Christian Groessler  <chris@groessler.org>
include/coff/ChangeLog-9103:2003-07-14  Christian Groessler  <chris@groessler.org>
include/coff/ChangeLog-9103:2001-10-26  Christian Groessler  <cpg@aladdin.de>
newlib/ChangeLog-2015:2007-06-06  Christian Groessler  <chris@groessler.org>
newlib/ChangeLog-2015:2007-06-05  Christian Groessler  <chris@groessler.org>
newlib/ChangeLog-2015:2004-12-17  Christian Groessler  <chris@groessler.org>
newlib/ChangeLog-2015:2003-02-18  Christian Groessler  <chris@groessler.org>
newlib/libc/machine/z8k/memcmp.S: * Copyright (C) 2004 Christian Groessler <chris@groessler.org>
newlib/libc/machine/z8k/memcpy.S: * Copyright (C) 2004 Christian Groessler <chris@groessler.org>
newlib/libc/machine/z8k/memmove.S: * Copyright (C) 2004 Christian Groessler <chris@groessler.org>
newlib/libc/machine/z8k/memset.S: * Copyright (C) 2004 Christian Groessler <chris@groessler.org>
```
but licences and claims copyright only in the last four files above, and his licence does not appear elsewhere in the repo.

*CodeSourcery* licences and copyrights appear in `COPYING.LIBGLOSS` and copyrights in some libgloss targets and elsewhere: 
```
$ grep -R CodeSourcery
ChangeLog:      * COPYING.LIBGLOSS: Add National Semiconductor and CodeSourcery
COPYING.LIBGLOSS:(15) - CodeSourcery, Inc. (tic6x-* targets)
COPYING.LIBGLOSS:Copyright (c) 2010 CodeSourcery, Inc.
COPYING.LIBGLOSS:    * Neither the name of CodeSourcery nor the
COPYING.LIBGLOSS:(22) CodeSourcery, Inc (csky-* targets)
COPYING.LIBGLOSS:Copyright (c) 2006 CodeSourcery Inc
include/partition.h:   Contributed by CodeSourcery, LLC.
libgloss/csky/io-close.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-exit.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-fstat.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-gdb.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-gettimeofday.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-isatty.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-lseek.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-open.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-read.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-rename.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-stat.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-system.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-time.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-unlink.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io-write.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/csky/io.h: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-crt0.S: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-crt1.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-exit.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-hosted.S: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-isrs.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-isv.S: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/cf-sbrk.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/fido-handler.c: * Copyright (c) 2006 CodeSourcery, Inc.
libgloss/m68k/fido-hosted.S: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/fido-_exit.c: * Copyright (c) 2006 CodeSourcery, Inc.
libgloss/m68k/fido_profiling.h: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-close.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-exit.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-fstat.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-gdb.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-gettimeofday.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-isatty.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-lseek.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-open.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-read.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-rename.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-stat.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-system.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-time.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-unlink.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io-write.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/io.h: * Copyright (c) 2006 CodeSourcery Inc
libgloss/m68k/m68k-semi.txt:Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-close.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-exit.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-fstat.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-gdb.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-gettimeofday.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-isatty.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-lseek.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-open.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-read.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-rename.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-stat.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-system.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-time.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-unlink.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io-write.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/io.h: * Copyright (c) 2006 CodeSourcery Inc
libgloss/nios2/nios2-semi.txt:Copyright (c) 2006 CodeSourcery Inc
libgloss/tic6x/crt0.S:   Copyright (c) 2010 CodeSourcery, Inc.
libgloss/tic6x/crt0.S:    * Neither the name of CodeSourcery nor the
libgloss/tic6x/syscalls.c:/* Copyright (c) 2010 CodeSourcery, Inc.
libgloss/tic6x/syscalls.c:    * Neither the name of CodeSourcery nor the
libgloss/visium/io-gdb.c: * Copyright (c) 2006 CodeSourcery Inc
libgloss/visium/io.h: * Copyright (c) 2006 CodeSourcery Inc
newlib/libc/machine/mips/machine/asm.h: * Copyright (C) 2009 CodeSourcery, LLC.
newlib/libc/machine/mips/machine/regdef.h: * Copyright (C) 2009 CodeSourcery, LLC.
newlib/libc/misc/fini.c: * Copyright (C) 2010 CodeSourcery, Inc.
newlib/libc/misc/init.c: * Copyright (C) 2004 CodeSourcery, LLC
newlib/testsuite/newlib.stdlib/stdlib.exp:# Copyright (C) 2008 by CodeSourcery, Inc.  All rights reserved.
```

Best to contact *Corinna Vinschen* and/or *Jeff Johnston* at *RedHat* or via the [ML](mailto:newlib@sourceware.org&subject=Licences) about any discrepancies that may need cured.

**Comment by BrianInglis** [comment]
*CodeSourcery* uses various licences in the above files, but the only two using the same terms as *Groessler* are: 
```
newlib/libc/misc/fini.c: * Copyright (C) 2010 CodeSourcery, Inc.
newlib/libc/misc/fini.c: *
newlib/libc/misc/fini.c: * Permission to use, copy, modify, and distribute this file
newlib/libc/misc/fini.c: * for any purpose is hereby granted without fee, provided that
newlib/libc/misc/fini.c: * the above copyright notice and this notice appears in all
newlib/libc/misc/fini.c: * copies.
newlib/libc/misc/fini.c: *
newlib/libc/misc/fini.c: * This file is distributed WITHOUT ANY WARRANTY; without even the implied
newlib/libc/misc/fini.c: * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
newlib/libc/misc/fini.c: */

newlib/libc/misc/init.c: * Copyright (C) 2004 CodeSourcery, LLC
newlib/libc/misc/init.c: *
newlib/libc/misc/init.c: * Permission to use, copy, modify, and distribute this file
newlib/libc/misc/init.c: * for any purpose is hereby granted without fee, provided that
newlib/libc/misc/init.c: * the above copyright notice and this notice appears in all
newlib/libc/misc/init.c: * copies.
newlib/libc/misc/init.c: *
newlib/libc/misc/init.c: * This file is distributed WITHOUT ANY WARRANTY; without even the implied
newlib/libc/misc/init.c: * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
newlib/libc/misc/init.c: */
```

**Comment by BrianInglis** [comment]
Also please note that *CodeSourcery* uses their own copyright with the **same licence text** for `libc/misc/{init,fini}.c`, also not mentioned in licecnse summaries COPYING.* so should the licence and abbr perhaps be renamed to a little more general phrase rather than duplicated for CS?

**Comment by jlovejoy** [comment]
to add, but need help with decision on name/id

**Comment by StefaniePors** [comment]
since the merchantability exclusion is specifically called out, how about: 
License Name: Historical Permission Notice and Disclaimer - merchantability variant. 
SPDX Identifier: HPND - merchantability variant

Alternatively: 
License Name: Historical Permission Notice and Disclaimer - no implied warranty variant, 
SPDX Identifier: HPND - no implied warranty variant
That obviously gets very long, but the differentiators are "weak"

**Comment by jlovejoy** [comment]
Thanks for weighing in @StefaniePors !  sounds like a good option for the name and id to me.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Historical Permission Notice and Disclaimer - merchantability variant
## License ID
HPND-merchantability-variant
## XML markup
none
## Notes:
This is similar to the HPND grant and short disclaimer, but adds a specific disclaimer as to merchantability and fitness for a particularl purpose
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
