### ISSUE TITLE
New license request: HPND-Intel [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by siddhesh** [spdx/license-list-XML#2410]
**1.** License Name: Historical Permission Notice and Disclaimer - Intel
**2.** Short identifier: HPND-Intel
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora through newlib and was found during license review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/491
**5.** License Request Url: http://tools.spdx.org/app/license_requests/355
**6.** URL(s): https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/machine/i960/memcpy.S;hb=HEAD
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceware.org/git/?p=newlib-cygwin

**Comment by karsten-klein** [comment]
**ScanCode**
matched id: [intel-osl-1993](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/intel-osl-1993.LICENSE)

**Comment by jlovejoy** [comment]
oops, sorry @siddhesh - I never responded here. Nothing to do yet, just assigning it to you b/c you submitted the issue

**Comment by jlovejoy** [comment]
doesn't seem to match to anything already on the SPDX License List. 
@zvr - do you have any input on this one, being it's from Intel? :)

**Comment by jlovejoy** [comment]
+1 to add, not sure on naming, maybe `Intel-MIT` as it seems very similar to MIT in terms of the initial grant. 

@zvr tagging you again, in case you have opinions!

**Comment by StefaniePors** [comment]
Let's go with SPDX Name: 'Historical Permission Notice and Disclaimer - Intel variant' and SPDX-Identifier: 'HPND-Intel' to not include MIT in the name.

**Comment by swinslow** [comment]
@StefaniePors Thank you! +1 from me, good with this name and ID.

**Comment by swinslow** [comment]
Given the +1's in the thread to @StefaniePors's suggestion, I'm marking this as approved.

# License Inclusion Decision

## Decision:

- [X] approved
- [ ] not approved

## Name

Historical Permission Notice and Disclaimer - Intel variant

## License ID

`HPND-Intel`

## XML markup

N/A

## Notes

N/A

## Next steps ##

@swinslow to create PR with XML and test text file
