### ISSUE TITLE
Update SMLNJ to allow matching to the included text

### ISSUE THREAD

**Issue by siddhesh** [spdx/license-list-XML#2411]
**1.** License Name: Historical Permission Notice and Disclaimer with docs disclaimer
**2.** Short identifier: HPND-docs-disclaimer
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora through newlib and was found during license review: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/486
**5.** License Request Url: http://tools.spdx.org/app/license_requests/356
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/02521c6b-f58c-498b-8833-b61acc0c2e87.png

**Note:**
The license closely matched with the following license ID(s): SMLNJ

**Comment by karsten-klein** [comment]
**ScanCode**
reference id: [cmu-uc](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cmu-uc.LICENSE)
matched id: [standard-ml-nj](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/standard-ml-nj.LICENSE)

**{metæffekt} Universe**
canonical name: [Permission Terms CWI](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-CWI:~:text=Permission%20Terms%20CWI)
short name: PT-CWI
Open CoDE status: (approved)
Open CoDE similar license id: MIT-CMU

**Comment**
As one can see the core license part is pretty generic. We derived the template from the CWI License in Python License 2.0. The MIT from CMU also looks quite similar and may be a better fit.
We'll probably will generalize this to a Permission Terms without a specific association to a copyright holder. Please also note, that the ScanCode [standard-ml-nj](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/standard-ml-nj.LICENSE)
 looks quite different to the SPDX template, while it links to SPDX's SMLNJ.

**Comment by jlovejoy** [comment]
link to license text in newlib: https://sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=newlib/libc/stdlib/gdtoa-gethex.c;hb=HEAD

**Comment by jlovejoy** [comment]
This is indeed a match to https://spdx.org/licenses/SMLNJ.html
note the only difference are in how the name is expressed and that is "replaceable" as per SPDX matching guidelines

@karsten-klein - I checked the ScanCode [standard-ml-nj](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/standard-ml-nj.LICENSE) and it matches. It looks like they have simply replaced "Lucent" (and other such specific names) with a generic reference to author, which would also be a match.

**Comment by jlovejoy** [comment]
I'll close this issue shortly

**Comment by xsuchy** [comment]
Copying @richardfontana comment from fedora-license-data repo:
If I'm not mistaken, it is not a match, because it has "that the copyright notice" instead of "the copyright notice", so would require (presumably) a markup change on the SPDX side.

**Comment by jlovejoy** [comment]
ugh, indeed, there is an extra "that" in there which makes no sense and is probably a typo, but I've now added a PR for markup for this.

**Comment by swinslow** [comment]
> ugh, indeed, there is an extra "that" in there which makes no sense and is probably a typo

Yup -- at a wild guess, it may be carried through from the original [OSI template for HPND](https://opensource.org/license/historical-php):

> [and] that both **[that] [the]** copyright notice and this permission notice appear

I assume the HPND template was originally framed this way to match to "that copyright notice" and "the copyright notice". But someone could also do both, I guess  :)

In any case, +1 to make that "that" optional.
