### ISSUE TITLE
New license request: latest W3C licenses

### ISSUE THREAD

**Issue by ThisIsMissEm** [spdx/license-list-XML#2429]
### How license meets inclusion principles

For the same reasons as previous inclusion of W3C licenses. This is just the latest version now that W3C is independent of MIT, with minor other changes.

### License Name

W3C Software Notice and Document License (2023-01-01)

### Suggested short identifier

W3C-20230101

### License or Exception?

license

### URL to license text

https://www.w3.org/copyright/software-license-2023/

### OSI Status

I don't know

### License author or steward

W3C

### URL to project(s) that use license

All updated W3C standards and specifications use this license.

### paste text of license here

This work is being provided by the copyright holders under the following license.

License
By obtaining and/or copying this work, you (the licensee) agree that you have read, understood, and will comply with the following terms and conditions.

Permission to copy, modify, and distribute this work, with or without modification, for any purpose and without fee or royalty is hereby granted, provided that you include the following on ALL copies of the work or portions thereof, including modifications:

     • The full text of this NOTICE in a location viewable to users of the redistributed or derivative work.
     • Any pre-existing intellectual property disclaimers, notices, or terms and conditions. If none exist, the W3C software and document short notice should be included.
     • Notice of any changes or modifications, through a copyright statement on the new code or document such as "This software or document includes material copied from or derived from [title and URI of the W3C document]. Copyright © [$year-of-document] World Wide Web Consortium. https://www.w3.org/copyright/software-license-2023/"

Disclaimers
THIS WORK IS PROVIDED "AS IS," AND COPYRIGHT HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE OR DOCUMENT WILL NOT INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.

COPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENT.

The name and trademarks of copyright holders may NOT be used in advertising or publicity pertaining to the work without specific, written prior permission. Title to copyright in this work will at all times remain with copyright holders.

**Comment by ThisIsMissEm** [comment]
I'm not sure on OSI status, I believe that requires someone from the W3C to submit the license. cc @dmitrizagidulin since you're far more involved with W3C matters than I am

**Comment by karsten-klein** [comment]
**ScanCode**
matched id: [w3c-software-2023](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3c-software-2023.LICENSE)

**Comment by jlovejoy** [comment]
The only differences between this license text and https://spdx.org/licenses/W3C-20150513.html are:
1) "Software and Document Short Notice" in the second clause is not capitalized
2) different copyright holder in the third clause

As to 1 - capitalization does not matter for matching, see https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b5-capitalization

As to 2 - this is also not a substantive difference in terms of the legal text and can be accommodated via markup

I would suggest we add markup to `W3C-20150513` and add the new URL and a Note explaining this.

agree?

**Comment by ThisIsMissEm** [comment]
I'd say that's up to someone at the W3C to determine. @plehegar or @timbl come to mind as far as people who might have input here. All I know is if someone were to select the W3C license when creating a github repo at present, then they would be getting the "old" license, not the current one, that's why I've opened this, to try to smooth that path a bit.

**Comment by dmitrizagidulin** [comment]
@ThisIsMissEm thanks for opening this issue btw!

**Comment by jlovejoy** [comment]
@ThisIsMissEm - let me explain a bit more: while `W3C-20150513` is the "old" license, the "new" one has not made substantive changes to be considered a different license under SPDX Matching Guidelines. This is a call by SPDX. 

Looking at this page: https://www.w3.org/copyright/software-license-2023/ , it'd be great if W3C could add along with the "status" statement at the top, to denote the SPDX id and then in the "Changes since the previous document" section, add that this change does not substantively change the license from the previous one dated 2015. 

SPDX can make a similar note in our license data.

@dmitrizagidulin - do you have any input in this regard?

**Comment by jlovejoy** [comment]
ok, I made a PR to illustrate what I mean as that might be easier to "see"!

In doing so, I noticed that the 2015 variant should have had markup in the third clause to begin with since that was always intended to be templatized for the name and URI

**Comment by ThisIsMissEm** [comment]
The thing that specifically did change between the two license versions is the copyright holder, I'd be surprised if that's not a substantial change?

In the 2023 document it is:
> Copyright © [$year-of-document] [World Wide Web Consortium](https://www.w3.org/)

In the 2015 document it is:
> Copyright © [YEAR] W3C® (MIT, ERCIM, Keio, Beihang)."

So something that is under 2015 would have a different copyright holder to the 2023 license.

**Comment by dmitrizagidulin** [comment]
+1 to what @ThisIsMissEm said, that is the main (and fairly significant) change, as it's a wholly different entity.

**Comment by jlovejoy** [comment]
@dmitrizagidulin @ThisIsMissEm - please read https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b3-substantive-text - thought I had included the link above, but in any case, this is what we are talking about regarding "substantive"

Copyright notice is generally not part of the license text itself.

Breaking down the third clause:

_Notice of any changes or modifications, through a copyright statement on the new code or document such as  "This software or document includes material copied from or derived from
[title and URI of the W3C document]._

--> The bit in brackets is presumably intended to have that info filled in, thus for purposes of matching license text to a corresponding SPDX Id, we mark this text as "replaceable" - see https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b34-guideline-replaceable-text

_Copyright © [$year-of-document] [World Wide Web Consortium](https://www.w3.org/). https://www.w3.org/copyright/software-license-2023/_
--> the year is also replaceable text, as described above. As for the name of the copyright holder, what if someone else used this license, then the copyright holder text would also need to be changed. 
Generally, we think of the entire copyright notice as replaceable for this reason, see https://spdx.github.io/spdx-spec/v2.3/license-matching-guidelines-and-templates/#b11-copyright-notice

This scenario is a bit different in the sense that the copyright notice is sort of embedded in the license, but it's still part of the required notice to refer to the original author in the case of modifications. Is the original author of this license *always* W3C (and the other copyright holders for the 2015 version)?

**Comment by plehegar** [comment]
Quick note about the OSI status. It's in progress.

**Comment by swinslow** [comment]
+1 to @jlovejoy's comments above. 

As mentioned, it looks to me that the changes between the license text at https://www.w3.org/copyright/software-license-2023/, as compared to [`W3C-20150513`](https://spdx.org/licenses/W3C-20150513.html), would be considered equivalent for SPDX matching purposes under the [SPDX matching guidelines](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-matching-guidelines-and-templates.md).

So I think adding markup to `W3C-20150513` is appropriate and would more explicitly handle the changes here. @jlovejoy has submitted #2447 for this and it looks good to me, so I'll merge it shortly. Thank you all!
