### ISSUE TITLE
LGPL-2.x(-*) templates are missing a line of text compared to the GNU-published texts, causing matching to fail

### ISSUE THREAD

**Issue by pmonks** [spdx/license-list-XML#2430]
The [LGPL-2.0 license text published by GNU](https://www.gnu.org/licenses/lgpl-2.0.txt) has, at line 102, this text:
```text
GNU LIBRARY GENERAL PUBLIC LICENSE
```
Similarly, the [LGPL-2.1 license text published by GNU](https://www.gnu.org/licenses/lgpl-2.1.txt) also has the same line of text, at line 115.

The associated SPDX templates are all missing this text, so matching against the GNU-published texts fails:
* [LGPL-2.0](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.0.xml#L154)
* [LGPL-2.0-only](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.0-only.xml#L160)
* [LGPL-2.0-or-later](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.0-or-later.xml#L146)
* [LGPL-2.1](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1.xml#L170)
* [LGPL-2.1-only](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1-only.xml#L172)
* [LGPL-2.1-or-later](https://github.com/spdx/license-list-XML/blob/main/src/LGPL-2.1-or-later.xml#L154)

**Comment by karsten-klein** [comment]
... with respect to the LGPL-2.0 license text...

**{metæffekt} Universe**
canonical name: [GNU Library General Public License 2.0](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[g]/README.md#user-content-GNU-Library-General-Public-License-2.0:~:text=GNU%20Library%20General%20Public%20License%202.0)
short name: LGPL-2.0
markers: General Terms Matches Marker, Incompatible with Secondary License Marker, No Warranty Marker, Patent Information Marker
category: LGPL
SPDX reference id: [LGPL-2.0-only](https://spdx.org/licenses/LGPL-2.0-only.html)
ScanCode reference id: [lgpl-2.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/lgpl-2.0.LICENSE)
OSI status: approved
Open CoDE status: approved
Open CoDE approved license id: LGPL-2.0-only (SPDX)

**ScanCode**
matched id: [lgpl-2.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/lgpl-2.0.LICENSE)

**Comment by pmonks** [comment]
@xsuchy yes this is a subsequent instance of the license's name, much further down in the license text. If you follow the links I provided above you'll be jumped down into the template where the text should be (but currently isn't).

**Comment by xsuchy** [comment]
Aha.
+1 to add it.

**Comment by jlovejoy** [comment]
fixed by #2440
