### ISSUE TITLE
CC-BY-3.0 template is missing a line of text compared to the Creative Commons-published texts, causing matching to fail

### ISSUE THREAD

**Issue by pmonks** [spdx/license-list-XML#2431]
The [CC-BY-3.0 license text published by Creative Commons](https://creativecommons.org/licenses/by/3.0/legalcode.txt) commences with this text:
```text
Creative Commons Legal Code
```
But the [associated SPDX template](https://github.com/spdx/license-list-XML/blob/main/src/CC-BY-3.0.xml#L12-L18) is missing this text, so matching against the Creative Commons-published text fails.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Creative Commons BY 3.0](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/README.md#user-content-Creative-Commons-BY-3.0:~:text=Creative%20Commons%20BY%203.0)
markers: Incompatible with Secondary License Marker
category: CC-BY
SPDX reference id: [CC-BY-3.0](https://spdx.org/licenses/CC-BY-3.0.html)
ScanCode reference id: [cc-by-3.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-by-3.0.LICENSE)
OSI status: pending
Open CoDE status: approved
Open CoDE approved license id: CC-BY-3.0 (SPDX)

**ScanCode**
matched id: [cc-by-3.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-by-3.0.LICENSE)

**Comment by pmonks** [comment]
@jlovejoy I did check one or two of the `CC-BY-*-4.0` license texts, and they don't have this line, so they're unaffected.  I didn't check either `CC-BY-*-1.0` or `CC-BY-*-2.0`.
