### ISSUE TITLE
Add index files

### ISSUE THREAD

**Issue by onacit** [spdx/license-list-XML#2439]
Would you please add `index.txt` file to both `/src` and `/src/exceptions` directory so that tools can use it?

e.g. `src/index.txt`

```txt
0BSD.xml
...
```

**Comment by zvr** [comment]
In general, tools should consume the data from the https://github.com/spdx/license-list-data repo, not this one.

I should note that in that directory, an index file is being automatically generated.

**Comment by xsuchy** [comment]
> so that tools can use it?

I wonder what tools you have in mind?

**Comment by onacit** [comment]
@zvr @xsuchy Thank you for your comments.
I know https://github.com/spdx/license-list-data.

I just trying to parse those XML files using Java classes generated from the XSD. :)

Thanks anyway.

**Comment by onacit** [comment]
@zvr Do we really have indices files in there?
>I should note that in that directory, an index file is being automatically generated.
