### ISSUE TITLE
New license request: HPND-UC-export-US [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mtasaka** [spdx/license-list-XML#2442]
**1.** License Name: HPND  - UC variant with US Government export warning
**2.** Short identifier: HPND-UC-export-US
**3.** License Author or steward: Copyright (C) 1985, 1990 Regents of the University of California
**4.** Comments: 
        - The license is used in magic, which is included in Fedora project: https://src.fedoraproject.org/rpms/magic
        - This license is found on re-review of magic license: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/504  
**5.** License Request Url: http://tools.spdx.org/app/license_requests/361
**6.** URL(s): https://github.com/RTimothyEdwards/magic/blob/master/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/RTimothyEdwards/magic

**Comment by xsuchy** [comment]
Text of the license:
```
Copyright (C) 1985, 1990 Regents of the University of California.

Permission to use, copy, modify, and distribute this
software and its documentation for any purpose and without
fee is hereby granted, provided that the above copyright
notice appear in all copies.  The University of California
makes no representations about the suitability of this
software for any purpose.  It is provided "as is" without
express or implied warranty.  Export of this software outside
of the United States of America may require an export license.
```

This is identical to HPND-UC except that it adds this sentence at the end:

```
Export of this software outside
of the United States of America may require an export license.
```

**Comment by richardfontana** [comment]
I should have added in the Fedora issue thread, it's not clear to me whether Fedora could/should legitimately use `HPND-UC` for this (essentially treating the final sentence as outside the license text as such), or whether SPDX should add that sentence as an optional termination of `HPND-UC`, or whether SPDX might want to create a unique identifier.

**Comment by jlovejoy** [comment]
good question @richardfontana - I mean it is sort of stating the obvious, but not sure we've had a scenario like this before. I've tagged as an item for discussion on tomorrow's call

**Comment by jlovejoy** [comment]
discussed on 4/11 call - given precedent of adding license with similar scenario of similar export text, e.g., https://spdx.org/licenses/HPND-export-US.html 
to be consistent, this would also be treated as such. 
for id: `HPND-UC-export-US`
and name: 'Historical Permission Notice and Disclaimer - University of California, US export warning`
