### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by onacit** [spdx/license-list-XML#2443]
I see `formatttedFixedTextGroup` and `formatttedAltTextGroup`.

**Comment by xsuchy** [comment]
Can you be more verbose? And elaborate what is the issue. I still have no idea what you means.

**Comment by onacit** [comment]
```
forma-ttt-ed
```
Thanks. @xsuchy

**Comment by xsuchy** [comment]
I found it; you are speaking about the typos in file `schema/ListedLicense.xsd`. I have opened PR.

**Comment by jlovejoy** [comment]
took me a minute to see that as well!

**Comment by jlovejoy** [comment]
Thanks for the catch @onacit !
