### ISSUE TITLE
CC-BY-3.0 template diverges from Creative Commons published text

### ISSUE THREAD

**Issue by pmonks** [spdx/license-list-XML#2445]
**Reproduction:**
```shell
$ ./test-one-license CC-BY-3.0
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Difference found comparing to test file: Normal text of license does not match starting at line #275 column #2 "." when comparing to template text " No term or provision of this License shall be deemed waived and no breach consented to unless such ..."
```

**Analysis:**
Section 8 of the [official license text published by Creative Commons (scroll down to line 275)](https://creativecommons.org/licenses/by/3.0/legalcode.txt) is quite different to what's [in the template](https://github.com/spdx/license-list-XML/blob/main/src/CC-BY-3.0.xml#L298-L349); subsection 8.e. in particular is completely different to that in the official CC license text.

**Comment by xsuchy** [comment]
In the origin/HEAD it is passing for me:
```
$ ./test-one-license CC-BY-3.0
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
License Creative Commons Attribution 3.0 Unported passed
$ git log |head
commit 47de8ad129134f683622e22a0ca78f3e4ba3bfe1
Merge: 02b3fcdb ba9414d2
Author: Miroslav Suchý <msuchy@redhat.com>
Date:   Thu Apr 4 09:21:44 2024 +0200

    Merge pull request #1901 from jamin-aws-ospo/non-printing-characters
    
    Non printing characters

commit 02b3fcdbf7e4917c14b87153edf1dc3ab3b688ca
```

**Comment by xsuchy** [comment]
And it is not passing after I locally merge https://github.com/spdx/license-list-XML/pull/2441

**Comment by pmonks** [comment]
> In the origin/HEAD it is passing for me:

It's passing in HEAD because the [`CC-BY-3.0` text located in the unit tests](https://github.com/spdx/license-list-XML/blob/main/test/simpleTestForGenerator/CC-BY-3.0.txt) does not match the [canonical `CC-BY-3.0` license text published by Creative Commons](https://creativecommons.org/licenses/by/3.0/legalcode.txt).

**Comment by jlovejoy** [comment]
ahh... I see. So, @xsuchy - the tests are passing b/c what we have in the XML and TXT file matches each other in this repo. But those files do NOT match what is on the Creative Commons site.  

This is a bit concerning. I will look into this more closely soon, as I might want to know how/when this happened

**Comment by pmonks** [comment]
It appears that the text across both sections 8.d and 8.e are the same, however specific sentences _within_ those sections have been moved between them (i.e. 8.d is now shorter than what had previously been captured in the test file, and 8.e is longer).

Clearly this is still an issue for matching (and the templates will still need to be updated), but perhaps from a legal perspective this means that this bug isn't as concerning as it might have been?
