### ISSUE TITLE
New license request: ruby-pty [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by voxik** [spdx/license-list-XML#2446]
**1.** License Name: Ruby pty extension license
**2.** Short identifier: ruby-pty
**3.** License Author or steward: Akinori Ito
**4.** Comments: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/503#note_1842451235
**5.** License Request Url: http://tools.spdx.org/app/license_requests/362
**6.** URL(s): https://github.com/ruby/ruby/blob/9f6deaa6888a423720b4b127b5314f0ad26cc2e6/ext/pty/pty.c#L775-L786, https://github.com/ruby/ruby/commit/0a64817fb80016030c03518fb9459f63c11605ea#diff-ef5fa30838d6d0cecad9e675cc50b24628cfe2cb277c346053fafcc36c91c204, https://github.com/ruby/ruby/commit/0a64817fb80016030c03518fb9459f63c11605ea#diff-fedf217c1ce44bda01f0a678d3ff8b198bed478754d699c527a698ad933979a0
**7.** OSI Status: 0
**8.** Example Projects: https://github.com/ruby/ruby/blob/9f6deaa6888a423720b4b127b5314f0ad26cc2e6/ext/pty/pty.c#L775-L786

**Comment by voxik** [comment]
Originally discussed for inclusion into Fedora here:

https://gitlab.com/fedora/legal/fedora-license-data/-/issues/503

**Comment by karsten-klein** [comment]
**ScanCode**
matched id: [w3m](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3m.LICENSE)

**Comments**
The w3m License has a different intro:

_Use, modification and redistribution of this software is hereby granted,-
provided that this entire copyright notice is included on any copies of
this software and applications and derivations thereof.

This software is provided on an "as is" basis, without warranty of any
kind, either expressed or implied, as to any matter including, but not
limited to warranty of fitness of purpose, or merchantability, or
results obtained from use of this software.

<img width="1000" alt="w3m-matching" src="https://github.com/spdx/license-list-XML/assets/20038021/63ec50a1-e348-4981-9450-e1a5d2036fe4">

**Comment by voxik** [comment]
> **ScanCode** matched id: [w3m](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/w3m.LICENSE)

Right.

Looking into this, what caught my attention is that the author mentioned in [SPDX](https://spdx.org/licenses/w3m) is `Akinori Ito`, who is likely the same person as the author of the `pty` Ruby library.

What is also worth of noting is that in the [original commit](https://github.com/ruby/ruby/commit/0a64817fb80016030c03518fb9459f63c11605ea), there is also [Japanese version of the license](https://github.com/ruby/ruby/commit/0a64817fb80016030c03518fb9459f63c11605ea#diff-fedf217c1ce44bda01f0a678d3ff8b198bed478754d699c527a698ad933979a0).

Also, if this is deemed that same license as `w3m`, then the `w3m` would not be probably the best identifier.

Maybe we can ask the author about the license history and evolution?

**Comment by jlovejoy** [comment]
Given the difference of "Use, modification and redistribution of this software is hereby granted, provided that ..." in `w3m` 
versus
"This software may be redistributed freely for this purpose, in full or in part, provided that..."  in this license,

I'd be in favor of adding as a new license. 

(Not sure if @karsten-klein comment above means that ScanCode "matched" this license to `w3m`, but I hope not, as that would be an incorrect match.)

As for a license name and id, I don't have a strong opinion, so would be inclined to go with @voxik suggestion.

**Comment by voxik** [comment]
> (Not sure if @karsten-klein comment above means that ScanCode "matched" this license to `w3m`, but I hope not, as that would be an incorrect match.)

Yes, ScanCode (incorrectly) matches this as `w3m`

**Comment by swinslow** [comment]
+1 to add as a new license.

For the name / ID, I think what @voxik proposed is fine too, though I might suggest capitalizing the "R" in the ID to mirror the existing [`Ruby`](https://spdx.org/licenses/Ruby.html) license on the License List. (Not a related license at all; but should probably capitalize Ruby in the same manner for both.) So:

ID: `Ruby-pty`
Name: "Ruby pty extension license"

**Comment by karsten-klein** [comment]
Please note that the scancode match score is 85.92 only with the given license text.

Form another conversation with @jlovejoy:

> ScanCode uses score metrics. That is, a license may match with an “accuracy” from 0.0 to 1.0. Please note that we do not cut off the score for the purpose of commenting ScanCode matches on SPDX issues. The match may be with a low score of, e.g., 0.35. Perhaps I should include the score when referencing to a ScanCode match.

**Comment by jlovejoy** [comment]
Thanks for the clarification/reminder @karsten-klein !

marking this as accepted!

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
Ruby pty extension license
## License ID
Ruby-pty

## XML markup
none
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
