### ISSUE TITLE
New license request: CC-PDM-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by davidfstr** [spdx/license-list-XML#2452]
**1.** License Name: Public Domain Mark 1.0 Universal
**2.** Short identifier: ~~CC-PDM~~ CC-PDM-1.0
**3.** License Author or steward: Creative Commons
**4.** Comments: 
* This deed is maintained by Creative Commons, a well-known license steward with most (all?) of its other licenses on the SPDX License List.

* This deed (Public Domain Mark 1.0 Universal) is one of the two replacements for the older deprecated Public Domain Dedication and Certification (PDDC) which is already on the SPDX license list. (The other replacement is CC0, which is also already registered on the SPDX list.)

* This deed intends to be used by TechSmart (a company I represent) to mark most of the works it is using from Project Gutenberg, which has many works whose copyright has expired in at least the United States and likely worldwide as well. Therefore I have linked below to both 1. a Project Gutenberg work and 2. TechSmart's Curriculum page to indicate its planned usage of this deed.

* The deed is reusable, intended to be used by anyone.
* The deed is stable, since its introduction circa 2010.

**5.** License Request Url: http://tools.spdx.org/app/license_requests/363
**6.** URL(s): https://creativecommons.org/publicdomain/mark/1.0/
**7.** OSI Status: Unknown
**8.** Example Projects: https://gutenberg.org/ebooks/41445, https://www.techsmart.codes/curriculum/

**Comment by davidfstr** [comment]
(Note to self: If/when this license request is approved, I can change TechSmart internal identifiers for this license from "LicenseRef-CC-PDM" to just "CC-PDM", or whatever the final identifier is.)

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Creative Commons Public Domain Mark 1.0](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[c]/README.md#user-content-Creative-Commons-Public-Domain-Mark-1.0:~:text=Creative%20Commons%20Public%20Domain%20Mark%201.0)
short name: CC-PDM-1.0
category: CC-PDM
ScanCode reference id: [cc-pdm-1.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-pdm-1.0.LICENSE)
OSI status: _none_

**ScanCode**
matched id: [cc-pdm-1.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-pdm-1.0.LICENSE)

**Comment**
+1 to add. Since the information source already carries a version, I would include the version in the id: CC-PDM-1.0

**Comment by davidfstr** [comment]
> I would include the version in the id: CC-PDM-1.0

Agreed. I see that the other Creative Commons licenses generally include the version number, even for 1.0 license versions.

Followups:
* ✅ I'll update the requested "Short identifier" in the opening post to this thread.
* 👉 There may be additional work to **update the identifier in the XML** which the SPDX-Online-Tools may have already generated. I do not know how to update that.

**Comment by jlovejoy** [comment]
Given we have all the other CC licenses and public domain dedications, I'm inclined to add, but I'm a bit confused on a couple things:
1) is it the text within the box at https://creativecommons.org/publicdomain/mark/1.0/deed.en that is considered the text of the dedication? (this is different "formatting" than some of the other CC licenses/deeds I've seen)
2) @davidfstr - can you point to an exact place/file/content where this is used? The websites you included are general and I don't really see a use of the text "in the wild"

thanks!

**Comment by jlovejoy** [comment]
ok, I think @karsten-klein already answered my first question, actually. and he already gave a thumbs up to including. I'd still be nice to see any example of actual use though!

I'm going to mark as accepted and leave the waiting for submitter label as well, as a reminder of both

**Comment by davidfstr** [comment]
> 1. is it the text within the box at https://creativecommons.org/publicdomain/mark/1.0/deed.en that is considered the text of the dedication? (this is different "formatting" than some of the other CC licenses/deeds I've seen)

Yes, I transcribed the text within the box on that page to Markdown format. I left off bold formatting.

However it looks like I also left off the **footnotes**, which could be important. If the links were included you'd also see the following at the bottom of the transcribed document and some extra references in the main text like `[^1]`:

```
[^1]: jurisdictions - Copyright terms vary jurisdiction to jurisdiction. A work free of copyright restrictions in one jurisdiction may not be similarly free in other jurisdictions.

[^2]: publicity or privacy - The use of a work free of known copyright restrictions may be otherwise regulated or limited. The work or its use may be subject to personal data protection laws, publicity, image, or privacy rights that allow a person to control how their voice, image or likeness is used, or other restrictions or limitations under applicable law.

[^3]: moral rights - Copyright laws in most jurisdictions around the world grant creators "moral rights" which may provide some redress if use of a work is considered "derogatory".

[^4]: endorsement - In some jurisdictions, wrongfully implying that an author, publisher or anyone else endorses your use of a work may be unlawful.
```

> 2. @davidfstr - can you point to an exact place/file/content where this is used?

Internal license data at TechSmart currently uses the transcribed text. I haven't identified any public places where any variation of the deed is used; I've only seen the mark's name used ("CC PDM 1.0").

**Comment by jlovejoy** [comment]
@davidfstr - by "internal license data" - does that mean that TechSmart is not using the dedication on an actual work (yet)?'

A couple examples in Github I found:
- https://github.com/TindakMalaysia/HISTORICAL-ELECTION-RESULTS/blob/main/1955-ELECTION-RESULTS/Licence
- https://github.com/cafkafk/rime/blob/3a1a41e89b1a7f2f15451209df734c5ca28ca432/LICENSES/LicenseRef-CC-PDM-1.0-DEED.txt#L4

**Comment by davidfstr** [comment]
> does that mean that TechSmart is not using the dedication on an actual work (yet)?

The asset-to-license metadata association is tracked but the deed isn't yet automatically added to any coding projects that are exported.
