### ISSUE TITLE
is LibPNG OSI Approved?

### ISSUE THREAD

**Issue by mlorenzoitx** [spdx/license-list-XML#2456]
Reading  [LibPNG](https://github.com/spdx/license-list-XML/blob/main/src/Libpng.xml) license XML  

 I found that value isOsiApproved="false"
https://github.com/spdx/license-list-XML/blob/2730e348675d2f540f7d543e1b0c1eb4edf7493b/src/Libpng.xml#L3

but in the license text it says that it's certified
https://github.com/spdx/license-list-XML/blob/2730e348675d2f540f7d543e1b0c1eb4edf7493b/src/Libpng.xml#L94

Approbation and Certification have the same meaning?, if no.  What's the difference?

**Comment by swinslow** [comment]
Hi @mlorenzoitx,

Looking at [OSI's list of licenses](https://opensource.org/licenses), I don't see any that match the [`Libpng` SPDX identifier](https://spdx.org/licenses/Libpng.html).

OSI does list [`Zlib`](https://spdx.org/licenses/Zlib.html) as ["The zlib/libpng License"](https://opensource.org/license/zlib), though when I look at its text, it is substantively different from the Libpng license you linked to above

So I don't see anything here indicating that OSI has approved what SPDX calls the [`Libpng` license](https://spdx.org/licenses/Libpng.html).

**Comment by jlovejoy** [comment]
Hi @mlorenzoitx - to add to @swinslow comments: https://opensource.org/license/zlib and https://spdx.org/licenses/Zlib.html are a match.

The license you see as https://spdx.org/licenses/Libpng.html was not submitted to OSI, thus not approved. 

See for the details (me asking your same question back in 2013!!) - scroll down to isssue 4 at https://lists.spdx.org/g/Spdx-legal/message/535

I'm going to close this shortly, as I don't think there is any action on this?
