### ISSUE TITLE
New license request: HPND [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by cranderson** [spdx/license-list-XML#2460]
**1.** License Name: HPND
**2.** Short identifier: HPND
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in the Fedora package koules-1.4 copyright.h and in the old source code for the Netrek Paradise client.2.3p19 paradise.sndsrv.linux.c.  It is a slight variation of the HPND license with these differences from the HPND template shown in https://docs.google.com/document/d/1xqSwTfJJ7btkhbblrIAZxOxv0iZPmAMGar9rU7DLKC8/edit as referred from https://github.com/spdx/license-list-XML/blob/main/DOCS/license-match.md :

This variant has removed a comma [,] after the text "copyright notice <appear|appears> in all copies".

This variant has changed the wording from "<copyright holder> makes no representations" to "No representations are made".

See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/509 for the Fedora issue.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/367
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: http://www.ucw.cz/~hubicka/koules/packages/koules1.4-src.tar.gz, http://ftp.netrek.org/pub/paradise/OLD/client/client.2.3p19.tar.gz

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Permission Terms (Nettrek)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-(Nettrek):~:text=Permission%20Terms%20(Nettrek))
short name: PT-Nettrek
markers: No Warranty Marker
category: Permission
OSI status: _none_

**Comment**
The HPND as defined in https://spdx.org/licenses/HPND.html is significantly "optionalized". I wonder how jar we want to go covering further variants. Undecided so far. We probably keep matching this as separate Permission Terms (Nettrek).

**Comment by cranderson** [comment]
Netrek is apparently spelled with one 't': https://netrek.org/

**Comment by karsten-klein** [comment]
Fixed. Thanks for the hint. I think I definitely need to wear my glasses permanently by now ;)

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Permission Terms (Netrek)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-(Netrek):~:text=Permission%20Terms%20(Netrek))
short name: PT-Netrek
markers: No Warranty Marker
category: Permission
OSI status: _none_

**Comment by jlovejoy** [comment]
license text for convenience:

```
Copyright (C) 1995 S. M. Patel (smpatel@wam.umd.edu)

   Permission to use, copy, modify, and distribute this
   software and its documentation for any purpose and without
   fee is hereby granted, provided that the above copyright
   notice appear in all copies and that both that copyright
   notice and this permission notice appear in supporting
   documentation.  No representations are made about the
   suitability of this software for any purpose.  It is
   provided "as is" without express or implied warranty.
```

**Comment by jlovejoy** [comment]
@cranderson is right as to the differences. Note that the section of:
`[<copyright holder> makes no representations about the suitability of this software for any purpose.  
<It|This software> is provided "as is" without express or implied warranty.]`
is optional altogether, so this would mean adding markup to this optional part.

**Comment by richardfontana** [comment]
IMO anything that doesn't seem to fit in the OSI's template for HPND shouldn't be covered under SPDX `HPND`, because otherwise licenses that have not been OSI-approved could be seen as having been OSI approved. (Alternatively and maybe not so unrealistically, SPDX could work with OSI to revise OSI HPND to embrace all the many HPND variants that have been found in recent years.)

**Comment by jlovejoy** [comment]
discussed on 7/25 legal call: should be its own license b/c passive voice the representation is broader. Add as new license with `HPND-Netrek`
