### ISSUE TITLE
BSD-3-Clause variant in Antlr4

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2461]
Antlr4 has the following clause 3:

```
3. Neither name of copyright holders nor the names of its contributors
may be used to endorse or promote products derived from this software
without specific prior written permission.
```
https://github.com/antlr/antlr4/blob/dev/LICENSE.txt#L14C1-L16C43

I believe this would require a change to the markup for BSD-3-Clause.xml.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [BSD 3-Clause License (copyright holder variant)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[b]/README.md#user-content-BSD-3-Clause-License-(copyright-holder-variant):~:text=BSD%203%2DClause%20License%20(copyright%20holder%20variant))
short name: BSD-3-Clause-copyright-holder
markers: Do Not Promote Marker, General Terms Matches Marker
category: BSD
OSI status: <none>

**ScanCode**
matched id: [bsd-new](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-new.LICENSE)

**Comment**
+1 to change BSD-3-Clause markup to include the case.

**Comment by jlovejoy** [comment]
discussed on 7/25 call - add markup (missing "the")
