### ISSUE TITLE
New license request: HIDAPI [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by davide125** [spdx/license-list-XML#2471]
**1.** License Name: HIDAPI
**2.** Short identifier: HIDAPI
**3.** License Author or steward: Alan Ott, Signal 11 Software
**4.** Comments: This license is used in Fedora and was found during license review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/513
**5.** License Request Url: http://tools.spdx.org/app/license_requests/368
**6.** URL(s): https://github.com/signal11/hidapi/blob/master/LICENSE-orig.txt
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/signal11/hidapi

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [HIDAPI License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[h]/README.md#user-content-HIDAPI-License:~:text=HIDAPI%20License)
short name: HIDAPI
category: HIDAPI License
ScanCode reference id: [hidapi](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/hidapi.LICENSE)
OSI status: _none_
Open CoDE status: approved
Open CoDE approved license id: hidapi (ScanCode)

**ScanCode**
matched id: [hidapi](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/hidapi.LICENSE)

**Comment**
+1 to add.

**Comment by Pizza-Ria** [comment]
Struggling with this.  The code that brought us this license can be licensed under GPLv3, BSD or Hidapi. So, there are other options. If this is the ONLY component that uses this license (even if that component is in Fedora) and it can be licensed under either of the other two more common licenses, does this one need to be ID'ed as well?  Seems like a hybrid of https://spdx.org/licenses/softSurfer.html and https://spdx.org/licenses/TermReadKey.html but I'll admit that the language is different.

**Comment by jlovejoy** [comment]
it is close in spirit to softSurfer and TermReadKey, but just different enough... 

@Pizza-Ria - I don't think the license choice is really a factor for our inclusion principles (but I get where you are coming from in a pragmatic sense ;)

the license expression for this project would be: `GPL-3.0-or-later OR BSD-3-Clause or LicenseRef-Hidapi` 

As much as it does sort of pain me, we probably should add it...

**Comment by davide125** [comment]
Speaking as a Fedora packager, I think this should be added so we can accurately represent the license expression for this package. Note that Fedora [explicitly discourages](https://docs.fedoraproject.org/en-US/legal/license-field/#_no_effective_license_analysis) packagers from performing effective license analysis, so we don't really have much of a choice besides listing the full expression.
