### ISSUE TITLE
HTTP(S) URL in MPL-2.0

### ISSUE THREAD

**Issue by leoheitmannruiz** [spdx/license-list-XML#2497]
Hey, I'm a little confused..

Why is it that a HTTP URL in the license-list-XML repo 
https://github.com/spdx/license-list-XML/blob/58b86f8023595eb2fad8587f70978dd1725a0cc4/src/MPL-2.0.xml#L462

turns into a HTTPS URL in the license-list-data repo in a few formats (like text and json)
https://github.com/spdx/license-list-data/blob/ddf4c0fe8ec024714fb97812abc378eb9a4d83be/text/MPL-2.0.txt#L360

but stays HTTP in other formats (such as HTML)
https://github.com/spdx/license-list-data/blob/ddf4c0fe8ec024714fb97812abc378eb9a4d83be/html/MPL-2.0.html#L575

**Comment by xsuchy** [comment]
https://github.com/spdx/license-list-XML/pull/2498 was merged.

**Comment by goneall** [comment]
The utility used to publish the license list data is the [LicenseListPublisher](https://github.com/spdx/licenselistpublisher).

I have not looked into this behavior, but I agree it should not be adding characters to the URLs for some of the formats.

Feel free to open an issue.  It may be a while before I can look at it myself, but if others have bandwidth, pull requests would be welcome.
