### ISSUE TITLE
Revise ulem markup to accommodate 'framed' variant

### ISSUE THREAD

**Issue by richardfontana** [spdx/license-list-XML#2499]
SPDX [added the identifier `ulem`](https://github.com/spdx/license-list-XML/issues/2088) to cover certain licenses found in the TeXLive distribution. The CentOS Stream/RHEL maintainer of TeXLive became aware of the following license, found in `framed`, one of the many packages making up TeXLive (included in Fedora as well as CentOS Stream/RHEL):
```
% Copyright (C) 1992-2011 by Donald Arseneau  (asnd@triumf.ca)
% These macros may be freely transmitted, reproduced, or modified
% for any purpose provided that this notice is left intact.
```
This differs from `ulem` only slightly:
```
This software may be freely transmitted, reproduced, or modified
for any purpose provided that this copyright notice is left intact.
```
Presumably `ulem` can be revised to accommodate this variant. 

Because the maintainer had a pressing need to use a Fedora-allowed license identifier, Fedora [added](https://gitlab.com/fedora/legal/fedora-license-data/-/commit/8afed9342e862693727680d02c64119d962b8883) `LicenseRef-framed` to cover this variant.

**Comment by richardfontana** [comment]
Upstream `framed` package on CTAN: https://ctan.org/tex-archive/macros/latex/contrib/framed (license text found in the file `framed.sty`).

**Comment by swinslow** [comment]
Looks like the two changes here are:

1. "This software" => "These macros"
2. "notice" => "copyright notice"

I'm fine with adding markup to `ulem` to accommodate these.

**Comment by swinslow** [comment]
@richardfontana I think #2501 should accommodate this change, assuming there's another +1 to approve it. Let me know if you have any concerns with that PR.
