### ISSUE TITLE
New license request: agpl-3.0-linking-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by capfei** [spdx/license-list-XML#2502]
**1.** License Name: AGPL-3.0 Linking Exception
**2.** Short identifier: agpl-3.0-linking-exception
**3.** License Author or steward: Unknown
**4.** Comments: I came across this linking exception for AGPL 3.0. It reads similar to the GPL 3.0 linking exception and seems used enough for inclusion consideration.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/373
**6.** URL(s): https://web.archive.org/web/20210124015834/http://mo.morsi.org/blog/2009/08/13/lesser_affero_gplv3/
**7.** OSI Status: Approved
**8.** Example Projects: https://github.com/moll/node-mitm/blob/bbf24b8bd7596dc6e091e625363161ce91984fc7/LICENSE#L8-L11, https://github.com/zenbones/SmallMind/blob/3c62b5995fe7f27c453f140ff9b60560a0893f2a/COPYRIGHT#L25-L30, https://github.com/savearray2/py.js/blob/b781273c08c8afa89f4954de4ecf42ec01429bae/README.md#license, https://github.com/CubeArtisan/cubeartisan/blob/2c6ab53455237b88a3ea07be02a838a135c4ab79/LICENSE.LESSER#L10-L15

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Linking Exception (AGPL)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[l]/README.md#user-content-Linking-Exception-(AGPL):~:text=Linking%20Exception%20(AGPL))
short name: Linking-Exception-AGPL
category: AGPL Linking Exception
ScanCode reference id: [linking-exception-agpl-3.0](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/linking-exception-agpl-3.0.LICENSE)

*Comment*
+1 as general AGPL linking exception.

**Comment by richardfontana** [comment]
My only concern here is the name/id. Surely there are going to be other, different AGPL linking exceptions, and this one (which I have the dubious distinction of having authored many years ago) isn't particularly worth elevating as a good example of an AGPL linking exception. 😄

**Comment by jlovejoy** [comment]
@richardfontana - sounds like you are in favor of adding, but would like a different name and id. Do you have something in mind?

I am also +1 to add this

**Comment by capfei** [comment]
Maybe LAPGL or lesser-agpl-3.0-exception?

**Comment by richardfontana** [comment]
That's probably not ideal either because there have been perennial calls to create or ask the FSF to create/bless a "Lesser AGPL" by that name.

**Comment by capfei** [comment]
There are a couple of exceptions that use "generic" in the name. Would going that route be preferrable?

- agpl-3.0-exception
- agpl-3.0-generic-exception
- agpl-3.0-generic-linking-exception

**Comment by richardfontana** [comment]
The concern I have is basically that there could be a number of different AGPL-specific linking exceptions. I'd personally be inclined to use something that references Mo Morsi (if he was indeed the first to use this exception, as I believe is the case) or the project he originally used this exception with, but I couldn't figure out the latter. Like:
`AGPL-3.0-or-later WITH Morsi-exception`

**Comment by capfei** [comment]
The earliest I can find is August 2009, https://sourceforge.net/p/romic/code/ci/master/tree/. An [archive of his old projects site](https://web.archive.org/web/20100117041946/http://projects.morsi.org/wiki/Main_Page) lists another project, that has a similarly named linking exception, Manic, but I cannot find a copy anywhere to verify the text.

I will spend another day looking around to see if I can find any older uses of this exception. If I can't, then I am fine with updating this to `Morsi-exception` since it seems like he used it, presumably, on at least two projects.

**Comment by richardfontana** [comment]
Romic, that rings a bell. Wow, that was so long ago he was using Sourceforge :) 
So if it were me, I might use "romic-exception" but I tend to like quirky names like that.

**Comment by capfei** [comment]
I didn't find anything older so I updated my PR to `Romic Exception` as the title and `romic-exception` as the file name. I also added the link to the sourceforge project.

Thank you for all of the feedback and suggestions!
