### ISSUE TITLE
New license request: Alhmzigroups [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by alhmzicompany** [spdx/license-list-XML#2503]
**1.** License Name: Alhmzi group
**2.** Short identifier: Alhmzigroups
**3.** License Author or steward: 
**4.** Comments: رخصة أباتشي
                           الإصدار 2.0، يناير 2004
                        http://www.apache.org/licenses/

   شروط وأحكام الاستخدام والنسخ والتوزيع

   1. تعاريف.

      "الترخيص" يعني شروط وأحكام الاستخدام وإعادة الإنتاج
      والتوزيع كما هو محدد في الأقسام من 1 إلى 9 من هذه الوثيقة.

      "المرخص" يعني مالك حقوق الطبع والنشر أو الكيان المرخص له من قبل
      مالك حقوق الطبع والنشر الذي يمنح الترخيص.

      "الكيان القانوني" يعني اتحاد الكيان القائم بالنيابة وجميع
      الكيانات الأخرى التي تتحكم فيها أو تخضع لسيطرتها أو تخضع لسيطرتها المشتركة
      السيطرة مع هذا الكيان. ولأغراض هذا التعريف،
      "السيطرة" تعني (أ) القدرة، المباشرة أو غير المباشرة، على التسبب في
      التوجيه أو إدارة مثل هذا الكيان، سواء عن طريق العقد أو
      خلاف ذلك، أو (2) ملكية خمسين بالمائة (50%) أو أكثر من
      الأسهم القائمة، أو (3) الملكية المفيدة لهذا الكيان.

      "أنت" (أو "خاصتك") تعني فردًا أو كيانًا قانونيًا
      ممارسة الأذونات الممنوحة بموجب هذا الترخيص.

      "نموذج "المصدر" يعني النموذج المفضل لإجراء التعديلات،
      بما في ذلك على سبيل المثال لا الحصر، كود مصدر البرنامج والوثائق
      ملفات المصدر والتكوين.

      يقصد بصيغة "الكائن" أي شكل ناتج عن ميكانيكية
      تحويل أو ترجمة نموذج المصدر، بما في ذلك على سبيل المثال لا الحصر
      لا يقتصر على كود الكائن المترجم، والوثائق التي تم إنشاؤها،
      والتحويلات إلى أنواع أخرى من الوسائط.

      "المصنف" يقصد به عمل التأليف سواء في المصدر أو
      نموذج الكائن، المتوفر بموجب الترخيص، كما هو موضح بواسطة أ
      إشعار حقوق الطبع والنشر المضمن في العمل أو المرفق به
      (يتم توفير مثال في الملحق أدناه).

      "الأعمال المشتقة" تعني أي عمل، سواء في المصدر أو الكائن
      النموذج الذي يعتمد على (أو مشتق من) العمل والذي من أجله
      المراجعات التحريرية أو الشروح أو التوضيحات أو التعديلات الأخرى
      تمثل، ككل، عملاً أصليًا للتأليف. من أجل غايات
      في هذا الترخيص، يجب ألا تتضمن الأعمال المشتقة الأعمال المتبقية
      يمكن فصلها عن واجهات، أو ربطها فقط (أو ربطها بالاسم)،
      الأعمال والمشتقات منها.

      "المساهمة" تعني أي عمل مؤلف، بما في ذلك
      النسخة الأصلية للعمل وأي تعديلات أو إضافات
      إلى هذا العمل أو الأعمال المشتقة منه، والتي يتم عمدًا
      تم تقديمه إلى المرخص له ليتم تضمينه في العمل بواسطة مالك حقوق النشر
      أو من قبل فرد أو كيان قانوني مخول بالتقديم نيابة عن
      مالك حقوق الطبع والنشر. ولأغراض هذا التعريف، "المقدم"
      يعني أي شكل من أشكال الاتصالات الإلكترونية أو الشفهية أو المكتوبة المرسلة
      إلى المرخص أو ممثليه، بما في ذلك على سبيل المثال لا الحصر
      التواصل عبر قوائم البريد الإلكتروني، وأنظمة التحكم في الكود المصدر،
      وإصدار أنظمة التتبع التي يتم إدارتها من قبل، أو نيابة عن،
      المرخص لغرض مناقشة العمل وتحسينه، ولكن
      باستثناء الاتصالات التي تم تمييزها بشكل واضح أو غير ذلك
      تم تحديدها كتابيًا بواسطة مالك حقوق الطبع والنشر على أنها "ليست مساهمة".

      "المساهم" يعني المرخص وأي فرد أو كيان قانوني
      بالنيابة عنه تم استلام المساهمة من قبل المرخص و
      تم دمجها لاحقًا ضمن العمل.

   2. منح ترخيص حقوق الطبع والنشر. وفقًا للشروط والأحكام الخاصة بـ
      هذا الترخيص، ويمنحك كل مساهم بموجب هذا ترخيصًا دائمًا،
      عالمي، غير حصري، بدون رسوم، خالٍ من حقوق الملكية، غير قابل للإلغاء
      ترخيص حقوق الطبع والنشر لإعادة إنتاج الأعمال المشتقة وإعدادها،
      العرض العلني والأداء العلني والترخيص من الباطن والتوزيع
      العمل والأعمال المشتقة منه في شكل مصدر أو موضوع.

   3. منح ترخيص براءة الاختراع. مع مراعاة الشروط والأحكام
      هذا الترخيص، ويمنحك كل مساهم بموجب هذا ترخيصًا دائمًا،
      عالمي، غير حصري، بدون رسوم، خالٍ من حقوق الملكية، غير قابل للإلغاء
      (باستثناء ما هو مذكور في هذا القسم) ترخيص براءة اختراع لصنع، صنع،
      استخدام وعرض بيع واستيراد ونقل العمل بطريقة أخرى،
      حيث ينطبق هذا الترخيص فقط على مطالبات براءات الاختراع القابلة للترخيص
      من قبل هذا المساهم والتي تنتهك بالضرورة حقوقهم
      المساهمة (المساهمات) وحدها أو عن طريق الجمع بين مساهماتها
      مع العمل الذي تم تقديم هذه المساهمة إليه. إذا كنت
      رفع دعوى براءات اختراع ضد أي كيان (بما في ذلك
      دعوى متبادلة أو دعوى مضادة في دعوى قضائية) تزعم أن العمل
      أو المساهمة المضمنة في العمل تشكل مساهمة مباشرة
      أو انتهاك براءات الاختراع المساهمة، ثم أي تراخيص براءات الاختراع
      سيتم إنهاء الترخيص الممنوح لك بموجب هذا العمل
      من تاريخ رفع هذه الدعوى.

   4. إعادة التوزيع. يجوز لك إعادة إنتاج وتوزيع نسخ من
      العمل أو الأعمال المشتقة منه بأي وسيلة، مع أو بدون
      التعديلات، وفي شكل المصدر أو الكائن، بشرط أن
      تلبية الشروط التالية:

      (أ) يجب عليك إعطاء أي مستلمين آخرين للعمل أو
          الأعمال المشتقة نسخة من هذا الترخيص؛ و

      (ب) يجب عليك أن تجعل أي ملفات معدلة تحمل إشعارات بارزة
          صرحت بأنك قمت بتغيير الملفات؛ و

      (ج) يجب عليك الاحتفاظ، في النموذج المصدر، بأي أعمال مشتقة
          التي تقوم بتوزيعها، وجميع حقوق الطبع والنشر وبراءات الاختراع والعلامات التجارية و
          إشعارات الإسناد من نموذج المصدر للعمل،
          باستثناء تلك الإشعارات التي لا تتعلق بأي جزء من
          الأعمال المشتقة؛ و

      (د) إذا كان العمل يشتمل على ملف نصي "إشعار" كجزء منه
          التوزيع، فيجب أن تكون أي أعمال مشتقة تقوم بتوزيعها
          تتضمن نسخة قابلة للقراءة من إشعارات الإسناد الواردة
          ضمن ملف الإشعار هذا، باستثناء تلك الإشعارات التي لا
          تتعلق بأي جزء من الأعمال المشتقة، في واحدة على الأقل
          من الأماكن التالية: ضمن ملف نصي إشعار موزعة
          كجزء من الأعمال المشتقة؛ ضمن نموذج المصدر أو
          الوثائق، إذا تم تقديمها مع الأعمال المشتقة؛ أو،
          ضمن عرض تم إنشاؤه بواسطة الأعمال المشتقة، إذا و
          أينما تظهر إشعارات الطرف الثالث عادةً. محتويات
          من ملف الإشعار هي لأغراض إعلامية فقط و
          لا تقم بتعديل الترخيص. يمكنك إضافة نسبك الخاصة
          الإشعارات ضمن الأعمال المشتقة التي تقوم بتوزيعها، جنبًا إلى جنب
          أو كملحق لنص الإشعار من العمل، بشرط
          أن إشعارات الإسناد الإضافية هذه لا يمكن تفسيرها
          كتعديل الترخيص.

      يمكنك إضافة بيان حقوق النشر الخاص بك إلى تعديلاتك و
      قد توفر شروط وأحكام ترخيص إضافية أو مختلفة
      لاستخدام تعديلاتك أو إعادة إنتاجها أو توزيعها، أو
      لأي من هذه الأعمال المشتقة ككل، شريطة استخدامك،
      إعادة إنتاج وتوزيع العمل يتوافق مع
      الشروط المنصوص عليها في هذا الترخيص.

   5. تقديم المساهمات. ما لم تنص صراحةً على خلاف ذلك،
      أي مساهمة تم تقديمها عمدًا للتضمين في العمل
      بواسطتك إلى المرخص يجب أن يكون بموجب الشروط والأحكام
      هذا الترخيص، دون أي شروط أو أحكام إضافية.
      على الرغم مما ورد أعلاه، لا يحل أي شيء هنا محل أو يعدل
      شروط أي اتفاقية ترخيص منفصلة قد تكون قمت بتنفيذها
      مع المُرخص له فيما يتعلق بهذه المساهمات.

   6. العلامات التجارية. لا يمنح هذا الترخيص الإذن باستخدام العلامات التجارية
      الأسماء أو العلامات التجارية أو علامات الخدمة أو أسماء المنتجات الخاصة بالمرخص له،
      باستثناء ما هو مطلوب للاستخدام المعقول والمألوف في وصف
      أصل العمل وإعادة إنتاج محتوى ملف الإشعار.

   7. إخلاء المسؤولية عن الضمان. ما لم يكن ذلك مطلوبًا بموجب القانون المعمول به أو
      تمت الموافقة عليه كتابيًا، ويقدم المرخص العمل (وكل
      يقدم المساهم مساهماته) على أساس "كما هي"،
      بدون ضمانات أو شروط من أي نوع، سواء كانت صريحة أو ضمنية
      ضمنيًا، بما في ذلك، على سبيل المثال لا الحصر، أي ضمانات أو شروط
      الملكية، وعدم الانتهاك، وقابلية التسويق، أو الملاءمة لـ
      غرض خاص. أنت المسؤول الوحيد عن تحديد
      ملاءمة استخدام العمل أو إعادة توزيعه وتحمل أي
      المخاطر المرتبطة بممارستك للأذونات بموجب هذا الترخيص.

   8. حدود المسؤولية. في أي حال من الأحوال وتحت أي نظرية قانونية،
      سواء في الضرر (بما في ذلك الإهمال)، أو العقد، أو غير ذلك،
      ما لم يكن ذلك مطلوبًا بموجب القانون المعمول به (مثل القتل المتعمد والفادح)
      (أفعال إهمالية) أو تم الاتفاق عليها كتابيًا، هل يجب على أي مساهم أن يتحمل المسؤولية؟
      مسؤول تجاهك عن الأضرار، بما في ذلك أي أضرار مباشرة أو غير مباشرة أو خاصة أو
      الأضرار العرضية أو التبعية من أي نوع والتي تنشأ نتيجة
      نتيجة لهذا الترخيص أو الخروج من الاستخدام أو عدم القدرة على استخدام
      العمل (بما في ذلك على سبيل المثال لا الحصر، الأضرار الناجمة عن فقدان السمعة الطيبة،
      التوقف عن العمل، أو فشل الكمبيوتر أو عطله، أو أي شيء من هذا القبيل
      الأضرار أو الخسائر التجارية الأخرى، حتى لو كان هذا المساهم
      وقد تم إخطاره بإمكانية حدوث مثل هذه الأضرار.

   9. قبول الضمان أو المسؤولية الإضافية. أثناء إعادة التوزيع
      العمل أو الأعمال المشتقة منه، يمكنك اختيار عرضه،
      وفرض رسوم مقابل قبول الدعم والضمان والتعويض،
      أو التزامات المسؤولية الأخرى و/أو الحقوق المتوافقة مع هذا
      رخصة. ومع ذلك، عند قبول هذه الالتزامات، يجوز لك التصرف فقط
      بالنيابة عنك وعلى مسؤوليتك الخاصة، وليس بالنيابة عن
      لأي مساهم آخر، وفقط إذا وافقت على التعويض،
      الدفاع عن كل مساهم وإعفاءه من أي مسؤولية
      التي تكبدها هذا المساهم أو المطالبات التي تم رفعها ضده بسبب
      من قبولك لأي ضمان أو مسؤولية إضافية.

   نهاية الشروط والأحكام

   الملحق: كيفية تطبيق ترخيص Apache على عملك.

      لتطبيق ترخيص Apache على عملك، قم بإرفاق ما يلي
      إشعار نموذجي، مع الحقول المحاطة بين قوسين "[]"
      واستبدالها بمعلومات التعريف الخاصة بك. (لا تشمل
      بين قوسين!) يجب أن يوضع النص في المكان المناسب
      بناء جملة التعليق لتنسيق الملف. كما نوصي أ
      يجب تضمين اسم الملف أو الفئة ووصف الغرض منه في
      نفس "الصفحة المطبوعة" مثل إشعار حقوق النشر لتسهيل
      تحديد الهوية داخل أرشيفات الطرف الثالث.

   حقوق الطبع والنشر [yyyy] [اسم مالك حقوق الطبع والنشر]

   مرخص بموجب ترخيص Apache، الإصدار 2.0 ("الترخيص")؛
   لا يجوز لك استخدام هذا الملف إلا وفقًا للترخيص.
   يمكنك الحصول على نسخة من الترخيص على

       http://www.apache.org/licenses/LICENSE-2.0

   ما لم يكن ذلك مطلوبًا بموجب القانون المعمول به أو تم الاتفاق عليه كتابيًا، البرمجيات
   الموزعة بموجب الترخيص يتم توزيعها على أساس "كما هي"،
   دون ضمانات أو شروط من أي نوع، سواء كانت صريحة أو ضمنية.
   راجع الترخيص لمعرفة الأذونات التي تحكم اللغة المحددة و
   القيود بموجب الترخيص.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/374
**6.** URL(s): http://www.apache.org/licenses/LICENSE-2.0
**7.** OSI Status: Approved
**8.** Example Projects: http://www.apache.org/licenses/LICENSE-2.0

**Comment by alhmzicompany** [comment]
Alhmzi groups

**Comment by xsuchy** [comment]
This is apache license that we already have on list. No other comments why it should be included and weather it meet requirements.
Closing as a spam.
