### ISSUE TITLE
Markup change of Boehm-GC

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2507]
During Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/530 we discovered  in
mariadb10.11
https://github.com/MariaDB/server/blob/11.6/libmysqld/lib_sql.cc

a license that has the wording:

```
This material is provided "as is", with absolutely no warranty expressed
or implied. Any use is at your own risk.

Permission to use or copy this software for any purpose is hereby
granted without fee, provided the above notices are retained on all
copies.

Permission to modify the code and to distribute modified code is
granted, provided the above notices are retained, and a notice that
the code was modified is included with the above copyright notice.
```

This is very close to Boehm-GC.
I will file a PR with markup change proposal where it will be more visible what needs to be changed.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [STLport License 4.5](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[s]/README.md#user-content-STLport-License-4.5:~:text=STLport%20License%204.5)
short name: STLport-4.5
category: STLport License
ScanCode reference id: [stlport-4.5](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/stlport-4.5.LICENSE)
OSI status: _none_
Open CoDE status: approved
Open CoDE approved license id: stlport-4.5 (ScanCode)

**ScanCode**
matched id: [stlport-4.5](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/stlport-4.5.LICENSE)

**Comment**
I'm not fully aware of the history at scancode. +1 to add dur to harmonization considerations.

**Comment by jlovejoy** [comment]
copying the license texts here b/c I'm having a hard time "seeing" in the PR!

`This material is provided "as is", with absolutely no warranty expressed
or implied. Any use is at your own risk.`
--> this is the same, other than not being in all caps and use of quotes around "as is"

`Permission to use or copy this software for any purpose is hereby granted without fee, `
--> versus "Permission is hereby granted to use or copy this program for any purpose" - so reverse order for the grant, but this version adds "without fee"

`provided the above notices are retained on all copies.`
--> same

`Permission to modify the code and to distribute modified code is granted, provided the above notices are retained, and a notice that the code was modified is included with the above copyright notice.`
--> also looks the same

so I guess the question is: does "without fee" make for enough of a difference?

**Comment by jlovejoy** [comment]
@swinslow @richardfontana @copernicat @Pizza-Ria  - thoughts? 

I am thinking that we have treated this as different in the past

**Comment by richardfontana** [comment]
I wasn't paying close attention to this. I can certainly think of legacy licenses with varying treatment of "without fee" that I think SPDX would consider/has considered substantively distinct. That could be based on the precise placement of "without fee" in a sentence, or inclusion in the phrase "with or without fee". So my immediate reaction is that it's hard to see why two licenses that are identical except that one adds "without fee" would be treated as substantively equivalent.

**Comment by jlovejoy** [comment]
@richardfontana - I agree. In which case, I think we need to switch this to being a new license submission. 

@xsuchy - do you want to submit via SPDX Online Tool, and then I'll close this issue?

**Comment by xsuchy** [comment]
Closing in the favor of https://github.com/spdx/license-list-XML/issues/2512
