### ISSUE TITLE
New license request: DocBook-Schema [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Lupphes** [spdx/license-list-XML#2516]
**1.** License Name: DocBook Schema License
**2.** Short identifier: DocBook-Schema
**3.** License Author or steward: Unknown
**4.** Comments: This license is used in Fedora and was found during license review and backlink to this issue. It is used for docbook5-schema and docbook5-style-xsl.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/378
**6.** URL(s): https://gitlab.com/fedora/legal/fedora-license-data/-/issues/525
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/docbook/xslt10-stylesheets, http://www.oasis-open.org/docbook/

**Comment by jlovejoy** [comment]
+1 to add, but similar question as to name and id as in #2515

**Comment by Lupphes** [comment]
I'm not sure about the identifier. Would you happen to have any suggestions?

Is there something that must be clarified before this license can be processed? What are the following steps for this?

**Comment by jlovejoy** [comment]
direct links to license text:
https://github.com/docbook/xslt10-stylesheets/blob/efd62655c11cc8773708df7a843613fa1e932bf8/xsl/assembly/schema/docbook51b7.rnc#L19
https://github.com/docbook/xslt10-stylesheets/blob/efd62655c11cc8773708df7a843613fa1e932bf8/xsl/assembly/schema/assembly51b7.rnc#L19

I think the name and ID as noted in the submission are fine

**Comment by swinslow** [comment]
+1 to add, and fine with proposed ID and name from the submission.

**Comment by swinslow** [comment]
Discussed on 2024-08-08 legal team call, agreed to add with above ID and name

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
DocBook Schema License
## License ID
DocBook-Schema
## XML markup
none (make sure to use the text in the link above, not what was submitted)
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
