### ISSUE TITLE
New license request: TrustedQSL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by davide125** [spdx/license-list-XML#2518]
**1.** License Name: TrustedQSL
**2.** Short identifier: TrustedQSL
**3.** License Author or steward: American Radio Relay League, Inc and TrustedQSL Developers
**4.** Comments: This license is used in Fedora and was found during license review in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/544
**5.** License Request Url: http://tools.spdx.org/app/license_requests/379
**6.** URL(s): https://sourceforge.net/p/trustedqsl/tqsl/ci/master/tree/LICENSE.txt
**7.** OSI Status: Unknown
**8.** Example Projects: https://www.arrl.org/tqsl

**Comment by xsuchy** [comment]
License text:
```
Copyright (C) 2001-2015 American Radio Relay League, Inc. All rights
reserved.

Portions (C) 2003-2023 The TrustedQSL Developers. Please see the AUTHORS.txt
file for contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

1. Any redistribution of source code must retain the above copyright
notice, this list of conditions and the disclaimer shown in
Paragraph 5 (below).

2. Redistribution in binary form must reproduce the above copyright
notice, this list of conditions and the disclaimer shown in
Paragraph 5 (below) in the documentation and/or other materials
provided with the distribution.

3. Products derived from or including this software may not use
"Logbook of the World" or "LoTW" or any other American Radio Relay
League, Incorporated trademarks or servicemarks in their names
without prior written permission of the ARRL. See Paragraph 6
(below) for contact information.

4. Use of this software does not imply endorsement by ARRL of
products derived from or including this software and vendors may not
claim such endorsement. 

5. Disclaimer: This software is provided "as-is" without
representation, guarantee or warranty of any kind, either express or
implied, including but not limited to the implied warranties of
merchantability or of fitness for a particular purpose. The entire
risk as to the quality and performance of the software is solely
with you. Should the software prove defective, you (and not the
American Radio Relay League, its officers, directors, employees or
agents) assume the entire cost of all necessary servicing, repair or
correction. In no event will ARRL be liable to you or to any third
party for any damages, whether direct or indirect, including lost
profits, lost savings, or other incidental or consequential damages
arising out of the use or inability to use such software, regardless
of whether ARRL has been advised of the possibility of such damages.

6. Contact information:

American Radio Relay League, Inc.
Attn: Logbook of the World Manager
225 Main St
Newington, CT 06111
voice: 860-594-0200
fax: 860-594-0259
email: logbook@arrl.org
Worldwide Web: www.arrl.org

This software consists of voluntary contributions made by many
individuals on behalf of the ARRL. More information on the "Logbook
of The World" project and the ARRL is available from the ARRL Web
site at www.arrl.org.
```

**Comment by jlovejoy** [comment]
This has some BSD-like text, but definitely it's own variant (and looks to be quite old)

+1 to add

Given that the American Radio Relay League copyright is older and "ARRL" is used in various places in the license, I'm wondering if `ARRL' would be a better id?
and maybe American Radio Relay League License for the full name?

**Comment by swinslow** [comment]
+1 to add

Looks like there have been several variations over time for this one. A bit of history from some digging:

* The [SourceForge history](https://sourceforge.net/p/trustedqsl/tqsl/ci/9efc28c7c6bac0f67ff6c8c3409270415e1f96ad/log/?path=/LICENSE.txt) shows changes over time. For example, [this commit](https://sourceforge.net/p/trustedqsl/tqsl/ci/afe0464c7d0cbce7bdbd8223ec0716f66681795d/) in 2003 removed an advertising clause that was previously present.
* Debian mailing lists in 2003 [discussed one of these earlier versions](https://lists.debian.org/debian-legal/2003/10/msg00329.html) that had 8 clauses, including the advertising clause.
* Fedora mailing lists in 2008 [discussed the same version](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/QAB6ZMJGZ4HMDZ3CVPF54ZAC2X5L76HA/) that was submitted in this issue. (And I see also now that @richardfontana already noted this in the current Fedora review discussion.)
* Gentoo [also has the same version](https://gitweb.gentoo.org/repo/gentoo.git/tree/licenses/LOTW) that was submitted in this issue, and calls the license "LOTW" (presumably for the project "Logbook of the World").

So, regarding the name:

Given the above, I'm sort of inclined to go with `LOTW` for the identifier and "LOTW License" as the longer name, mostly to crib from the decision that Gentoo already made?

But if folks feel more strongly about using `TrustedQSL`, I'm fine with that, as these all appear to be related.

I might not go with `ARRL`, mostly out of not knowing whether ARRL as an organization may have released other software under different licenses.

**Comment by richardfontana** [comment]
Apparently Logbook of the World refers to an associated dataset of some sort maintained by ARRL, so for that reason I'd be inclined to go with TrustedSQL.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [TrustedQSL License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[t]/README.md#user-content-TrustedQSL-License:~:text=TrustedQSL%20License)
short name: TrustedQSL-License
markers: General Terms Matches Marker
category: TrustedQSL
OSI status: _none_

**Comment**
+1 to add.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
TrustedQSL License
## License ID
TrustedQSL
## XML markup
none at this time
## Notes:
none at this time
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).

**Comment by davide125** [comment]
Used the online tool to make https://github.com/spdx/license-list-XML/pull/2552 for this
