### ISSUE TITLE
New license request: HPND-DocBook-Stayton [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2523]
**1.** License Name: DocBook XSL Bob Stayton HPND License Variant
**2.** Short identifier: HPND-DocBook-Stayton
**3.** License Author or steward: Unknown
**4.** Comments: Found during license review in Fedora in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/545
It is used in package docbook5-schemas
**5.** License Request Url: http://tools.spdx.org/app/license_requests/381
**6.** URL(s): http://www.docbook.org/xml/5.0/docbook-5.0.zip
**7.** OSI Status: Unknown
**8.** Example Projects: http://www.oasis-open.org/docbook/

**Comment by xsuchy** [comment]
Fedora issue is https://gitlab.com/fedora/legal/fedora-license-data/-/issues/545 and some additional context is in https://gitlab.com/fedora/legal/fedora-license-data/-/issues/395#note_2010657994

Text of license:

```
# Permission to use, copy, modify and distribute this stylesheet
# and its accompanying documentation for any purpose and without fee
# is hereby granted in perpetuity, provided that the above copyright
# notice and this paragraph appear in all copies. The copyright
# holders make no representation about the suitability of the schema
# for any purpose. It is provided "as is" without expressed or implied
# warranty.
```

@richardfontana comment:
> This is close to HPND-UC and maybe some other HPND variants, but I think it's distinctive enough that it should be given a unique identifier. (For example, the second sentence refers to "the schema" while the first sentence refers to "this stylesheet and its accompanying documentation".)

**Comment by jlovejoy** [comment]
<img width="665" alt="image" src="https://github.com/user-attachments/assets/3c1e60a3-2533-49a2-996e-83b620a1b08e">

**Comment by jlovejoy** [comment]
pasted image of diff above. Note the "University of California" v. "copyright holders" is already accommodated via markup.

but I think I agree with @richardfontana that the other changes are just enough that this probably needs to be a new license.

curiosity that it uses "stylesheet" and then "schema"?

**Comment by swinslow** [comment]
+1 to add, based on the above and from a few other checks I'm not finding anything currently on the list that substantively matches this text.

For the name, though, I'm hesitant to use "Stayton" as part of the ID / name. Looking at the text from https://gitlab.com/fedora/legal/fedora-license-data/-/issues/545 I see "bobstayton" in the release line but not in the copyright notice. Plus, where possible I'm trying to minimize us using people's names in license IDs—at least without their own approval. We (and I) haven't stuck to this consistently in the past, but I think it's worth minimizing where we can.

Would something more like `HPND-DocBoook` or `HPND-DocBook-OASIS` work here instead?

**Comment by richardfontana** [comment]
I think there might be another HPND variant in DocBook.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [DocBook Stylesheet License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[d]/README.md#user-content-DocBook-Stylesheet-License:~:text=DocBook%20Stylesheet%20License)
short name: DocBook Stylesheet License
markers: General Terms Matches Marker, No Warranty Marker
category: DocBook Stylesheet
OSI status: _none_

**Comment**
We differentiate the DocBook Stylesheet License and the DocBook Shema License. +1 to add in support of DocBook as widely used tool.

**Comment by jlovejoy** [comment]
we just need to settle on id and name for this one. how about:
`DocBook-stylesheet` ?

we didn't use HPND on https://spdx.org/licenses/DocBook-Schema.html and https://spdx.org/licenses/DocBook-XML.html

so thinking we might be consistent with those??

**Comment by swinslow** [comment]
I'm +1 to use "DocBook-Stylesheet", would capitalize "Stylesheet" to match other DocBook IDs we recently added.
