### ISSUE TITLE
New license request: harbour-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by chenrui333** [spdx/license-list-XML#2524]
**1.** License Name: harbour exception
**2.** Short identifier: harbour-exception
**3.** License Author or steward: unknown
**4.** Comments: harbour license exception for its library
**5.** License Request Url: http://tools.spdx.org/app/license_requests/382
**6.** URL(s): https://github.com/harbour/core/blob/master/LICENSE.txt#L44-L66
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/harbour/core

**Comment by jlovejoy** [comment]
text of exception:

As a special exception, the Harbour Project gives permission for
additional uses of the text contained in its release of Harbour.

The exception is that, if you link the Harbour libraries with other
files to produce an executable, this does not by itself cause the
resulting executable to be covered by the GNU General Public License.
Your use of that executable is in no way restricted on account of
linking the Harbour library code into it.

This exception does not however invalidate any other reasons why
the executable file might be covered by the GNU General Public License.

This exception applies only to the code released by the Harbour
Project under the name Harbour.  If you copy code from other
Harbour Project or Free Software Foundation releases into a copy of
Harbour, as the General Public License permits, the exception does
not apply to the code that you add in this way.  To avoid misleading
anyone as to the status of such modified files, you must delete
this exception notice from them.

If you write modifications of your own for Harbour, it is your choice
whether to permit this exception to apply to your modifications.
If you do not wish that, delete this exception notice.

**Comment by jlovejoy** [comment]
this does not match any exception already on the SPDX LIcense List

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Linking Exception (Harbour)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[l]/README.md#user-content-Linking-Exception-(Harbour):~:text=Linking%20Exception%20(Harbour))
short name: Linking-Exception-Harbour
category: Linking Exception
OSI status: _none_

**Comment**
Unsure about adding. I have no strong evidence on use. I would - since harbour in a language and an infrastructure - add it in support of their objectives.

**Comment by jlovejoy** [comment]
discussed on 9/12 - add license, fine with name/id, add note that it is similiar to SANE
