### ISSUE TITLE
IETF variant of BSD-3-Clause license

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2529]
During Fedora License review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/533 we found a license that is used in net-snmp package:
  https://github.com/net-snmp/net-snmp/blob/master/COPYING#L320
This license is very close to BSD-3-Clause but the third clause is:

```
*  Neither the name of Internet Society, IETF or IETF Trust, nor the
names of specific contributors, may be used to endorse or promote
products derived from this software without specific prior written
permission.
```

Should we add this as a markup change to BSD-3-Clause or assign a new id?

Full text of the license:

```
Copyright (c) 2013 IETF Trust and the persons identified as authors of
the code.  All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

*  Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

*  Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

*  Neither the name of Internet Society, IETF or IETF Trust, nor the
names of specific contributors, may be used to endorse or promote
products derived from this software without specific prior written
permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS
IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [BSD 3-Clause License (copyright holder variant)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[b]/README.md#user-content-BSD-3-Clause-License-(copyright-holder-variant):~:text=BSD%203%2DClause%20License%20(copyright%20holder%20variant))
short name: BSD-3-Clause-copyright-holder
markers: Do Not Promote Marker, General Terms Matches Marker
category: BSD
OSI status: _none_

**ScanCode**
matched id: [bsd-new](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/bsd-new.LICENSE)

**Comment**
Should be matched with SPDX as BSD-3-Clause. In our understanding the variation does not change the meaning of the license.

**Comment by swinslow** [comment]
Comparing this to [the current markup for BSD-3-Clause](https://github.com/spdx/license-list-XML/blob/main/src/BSD-3-Clause.xml), I'm seeing two differences from the "standard" text visible on the [License List website](https://spdx.org/licenses/BSD-3-Clause.html):

1. In the final all-caps disclaimer paragraph, the second sentence of the IETF version uses "IN NO EVENT SHALL THE COPYRIGHT **OWNER** OR CONTRIBUTORS BE LIABLE FOR . . ." whereas BSD-3-Clause uses "IN NO EVENT SHALL THE COPYRIGHT **HOLDER** OR CONTRIBUTORS BE LIABLE FOR . . .". However, that part of BSD-3-Clause is enclosed in an `<alt>` tag that permits any characters to match, so "OWNER" vs. "HOLDER" shouldn't matter here.

2. More notable (and as @xsuchy flagged), clause 3 of the IETF version uses "Neither the name of Internet Society, IETF or IETF Trust, nor the names of specific contributors, may . . .". 

For item 2, in BSD-3-Clause this is part of [the worst `<alt>` tag regex](https://github.com/spdx/license-list-XML/blob/779bbe079ca2595e2d91fae30733f5b40eaf60e1/src/BSD-3-Clause.xml#L31-L34) in the entire License List.  :)  But looking at the various options within that regex, I see the following:

`(Neither\s+the\s+name\s+of.+nor\s+the\s+names\s+of\s+(specific\s+)?contributors,?\s+may)`

Please let me know if I'm wrong, but I _think_ that matches the language that's here in this IETF version?

If so, then I think this IETF version is already a match for BSD-3-Clause as-is.

(There's a separate discussion to be had about whether all these `\s+` tags are appropriate to embed in the regex, but that's for another issue and another day...)

**Comment by jlovejoy** [comment]
@xsuchy - I agree with @swinslow analysis above, but we just wanted to confirm as well and make sure we didn't miss anything

**Comment by xsuchy** [comment]
Yes. I can confirm it matches the current markup. Closing.
