### ISSUE TITLE
Classpath-exception-2.0 variant in Free Pascal

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2530]
During Fedora License review
  https://gitlab.com/fedora/legal/fedora-license-data/-/issues/548
we found in package `fpc` (Free Pascal) an exception that is close to `Classpath-exception-2.0` and used in combination with LGPL-2.1-or-later.

This exception is identical to `Classpath-exception-2.0` except that it omits the first paragraph/sentence:

```
Linking this library statically or dynamically with other modules is making a combined work based on this library. Thus, the terms and conditions of the GNU General Public License version 2 cover the whole combination.
```

Should this section be marked as optional in current exception? Or this should be new id?

Full text of the license:
https://gitlab.com/freepascal.org/fpc/source/-/blob/release_3_2_2/rtl/COPYING.FPC

```
This is the file COPYING.FPC, it applies to the Free Pascal Run-Time Library 
(RTL) and packages (packages) distributed by members of the Free Pascal 
Development Team.

The source code of the Free Pascal Runtime Libraries and packages are 
distributed under the Library GNU General Public License 
(see the file COPYING) with the following modification:

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent modules,
and to copy and distribute the resulting executable under terms of your choice,
provided that you also meet, for each linked independent module, the terms
and conditions of the license of that module. An independent module is a module
which is not derived from or based on this library. If you modify this
library, you may extend this exception to your version of the library, but you are
not obligated to do so. If you do not wish to do so, delete this exception
statement from your version.
```

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Linking Exception (independent module)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[l]/README.md#user-content-Linking-Exception-(independent-module):~:text=Linking%20Exception%20(independent%20module))
short name: Linking-Exception-Independent
category: Independent Linking Exception
ScanCode reference id: [independent-module-linking-exception](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/independent-module-linking-exception.LICENSE)
ScanCode reference id: [linking-exception-lgpl-2.0-plus](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/linking-exception-lgpl-2.0-plus.LICENSE)
OSI status: _none_

**ScanCode**
matched id: [linking-exception-lgpl-2.0-plus](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/linking-exception-lgpl-2.0-plus.LICENSE)

**Comments**
I would add this as generic exception without associating this to Pascal or GPL licenses.

**Comment by jlovejoy** [comment]
discussed on 9/26 call - agree to add, but ran out of time for deciding on exact nature of markeup, name, and id

@swinslow @karsten-klein @Pizza-Ria - have a look at #2573 and let me know what you think!
