### ISSUE TITLE
New license request: mxml-exception

### ISSUE THREAD

**Issue by nirik** [spdx/license-list-XML#2531]
**1.** License Name: ASL-2.0 + linking exception
**2.** Short identifier: GPL-2.0-Linking-Exception
**3.** License Author or steward: michaelrsweet
**4.** Comments: mxml is a package in Fedora and the exception is has doesn't seem to match any existing exceptions. 

See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/549#note_2027321979
**5.** License Request Url: http://tools.spdx.org/app/license_requests/383
**6.** URL(s): https://github.com/michaelrsweet/mxml/blob/master/NOTICE, https://github.com/michaelrsweet/mxml/blob/master/LICENSE
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/michaelrsweet/mxml/

**Comment by karsten-klein** [comment]
Quite confusing naming proposal. I assume the following exception is the subject here:

> In addition, if you combine or link compiled forms of this Software with
> software that is licensed under the GPLv2 or LGPLv2 (“Combined Software”) and if
> a court of competent jurisdiction determines that the patent provision (Section
> 3), the indemnity provision (Section 9) or other Section of the License
> conflicts with the conditions of the GPLv2 or LGPLv2, you may retroactively and
> prospectively choose to deem waived or otherwise exclude such Section(s) of the
> License, but only in their entirety and only with respect to the Combined
> Software.

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Apache Patent Provision Exception](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[a]/README.md#user-content-Apache-Patent-Provision-Exception:~:text=Apache%20Patent%20Provision%20Exception)
short name: Apache-Patent-Exception
category: Apache Patent Provision Exception
ScanCode reference id: [apache-patent-exception](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/apache-patent-exception.LICENSE)
OSI status: _none_

**ScanCode**
matched id: apache-2.0 WITH generic-exception

**Comment**
Please note that exception is explicitly dealing with patents. Simply naming it a "linking exception" I do not regard a valid approach. So I'm proposing to use the (canonical) name and short name as we have derived. +1 to add.

**Comment by richardfontana** [comment]
Note also the complication that there is a [separate text](https://github.com/michaelrsweet/mxml/tree/master?tab=readme-ov-file#legal-stuff) in the README.md file of the same project that basically says the exception is removable (in the manner of typical GPL exceptions, I guess). See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/549#note_2116790301

**Comment by jlovejoy** [comment]
@richardfontana - does that impact your thoughts on inclusion to SPDX or not?

**Comment by swinslow** [comment]
Discussed on 2024-10-24 legal team call -- +1 to add this, given its inclusion in Fedora together with it being in the same vein as other "enable linking between incompatible licenses" exceptions such as [LLVM-exception](https://spdx.org/licenses/LLVM-exception.html).

For the name, wouldn't use "Apache" or "ASF" in the name or ID since it isn't an ASF-issued exception. Also wouldn't use "GPL-2.0" since it applies to LGPL-2.0 also; and wouldn't include "patent" since it's broader that just the patent indemnity provision.

Discussed on legal team call and agreed to use "mxml Exception" as name and `mxml-exception` as identifier to use for this one, based on it appearing that this project (and possibly others from the same author) are where this originates.

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
mxml Exception
## License ID
mxml-exception
## XML markup
none
## Notes:
This is similar to the LLVM-exception, but omits the first paragraph.
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
