### ISSUE TITLE
Updating a link in licenseXml to the latest license-list-XML version

### ISSUE THREAD

**Issue by bact** [spdx/license-list-XML#2536]
[licenseXml](https://github.com/spdx/spdx-3-model/blob/main/model/ExpandedLicensing/Properties/licenseXml.md?plain=1) property in SPDX v3 spec is pointing to a specific version of [ListedLicense.xsd](https://github.com/spdx/license-list-XML/blob/v3.24.0/schema/ListedLicense.xsd) (at the time of writing, v3.24.0).

Once a license-list-XML release a new version, the link in licenseXml property page should get updated to the latest version.

**Comment by swinslow** [comment]
Hi @bact, v3.25.0 has now been tagged and released.

Is there anything further that you think is needed in this repo? It looks like this is just asking about updating the reference in a different repo. Let me know if you need anything else here, otherwise I'll close this.

**Comment by bact** [comment]
Open two PRs in different repos to resolve this:
- https://github.com/spdx/spdx-3-model/pull/863
- https://github.com/spdx/spdx-spec/pull/1075
