### ISSUE TITLE
New license request: InnoSetup [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by dscho** [spdx/license-list-XML#2550]
**1.** License Name: InnoSetup license
**2.** Short identifier: InnoSetup
**3.** License Author or steward: Unknown
**4.** Comments: InnoSetup is an open source program that helps generating Windows-based installers. The InnoSetup license seems to be based on a 3-clause BSD license, with the "origin" exception borrowed from the zlib license. It is thus different to both.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/387
**6.** URL(s): https://github.com/jrsoftware/issrc/blob/HEAD/license.txt
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/jrsoftware/issrc

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Inno Setup License](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[i]/README.md#user-content-Inno-Setup-License:~:text=Inno%20Setup%20License)
short name: Inno-Setup
markers: No Warranty Marker
category: Inno Setup License
ScanCode reference id: [inno-setup](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/inno-setup.LICENSE)
OSI status: _none_

**ScanCode**
matched id: [inno-setup](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/inno-setup.LICENSE)

**Comment**
I've no evidence for widespread adoption of the license. I would argue +1 from a application/use point of view.

**Comment by jlovejoy** [comment]
@karsten-klein - when you say no evidence for widespread adoption, do you mean in regard to use by other projects?
Seems like this project itself is probably widely use, agree?

**Comment by dscho** [comment]
@jlovejoy is there anything I can/need to do to help get this done?

**Comment by jlovejoy** [comment]
discussed on 10/24 legal call, add and use suggested name

**Comment by jlovejoy** [comment]
# License Inclusion Decision

## Decision:

- [ ] approved
- [ ] not approved

## Name
InnoSetup License
## License ID
InnoSetup
## XML markup
none
## Notes:
none
## Next steps ##
If the license has been accepted, please follow [the accepted-license process to create the PR](https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md#accepted-license-process).
