### ISSUE TITLE
New license request: B [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by raitsek** [spdx/license-list-XML#2564]
**1.** License Name: sepa credit transfer
**2.** Short identifier: B
**3.** License Author or steward: BILL
**4.** Comments: oke
**5.** License Request Url: http://tools.spdx.org/app/license_requests/392
**6.** URL(s): https://sites.google.com/view/sepavalidate/homepage
**7.** OSI Status: Approved
**8.** Example Projects: https://tools.spdx.org/app/submit_new_license/

**Comment by swinslow** [comment]
closing as spam
