### ISSUE TITLE
Markup: HPND-sell-variant (was New license request: MIT-old-style [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2575]
**1.** License Name: MIT Old Style
**2.** Short identifier: MIT-old-style
**3.** License Author or steward: Unknown
**4.** Comments: This license was discovered during License review in Fedora Linux. https://gitlab.com/fedora/legal/fedora-license-data/-/issues/575
It is an old license, but it is still actively used in the Xsel package.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/396
**6.** URL(s): https://github.com/kfish/xsel/blame/master/COPYING
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/kfish/xsel/

**Comment by xsuchy** [comment]
License text for your convenience:
```
Permission to use, copy, modify, distribute, and sell this software and its
documentation for any purpose is hereby granted without fee, provided that
the above copyright notice appear in all copies and that both that
copyright notice and this permission notice appear in supporting
documentation.  No representations are made about the suitability of this
software for any purpose.  It is provided "as is" without express or
implied warranty.
```

**Comment by xsuchy** [comment]
@richardfontana comment from Fedora issue:
> This is close to HPND-sell-variant but the disclaimer sentence ("No representations are made about the suitability of this software for any purpose") is different (possibly only in being in the passive). Approved, submit to SPDX, see if they think HPND-sell-variant should be revised to accommodate this variant.

I will welcome your comments if this should be new license or markup of existing license. Or something else?

**Comment by jlovejoy** [comment]
exact difference is as follows:

 `HPND-sell-variant` says:
`<copyright holder> <makes|make> no representations about the suitability of this software for any purpose. `
 
this license says:
`No representations are made about the suitability of this
software for any purpose. `

**Comment by jlovejoy** [comment]
I have a hard time thinking that passive voice changes the meaning here, but would like to hear others input.

**Comment by richardfontana** [comment]
Well, I suppose the difference is that the passive voice version suggests that a potentially larger set of entities are not making representations. Would SPDX consider these to be the same: "The copyright holders disclaim warranties ... " and "The copyright holders and distributors disclaim warranties ... "?

**Comment by karsten-klein** [comment]
**{metæffekt} Universe**
canonical name: [Permission Terms (variant 123)](https://github.com/org-metaeffekt/metaeffekt-universe/blob/main/src/main/resources/ae-universe/[p]/README.md#user-content-Permission-Terms-(variant-123):~:text=Permission%20Terms%20(variant%20123))
short name: PT-Var123
markers: No Warranty Marker
category: Permission
ScanCode reference id: [mit-old-style](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-old-style.LICENSE)
OSI status: _none_
Open CoDE status: approved
Open CoDE approved license id: mit-old-style (ScanCode)

**ScanCode**
matched id: [mit-old-style](https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/mit-old-style.LICENSE)

**Comment**
No particular opinion on adding.

**Comment by jlovejoy** [comment]
so @richardfontana - are you +1 to treat this the same and add markup?

**Comment by Pizza-Ria** [comment]
I do not have a strong opinion but when I run the license analysis tool, it comes up as an 80% match for HPND-Netrek (deprecated) ... the primary difference is the addition of the grant to "sell".  So, I'm not sure I understand why we are calling it MIT-Old-Style.  I looked at a couple of versions of MIT and the wording is substantially closer to the match provided by the tool.
