### ISSUE TITLE
New license request: MIPS [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by xsuchy** [spdx/license-list-XML#2586]
**1.** License Name: MIPS License
**2.** Short identifier: MIPS
**3.** License Author or steward: Unknown
**4.** Comments: This was found during License Review in Fedora Linux https://gitlab.com/fedora/legal/fedora-license-data/-/issues/235
It was found in a package binutils-gdb.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/400
**6.** URL(s): https://sourceware.org/cgit/binutils-gdb/tree/include/coff/sym.h#n11, https://sourceware.org/cgit/binutils-gdb/tree/include/coff/symconst.h#n11
**7.** OSI Status: Unknown
**8.** Example Projects: https://sourceware.org/cgit/binutils-gdb

**Comment by xsuchy** [comment]
License text:
```
Copyright (c) 1992, 1991, 1990 MIPS Computer Systems, Inc.
MIPS Computer Systems, Inc. grants reproduction and use
rights to all parties, PROVIDED that this comment is
maintained in the copy. 
```

But e.g., here 
https://sourceware.org/cgit/binutils-gdb/tree/include/coff/symconst.h#n18
is slightly longer variant:

```
(C) Copyright 1984 by Third Eye Software, Inc.

Third Eye Software, Inc. grants reproduction and use rights to
all parties, PROVIDED that this comment is maintained in the copy.

Third Eye makes no claims about the applicability of this
symbol table to a particular use.
```

**Comment by jlovejoy** [comment]
@xsuchy - is the second variant (Third Eye) also found in Fedora?

**Comment by swinslow** [comment]
I'm +1 to add each of these as separate historical licenses, probably with `MIPS` and `Third-Eye` as the identifiers.

**Comment by jlovejoy** [comment]
discussed on 12/12 call - agree to add both with following ids:
`MIPS`  with no markup
Note: This license is the same as ThirdEye, but does not have a disclaimer.

`ThirdEye` with no markup.
Notes: This license is the same as MIPS, but adds a disclaimer.
