### ISSUE TITLE
Spelling Correction

### ISSUE THREAD

**Issue by Pizza-Ria** [spdx/license-list-XML#2587]
Correct spelling of university in https://spdx.org/licenses/xpp.html.

**Comment by xsuchy** [comment]
There are two options specified using alt tag. One of them is grammatically correct.
https://github.com/spdx/license-list-XML/blob/main/src/xpp.xml#L48

But I agree that the one inside of the tag (and that is rendered in the documentation) should be the correct one.

**Comment by swinslow** [comment]
Thanks @Pizza-Ria! Merged in #2588.
