### ISSUE TITLE
New license request: W3C Software and Document license - 2023 version

### ISSUE THREAD

**Issue by bact** [spdx/license-list-XML#2600]
### How license meets inclusion principles

- The license is widely used by W3C community and related software and documents.
- [SPDX License List](https://spdx.org/licenses/) already has three variants of this license: `W3C`, `W3C-19980720`, `W3C-20150513`
- Per SPDX License List, two of its variants are OSI-approved.
  - OSI page for `W3C-20150513` https://opensource.org/license/w3c 
- The license can be applied to source code and documents
- It has a stable text with a permanent URL

### License Name

W3C Software and Document license - 2023 version

### Suggested short identifier

`W3C-2023`

(the existing `W3C` may need to be deprecated and replaced by a dated identifier, perhaps `W3C-2022`)

### License or Exception?

license

### URL to license text

https://www.w3.org/copyright/software-license-2023/

### OSI Status

I don't know -- but its previous version is OSI-approved.

Please see @coolharsh55 comments below https://github.com/spdx/license-list-XML/issues/2600#issuecomment-2453010346

### License author or steward

World Wide Web Consortium

### URL to project(s) that use license

- https://github.com/w3c/epub-specs/
- https://github.com/w3c/html-aria/
- https://github.com/w3c/csswg-drafts/
- https://github.com/WICG/inert/
- https://github.com/immersive-web/webxr-hand-input/

### paste text of license here

Software and Document license - 2023 version

Status: This document is in effect since 1 January 2023.

This work is being provided by the copyright holders under the following license.

License

By obtaining and/or copying this work, you (the licensee) agree that you have read, understood, and will comply with the following terms and conditions.

Permission to copy, modify, and distribute this work, with or without modification, for any purpose and without fee or royalty is hereby granted, provided that you include the following on ALL copies of the work or portions thereof, including modifications:

The full text of this NOTICE in a location viewable to users of the redistributed or derivative work.
Any pre-existing intellectual property disclaimers, notices, or terms and conditions. If none exist, the W3C software and document short notice should be included.
Notice of any changes or modifications, through a copyright statement on the new code or document such as "This software or document includes material copied from or derived from [title and URI of the W3C document]. Copyright © [$year-of-document] World Wide Web Consortium. https://www.w3.org/copyright/software-license-2023/"

Disclaimers

THIS WORK IS PROVIDED "AS IS," AND COPYRIGHT HOLDERS MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF THE SOFTWARE OR DOCUMENT WILL NOT INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.

COPYRIGHT HOLDERS WILL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF ANY USE OF THE SOFTWARE OR DOCUMENT.

The name and trademarks of copyright holders may NOT be used in advertising or publicity pertaining to the work without specific, written prior permission. Title to copyright in this work will at all times remain with copyright holders.

Versions

This version: https://www.w3.org/copyright/software-license-2023/
Latest version: https://www.w3.org/copyright/software-license/
Previous version: https://www.w3.org/copyright/software-license-2015/

Changes since the previous document

The 2023 version updates identification of the copyright holder.

**Comment by coolharsh55** [comment]
Thanks Art. The W3C page https://www.w3.org/Status.html identifies its license as OSI approved - though the OSI archive only refers to 2015 version. The 2023 license has a change log that only adds identification of copyright holder and no other material changes. So I think the latest license also is OSI conformant though not explicitly in its list.

**Comment by swinslow** [comment]
Hi @bact,

As described in the notes for [`W3C-20150513`](https://spdx.org/licenses/W3C-20150513.html), the 2023 changes made by W3C to the license were only changes to the copyright notice in the middle of the license (under the third bullet point). Changes to copyright notices are ignored pursuant to the [SPDX Matching Guidelines](https://spdx.github.io/spdx-spec/v3.0.1/annexes/license-matching-guidelines-and-templates/#copyright-notice).

Given that, the 2023 changes made by W3C are still a match to `W3C-20150513`, so a new license ID / entry on the License List is not required. Please see also the discussion at #2429 earlier this year and the corresponding PR at #2447 which clarified this.

**Comment by bact** [comment]
Thank you @swinslow.
