### ISSUE TITLE
rename gh label "has acknowledgement" to "requires acknowledgement"?

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#313]
If we think of our label "has acknowledgement" as applying to PRs for licenses that require acknowledgement, should we rename our "has acknowledgement" label to "requires acknowledgement" for clarity & posterity? Thoughts?

If we do so, I assume we would have to select every PR with that label, apply the new label to those PRs, and then remove the old label.

See also https://github.com/spdx/license-list-XML/pull/248#discussion_r63072595

**Comment by jlovejoy** [comment]
agreed, was able to change name of label, which now appears globally :)
