### ISSUE TITLE
report on licenses that have anything other than <li> as direct children of <list> ?

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#317]
Looking at #293, as well as several other licenses that have (or should have) nested lists, I wonder if it would be possible to programmatically check the XML files for any place where the direct child entity of a &lt;list&gt; tag is _not_ an &lt;li&gt; tag. I'm guessing/assuming here that we would want to make that a rule similar to &lt;li&gt;s in HTML, i.e. that these would be illegal:

`<list>  <list>`
(should be `<list> <li> <list>`)

`<list>  <p>`
(should be `<list> <li> <p>`)

`<list> License-text`
(should be `<list> <li> License-text` or `<list> <li> <p> License-text`)

**Comment by myndzi** [comment]
I agree, and it should be easy to programmatically check and possibly fix, depending on the case

**Comment by goneall** [comment]
The schema has a minOccurs="1" for the list items.  The SPDX tools which generate the website will validate against the schema and report errors on any invalid licenses.  I don't plan to implement any programatic fixes, just reporting the errors - I'll leave it to humans to review the licenses and add list items in the correct locations.

**Comment by jlovejoy** [comment]
will close, as has been dealt with. if separate issues come up, will open separate issues for those
