### ISSUE TITLE
Unicode TOU revision

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#320]
It appears that Steven Loomis [reported](http://lists.spdx.org/pipermail/spdx-legal/2016-July/001807.html) a revision in the Unicode TOU license back on July 27, but for me, at least, the resulting email from mail.linuxfoundation.org did not arrive until today. No need to figure out the email weirdness, but since the XML Unicode TOU license has already been merged, I'm filing this issue as a reminder for us to add the updated license revision.

Here's the email:

---

`Hello, - this license has a revision.`

`Short name: Unicode-TOU`

`re: http://spdx.org/licenses/Unicode-TOU.html#licenseText`
`And http://wiki.spdx.org/view/Legal_Team/License_List/Licenses_Under_Consideration`

`Please note that the Unicode-TOU has been revved, see http://www.unicode.org/copyright.html – the ICU project is now under Unicode, and so ICU is now under Unicode-TOU and not under ICU`

`Example use:`
`ICU website: http://site.icu-project.org link “open source license”`
`ICU contents:  http://source.icu-project.org/repos/icu/icu/trunk/LICENSE`

**Comment by jlovejoy** [comment]
this was resolved https://lists.spdx.org/pipermail/spdx-legal/2016-October/001863.html
