### ISSUE TITLE
typo in BSD-3-Clause-No-Nuclear-License-2014.txt

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#323]
This license hasn't been migrated to github yet, but there's a typo on line 2 of [BSD-3-Clause-No-Nuclear-License-2014.txt](http://git.spdx.org/?p=license-list.git;a=blob;f=BSD-3-Clause-No-Nuclear-License-2014.txt;h=a454f2dd7b0e7364df0a58e00293616f2aa16557;hb=f0c56f89c60469bec90804621f84fb2d9fbe6012).

Reads:
`Copyright © 2008, 2014 OrUntitled.txtacle and/or its affiliates. All rights reserved.`

Probably should be:
`Copyright © 2008, 2014 Oracle and/or its affiliates. All rights reserved.`

**Comment by jlovejoy** [comment]
this has been fixed, closing
