### ISSUE TITLE
typo in BSD-3-Clause-No-Nuclear-License.txt

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#324]
Mark Baushke reports a typo in [BSD-3-Clause-No-Nuclear-License.txt](http://git.spdx.org/?p=license-list.git;a=blob;f=BSD-3-Clause-No-Nuclear-License.txt;h=000b03ab3477bb93391f9c52bc426c70b4685be9;hb=f0c56f89c60469bec90804621f84fb2d9fbe6012): 
Line 12 is very long and splits the word "SUN" across the end of line 12 and the beginning of line 13

Probably those lines should be seasoned with carriage returns for better readability.

**Comment by jlovejoy** [comment]
I believe this has been fixed, see: https://github.com/spdx/license-list-XML/blob/master/src/BSD-3-Clause-No-Nuclear-License.xml (@bradleeedmondson, can you do a sanity check?

**Comment by bradleeedmondson** [comment]
Yes, fixed. Resolving.
