### ISSUE TITLE
reminder: true-up XML license list for SPDX releases post 2.3

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#327]
The current license list in the XML format was generated based on a now-outdated SPDX release (I believe 2.3, but am not sure). So, we need to add XML representations of all licenses added after that port. Hopefully this will be as simple as looking at the [commit log](https://github.com/spdx/license-list/commits/master) and the existing license spreadsheet and checking off each new license one-by-one.

This issue is a placeholder reminder to do that.

**Comment by jlovejoy** [comment]
I think we have done this... do final check on any to-be added licenses since 2.6 though.

**Comment by bradleeedmondson** [comment]
I believe we need to do this again now that we've accepted more licenses to the list.

**Comment by jlovejoy** [comment]
decision to add 2.7 licenses after @goneall has done XML true-up on revised XML tags

**Comment by bradleeedmondson** [comment]
I haven't done a careful check, but based on a quick scan of the [Google Sheets document](https://docs.google.com/spreadsheets/d/11AKxLBoN_VXM32OmDTk2hKeYExKzsnPjAVM7rLstQ8s/edit#gid=695212681), that looks like it could be:
* EPL-2.0
* EUPL-1.2
* ~~BSD-2-Clause-Patent (done)~~
* W3C-Software-2015
* ~~Unicode-DFS-2015 (done)~~
* ~~Unicode-DFS-2016 (done)~~
* ~~TCP-wrappers (done)~~
* ~~Net-SNMP (done)~~

And perhaps also some/all of the licenses still under review:
* CDLA-Permissive-1.0
* CDLA-Sharing-1.0
* OSCAT

Then we should add the accepted [exceptions](https://docs.google.com/spreadsheets/d/11AKxLBoN_VXM32OmDTk2hKeYExKzsnPjAVM7rLstQ8s/edit#gid=0):
* ~~Linux-syscall-note (done)~~
* Bootloader-exception

And _perhaps_ the same for exceptions under review, although I'm not as familiar with these and they may be stale at this point. But as marked, these are "under review":
* aptana-exception-3.0
* Cygwin-exception-2.0
* FOSS-License-exception
* MySQL-Connector-ODBC-exception-2.0
* OCaml-exception
* rrdtool-floss-exception-2.0
* sencha-exception-3.0
* trolltech-gpl-exception-1.2
* wolfcms-exception-2.0
* Zarafa-trademark-exception-3.0

**Comment by zvr** [comment]
Given that @jlovejoy quickly approved BSD-2-Clause-Plus-Patent but not yet the two CDLAs that I did at the same time, I wonder whether I should flag them "needs legal discussion" to make them more visible :)

**Comment by jlovejoy** [comment]
Is this why you give chocolate? ;)


Sent from an ARM powered device 

-------- Original message --------

**Comment by jlovejoy** [comment]
need to check for W3C-Software-2015 and OSCAT

**Comment by jlovejoy** [comment]
OSCAT as not accepted; email sent, spreadsheet updated.

**Comment by jlovejoy** [comment]
W3C-20150513 was already added
https://github.com/spdx/license-list-XML/blob/master/src/W3C-20150513.xml
