### ISSUE TITLE
Should we allow formatting in the alt and optional elements

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#393]
Question: Should we allow paragraphs, bullets, lists inside the optional and alt elements?  I would assume we should disallow nested optional and alt elements (e.g. "<optional> this is an <optional> really </optional> optional text </optional>")

Note that the current schema definition only uses simple text for optional and alt.

**Comment by wking** [comment]
On Fri, Feb 24, 2017 at 07:32:33PM -0800, goneall wrote:
> I would assume we should disallow nested optional and alt elements
> (e.g. "<optional> this is an <optional> really </optional> optional
> text </optional>")

As I understand it, the purpose of <optional> is to allow a license to
match whether or not it contains the optional content.  If there are
multiple flavors of the optional content, you'd need either nested
<optional> elements or a series of <optional> elements:

  <optional>flavor A</optional>
  <optional>flavor B</optional>
  <optional>flavor</optional>

Personally I'd rather allow nesting:

  <optional>flavor<optional> <alt name="flavor" match="A|B">A</alt></optional></optional>

because with longer optional/alternative text it allows us to avoid
repeating shared content.

**Comment by bradleeedmondson** [comment]
@goneall I can say that we have a fair number of licenses with significant portions of text marked optional, so I'd think that we'd need to be able to include formatting tags within &lt;optional&gt; blocks to be able to display that in a readable way.

I have no opinion on nesting &lt;optional&gt; or &lt;alt&gt; tags within each other.

**Comment by goneall** [comment]
Agree on the nesting of the formatting.  We'll need to update the schema for this.

I'm thinking that we do not nest <optional> and <alt> - I haven't seen this in practice and it would really complicate the schema.

@wking Your proposal is quite reasonable, however, we have already standardized on the current approach for the text files.  I would like to keep the basic format between the template text and HTML structurally similar.  If we were to change the structure of both, it would involve a revision of the spec.  I would suggest we go with the current approach for now and consider alternative formats in future revisions of the spec.  We would also want to take into account backwards compatibility since these formats have been encoded in license text outside of the XML.

**Comment by wking** [comment]
On Wed, Mar 22, 2017 at 10:35:30AM -0700, goneall wrote:
> I would suggest we go with the current approach for now and consider
> alternative formats in future revisions of the spec.

I was just trying to demonstrate where nesting alt/optional would be
useful, and not trying to propose an alternate format.  I agree that
nesting alt/optional makes the schema and license definitions more
complicated, although as I tried to show in my example, sometimes that
increased complication can help avoid redundancy in the license
definition.  However, allowing nesting alt/optional is a
backwards-compatible change, so we can always forbid nesting for now
and allow it later on if we change our minds.

> We would also want to take into account backwards compatibility
> since these formats have been encoded in license text outside of the
> XML.

I don't see a backwards compatibility issue with *adding* nesting for
alt/optional.  All existing licenses won't use nested alt/optional,
and they'll still be valid whether nesting alt/optional becomes legal
or not.

I'm not clear on the “these formats have been encoded in license text
outside of the XML” wrinkle.  Are there non-XML formats where nesting
alt/optional wouldn't be possible?  Either way, I guess we can address
this if/when we decide to pick nesting alt/optional back up.

**Comment by pmadick** [comment]
Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by goneall** [comment]
I added nested formatting for the alt and optional fields in the schema and implemented support in the spdx-tools.
