### ISSUE TITLE
Error in SPDX version of Apache-1.1

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#396]
Reported by Richard Fontana:

---------------------------------------------------

Hi,

The license text for Apache-1.1 
has for clause 4: "4. The "Apache" and "Apache Software Foundation" must not be used to endorse or promote products derived from this software without prior written permission. For written permission, please contact apache@apache.org" 

Assuming the following text at apache.org is or should be treated as authoritative:
https://www.apache.org/licenses/LICENSE-1.1

the SPDX text is in error, as it is missing the word "names" (and the closing period).

See also the template version at https://github.com/spdx/license-list/blob/master/Apache-1.1.txt#L15.

 Richard

**Comment by bradleeedmondson** [comment]
Also reported by Richard: 

-----------------------------------

The same error exists in the SPDX text for Apache-1.0:
https://spdx.org/licenses/Apache-1.0.html
"4. The "Apache" and "Apache Software Foundation" must not be used to endorse or promote products derived from this software without prior written permission. For written permission, please contact apache@apache.org"

Compare to http://www.apache.org/licenses/LICENSE-1.0 :
*  4. The names "Apache Server" and "Apache Group" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    apache@apache.org.

**Comment by jlovejoy** [comment]
have created PRs for both of these issues. to review on April 13 legal call, then merge 
issue from @richardfontana

**Comment by bradleeedmondson** [comment]
fixed in #400 and #401 

resolved
