### ISSUE TITLE
Remove "only" from GPL license titles?

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#398]
Per @wking, should we remove the appended word "only" from the GPL licenses that still have it?

GNU General Public License v1.0 only
GNU General Public License v2.0 only
GNU General Public License v3.0 only
GNU Lesser General Public License v2.1 only
GNU Lesser General Public License v3.0 only
GNU Library General Public License v2 only

**Comment by bradleeedmondson** [comment]
linked to https://github.com/spdx/license-list/issues/6

**Comment by jlovejoy** [comment]
this is linked to this discussion: https://wiki.spdx.org/view/Legal_Team/or-later-vs-unclear-disambiguation 
Depending on findings there re: discontinuing the use of "+" operator, the "only" in the full names may end up being accurate for all cases again. So, I don't think we want to change that now.
I'm closing this issue, as this is a topic that needs discussion (on our bi-weekly calls) and cross-team coordination with the tech team - see legal meeting minutes from 7/20 for schedule of that

**Comment by jlovejoy** [comment]
on-going, larger discussion: also captured here: https://wiki.spdx.org/view/Legal_Team/only-operator-proposal

**Comment by jlovejoy** [comment]
also discussed here: https://github.com/spdx/license-list/issues/6

**Comment by jlovejoy** [comment]
have dealt with via bigger issue/conversation, so closing this issue
