### ISSUE TITLE
SPDX matching guidelines and common variant of BSD-3-Clause

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#399]
From Richard:

---------------------------------

I've noticed that a very common variant of what I think of as the 3-clause BSD license has this as its third clause:

3. The name of the author may not be used to endorse or promote
      products derived from this software without specific prior
      written permission.

Am I right that such a license, otherwise matching[1] what SPDX calls 'BSD-3-Clause', would not be considered a match to 'BSD-3-Clause' because clause 3 does not say 'Neither the name of the author nor the name of its contributors...'?

Asking because this seems to be the case from a strict reading of the SPDX matching guidelines, yet the result also seems to violate its spirit.

 Richard

[1]The non-use of 'contributors' results in changes to the stock disclaimer language too. I don't think it is clear whether this too would result in a non-match under the SPDX guidelines.

**Comment by jlovejoy** [comment]
I agree that these two variations are not legally different and should be accommodated in our matching markup. 
 
Text of clause 3 we have for comparison:

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

But would need help with someone from the technical side as to how to implement such markup

**Comment by jlovejoy** [comment]
marking as later, as need to make sure other lawyers agree

**Comment by bradleeedmondson** [comment]
discussed on legal call today; we agree that these two wordings are identical and they should be marked up to both match BSD-3 clause.

one thing to note is that we need to be careful not to do a simple match for both "may" and "may not" as their meanings are inverted in the two versions by language earlier in the sentence.

Would @wking or @goneall be able to write and test some &lt;alt&gt; tags that will match both, but not the hybrids "neither ... may _not_" or  "The name of the author _may_ be used..."?

**Comment by goneall** [comment]
I created a pull request #650 which has been unit tested with the 2 variants for clause 3 mentioned above.

**Comment by jlovejoy** [comment]
closing this issue as #650 has now been merged.
