### ISSUE TITLE
ISC copyright and URL

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#404]
See https://github.com/spdx/license-list/issues/7

**Comment by jlovejoy** [comment]
updated URL here

**Comment by jlovejoy** [comment]
note: need to add markup in copyright notice, also in the disclaimer
@goneall or @sam-ellis - could one of you do this?

**Comment by goneall** [comment]
@jlovejoy is the request  to allow <optional> and <alt> within the <copyrightText> elements?  If so, this is non-trivial to update the XML schema and tooling.  Can we postpone this enhancement until after we release the current license list?

**Comment by wking** [comment]
On Fri, Jul 28, 2017 at 11:51:03PM +0000, goneall wrote:
> @jlovejoy is the request to allow <optional> and <alt> within the
> <copyrightText> elements?

Currently *all* of copyright(Text) is optional [1].  But the matching
guidelines are a bit too ambiguous for machine detection.  For
example, it's clear (to a human reader) that the copyright notice
should be ignored (guideline 10), and that extraneous text at the end
of the license should be ignored (guideline 12), but other additional
text should result in a non-match (guideline 2.1.2).  However, there
are no rules about deciding if leading content is a copyright notice
(which should be ignored) or other substantive text (which should
result in a non-match).  To cover *that*, we'd want to require
copyright(Text) content to match, and, as you suggest, use <optional>
and <alt> within it to mark the replacable parts.

[1]: https://spdx.org/spdx-license-list/matching-guidelines
     entry 10 is about copyright notices

**Comment by wking** [comment]
Interestingly, BSD-2-Clause already has an `<alt>` entry inside it's `<copyright(Text)>`, in both the [master branch][1] and [schemadev][2].  Does that need to be temporarily removed until the tooling catches up with it, or can we go ahead and add similar markup to other licenses where the project's copyright statement (vs. the copyright statement for the license text itself) is often included in the provided text?

[1]: https://github.com/spdx/license-list-XML/blob/42b7ea5bba502f5f835a73dbdd96d5aa8b11ce1d/src/BSD-2-Clause.xml#L8
[2]: https://github.com/spdx/license-list-XML/blob/2b7dd5d067561b8e27c1efbc35fc88851356edd7/src/BSD-2-Clause.xml#L10

**Comment by goneall** [comment]
@wking Thanks for pointing out the BSD-2-Clause.  I checked and it does pass the XML validation and renders correctly.  We can embed the alt and var tags inside copyright text.

**Comment by jlovejoy** [comment]
resolved via https://github.com/spdx/license-list-XML/commit/95ffa76086f20c8032e8bbed4986e161a66d098e#diff-ee84c90ca26933944e7b2fc0c3bd14b4
