### ISSUE TITLE
duplicate license: Nunit

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#405]
From Julian Palard to the SPDX legal list:
----------

Hi,

I spotted the [Nunit](https://spdx.org/licenses/Nunit.html) is a duplicate of the [zlib/libpng License with Acknowledgement](https://spdx.org/licenses/zlib-acknowledgement.html) license.

So I think those two identifiers have to be merged. As the zlib license looks more legitimate (as a license name) than the nunit one (more a software name than a license name), I think the zlib-acknowledgement identifier is the right one for the license used in the Nunit software.

Bests,
Julien Palard

**Comment by jlovejoy** [comment]
need to determine which was sooner license (probably zlib/libpng) and then deprecate the newer one

**Comment by silverhook** [comment]
Zlib/libpng license is the original one. Nunit is based upon it.

According to [Wikipedia][wp], the zlib/libpng license was originally written by Jean-loup Gailly and Mark Adler in 1995. I get the same impression by looking at the license page on [zlib homepage itself][zlib]. So we might want to change the authorship/copyright notices of our copy Zlib license in SPDX.

Furthermore, on [Nunit’s old license page][nunit], it specifically states that:

> **License Note**
> 
> This license is based on the open source zlib/libpng license. The idea was to keep the license as simple as possible to encourage use of NUnit in free and commercial applications and libraries, but to keep the source code together and to give credit to the NUnit contributors for their efforts. […]

But I wonder where we got the [zlib-acknowledgement][za] from in the first place. The only page that we link to in SPDX is [Fedora‘s Licensing Wiki][fedora-zlib], where they specifically state that it is the same as NUnit license:

> This is from NUnit, other packages may have different notices/copyright holders: 

On the other hand, in the [Fedora’s Licensing Wiki][fedora-nunit] it also says that the NUnit license itself is based on MIT, which seems doubtful.

[wp]: https://en.wikipedia.org/wiki/Zlib_License
[zlib]: http://www.zlib.net/zlib_license.html
[nunit]: http://nunit.org/nuget/license.html
[za]: https://spdx.org/licenses/zlib-acknowledgement.html
[fedora-zlib]: https://fedoraproject.org/wiki/Licensing:ZlibWithAcknowledgement
[fedora-nunit]: https://fedoraproject.org/wiki/Licensing:Nunit

**Comment by jlovejoy** [comment]
agree Nunit should be deprecated. thanks for the research @silverhook !

**Comment by jlovejoy** [comment]
I've added the isDeprecated tag, see: https://github.com/spdx/license-list-XML/commit/6819b51dd1de7bd3e66bb9e6d0ba8bfce86f3737#diff-6df9521058a33bffa08fd067805d06cd
but am not sure how we identify the version number at which it was deprecated (e.g., 3.0) see last column in table: https://spdx.org/licenses/ 
All previous deprecated licenses were from the same release, but won't always be the case! I believe it pulled that from the spreadsheet. Perhaps we need to add a tag for this?
@goneall  thoughts?

**Comment by goneall** [comment]
There is an attribute `deprecatedVersion` for the license and exception.

I committed a change to add the deprecated version=3.0: https://github.com/spdx/license-list-XML/commit/4803f04e0c8117f76263d4cf527bfdebb1a4917d

**Comment by wking** [comment]
Can this issue be closed now that 6819b51d and 4803f04e have landed (no PRs?)?
