### ISSUE TITLE
Add deprecatedVersion attribute

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#408]
In the current spreadsheet, we maintain the license list version when a deprecated license was deprecated.  To track this in the XML, I propose we add an attribute "deprecatedVersion" whose value is the license list version when the license or exception was deprecated.

**Comment by bradleeedmondson** [comment]
+1 for this.

**Comment by jlovejoy** [comment]
discussed on June 8, 2017 legal call; done and implemented by @goneall 
data that is not displayed but included in Schema file (and updated Google doc)
