### ISSUE TITLE
example tag (for exceptions) not needed

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#412]
@goneall to remove tag (that was newly added)
@jlovejoy to check exceptions that had examples of use and add to notes field

**Comment by goneall** [comment]
Removed from the schema and the tools have been updated to deprecate the example.

**Comment by goneall** [comment]
Reopening to track the removal of examples from the exceptions (oops)

**Comment by goneall** [comment]
The example tag is not in the schema and all exceptions have been verified against the schema.  Now, I think we can close this issue.
