### ISSUE TITLE
Formatting Lists creates extra paragraphs

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#414]
In translating the XML into HTML, list items need a linefeed to be formatted properly as well as an indent.

To accomplish this, I am creating a paragraph with an indent attribute at the start of every list item.

Most of the license XML's include a paragraph tag after the bullet tag (see Apache-1.0.xml for an example).  This second paragraph tag creates a separate line feed. (e.g. the HTML ends up being <p style="margin-left: 40px;"> 1. <p>..." for the first bullet in Apache 1.0).

It seems like the best way to fix this is to remove the first paragraph tags that are inside the list items (if they exist).

I can add this to the utility which translates the old XML format to the new XML format, but it may remove more paragraphs than desired.

@bradleeedmondson Let me know what you think.

**Comment by wking** [comment]
On Mon, Jun 12, 2017 at 06:50:42PM -0700, goneall wrote:
> Most of the license XML's include a paragraph tag after the bullet
> tag (see Apache-1.0.xml for an example).  This second paragraph tag
> creates a separate line feed. (e.g. the HTML ends up being <p
> style="margin-left: 40px;"> 1. <p>..." for the first bullet in
> Apache 1.0).

I think we should fix this by keeping the paragraph tags and updating
the styling.  Adding a left-margin to p tags feels a bit strange
anyway.  Perhaps you just want padding on the wrapping div (or
whatever tag holds the full license)?

> It seems like the best way to fix this is to remove the first
> paragraph tags that are inside the list items (if they exist).

This will make things awkward when you need multiple paragraphs within
a single list entry.  I'd rather keep them, and just fix the styling.

**Comment by goneall** [comment]
I believe we want to do some formatting to the lists, otherwise there is no way to indicate whether text should be indented etc.

@wking Can you provide a proposed translation to HTML which would format the list properly?

Here is a snippet from the current Apache-1.0:

     <list>
        <item>
            <bullet>1.</bullet>
            <p>Redistributions of source code must retain the above copyright notice, this list of conditions
             and the following disclaimer.</p>
        </item>
        <item>
            <bullet>2.</bullet>
            <p>Redistributions in binary form must reproduce the above copyright notice, this list of conditions
             and the following disclaimer in the documentation and/or other materials provided with the
             distribution.</p>
        </item>
        <item>
            <bullet>3.</bullet>
            <p>All advertising materials mentioning features or use of this software must display the following
             acknowledgment: "This product includes software developed by the 
            <alt match=".+" name="organizationClause3">Apache Group for use in the Apache HTTP server project
            (http://www.apache.org/)</alt>." 
          </p>
        </item>
        <item>
            <bullet>4.</bullet>
            <p>The 
            <alt match="name|names|name\(s\)" name="nameClause4">name</alt>
               <alt match=".+" name="organizationClause4">"Apache Server" and "Apache Group"</alt> must
            not be used to endorse or promote products derived from this software without prior written
            permission. For written permission, please contact 
            <alt match=".+" name="contactClause4">apache@apache.org</alt>.
          </p>
        </item>
        <item>
            <bullet>5.</bullet>
            <p>Products derived from this software may not be called 
            <alt match=".+" name="nameClause5">"Apache"</alt> nor may 
            <alt match=".+" name="name2clause5">"Apache"</alt> appear in their name, without prior written
            permission of 
            <alt match=".+" name="name3clause5">the Apache Group</alt>. 
          </p>
        </item>
        <item>
            <bullet>6.</bullet>
            <p>Redistributions of any form whatsoever must retain the following acknowledgment:</p>
            <p>"This product includes software developed by <alt match=".+" name="nameClause6">the 
          Apache Group for use in the Apache HTTP server project (http://www.apache.org/)</alt>.</p>
        </item>
      </list>

**Comment by bradleeedmondson** [comment]
This is pushing a bit outside my area of expertise, but I tend to think we should leave them in as well. Can we solve this problem by completely removing all styling (except maybe bold) from bullets? I wouldn't mind if list item 1. in your example rendered this:
`1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.`

**Comment by bradleeedmondson** [comment]
Although now that I think about it, maybe that means the bullets should be moved inside the &lt;p&gt; tags?

**Comment by wking** [comment]
On Tue, Jun 13, 2017 at 11:09:22AM -0700, goneall wrote:
>      <list>
>         <item>
>             <bullet>1.</bullet>
>             <p>Redistributions of source code must retain the above copyright notice, this list of conditions
>              and the following disclaimer.</p>
>         </item>
>         …
>         <item>
>             <bullet>6.</bullet>
>             <p>Redistributions of any form whatsoever must retain the following acknowledgment:</p>
>             <p>"This product includes software developed by <alt match=".+" name="nameClause6">the 
>           Apache Group for use in the Apache HTTP server project (http://www.apache.org/)</alt>.</p>
>         </item>
>       </list>

As @bradleeedmondson points out, we want the XML source to be:

 <item><p><bullet>1.</bullet> Redistribution of source…

if you don't want a newline after the bullet.  And the translated HTML
(including the previous paragraph from the Apache 1.0 text and adding
a wrapping div would be:

  <div class="license">
    <p>Redistribution and use in source…</p>
    <ul>
      <li><p>1. Redistribution of source…</p></li>
      <li>…</li>
      <li>
        <p>6. Redistributions of any form…</p>
        <p>"This product includes…</p>
      </li>
    </ul>
  </div>

That gets the usual ul/li indents without any need for custom styling.
If you want everything to get indented a bit, just add CSS like:

  div.license {
    padding-left: 40px;
  }

or whatever.  But that styling should almost certainly not be part of
a “canonical” HTML translation, since it's clearly styling and not
content.

**Comment by goneall** [comment]
This seems like a good approach with a couple caveats.

The above snippet will render bullets in the list items.  We could change the above to <ul style="list-style: none;">.  I realize it is better to have styles externalized, but I don't have control over all the style for this website and would like to ensure the license text renders correctly.

I also believe we will need to move all paragraphs before the bullets, otherwise we will get an undesirable linefeed between the bullet and the text.

Two questions:
- Should I use the <ul style="list-style:none">?
- Should we change all the paragraph tags to before the bullets in all the license text or should we do some automated translation?

**Comment by bradleeedmondson** [comment]
Render looks a bit weird -- retry? @goneall

**Comment by wking** [comment]
On Tue, Jun 13, 2017 at 12:40:45PM -0700, Bradlee H. Edmndson wrote:
> Render looks a bit weird -- retry? @goneall 

GitHub hides tags in Markdown comments (maybe as some sort of XSS
protection?).  If you're commenting via their web UI, it's probably
best to backtick your examples (e.g. `<p>`).

**Comment by wking** [comment]
On Tue, Jun 13, 2017 at 12:31:57PM -0700, goneall wrote:
> The above snippet will render bullets in the list items.  We could
> change the above to <ul style="list-style: none;">.

Good idea.

> I realize it is better to have styles externalized, but I don't have
> control over all the style for this website and would like to ensure
> the license text renders correctly.

Indents for paragraphs and lists don't seem like they have unique
“correct” values to me, so I'd rather punt where possible.  Whoever
*does* have control over the page style can decide if/how they'd like
to indent whatever.

It would be nice to mark the bullet portion more appropriately in
HTML, and you can sometimes do that (e.g. with the value attribute
[1]), but your <bullet> is more generic than li's value, so it won't
work all the time.  Still, it may be worth adjusting the XML schema so
you can use ol/ul as appropriate and set value where that is
sufficient (and it would keep the bullet values out of the <p>).  Then
fall back to explicit <bullet> entries (inside a <p> and grouped by a
<ul>) where nothing else makes sense.

[1]: https://www.w3.org/TR/html5/grouping-content.html#attr-li-value

**Comment by goneall** [comment]
I fixed the rendering - at least it looks find on my web page.  You may need to reload the page.  Let me know if it is still a problem.

**Comment by goneall** [comment]
@wking I've also thought about using attributes on the HTML list.  It would leave the list item enumeration and rendering to the browser which may not be precise enough for the license text.  To take advantage of the attribute, the bullets would not be included in the XML - just an attribute would be added to the list which would automatically number the lists based on the attribute.

Maybe a release 2 feature?

**Comment by wking** [comment]
> I fixed the rendering…

I think you're still missing backticks around your first `<ul …>` example:

![render](https://user-images.githubusercontent.com/209920/27102210-3fa82a6c-5039-11e7-85eb-c472b2b90256.png)

> I've also thought about using attributes on the HTML list. It would leave the list item enumeration and rendering to the browser which may not be precise enough for the license text.

Right.  We'd have to fall back to something else if we wanted a bullet like “1.13.” (from `CDDL-1.1`).  But I think for things like `a` vs. `a)` vs. `(a)` we'd be fine collapsing to HTML's `a` `type`, especially since bullet values are going to be ignored in matching.  And we could add our own attribute for “this is the original plain-text value for this bullet” so folks could recover that when converting the XML to text/plain.  That would reduce the “how do we handle custom bullets” issue to the handful of license that don't fit one of HTML's numbering schemes.

Another alternative would be to use manually numbered headers instead of lists, which may be a better fit for things like “1.13.” anyway.

**Comment by goneall** [comment]
I'll use "<ul style="list-style:none">" for all the lists and <li> for the items.  I'll preserve the paragraph tags as is.

After thinking about it some more, it would be easier to move the paragraph tags outside the bullet using search and replace and not mess with the XML conversion utility. 

I'll close this issue and we can track individual license formatting issues with separate issues.

@wking and @bradleeedmondson thanks for the review and suggestions

**Comment by bradleeedmondson** [comment]
Just going through my backlog here and I would say this is still a live meta-issue that should have an open issue until the proposed changes are made throughout the repo. We could do a new issue (just outlining what we want to do) or reopen this one. 

@goneall @wking agree?

**Comment by wking** [comment]
On Thu, Aug 03, 2017 at 11:27:08AM -0700, Bradlee H. Edmndson wrote:
> We could do a new issue (just outlining what we want to do) or reopen this one.

I'm fine re-opening this issue, but I'm not sure what we want to do
;).  I've just been trying to track whatever approach seems popular in
master.  @goneall, maybe you want to take another stab at formatting
[1]?  I suggest using triple-backticks [2] around your XML snippet.

[1]: https://github.com/spdx/license-list-XML/issues/414#issuecomment-308421121
[2]: https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks

**Comment by bradleeedmondson** [comment]
I think the result of this ticket was that we agreed to move the b-tags inside the p-tags:
```
<li>
      <p><bullet>1.</bullet> Redistribution of source… lorem ipsum paragraphum.</p>
</li>
```

I just wanted to make sure we actually did that before release, and since I haven't thought of a way to do it programmatically, I have (perhaps naively) assumed we might need to do it by hand. Either way, my thinking was that we are tracking all release-blocking items as GH issues in this repo (again an assumption -- not 100% sure @jlovejoy would agree) and that therefore we should have something open for this problem & planned solution.

**Comment by goneall** [comment]
@wking @bkeepers We should revisit after we switch to the new XML format.  I take care of some of this during the translation.  No problem keeping this open until we verify it has been fixed.

**Comment by goneall** [comment]
@wking @bradleeedmondson You can review https://spdx.org/licenses/preview/ which has the generated website from the schema branch (which is a little behind the master branch)

**Comment by bradleeedmondson** [comment]
Perhaps this re-raises the question of whether we need the &lt;p&gt; tag at all? 

If we do want to keep it, then I think we'd want to add it back in the schemadev branch rather than leaving the text in bare &lt;li&gt;s (e.g. as we currently have at line 55 in https://github.com/spdx/license-list-XML/blob/schemadev/src/AGPL-1.0.xml).

**Comment by wking** [comment]
On Thu, Aug 03, 2017 at 08:34:44PM +0000, Bradlee H. Edmndson wrote:
> Perhaps this re-raises the question of whether we need the <p> tag at all? 

We need it for list entries that have multiple paragraphs (e.g. [1]).

> If we do want to keep it, then I think we'd want to add it back in
> the schemadev branch rather than leaving the text in bare
> <li>s (e.g. as we currently have at line 55 in

Yeah.  I'm not a fan of the:

  <item>
    <bullet>0.</bullet>
    This License applies to any program or other work which contains a notice placed by the copyright
      holder saying it may be distributed under the terms of this Affero General Public License. The
      …
      the term "modification".) Each licensee is addressed as "you".
    <p>Activities other than copying, distribution and modification are not covered by this License;
      …
      the Program does.</p>
  </item>

that's in schemadev now.

[1]: https://github.com/spdx/license-list-XML/blob/b42efd5a6339ef7248d79d53a830b7d2caa07bf8/src/GPL-3.0.xml#L94-L111

**Comment by wking** [comment]
On Thu, Aug 03, 2017 at 08:19:15PM +0000, goneall wrote:
> … the schema branch (which is a little behind the master branch)

Keeping these syncronized seems like more trouble than it's worth.
Can you file a PR with the schemadev stuff, and when it lands we can
go convert any remaining open PRs to the new format?

**Comment by goneall** [comment]
@wking @bradleeedmondson  Let's revisit after we switch over to the new XML format.  I don't want to invest too much effort before we switch since the new XML may have a different set of issues.

**Comment by goneall** [comment]
OK - now that we have the [license list preview](https://spdx.org/licenses/preview/) up and everything is converted to the new XML format, @wking and @bradleeedmondson what do you think of the item and bullet formatting?

**Comment by bradleeedmondson** [comment]
goneall:
> OK - now that we have the license list preview up and everything is converted to the new XML format, @wking and @bradleeedmondson what do you think of the item and bullet formatting?

Looks good to me!

**Comment by goneall** [comment]
@bradleeedmondson Thanks for the review

Are we OK to close this issue?

**Comment by wking** [comment]
I'm [still][1] not excited about the lack of a leading `<p>` (e.g. [here][2]).  But the way you have it seems to render ok.  So I'd rather leave this open until we can get a leading `<p>` for the initial paragraph, but think that the current status is good enough for this issue to be punted from “immediate release” to “next release”.

[1]: https://github.com/spdx/license-list-XML/issues/414#issuecomment-320094253
[2]: https://github.com/spdx/license-list-XML/blob/9cd31d098d3943e06e58d652efb3067977b1f9a2/src/GPL-2.0.xml#L199-L210

**Comment by jlovejoy** [comment]
this has been resolved; spacing now rendering properly
