### ISSUE TITLE
Replace osi-approved (a.k.a. isOsiApproved) with an OSI-ID property?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#417]
Currently we have an `osi-approved` property (e.g. [here][1]).  In the `schemadev` branch, that same information is represented with `isOsiApproved` (e.g. [here][2]).  I think it would be more useful to replace that boolean with an OSI-ID property (`osiId`?  `OSI-ID`?).  For example:

```xml
<license licenseId="CECILL-1.0" osiId="CECILL-1.0" …>…</license>
```

That would let us gracefully handle situations like [0BSD][3], which the OSI calls [FPL-1.0.0][4]:

```xml
<license licenseId="0BSD" osiId="FPL-1.0.0" …>…</license>
```

Consumers currently have to [assume the SPDX and OSI IDs match][5] and [carry manual lists of cases where that is not true][6].

[1]: https://github.com/spdx/license-list-XML/blob/65e7b17b67400a590c27b1db27060ab4f904a247/src/CDDL-1.0.xml#L1
[2]: https://github.com/spdx/license-list-XML/blob/schemadev/src/CDDL-1.0.xml#L3
[3]: https://github.com/spdx/license-list-XML/blob/65e7b17b67400a590c27b1db27060ab4f904a247/src/0BSD.xml
[4]: https://opensource.org/licenses/FPL-1.0.0
[5]: https://github.com/OpenSourceOrg/licenses/blob/f7ff223f9694ca0d5114fc82e43c74b5c5087891/licenses/spdx/scrape.py#L31-L34
[6]: https://github.com/OpenSourceOrg/licenses/blob/f7ff223f9694ca0d5114fc82e43c74b5c5087891/licenses/spdx/manual.json#L3-L7

**Comment by wking** [comment]
Another reason for recording the OSI ID is that it gives you access to more data.  For example, if you only know that the BSD-3-Clause license is OSI approved, that's that.  But if you know that [its OSI ID is BSD-3][1], you can ask the OSI what they think about it directly:

```
$ curl -s https://api.opensource.org/license/BSD-3 | jq .
{
  "id": "BSD-3",
  "identifiers": [
    {
      "identifier": "BSD-3-clause",
      "scheme": "DEP5"
    },
    {
      "identifier": "BSD-3-Clause",
      "scheme": "SPDX"
    },
    {
      "identifier": "License :: OSI Approved :: BSD License",
      "scheme": "Trove"
    }
  ],
  "links": [
    {
      "note": "Wikipedia Page",
      "url": "https://en.wikipedia.org/wiki/BSD_licenses#3-clause"
    },
    {
      "note": "OSI Page",
      "url": "https://opensource.org/licenses/BSD-3-Clause"
    }
  ],
  "name": "BSD 3-Clause License",
  "other_names": [
    {
      "name": "Revised BSD License",
      "note": null
    },
    {
      "name": "Modified BSD License",
      "note": null
    },
    {
      "name": "New BSD License",
      "note": null
    }
  ],
  "superseded_by": null,
  "keywords": [
    "osi-approved",
    "popular",
    "permissive"
  ],
  "text": [
    {
      "media_type": "text/html",
      "title": "HTML",
      "url": "https://opensource.org/licenses/BSD-3-Clause"
    }
  ]
}
```

[1]: https://github.com/OpenSourceOrg/licenses/blob/f7ff223f9694ca0d5114fc82e43c74b5c5087891/licenses/spdx/manual.json#L3-L9

**Comment by goneall** [comment]
@jlovejoy Is this a field the legal team would be willing to maintain?  

I recall a discussion with OSI where they were going to make their license list programatically available.  This may be a solution to the use case described.

@wking if were were to add this information, I would add it as a separate field to maintain backwards compatibility.

**Comment by kestewart** [comment]
@wking  Others are already using the isOSIApproved field so we'll have to be careful - see use in: 
https://github.com/OpenSourceOrg/licenses/blob/master/licenses/spdx/scrape.py

**Comment by wking** [comment]
> @wking Others are already using the isOSIApproved field so we'll have to be careful - see use in:
https://github.com/OpenSourceOrg/licenses/blob/master/licenses/spdx/scrape.py

I'd patch that to use the SPDX -> OSI ID transkation.  The OSI folks should not be asking *us* whick licenses they've approved.

For backwards-compat more generally, I'd contine to supply the property in our JSON.  I'd just supply it automatically (vs. pulling it from some human-maintained XML source).

**Comment by swinslow** [comment]
Discussed on 2019-07-30 tech team call, agreed to close this, not adding osiID tags.
