### ISSUE TITLE
Decide whether to further templatize NASA-1.3 license

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#421]
Recently merged the NASA-1.3 license in #137, but it has several sections that arguably should be templatized further, e.g. lines 18-20, line 65, etc. in 034386eb7380f49af58910504b3ec126ec8b4b34

We should decide here whether we want to do this, or not (as we might not, if we consider this more of a one-off or vanity license that is only used verbatim).

**Comment by jlovejoy** [comment]
discussed on Aug 23 call: 2 questions:
should it need variable field markup for all blanks? yes
copyright notice in section B added as standard header (with markup)? no, this is really a copyright notice and not a license notice/header

**Comment by jlovejoy** [comment]
closing issue, as pull request has been submitted
