### ISSUE TITLE
Handling stale URLs?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#433]
There are a number of licenses with stale URLs (e.g. the upstream URLs for the [AFL-3.0][1] and [Condor-1.1][2]).  @bradleeedmondson [pointed out][3] that there is no policy (or at least, no easily discoverable policy) around how those links are maintained.  Should stale URLs be:

* Removed from the XML source (we'd still have them in the Git archives).
* Kept in the XML source…
    * … with known-dead markup (e.g. `<url dead="true">…</url>`).
    * … without special markup.
* Replaced by Internet Archive links to old copies of the original URL (like [this][4]).

The presence of Internet Archive links in the current master (e.g. [here][5]) suggests that as the preferred approach, but it would be good to have an official legal-team policy on this.

If we decide to go with archive.org replacements, is archive.org the only acceptable archival source?  Or are other links (e.g. into mailing list archives, see my comments in #431) also acceptable?

[1]: https://github.com/spdx/license-list-XML/pull/11#r63288907
[2]: https://github.com/spdx/license-list-XML/pull/430
[3]: https://github.com/spdx/license-list-XML/pull/11#r131222292
[4]: https://github.com/spdx/license-list-XML/pull/430/commits/6a6384bd99d178f69e6b035f7ba676a1ad9e6772
[5]: https://github.com/spdx/license-list-XML/blob/b42efd5a6339ef7248d79d53a830b7d2caa07bf8/src/OSL-2.0.xml#L3

**Comment by bradleeedmondson** [comment]
I agree that this should be made explicit, but on reflection I don't think this needs to hold up the next release. Removing immediate-release milestone.

**Comment by wking** [comment]
While there is, as far as I know, still no official policy on this, recent legal-team decisions ([here][1], [here][2], and [here][3]) have supported a “keep dead links without special markup, and add working Internet Archive links where they can be found” approach.  Unmarked, known-dead links in the XML is my least favorite approach to handling known-dead links, but that's still probably the precedent to follow until we get an official policy.

[1]: https://github.com/spdx/license-list-XML/pull/430#issuecomment-329553704
[2]: https://github.com/spdx/license-list-XML/pull/427#issuecomment-329555901
[3]: https://github.com/spdx/license-list-XML/pull/419#issuecomment-329563093

**Comment by wking** [comment]
As a counter-example to the above “keep dead links without special markup, and add working Internet Archive links where they can be found”, in 2e89b5e28 we replaced a dead http://www.isc.org/… URL with a working https://www.isc.org/….  It's possible that the consistent policy is:

> When an [authority][1] changes their canonical URL, replace the previous entry with the new canonical URL.  When an [authority][1] ceases to serve the old URL but does not provide a replacement, keep the dead URL without special markup but add a new Internet Archive link (where it can be found) to the removed content.

It's also possible that we've handled the same situation in different ways in the absence of an explicit policy (although there are some policy sketches in the [minutes of the 2017-09-14 legal meeting][1]), and that we will eventually declare a policy that is not consistent with all of our previous actions.

[1]: https://wiki.spdx.org/view/Legal_Team/Minutes/2017-09-14

[1]: https://tools.ietf.org/html/rfc3986#section-3.2

**Comment by wking** [comment]
Collecting precendent, #573 just landed with the “removed from the XML source” approach.  One possible difference is that #419, #430, and #436 were bringing in a new Internet Archive link, while #573 was using a different enlightenment.org link.  Perhaps the URL authority has an impact on the implicit policy.  On the other hand, #427 tracked the Freetype project from the defunct freetype.fis.uniroma2.it to the project's new location under git.savannah.gnu.org, and in that location [the legal team still wanted to keep the dead URL][1].  I'm not sure how to square #573 with #427, but the URL authority and current canonical project locations may be a useful variables to consider when formalizing our policy.

[1]: https://github.com/spdx/license-list-XML/pull/427#issuecomment-329555901

**Comment by jlovejoy** [comment]
I think we resolved this issue when we added the following text to the Overview page, field description part C
"Note that the source URL may refer to an original URL for the license which is no longer active. We don't remove inactive URLs. New or best available URLs may be added."

at https://spdx.org/spdx-license-list/license-list-overview
