### ISSUE TITLE
Remove CeCILL-C fr (for now)

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#445]
We've said the canonical CeCILL C license file will, for now, be the English one. @goneall to remove CeCILL-C fr file after conversion work is done. (Or during would probably be fine too.)

**Comment by bradleeedmondson** [comment]
Just didn't want to forget. 

cc: @zvr

**Comment by goneall** [comment]
Added pull request #447 to remove

**Comment by wking** [comment]
With #447 merged, can this be closed?

**Comment by bradleeedmondson** [comment]
Yep
