### ISSUE TITLE
paragraph header in prev paragraph / spacing of paragraphs inconsistent

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#449]
This line is a paragraph header that is incorrectly included at end of previous paragraph:

https://github.com/spdx/license-list-XML/blob/19dcfd1b31c7e81582e5f23b91c0667544d4a678/src/GPL-2.0.xml#L251

good eye @wking -- this was how most of the headers came out of the initial conversion tool (bash script), so this is just one that we missed when cleaning them up by hand. will fix.

**Comment by jlovejoy** [comment]
also doing some weird stuff in GPL-3.0
check again after next PREVIEW generation by @goneall

**Comment by jlovejoy** [comment]
Gary and I have resolved this so that the licenses render with spacing as they did before
