### ISSUE TITLE
OFL-1.1 standard license header

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#451]
We [currently don't declare `standardLicenseHeader` for the OFL-1.1][1], but they define one in their license document (above the title):

```
$ curl -sL 'http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web' |
>   w3m -T text/html -dump | grep -A7 'Copyright (c)' | cut -b 15-
Copyright (c) <dates>, <Copyright Holder> (<URL|email>),
with Reserved Font Name <Reserved Font Name>.

Copyright (c) <dates>, <additional Copyright Holder> (<URL
|email>),
with Reserved Font Name <additional Reserved Font Name>.

Copyright (c) <dates>, <additional Copyright Holder> (<URL|
email>).

This Font Software is licensed under the SIL Open Font License,
Version 1.1.

This license is copied below, and is also available with a FAQ
at: http://scripts.sil.org/OFL
```

And they *also* [discuss their recommendations for using it in their FAQ][2]:

> * Put your copyright and Reserved Font Names information at the beginning of the main OFL.txt file in place of the dedicated placeholders (marked with the `<>` characters). Include this file in your release package.
> * Put your copyright and the OFL text with your chosen Reserved Font Name(s) into your font files (the copyright and license fields). A link to the OFL text on the OFL web site is an acceptable (but not recommended) alternative. Also add this information to any other components (build scripts, glyph databases, documentation, test files, etc). Accurate metadata in your font files is beneficial to you as an increasing number of applications are exposing this information to the user. For example, clickable links can bring users back to your website and let them know about other work you have done or services you provide. Depending on the format of your fonts and sources, you can use template human-readable headers or machine-readable metadata. You should also double-check that there is no conflicting metadata in the font itself contradicting the license, such as the fstype bits in the os2 table or fields in the name table.

The first point suggests they intend the full copyright/license to be used as you'd use the GPL-3.0 license text (for example), by dropping it in a project level file.

The “Also add this information to any other components (build scripts…” in the second point suggests they intend the full copyright/license to also be their standard license header.  Our current XML schema doesn't provide an easy way to declare that the `standardLicenseHeader` is the same as the license text, but maybe it should?  Perhaps via some generic XML reference mechanism?  Otherwise we're going to have to duplicate this information in both places.

[1]: https://github.com/spdx/license-list-XML/blob/9984ebd50cf621010d9b24b95fa7dd47e42ba79a/src/OFL-1.1.xml
[2]: http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#83afb016

**Comment by mlinksva** [comment]
> This license is copied below

Also from the FAQ, emphasis added:

> Put your copyright **and** the OFL text with your chosen Reserved Font Name(s) into your font files (the copyright and license fields).

Doesn't look to me as if the copyright/license/reserved font notices above the license text are intended to be used as a standalone header.

**Comment by wking** [comment]
I agree, and think they intend the full copyright+license in`OFL.txt`, with exactly the same full copyright+license in script headers.

**Comment by mlinksva** [comment]
Ah, that's what you were saying already with "is the same as the license text". I didn't read closely enough!

**Comment by mlinksva** [comment]
(Of course that's also how MIT/ISC/BSD are sometimes used as headers too, with header==full license.)

**Comment by wking** [comment]
On Sat, Oct 21, 2017 at 09:44:03PM +0000, Mike Linksvayer wrote:
> Of course that's also how MIT/ISC/BSD are sometimes used as headers
> too, with header==full license.

Good point.  Any mechanism we use for “the standard license header is
the same as the license text” should get used for them as well, even
if that mechanism is “copy/paste the whole template under each tag”.
And on the “under each tag” front, I'd like to land #452 before we
start doing lots of XML-referencing or copy/pasting ;).

**Comment by wking** [comment]
Can someone with push access re-open this?  #491 [did not address this issue][1].

[1]: https://github.com/spdx/license-list-XML/pull/491#pullrequestreview-79017224

**Comment by bradleeedmondson** [comment]
Re-opened as unaddressed.

Does this need to be fixed for immediate release (next license list)?

**Comment by wking** [comment]
> Does this need to be fixed for immediate release (next license list)?

Not having the standard header marked up for these licenses reduces their usefullness.  But we've never had their headers before, so I don't see a problem with punting to a later release.

**Comment by bradleeedmondson** [comment]
I think we'll punt to later release, esp. since this question affects many short licenses where the "header" might be the whole license. Not sure we need to declare anything for that case, as then you just have a license-text match, no?

In ay event we can figure this out after the next license-list release.

**Comment by wking** [comment]
On Tue, Dec 19, 2017 at 09:51:02PM +0000, Bradlee H. Edmndson wrote:
> Not sure we need to declare anything for that case, as then you just
> have a license-text match, no?

Ah, I hadn't considered that angle.  I'm ok with that, but if we go
that route I'd really like to see it called out in the documentation
(which is currently in [1], although I'd like to see documentation
that's local to this repo #495).

[1]: https://spdx.org/spdx-license-list/license-list-overview

**Comment by jlovejoy** [comment]
As per the field description in https://spdx.org/spdx-license-list/license-list-overview
I don't think the short licenses fit this description:
* Should only include text intended to be put in the header of source files or other files _as specified in the license or license appendix when specifically delineated_
* Leave this field blank if there is no standard header as specifically defined in the license

The Standard Header field is intentionally narrowly defined. There are, of course, lots of variations and there has been discussion of trying to capture some of those - perhaps in a different field so as not to confuse with what the license actually suggests. We have also discussed the idea of adding the SPDX-License-Identifier notice as has getting increased use (see https://github.com/ARM-software/arm-trusted-firmware/blob/master/bl1/bl1_fwu.c for example) and which is recommended in the spec, Appendix V. But for the time being, I think we will be consistent with our definition.

**Comment by wking** [comment]
From a consumer standpoint, there may also be a distinction between "upstream recommends you put the whole license in the header" and "upstream makes no recomendation about the header".  So I'm back to thinking we'll (eventually) need some sort of explicit markup for this.

**Comment by swinslow** [comment]
Given the discussion above, and given the recommendation of the OFL stewards that the whole OFL text should be included in a font file, I'm inclined to say that it's correct that no standard license header is included here. Note also that the OFL identifiers were updated to include separate copyright notice formats for Reserved Font Names vs. not. Given all that, I would suggest closing this issue.

**Comment by swinslow** [comment]
Discussed on 2021-12-09 legal team call, agreed that no standard license header section should be added.
