### ISSUE TITLE
CC-BY-ND-2.0 is a duplicate of CC-BY-ND-3.0

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#479]
The CC-BY-ND-2.0.xml file contains content for CC-BY-ND-3.0.  A diff of the content for the 2 files only shows minor differences.

**Comment by goneall** [comment]
This looks like it is related to pull request #455

**Comment by wking** [comment]
And this issue is an exact dup of #448.  I think we can close this one in favor of the older issue and PR.

**Comment by goneall** [comment]
Oops - somehow I missed #448 when I was reviewing the issues over the weekend.  Closing this issue as a duplicate.
