### ISSUE TITLE
MPL-2.0 disclaimer, limitation un-conspicoufied

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list-XML#493]
Probably not important for license matching, but to the extent the SPDX texts and site are treated as canonical and copied by others, possibly unfortunate.

http://lu.is/blog/2012/08/19/a-quick-note-on-conspicuous-text-also-known-as-all-caps/ describes how the Mozilla-provided HTML and text versions are highlighted without using all caps.

Maybe there is some annotation that would allow some form of highlighting to be retained in versions SPDX publishes? I don't see anything offhandedly in https://github.com/spdx/license-list-XML/blob/master/schema/ListedLicense.xsd

**Comment by wking** [comment]
I'm in favor of adding [`<strong>`][1] (or `<conspicuous>` or whatever) to our XML schema.

[1]: http://w3c.github.io/html/textlevel-semantics.html#the-strong-element

**Comment by goneall** [comment]
After reading the link, having some way of communicating conspicuous text seems like a good idea.

Since this would have semantic meaning, I would suggest ```<conspicuous>```. 

When generating the website, we can add style to text enclosed in the tags.

Suggest this for a future release of the license list.

**Comment by wking** [comment]
On Sun, Nov 26, 2017 at 07:46:05PM +0000, goneall wrote:
> Since this would have semantic meaning, I would suggest ```<conspicuous>```. 

From the HTML 5 spec for ‘strong’ [1]:

  The strong element represents strong importance, seriousness, or
  urgency for its contents.

Which sounds right to me.  I'm ok with coining our own ‘conspicuous’,
but if we do that, I think we should have some motivation for passing
over ‘strong’.  I can't think of a reason myself.

[1]: http://w3c.github.io/html/textlevel-semantics.html#the-strong-element

**Comment by mlinksva** [comment]
For amusement or possible insight, cc @tieguy

**Comment by goneall** [comment]
> From the HTML 5 spec for ‘strong’ [1]:
  The strong element represents strong importance, seriousness, or
  urgency for its contents.

>Which sounds right to me.  I'm ok with coining our own ‘conspicuous’,
but if we do that, I think we should have some motivation for passing
over ‘strong’.  I can't think of a reason myself.

The article linked above has this text:
```So if not ALL CAPS, what actuallyisrequired? This varies from rule to rule, unfortunately. But in the UCC, conspicuous is defined as text a reasonable person “ought to have noticed”, which includes:

“(A) a heading in capitals equal to or greater in size than the surrounding text, or in contrasting type, font, or color to the surrounding text of the same or lesser size; and

(B) language in the body of a record or display in larger type than the surrounding text, or in contrasting type, font, or color to the surrounding text of the same size, or set off from surrounding text of the same size by symbols or other marks that call attention to the language.”

(From UCC 1-201(b)(10); same text also appears in UCC 2-103(1)(b)(i).)```

I think the two definitions are similar but not exactly the same.  I still prefer a term separate from ```<strong>```

**Comment by wking** [comment]
On Mon, Nov 27, 2017 at 07:24:34PM +0000, goneall wrote:
> > But in the UCC, conspicuous is defined as text a reasonable person
> > “ought to have noticed”, which includes…

So “conspicuous text has more *display* constraints than the HTML 5
spec assigns to <strong>”?  In fact, HTML 5 doesn't get specific about
the display at all.  If the semantics are the same (which you don't
seem to be disputing), can't we use <strong> in the XML templates, and
leave it to conservative XML→HTML translators (e.g. “I'm not
comfortable leaving it up to the browser's <strong> implementation to
make this sufficiently conspicuous”) to add whatever styling they feel
is appropriate?

Or do you see a semantic distinction between <strong> and conspicuous
text?

**Comment by goneall** [comment]
> Or do you see a semantic distinction between <strong> and conspicuous text?

I don't really have a strong opinion, but if we use a different term we don't even have to decide if the semantics are the same.  We can just reference the legal semantic definitions.

**Comment by wking** [comment]
On Mon, Nov 27, 2017 at 08:07:39PM +0000, goneall wrote:
> I don't really have a strong opinion, but if we use a different term
> we don't even have to decide if the semantics are the same.  We can
> just reference the legal semantic definitions.

And then have different tags if non-US countries have different
semantics or display requirements?  If <strong> isn't a great match,
maybe we want <warranty> (wasn't there an issue about that recently?)
and similar for things that are impacted by display requirements like
this in some jurisdiction?

Looking at the upstream text, their HTML uses <em>:

  $ curl -s https://www.mozilla.org/en-US/MPL/2.0/ | grep 'as is'
  <p><em>Covered Software is provided under this License on an “as is” basis,…

I don't think <em> is a great fit, now that HTML5 is about stress
emphasis [1].  Their plain-text version uses some exciting asterisk
boxing:

  $ curl -s https://www.mozilla.org/media/MPL/2.0/index.815ca599c9df.txt | grep -B5 'as is'
  ************************************************************************
  *                                                                      *
  *  6. Disclaimer of Warranty                                           *
  *  -------------------------                                           *
  *                                                                      *
  *  Covered Software is provided under this License on an "as is"       *

So whatever we do, we're currently trying to guess at the semantics
upstream intended based on their styling (or, with <em>, their
questionable semantics ;).  We probably want to go upstream and figure
out what they're comfortable with, since this is really about
expressing upstream intent now that folks expect renderings beyond
text/plain.  And we probably need a lot of <optional> and <alt> blocks
in our MPL-2.0.xml to cover those asterisks :p.

[1]: https://www.w3.org/TR/html5/text-level-semantics.html#the-em-element
     “The em element also isn't intended to convey importance; for
     that purpose, the strong element is more appropriate.”

**Comment by pombredanne** [comment]
The plain text version should what is used there IMHO https://www.mozilla.org/media/MPL/2.0/index.txt
But @mlinksva ever since texts have started to be tagged in SPDX IMHO they cannot be used anymore as a reference.

**Comment by tieguy** [comment]
Note, generally, that later licenses have not chosen to go this route (as far as I know) so perhaps just a hack to handle MPL is sufficient. (I'd be happy to hear if I'm wrong!)

On re-reading the HTML5 spec (which I think may still have been in draft when we published MPL v2?) I would definitely choose strong over em. I may even try to get that fixed upstream on the MPL website, though low priority for me. 

@pombredanne yes, that's the correct plain text to use.

**Comment by swinslow** [comment]
Looking back at this old issue, I think there's basically three options:

1. do nothing, leave as-is; or
2. update the [MPL-2.0 test text file](https://github.com/spdx/license-list-XML/blob/master/test/simpleTestForGenerator/MPL-2.0.txt) (and [-no-copyleft-exception](https://github.com/spdx/license-list-XML/blob/master/test/simpleTestForGenerator/MPL-2.0-no-copyleft-exception.txt)) to use the ["canonical" text](https://www.mozilla.org/media/MPL/2.0/index.txt), and then update the XML markups accordingly if needed
3. rework the XML schema and publisher tool to incorporate a new "conspicuous" tag -- and then consider whether other existing licenses ought to use that new tag as well

3 sounds hard.

I'd lean towards 1 or 2, with a slight preference for 2.

**Comment by jlovejoy** [comment]
We should really use https://www.mozilla.org/media/MPL/2.0/index.txt for our textgenerator file
Then we'd need to add markup for the full lines of *** at the beginning and end of text
The asterisk at beginning of each line will be ignored (@goneall - confirm?)
The asterisk at end may need optional markup

**Comment by swinslow** [comment]
I'll test this out for how the checker / publisher handles asterisks, and will figure out how best to accommodate the markup  :)

**Comment by goneall** [comment]
> The asterisk at beginning of each line will be ignored (@goneall - confirm?)

I just checked the code and single `*` at the beginning of a line will be ignored.

> The asterisk at end may need optional markup

This will also be taken care of by the matcher, so as long as the online tools or command line matcher is used, no need for marking up the single astericks.

You will, however, need to add a markup for the line of asterisks - anything more than 2 will not be skipped

**Comment by swinslow** [comment]
Perfect, thanks @goneall! I'll edit the markups to handle this for the lines of asterisks.
