### ISSUE TITLE
Test license matching against a known set of license texts on every PR or push

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#503]
This is similar to issue #502 but would require more infrastructure.

There is Java code which does the compare against a set of test licenses used by the code which generates the spdx.org/licenses website.  We could wrap this code in some scripts run by Travis-CI to test on every push or pull request.

**Comment by wking** [comment]
Fixed by #593?

**Comment by goneall** [comment]
Yes - Fixed by #593
