### ISSUE TITLE
Automatically update the license-list-data repository on every push or PR

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#504]
Related to Issue #503 in that it could leverage the same Java code and push the generated license list data on every successful update to the master branch.

We would need a way to cache the credentials for github to do the push.

**Comment by swinslow** [comment]
Discussed on 2019-07-30 tech team call, believe this is done but @goneall will confirm and then close.

**Comment by goneall** [comment]
Confirmed - this has already been resolved. Closing.
