### ISSUE TITLE
Add EUPL-1.2 license template

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#505]
Matija volunteered on today's legal call to create initial PR for EUPL-1.2, @zvr to review

**Comment by silverhook** [comment]
That’s me, yup. ,o/

**Comment by silverhook** [comment]
Early findings/bugs:

- OSI lists EUPL-1.2 still under the 1.1 URL: https://opensource.org/licenses/EUPL-1.1 – that’s obviously a bug on their side, so we’ll have to come back to change the OSI link once they fix it.
- I found a dead link in the `EUPL-1.1.xml` and have already fixed it. Will push that commit as well.

**Comment by silverhook** [comment]
EUPL-1.1 URL fixed in https://github.com/spdx/license-list-XML/pull/510
