### ISSUE TITLE
CDLA-Sharing-1.0 Parsing Error

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#517]
Following is an XML schema validation error reported when generating the license list data:

Parsing error in XML file CDLA-Sharing-1.0.xml at line 170, column 23:cvc-complex-type.2.4.a: Invalid content was found starting with element 'bullet'. One of '{"http://www.spdx.org/license":item, "http://www.spdx.org/license":list}' is expected., Skipping file CDLA-Sharing-1.0.xml

**Comment by wking** [comment]
Fix in flight with #519.

**Comment by zvr** [comment]
The bug is in the data, and is not correctly fixed.
There is a nested list, but it has no `item`s.
The fix #519 deletes the `list` element instead of adding them.
I'll provide a fix later in the weekend.

**Comment by wking** [comment]
> The fix #519 deletes the list element instead of adding them.

Yup, see [here][1] about why I went that way.

[1]: https://github.com/spdx/license-list-XML/pull/519/commits/5fb0a3a38800e3877f3398567b5c3709d38c9fe0

**Comment by goneall** [comment]
@wking Do you want to move this fix to its own PR?  I can then merge the other changes in #519 .   @zvr alternatively, if you agree with the changes in the PR I can merge with this fix as well.

**Comment by wking** [comment]
#519's tests won't pass without some fix.  I think we should land #519 as it stands, and if @zvr wants he can file a follow-up PR with a `<list>` and items.

**Comment by wking** [comment]
Checking [upstream][1], they do use a list with item blocks, so I now agree with @zvr on the intended styling.  It will take me a bit before I can update #519, so I'm still fine landing the update as follow-up work if you want to land #519 as it stands.  Or I should be able to file the update by tomorrow.

[1]: https://cdla.io/sharing-1-0/

**Comment by zvr** [comment]
Submitted #521 to fix this

**Comment by goneall** [comment]
Confirmed fixed
