### ISSUE TITLE
Increase maxfilesize in gulpfile.js

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#520]
GPL-3.0.xml is 45Kb which is larger than MAX_FILE_SIZE and will likely cause an error on validation.

**Comment by wking** [comment]
Why do we even have `MAX_FILE_SIZE`?  Can we drop it entirely?

**Comment by goneall** [comment]
> Can we drop it entirely?

IMHO, yes.

**Comment by wking** [comment]
Fixed by #525.
