### ISSUE TITLE
Tag copyrightText should be for content, not license copyright

### ISSUE THREAD

**Issue by zvr** [spdx/license-list-XML#523]
The issue that was pointed out in #490 seems to be present in more licenses.
For example the EUPL ones.

We should go over all the licenses and review the use of `<copyrightText>` tag

**Comment by wking** [comment]
> We should go over all the licenses and review the use of `<copyrightText>` tag

How do you want to organize that?  Open issues for all the current licenses and require some sort of argument be made for whether that license should or should not include the tag?  I'm fine leaving this to folks with an interest in a particular license like #490.

**Comment by jlovejoy** [comment]
copyrightText _should_ be around copyright notice UNLESS that copyright notice applies to the license itself (putting aside the issue of whether/if licenses should be/are copyrightable). 
Examples include: GNU licenses, Apache, Larry Rosen's licenses. 
To be reviewed later, as needed.

**Comment by goneall** [comment]
@jlovejoy Is this really a technical issue?  Someone(s) need to go through and make sure we are not miss-using the copyright field - not something that can be automated in the tools.

I'm about to put in a PR to automatically make all copyrights optional for matching.  I don't think this needs to be resolved beforehand, but just alerting folks that this will change how copyrights are treated.

**Comment by jlovejoy** [comment]
oops, no, probably not a technical issue, not sure why I used that label. 
I think I did check in the latest PR you sent for this issue, though

**Comment by swinslow** [comment]
On this old issue from 2017, if anyone intends to pick up the task of auditing all existing licenses to check how the `copyrightText` tag is being used, then feel free to raise your hand  :)

Otherwise, I would suggest closing this issue and handling it on a case-by-case basis if and when folks raise issues or PRs to fix particular instances of this.

**Comment by jlovejoy** [comment]
@jlovejoy to check list I have had for awhile - maybe update some easy ones and then close as per @swinslow suggestion as this is not critical

**Comment by swinslow** [comment]
@jlovejoy I'm going to move this one forward to 3.18 -- though as mentioned above, I'm also fine with just closing it.

**Comment by swinslow** [comment]
I believe @jlovejoy is looking into this -- moving forward to 3.19.

**Comment by swinslow** [comment]
@jlovejoy Is there anything being looked at here for 3.19 or planned in the near future? If not, I'd suggest we close this since it's been pending since 2017.

**Comment by swinslow** [comment]
Closing this, given no action in approx. 12 months.
