### ISSUE TITLE
ZLib Copyright Addition causes match failure against the original license text

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#529]
Test for license Zlib failed: Test for license ID Zlib failed due to difference found Normal text of license does not match starting at line #3 column #5"software".

This is cause by the copyright text not being found in the original text.

This can be fixed by wrapping the copyright text in an optional tag.

**Comment by mlinksva** [comment]
Sorry about that, I may have been under the misimpression in #482 that copyright text is always optional. I'll make a PR to fix shortly.

**Comment by goneall** [comment]
@mlinksva No worries - I was also thinking about improving the tooling to handle the copyright text in a similar fashion to the title and bullet text.  But the tools currently do not do anything special for the copyright text itself.  Thanks for fixing.

**Comment by wking** [comment]
If the plan is not to fix the tooling (which is fine with me, I'm ok with explicit `<optional>` inside of `<copyrightText>`), do we want PRs like #531 for all of our licenses?  It seems (as of 40bf3d9bd5), only OFL-1.1 and Zlib are doing this.

**Comment by goneall** [comment]
I'm leaning towards fixing the tool on the next release rather than add optional texts inside all of the other licenses.

It should probably be an alt/var rather than optional with a well thought out regular expression pattern.

The reason this one was flagged was without the optional, the original license text didn't match.  All the others pass this basic test.

**Comment by mlinksva** [comment]
FWIW there are some (74 according to grep) licenses for which copyrightText maybe should be non-optional because the license text refers to "the above copyright notice" and therefore doesn't make sense without a copyright notice.

**Comment by goneall** [comment]
> FWIW there are some (74 according to grep) licenses for which copyrightText maybe should be non-optional because the license text refers to "the above copyright notice" 

We could have an `<alt...` pattern that requires something to be there, but allow for some variability.

Perhaps this should be done at the individual license level rather than in the tools.
