### ISSUE TITLE
deprecate GNU licenses with current identifiers

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#543]
GPL-1.0
GPL-2.0
GPL-3.0

LGPL-2.0
LGPL-2.1
LGPL-3.0

FDL-1.1
FDL-1.2
FDL-1.3

AGPL-3.0

**Comment by goneall** [comment]
The notes for the recently added [L]GPL-N.N+.xml files need to be updated to reference the new ID's.

**Comment by zvr** [comment]
The FDL ones are actually GFDL ;)

**Comment by zvr** [comment]
Submitted #553

**Comment by zvr** [comment]
@goneall I am not sure I understood your comment... Which recently added files, which notes and which IDs?

**Comment by goneall** [comment]
> Which recently added files, which notes and which IDs?

The LGPL-2.1+, GPL-2.0+, etc.

**Comment by jlovejoy** [comment]
include AGPL-1.0 and then close this
