### ISSUE TITLE
missing some deprecated licenses

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#544]
I was checking the list of deprecated licenses against what's in the src files here and it appears that these are missing:

GPL-1.0+
GPL-2.0+
GPL-3.0+
GPL-3.0-with-GCC-exception
LGPL-2.1+
LGPL-3.0+
LGPL-2.0+
StandardML-NJ
WXwindows

@goneall  i think you (or Kris) had added these? Am I missing something?

**Comment by goneall** [comment]
Yes - these should have been added.  @jlovejoy glad you checked this.  I'll add PR's for the missing deprecated licenses.

**Comment by jlovejoy** [comment]
GPL-1.0+
~~GPL-2.0+~~
~~GPL-3.0+~~
~~GPL-3.0-with-GCC-exception~~
~~LGPL-2.1+~~
~~LGPL-3.0+~~
~~LGPL-2.0+~~
~~StandardML-NJ~~
~~WXwindows~~

Merged commits for 8 files, but looks like GPL-1.0+ was missing?

**Comment by goneall** [comment]
Adding a PR for GPL-1.0+
