### ISSUE TITLE
New License: Open Data Commons Attribution License

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#548]
adding issue here to cover https://github.com/spdx/license-list/issues/12
needs official addition info - to be discussed for later release

**Comment by bradleeedmondson** [comment]
Discussed on legal call; approved for addition to the SPDX License List.

Appears to be open-source compliant, was announced in 2010, and currently while the license text does not appear to be used in codebases, the standard header language appears in ~40k pages in google search (so it is used in the wild).

Proposed name: Open Data Commons Attribution License v1.0
Proposed short identifier: ODC-By-1.0

**Comment by bradleeedmondson** [comment]
@smileygingerbread Thanks for making this initial request. We moved the [ODC-By 1.0 license addition request](https://github.com/spdx/license-list/issues/12) to this repository and this issue. 

We have now reviewed and accepted it. It should appear in the [next release](https://github.com/spdx/license-list-XML/milestone/4) of the SPDX License List.

**Comment by bradleeedmondson** [comment]
@wking Would you be able to file a PRs for the XML definition of this license?

**Comment by jlovejoy** [comment]
PR for adding license made, so closing issue here: https://github.com/spdx/license-list-XML/pull/663
