### ISSUE TITLE
GPL-*-only: Drop standard license headers?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#579]
We currently provide these (e.g. [here][1]), but the license text only recommends the or-later header (e.g. [here][2]).  That means the `-only` headers do not satisfy our:

> [Leave this field blank if there is no standard header as specifically defined in the license][3]

condition.  And I'm not even sure if they satisfy the [potential][4] weaker condition of:

> Recommended by the license steward.

You might have to weaken to:

> Frequently found in the wild.

and that's a big weakening.  Although #489 is going that far for the license text, so maybe we're ok going that far for the headers.  Either way, I think we need to either soften our [header claims][3] or remove the `GPL-*-only` headers.

[1]: https://github.com/spdx/license-list-XML/blob/e176dedba036533f045dc926429afaab7c38e16d/src/GPL-3.0-only.xml#L9
[2]: https://github.com/spdx/license-list-XML/blob/e176dedba036533f045dc926429afaab7c38e16d/src/GPL-3.0-only.xml#L796
[3]: https://spdx.org/spdx-license-list/license-list-overview
[4]: https://github.com/spdx/license-list/issues/5#issuecomment-284526732

**Comment by jlovejoy** [comment]
sorry @wking but this is taking the explanation of the standard header field a bit too rigidly. The standard headers for GPL are very well known and used; the difference of the "any later version" language being present or removed in the license notice is the recommendation from the FSF (reiterated recently by RMS) and codified by the clause about later versions. No one has ever had an issue here before, notably when that definition was made at a time when the two variations were listed individually on the license list (as they now are again). This is a bit of a solution in search of a problem :)

**Comment by wking** [comment]
On Thu, Jan 11, 2018 at 08:50:55PM +0000, Jilayne Lovejoy wrote:
> … the difference of the "any later version" language being present
> or removed in the license notice is the recommendation from the FSF
> (reiterated recently by RMS) …

Can you link to FSF-recommended wording for the only forms?  Then we
could weaken the policy to just “Recommended by the license steward”.
