### ISSUE TITLE
Rename listVersionAdded → addedVersion to match deprecatedVersion?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#584]
It bothers me a bit that we use different phrasings for these very similar ideas.  Renaming should be trivial work in this repository (`sed`) and probably in spdx/tools too (likely also `sed`, although I'm not sure).  Is anyone else interested in making this change to increase our internal consistency?  If it's just me, I'll live with the inconsistency ;).

**Comment by swinslow** [comment]
Discussed on 2019-07-30 tech team call, there were no concerns about leaving the tag name as-is for the time being.
