### ISSUE TITLE
New License Request: Standard C++ Foundation License

### ISSUE THREAD

**Issue by vmarkovtsev** [spdx/license-list-XML#612]
Full Name: Standard C++ Foundation License
Short Identifier: Please choose for me.
URL: https://github.com/isocpp/CppCoreGuidelines/blob/master/LICENSE
OSI-approved: don't know

**Comment by jlovejoy** [comment]
Sorry for slow response. This license is not an open source license, as it is restricted to personal and internal business use only. See principles of inclusion here: https://spdx.org/spdx-license-list/license-list-overview 
You can always use the LicenseRef option as described in section 6 of the SPDX specification https://spdx.org/spdx-specification-21-web-version#h.1v1yuxt

**Comment by vmarkovtsev** [comment]
Thanks! So shall I close this?

**Comment by jlovejoy** [comment]
err... good question- handling these kinds of request purely via Github is a new thing (usually we give a chance for discussion on our bi-weekly calls) and I'm not sure I want to be the only one to make the call.
@pmadick  @bradleeedmondson  - can I get another input here, so I'm not making a unilateral decision?

**Comment by bradleeedmondson** [comment]
I agree with you @jlovejoy -- I would just add the Not Accepted tag to this request and then close. In fact, I've just done that. Thanks!
