### ISSUE TITLE
Update make file to publish to license-list-data repository

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#613]
Add targets for publishing the license data generated by the SPDX tools to the license-list-data repository.

You can find a shell script from the close PR request https://github.com/goneall/license-list-XML/blob/a4dc1f13ddaeb8b209e8051e53cdd2c950b7a0a4/.travis/testPublishLicenseList.sh

There is also a failed attempt to implement this at https://github.com/goneall/license-list-XML/blob/master/Makefile.  Note that the makefile updates did not work due to problems with the variable declarations.  Apparently, just dropping in the shell variable definitions to the makefile does not work.

**Comment by goneall** [comment]
@wking - Can you take a look at this?  Makefiles is not my specialty.

**Comment by swinslow** [comment]
@goneall @zvr -- we discussed this on the 2019-07-30 tech team call, can you take a look at this?

**Comment by swinslow** [comment]
@zvr likes Makefiles so he will take a look  :)

**Comment by goneall** [comment]
it looks like this has been resolved and can be closed - @zvr , if you agree, go ahead and close the issue
