### ISSUE TITLE
New License/Exception Request: Linux-OpenIB

### ISSUE THREAD

**Issue by kestewart** [spdx/license-list-XML#620]
**Provide a proposed Full Name for the license or exception.**
Linux Kernel Variant of OpenIB.org license

**Provide a proposed Short Identifier.**
Linux-OpenIB

**Provide a functioning url reference to the license or exception text, either from the author or a community recognized source.**

[https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h)

**Create and attach a text file with the license or exception text from the url provided in #3. Please proofread the text file to ensure that:**

- **Information has not been lost or modified.**
- **Formatting is clean and consistent with the license or exception URL.**

>    OpenIB.org BSD license below:
> 
>     Redistribution and use in source and binary forms, with or
>     without modification, are permitted provided that the following
>     conditions are met:
>
>      - Redistributions of source code must retain the above
>        copyright notice, this list of conditions and the following
>        disclaimer.
>
>      - Redistributions in binary form must reproduce the above
>        copyright notice, this list of conditions and the following
>        disclaimer in the documentation and/or other materials
>        provided with the distribution.
> 
>    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
>    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
>    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
>    NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
>    BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
>    ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
>    CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
>    SOFTWARE.

**Indicate whether the license is OSI-approved (see: http://www.opensource.org/licenses/alphabetical) or whether it has been submitted for approval to the OSI and is currently under review.**

No

**Provide a short explanation regarding the need for this license or exception to be included on the SPDX License List, including identifying at least one program that uses this license.**

The linux kernel uses the above license extensively throughout the driver subsystem since 2005.   It is not actually the OpenIB.org license - which is a BSD-2-Clause, but rather has the MIT license disclaimer used instead of the BSD-2-Clause disclaimer.  The author may have wanted the BSD license grant language, but wanted the MIT disclaimer because it explicitly disclaims the warranty of non-infringement.

Note that the University of Illinois/NCSA Open Source License (https://spdx.org/licenses/NCSA.html) is similarly a combination of BSD-style and MIT language, and has its own SPDX identifier on the License List. NCSA has an MIT-style license grant, BSD-3-Clause license conditions, and MIT-style disclaimer.

**Comment by kestewart** [comment]
Background:

In 2004 an industry association called Open Infiniband or "OpenIB" was founded to consolidate and upstream into Linux what is today drivers/infiniband.

That group of companies mutually agreed to use a "dual GPL and BSD license" scheme and the membership agreement obligated the member companies to use such a license.

The license text was first introduced to the linux kernel around 2005 and has been copied into >600 files (either as an include or directly).  It looks like there are > 15 companies listed as copyright holders, some now defunct, so to aid with cleanup of the Linux kernel licensing, we’d like to get this variant of a combination BSD & MIT licenses to have its own identifier.


Example:  include/uapi/rdma/ib_user_sa.h
(which is copied into around 659 kernel files and is mistakenly labeled with “OR BSD-2-Clause”)


> Copyright (c) 2005 Intel Corporation.  All rights reserved.
>
> This software is available to you under a choice of one of two
> licenses.  You may choose to be licensed under the terms of the GNU
> General Public License (GPL) Version 2, available from the file
> COPYING in the main directory of this source tree, or the
> OpenIB.org BSD license below:
>
>     Redistribution and use in source and binary forms, with or
>     without modification, are permitted provided that the following
>     conditions are met:
>
>      - Redistributions of source code must retain the above
>        copyright notice, this list of conditions and the following
>        disclaimer.
>
>      - Redistributions in binary form must reproduce the above
>        copyright notice, this list of conditions and the following
>        disclaimer in the documentation and/or other materials
>        provided with the distribution.
>
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
> NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
> BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
> ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
> CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
> SOFTWARE.

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/uapi/linux/rds.h


Using the wayback machine: https://web.archive.org/web/20041204083759/http://openib.org:80/license.html



> OpenIB BSD License
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
> 
> * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> 
> * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> 
> 
> THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

In 2014 OpenIB.org Alliance expanded scope and became the OpenFabrics Alliance (OFA) https://www.openfabrics.org/index.php/organization.html

If you look at the OpenFabric https://github.com/ofiwg/libfabric/blob/master/COPYING  it is now clearly the BSD-2-Clause license as well,  but what was copied into the kernel files in 2005 and replicated throughout the kernel does not match.


Somehow when drivers/infiniband was first merged it contained the license text used in the kernel today, and its unclear where Roland Drier got the text from.


From there all the member companies copy and pasted that text, and it has become the canonical text in the linux kernel for the infiniband driver.   After that it appeared to spread into other parts of the kernel, eg.  crypto, scsi, net, etc all now have files that use it.  The current maintainer doesn’t believe this was any sort of well thought out act, probably just the same developers 'cargo cult' copying what they had always done.


To clarify the difference, if you ignore the preamble and start at "Redistribution" then:


 The first 50% of the license text matches the sample license of SPDX

 BSD-2-Clause, up until "THE SOFTWARE IS PROVIDED".


The final paragraph matches the sample license of the SPDX for MIT.


Because of the last para,  per the matching rules is that this is a 'no match' to BSD-2-Clause.

**Comment by jlovejoy** [comment]
discussed March 22 legal call - accepted and merged
