### ISSUE TITLE
update LLVM exception URL once in use

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#622]
URL for LLVM exception goes to email with text; update to source repo once license switch is made.
Review use of dashes in actual use and whether optional or alt tag is more appropriate as well.

**Comment by wking** [comment]
On Thu, Mar 22, 2018 at 06:58:08PM +0000, Jilayne Lovejoy wrote:
> Review use of dashes in actual use and whether optional or alt tag
> is more appropriate as well.

I've filed #623 for this.

**Comment by jlovejoy** [comment]
URL was updated for 3.2 release, closing issue
