### ISSUE TITLE
Significance of the “approved” label?

### ISSUE THREAD

**Issue by wking** [spdx/license-list-XML#631]
We have an “[approved][1]” label, but I'm not sure what it means.  Do we still need it?  The most recent issue/PR to use it is #381, and I think that case is better represented by the newer “[new license/exception: Accepted][2]” label.

[1]: https://github.com/spdx/license-list-XML/issues?q=label%3Aapproved
[2]: https://github.com/spdx/license-list-XML/labels/new%20license%2Fexception%3A%20Accepted

**Comment by bradleeedmondson** [comment]
I believe you're right; that the 'approved' label was functionally replaced
by 'new license/exception: accepted'

**Comment by bradleeedmondson** [comment]
I merged all PRs that had been tagged with 'approved' into the accepted label and removed the approved label.
