### ISSUE TITLE
OpenJDK-assembly-exception-1.0 exception text: descriptive text optional or required?

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#634]
We added OpenJDK-assembly-exception-1.0 in #625 today.

As currently marked up, we include descriptive text ([1](https://github.com/swinslow/license-list-XML/blob/bddee547bcca5764fbf68ba9f7a372b61e53715a/src/exceptions/OpenJDK-assembly-exception-1.0.xml#L10), [2](https://github.com/swinslow/license-list-XML/blob/bddee547bcca5764fbf68ba9f7a372b61e53715a/src/exceptions/OpenJDK-assembly-exception-1.0.xml#L41)) as required for a match, but arguably this would be better viewed as optional or not included at all. This issue is to decide that question.

**Comment by bradleeedmondson** [comment]
discussed on legal call 5/31; decided to make first and last paragraphs optional.

**Comment by jlovejoy** [comment]
needs PR to get done, then close this

**Comment by bradleeedmondson** [comment]
marked 2 paragraphs as optional in #667 

merged; resolved
