### ISSUE TITLE
New License Request: TU-Berlin 1.0 and 2.0

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#636]
From A. Wilcox, Project Lead, Adélie Linux, via the [legal team](https://spdx.org/legal-team)'s [mailing list](https://lists.spdx.org/mailman/listinfo/spdx-legal):

> Proposed Full Name:
> 
> Technische Universitaet Berlin License
> 
> Permissive Technische Universitaet Berlin License [???]
> 
> 
> Proposed Short Identifier:
> 
> TU-Berlin-1.0
> 
> TU-Berlin-2.0
> 
> 
> URL references:
> 
> 1.0:
> 
> http://alpha.tmit.bme.hu/pub/audio/gsm-1.0/copyrigh
> https://github.com/swh/ladspa/blob/master/gsm/COPYRIGHT
> 
> 
> 2.0:
> 
> https://github.com/CorsixTH/deps/blob/master/licences/libgsm.txt
> https://answers.launchpad.net/ubuntu-leb/oneiric/+source/libgsm/+copyright
> 
> 
> OSI-approved?
> 
> No.
> 
> 
> Packages using this license:
> 
> gsm / libgsm
> 
> via inclusion of gsm code: ladspa, rplay, speex, some builds of vorbis
> 
> 
> Date:
> 
> 1.0: 15-Sep-1992
> 2.0: 05-Apr-2009
> 
> 
> Explanation (non-normative):
> 
> I did not find any reference to these licenses in the tracking page.  I
> have only seen this used in gsm; I do not know if the university has
> released other open source projects.  (No further packages were found
> searching for key, unique phrases in DuckDuckGo nor Google nor GitHub.)
> 
> Fedora seems to consider this "MIT", but other than some similarities in
> 2.0 to MIT/PetSC and MIT/HP, this license has nothing more than a
> spiritual relation to MIT in my opinion.
> 
> If this should instead be considered a MIT variant, I would be willing
> to resubmit as that.
> 
> Thanks for your consideration.
> 
> 
> Best,
> --arw
> 
> --
> A. Wilcox (awilfox)
> Project Lead, Adélie Linux

And Dennis reports:

> For the record, the proposed license is currently recognized by ScanCode as tu-berlin. 
> 
> https://github.com/nexB/scancode-toolkit/blob/4e63a6775a895fdec5a3a53f96013399fa34b1b7/src/licensedcode/data/licenses/tu-berlin.yml
> 
> Regards,
> Dennis Clark

**Comment by bradleeedmondson** [comment]
Discussed on legal call today; vote is to recognize both 1.0 and 2.0 as new licenses on the SPDX License List. 

Note that the additional permission added in 2.0 is a close match for a license already on the list, however since it is explicitly cast as "append[ed]" "additional permission[s]" to the 1.0 terms, it is not identical to any existing license on the list. 

Approved.

**Comment by bradleeedmondson** [comment]
@wking Would you be able to file PRs for XML definitions of these two licenses?

**Comment by swinslow** [comment]
Hi @bradleeedmondson, I'm preparing the markup for these two.
