### ISSUE TITLE
New exception: OCaml LGPL linking exception

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#649]
OCaml linking exception reported by Andy Li on the SPDX mailing list:

> Full Name:
> OCaml linking exception
> 
> Short Identifier:
> OCaml-linking-exception
> 
> Reference to exception text:
> https://github.com/ocaml/opam/blob/master/LICENSE
> 
> Exception text is attached as "OCaml-linking-exception.txt". Notice that individual usages in libraries have slightly difference mainly due to differences in software names and author names.
> 
> I haven't noticed any information on whether this is OSI-approved.
> 
> The exception is used by OCaml itself and is very popular among OCaml libraries:
> 
>  * OCaml: https://github.com/ocaml/ocaml/blob/trunk/LICENSE
>  * opam: https://github.com/ocaml/opam/blob/master/LICENSE
>  * OCaml batteries-included: https://github.com/ocaml-batteries-team/batteries-included/blob/master/LICENSE
> 
> Best regards,
> Andy

**Comment by bradleeedmondson** [comment]
Text of the attached document:

> As a special exception to the GNU Lesser General Public License, you
> may link, statically or dynamically, a "work that uses the Library"
> with a publicly distributed version of the Library to produce an
> executable file containing portions of the Library, and distribute
> that executable file under terms of your choice, without any of the
> additional requirements listed in clause 6 of the GNU Lesser General
> Public License. By "a publicly distributed version of the Library", we
> mean either the unmodified Library as distributed, or a modified
> version of the Library that is distributed under the conditions
> defined in clause 2 of the GNU Lesser General Public License. This
> exception does not however invalidate any other reasons why the
> executable file might be covered by the GNU Lesser General Public
> License.

**Comment by bradleeedmondson** [comment]
I can write this up as XML

**Comment by bradleeedmondson** [comment]
Wrote up XML to add this in PR #660, but we still have questions for the license authors/submitters, e.g. here:
https://lists.spdx.org/g/Spdx-legal/topic/22080605#1338


Removed from milestone 3.2 since this is not ready for decision-making

**Comment by jlovejoy** [comment]
discussed on July 26 legal call: historical issues here have to do with clause numbers; decided to add current exception language as found in links above. Need markup for names. Don't have make "library/lesser" replaceable, as that is good indicator of older versions (which we can add later if they are prevalent). https://github.com/ocaml/ocaml/commit/2d26308ad4d34ea0c00e44db62c4c24c7031c78c#diff-9879d6db96fd29134fc802214163b95a

**Comment by jlovejoy** [comment]
@bradleeedmondson  can you update PR as needed?

**Comment by bradleeedmondson** [comment]
build test for #660 failed; once that is sorted out this will be ready to add for milestone 3.3

**Comment by goneall** [comment]
Should be good to merge - build failures are fixed in the master branch.

**Comment by jlovejoy** [comment]
PR now merged
