### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by yoooooooooooooooooooooooo** [spdx/license-list-XML#652]
`http://opensource.linux-mirror.org/licenses/afl-2.0.txt` at https://spdx.org/licenses/AFL-2.0.html is broken.

**Comment by jlovejoy** [comment]
we can probably just remove that since it was updated with the wayback archive of the same link

**Comment by jlovejoy** [comment]
https://github.com/spdx/license-list-XML/pull/653
