### ISSUE TITLE
Cleanup for TU-Berlin-1.0 and TU-Berlin-2.0

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#666]
This is a follow-up issue from the new licenses TU-Berlin-1.0 and TU-Berlin-2.0 (#636), which was added to the license list in version 3.2 in #665.

Comments to #665 from @goneall and agreed by @jlovejoy included a suggestion for further cleanup in version 3.3: consider whether to add `alt` tags around instances of `Technische Universitaet Berlin`, to make this templateable. Alternatively, consider whether this should be treated as a single-use license where a different copyright holder / name should not match these licenses.

**Comment by jlovejoy** [comment]
discussed on 10/4 legal call: no knowledge of alternative names, so leaving without markup for now/until we find instance of such

**Comment by DennisClark** [comment]
For the record, I found the TU-Berlin-2.0 license in the `copyright` file of `libgsm1_1.0.13-4_amd64.deb`   which is available at https://packages.ubuntu.com/trusty/amd64/libgsm1/download

The license is clearly under the original license authors, not an alternative.  

```
This is the Debian GNU/Linux prepackaged version of libgsm, an implementation of the
European GSM 06.10 provisional standard for full-rate speech
transcoding, prI-ETS 300 036, which uses RPE/LTP (residual pulse
excitation/long term prediction) coding at 13 kbit/s.

This package was put together by Klee Dienes <klee@debian.org>, from
sources retrieved from
<URL:http://kbs.cs.tu-berlin.de/~jutta/toast.html>.
This package was maintained by Martin Mitchell <martin@debian.org>.
This package is now maintained by Jochen Friedrich <jochen@scram.de>.

Copyright 1992, 1993, 1994 by Jutta Degener and Carsten Bormann,
Technische Universitaet Berlin

Any use of this software is permitted provided that this notice is not
removed and that neither the authors nor the Technische Universitaet Berlin
are deemed to have made any representations as to the suitability of this
software for any purpose nor are held responsible for any defects of
this software.  THERE IS ABSOLUTELY NO WARRANTY FOR THIS SOFTWARE.

As a matter of courtesy, the authors request to be informed about uses
this software has found, about bugs in this software, and about any
improvements that may be of general interest.

Berlin, 28.11.1994
Jutta Degener
Carsten Bormann

etc.
```
