### ISSUE TITLE
New license request: +CAL

### ISSUE THREAD

**Issue by bradleeedmondson** [spdx/license-list-XML#670]
From Sally Mindrebo sally.mindrebo@corpaccountabilitylab.org):

> 1) License Name: +CAL Software License
> 
> 2) Short Identifier: +CAL
> 
> 3) URL: https://legaldesign.org/cal-software-license
> 
> 4) OSI Approval: Submitted and under review
> 
> 5) Why the +CAL License?: There are no existing licenses that (1) expand a common law duty of care across the supply chains in which the copyrighted work is used and (2) provide victims of abuse by corporations with third-party beneficiary standing to enforce the copyright license. These two features are unique to the CAL license, which otherwise operates with the same legal logic as the GNU General Public License. Accordingly, this is a new special purpose license intended for users who would like to create copyrighted works that repair distorted and unjust market structures, in line with the ethics and values of certain copyright creators.

**Comment by bradleeedmondson** [comment]
I asked submitter (who appears to be license author):

> 1. Can you point us to some examples of projects or works that are using this license? We try to represent open-source software as it is actually used "in the wild," so usage in a project is a requirement for being added to the SPDX License List.
> 
> 2. Would it be possible for CAL to add a version number to this license? There may come a time where you wish to revise it and release an updated license text, and that is a lot more straightforward if you are going from CAL-1.0 to CAL-1.1 or CAL-2.0. We look to the license author to specify their versioning and to be transparent when changes are made to the text by bumping the version number.
> 
> 3. Do you have any objection to our labeling and titling the license CAL instead of +CAL? The + character has a special meaning in SPDX license expressions, and is not allowed in SPDX IDs.
> 
> 4. Please let us know what OSI says after its review.

**Comment by jlovejoy** [comment]
pushed out to 3.4 - have yet to get response from email with questions (see above)

**Comment by jlovejoy** [comment]
replied to submitter again on 10/25: https://lists.spdx.org/g/Spdx-legal/message/2430

**Comment by swinslow** [comment]
Looks like there was no response to Brad's questions on July 12 or to Jilayne's follow-up on Oct. 25. I'd be in favor of closing this one. The submitter could re-open an issue for it in the future if they have evidence of usage in the wild, and can address Brad's other points.
