### ISSUE TITLE
update links to Contributing page on website

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#680]
as per https://github.com/spdx/license-list-XML/pull/674
add a link to CONTRIBUTING to webpage (https://spdx.org/spdx-license-list/request-new-license), update links elsewhere, so we can eventually get rid of webpage and just have one place for this info

Links to be update on following pages:

- [x] https://spdx.org/spdx-license-list/license-list-overview
- [x]   https://spdx.org/licenses/ (in template)
- [x]   https://spdx.org/licenses/exceptions-index.html (in template)
- [x] FAQ page, next-to-last question (just above "Tools")
- [ ] Appendix I of the spec also has the link, because the license list is currently embedded in the spec as an appendix.

**Comment by swinslow** [comment]
Hi @jlovejoy, I've now updated the links to point to CONTRIBUTING for checkboxes 1 and 4 on your list. (I'm not sure how to actually check them off!)

Items 2 and 3 will presumably need to be modified as part of the next license list release push.

I think Item 5 would potentially be handled by removing the license list from the spec, as we've discussed. If it won't be removed for the next release, then I can post a PR to just change the link.

**Comment by swinslow** [comment]
Items 2 and 3 require changes in spdx/license-list-data. I've added an issue there: https://github.com/spdx/license-list-data/issues/40

Item 5 requires changes in spdx/spdx-spec. I've added an issue there: https://github.com/spdx/spdx-spec/issues/103

I'll help with moving those issues forward in those repos, just didn't want to lose track of them here...

**Comment by jlovejoy** [comment]
made PRs to change links in template HTML pages here: https://github.com/spdx/LicenseListPublisher/pull/41

**Comment by jlovejoy** [comment]
made PR for changing link in spec here: https://github.com/spdx/spdx-spec/pull/104

**Comment by swinslow** [comment]
also made PR for changing links in license-list-data, at https://github.com/spdx/license-list-data/pull/43

Though I just now realized that the PR from @jlovejoy in https://github.com/spdx/LicenseListPublisher/pull/41 might make that one unnecessary... @goneall can you weigh in too?

**Comment by jlovejoy** [comment]
I think we can close this... @swinslow , @goneall  - agree?

**Comment by swinslow** [comment]
Agreed!

**Comment by goneall** [comment]
Agree as well.  I'll go ahead and close the issue.
