### ISSUE TITLE
Add top level license to license list code and files

### ISSUE THREAD

**Issue by kestewart** [spdx/license-list-XML#683]
@jlovejoy I've gotten a question about the top level license for this github repo (for the aggregation), 
and given we have the output listed in the specification https://spdx.github.io/spdx-spec/appendix-I-SPDX-license-list/  which is CC-BY-3.0  and have had since the start,  I believe that CC-BY-3.0 is a reasonable license to denote this repository with.    Thoughts?

**Comment by jlovejoy** [comment]
began to discuss on Aug 23 call - needs more thought and discussion. Should we take similar approach to data and any potential copyrightable text in SPDX docs as per section 2.2 of spec?

**Comment by jlovejoy** [comment]
(discussed on Sept 20 call)
by way of example:
- spec license is CC-BY-3.0
- SPDX tools are Apache-2.0
- SPDX meta-data - CC0-1.0 (if at all)

for license-list repo - different types of files:
- XML schema has CC-BY-4.0 notice -- should we make this software license? would be easier to make this CC0-1.0. need to get okay from SPDX Legal team, particularly contributors to that file
- validate-schema.js has MIT -- also make this CC0-1.0 to be consistent and for same reasons as above. Check with Trevor that no other code was pulled into this file and we can change license
- XML license files - not going to put license notice in XML files, but a notice in README would helpful to clarify that to the extent there is any copyrightable material... it's CC0-1.0
action items: draft something for review (@jlovejoy) also work on explanation of "license of the license" in parallel (@swinslow @pmadick @bradleeedmondson )

**Comment by goneall** [comment]
As one of the contributors to the XML schema file, CC0-1.0 is fine by me.  @wking is the other contributor to the XML schema file.

**Comment by wking** [comment]
> As one of the contributors to the XML schema file, CC0-1.0 is fine by me.

Me too.  Somebody file a PR with a header tag! ;)

**Comment by jlovejoy** [comment]
thanks @goneall and @wking  - I'll sort out wrapping this up later/over next few days. As per discussion on call, also want to put out an email to the list, so everyone is aware generally.

**Comment by jlovejoy** [comment]
PR #710 created for this

**Comment by swinslow** [comment]
I believe this can be closed now? At least w/r/t anything that will be part of the 3.3 release.

**Comment by swinslow** [comment]
Believe this one has been done since Oct. 2018, so I'm going to go ahead and close it.
