### ISSUE TITLE
New License Request: Nordic 5-Clause BSD

### ISSUE THREAD

**Issue by carlescufi** [spdx/license-list-XML#689]
A) Full Name

Nordic 5-Clause BSD License

B) Short Identifier

BSD-5-Clause-Nordic

C) Other web pages for license/exception

http://developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v15.x.x/doc/15.2.0/nRF5_Nordic_license.txt
https://github.com/NordicSemiconductor/nRF5-SDK-for-Mesh/blob/master/COPYING.md

D) Notes

E) OSI Approved?
No, and it will not be (does not comply with the Open Source Definition)

F) FSF Free/Libre?
No

G) Text

```
Copyright (c) 2018 Nordic Semiconductor ASA

All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form, except as embedded into a Nordic
   Semiconductor ASA integrated circuit in a product or a software update for
   such product, must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other
   materials provided with the distribution.

3. Neither the name of Nordic Semiconductor ASA nor the names of its
   contributors may be used to endorse or promote products derived from this
   software without specific prior written permission.

4. This software, with or without modification, must only be used with a
   Nordic Semiconductor ASA integrated circuit.

5. Any software provided in binary form under this license must not be reverse
   engineered, decompiled, modified and/or disassembled.

THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

H) Standard License Header
```
/*
 * Copyright (c) <YEAR> <COPYRIGHT HOLDER>
 *
 * SPDX-License-Identifier: BSD-5-Clause-Nordic
 */
```

**Comment by carlescufi** [comment]
Note to maintainers: I understand this is not an OSI-approved license nor never will be, but it's already a popular license in Nordic Semiconductor distributed SDKs and tools, and we at Nordic would like to adopt SPDX.

**Comment by jlovejoy** [comment]
discussed on Sept 20 call: as per the license inclusion guidelines at https://spdx.org/spdx-license-list/license-list-overview : "...any license that is a candidate for inclusion on the SPDX License List must have the general attributes of an "open source" license."  
So, we won't add this. But note that you can still adopt SPDX! (and we think it's great that you want to!) - in this case, I'd recommend using the LicenseRef option (see section 6 here: https://spdx.org/sites/cpstandard/files/pages/files/spdxversion2.1.pdf

Which might look like:
/*
 * Copyright (c) <YEAR> <COPYRIGHT HOLDER>
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-binary
 */

(I purposely didn't use "BSD-5-Clause" as I think using BSD could be confusing in that it suggests it's like BSD and hence is open source)

**Comment by jlovejoy** [comment]
@carlescufi - I meant to tag you in above comment to ensure you saw above. If you have any further questions, please direct them to the SPDX legal team mailing list, which can be joined (if you are not a member) here: https://lists.spdx.org/g/spdx-legal

**Comment by carlescufi** [comment]
@jlovejoy sorry for the late reply. Thank you for the clarification and explanations.
