### ISSUE TITLE
New License/Exception Request: copyleft-next

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#691]
from Kuno Woudt via email:

New License/Exception Request: copyleft-next

1. Provide a proposed Full Name for the license or exception.

copyleft-next 0.3.1

2. Provide a proposed Short Identifier.

copyleft-next-0.3.1

3. Provide a functioning url reference to the license or exception text, either from the author or a community recognized source.

https://github.com/copyleft-next/copyleft-next/blob/master/Releases/copyleft-next-0.3.1

4. Create and attach a text file with the license or exception text from the url provided in #3. 

[attached]

5. Indicate whether the license is OSI-approved (see: http://www.opensource.org/licenses/alphabetical) or whether it has been submitted for approval to the OSI and is currently under review.

The license is not formally OSI approved, nor has it been submitted for review (AFAIK).

6. Provide a short explanation regarding the need for this license or exception to be included on the SPDX License List, including identifying at least one program that uses this license.

Various software packaging tools rely on the SPDX license identifier list when dealing with software packages, for example the "license" field in package.json used by the node.js / NPM ecosystem. The npm tool tries to encourage proper licensing of packages published to the public npm registry by warning about invalid license identifiers. As a user of copyleft-next, I would like to see tools such as npm accept the license.

copyleft-next is a copyleft license written by Richard Fontana and various contributors, explicitly compatible with any version of the GPL (and AGPL).

copyleft-next is not a very popular license, but is used by a small group of developers for their projects:

https://github.com/search?q=%22copyleft-next%22+filename%3ALICENSE&type=Code

**Comment by jlovejoy** [comment]
name/identifier preference from license author, Richard Fontana:

Full name: copyleft-next  0.3.1
Identifier:  copyleft-next-0.3.1

**Comment by swinslow** [comment]
Hi @jlovejoy, you can assign this one to me, I've started working on the test + XML files.

**Comment by jlovejoy** [comment]
PR https://github.com/spdx/license-list-XML/pull/698 made for this

**Comment by jlovejoy** [comment]
re-opening, b/c while we added 0.3.1 for release 3.3, there are other older versions - add those too?

**Comment by swinslow** [comment]
Hi @jlovejoy, I created #709 to track adding the versions of copyleft-next prior to 0.3.1. Feel free to assign #709 to me (would suggest we mark it for 3.4, as mentioned there).
