### ISSUE TITLE
New License Request: Convertible Free Software License Version 1.1

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#692]
(via email from Elmar Stellnberger -  see message link for attachment

Full Name: Convertible Free Software License Version 1.1
Short Identifier: C-FSL v1.1
URL: https://www.elstel.org/license/C-FSL-v1.1.txt
OSI approved: not yet
why we need this license:
While the BSD license allows the whole world to re-license and while re-licensing is virtually impossible with GPL since every contributor would need to consent the C-FSL license goes a practical intermediate way restricting the right to re-license to a group called the original authors. That way open source developers are not excluded from making business with others who want to base a proprietary product on the given piece of open source software.

P.S.: the license has already been checked by a lawyer from the EPA (Environmental Protection Agency) for OSS-compliance.

-=-=-=-=-=-=-=-=-=-=-=-

View/Reply Online (#2349): https://lists.spdx.org/g/Spdx-legal/message/2349

**Comment by jlovejoy** [comment]
under review currently by OSI, will review once OSI approval is solidified (or significant usage is shown)

**Comment by swinslow** [comment]
A new version of C-FSL (1.3) was sent to OSI license-review yesterday. It sounds like 1.1 is no longer under consideration by OSI, but 1.3 is currently in their review and discussion window.

**Comment by DennisClark** [comment]
It might be best for someone with the necessary credentials to modify the title of this Issue to `Version 1.3`.   I don't seem to be able to do that.

**Comment by DennisClark** [comment]
Also, given that this is a new license still in the proposal/review stage, it would be best to tag it for a future release rather than 3.5.

**Comment by jlovejoy** [comment]
updated title to 1.x for now :)

I'm going to leave as 3.5, so we don't forget about it. We can push it to 3.6 if it hasn't been settled by time we are doing the 3.5 release.

**Comment by swinslow** [comment]
Based on legal team discussion on 2019-01-24, decided to close this issue for now as the license text and versions continue to evolve. The finalized version can be resubmitted when and if the version is approved by OSI or has usage in the wild.
