### ISSUE TITLE
New License/Exception Request: pre-0.3.1 releases of copyleft-next

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#709]
copyleft-next-0.3.1 was added to the license list for 3.3 (see #691 and #698). 

Five older versions of copyleft-next also exist, available at https://github.com/copyleft-next/copyleft-next/tree/master/Releases. I'm happy to prepare and submit PRs for these. 

I would suggest we mark this as an issue for the 3.4 license list release. 

I'd also be interested in thoughts re: whether we want confirmation of any projects in the wild using these pre-0.3.1 versions of copyleft-next, before adding those to the list.

**Comment by warpr** [comment]
@swinslow iirc as Richard wrote this license the version bumped a few times in the first few months as the license was being developed, and not really in use yet.  I have definitely seen 0.3.0 in the wild, but any version prior to that I expect isn't used much or at all.

**Comment by swinslow** [comment]
@warpr Thank you -- this is helpful context. Based on this I'd suggest that we add 0.3.0 now, and hold off on adding others unless / until they are spotted in the wild.

**Comment by swinslow** [comment]
I think #723 is ready to merge, just waiting for others to review / approve (I wasn't inclined to merge my own submission...)

**Comment by jlovejoy** [comment]
closing issue with addition 0.3.0
recognition that there are older versions and we usually add all versions, but since it seems to be only 0.3.1 and 0.3.0 in use and no request for older versions; we can add those later, if requested
