### ISSUE TITLE
Machine-readable field for deprecated licenses where license steward has superseded with another license

### ISSUE THREAD

**Issue by bkuhn** [spdx/license-list-XML#716]
At today's SPDX Legal call, during discussion of the [Free RTOS Exception](https://spdx.org/licenses/freertos-exception-2.0.html)  which is effectively deprecated at least for the upstream project due to [Amazon relicensing Free RTOS under MIT license](https://www.freertos.org/a00114.html#exception), I suggested this idea as a possible feature.  The feature may need a change to [spdx-spec](https://github.com/spdx/spdx-spec) instead, but consensus on the call seemed to be to file the issue here.

The idea is for this use case: a license steward deprecates a license (such as Free RTOS, or another example being TrollTech/Nokia did with the (Qt Exception)[https://spdx.org/licenses/Nokia-Qt-exception-1.1.html] and possibly the (QPL itself)[https://spdx.org/licenses/QPL-1.0.html]). However, when deprecating the license, they supersede it with a new license and that causes *most* of the code under that license to be relicensed since the license was most heavily associated with a single codebase.  While we all hate project-specific licenses, they do exist and we're often as a community trying to convince them to switch to a standard license, and that eventually does happen.

The problem is that forks may float around under the old license, or otherwise people have copies of the codebase in their work and haven't heard about the relicense.  Then someone runs a license scanner, and discovers this weird license.

The feature idea is just some sort of machine-readable hinting that could be associated with the license in SPDX "somewhere" such that the tooling could pop up a message to say: "Hey, we found this code under this license.  The license is deprecated but we're glad to tell you that the odds are good you can just relicense this stuff under this much more standard license.  Of course, YMMV and check that you haven't incorporated other changes from third parties, but it's worth looking into."

Obviously a human could discover this by inspection of the license-list, the scan results, net.searching, etc., but since SPDX's license-list authors usually *have* this information ahead of time and, at least with Free-RTOS, are considering putting that information into the license list free form, why not put it in there in a machine-readable way?

**Comment by goneall** [comment]
+1 on the supporting this use case.

Currently, deprecated is an attribute in the license list XML schema and in the "output" formats (see https://github.com/spdx/license-list-XML/blob/5d3f5598201970e91ffd450f59db16609b33e83b/schema/ListedLicense.xsd#L51).  We would need to decide on how to represent this data.

I can think of 2 choices:
- independent element "deprecatedBy" which would refer to the license intended to replace the deprecated license (e.g. by licenseID) - this is consistent with our approach on the deprecated version
- Change the current deprecated attribute to an element and allow an optional sub-element "deprecatedBy".  If we take this approach, we could move the deprecatedVersion as another sub-element under the deprecated element.

**Comment by silverhook** [comment]
I really like the idea and support it.

One issue could be with licenses that were then deprecated by different licenses in different packages. I don’t have any examples ready though.

**Comment by jlovejoy** [comment]
no further comments on this for 2.5 years and considering all that's on the plate now, should we close? @goneall or @silverhook - what are thoughts since you thought it would be useful? It seems like it could get subjective to judge this very quickly, unless we use a very narrow set of requirements? (and use something other than "deprecated" since that has its own meaning in SPDX land; maybe "retired"?)

**Comment by silverhook** [comment]
…and ”Retired” would be defined as retired by license steward? That might work.

**Comment by jlovejoy** [comment]
yeah, that would be the idea, although, I'm not sure that's as easy as it sounds... 

I think part of the original idea was identifying the licenses on the "Licenses that have been voluntarily retired" section here: https://opensource.org/licenses/category
But that is very few licenses. 
@bkuhn  also mentions "superseded" licenses, but that is kind of a different category. And the example that spurred this whole conversation (which started on a call and then this issue followed) was the old FreeRTOS license, which isn't even on the OSI categories.  

I guess my concern is that we don't want to get into a position of making a judgement (we already do that for accepting licenses on the list to begin with and that's hard enough!) and not really have good criteria for that. If we only relied on OSI for this categorization, then that would probably be ok, but I'm not sure that was the original intent

**Comment by silverhook** [comment]
That’s the main issue I see as well – which is why I think the only reasonable way would be to only implement the fact  that the _license steward_ retired that (version of the) license.

On a per-project basis, I don’t see how this could work.

**Comment by jlovejoy** [comment]
given the stated challenges of this and that it hasn't otherwise gotten picked up, I'm going to close this.  To @silverhook point, I believe if we implemented this as the "license steward retired/deprecated the license" but I suspect this would be a very small number given how many licenses don't really have a steward
