### ISSUE TITLE
New license request: SATA [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#717]
**1.** License Name: he Star And Thank Author License
**2.** Short identifier: SATA
**3.** URL: https://github.com/zTrix/sata-license/blob/a72e947589ac80df3a0e586f2cb3c154bb9923f0/LICENSE.txt
**4.** OSI Approval: no

**Comment by silverhook** [comment]
@goneall, you’re missing a ‘T’ in the License Name field.

**Comment by jlovejoy** [comment]
see thread here: https://lists.spdx.org/g/Spdx-legal/message/2427 
with questions to submitted; also need to determine if submitter is license author?

**Comment by jlovejoy** [comment]
as of Dec 12, still no response from license submitter

**Comment by silverhook** [comment]
@qiwihui, can you look into this (see link above for the discussion thread so far).

**Comment by swinslow** [comment]
Since there has been no response from the submitter since October, the legal team agreed on 2019-01-24 call to close this issue.
