### ISSUE TITLE
add open hardware (and open data) definitions or references to license inclusion guidelines

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#719]
see https://www.oshwa.org/definition/  for open hardware

raised as in this thread: https://lists.spdx.org/g/Spdx-legal/topic/27459493#2426

**Comment by m30-jrs** [comment]
I added a representative sample OSHW license request (CERN OHL v1.2) for reference: https://lists.spdx.org/g/Spdx-legal/topic/new_license_request_cern/27813077

**Comment by jlovejoy** [comment]
@m30-jrs - I've now added both versions of CERN-OHL via the license submission tool, as well as TAPR (see https://github.com/spdx/license-list-XML/issues ) 
Will next get with @andrewjskatz re: adding Solderpad (all versions) 
We'll use this issue for tracking the addition of the open hardware definition in the SPDX License List overview page :)

**Comment by silverhook** [comment]
For data, this might be an option:

OKFN’s “Open Definition”:
http://opendefinition.org/od/2.1/en/

OKFN’s list of approved (and not) Open licenses for content and data:
http://opendefinition.org/licenses/
and the process on how licenses get on that list:
http://opendefinition.org/licenses/process/

**Comment by swinslow** [comment]
Per last week's legal team call, this is still in process. It is not really tied to a license list release, as it will likely be an update to the main website. I'm setting its milestone to 3.6 so that we don't lose track of it and aim to handle it early in the 3.6 cycle.

**Comment by swinslow** [comment]
@jlovejoy I think this is now complete, with the updates to https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md -- are you good with us closing out this issue?

**Comment by swinslow** [comment]
Discussed on 2019-06-13 legal call, all set here.
