### ISSUE TITLE
New Exception Request: OpenSSL Exception

### ISSUE THREAD

**Issue by cas--** [spdx/license-list-XML#720]
Full name: OpenSSL Exception
Short identifier: OpenSSL-exception
Existing discussion: https://lists.spdx.org/g/Spdx-legal/topic/24235315#2398

**Comment by swinslow** [comment]
From legal call 2019-01-24: Look at https://people.gnome.org/~markmc/openssl-and-the-gpl.html and https://lists.debian.org/debian-legal/2004/05/msg00595.html; @swinslow to report back on recommendation for generic version.

**Comment by swinslow** [comment]
OK, so, having dug into this a bit deeper I am finding several different versions of a "generic" OpenSSL exception in the wild. Here's a quick rundown with links:

1) **OpenVPN version**: see https://openvpn.net/license/. This is the exception that is [currently on the exceptions list](https://spdx.org/licenses/openvpn-openssl-exception.html). It hard-codes OpenVPN's name into the license text. 

At #762 I submitted a draft PR for a new OpenSSL-Exception that essentially just templatizes this to remove their name. Others using this version are [1](ftp://ftp.axis.com/pub_soft/MPQT/P1354/5_40_19_1/P1354_5_40_19_1_thirdpartysoftwarelicthird.txt) and [2](https://tracker.debian.org/media/packages/o/openvpn/copyright-2.4.0-6%2Bdeb9u2).

2) **Deluge version**: see https://git.deluge-torrent.org/deluge/tree/LICENSE. This was mentioned by @cas-- in the mailing list thread. This is comparable to the OpenVPN version, with some changes such as: (A) permission to link the code of *portions of* the program; (B) not mentioning modified versions of OpenSSL, or distributing linked combinations; and (C) referring to modifying and deleting the exceptions from individual files.

3) **Icinga version**: see https://github.com/Icinga/icinga2/blob/master/README.md. This is identical to the Deluge version, but in the end of the first sentence it adds: *under certain conditions as described in each individual source file, and distribute linked combinations including the two*.

This is used for several other projects, including [3](https://github.com/JoeDog/siege/blob/master/README.md) and [4](https://github.com/nbs-system/naxsi/blob/951123ad456bdf5ac94e8d8819342fe3d49bc002/naxsi_src/naxsi_raw.c)

4) **Mongo version**: see https://github.com/mongodb/mongo/blob/master/src/mongo/db/query/parsed_projection.cpp. This is similar to the Icinga version, with a few tweaks and with reference to their SSPL.

**Comment by DennisClark** [comment]
They appear to be four different exceptions to me, and trying to templatize two or more of them together might just be a bit confusing rather than helpful.

**Comment by swinslow** [comment]
Discussed on 2019-03-07 legal team call, approved adding all 4 as separate exceptions to the list, Steve will submit PR

**Comment by cas--** [comment]
To clarify, in case was overlooked, the Deluge exception is a direct copy of the Debian legal suggestion: https://people.gnome.org/~markmc/openssl-and-the-gpl.html

**Comment by swinslow** [comment]
Hi @cas--, thanks for noting this. I think the Deluge exception (item 2 in my list above) is actually slightly different from Debian legal's, as Deluge appears to have deleted the following from the end of the first line: *under certain conditions as described in each individual source file, and distribute linked combinations including the two*.

However, what I called the Icinga exception (item 3 above) includes this text and does appear to be identical to Debian legal's version. So I'll refer to item 3 as the "Debian OpenSSL exception" in the actual PR submission.

**Comment by swinslow** [comment]
I've just added #824 to add exceptions 2-4 from my earlier list above. Would welcome a review from @cas-- (or anyone else!)

**Comment by cas--** [comment]
To keep conversation thread, I'll reply here :)

> under certain conditions as described in each individual source file

Hmm I thought the point of the SPDX to not require verbose licence text in source files so the debian `as described in each individual source file` is counter to this and `under certain conditions` is rather vague for an SPDX exception. Maybe remove this portion of text? I checked Icinga code and they never mention the OpenSSL exception in any of their source files so I'm sure they would be fine with adopting a modified exception without that text. I also see the text has been removed from this [copyright](https://tracker.debian.org/media/packages/o/openvpn/copyright-2.4.0-6%2Bdeb9u2) so it has precedence. 

**Debian exception:** Using debian in the name of the generic openssl exception seems unnecessary and perhaps confusing? Other than it was proposed by Debian legal it has no other connection with Debian and `openssl-exception` name is free to use. 

**Deluge exception:** As the main Deluge developer I really just want to use a generic OpenSSL exception and happy to adopt the Debian exception. So please don't create a separate exception for us.

**mongodb exception:** The mongodb PR wording does not seem to be any different from the debian one, since it has no mention of their SSPL. Would creating the debian exception and then pointing this out to mongodb devs perhaps would suffice?

**Comment by silverhook** [comment]
The MongoDB exception seems slightly differently worded, but apart from using a bit more generic wording in places (but not in enough to make it OpenSSL-agnostic). If Mongo agrees to change their exception to the Debian one, it would be great. Unsurprisingly, I’m in favour of having fewer reasonable templates than more texts.

@cas--, that is a mighty offer to reduce the chaos in licensing. Many thanks! :)

**Comment by swinslow** [comment]
Per comments here and in #824, I'm going to suggest we remove this from 3.5 and move to 3.6, to address the recent feedback from commenters here and in the PR. Thanks!

**Comment by tsteenbe** [comment]
@swinslow  Found a slightly shorter version of OpenSSL exception today see https://github.com/psycopg/psycopg2/blob/2_7_6_1/lib/_json.py#L17-L23. Under which variant would you classify it?

**Comment by swinslow** [comment]
@MarkAtwood will take a fresh look at this for 3.10.

**Comment by MarkAtwood** [comment]
I will take and eval this one

**Comment by swinslow** [comment]
@MarkAtwood, when you review this one you'll probably also want to look briefly at #1007, which is related.

**Comment by swinslow** [comment]
@MarkAtwood any progress on this one?

**Comment by chenrui333** [comment]
Any update on this issue?

**Comment by jlovejoy** [comment]
closing, as consolidated all OpenSSL variants into #1356
