### ISSUE TITLE
New License Request: Reserved Font Name options for OFL-1.0 and OFL-1.1 [EDITED]

### ISSUE THREAD

**Issue by n8willis** [spdx/license-list-XML#724]
This request formalizes the inquiry discussed on the mailing list here: https://lists.spdx.org/g/Spdx-legal/message/2283

Proposed Full Name: Reserved Font Name

Proposed Short Identifier: RFN

URL Reference: https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web
(Additional exploration of the RFN clause by the license authors is available at https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web_fonts_and_RFNs )

OSI approval: Yes. The RFN clause is an option for both the 1.0 and 1.1 (current) versions of the Open Font License (OFL), which is OSI-approved.

Explanation: 
The RFN clause is an optional condition of the Open Font License (OFL) that the copyright holder can invoke when publishing a font under the OFL. By default, the RFN clause is inactive. If invoked on a font package, it substantially alters the work required for recipients to comply with the OFL. 

The second URL reference above details the license author/custodian's intent regarding which changes to a font binary constitute a "modification" that triggers the clause.

Since there is currently no distinction between "vanilla OFL" and "OFL with an RFN declaration" in SPDX or other license-compliance tooling, remaining in compliance is made more difficult for downstream redistributors of OFL-with-RFN fonts.

Text: 
' "Reserved Font Name" refers to any names specified as such after the
copyright statement(s).'
[...]
'3) No Modified Version of the Font Software may use the Reserved Font
Name(s) unless explicit written permission is granted by the corresponding
Copyright Holder. This restriction only applies to the primary font name as
presented to the users.'

**Comment by davelab6** [comment]
URL Reference is maybe better as https://scripts.sil.org/OFL_web (same as above in short form) or https://scripts.sil.org/OFL which is the license homepage

**Comment by DennisClark** [comment]
Assuming that actual usage of this would be something like
`OFL-1.1 WITH RFN`  
and it makes sense to me to create this as an Exception in the SPDX list.  

(Naturally this RFN bit contributes to the conversation about whether we should call such a thing an "Exception" rather than something more generic such as a "Qualifier".  That's fine with me, although it needs more discussion in the Legal call perhaps.)

**Comment by silverhook** [comment]
> (Naturally this RFN bit contributes to the conversation about whether we should call such a thing an "Exception" rather than something more generic such as a "Qualifier". That's fine with me, although it needs more discussion in the Legal call perhaps.)

+1 on both sentences from me.

**Comment by swinslow** [comment]
Discussed on 2019-01-24 call; want to discuss with broader group on next call re: whether to include separate IDs for different implementations of same license text; how this interacts with concept of exceptions; etc.

**Comment by davelab6** [comment]
Thanks for sharing the summary of the call!! I'm eager to follow along this
effort

**Comment by n8willis** [comment]
The minutes from the 1/24 call seem to be (largely) missing: https://wiki.spdx.org/view/Legal_Team/Minutes/2019-01-24

Are they forthcoming, or are they just gone for good?

**Comment by swinslow** [comment]
This request was discussed on 2019-03-21 legal team call. Consensus was not yet reached on whether to add this as separate licenses from OFL-1.0 and OFL-1.1, and more discussion was desired. The team's intention is to dedicate more time for analyzing this on the next legal team call on 2019-04-04, with the aim of making a yes-or-no decision then.

**Comment by bradleeedmondson** [comment]
Legal team volunteer here. We did not get the chance to discuss on today's call, but will look at this for the next release cycle (if it is accepted).

**Comment by jlovejoy** [comment]
oh dear, this is quite old - needs attention!

**Comment by swinslow** [comment]
Circling back on this very old issue -- I think this is a path forward:

I think it is appropriate to accommodate the RFN concept on the license list. However, I don't think it fits as an "exception" for the exceptions list. Given the way SPDX "exceptions" currently work, they're generally meant to be something that removes obligations or restriction. By contrast, treating RFN as an exception by saying `OFL-1.1 WITH RFN` is actually the opposite -- it's essentially _adding_ a restriction.

So instead, I'd propose adding separate license IDs on the main license list:
* `OFL-1.1-RFN` -- use where licensed under OFL-1.1, when we know that there _is_ a RFN
* `OFL-1.1-no-RFN` -- use where licensed under OFL-1.1, when we know that there _is not_ a RFN
* `OFL-1.1` -- also keep existing ID, to mean that it is licensed under OFL-1.1, but when _we are not asserting anything about whether there is an RFN_

and then the same pattern for OFL-1.0 as well.

I think this approach (particularly the last bullet point) keeps things consistent with current uses and meanings of the existing OFL-1.1 identifier, but adds the -RFN and -no-RFN options to enable expressing those meanings if desired.

@n8willis / @davelab6 -- any objections to this approach?
@jlovejoy and others who commented -- any concerns with handling things this way?

If no objections, I'm happy to prepare a PR to add these. However, as a heads-up, there may also be a technical issue that would need to be resolved to handle it this way. I believe the license list publisher + test infrastructure will flag an error if it sees new licenses with identical texts (which would be the case here). We would just need to configure it to exclude these OFL instances, which I think we already do for a few that are known to have identical texts (e.g. GPL-3.0-only vs GPL-3.0-or-later). cc @goneall -- I may need a bit of help from you in sorting through this  :)

**Comment by swinslow** [comment]
PR #965 submitted to address this; to be discussed on today's legal team call.

**Comment by swinslow** [comment]
Discussed on 2020-01-16 legal team call, agreed with approach above. @bradleeedmondson will review PR #965

**Comment by davelab6** [comment]
I like this approach! Thanks for moving this forwards!
