### ISSUE TITLE
BSD0 license cites someone's name

### ISSUE THREAD

**Issue by techknowlogick** [spdx/license-list-XML#737]
The BSD0 license cites the name of "Copyright (C) 2006 by Rob Landley rob@landley.net".

Issue copied from: go-gitea/gitea#5397

**Comment by zvr** [comment]
What is the issue?
The SPDX matching guidelines clearly state that copyright notices should be ignored (section **10** in https://spdx.org/spdx-license-list/matching-guidelines).

**Comment by techknowlogick** [comment]
@zvr Thanks 😄

**Comment by waldyrious** [comment]
Still, for completeness, shouldn't it be wrapped in an `<alt match=".+" name="copyright">` tag, as is done e.g. [for the ISC](https://github.com/spdx/license-list-XML/blob/3.3/src/ISC.xml#L10)?

**Comment by zvr** [comment]
PRs always welcome ;)
