### ISSUE TITLE
New license request: JPNIC / BIND license text

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#748]
I don't believe this was ever resolved in terms of new license or if we can accommodate with additional markup in Sendmail license.

See https://lists.spdx.org/g/Spdx-legal/topic/jpnic_bind_license_text/22080968?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,100,22080968 for background

**Comment by DennisClark** [comment]
I agree with Trevor "that there are enough wording differences that it would probably be easiest/safest to mint a new license identifier."   I also think it would be less confusing to have a new license, rather than make the Sendmail license more complicated.

**Comment by swinslow** [comment]
Some links in mailing list are no longer valid, including the link to the actual license text. This submission will need the actual license text at a current link for the team to evaluate. To be raised again on next legal team call.

**Comment by swinslow** [comment]
After poking around for a while, I believe the text that's being referred to can be found here:

https://gitlab.isc.org/isc-projects/bind9/blob/master/COPYRIGHT#L366

Although there are some similarities to Sendmail, I think there are enough differences that I wouldn't suggest handling it through just markup. I would recommend a new license identifier for this one. Let's discuss on today's call, and if there is agreement then I can prepare the XML.

**Comment by swinslow** [comment]
Discussed on 2019-03-07 call, agreed to add as a separate license.

**Comment by swinslow** [comment]
Thanks for taking this one @bradleeedmondson  =)

**Comment by swinslow** [comment]
@bradleeedmondson If you don't have a chance to get to this, let me know and I'm happy to help out (and/or review as a second set of eyes).

**Comment by jlovejoy** [comment]
@kemitchell picked this up with PR #828 so I've removed @bradleeedmondson  :)

**Comment by reversi-fun** [comment]
oo!
If you are still in time, give it the same name as  calculate-linux/JNIC.

https://www.calculate-linux.org/packages/licenses/JNIC

**Comment by swinslow** [comment]
Closing this issue as #828 has been merged to add JPNIC (thank you @kemitchell!)
