### ISSUE TITLE
Add markup to MIT-CMU?

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#750]
@markatwood requested new license from Python Imaging Library , but it looks to be an almost-match to a couple licenses. Consider adding markup to accommodate?

See thread at:  https://lists.spdx.org/g/Spdx-legal/topic/28745782#2505

**Comment by swinslow** [comment]
Hi @jlovejoy, I'll pick this one up and dig into it a bit deeper / review the thread and submit a PR.

**Comment by swinslow** [comment]
Having taken another look at these, I agree with the summary that @jlovejoy provided at  https://lists.spdx.org/g/Spdx-legal/message/2519 regarding the differences between this and MIT-CMU. 

I'd also note the additional "intro" language that Philippe described at 
https://lists.spdx.org/g/Spdx-legal/message/2505. And, given the way that the [Pillow LICENSE file](https://github.com/python-pillow/Pillow/blob/master/LICENSE) includes this "intro" language, it reads to me like it is intended to be part of the license itself.

One other observation: I am hesitant to mark up MIT-CMU to add the differences here as optional choices. MIT-CMU was apparently intended to reflect a specific license from [Fedora's MIT wiki page](https://fedoraproject.org/wiki/Licensing:MIT?rd=Licensing/MIT#CMU_Style), so making templating changes to it feels to me like the wrong approach. Particularly where I think there are arguably substantive differences (e.g., "permission" is different from "prior permission").

I'll prepare a PR to add a new PIL license, and perhaps we can discuss it on today's call.

**Comment by swinslow** [comment]
Just added #776 to add the PIL license. 

If the team agrees to take this route, let's also rename this Issue to something like "Add PIL license" to avoid confusion.  =)

**Comment by swinslow** [comment]
Discussed on 2019-02-21 call; will close 776 without merging, and add templating to MIT-CMU to capture the differences with the PIL license.

**Comment by jlovejoy** [comment]
is this completed, @swinslow ?

**Comment by swinslow** [comment]
I think so  =)  Just added #823 which should fix this, but would be great to get a review from you and/or @bradleeedmondson as a second set of eyes on the new templating.

**Comment by swinslow** [comment]
@swinslow to add PIL link as cross-reference
