### ISSUE TITLE
libpng license: review new version, add markup

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#751]
Latest release of libpng, 1.6.36, updated its license: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt . To cite the homepage at http://www.libpng.org/pub/png/libpng.html : "The current public release, libpng 1.6.36, . . . updates the license (identical terms to the zlib license, with the old license appended in the manner of the Python Software Foundation License version 2, and the list of contributing authors moved to a separate AUTHORS file)."

The update license file looks to be two licenses:
- the first part, "PNG Reference Library License version 2" has similar aspects as zlib, but with a longer lead-in and disclaimer in the first part
- the second part, "PNG Reference Library License version 1 (for libpng 0.5 through 1.6.35)" is similar in substance to  Libpng currently on SPDX License List, but would need review and markup to be a match. This needs further review in terms of matching to ensure differences are not legally substantive (my initial impression is that they are not)

Submitter's suggestion is to add first license and update existing Libpng (at which point, someone could use the AND operator to combine the two for identifying the license of this library.

Could someone please pick this one up and prepare a specific proposal and analysis?

**Comment by jlovejoy** [comment]
see initial email here: https://lists.spdx.org/g/Spdx-legal/topic/28914731#2520

**Comment by bradleeedmondson** [comment]
Discussed on legal call 2/7/2019. We view this as a new license and will plan to add it as libpng-2.0. I can take this issue and template it in a PR.

**Comment by bradleeedmondson** [comment]
Oops colliding with @zvr. Mind if I keep this one?

**Comment by zvr** [comment]
Sure, no problem.

**Comment by bradleeedmondson** [comment]
I've added the v2 license in #775 

Can I get a review that this looks correct? In particular we should be sure that we mean to add only the new text, not the ([new text]) + ([new header text for old license] + [old license]) as the v2. Does #775 look right to @jlovejoy @goneall ? Thanks!

**Comment by swinslow** [comment]
#775 was merged, so I'm closing this issue. Thanks @bradleeedmondson!
