### ISSUE TITLE
New license request: NCGL-UK-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by hsteptoe** [spdx/license-list-XML#763]
**1.** License Name: Non-Commercial Government Licence
**2.** Short identifier: NCGL-UK-2.0
**3.** URL: http://www.nationalarchives.gov.uk/doc/non-commercial-government-licence/version/2/
**4.** OSI Status: Not Submitted

**Comment by mlinksva** [comment]
This is another non-commercial license, these seem to have been rejected eg https://github.com/spdx/license-list-XML/issues/611 since the adoption of "general attributes of an 'open source' license" guidelines as mentioned at previous link and in https://lists.spdx.org/g/Spdx-legal/topic/26425511

**Comment by hsteptoe** [comment]
This is clearly a grey area... 

I would argue that NCGL-UK-2.0 is equivalent to the OSI approved [NPOSL-3.0](https://opensource.org/licenses/NPOSL-3.0).  The key clause of NCGL-UK-2.0 is:

> You are not permitted to: exercise any of the rights granted to you by this licence in any manner that is primarily intended for or directed toward commercial advantage or private monetary compensation.

which in my mind is equivalent to the NPOSL-3.0 saying:

> [The Licensor] derives no revenue whatsoever from the distribution of the Original Work or Derivative Works thereof, or from support or services relating thereto.

In terms of other OSI definitions, NCGL-UK-2.0 does:

- allow free distribution 👍 
- allow modifications and derived works 👍 
- not discriminate against any person or group of persons 👍 
- not restrict anyone from making use of the program in a specific field of endeavor 👍 
- ... adhere to other aspects of OSI criteria, which are hopefully self evident

Even if you still disagree that is doesn't fully comply with the OSI guidelines, the SPDX guidelines say that:

> the SPDX Legal Team does not require (1) strict compliance with all elements of the OSI Definition; or (2) strict compliance with any particular element of the OSI Definition

and, with reference to environmental considerations:

1. There are already multiple licences that are _more_ restrictive on the SPDX list, consistency of inclusion ought to be an important tenant of SPDX, and...
2. NCGL-UK-2.0 is commonly used across UK governmental work

**Comment by mlinksva** [comment]
It's not at all equivalent to NPOSL-3.0, which does not limit licens**ee** commercial use. Any licensee that is not a non-profit can distribute the work or derivatives under OSL-3.0.

**Comment by jlovejoy** [comment]
you are both right - we have generally rejected non-open source licenses and we have included at least one (from top of my head) non-commercial license (the CC-NC variants) on the SPDX License List. All of the CC licenses were included on the list in early days before we had defined inclusion guidelines (see https://wiki.spdx.org/view/Legal_Team/Decisions/Inclusion_Guidelines_(Background) for a bit of that history)

**Comment by mlinksva** [comment]
Thanks for that additional context link @jlovejoy!

Personally I think there might be some value in SPDX cataloging non-open licenses with demonstrated wide use (so that detection tools using the SPDX license list/texts can make life easier for their users by positively identifying those licenses with SPDX IDs) but there's also value in keeping primary focus on open licenses not not making it appear that non-open licenses are open. One solution might be a non-open license list, perhaps reflected on the website at a URL something like https://spdx.org/licenses/non-open ... of course the CC NC and ND licenses that made it through to the main list in pre-guidelines could be moved there, and others added there ... just random thought. 😄

**Comment by jhabdas** [comment]
to echo the thoughts of @mlinksva the more competition businesses have with black duck the better, imho, and this seems like the logical jumping point. this would allow more tools like https://github.com/jslicense/licensee.js to come out and open what is otherwise closed by services which are opaque.

**Comment by hsteptoe** [comment]
Thanks for the continued discussion on this...

Personally, I think I would be helpful to acknowledge that the use of NC or similar licences sometimes reflects movement by organisations and institutions, that have not _historically_ engaged with open source, towards a more open-source way of thinking.  Being too puritanical about open licences may actually hinder the change and heighten the inertia.

The motivation behind my original request was making some data available on Zenodo. This is not yet common at my institution, but having a range of licence options that our project managers feel comfortable using in the context of a range of different project agreements, is a step towards making this more common.  

By all means, be accurate and clear with the definition of an open licence, and the way that NC might not fit within this definition, but pervading an attitude of "_open or nothing_" is likely to result in no change.

**Comment by jhabdas** [comment]
WRT definition of "Open Source" I'd just like to state here I think GNU got it wrong and their license matrix says it all. Nothing could be less open than slapping a license on your software no one could use or understand. Open source to me is BSD and [public domain equivalents](https://en.wikipedia.org/wiki/Public-domain-equivalent_license). But I digress.

**Comment by jhabdas** [comment]
WRT definition of "Open Source" I'd just like to state here I think GNU got it wrong and their [license compatibility matrix](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility) says it all. Nothing could be less open than slapping a license on your software no one could use or understand. Open source to me is BSD and the like, and [public domain equivalents](https://en.wikipedia.org/wiki/Public-domain-equivalent_license). Open needs to consider people with cognitive disabilities not create the most bulletproof license as its an impossible game. We just need to undo Berne entirely for anything digital and I think we're good. But I digress.

**Comment by swinslow** [comment]
Discussed on 2019-03-07 legal team call. See related comments in https://github.com/spdx/license-list-XML/issues/767#issuecomment-470709673. Similar discussions applied here, albeit without the relation to pre-existing CC licenses. Outcome of the call was same approach as in the link above, anticipated that this will be revisited and a decision reached on the next legal team call.

**Comment by jlovejoy** [comment]
discussed on 2019-03-21 legal team call - see comments on #767 as similar issues. 
note as per some of the comments above - the question as to whether SPDX License List should allow non-free / non-open source licenses (e.g., freeware licenses) beyond the CC ones that are already there is a perennial one. There are some good reasons not to (e.g. those licenses often change frequently and are very hard to track, making a mess), most notably, the SPDX spec already has a way to deal with licenses not on the SPDX License List by using the LicenseRef- tag. 
As this discussion hits upon some bigger issues, we are going to hold, but push out to allow for those bigger discussions to occur.

**Comment by MarkAtwood** [comment]
Recommend the scoped license identifier  LicenseRef-.gov.uk.-NCGL-2.0

**Comment by swinslow** [comment]
Circling back here -- I think the "yes or no" on this one is tied to the ongoing discussions for the License Inclusion Guidelines updates being discussed at #925. That is intended to be addressed during 3.8, so I'm moving this to 3.8 also. After a decision is reached on updating the guidelines, we should be able to give this a "yes or no" outcome.

**Comment by swinslow** [comment]
Following up on this quite old issue. The SPDX license list inclusion principles have now been updated, see https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md.

In light of the updated principles, and a broader intent to include "source available" licenses that aren't fully compliant with the OSD or similar definitions, I would be in favor of adding this one to the list. There's evidence of significant use in the wild. Reading its definition of "Licensor," I'm actually a bit unclear whether it is possible for others to reuse the license, or whether it's limited to just the UK government. But all-in-all I would be in favor of adding it, and I think the NC restrictions can be pictured similarly to the discussion in #767 for adding a new CC license with -NC terms.

**Comment by jlovejoy** [comment]
see PR #1030
