### ISSUE TITLE
Use header-less archive.org URLs

### ISSUE THREAD

**Issue by ppalaga** [spdx/license-list-XML#777]
E.g. compare

http://web.archive.org/web/20021004124254/http://www.opensource.org/licenses/academic.php

used now with

http://web.archive.org/web/20021004124254id_/http://www.opensource.org/licenses/academic.php

The second variant shows the original content without the archive.org header, which should IMO be preferred.

**Comment by mlinksva** [comment]
I prefer with the header. The wayback machine is a research tool and not having the header which makes it easy to navigate among snapshots makes the link less valuable to me. Plus it's more clear what is going on (viewing an archived copy) for all who ignore URLs.

**Comment by ppalaga** [comment]
My motivation for this is very similar to #779:

The header-less variant of the URL returns the same content over time. To the very opposite, the  variant with the header returns different content on every request. It is easy to demonstrate using `curl` and ` sha1sum`.

Stable content is useful because:

1. It allows grouping interchangeable URLs. If the URLs do not return any irrelevant clutter, I can simply group them by sha1 of the content. 

2. It allows a simple automatic check that the URL returns the same content over time. URLs come a and go. In some cases redirects are set, that do not refer to pages that contain the actual license text. With the irrelevant clutter included in the content I am even not able to tell reliably that the content has changed at some point in time and that a human should review the content and decide if it still relevant at all. This kind of automatic testing is a good thing and issues like #780 prove that it would  make sense also for the date in the current repository.

**Comment by jlovejoy** [comment]
I don't see much reason to change these to the headerless variant for the reasons @mlinksva noted, but also because the URLs are really just for reference. We always knew they may become stale (which was part of the purpose of having the SPDX License List - reliable place to find the license text!)

please also note as to stale URLs, we did come up with this general guidance to not remove stale URLs: https://spdx.org/spdx-license-list/license-list-overview#fields

**Comment by swinslow** [comment]
Agree with the earlier comment from @jlovejoy -- the approach has been that even stale / inactive URLs should not be removed or changed, so I don't think that existing archive.org URLs should be modified.
