### ISSUE TITLE
Prefer raw.githubusercontent.com to github.com

### ISSUE THREAD

**Issue by ppalaga** [spdx/license-list-XML#779]
E.g. compare

https://github.com/asimonov-im/bzip2/blob/master/LICENSE

used now with

https://raw.githubusercontent.com/asimonov-im/bzip2/master/LICENSE

The second variant shows the original content without the GitHub UI, which should IMO be preferred.
The question is also whether it is a good idea to refer to the master branch. A specific commit or tag is perhaps more preferable, because people sometimes move license files around, e.g LICENSE.txt -> LICENSE etc.

**Comment by ppalaga** [comment]
There is also https://github.com/aws/mit-0 that should better be https://raw.githubusercontent.com/aws/mit-0/master/MIT-0

**Comment by ppalaga** [comment]
Similarly for git.kernel.org: plain https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/plain/drivers/infiniband/core/sa.h would be better than https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/core/sa.h

**Comment by ppalaga** [comment]
Similar for yet another git ui: http://git.savannah.gnu.org/cgit/bison.git/plain/data/yacc.c?id=193d7c7054ba7197b0789e14965b739162319b5e
better than http://git.savannah.gnu.org/cgit/bison.git/tree/data/yacc.c?id=193d7c7054ba7197b0789e14965b739162319b5e#n141

**Comment by mlinksva** [comment]
I feel the same way for this as I do for #777 -- a link to raw content without UI for navigating history (commits in this case, snapshots the other) makes the link less useful. 

Your savannah example shows another downside -- the raw content version doesn't link directly to the most pertinent line (I guess it is used to document an exception?) but the HTML version does.

There are certainly contexts in which linking to raw content is most welcome -- a download link for example, but provision of cross-references doesn't strike me as such a context.

**Comment by ppalaga** [comment]
I am realizing I said "I prefer" without saying why. Sorry, let me explain: 

The raw variant of the URL returns the same content over time unless a new version is pushed to the git repository. To the very opposite, the github.com variant returns different content on every request. Please try it yourself:

```
curl https://github.com/asimonov-im/bzip2/blob/master/LICENSE > lic1.html
curl https://github.com/asimonov-im/bzip2/blob/master/LICENSE > lic2.html
diff lic1.html lic2.html
```

vs. 

```
curl https://raw.githubusercontent.com/asimonov-im/bzip2/master/LICENSE > lic1.txt
curl https://raw.githubusercontent.com/asimonov-im/bzip2/master/LICENSE > lic2.txt
diff lic1.txt lic2.txt
```

And that's exactly the reason: I want to be able to track any changes in the license text. Unlike the raw variant, the github.com variant is quite useless for any automatic checks of this kind. 

With github.com, I even cannot reliably tell if http and https URLs are interchangeable.

**Comment by ppalaga** [comment]
> Your savannah example shows another downside -- the raw content version doesn't link directly to the most pertinent line (I guess it is used to document an exception?) but the HTML version does.

OK, let's exclude URLs a having line anchor from the scope of this issue.

**Comment by mlinksva** [comment]
> I want to be able to track any changes in the license text.

OK, I appreciate that use case. I only had in mind the human browsing use case.

FWIW it's possible at least for github, savannah, and archive.org (in #777) to mechanically transform a URL with HTML that won't always return identical content to a raw content URL. In tests for another project https://github.com/github/choosealicense.com/blob/44260e9c6b1267a8825896386804619eb8f52c8d/spec/license_meta_spec.rb#L58-L64

```ruby
            if example_url.start_with?('https://github.com/')
              example_url.gsub!(%r{\Ahttps://github.com/([\w-]+/[\w\.-]+)/blob/([\w-]+/\S+)\z}, 'https://raw.githubusercontent.com/\1/\2')
            elsif example_url.start_with?('https://git.savannah.gnu.org/', 'https://git.gnome.org/')
              example_url.gsub!(%r{/tree/}, '/plain/')
            elsif example_url.start_with?('https://bitbucket.org/')
              example_url.gsub!(%r{/src/}, '/raw/')
            end
```

> With github.com, I even cannot reliably tell if http and https URLs are interchangeable.

There's no reason to ever use a http URL with the site. Any such links ought be changed to https.

**Comment by ppalaga** [comment]
> it's possible at least for github, savannah, and archive.org (in #777) to mechanically transform a URL with HTML that won't always return identical content to a raw content URL

Yeah, that's exactly what we ended up doing in license-maven-plugin: https://github.com/mojohaus/license-maven-plugin/blob/558e6986409f34ae7319ba1346c9162809fb75b2/src/build/scripts/GenerateSpdxLicenseList.groovy#L40-L45

> > With github.com, I even cannot reliably tell if http and https URLs are interchangeable.
> 
> There's no reason to ever use a http URL with the site. Any such links ought be changed to https.

I fully agree, but our use case in license-maven-plugin is typically to aggregate/validate license names/texts/URLs based on Maven metadata where all kinds crap is possible. SPDX helps a lot, many thanks for having it!

**Comment by swinslow** [comment]
Note that generally cross reference URLs should not be removed / replaced. E.g., from https://spdx.org/spdx-license-list/license-list-overview:

> Note that the source URL may refer to an original URL for the license which is no longer active. We don't remove inactive URLs. New or best available URLs may be added.

I realize that's talking about inactive URLs, not "preferable vs. less preferable" URLs, but either way I think the principle holds. A URL to a license text might not just be to point to the exact text. It might also be useful, for instance, as a marker in other code as evidence that the code was meant to be under the license. I'm just noting this to say that even if raw Github links are added to existing entries, I don't think the existing non-raw links should be removed.

Either way, if the proposal is to add raw github links to the existing license list entries (and to maintain them for new entries going forward), are there volunteers to do so? If not then I'm inclined to close this issue.

**Comment by swinslow** [comment]
Circling back from my earlier comment above, I haven't seen comments from volunteers to add + maintain raw github links to existing license list entries, so I am going to go ahead and close this issue. Anyone who is interested in volunteering to help with this should feel free to re-open.

As a general matter, when creating new license list entries, we can aim to prefer raw Github links where feasible. Sometimes this will be in addition to "non-raw" links since the cross-reference field has multiple purposes, including to assist with matching other references to licenses that are used in ordinary day-to-day usage.
