### ISSUE TITLE
New license request: blessing [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by drhsqlite** [spdx/license-list-XML#819]
**1.** License Name: The SQLite Blessing
**2.** Short identifier: blessing
**3.** License Author or steward: The SQLite development team
**4.** URL: https://www.sqlite.org/src/artifact/e33a4df7e32d742a?ln=4-9
**4.** OSI Status: Not Submitted

**Comment by drhsqlite** [comment]
Alternate URL: <https://sqlite.org/src/file/LICENSE.md>

**Comment by pombredanne** [comment]
quite blessed to have @drhsqlite chime in !
FWIW, I have tracked this as a plain public domain dedication in ScanCode until now https://github.com/nexB/scancode-toolkit/blob/45bbafd170732ed6eb998b59cace74de6c18f22d/src/licensedcode/data/rules/public-domain_144.RULE

**Comment by swinslow** [comment]
I'm in favor of adding this to the license list.

I think it's comparable (at least in the disclaimer scope) to others on the SPDX License List like [Unlicense](https://spdx.org/licenses/Unlicense.html), albeit less detailed on the grant / disclaimer scope. I've come across this particular statement in SQLite-related tools in the wild. And certainly SQLite is used [everywhere](https://sqlite.org/mostdeployed.html)...

**Comment by jlovejoy** [comment]
+1 on adding this, especially since it's been in use for a long time by a major project

**Comment by swinslow** [comment]
All, please feel free to take a look at #877 and let me know any feedback. Short and simple so hopefully it'll be good to go  =)

**Comment by swinslow** [comment]
Discussed on 2019-06-13 legal team call, agreed to add this one.
