### ISSUE TITLE
New license request: CC-PD [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by reversi-fun** [spdx/license-list-XML#836]
**1.** License Name: Copyright-Only Dedication (based on United States law) or Public Domai
**2.** Short identifier: CC-PD
**3.** License Author or steward: creativecommons.org
**4.** Comments: This license likes spdx/Unlicense,but Terms are different.

creativecommons.org says "CC0 for Public Domain Dedication",
But There is a project using this license, Exsample is calculate-linux.org.
**5.** URL: https://creativecommons.org/licenses/publicdomain/
**6.** OSI Status: Not Submitted

**Comment by pombredanne** [comment]
FWIW this is tracked in ScanCode as https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-pd.yml and https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/cc-pd.LICENSE

**Comment by swinslow** [comment]
I've come across this periodically in the wild, in some cases for works that moved to CC0 for later versions, but used this public domain statement for earlier releases. As the submitter noted, this seems reasonably comparable to something like The Unlicense. 

I think this is appropriate to include on the License List, even though Creative Commons has retired it and doesn't recommend it for new works going forward.

My only comment is that we might want to use the name "Public Domain Certification" and the short identifier "CC-PDC". It appears that Creative Commons separately has a "Public Domain Mark" option, see https://creativecommons.org/publicdomain/mark/1.0/, and we should probably make sure the name + identifier align to the old tool.

**Comment by mlinksva** [comment]
If not CC-PD I would recommend CC-PDDC. It started as a dedication only https://web.archive.org/web/20021222174155/creativecommons.org/licenses/publicdomain but was  characterized as a dedication and certification early on https://web.archive.org/web/20040402125107/http://creativecommons.org/licenses/publicdomain/ and referred to as CC-PDDC various places eg https://wiki.creativecommons.org/wiki/PDM_FAQ#What_about_CC.E2.80.99s_Public_Domain_Dedication_and_Certification.3F_Can_that_tool_still_be_used.3F

**Comment by swinslow** [comment]
@mlinksva Thanks for the background -- this is very helpful. Agreed, CC-PDDC sounds like a good choice for the ID here.

**Comment by swinslow** [comment]
Discussed on 2019-04-18 Legal Team call, agreed that this can be added to the License List.

**Comment by bradleeedmondson** [comment]
The links @mlinksva provides lead to two different license texts, the 2002 PD Dedication and the 2004 PD Dedication or Certification.

In my opinion, those are substantially different from each other (legally), so I think we'll need to add these as two different licenses with two different IDs.

**Comment by swinslow** [comment]
Agree with @bradleeedmondson -- these do appear to be two separate texts and should probably get two separate entries. We may want to get Creative Commons' input on the desired names and identifiers for these two entries, before they are added to the list.

**Comment by pombredanne** [comment]
@swinslow @bradleeedmondson so you confirm that the 2002 text reported by @mlinksva should be treated as separate license from the 2004 text?

The 2004 text is rather common. The 2002 text is rather uncommon: https://github.com/search?q=%22The+person+or+persons+who+have+associated+their+work+with+this+document%22&type=Code ... 9 files. And a few odds and ends: http://www.authorama.com/microsoft-research-drm-talk-7.html ... I am fine to treat it as a new license, but I am not sure this passes a usage threshold.

**Comment by pombredanne** [comment]
and FWIW there is not much of the 2002 version used elsewhere too https://www.google.com/search?q="The+person+or+persons+who+have+associated+their+work+with+this+document"

**Comment by swinslow** [comment]
@pombredanne I do think they should be treated differently. They read to me as having substantive differences. Other than looking at the archive links, I don't know enough about the history of them to know whether 2002 / 2004 are the appropriate dates that we would reference.

Very helpful to know that what we're currently calling the 2004 text is quite common -- and that the 2002 version is rare -- thanks for researching and confirming! 

Based on that, I'd be inclined to say that perhaps we add the 2004 text as "CC-PDDC", and omit the 2002 version altogether for now. @bradleeedmondson, would you agree?

**Comment by jlovejoy** [comment]
@mlinksva - do you have any comments on the two variants found (and adding just the 2004 variant for above stated reasons)?

**Comment by mlinksva** [comment]
Sorry, missed question until now. I agree with @swinslow above:

> Based on that, I'd be inclined to say that perhaps we add the 2004 text as "CC-PDDC", and omit the 2002 version altogether for now.

**Comment by jlovejoy** [comment]
ok, so short identifier = CC-PDDC
(is that for Public Domain Dedication or Certification?)
and for full name = Creative Commons Public Domain Dedication or Certification
??
If we stuck with what the CC website says, it'd be "Creative Commons Copyright-Only Dedication* (based on United States law) or Public Domain Certification" - but that is awfully long and I'm not crazy about a parenthetical in the middle of a full name... but that would be accurate...

**Comment by mlinksva** [comment]
👍 Creative Commons Public Domain Dedication and Certification

That's what it's called on https://creativecommons.org/retiredlicenses/ FWIW.

**Comment by bradleeedmondson** [comment]
I agree, and support adding the widely used 2004 text as CC-PDDC, and
leaving off the 2002 text for now. If we need to add the 2002 text later,
we can suffix "-2002" and treat it as a minor (but legally distinct)
variant.

**Comment by jlovejoy** [comment]
merged #884
