### ISSUE TITLE
New license request: Ruby-Artistic [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by reversi-fun** [spdx/license-list-XML#837]
**1.** License Name: the old version of the Ruby license(Artistic-1.0 license like)
**2.** Short identifier: Ruby-Artistic
**3.** License Author or steward: ruby-lang.org
**4.** Comments: This is the old version of the Ruby license which was used up until the release of the 1.9.3 version of the MRI Ruby interpreter.
The new version of Ruby license is called 'Ruby-BSD' in Gentoo.
Both {the old calculate-Linux/Ruby ​​and the new calculate-Linux/Ruby-BSD} are included in the calculate-Linux license list.

However, SPDX&FSF calls calculate-Linux/Ruby-BSD under the name spdx/Ruby & FSF/Ruby.
So it would be reasonable to give the old "calculate-Linux/Ruby" the new name "spdx/Ruby-Artistic".
The terms "spdx/Ruby-Artistic" are similar to Artistic-1.0, including being certified as not-free by the FSF.
**5.** URL: https://www.calculate-linux.org/packages/licenses/Ruby
**6.** OSI Status: Not Submitted

**Comment by reversi-fun** [comment]
Attach evidence that Ruby-Artistic and Artistic-1.0 were analyzed as similar.

https://github.com/reversi-fun/license_doc_similality1/blob/master/data/lic_graph.fdp.svg

![ruby-artistic-simlal](https://user-images.githubusercontent.com/2231549/55125878-8314fb00-514e-11e9-943c-2862572c2e80.png)

**Comment by swinslow** [comment]
This does appear to be close to (but different from) the [Ruby license](https://spdx.org/licenses/Ruby.html) that's currently on the SPDX License List. Based on comments in the URL listed above, it sounds like it's an earlier version of Ruby's license.

Do you have a more canonical URL for it, e.g. a link to the license text on the Ruby website or in a Ruby source code repo? And/or a link to such a page in the Internet Archive?

If we can locate it in an original Ruby source, I'm in favor of adding it. 

I would recommend though that we give it a name like "Ruby-______", where ______ is the version # of Ruby that it was associated with. Given its closeness to the existing Ruby license, I don't think "Artistic" should be included in the name.

**Comment by reversi-fun** [comment]
OK.
* License Name: Ruby Narrow-defined Old License(version 1.6 - 1.9.2)
    The Japanese version of the wiki explains as follows:
     https://ja.wikipedia.org/wiki/Rubyライセンス
  * in Japanease : ```(狭義のRubyライセンスはArtistic Licenseをベースに、Ruby言語に適した制約に修正したライセンスである)```

  * in english: ```(The narrowly-defined Ruby license is a license based on the Artistic License and modified to the restrictions suitable for the Ruby )```

* ShortName replace: "Ruby-1.8-older"
   before 1.4 version of Ruby License is GPL-2.0.
   version 1.6,(1.7Absent),1.8,1.9.1,1.9.2 of Ruby license is "Ruby-Artistic"
   because 1.9.3 version of Ruby license changes 'Ruby-BSD'.

* "original Ruby source URL" is :
    https://github.com/ruby/ruby/blob/ruby_1_6/COPYING
    https://github.com/ruby/ruby/blob/ruby_1_8_7/COPYING
    https://github.com/ruby/ruby/blob/ruby_1_9_2/COPYING
Correct URL(But old refered) is: 
    http://www.ruby-lang.org/en/about/license.txt(ref from Debian Linux license list )

**Comment by jlovejoy** [comment]
as per june 23rd legal call - more research needed here (and not enough time)

**Comment by MarkAtwood** [comment]
I suggest
 LicenseRef-.rubylang.org.-Older
 LicenseRef-.rubylang.org.-Artistic
 etc

**Comment by swinslow** [comment]
I've compared the texts of the 1.6, 1.8.7 and 1.9.2 Ruby versions that were linked in https://github.com/spdx/license-list-XML/issues/837#issuecomment-484032370, as compared to the current Ruby license text at http://www.ruby-lang.org/en/LICENSE.txt

The only substantive differences I see among the versions is in the other license option (the "Ruby OR _____") that's listed in the intro paragraph. In 1.6 it was "GPL", 1.8.7 and 1.9.2 were "GPL version 2" and currently it's "2-clause BSDL".

But that intro paragraph is not part of the [Ruby license text on the SPDX site](https://spdx.org/licenses/Ruby.html), and the Notes on that page already note that Ruby as a project is disjunctively licensed under other licenses. Thus, the "OR ______" option is part of Ruby the project's licensing, not as part of the "Ruby license" text.

Therefore, no change is needed here and I am closing this issue.
