### ISSUE TITLE
New license request: intel-ucode [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by reversi-fun** [spdx/license-list-XML#839]
**1.** License Name: intel CPU microcode license
**2.** Short identifier: intel-ucode
**3.** License Author or steward: Intel Corporation.
**4.** Comments: This license is called calculate-Linux/intel-ucode.
This license is BSD-3-Clause based ,but  "Binary form" clause is added.
 "Binary form" clause is Good for Distributor.

Intel says That:
--
Update: 10:44 AM, 23 August 2018: Intel’s full updated license and statement:

 We have simplified the Intel license to make it easier to distribute CPU microcode updates and posted the new version http://bit.ly/2w9RjtM. As an active member of the open source community, we continue to welcome all feedback and thank the community.
---

https://wccftech.com/intel-microcode-update-gag-order-benchmarks/
https://www.reddit.com/r/linux/comments/99rqm0/intel_clears_up_microcode_licensing_controversy/
**5.** URL: https://www.calculate-linux.org/packages/licenses/intel-ucode
**6.** OSI Status: Not Submitted

**Comment by zvr** [comment]
The canonical URL should be:
https://01.org/mcu-path-license-2018

and the short identifier should have a version like "-2018"

**Comment by reversi-fun** [comment]
Thanks.
Short identifier replace to : intel-ucode-2018

**Comment by swinslow** [comment]
This is a binary-only distribution license, e.g. more of a freeware license with no source code rights granted and no modification permitted.

This does not fit with the SPDX license inclusion principles (https://spdx.org/spdx-license-list/license-list-overview). I suggest this should be rejected and this issue should be closed.

**Comment by reversi-fun** [comment]
I understand that [calculate-Linux/intel-ucode](https://old.calculate-linux.org/packages/licenses/intel-ucode) required to use Linux sometimes does not fit in spdx.

I am satisfied with what I could pass until the analysis of similarity.

**Comment by swinslow** [comment]
Discussed on 2019-04-18 Legal Team call, agreed that this should be rejected as being binary-only.
