### ISSUE TITLE
Apache-1.1 template markup

### ISSUE THREAD

**Issue by reversi-fun** [spdx/license-list-XML#840]
**1.** License Name: CA Open Source Licence Version 1.0
**2.** Short identifier: CAOSL-1.0
**3.** License Author or steward: Computer Associates.
**4.** Comments: This License likes (("Apache-1.1" + Entessa + "calculate-Linux/JNIC")/3).

The license holder seems to be stuck with the difference, AS there:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=15abaf9459ca5f92b77c048f578c609f1f7d34e6
**5.** URL: https://www.calculate-linux.org/packages/licenses/CAOSL
**6.** OSI Status: Not Submitted

**Comment by reversi-fun** [comment]
I add evidence that I have analyzed similarity.

https://github.com/reversi-fun/license_doc_similality1/blob/master/data/lic_graph.sfdp.svg
![CAOSL-license](https://user-images.githubusercontent.com/2231549/55133888-86b67b00-516a-11e9-9404-ebc791c08a7c.png)

**Comment by pombredanne** [comment]
This is a variant of Apache-1.1 and IMHO not worthy of a new license id.

**Comment by reversi-fun** [comment]
IMHO?
1. CAOSL-1.0 has less disclaimer than Apache-1.1.
  CAOSL-1.0 does not indicate the existence of any other copyright holder and the possibility of betrayal.
  Apache-1.1 sayes "This software consists of voluntary contributions made ....". 
  It suggests a legal risk.

2. The prohibition conditions in paragraph 5 are different.
  CAOSL-1.0 prohibits only the name of the copyright holder.
  Apache-1.1 prohibits  some names(copyright holder and product name trademark?).
 for exsample:
  "my-apache-commmon" is drived from CAOSL-1.1 licensed product.
   It is not a violation in CAOSL-1.1. 
   but It's a violation in Apache-1.1 .

**Comment by jlovejoy** [comment]
it is a match to Apache-1.1 with a couple minor variations:
* clause 4 removes the last sentence, "For written permission..."
* clause 5 states "Products may not include <NAME> ..." as opposed to "Products derived from this software may not be called <NAME>..." 

I don't think either of these differences as being substantively different from a legal point of viewand could be accommodated with additional markup to Apache-1.1 - @swinslow @bradleeedmondson - do you agree?

**Comment by swinslow** [comment]
@jlovejoy circling back on your questions here -- I agree that I am comfortable with accommodating the changes in markup and treating these as the same license for SPDX matching purposes.

The one thing I'm not sure about is for the second bullet (clause 5), whether the XML markup is capable of expressing an option between those two choices: "Products may not include _____ in their name" OR "Products derived from this software may not be called _____, nor may _____ appear in their name". 

At least, I'm not certain offhand how to express that in the markup  =)  I'll take a closer look but we may need some help from others in determining whether that's workable. cc @zvr @bradleeedmondson @goneall in case any of you have thoughts!

**Comment by swinslow** [comment]
Marking as "technical issue" since this needs input from the more tech-minded folks on whether the options can be expressed in markup, and if so how...

**Comment by goneall** [comment]
> The one thing I'm not sure about is for the second bullet (clause 5), whether the XML markup is capable of expressing an option between those two choices: "Products may not include _____ in their name" OR "Products derived from this software may not be called _____, nor may _____ appear in their name".

Creating an `<alt` tag with a more complex and complete regex should take care of this.

Following is an example of a regex which matches the 2 clauses.  It also includes the 2 existing `<alt` tag regexes.

Change:

```
 Products derived from this software may not be called
          <alt match=".+" name="name1Clause5">"Apache" [ex. "Jakarta," "Apache," or "Apache Commons,"]</alt> nor may
          <alt match=".+" name="name2clause5">"Apache" [ex. the names]</alt> appear in their name, without
          prior written permission of
          <alt match=".+" name="name3clause5">the Apache Software Foundation</alt>.
```

to:

```
<alt match="(Products derived from this software may not be called\s.+nor may\s.+appear in their name, without prior written permission of\s.+.|Products may not include\s.+in their name, without prior
written permission of\s.+.)" name="Clause5">Products derived from this software may not be called "Apache" [ex. "Jakarta," "Apache," or "Apache Commons,"] nor may "Apache" [ex. the names] appear in their name, without prior written permission of the Apache Software Foundation.</alt>
```

I tested the regex against the 2 variants using the [Rexex 101 regex tester](https://regex101.com/).

**Comment by goneall** [comment]
Is clause 4 the only other clause to be updated?  If so, I can create a PR with the above change and another update for clause 4.

**Comment by swinslow** [comment]
Hi Gary, yes, clauses 4 and 5 are the only ones with changes.

My only question on the regex's is about how it is displayed on the license list. If I am correctly understanding the example you gave above, it looks like the regex would match against either example -- but, the license list website would only display the plain text that is between the alt tags. 

In other words, someone looking at the license list on the website wouldn't know that either of the matches is permitted -- they would only see one of the options. Is that correct, or am I misunderstanding how it would be rendered?

**Comment by goneall** [comment]
> My only question on the regex's is about how it is displayed on the license list. If I am correctly understanding the example you gave above, it looks like the regex would match against either example -- but, the license list website would only display the plain text that is between the alt tags.

That is correct.   The website would display the text as red indicating it is `alt` text.  You could change the text within the alt text without changing the template matching, but it would probably mess up simpler text matching tools that do not use the markup (there are several of them out there).  Another option would be to update the tools to have some text show up as hover text.  This would require changing the tools.

**Comment by swinslow** [comment]
@goneall Got it -- thanks Gary. I think I've been incorrectly assuming that the red text in the license list was always an "anything goes" match, when of course it isn't -- my mistake!

For this one, it would be fantastic if you're able to proceed with the PR that you proposed. I think it's worth us adding the alt match as you described.

In terms of modding the tools to e.g. have alt text match options display on the license list page, I recognize that would probably take some time to modify -- so no need for us to worry about that now, or to hold this one up in the meantime. Thanks again!

**Comment by goneall** [comment]
@swinslow Added the PR with markup for both clauses - pls review and merge if its OK.  This should resolve this issue.

**Comment by swinslow** [comment]
Hi @goneall, I just added a comment in the #963 PR thread -- Apache-1.1 edits look great (thank you!!) but I wasn't sure if the matching guidelines change was added inadvertently?

**Comment by swinslow** [comment]
#963 is now merged (after removing the guidelines edit) so this is resolved. Thank you again @goneall!
