### ISSUE TITLE
New license request: Java-Spec [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by reversi-fun** [spdx/license-list-XML#847]
**1.** License Name: Java Specification License Templates for Reference Implementation.
**2.** Short identifier: Java-Spec
**3.** License Author or steward: Oracle America, Inc.
**4.** Comments: This is a "license template" for Java VM and Java module.

Because the Java module license was waiting to be naming of each artficate-name, it resulted in a revolt of the variant.

  * [Spec Leads License Reference](https://jcp.org/en/resources/license_reference)
    * [SAMPLE SPEC GENERAL LICENSE AGREEMENT
](https://www.spec.org/spec/docs/sample_license_agreement.pdf)
  　* Java-RL(Java Research License)
    * Java-DL(Java Distribution License)
      calculate-Linux/sun-jsr67,"scancode-toolkit/src/licensedcode/data/licenses/day-spec.LICENSE"
    * Java-Eval(JSR Spec Evaluation License)
    * [Java-BCL](https://www.oracle.com/technetwork/java/javase/terms/license/index.html)
    * [Oracle Binary Code License Agreement For the Java SE version 10 Reference Implementation](https://jdk.java.net/java-se-ri/10-bcl)

Implementer of openJDK(or Java module) is increasing, I propose to decide the license name of the template before resurgence starts again.
"API Specification" is "fair use" and Not protected by CopyRight,
But I think that API specification with reference implementation is copyrighted and may have a license statement.
  * [calculate-Linux/sun-jsr67](https://old.calculate-linux.org/packages/licenses/sun-jsr67)
  * [scancode-toolkit/src/licensedcode/data/licenses/sun-jsr-spec-04-2006.LICENSE]()
  * [JSR-000337 JavaTM SE 8 Release Contents Final Release LIMITED LICENSE GRANTS](https://download.oracle.com/otndocs/jcp/java_se-8-fr-spec/license.html),[calculate-Linux/oracle-java-documentation-8](https://old.calculate-linux.org/packages/licenses/oracle-java-documentation-8)
  * [JavaSE9 spec license-3903847](https://www.oracle.com/technetwork/java/javase/overview/javase9speclicense-3903847.html),[calculate-Linux/oracle-java-documentation-9](https://old.calculate-linux.org/packages/licenses/oracle-java-documentation-9),
  * [calculate-Linux/oracle-java-documentation-11](https://old.calculate-linux.org/packages/licenses/oracle-java-documentation-11)
**5.** URL: https://jcp.org/aboutJava/communityprocess/speclead/final-license.txt
**6.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
From the links listed at the top of this issue, the first one appears to have nothing to do with specifications or Oracle / Java, and appears to just be from an organization called "SPEC". Does not appear to be an open source license.

Two of the other licenses mentioned at the top do not include links, so I do not know what they are referring to.

The final two listed are binary code agreements that are not open source licenses.

I suggest this issue should be closed.

**Comment by reversi-fun** [comment]
"binary code agreements" ?

Oracle-OpenJDK and Adapt-OpenJDK, JSR-000337 etc..,  is licensed under this licenses variation.
(It may contain many variants to identify the "spec". )
And, It  have restrictions on "source code" and "implementation of the Specification".

https://jcp.org/aboutJava/communityprocess/speclead/final-license.txt
```
5. Definitions. 
 For the purposes of this Agreement: 
 "Independent Implementation" shall mean 
an implementation of the Specification 
that neither derives from any of 
Specification Lead's  source code or binary code materials nor,
except with an appropriate and separate license from Specification Lead, 
includes any of Specification Lead's  source code or binary code materials;
```

**Comment by reversi-fun** [comment]
The meaning of the grouping of licenses mentioned at the beginning does not seem to be understood.(In my broken English)

Those licenses can be grouped before or after 2014Year.

In 2014, the Court of Appeals Court found that not only API functions but also code declarations and structures, sequences, and configurations (SSO)  that Google had copied from 37 Java API packages are copyrighted.
https://www.reuters.com/article/us-oracle-google-ruling/oracle-wins-copyright-ruling-against-google-over-android-idUSBREA480KQ20140509

This Issue, I proposed a "Specification license with a reference implementation" that is also an SSO to be protected by copyright in a post 2014Year Precedent.

Furthermore, since the variation of the license is wide,SO I proposed a template license.

I attach the figure which shows the similarity of the template license and the variant which I found.


The attached figure can be expanded,by downloading the following SVG file, 
opening it with a browser, and searching for "license template for implementing final JSRs".
   https://github.com/reversi-fun/license_doc_similality1/blob/master/data/lic_graph.fdp.svg

![license template for implementing final](https://user-images.githubusercontent.com/2231549/57196002-6eb8ef00-6f93-11e9-97d7-6ce604ac8352.png)

**Comment by jlovejoy** [comment]
I'm finding this all a bit confusing, but am assuming the actual license text you are proposing to add is https://jcp.org/aboutJava/communityprocess/speclead/final-license.txt - this is clearly not an open source license. We also have a history of not adding the various Sun/Oracle binary or restricted use licenses due to the variability and lack of clear naming and versioning. 

If Oracle has cleaned up the latter issue, then we could consider, but that still leaves the first point as a stumbling block. In any case, I'd prefer to see Oracle engaged in any submission of their licenses, so then we get direct info and are not guessing.

**Comment by reversi-fun** [comment]
I See:
 * "license family name"(template includes variability) is rejected. 
 * {"Specification documents" + "Reference Implementation(binary)" (not source code)+(restricted use licenses)} is not "open source software". 

I have failed the "Specification license template for reference implementation" proposal.

**Comment by swinslow** [comment]
Discussed on 2019-06-13 legal team call, agreed to close.
