### ISSUE TITLE
Suggestion: Add info to spdx.org/licenses about using identifiers in source code

### ISSUE THREAD

**Issue by GeorgLink** [spdx/license-list-XML#848]
Hi, 

I keep looking up how to use SPDX license short identifiers in source code. I just need a reminder to use `SPDX-License-Identifier:`. When I first go to https://spdx.org/licenses but cannot directly answer how to use the identifiers.

A simple solution would be to include a statement like the following above the license list:

> To include licenses in source code, create a comment using the format: `SPDX-License-Identifier: [LICENSE STATEMENT]`

Additionally, a link to this presentation https://spdx.org/sites/cpstandard/files/pages/files/using_spdx_license_list_short_identifiers.pdf for more information would be a nice addition to the licenses page.

**Comment by zvr** [comment]
There is a whole appendix on the SPDX spec: "Using SPDX short identifiers in Source Files"
https://spdx.org/spdx-specification-21-web-version#h.twlc0ztnng3b

**Comment by GeorgLink** [comment]
Thanks @zvr,

Maybe the SPDX spec section is a better source to link to than the presentation.

The suggestion in this issue is to improve the usability of the license list for my use case. 
I frequently want to look up a license short identifier and how to use it.
I would find it helpful to have this information readily available in the license list or linked to from the license list. Right now, I'm missing an information scent from the license list.

**Comment by swinslow** [comment]
There's also a page at https://spdx.org/ids that specifically addresses how to use short-form IDs, in a way that might be more relevant and easier to get started with. @GeorgLink, does this help?

**Comment by GeorgLink** [comment]
The IDs page is awesome. How could I have missed it? Thanks @swinslow!

I continue to champion to include on (https://spdx.org/licenses/) information about how to use the IDs. Linking to the IDs page or the SPDX spec section would be great.

**Comment by swinslow** [comment]
Thanks @GeorgLink! Glad it is helpful! 

And thanks, this is helpful feedback. You're right, the "IDs" menu entry on the [main SPDX page](https://spdx.org) doesn't appear on the license list pages. We're discussing ways to perhaps rework the intro text on https://spdx.org/licenses/, but I'll look at adding a link to the IDs page from there in the meantime.

**Comment by swinslow** [comment]
Hi @GeorgLink, I've added an issue at https://github.com/spdx/LicenseListPublisher/issues/46 for this suggestion, since that's the repo that's used to generate the licenses list website pages. I'll close this issue here in license-list-XML. Thanks!

**Comment by GeorgLink** [comment]
Thanks @swinslow
