### ISSUE TITLE
MPL-2.0 missing standardLicenseHeader

### ISSUE THREAD

**Issue by Phrohdoh** [spdx/license-list-XML#849]
See https://github.com/amzn/askalono/issues/41

**Comment by swinslow** [comment]
Agreed, looks like the [XML for MPL-2.0](https://github.com/spdx/license-list-XML/blob/master/src/MPL-2.0.xml) doesn't currently have the standard license header from Exhibit A. I agree it should be added...

**Comment by bradleeedmondson** [comment]
I also agree the standard header information should be added. But I would point the submitter to SPDX Short Identifiers (and how they can apply a license to a source file in one, machine-readable line): https://spdx.org/ids

**Comment by jlovejoy** [comment]
added #860 for MPL-2.0

but I'm a bit confused as what the standard header should be for https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html

possibly: 
This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.

_If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0._

@tieguy might be able to answer this question :)

**Comment by swinslow** [comment]
Added with #860, thanks @jlovejoy.
