### ISSUE TITLE
New license request: VMD [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by ghost** [spdx/license-list-XML#850]
**1.** License Name: Visual Molecular Dynamics Software License Agreement
**2.** Short identifier: VMD
**3.** License Author or steward: VMD Team, Theoretical and Computational Biophysics Group, Beckman Institute, University of Illinois
**4.** Comments: I am not affiliated with VMD or the University of Illinois.
**5.** Standard License Header: 
**6.** URL: https://www.ks.uiuc.edu/Research/vmd/current/LICENSE.html
**7.** OSI Status: Not Submitted

**Comment by devurandom** [comment]
I notified the VMD team about this review here and hope they will chime in.

>     * The lead-in to the agreement mentions that the license grant is "Upon execution of this Agreement" -- I know you mentioned you aren't affiliated with VMD or University of Illinois so this probably isn't a question you can answer :) but I wonder if that means that U. of Illinois requires people to physically sign and "execute" the agreement? That would be significantly different from all OSS licenses I can think of.

Given how the download of VMD works, I expect this to mean "clicking an Accept button on the page that displays the license, before you are downloading the VMD source or binaries".

**Comment by urzds** [comment]
I notified the [VMD team](vmd@ks.uiuc.edu) about this review here and hope they will chime in.

> * The lead-in to the agreement mentions that the license grant is "Upon execution of this Agreement" -- I know you mentioned you aren't affiliated with VMD or University of Illinois so this probably isn't a question you can answer :) but I wonder if that means that U. of Illinois requires people to physically sign and "execute" the agreement? That would be significantly different from all OSS licenses I can think of.

Given how the download of VMD works, I expect this to mean "clicking an Accept button on the page that displays the license, before you are downloading the VMD source or binaries".

**Comment by jlovejoy** [comment]
based on @swinslow comments already, plus the restrictions on redistribution in section 2, I'd agree that this is clearly not open source. It's also licensor and project-specific meaning it can't even be re-used by others (not a huge factor, but we are trying to consider this as well and the open source community has certainly been getting away from entity-specific licenses. 

I don't think this is appropriate for the SPDX License List.

(completely unrelated, but I have to wonder how the university accepts contributions to this project, as they certainly can't come in under this license!)

**Comment by swinslow** [comment]
Given the above comments recommending against inclusion on the list, and seeing that the original submitter has apparently deleted their Github account, I'm going to go ahead and close this one.
