### ISSUE TITLE
New license request: SSPL-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by fallenpegasus** [spdx/license-list-XML#854]
**1.** License Name: Server Side Public License, version 1
**2.** Short identifier: SSPL-1.0
**3.** License Author or steward: MongoDB, Inc.
**4.** Comments: SSPL was recently submitted to and then withdrawn from OSI.

The SSPL is applied to the community edition of MongoDB Server.
**5.** Standard License Header: This program is free software: you can redistribute it and/or modify it under the terms of the Server Side Public License, version 1, as published by MongoDB, Inc.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the Server Side Public License for more details.

You should have received a copy of the Server Side Public License along with this program. If not, see <http://www.mongodb.com/licensing/server-side-public-license>.
**6.** URL: https://www.mongodb.com/licensing/server-side-public-license
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Hi @fallenpegasus, just wondering -- I recall seeing discussions of a version 2 of SSPL on the OSI mailing list. Has Mongo (or others) moved to using version 2, or is version 1 the "official" version at present?

**Comment by jlovejoy** [comment]
might be good to tag someone from MongoDb here or otherwise involved with license steward. 
@heathermeeker, perhaps?

**Comment by heathermeeker** [comment]
Afaik the code is still on version 1.

**Comment by swinslow** [comment]
Thanks @heathermeeker -- agreed, based on https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt it looks like they're using version 1.

I think this is appropriate to add to the list.

**Comment by jlovejoy** [comment]
@heathermeeker - is someone at MongoDB aware of this request? we are inclined to add it, but it would be nice to have involvement/awareness by someone from MongoDB (especially in case they have an opinion on name and id)

**Comment by heathermeeker** [comment]
I am checking with Mongo.

**Comment by heathermeeker** [comment]
Mongo is OK with this.

**Comment by jlovejoy** [comment]
#888 for this
