### ISSUE TITLE
Versioning consistency

### ISSUE THREAD

**Issue by don-vip** [spdx/license-list-XML#855]
Hello,
I consider the potential usage of SPDX license list in Maven Project Info Reports Plugin, as discussed in https://issues.apache.org/jira/browse/MPIR-382.
We found out that the versioning is inconsistent: sometimes the version numbers are defined as "v1.0" and sometimes as "1.0".
Could a single versioning scheme be used in the entire list?

**Comment by goneall** [comment]
@don-vip Just to clarify - is your issue is with the license ID's, license names or the license list version?

**Comment by don-vip** [comment]
License names ("full name"), as displayed at https://spdx.org/licenses/

**Comment by zvr** [comment]
Ah, but the full names are selected by the license authors or stewards...
I mean, CERN talks about "CERN OHL v1.2" https://www.ohwr.org/project/licenses/wikis/cern-ohl-v1.2 but Creative Commons call theirs "Creative Commons Attribution 4.0 International Public License" https://creativecommons.org/licenses/by/4.0/ (without a "v").

I would also appreciate consistency across all license authors, but it's not SPDX's task to rename licenses. In the couple of instances where we created "versions" I think we consistently used something like "(date)" (e.g. Unicode or W3C).

**Comment by don-vip** [comment]
Ah, I thought you also defined the licenses names, my bad. In that case, the correct name of Apache License 2.0 is "Apache License, Version 2.0".

**Comment by jlovejoy** [comment]
we actually did normalize on how this would be used in full names in the beginning which is defined here: https://spdx.org/spdx-license-list/license-list-overview#fields - mostly this was just a matter of tidying up.
I any case, if you are using the SPDX License List for purposes of identifying licenses, you should be using the short identifiers (not the full name). We define the short identifiers. Sounds like maybe you are confusing those two fields?
hope that helps!

**Comment by don-vip** [comment]
Thank you for the explanations. Maven POM unfortunately does not define a field for license identifier. I'll work on match per license URL and not per license name.

**Comment by jlovejoy** [comment]
@don-vip - you are aware of the matching guidelines? https://spdx.org/spdx-license-list/matching-guidelines and the various tools for license scanning?  Not sure what your methodology is (and this is probably not the best place to discuss), but I'd invite you to attend either the SPDX tech or legal team calls, as you might get some helpful input there (if you haven't already)

**Comment by slachiewicz** [comment]
Official name of that license is "Apache License, Version 2.0" not "Apache License 2.0"

https://www.apache.org/licenses/LICENSE-2.0

See license text "Licensed under the Apache License, Version 2.0 (the "License"); "
