### ISSUE TITLE
New license request: Open-BSV [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Danconnolly** [spdx/license-list-XML#864]
**1.** License Name: Open BSV License
**2.** Short identifier: Open-BSV
**3.** License Author or steward: Bitcoin Association
**4.** Comments: This is a modified form of the MIT license which grants full rights to use the software and source code on the Bitcoin SV blockchain, but restricts it from being used on any other blockchain. Innovation and creativity is blossoming on the Bitcoin SV blockchain with many solutions being designed and developed. The blockchain space is very competitive and several development teams have requested an MIT style license that enables them to share their work but prevents other blockchains from simply copying their work. The Bitcoin Association has responded to these requests by creating the Open BSV license.

An existing software solutions that uses this license is the Bitcoin SV Node implementation.
Web page: https://bitcoinsv.io/. 
Source code license: https://github.com/bitcoin-sv/bitcoin-sv/blob/master/LICENSE

Several other software products are expected to be using this license in the near future.
**5.** Standard License Header: 
**6.** URL: https://bitcoinassociation.net/open-bsv-license/
**7.** OSI Status: Not Submitted

**Comment by zvr** [comment]
Since the license restricts use, I don't think it's an Open Source license.

This does not fit with the SPDX license inclusion principles (https://spdx.org/spdx-license-list/license-list-overview). I suggest this should be rejected and this issue be closed.

**Comment by Danconnolly** [comment]
Many of the licenses in the current SPDX license list restrict use. For 
example, the GNU GPL v3.0 license places several restrictions on the use 
of the Software to which it is applied.

**Comment by jlovejoy** [comment]
The license inclusion guidelines reference use of the Open Source Definition (as well as the FSF 4 freedoms, in our updated doc which is a work-in-progress) as a guiding principle. Your license clearly has a field of use restriction. (GPLv3, on the other hand, is considered a free license by all organizations that make such determinations.

**Comment by Danconnolly** [comment]
The restriction we have does not fit into any of the categories that are listed in the annotated Open Source Definition. The closest might be 10. License Must Be Technology-Neutral, however the annotations state that "This provision is aimed specifically at licenses which require an explicit gesture of assent ...".

However, we are withdrawing this application. Thank you for your time.
