### ISSUE TITLE
Releasing conditions for 3.6

### ISSUE THREAD

**Issue by sskras** [spdx/license-list-XML#865]
I wonder when is it going to happen.  Has every open issue linked to the following milestone be closed for it?
https://github.com/spdx/license-list-XML/milestone/8

**Comment by jlovejoy** [comment]
we aim to do new releases on a quarterly tick, which would be end of June.  I thought was documented somewhere, but I can't seem to find that... something to add to our documentation review work.

as to whether we will close out every issue tagged for 3.6 - given the high volume of issues this cycle and that June is fast approaching, there is probably a good chance some will get pushed to 3.7. 

We need help!

**Comment by jlovejoy** [comment]
closing this, as I just added a PR to add this to CONTRIBUTING #870 - if there are other places we should also add this info, let me know!

**Comment by sskras** [comment]
Thanks!

**Comment by sskras** [comment]
It's out! Thanks once more.
