### ISSUE TITLE
New license request: SSH-short and SSH-OpenSSH [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by rohieb** [spdx/license-list-XML#867]
**1.** License Name: SSH License
**2.** Short identifier: SSH
**3.** License Author or steward: Tatu Ylönen
**4.** Comments: Used by the original SSH code. Still used today by derived software like OpenSSH or dropbear.
**5.** Standard License Header: 
**6.** URL: https://github.com/openssh/openssh-portable/blob/V_7_3_P1/LICENCE
**7.** OSI Status: Not Submitted

**Comment by rohieb** [comment]
The other supplemental URLs which I submitted in the form somehow didn't make it into the issue:
* https://salsa.debian.org/ssh-team/openssh/blob/master/debian/copyright
* https://enterprise.dejacode.com/licenses/public/openssh/

**Comment by jlovejoy** [comment]
this file has 8 licenses listed for different files/part of the code (and some of the parts seemed to contain multiple licenses themselves). some of the licenses listed are already on the SPDX License List - is this request to add just the license in part 1?

**Comment by rohieb** [comment]
Ah yes. The license text I submitted in the [form](http://13.57.134.254/app/submit_new_license/) also didn't make it here, I see :) It was meant to be only the first part from the links:

```
Copyright (c) 1995 Tatu Ylonen <ylo@cs.hut.fi>, Espoo, Finland
All rights reserved

As far as I am concerned, the code I have written for this software
can be used freely for any purpose.  Any derived versions of this
software must be clearly marked as such, and if the derived work is
incompatible with the protocol description in the RFC file, it must be
called by a name other than "ssh" or "Secure Shell".
```

**Comment by swinslow** [comment]
Hmmm... this is an interesting (and messy) one. 

If we'd be trying to capture Tatu's original license, then based on the text from https://github.com/openssh/openssh-portable/blob/V_7_3_P1/LICENCE, it reads to me like it should be:
- both parts prefixed by `*` (lines 10-17 and 20-25), and
- the two paragraphs after `the license continues` (lines 44-53), and
- the `NO WARRANTY` all-caps text (lines 58-76).

But that's just guessing, based on the modified original license text that openssh is using here.

@rohieb, do you know if there's anywhere still available online where we can find the original code (and license text) from Tatu Ylonen, where it hasn't been modified / edited as in the examples here?

**Comment by rohieb** [comment]
Huh, that's a good question. I've never encountered the original license, only the ones used by OpenSSH and dropbear, and the latter only uses the first paragraph (lines 10-17 in your link). So that sounds kind of like the BSD 1/2/3-clause situation to me… :)

**Comment by pombredanne** [comment]
@swinslow you would have to go far back last century to find anything but what is in the current openssh or dropbear licenses.
Here is the first occurrence in the CSV ;] for openssh, https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/usr.bin/ssh/LICENCE?rev=1.1&content-type=text/plain about 20 years ago.

Earlier would be 1.0: https://ftp.nluug.nl/security/ssh/old/ssh-1.0.0.tar.gz
and 1.2: https://ftp.nluug.nl/security/ssh/old/ssh-1.2.0.tar.gz
But these are likely different licenses... and the versions in between are even more funky (licensing-wise)
 
FWIW this has been tracked as the `tatu-ylonen` license in Scancode: https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tatu-ylonen.LICENSE

**Comment by swinslow** [comment]
Thanks @pombredanne. So it looks like Scancode uses `tatu-ylonen` to reference the first 5 lines of that "original" license.

Having now spent more time than I should have doing archaeology into this  =)  here are some thoughts:

Where this notice appears outside of OpenSSH, it appears to be just those same 5 lines. Examples:
- http://ftp.nchc.org.tw/NetBSD/NetBSD-current/src/crypto/external/bsd/openssh/dist/pathnames.h
- http://web.mit.edu/kolya/.f/root/athena.mit.edu/sipb.mit.edu/project/openssh/OldFiles/src/openssh-2.9.9p2/ssh-add.1 (also includes BSD-2-Clause below it)
- https://joinup.ec.europa.eu/svn/lesoll/trunk/italc/lib/src/dsa_key.cpp (scroll down - GPL and other notices at top)

All of which suggests that this short version functioned as a standalone license for at least some code.

However, [this](https://web.archive.org/web/20070909182914/https://wwwcip.informatik.uni-erlangen.de/~msfriedl/LIC/ssh-1.2.12/COPYING) appears to be a copy of the COPYING file from 1.2.12, which [OpenSSH describes](https://www.openssh.com/history.html) as the release they worked from.

And it appears that OpenSSH annotated that version into the text that makes up item 1 in https://github.com/openssh/openssh-portable/blob/V_7_3_P1/LICENCE. It's this annotated version that appears to be widely used, given OpenSSH's use in the wild.

So I'd suggest we add two entries to the SPDX License List:
1) The first, for the "short" 5-line version reflected in https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tatu-ylonen.LICENSE
2) The second, for the text that currently makes up the entirety of item 1 from https://github.com/openssh/openssh-portable/blob/V_7_3_P1/LICENCE -- including the "annotations" there

Does that all make sense? If so, we'll just want to sort out names and identifiers for these two versions that would hopefully help to minimize the confusion...

**Comment by rohieb** [comment]
Thank you for adding more research to this!

> Where this notice appears outside of OpenSSH, it appears to be just those same 5 lines. Examples:
> […]
> All of which suggests that this short version functioned as a standalone license for at least some code.

Agreed.

> However, [this](https://web.archive.org/web/20070909182914/https://wwwcip.informatik.uni-erlangen.de/~msfriedl/LIC/ssh-1.2.12/COPYING) appears to be a copy of the COPYING file from 1.2.12, which [OpenSSH describes](https://www.openssh.com/history.html) as the release they worked from.
> 
> And it appears that OpenSSH annotated that version into the text that makes up item 1 in https://github.com/openssh/openssh-portable/blob/V_7_3_P1/LICENCE. It's this annotated version that appears to be widely used, given OpenSSH's use in the wild.

The very first Git commit of OpenSSH also has a file [https://github.com/openssh/openssh-portable/blob/d4a8b7e34dd619a4debf9a206c81db26d1402ea6/COPYING.Ylonen COPYING.Ylonen], which also includes the original SSH license with the warranty disclaimer at the end, except for the parts about the code base that was stripped out. Otherwise the text is the same as in your linked version. So I can follow your argument here.

> So I'd suggest we add two entries to the SPDX License List:

Agreed.

> 1. The first, for the "short" 5-line version reflected in https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/tatu-ylonen.LICENSE

I did not find any other licenses related to Tatu Ylonen until now, but I think this text is specific to SSH, so I would include it in the identifiers. We could use `Ylonen-SSH` and `Tatu Ylonen SSH License` for that one.

> 2. The second, for the text that currently makes up the entirety of item 1 from https://github.com/openssh/openssh-portable/blob/V_7_3_P1/LICENCE -- including the "annotations" there

For version 2, I would suggest the identifiers `Ylonen-OpenSSH` and `Tatu Ylonen SSH License (annotated version used by OpenSSH)`.

**Comment by swinslow** [comment]
Thanks @rohieb. All sounds good to me, except I'm going to suggest `SSH-short` for the first one and `SSH-OpenSSH` for the second, to avoid using individuals' names in the license identifiers themselves.

These two formats were discussed briefly during the prior legal team call, and I'll raise them again on today's call to see if we can finalize for the upcoming 3.7 release.

**Comment by swinslow** [comment]
Discussed on 2019-10-03 call, agreed to add these two entries and use the identifiers `SSH-short` and `SSH-OpenSSH`

**Comment by jlovejoy** [comment]
added to license list via #936
