### ISSUE TITLE
How to test a single license

### ISSUE THREAD

**Issue by kemitchell** [spdx/license-list-XML#880]
@goneall, is there an easy way to check matching on a single license at a time? Perhaps we could write that in as a Make target.

I haven't done `time make` on my machine, but the full check takes a few minutes at least. I see Travis CI is similar.

**Comment by goneall** [comment]
To check against the existing listed licenses, you can use http://13.57.134.254/app/check_license/

If this is to help with the development of a new license XML, the only tool to do the compare compares all licenses which does take a substantial amount of time.

The only matching algorithm implementation I am aware of is written in Java, so any solution would require a JVM to execute.

Writing a Java command line to compare a single license would be the least effort approach.

I also wonder if we could add a feature to the online tools to allow you to upload text and a license XML and do a single compare or integrate into the new license submittal workflow being worked on as part of GSoC.

**Comment by goneall** [comment]
As an update, looked into changing the tools which build the license list data from this repo and I ran into a problem where we still want to check all other licenses in the repo for duplicates.

I did, however, add an issue to allow for a single file to be generated and tested: https://github.com/spdx/LicenseListPublisher/issues/50

I hope to get this implemented before the next release of the license list (along with several other improvements)

**Comment by kemitchell** [comment]
@goneall this would help us debugging new XML for new licenses substantially.
