### ISSUE TITLE
New license request: OGL-Canada-2.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by burritojustice** [spdx/license-list-XML#882]
**1.** License Name: Open Government Licence - Canada
**2.** Short identifier: OGL-Canada-2.0
**3.** License Author or steward: Government of Canada
**4.** Comments: This license is used by various Canadian government agencies when publishing open data sets. 

While there is no specific reference to the short identifier on the license page, I do see references to OGL-C in Wikimedia Canada and elsewhere online. https://ca.wikimedia.org/wiki/Compatibility_of_the_Open_Government_Licence_-_Canada_with_Wikimedia_projects
**5.** Standard License Header: 
**6.** URL: https://open.canada.ca/en/open-government-licence-canada
**7.** OSI Status: Not Submitted

**Comment by burritojustice** [comment]
sorry, I think the license text got dropped when I submitted the form:

Open Government Licence - Canada
You are encouraged to use the Information that is available under this licence with only a few conditions.

Using Information under this licence
Use of any Information indicates your acceptance of the terms below.
The Information Provider grants you a worldwide, royalty-free, perpetual, non-exclusive licence to use the Information, including for commercial purposes, subject to the terms below.
You are free to:
Copy, modify, publish, translate, adapt, distribute or otherwise use the Information in any medium, mode or format for any lawful purpose.
You must, where you do any of the above:
Acknowledge the source of the Information by including any attribution statement specified by the Information Provider(s) and, where possible, provide a link to this licence.
If the Information Provider does not provide a specific attribution statement, or if you are using Information from several information providers and multiple attributions are not practical for your product or application, you must use the following attribution statement:
Contains information licensed under the Open Government Licence – Canada.

The terms of this licence are important, and if you fail to comply with any of them, the rights granted to you under this licence, or any similar licence granted by the Information Provider, will end automatically.

Exemptions
This licence does not grant you any right to use:

Personal Information;
third party rights the Information Provider is not authorized to license;
the names, crests, logos, or other official symbols of the Information Provider; and
Information subject to other intellectual property rights, including patents, trade-marks and official marks.
Non-endorsement
This licence does not grant you any right to use the Information in a way that suggests any official status or that the Information Provider endorses you or your use of the Information.

No Warranty
The Information is licensed “as is”, and the Information Provider excludes all representations, warranties, obligations, and liabilities, whether express or implied, to the maximum extent permitted by law.

The Information Provider is not liable for any errors or omissions in the Information, and will not under any circumstances be liable for any direct, indirect, special, incidental, consequential, or other loss, injury or damage caused by its use or otherwise arising in connection with this licence or the Information, even if specifically advised of the possibility of such loss, injury or damage.

Governing Law
This licence is governed by the laws of the province of Ontario and the applicable laws of Canada.

Legal proceedings related to this licence may only be brought in the courts of Ontario or the Federal Court of Canada.

Definitions
In this licence, the terms below have the following meanings:

"Information"
means information resources protected by copyright or other information that is offered for use under the terms of this licence.
"Information Provider"
means Her Majesty the Queen in right of Canada.
“Personal Information”
means “personal information” as defined in section 3 of the Privacy Act, R.S.C. 1985, c. P-21.
"You"
means the natural or legal person, or body of persons corporate or incorporate, acquiring rights under this licence.
Versioning
This is version 2.0 of the Open Government Licence – Canada. The Information Provider may make changes to the terms of this licence from time to time and issue a new version of the licence. Your use of the Information will be governed by the terms of the licence in force as of the date you accessed the information.

Open Government Licence Consultation Report

Date modified: 2017-12-20

**Comment by mlinksva** [comment]
I'd suggest short id of `OGL-Canada-2.0` or `OGL-CA-2.0`. C alone isn't very meaningful, and it is version 2.0. 😄

**Comment by burritojustice** [comment]
sorry, forgot the `2.0`!

And agree re `OGL-C-2.0` not being meaningful. Finding more references to `OGL-Canada-2.0`:

https://enterprise.dejacode.com/licenses/?q=open+government
https://github.com/okfn/licenses/blob/master/licenses/OGL-Canada-2.0.json

https://enterprise.dejacode.com/licenses/?q=open+government

**Comment by MarkAtwood** [comment]
This license is only usable by "Her Majesty the Queen in right of Canada ", e.g.  the government of Canada.  So unless this the license text is templatized, this is a single user license.

I suggest a scoped license identifier of LicenseRef-.gc.ca-OGL-2.0

**Comment by swinslow** [comment]
Interesting... we did add the OGL-UK licenses to the license list, which appear related to this one but are clearly substantively different. But the OGL-UK-* set are are designed to be used by anyone as the Licensor, and as @MarkAtwood noted, OGL-Canada-2.0 is only usable as a license from the specific named licensor.

@burritojustice, the dejacode and okfn links you mentioned appear to be from tools talking about the license itself. Do you have examples of data sets or other content that have been released under this license (not necessarily using the identifier, but the license itself)?

If this is used for a substantial amount of content released in the wild, I could be in favor of adding it to the list, despite it being limited to a single licensor. From a quick read of the terms, the single named licensor is the only qualm I have about it meeting the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md).

**Comment by pombredanne** [comment]
@mlinksva you wrote:

> I'd suggest short id of OGL-Canada-2.0 or OGL-CA-2.0. C alone isn't very meaningful, and it is version 2.0.

... and I second this. FWIW I have opted for a slightly different key in ScanCode:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/can-ogl-2.0-en.yml
to group together each of the provincial or city variants with the same prefix:
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/can-ogl-alberta-2.1.yml
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/can-ogl-toronto-1.0.yml
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/can-ogl-toronto-1.0.yml
https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/can-ogl-alberta-2.1.yml

**Comment by burritojustice** [comment]
@swinslow it is widely used -- this is the primary license structure for open data in Canada.

There are at least 10,000 datasets here.

https://open.canada.ca/en/search/inventory

For a more specific example, it's used by Natural Resources Canada (think the USGS)
https://www.nrcan.gc.ca/earth-sciences/geography/topographic-information/licence/17285

As @pombredanne notes, there are many provincial and city variants.

https://vancouver.ca/your-government/open-data-catalogue.aspx

Very similar wording in the Statistics Canada data licensing 

https://www.statcan.gc.ca/eng/reference/licence
https://www.statcan.gc.ca/eng/reference/licence-faq

**Comment by swinslow** [comment]
Given the wide usage that @burritojustice noted in the first link from the preceding comment, I believe that this should be added to the list. 

(I haven't compared it to the provincial / city / Statistics Canada variants that are noted separately -- if those are substantively different licenses under the [SPDX matching guidelines](https://spdx.org/spdx-license-list/matching-guidelines), then those wouldn't fall under this entry.)

I'll raise this on the legal team call today for others' input, but my view is that it is appropriate to add.

**Comment by jlovejoy** [comment]
Ok to add, and we can always consider in the future to add markup text if and in order to accommodate different entities using the same license

**Comment by jlovejoy** [comment]
added PR at #944 (but not sure if I got short identifier as decided?)
