### ISSUE TITLE
Proposal: Add http URL consideration to matching guidelines

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#892]
Propose adding the following to the matching guidelines:

13. URL references

12.1 Purpose:  To avoid a license mismatch merely because a different in protocol for a URL reference (e.g. ```http://``` vs. ```https://```.

12.1.1 Guideline:  The two URL protocol prefixes ```http://``` and ```https://``` will be considered equivalent and interchangeable for matching purposes.

**Comment by zvr** [comment]
+1

But let's use the official nomenclature:

> `http` and `https` URI schemes shall be considered equivalent for matching purposes.

(or something like that)

**Comment by goneall** [comment]
Closing this as a duplicate of #633  This issue has been updated with the proposal text.
