### ISSUE TITLE
Add the attribute spacing to the alt element

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#897]
Similar spacing issues can occur with the `<alt` elements as what happened to the `<optional>` elements (see PR #896 for reference).

**Comment by jlovejoy** [comment]
what is the status of this? @goneall @zvr

**Comment by zvr** [comment]
Unless there's an urgent need, I was planning to have it subsumed in #890...

**Comment by swinslow** [comment]
Given @zvr's comment that this will be subsumed in #890, I'm going to copy it over to that issue and then close this separate one.
