### ISSUE TITLE
Generate documentation for the XML schema or add doc in DOCS folder

### ISSUE THREAD

**Issue by goneall** [spdx/license-list-XML#898]
Although the XML schema documents many of the fields, it is currently hard to read and follow.  We have some documentation on the [Wiki](https://wiki.spdx.org/view/Legal_Team/Templatizing), it can be a bit hard to find.

**Comment by jlovejoy** [comment]
is this different than #890 ?

**Comment by swinslow** [comment]
Hi @goneall @zvr, is there anything for this issue that will be implemented for 3.8?

If not, should we change it to "later release" or just close the issue?

**Comment by jlovejoy** [comment]
consolidating into #1369
