### ISSUE TITLE
New license request: Sun-RPC [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by rohieb** [spdx/license-list-XML#906]
**1.** License Name: Sun RPC License
**2.** Short identifier: Sun-RPC
**3.** License Author or steward: 
**4.** Comments: Found in portmap, which was apparently forked from an old version of the Sun RPC code, which has since been relicensed to BSD-3-Clause (see https://github.com/Distrotech/rpcbind/blob/master/src/pmap_svc.c).
The text is similar to the Rdisc license, but includes the additional constraint: "Users may copy or modify Sun RPC without charge, but are not authorized to license or distribute it to anyone else except as part of a product or program developed by the user or with the express written consent of Sun Microsystems, Inc."
**5.** Standard License Header: 
**6.** URL: https://fossies.org/linux/portmap/portmap.c
**7.** OSI Status: Not Submitted

**Comment by rohieb** [comment]
Hmm. The online tool didn't put in the license text, and the [second source](https://fossies.org/linux/portmap/from_local.c)… Here it is:

```
Sun RPC is a product of Sun Microsystems, Inc. and is provided for
unrestricted use provided that this legend is included on all tape
media and as a part of the software program in whole or part.  Users
may copy or modify Sun RPC without charge, but are not authorized
to license or distribute it to anyone else except as part of a product or
program developed by the user or with the express written consent of
Sun Microsystems, Inc.

SUN RPC IS PROVIDED AS IS WITH NO WARRANTIES OF ANY KIND INCLUDING THE
WARRANTIES OF DESIGN, MERCHANTIBILITY AND FITNESS FOR A PARTICULAR
PURPOSE, OR ARISING FROM A COURSE OF DEALING, USAGE OR TRADE PRACTICE.

Sun RPC is provided with no support and without any obligation on the
part of Sun Microsystems, Inc. to assist in its use, correction,
modification or enhancement.

SUN MICROSYSTEMS, INC. SHALL HAVE NO LIABILITY WITH RESPECT TO THE
INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY PATENTS BY SUN RPC
OR ANY PART THEREOF.

In no event will Sun Microsystems, Inc. be liable for any lost revenue
or profits or other special, indirect and consequential damages, even if
Sun has been advised of the possibility of such damages.

Sun Microsystems, Inc.
2550 Garcia Avenue
Mountain View, California  94043
```

**Comment by jlovejoy** [comment]
the license text is in the online tool. I know, it's a bit confusing in that way, but it is accessible. thanks!

**Comment by swinslow** [comment]
Thanks @rohieb. Given SPDX's [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md), the additional constraint you noted in your comments gives me pause. A restriction on redistribution leads me to think that this likely doesn't meet the bar for inclusion on the SPDX license list.

That said, anyone can still reference this license (and any other license not on the license list) in an SPDX document using a [user-defined `LicenseRef-` tag](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60), and there is currently an [open proposal](https://github.com/spdx/spdx-spec/issues/113) discussing use of namespaces to enable `LicenseRef-` tags separately from SPDX documents.

**Comment by pombredanne** [comment]
FWIW, this has been tracked in ScanCode as the sun-rpc license for as long as ScanCode has existed https://github.com/nexB/scancode-toolkit/blob/develop/src/licensedcode/data/licenses/sun-rpc.LICENSE

**Comment by rohieb** [comment]
On Sat, Jul 27, 2019 at 11:56:58AM -0700, Steve Winslow wrote:
> Thanks @rohieb. Given SPDX's [license inclusion principles](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md), the additional constraint you noted in your comments gives me pause. A restriction on redistribution leads me to think that this likely doesn't meet the bar for inclusion on the SPDX license list.

Right, that seems resonable to me, so I'll close this issue.

 - Roland
