### ISSUE TITLE
mark-up for hyphens?

### ISSUE THREAD

**Issue by jlovejoy** [spdx/license-list-XML#917]
SPDX License List Matching Guidelines 5.1.2 says Any hyphen, dash, en dash, em dash, or other variation should be considered equivalent.

But sometimes we have hyphens in some words, like non-commercial or noncommercial - which is accommodated in guideline 8.1.1 with list of "equivalent" words.

Should we add non-infringement / noninfringment  (or any others) to 8.1.1 equivalent word list or accommodate hyphened words with some kind of markup?

@tsteenbe

**Comment by goneall** [comment]
Do the matching guidelines imply that hyphens are equivalent to no hyphen?  If not, then we should probably add the equivalent words.  BTW - I'll need to update the tools with any new equiv. words.

**Comment by jlovejoy** [comment]
@goneall correct. I think we should add the two hyphen/non hyphen variants mentioned above to our equivalency list.

We are also in the process of moving the matching guidelines to the spec, so it will at least be easier to see changes then! (And we'll rev the matching guidelines versioning, as we gave it its own version number some time ago)

**Comment by goneall** [comment]
It looks like the tools already treats the following as equivalent:
```
		"copyright-owner", "copyright-holder"
		"sublicense", "sub-license"
		"non-infringement", "noninfringement"
```

I added a pull request to make the different dash varieties equivalent.

**Comment by goneall** [comment]
So ... I don't think we need to add any markup as long as tools implement the equivalent words and normalize hyphens per license matching guidelines.

**Comment by jlovejoy** [comment]
great. so, can close this @goneall ?

**Comment by goneall** [comment]
@jlovejoy yes - I'll go ahead and close
