### ISSUE TITLE
Python-2.0 license should not include all the history of Python licensing

### ISSUE THREAD

**Issue by pombredanne** [spdx/license-list-XML#919]
The Python-2.0 license is used in Python proper and in other projects. Yet the Python-2.0 text @ SPDX is really the whole Python.org license notice and history, making this is license text useless outside of the Python.org licensing.

**Comment by swinslow** [comment]
@pombredanne I'm in favor of this. Looking at https://github.com/spdx/license-list-XML/blob/master/src/Python-2.0.xml, is your suggestion that `Python-2.0` should be just lines 14-65? With the remainder punted out into separate license entries (possibly `Python-1.X`, `Python-1.Y` variants)?

I do note that `CNRI-Python` already exists for one part of the older version "history" chunks. I haven't run a redline against the center part of what's currently in `Python-2.0`, but flipping between tabs it sure does look the same...

**Comment by swinslow** [comment]
That being said, a couple of downsides to making this change -- 

* the OSI definition of `Python-2.0` includes the full "history" text -- see https://opensource.org/licenses/Python-2.0.  (Perhaps, if we change, it should only be concurrent with OSI making a change so that they stay in sync?)

* For Python itself (the language implementation), is it under just the Python-2.0 portion of this? Or does the standard Python distribution contain code that is still under the earlier licenses? If we were to break them out into separate entries, it would be a shame if that meant that the license for Python became something like `Python-2.0 AND Python-1.6b1 AND Python-1.2 AND...`

**Comment by pombredanne** [comment]
@swinslow You are right: changing the current `Python-2.0` text is likely a bad idea. Yet we need a way to handle projects that use strictly the text from https://github.com/spdx/license-list-XML/blob/2a148109f590f29ec635fdbfa920b7d426d6df61/src/Python-2.0.xml#L10 to https://github.com/spdx/license-list-XML/blob/2a148109f590f29ec635fdbfa920b7d426d6df61/src/Python-2.0.xml#L65 and are not Python (and therefore do not need to cargo the history of Python licensing)

One possibility, we could have  new id --e.g. `PSF-2.0`-- that contains only this text and leave the Python one as is. As you pointed out it is not the first time that there is an id text contained in another text. This would offer the maximum flexibility with the minimum changes

**Comment by jlovejoy** [comment]
@pombredanne - are you suggesting that we have a new entry that is only the part lines 10-65? What is the justification of this - that is, are you finding this alone in the wild and if so, can you point to an example? 
thanks!

**Comment by jlovejoy** [comment]
@pombredanne - can you clarify the resulting idea here?

btw, I should have mentioned that in long ago, ancient history SPDX license list, one of our early contributors did a TON of research on the Python license "stack", as we referred to it, in terms of trying to understand what was used for which version of Python. There was a chart I believe, which was somewhat dizzying. If I can find that, it might be a good thing to store on the wiki for posterity.

**Comment by rohieb** [comment]
> @pombredanne - are you suggesting that we have a new entry that is only the part lines 10-65? What is the justification of this - that is, are you finding this alone in the wild and if so, can you point to an example?

I'm finding this part of the Python-2.0 license text alone in the wild, e.g. in [scipy-sphinx-theme](https://github.com/scipy/scipy-sphinx-theme/blob/d990ab9134199f6496b9ac8567f10791f04a720a/LICENSE.txt#L39), so I would welcome this part as a single license.

**Comment by pombredanne** [comment]
@rohieb Thanks
@jlovejoy sorry for the late reply: the point is that non-PSF code that is under the Python license will not have the historical baggage that the PSF Python license has because these other historical licenses just do not apply.

**Comment by rohieb** [comment]
@jlovejoy wrote:
> btw, I should have mentioned that in long ago, ancient history SPDX license list, one of our early contributors did a TON of research on the Python license "stack", as we referred to it, in terms of trying to understand what was used for which version of Python. There was a chart I believe, which was somewhat dizzying. If I can find that, it might be a good thing to store on the wiki for posterity.

The chart is even part of Python's LICENSE file :-) https://github.com/python/cpython/blob/master/LICENSE#L27

**Comment by rohieb** [comment]
@pombredanne wrote:
> Yet we need a way to handle projects that use strictly the text from
> 
> https://github.com/spdx/license-list-XML/blob/2a148109f590f29ec635fdbfa920b7d426d6df61/src/Python-2.0.xml#L10
> to
> 
> https://github.com/spdx/license-list-XML/blob/2a148109f590f29ec635fdbfa920b7d426d6df61/src/Python-2.0.xml#L65
> and are not Python (and therefore do not need to cargo the history of Python licensing)
> 
> One possibility, we could have new id --e.g. `PSF-2.0`-- that contains only this text and leave the Python one as is.

I've done exactly that in PR #952 now, would be great if you could have a look whether that's what you want.

**Comment by swinslow** [comment]
I'm in favor of the approach @rohieb implemented in #952, by adding a new "PSF-2.0" entry that contains just the specific license text without the historical text. (I'll have a couple of minor comments on #952 itself)

@pombredanne @jlovejoy, does that work for you also? Any concerns or are you good with the proposal in #952?

**Comment by bradleeedmondson** [comment]
The approach in #952 makes sense to me.

**Comment by rohieb** [comment]
@swinslow:
> (I'll have a couple of minor comments on #952 itself)

Do you still have? I don't see them on #952…

**Comment by swinslow** [comment]
Discussed on 2020-01-30 legal team call, OK to merge #952, will want to add listVersionAdded tag but can do that post-merge.

**Comment by rohieb** [comment]
@swinslow thanks for the cleanup! :)
