### ISSUE TITLE
New license request: etalab-2.0

### ISSUE THREAD

**Issue by bzg** [spdx/license-list-XML#923]
**1.** License Name: Open License 2.0
**2.** Short identifier: ol-2.0
**3.** License Author or steward: Etalab (French mission for open data : https://www.etalab.gouv.fr)
**4.** Comments: The license has not been submitted to OSI because it is mainly targetting open data, not open source.

If modications are required, please let me know.

Thanks!
**5.** Standard License Header: 
**6.** URL: https://www.etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Thank you @bzg for submitting this! I see the plain text of the submitted license is in the request entry at http://13.57.134.254/app/license_requests/50/

I (and others) will review the license text more closely, but a couple of initial questions come to mind:

* Is "Open License 2.0" the license name? If you're affiliated with the license steward, it would be ideal if a more specific name could be used to refer to the license. "Open License" is pretty general and might confuse people (as pretty much every license on the License List is an "open license"!)

* Do you know of examples where this license is being used in the wild? One of the factors that the team looks at, when evaluating whether to add a license, is whether it is currently in use for multiple projects. See [here](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) for more details about the team's license inclusion principles at present.

**Comment by swinslow** [comment]
Sorry, one additional question:

* Is this English version the "official" version of the license text? Or is there a French version that is the canonical license text?

**Comment by bzg** [comment]
Hi Steve,

thanks for the prompt feedback!

Steve Winslow <notifications@github.com> writes:

> I (and others) will review the license text more closely, but a
> couple of initial questions come to mind:
>
>     Is "Open License 2.0" the license name? If you're affiliated with
>     the license steward, it would be ideal if a more specific name
>     could be used to refer to the license. "Open License" is pretty
>     general and might confuse people (as pretty much every license on
>     the License List is an "open license"!)

Yes, "open license 2.0" is the real name.  I know it is a bad name.
It is sometimes called by reusers the "Etalab license 2.0", because
Etalab is the name of the mission who publishes it.

I will ask my colleagues what they think about using "Etalab license"
as the name for a SPDX identifier, with etl-2.0 for short.  Or maybe
the "Etalab Open License" and eol-2.0.  (Let me know if you think one
is clearly better.)

>     Do you know of examples where this license is being used in the
>     wild? One of the factors that the team looks at, when evaluating
>     whether to add a license, is whether it is currently in use for
>     multiple projects. See here for more details about the team's
>     license inclusion principles at present.

The license is used by the whole open data ecosystem in France.

https://www.data.gouv.fr/fr/datasets/referentiel-de-lorganisation-administrative-de-letat/
https://www.data.gouv.fr/fr/datasets/boamp/

There are more than +2k organizations (from small cities to big
ministries) using it right now.

It is also used by french administrations to publish documents. See
for example the french open source policy for the public sector here:

https://github.com/DISIC/politique-de-contribution-open-source/blob/master/README.en.md

Let me know if you need more examples.

Best,

-- 
 Bastien

**Comment by bzg** [comment]
Hi Steve,

Steve Winslow <notifications@github.com> writes:

> Sorry, one additional question:
>
>     Is this English version the "official" version of the license
>     text? Or is there a French version that is the canonical license
>     text?

The French version is the canonical license text, you can find it here:
https://github.com/DISIC/politique-de-contribution-open-source/blob/master/LICENSE.pdf

The english version is provided "as is", to share documents more widely.

Best,

-- 
 Bastien

**Comment by camillem** [comment]
Hi Bastien, all, 

Regarding the name,  I think that "Etalab Open License 2.0" would be indeed much better than just "Open License". As for the ID, I think "Etalab-2.0" could be  a good fit, as it's more immediately relatable to the steward of the license than just "EOL".
Best, 
Camille

**Comment by bzg** [comment]
Hi Camille, thanks for your feedback.  I will suggest "Etalab Open License 2.0" and etalab-2.0 internally and get back to you ASAP.

**Comment by bzg** [comment]
I just validated this with our legal team: we can proceed with "Etalab Open License 2.0" and "etalab-2.0". Thanks!

**Comment by swinslow** [comment]
Thank you @bzg! I've updated the title of this issue to reflect the change. I'll follow up in a separate comment below with my thoughts on whether the license should be added to the list.

Updated submission request details will be:

1. License Name: Etalab Open License 2.0
2. Short identifier: etalab-2.0
3. License Author or steward: Etalab (French mission for open data : https://www.etalab.gouv.fr)
4. Comments: The license has not been submitted to OSI because it is mainly targetting open data, not open source.

If modications are required, please let me know.

Thanks!
5. Standard License Header:
6. URL: https://www.etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf
7. OSI Status: Not Submitted

**Comment by swinslow** [comment]
I think this license is appropriate to add to the license list. I believe it meets the current license inclusion principles, and per @bzg's comments above it is evidently widely used by the French government.

My main question is for others on the SPDX team: according to the comments above, it appears that the French version is the "canonical" license text, and the English version is provided for convenience:
* French: https://github.com/DISIC/politique-de-contribution-open-source/blob/master/LICENSE.pdf
* English: https://www.etalab.gouv.fr/wp-content/uploads/2018/11/open-licence.pdf

Looking to what SPDX has done in the past:
* For [CECILL-1.0](https://spdx.org/licenses/CECILL-1.0.html), only the French version was authoritative (see [here](https://cecill.info/faq.en.html#francais-anglais)). On the SPDX list we used the French text, and added a note with the URL to the English translation.
* For later CeCILL versions such as [CECILL-2.1](https://spdx.org/licenses/CECILL-2.1.html), the license steward says that they are deemed equally valid and interchangeable. On the SPDX list we used the English text, and added a note with the URL to the French version.

Given all of that, I'm inclined to say that here for etalab-2.0, we should follow the same pattern as CECILL-1.0: add the French version, with a note providing the link to the English translation.

@jlovejoy @bradleeedmondson or others -- would you agree?

**Comment by bzg** [comment]
> Given all of that, I'm inclined to say that here for etalab-2.0, we should follow the same pattern as CECILL-1.0: add the French version, with a note providing the link to the English translation.

FWIW, agreed. Thanks!

**Comment by bzg** [comment]
Hi all, is there anything I can do to help moving forward with this? Or any hint on how long the validation process could be? I don't want to rush anyone, this is just to let you know that this issue is high on my list.

Thanks!

**Comment by swinslow** [comment]
Based on the prior legal team call, I believe consensus was to approve this license using the French text, and in notes to include the link to the English translation. I will ask the legal team to confirm during today's call, and hopefully we can get this in for the upcoming 3.7 release of the license list.

**Comment by bzg** [comment]
Great, thanks a lot.

**Comment by jlovejoy** [comment]
added license with #935

**Comment by bzg** [comment]
Thanks again for handling this. Our of curiosity, when can I expect to see the licence listed on https://spdx.org/licenses ?  My next move is to update the SPDX identifier of the license on [Etalab's page listing approved licenses](https://spdx.org/licenses/). Thanks!

**Comment by swinslow** [comment]
Hi @bzg, I am expecting to push the next update of the license list (3.7) to https://spdx.org/licenses within the next couple of days.

**Comment by bzg** [comment]
Great, thanks a lot!

**Comment by swinslow** [comment]
Hi @bzg, as a heads-up, the 3.7 license list release is now live at https://spdx.org/licenses. So you should be all set to use this identifier now.

**Comment by bzg** [comment]
Hi @swinslow, that's great news, thanks a lot for the heads-up!
