### ISSUE TITLE
Fix spelling of "Licence" in title of CERN-OHL-1.1

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#932]
(cc @jlovejoy @goneall)

@sschuberth [noted](https://github.com/spdx/license-list-XML/pull/930) that on the SPDX license list, there is a difference in the titles for CERN-OHL-1.1 and CERN-OHL-1.2 for how "Licence" is spelled:
- [CERN-OHL-1.1](https://spdx.org/licenses/CERN-OHL-1.1.html): CERN Open Hardware **License** v1.1
- [CERN-OHL-1.2](https://spdx.org/licenses/CERN-OHL-1.2.html): CERN Open Hardware **Licence** v1.2

PR #930 suggested changing title of 1.2 to "License" with an "s", to align on American English spelling.

However, it looks to me like the license steward / author uses "Licence" with a "c" in both. So I'm guessing that spelling it with an "s" in 1.1 was accidental and should be fixed.

This should be an easy fix for newer participants in the license list who would like to submit a PR to fix it  :)

**Comment by jlovejoy** [comment]
we should use what the license steward used. We do already have license/licence on the matching guidelines word equivalent list :)

**Comment by jlovejoy** [comment]
#933
