### ISSUE TITLE
GPL compatibility information

### ISSUE THREAD

**Issue by lassik** [spdx/license-list-XML#934]
Would it be possible to add a machine-parseable GPL compatibilty field based on the information at https://www.gnu.org/licenses/license-list.html?

It could be something like:

```
"isGplCompatible": "always"
"isGplCompatible": "never"
"isGplCompatible": "it's complicated"
```

The last choice is for licenses that require a relicensing or dual-licensing arrangement or put put some restrictions on the other license is aplpied.

**Comment by mlinksva** [comment]
FWIW the info published in the FSF license list is available in https://wking.github.io/fsf-api/licenses-full.json (see "compatible" tags) put together by @wking in https://github.com/wking/fsf-api

**Comment by goneall** [comment]
@mlinksva Thanks for pointing this out.

The data being available definitely helps with the implementation.

In looking at the tags, it looks like we can easily get the stated GPL compatibility, but there doesn't seem to be any tags for incompatible.

**Comment by goneall** [comment]
@lassik I would propose we use Boolean fields rather than text to reduce the effort in tooling to parse the fields.

We could use the similar field definitions @wking used in the tags:
- isGpl2Compatible - if true, the license is declared as compatible with the GPL version 2 by FSF, if false the license is declared as not compatible with the GPL version 2 by FSF, if no value is present no (machine parseable) statement has been by FSF
- isGpl3Compatible - if true, the license is declared as compatible with the GPL version 3 by FSF, if false the license is declared as not compatible with the GPL version 3 by FSF, if no value is present no (machine parseable) statement has been by FSF

Note that we don't have the data yet to populate the stated incompatible license information.

**Comment by goneall** [comment]
@swinslow @jlovejoy Any legal team concerns with adding this to the license list data?  If we add this to the data, should we add this to the license html rendered on spdx.org/licenses?

**Comment by swinslow** [comment]
I would not be in favor of adding these details to the list. I think that deciding whether one license is compatible with another gets too deep into interpreting the licenses, where SPDX’s goals have been focused on identifying the license text but not interpreting it.

**Comment by wking** [comment]
I'd still rather just give the GNU identifier for each license and then link to them where they can expose whatever complicated opinions they want without SPSX having to do more than text matching.

**Comment by lassik** [comment]
The point of the `always`, `never` and `it's complicated` options I proposed was that in some cases the compatibility is clear ("always" option; e.g. most permissive licenses). In other cases the FSF says that the license is fundamentally incompatible with the GPL ("never" option). [Apache License, Version 2.0](https://www.gnu.org/licenses/license-list.html#apache2) illustrates both cases, differing for GPL 3 and GPL 2:

> * This is a free software license, compatible with version 3 of the GNU GPL.
> * Please note that this license is not compatible with GPL version 2, because it has some requirements that are not in that GPL version.

Some are more complicated and require human judgment, e.g. [Eclipse Public License Version 2.0](https://www.gnu.org/licenses/license-list.html#EPL2):

> In terms of GPL compatibility, the Eclipse Public License version 2.0 is essentially equivalent to version 1.0. The only change is that it explicitly offers the option of designating the GNU GPL version 2 or later as a “secondary license” for a certain piece of code.
>
> If an initial contributor releases a specific piece of code and designates GNU GPL version 2 or later as a secondary license, that provides explicit compatibility with those GPL versions for that code. (Doing so is roughly equivalent, for users, to releasing that piece of code under a dual license, EPL | GPL.) However, the EPL2 without this designation remains incompatible with the GPL. 

So it would be useful to be able to machine-check whether a particular license is one of the trivial cases ("always") or one of the hopeless cases ("never"). Though I'm just a programmer with no legal qualifications so I may be missing some subtlety here.

**Comment by wking** [comment]
> So it would be useful to be able to machine-check...

I agree, but I think exposing an API for "is A compatible with B?" should be up to the GNU folks and other opinionated people.  The SPDX job is just identifying the licenses in question so folks can use SPDX license expressions for A and B without having to inline the full text.

**Comment by goneall** [comment]
I agree that SPDX should not represent any SPDX organization opinions or judgement on license compatibility.

One approach would be to define these flags to be "The FSF declares the license to be compatible with ...".  This way, the flag would be representing a verifiable fact based on what is represented on the FSF website.  There is still an opinion, but it is the opinion of the FSF.

If it is problematic to include the FSF opinion on license compatibility directly in the SPDX metadata, those interested in this information could use the fsf-api referenced above in conjunction with the SPDX license data.

**Comment by lassik** [comment]
OK, you raise a good point. Perhaps the FSF should have an API that uses SPDX license identifiers and supplies official GPL compatibility data. That would be the best of both worlds: programmers could easily combine SPDX and FSF data yet SPDX would not have to bear the responsibility of interpretation.

So if a dataset like https://github.com/wking/fsf-api was officially maintained by the FSF using SPDX IDs that would be perfect.

OSI also has an unofficial API: https://github.com/opensourceorg/licenses

**Comment by jlovejoy** [comment]
A couple additional points to those already raised:
- we have attempted to identify what the FSF considers "free" (in the same way we identify if a license is OSI-approved) and that is fine as it's a binary determination based on their definition of free.
- but the compatibility issue is not something SPDX should represent (and this has been asked a few times over the years) - for all the reasons already stated and additionally "compatibility" besides being very much a legal interpretation of both licenses and not having clear cut answers or standards against which to judge, it is also a determination dependent on how each piece of software is being used.  You have to start by identifying when "compatibility" is an issue, (an interpretation in and of itself) and then interpret both licenses against that use-case.  Having worked on various tools for license compliance in the past, this is not an analysis that lends itselsf to software tools, let alone a flat "list" of data.

**Comment by lassik** [comment]
@jlovejoy Are some permissive licenses (e.g. BSD-2-Clause or MIT) not "obviously" compatible with the GPL?

**Comment by jlovejoy** [comment]
@lassik - even if I think there are, it doesn't matter. We are not going to include legal interpretations as part of the SPDX License List

**Comment by swinslow** [comment]
Hi @lassik, even if some may view it as clear or obvious, deciding whether one license is compatible with another involves interpreting the licenses in some way. SPDX’s goals have been focused on identifying the license text but not interpreting it. From https://spdx.org/spdx-license-list/license-list-overview:

> The goal of SPDX is not to evaluate licensing information or to provide legal interpretations. The only goal is to reliably and consistently communicate and share objective factual information so that organizations using software components will have the information necessary to conduct their independent analysis and evaluation.

If other projects choose to provide interpretations of which licenses are compatible with which others, that would be extremely helpful (and hopefully they'll use SPDX license identifiers when they do so, to avoid confusion about which license is which!) But making those calls is outside the scope of the SPDX license list itself.
