### ISSUE TITLE
New license request: O-UDA-1.0 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by mlinksva** [spdx/license-list-XML#951]
**1.** License Name: Open Use of Data Agreement v1.0
**2.** Short identifier: O-UDA-1.0
**3.** License Author or steward: Microsoft
**4.** Comments: See background at https://github.com/microsoft/Open-Use-of-Data-Agreement#why-a-new-agreement including rationale and comparison with other open data licenses each of which is in the SPDX License List.

O-UDA-1.0 will be used for various datasets released on GitHub and elsewhere, examples forthcoming.
**5.** Standard License Header: 
**6.** URL: https://github.com/microsoft/Open-Use-of-Data-Agreement/blob/v1.0/O-UDA-1.0.md
**7.** OSI Status: Not Submitted

**Comment by mlinksva** [comment]
cc @royaljust 

I'm happy to make a PR with the correct XML formatting if/as appropriate.

**Comment by swinslow** [comment]
I'm generally in favor of adding. Looks to me like a straightforward open data license agreement, comparable to CDLA and other open data licenses on the list.

@mlinksva / @royaljust, do you have examples of where this license is in use in the wild? I see @mlinksva's comment that examples will be forthcoming; seeing some examples of real-world use would be helpful in considering it for addition to the license list.

**Comment by swinslow** [comment]
Hi @mlinksva and @royaljust, I wanted to circle back and see if you have any examples of this being used in the wild that you can share.

**Comment by mlinksva** [comment]
https://www.microsoft.com/en-us/research/blog/microsoft-research-open-data-project-evolving-our-standards-for-data-access-and-reproducible-research/ links:

- https://msropendata.com/datasets/94d31431-0842-447c-b990-245761b7c5f2
- https://msropendata.com/datasets/d7859d92-56c9-46f2-b217-6adafaa1500f
- https://msropendata.com/datasets/85596452-0fe3-4335-bc00-ae83ee8ffcfd

I can't produce a stable URL for a list, but it seems there are 10 datasets as of right now on that site under O-UDA-1.0. I believe a bunch more are in process. I don't know of any non-Microsoft uses yet, will add when I hear of any if useful at the time.

**Comment by swinslow** [comment]
Thanks for this @mlinksva. I note also that this has also been [submitted to Open Knowledge Foundation](https://discuss.okfn.org/t/license-approval-request-open-use-of-data-agreement-1-0/8865) for approval under their Open Definition, and the preliminary comments there are favorable.

I'm in favor of adding, and will raise this on today's legal team call to see if there is consensus.

**Comment by swinslow** [comment]
We didn't have time to turn to this one during the legal team call on 2020-02-13, I'm hoping to do so during the next call on 2020-02-27.

**Comment by jlovejoy** [comment]
@mlinksva - looks like you use O-UDA within the license - but the short identifier would be O-UDA-1.0

would it make sense, for consistency, to use O-UDA-1.0 within the license too?

**Comment by jlovejoy** [comment]
but substantively , seems fine to add to me

**Comment by swinslow** [comment]
Discussed on legal team call 2020-02-27, agreed to add. Please feel free to weigh in on preferences for the identifier and the term used in the license text, per @jlovejoy's comment above.

**Comment by mlinksva** [comment]
@jlovejoy to verify I understand, you're asking if it would make sense to add "-1.0" to:

> This is the Open Use of Data Agreement, Version 1.0 (the "O-UDA<b>-1.0</b>"). 

and then throughout?

That doesn't seem necessary, but I'm curious if it would be a first for a license to use its own SPDX ID internally? 😄

**Comment by jlovejoy** [comment]
that was essentially my thinking - I'm not sure it feels imperative in this instance - especially since the license is already in use.
It *is* more imperative as when the usage in the license is related to how to apply the license :)

probably would be first to use its own SPDX ID internally, unless SPDX adopted an identifier exactly as it was already used.

of course, version number is key for identifier.

**Comment by jlovejoy** [comment]
so yeah, just a thought that struck me, but a thought that can probably be ignored!

**Comment by swinslow** [comment]
Since it's already in use, I'd be in favor of adding this one as it is, in its current state (e.g. without having the defined term changed in the license text). If the license stewards do change it at some point in the future, I imagine we could accommodate that with markup pretty easily so that both would match to the same license list entry.

**Comment by mlinksva** [comment]
Great, I'll try to get a PR submitted soon (but feel free to go ahead if anyone is eager to do so).

**Comment by swinslow** [comment]
@mlinksva and @royaljust, I've submitted #1003 to add O-UDA-1.0 to the license list. Take a look and if you can give it a +1, I'll get it merged. Thanks!
