### ISSUE TITLE
New license request: COSL [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by ashok-cl** [spdx/license-list-XML#955]
**1.** License Name: CasperLabs Open Source License
**2.** Short identifier: COSL
**3.** License Author or steward: Medha Parlikar
**4.** Comments: While creating a new package, we have to specify a license for it. Present API needs it for uploading  new packages created on Bintray.
**5.** Standard License Header: 
**6.** URL: https://github.com/CasperLabs/CasperLabs/blob/dev/LICENSE
**7.** OSI Status: Pending

**Comment by swinslow** [comment]
@ashok-cl, I haven't done a close read of the license text yet, but please take a look at the [SPDX license inclusion guidelines](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md).

In particular I'd note the following:

> If it is a newly drafted license, it is drafted such that it can be used by anyone (e.g., it is not company-specific or a "vanity" license)

From a first glance, this looks like it is very specific to CasperLabs (going so far as referencing a specific commit and fork date from a particular repo as part of its terms). I haven't read any of the other terms of the license so far, but from an initial look it seems that that pushes it squarely into the "not drafted for general use" category.

**Comment by ashok-cl** [comment]
Thanks for your response Steve. Apologies as I could not respond to you
sooner as I was OOO.
Let me get back to you with more specific details on this.

Wishing you a Happy New Year 2020, in advance.

Cheers!
Ashok

**Comment by swinslow** [comment]
Hi @ashok-cl, circling back, do you have any updates on my earlier comments?

**Comment by ashok-cl** [comment]
Hi Steve,

Thanks for circling back on this issue. Since last time, we have reached
out to our lawyers who have prepared the initial draft with all the
comments that we received on this application. This is one of the important
items under progress for us but just by the nature is taking more time.

What would be your advice on this? Should we consolidate responses to all
the comments, make changes and then resubmit or try to resolve it in a
sequential manner? Your guidance is much appreciated.

Regards,
Ashok

**Comment by swinslow** [comment]
Hi @ashok-cl, speaking just from my own perspective here (others on the legal team can feel free to weigh in as well).

My expectation is that [the license as submitted in its current form](https://github.com/CasperLabs/CasperLabs/blob/dev/LICENSE) is probably not appropriate for inclusion on the SPDX License List. I'd refer back to the [SPDX License Inclusion Guidelines](https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md) and in particular the one I highlighted above:

> If it is a newly drafted license, it is drafted such that it can be used by anyone (e.g., it is not company-specific or a "vanity" license)

This license appears to refer to not only just a single project, but even a specific point in time and a particular commit hash. Although the SPDX License List does contain historical licenses that were specific to single projects, current practice has generally been that newly-drafted licenses for the License List should be usable by anyone and should not be project-specific. (In addition to a balancing of the other factors described in the guidelines.)

Given that, I think the license is probably not going to be added in its current form, and would (at a minimum) need to show wider or more prominent use before being added, in addition to the other guidelines factors.

**Comment by ashok-cl** [comment]
Thanks for the guidance Steve. This makes sense and I have taken this
feedback to the legal team so that they can look at updating the license
accordingly.

Appreciate your feedback and guidance here.

**Comment by jlovejoy** [comment]
leaving this open and with "waiting for" label, but putting for Later milestone for now

**Comment by swinslow** [comment]
Discussed on 2020-05-21 legal team call, agreed that as currently constituted this is neither drafted for general use nor likely to meet other license inclusion requirements, so it is not accepted.
