### ISSUE TITLE
New license request: LOv2 [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by SylviaLambert43** [spdx/license-list-XML#961]
**1.** License Name: OPEN LICENCE 2.0
**2.** Short identifier: LOv2
**3.** License Author or steward: Etalab (French Government)
**4.** Comments: -SPDX id required in interop' exchanges (DCAT-AP)
- harvester like udata should use this information
**5.** Standard License Header: 
**6.** URL: https://github.com/etalab/licence-ouverte/blob/master/open-licence.md
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Hello @SylviaLambert43, thanks for submitting.

Please note that this license was added to the SPDX list with the identifier [etalab-2.0](https://spdx.org/licenses/etalab-2.0.html) in October (see #935), so I will go ahead and close this issue.
