### ISSUE TITLE
New license request: NEKO [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by ArthurSegato** [spdx/license-list-XML#964]
**1.** License Name: Nekoware License
**2.** Short identifier: NEKO
**3.** License Author or steward: Arthur Segato Paulo
**4.** Comments: I believe cats need more affection and love.
**5.** Standard License Header: 
**6.** URL: https://arthursegato.com/nekoware/
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
URL seems to be 404, here is the license text from the submission:

```
'Nekoware License'

Version 1

"You are free to use this thing any way and wherever you want as long as you pet a cat first, in case there are no cats near, I allow you to pet me."

This license was created by Arthur Segato

13/01/2020
```

**Comment by swinslow** [comment]
@ArthurSegato can you provide some examples of where this license is being widely used by others?

**Comment by ArthurSegato** [comment]
> @ArthurSegato can you provide some examples of where this license is being widely used by others?

As this license is recent I still have no examples of other projects to show you, the 404 error is due to the website is undergoing changes, sorry for the inconvenience.

**Comment by jlovejoy** [comment]
@ArthurSegato - do I understand correctly that you wrote this license based on a belief that cats need more affection and it's not actually used (yet)?

We have just updated our license inclusion guidelines, I'm not sure it meets those - see https://github.com/spdx/license-list-XML/blob/master/DOCS/license-inclusion-principles.md

**Comment by ArthurSegato** [comment]
I read the new guidelines and saw that my license does not fit it, I will reformulate it, thanks for your attention.
