### ISSUE TITLE
New license request: LGPL-3.0-linking-exception [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by tsteenbe** [spdx/license-list-XML#975]
**1.** License Name: LGPL-3.0 Linking Exception
**2.** Short identifier: LGPL-3.0-linking-exception
**3.** License Author or steward: Canonical
**4.** Comments:  This exception seem to come originally from Canonical but have several to other libraries using it.
**5.** Standard License Header: 
**6.** URL: 
- https://enterprise.dejacode.com/licenses/public/linking-exception-lgpl-3.0/
- https://launchpad.net/ubuntu/trusty/+source/golang-goyaml/+copyright
- https://raw.githubusercontent.com/go-xmlpath/xmlpath/v1/LICENSE
- https://github.com/juju/errors/blob/master/LICENSE
- https://github.com/goamz/goamz/blob/master/LICENSE
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Thanks @tsteenbe!

I'm in favor of adding this. I've run into this one regularly in real-world use. I haven't yet compared the various links from your submission to confirm they're identical, but (assuming they are) I would be good with adding this.

My only comment is the name. In 3.8 we added `GPL-3.0-linking-exception` based on a templated version coming from the FSF FAQ. I wonder if adding one here with the name and ID `LGPL-3.0-linking-exception` might confuse folks into thinking that it's also an "officially blessed" FSF exception.

If this originates from Canonical, perhaps something more like `LGPL-3.0-Canonical-linking-exception`? I imagine @jlovejoy might have some opinions on the naming for this one in particular  :)

**Comment by swinslow** [comment]
Text of exception from original submission:

```
As a special exception to the GNU Lesser General Public License version 3
("LGPL3"), the copyright holders of this Library give you permission to
convey to a third party a Combined Work that links statically or dynamically
to this Library without providing any Minimal Corresponding Source or
Minimal Application Code as set out in 4d or providing the installation
information set out in section 4e, provided that you comply with the other
provisions of LGPL3 and provided that you meet, for the Application the
terms and conditions of the license(s) which apply to the Application.

Except as stated in this special exception, the provisions of LGPL3 will
continue to comply in full to this Library. If you modify this Library, you
may apply this exception to your version of this Library, but you are not
obliged to do so. If you do not wish to do so, delete this exception
statement from your version. This exception does not (and cannot) modify any
license terms which apply to the Application, with which you must still
comply.
```

**Comment by tsteenbe** [comment]
@swinslow  +1 from my side on using `LGPL-3.0-Canonical-linking-exception`

**Comment by jlovejoy** [comment]
I have done some asking around at Canonical (where I work) and there is no evidence that I can find that Canonical authored this exception. I don't know where it came from, but I'm not sure it's appropriate to use a company name  in the title - looking at https://spdx.org/licenses/exceptions-index.html, it would certainly be a first.

from the links above, it looks like this is used in a few projects, so using a project name (more typical from our list of exceptions) may not work either.

**Comment by swinslow** [comment]
Thanks @jlovejoy, makes sense.

@tsteenbe well, in the absence of an "official" linking exception from FSF for LGPL-3.0 (at least that I'm aware of), I suppose calling this `LGPL-3.0-linking-exception` is reasonable. If this is actually used in the wild by several projects, and there isn't another better name, I'd be in favor of just going with that.

**Comment by jlovejoy** [comment]
seems like there is support to add this? can we mark it as such?

**Comment by swinslow** [comment]
Agreed, I'll add the "accepted" tag.

**Comment by swinslow** [comment]
@tsteenbe I just submitted #1001 to address this -- would be great to get your quick review as the original requester of this. Thanks!
