### ISSUE TITLE
Update BSD-2-Clause-FreeBSD

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#976]
Adding issue originally from @pgiffuni in license-list-data repo at https://github.com/spdx/license-list-data/pull/58:

= = = = =

* "All rights reserved." is considered obsolete.
 
* What appears to be a final disclaimer is not part of the license (and has never been used in code). It was a disclaimer from the FreeBSD Documentation Project that was bogusly copied by some sites, including OSI, but that has slowly been fixed.

For further reference, check https://www.freebsd.org/doc/en_US.ISO8859-1/articles/committers-guide/pref-license.html

**Comment by swinslow** [comment]
Hi @pgiffuni, a few thoughts on this:

The `BSD-2-Clause-FreeBSD` entry on the SPDX License List pre-dates my involvement with SPDX, so I can't speak to how it was originally included. The purpose of the list is to help with identifying licenses that are seen in the wild, whether in code itself or in associated documentation. I am guessing that the "views and conclusions" final sentence was included because it was seen as potentially applying to the codebase, and was viewed as potentially a distinct license text from `BSD-2-Clause` without that sentence.

I have seen other instances where folks are using that last sentence in code both in and out of FreeBSD, with other names listed (for example, see https://people.freebsd.org/~ivoras/wine/patch-wine-nvidia.sh)

On the SPDX License List, we do not change identifiers since the community depends on the license identifiers and URLs remaining stable. However, we can deprecate licenses (which keeps them listed, but moved to the section at the bottom of https://spdx.org/licenses/).

I'd propose the following:

- we deprecate BSD-2-Clause-FreeBSD
- we add an alternative license, which contains the same "views and conclusions" text, but with markup allowing other names (rather than FreeBSD) to be included there
- in the meantime, the FreeBSD project might want to switch to using the short-form identifier `BSD-2-Clause` in their code, since that one does not include the final sentence you are describing -- see https://spdx.org/licenses/BSD-2-Clause.html

Does that all make sense?

**Comment by karsten-klein** [comment]
How does this relate also to BSD-2-Clause-NetBSD. 

I would argue that this should also be deprecated.

The line "This code is derived from software contributed to The NetBSD Foundation by " may - as above - not regarded as part of the license.

I hope I didn't miss anything in my cross-checking:
- BSD-2-Clause-NetBSD is not OSI-approved
- Differences between BSD-2 Clause only in the scope of placeholders for the copyright holders.

**Comment by swinslow** [comment]
Discussed on 2020-07-26 legal team call, noted that -NetBSD was already handled previously; agreed to deprecate -FreeBSD variant and to add a more general one; @swinslow to prepare and submit PR. 

See https://github.com/spdx/meetings/blob/master/legal/2020-07-16.md for cross-ref

**Comment by vmbrasseur** [comment]
👍 once the templating is fixed.
