### ISSUE TITLE
Add MulanPSL-2.0

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#978]
In license list release 3.7 we added [MulanPSL-1.0](https://spdx.org/licenses/MulanPSL-1.0.html), a permissive license containing both Chinese text and an English translation.

Based on https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-February/004695.html, it appears that OSI has now approved version 2 of the Mulan Permissive Software License. (Please disregard the "V1" in the thread title at that link; it was an updated v2 that was submitted and approved.)

Version 2 is available at https://license.coscl.org.cn/MulanPSL2/. From a basic review, it looks mostly the same except that a new Section 6 was added, clarifying that if there is a conflict between the Chinese and English versions, the Chinese version will prevail. Additionally, some parts of the English translation were cleaned up and clarified, and it appears there were some edits to the Chinese section as well (but I'm not remotely qualified to weigh in on what those say).

In any event, since this was approved by the OSI Board, I believe it is a clear thumbs-up to add to the SPDX License List. Would be great to get corresponding +1's from others so we can add it. Thank you!

**Comment by jlovejoy** [comment]
yes, if it's approved by OSI, then we add it to the SPDX License List

**Comment by swinslow** [comment]
Discussed on legal team call 2020-02-27, agreed to add.
