### ISSUE TITLE
New license request: WiX-statement [SPDX-Online-Tools]

### ISSUE THREAD

**Issue by Jon-Work** [spdx/license-list-XML#979]
**1.** License Name: WiX Toolset License Statement
**2.** Short identifier: WiX-statement
**3.** License Author or steward: .NET Foundation
**4.** Comments: This license clarification is used by the WiX Toolset.  I'm not affiliated with the WiX Toolset, I am just using it to distribute software.

WiX generates installer packages.  This clarification is important, it clarifies that WiX can be used to distribute software that is under any license (even proprietary software).  Without this clarification, users would worry that they have to use the MS-PL for software distributed using WiX.

Usage:

SPDX-License-Identifier: (MS-RL WITH WiX-statement)
**5.** Standard License Header: 
**6.** URL: https://wixtoolset.org/about/license/
**7.** OSI Status: Not Submitted

**Comment by swinslow** [comment]
Text of license copied below from original submission:

> The WiX toolset is released under the Microsoft Reciprocal License (MS-RL). A reciprocal license is used to ensure that others who build on the effort of the WiX community give back to the WiX community. Specifically the license requires that fixes and improvements to the WiX toolset must be published using the same license.
> 
> Sometimes the reciprocal license is incorrectly interpreted to also apply to bundles, packages, and custom actions built using the WiX toolset. The Outercurve Foundation has previously provided this statement below to clarify which now the .NET Foundation reaffirms:
> 
> The WiX toolset (WiX) is licensed under the Microsoft Reciprocal License (MS-RL). The MS-RL governs the distribution of the software licensed under it, as well as derivative works, and incorporates the definition of a derivative work provided in U.S. copyright law. OuterCurve Foundation (and the .NET Foundation) does not view the installer packages generated by WiX as falling within the definition of a derivative work, merely because they are produced using WiX. Thus, the installer packages generated by WiX will normally fall outside the scope of the MS-RL, and any of your source code, binaries, libraries, routines or other software components that are incorporated in installer packages generated by WiX can be governed by other licensing terms.

**Comment by jlovejoy** [comment]
this seems more like either a "clarification" of what WiX thinks MS-RL means in relation to the WiX installer packages and the meaning of "derivative work"  

I'm not sure this rises to the level of an "exception" to the license terms? 

Would be nice to have someone from the WiX to comment or maybe @stephenrwalli has some insights, as he was involved with OuterCurve

**Comment by Jon-Work** [comment]
It's like the "Linux-syscall-note" exception that is already in the SPDX list.

Lawyers can argue whether in legal-speak it is a "note", "statement", "exception", "clarification", or something else.  But SPDX only has a technical category called "exceptions" that handles things like this, so it needs to be a SPDX "exception".

**Comment by jlovejoy** [comment]
@Jon-Work - do you represent WiX?

we had Linux contributors involved with the addition of the Linux-syscall-note and there was quite a bit of discussion about that.  So, discussion here is also just as appropriate.

**Comment by jlovejoy** [comment]
@Jon-Work - oops, sorry, you already said you don't represent WiX

any ideas on who we can tag for some insight on the intentions here?

as for the "lawyers can argue" comment (which comes across a bit snarky - this is the SPDX legal team, which is made up of some lawyers who have worked very hard to make the SPDX License List a consistent, reliable and usable thing!) - yes, we have a category called "exceptions" and we have had long discussions as to naming, but regardless of what it's called, the concept of what goes on that part of the list is what matters, see top of https://spdx.org/licenses/exceptions-index.html - notably this:
"These exceptions grant an exception to a license condition or additional permissions beyond those granted in a license; they are not stand-alone licenses. "

that's what I was trying to get at.

**Comment by swinslow** [comment]
Discussed on 2020-05-07 legal team call; pending response from submitter and also looking for input from the license stewards for WiX, if they are not currently in this issue thread. The SPDX license inclusion principles include input from license steward where applicable.

**Comment by jlovejoy** [comment]
@ jeffmcaffer - could you comment or point us to someone who has some direct background on this?  :)

**Comment by silverhook** [comment]
@jeffmcaffer ^ ^

**Comment by Jon-Work** [comment]
If you'd like to get the WiX developers involved in this thread, I suggest you contact them through their "wix-dev" mailing list - https://wixtoolset.org/documentation/mailinglist/

Sorry if anything I wrote came across as snarky, that wasn't my intention.

As I'm not part of the WiX team, I'm just a user of WiX and a fan of the SPDX system, there's not really anything more I can contribute here, so I'll gracefully bow out of this thread now.

Kind regards,

Jon

**Comment by jlovejoy** [comment]
thanks @Jon-Work  - appreciate the submission. it is somewhat standard to make sure the license steward/author is aware of a submission and, in this case, it would be especially helpful. We're working on it!

**Comment by MarkAtwood** [comment]
ill take this one

**Comment by MarkAtwood** [comment]
Checking in, I'm chasing down a conversation with the ED of the ,NET Foundation

**Comment by MarkAtwood** [comment]
The of .NET Foundation is Claire.Novotny@microsoft.com    

Email inviting their participation has been sent.

**Comment by robmen** [comment]
@jlovejoy has it right. The WiX Toolset is available under the MS-RL.

The purpose of the extra text is this:

> Sometimes the reciprocal license is incorrectly interpreted...

I requested that Outercurve Foundation provide us a small blurb of text to serve as a quick rebuttal to corporate lawyers who argued the MS-RL was viral. Outercurve provided the text and it was reaffirmed by .NET Foundation when the WiX Toolset copyright was transferred (due to Outercurve's closure).

That blurb has served its purpose extremely well for over a decade now.

**Comment by jlovejoy** [comment]
coming back to this - I only see this text on the website, but it does not appear to be included WITH the MS-RL in the LICENSE.txt file. We have not included other "commentary" about licenses on websites, should we do so here? Would that then set a dangerous precedent?

**Comment by swinslow** [comment]
Discussed on 2020-10-22 SPDX legal team call. Since the text appears on the website, but does not appear to be included in any of the WiX code itself, it doesn't appear to fit the typical model of being a license exception used in code. 

If the WiX project plans to incorporate it into its code, then it might be more appropriately viewed as an exception / modification that is appropriate for inclusion on the exceptions list. But if it remains just on the website, it seems closer to commentary interpreting the license, rather than an actual exception to MS-RL.
