### ISSUE TITLE
Deprecate BSD-2-Clause-NetBSD

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#980]
[BSD-2-Clause-NetBSD](https://spdx.org/licenses/BSD-2-Clause-NetBSD.html) is identical to [BSD-2-Clause](https://spdx.org/licenses/BSD-2-Clause.html), with one exception -- the -NetBSD variant includes the following at the beginning:

```
This code is derived from software contributed to The NetBSD Foundation by 
```

Setting aside the fact that the sentence is incomplete and probably needs markup, if it remains...

I don't think that this is sufficiently distinctive from standard BSD-2-Clause that it warrants having a separate identifier. I view this line as being more akin to a copyright notice, describing perhaps the source of code but not saying anything relevant from a license perspective.

I'm not suggesting we remove it from the license list, since it already exists on the list and folks might be using the ID. But I would suggest that we move it to the deprecated category and add a note that it is viewed as being substantively identical to BSD-2-Clause.

**Comment by jlovejoy** [comment]
yeah, this has always kind of bugged me. I'm not sure what the historical reason for having it was - might be worth a bit of digging on that.

I'd also be curious to know from various tool/scanning folks how often it is found (in this form)

**Comment by jlovejoy** [comment]
> I'd also be curious to know from various tool/scanning folks how often it is found (in this form)

@pombredanne @goneall  - any input on the above question?

**Comment by goneall** [comment]
> I'd also be curious to know from various tool/scanning folks how often it is found (in this form)

Less common now than 5 to 10 years ago, but still very common in my experience

**Comment by swinslow** [comment]
I've run into it periodically in the code I'm reviewing (which is what prompted me to file the issue)  :)

Sounds like there's support to deprecate it. Unless there's objection, I'll prep a PR to move it to deprecated status and add a note explaining why.

**Comment by pombredanne** [comment]
@jlovejoy 

> > I'd also be curious to know from various tool/scanning folks how often it is found (in this form)

We see it often enough in embedded devices. I will soon have a larger DB of scans online so I will then be able pull some stats on frequencies. There are no issue with deprecating this at all.
