### ISSUE TITLE
clarifications on licensing of the contents of this repository (or files generated from it and hosted on the spdx site)

### ISSUE THREAD

**Issue by lelutin** [spdx/license-list-XML#986]
Hello,

I'm working on packaging a ruby library called ruby-spdx-licenses[0] [1] for
debian and I had some questions pop to mind about licensing.

0:https://rubygems.org/gems/spdx-licenses
1:https://github.com/domcleal/spdx-licenses

The code ships a a copy of the SPDX license list in JSON format. The copy
was taken from the SPDX web site:

https://github.com/domcleal/spdx-licenses#spdx-licenses

From what I could gather, the website specifies that all content is
covered by CC-BY 3.0:

https://spdx.org/Trademark
https://www.linuxfoundation.org/terms/

However, I'm not confident in my comprehension of the trademark and
licensing information that I found. Also, I was pointed to this repository
as the source of the JSON file, and from the repository, I don't have a
clear view on what licensing applies to the contents of the repository
and files produced by it.

Could you help me to confirm or clarify what license I should attribute to
that JSON file?

Also, I found some mentions on the SPDX web site about some terms related
to the use of the SPDX name, which would be present in the package name
and in its description

https://spdx.org/frequently-asked-questions-faq-0

"Can I use the SPDX trademark?
    Yes. It is a registered trademark so don't forget the (r)."

Do I need to add (r) after each occurrence of the name "SPDX" in the
package description? Is it an issue if the name "SPDX" (lowercased) is
used in the package name itself? For this latter case, I'm not sure that I can
include a (r) in the package name.

**Comment by ge-fa** [comment]
Dear maintainers,

Any information regarding this?

Thanks!

**Comment by jlovejoy** [comment]
looks like the CC0 license info was added to the file some time ago - see https://github.com/spdx/license-list-XML/blob/master/package.json

@swinslow  - am I looking at that correctly? given the specific file has been addressed, I think we can close this (and should have some time ago!)

**Comment by jlovejoy** [comment]
we also have #1044 - so will keep that open, reference this and close this one - as they are addressing the same issue
