### ISSUE TITLE
Parity 7.0.0

### ISSUE THREAD

**Issue by kemitchell** [spdx/license-list-XML#987]
This is a tracking issue for identification of [Parity-7.0.0](https://paritylicense.com/versions/7.0.0.html).

A pull request with an XML file, #949, was opened at the start of November in 2019.

@swinslow [helpfully suggested opening this issue](https://github.com/spdx/license-list-XML/pull/949#issuecomment-593708209), to ensure it makes the docket.

**Comment by swinslow** [comment]
I'm generally in favor of adding. This is the next version of the Parity license for which we added version 6.0.0 in release 3.6 ([XML](https://github.com/spdx/license-list-XML/blob/master/src/Parity-6.0.0.xml), #805)

@kemitchell a couple of quick questions:

- can you point to examples of current use of Parity-7.0.0 in the wild?
- can you give a short summary of any significant substantive differences from 6.0.0 to 7.0.0?

Thank you!

**Comment by waldyrious** [comment]
> can you give a short summary of any significant substantive differences from 6.0.0 to 7.0.0?

Some links that could be useful (similar to the [list I compiled for the PR adding Prosperity 3.0.0](https://github.com/spdx/license-list-XML/pull/960)):

- [Announcement blog post](https://blog.licensezero.com/2019/11/04/Parity-7.html)
- [Release notes](https://github.com/licensezero/parity-public-license/releases/tag/v7.0.0) in the license's repository
- [List of commits](https://github.com/licensezero/parity-public-license/compare/v6.0.0...v7.0.0) between v6.0.0 and v7.0.0
- [Full text of the 7.0.0 license](https://github.com/licensezero/parity-public-license/blob/v7.0.0/LICENSE.md), and [full text of the v6.0.0 license](https://github.com/licensezero/parity-public-license/blob/v6.0.0/LICENSE.mustache)

Of these, the release notes seem to provide the most explicit human-readable summary of the changes:

> - Rewrite based on the [API Copyleft License](https://github.com/kemitchell/api-copyleft-license), in the style of the [Blue Oak Model License](https://blueoakcouncil.org/license/1.0.0) and [Polyform Project](https://polyformproject.org) licenses.
> - Add an explicit exception for prototypes.
> - Add an explicit exception for reverse engineering closed software.
> - Numerous improvements to copyleft rules.
> - Use string-interpolation-style `$`-sigil placeholders.

**Comment by kemitchell** [comment]
@zkat's https://github.com/zkat/cacache-rs currently uses 7.0.0. 

@substack's eyros [is waiting on SPDX identification](https://github.com/licensezero/paritylicense.com/pull/6) to move from 6 to 7.

**Comment by jlovejoy** [comment]
@swinslow - do we still need the "discuss on legal call" label?

**Comment by swinslow** [comment]
No, I think this is OK to add given brief discussion on the call this week. I'm removing the label and marking it as approved.

**Comment by swinslow** [comment]
I'll take a look at the PR that @kemitchell submitted at #949

**Comment by swinslow** [comment]
Closing this issue, as #949 has now been merged. Thanks all!
