### ISSUE TITLE
Request to add CC Public Domain Mark

### ISSUE THREAD

**Issue by swinslow** [spdx/license-list-XML#988]
Copying relevant portions from spdx-legal mailing list, see https://lists.spdx.org/g/Spdx-legal/topic/71831424#2734:

From @david-a-wheeler:
> The SPDX license list needs to add the Creative Commons "public domain mark". Yes, from some points of view it's technically not a license, but when you're trying to figure out what rights the recipient has, it is *definitely* a license.... it's just a license (permission) granted directly through the application of law. The SDPX license currently includes the "Creative Commons Public Domain Dedication and Certification" https://spdx.org/licenses/CC-PDDC.html which combined the features of both, but that was retired years ago and split up into the CC0 and the public domain mark.

From @swinslow:
> Regarding the Creative Commons Public Domain Mark: For items to be added to the SPDX License List, among other requirements there needs to be a corresponding "matching text" that represents the entry that actually goes on the list. You can see these in the texts that are used at https://spdx.org/licenses/CC0-1.0.html and https://spdx.org/licenses/CC-PDDC.html. Is there a corresponding text that is associated with Creative Commons' Public Domain Mark? From some brief searching I'm not coming across one. If there is one then I would encourage adding an issue at https://github.com/spdx/license-list-XML/issues with a link to the text, so that it can be reviewed and considered.

From @david-a-wheeler:

> Re: the "Public Domain Mark”, to retrieve the “matching text” you start from here:
> 
> https://creativecommons.org/choose/mark/
> 
> Unfortunately, what they’ve chosen to do is to “auto-fill” the matching text. So what happens is that you get the matching text by retrieving this URL with various fields filled in:
> 
> https://creativecommons.org/choose/mark/results
> 
> So for example, https://creativecommons.org/choose/mark/results?work_title=WORK_NAME&author_title=AUTHOR_NAME&author_href=AUTHOR_URL&curator_title=INDIVIDUAL_NAME&curator_href=INDIVIDUAL_URL&lang=en_US&field1=continue
> 
> ends up being displayed as:
> 
> This work (WORK_NAME, by AUTHOR_NAME), identified by INDIVIDUAL_NAME, is free of known copyright restrictions.
> 
> While just retrieving https://creativecommons.org/choose/mark/results reports:
> 
> This work is free of known copyright restrictions.
> 
> It’s pretty obvious how this works. I suspect the Creative Commons folks would be happy to reveal the full template, they probably have just never been asked.

**Comment by goneall** [comment]
This could be added as a template e.g.:

```
This work (<alt match=".+" name="work">Work Name</alt>, (<alt match=".+" name="author">Author Name</alt>), identified by <alt match=".+" name="curator">Curator Name</alt>, is free of known copyright restrictions.
```

**Comment by swinslow** [comment]
Thanks @goneall! 

Also on the mailing list it was just posted where these templates come from, with a few other potential variations (thanks @pombredanne!) -- https://github.com/creativecommons/cc.license/blob/a134299fdb0e882b84a2c181afc5588e13ae32df/cc/license/formatters/classes.py#L324

**Comment by david-a-wheeler** [comment]
FYI, Philippe Ombredanne appears to have found the underlying template:

> https://github.com/creativecommons/cc.license/blob/a134299fdb0e882b84a2c181afc5588e13ae32df/cc/license/formatters/classes.py#L324

**Comment by goneall** [comment]
A bit more work to have a template that covers all of the options, but definitely doable with an hour or so worth of work.

**Comment by carmenbianca** [comment]
Ought someone from CC be pinged to catch their input?

100% ack on adding this, though. Pinging @mxmehl and @silverhook to make them aware of this issue.

**Comment by pombredanne** [comment]
If this is of any use we are tracking several public domain-related licenses in ScanCode beside the two CC present in SPDX and the CC PD mark subject of this ticket: 

- the CC PD mark: https://github.com/nexB/scancode-toolkit/blob/9d53e94474347da5292aae7be9bb7cedb4399a9a/src/licensedcode/data/licenses/cc-pdm-1.0.yml

- For things specifically from the US Gov't as this is special especially for non US users: https://github.com/nexB/scancode-toolkit/blob/17067e2607ab5c77b116f69a3d0df9a59032d70e/src/licensedcode/data/licenses/us-govt-public-domain.yml

- A generic public domain where the actual captured text defines the specifics: https://github.com/nexB/scancode-toolkit/blob/17067e2607ab5c77b116f69a3d0df9a59032d70e/src/licensedcode/data/licenses/public-domain.yml 

- The same but when it comes with a warranty disclaimer: https://github.com/nexB/scancode-toolkit/blob/6ca3b5e8a74085f9390e7086b7e2a109b8afee52/src/licensedcode/data/licenses/public-domain-disclaimer.yml

... and several variations on the above generic ones that are common enough to warrant having their own license key https://github.com/nexB/scancode-toolkit/search?l=YAML&q=%22category%3A+Public+Domain%22 

As for having something that specifically is for things deemed not copyrightable, this should IMHO be its own license id.

**Comment by mlinksva** [comment]
The URL CC uses to identify PDM is https://creativecommons.org/publicdomain/mark/1.0/

FWIW there's also a FAQ at https://wiki.creativecommons.org/wiki/PDM_FAQ

Unlike all other CC instruments there isn't a corresponding license text. The output/templates from CC cited above are notices, but perhaps could serve as license text in a SPDX record; an alternative would be the "deed" text at the URL above.

> Ought someone from CC be pinged to catch their input?

@kgodey in case there's interest from CC in providing input.

**Comment by waldyrious** [comment]
> A bit more work to have a template that covers all of the options, but definitely doable with an hour or so worth of work.

In case that helps, here's a regex that covers all the plaintext variations:

```js
/This work(?: \((?:WWW(?:, by AAA)?|by AAA)\))?(?:, identified by CCC,)? is free of known copyright restrictions\./
```

Visualized as a [Debuggex](https://www.debuggex.com/) diagram:

![Screenshot 2020-03-10 at 12 22 50](https://user-images.githubusercontent.com/478237/76311942-ea797b80-62c9-11ea-9094-972d4fe63481.png)

**Comment by mlinksva** [comment]
By the way, another initiative that may be worth looking at if folks want to think about how statements about copyright status ought be represented in SPDX in general, rather than treating CC-PDM-1.0 as a one-off: https://rightsstatements.org which IIRC @mzeinstra is one of the main architects of.

**Comment by mzeinstra** [comment]
Thank for the notification Mike, I also participated in the workshops that led to the Public Domain Mark. 

I was one of the architects of rightsstatements, but most credits should go to @anarchivist and @aisaac , I was more heavily involved in one of its predecessors.  I'll open a new ticket where we can discuss if those are fit for the purpose of SPDX.

**Comment by sarahpearson** [comment]
As @mlinksva correctly states above, the CC Public Domain Mark does not have corresponding legal text. It is more like a rights statement than a license.

**Comment by aisaac** [comment]
Just one detailed note about @mlinksva 's comment above: should you want to use linked data or other machine-readable format, the canonical URI for the CC rights statements uses HTTP not HTTPS (even though it - correctly - redirects to HTTPS for browsers). See discussions from the perspective of statements re-users such as IIIF at https://github.com/IIIF/trc/issues/32. There's also a couple of not-yet-closed tickets about this in the CC space: https://github.com/creativecommons/creativecommons.org/issues/1030 https://github.com/creativecommons/cc.licenserdf/issues/7

**Comment by jlovejoy** [comment]
@pombredanne - if there are commonly found public domain dedications that have consistent associated text to express them, then please submit them to be added to the SPDX License List

as for a general public domain identifier that is *not* associated with a set text, we have discussed this many times in the past - please see this write-up as to why that is problematic: https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files_(DRAFT)

**Comment by karsten-klein** [comment]
Skimming over the above comments I would argue:

That the text can be extracted from [https://creativecommons.org/publicdomain/mark/1.0/](url) as @mlinksva pointed out earlier. 

The relevant phrases for matching the CC Public Domain Mark 1.0 would then be
    - "This work has been identified as being free of known restrictions under copyright law, including all related and
       neighboring rights"
    - "You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission"

The later of the two is definitely a grant (a permission), as @david-a-wheeler pointed out in the initial comment. I also follow the argument of @david-a-wheeler, that the PDD was a predecessor of the PDM. As such the PDM is an equivalent of PDD and should also be included in the SPDX list (for completeness in combination wit CC0).

The above regexp discussion is another topic; which I would split from the initial request / this issue. 

This approach would also be in alignment with @pombredanne above contribution referring to "the CC PD mark" [https://github.com/nexB/scancode-toolkit/blob/9d53e94474347da5292aae7be9bb7cedb4399a9a/src/licensedcode/data/licenses/cc-pdm-1.0.yml](url)

Hope this helps in the decision process...

Cheers,
Karsten

**Comment by pmadick** [comment]
The SPDX Legal Team considered this request during the September 10, 2020 meeting.  At this time the request to add the CC Public Domain Mark is denied, but may be reconsidered at a different time.  A good explanation of the standards for such a request can be found at https://wiki.spdx.org/view/Legal_Team/Decisions/Dealing_with_Public_Domain_within_SPDX_Files_(DRAFT) .  The Public Domain Mark is not a license, but appears to be a legal conclusion that may be drawn by a reviewer much like an SPDX document.

**Comment by Apteryks** [comment]
Hello,

This is closed, but I'm faced with this situation: I want to help a project migrate from using traditional copyright notices + license headers to REUSE/SPDX (`SPDX-License-Identifier` and `SPDX-FileCopyrightText`), e.g. in this PR: https://github.com/scheme-requests-for-implementation/srfi-151/pull/6/files#diff-12fe31e9b69c758fbb5bc1f9d716d64347364057dc87e146bfb543328d5f453d

I do not own any of the copyrights, and some files are under public domain.  Can I mark these as CC0-1.0, which is the closest license to "public domain" that is recommended e.g. by reuse.software? Or how do people deal with this, especially when the original author is not around to say whether they are OK with this?

It seems having a  CC Public Domain Mark identifier would offer a simple way to simply state the current status of the file without having to change its license status.
