### ISSUE TITLE
Remove “LEDs” typo(?) from NOSL

### ISSUE THREAD

**Issue by silverhook** [spdx/license-list-XML#991]
In NOSL currently we see the following section (emphasis mine):

> 3.7. Larger Works.
>You may create a Larger Work by combining Covered Code with other code not governed by the terms of this License and distribute the Larger Work as a single **LEDs** product. In such a case, You must make sure the requirements of this License are fulfilled for the Covered Code. 

…but looking at the [Internet Archive](https://web.archive.org/web/20090421091657/http://bits.netizen.com.au/licenses/NOSL/nosl.txt) of the original text, I can see the following:

> 3.7. Larger Works.
> You may create a Larger Work by combining Covered Code with other code not governed by the terms of this License and distribute the Larger Work as a single product. In such a case, You must make sure the requirements of this License are fulfilled for the Covered Code.

It seems to me that the word “LEDs” somehow snuck into there by pure chance when writing the SPDX template.

While we’re at it, it might make sense to add an Internet Archive link as well.

**Comment by swinslow** [comment]
Good eye @silverhook! That certainly does look to me like it's an error...

It might have come into SPDX by way of the FSF's license list -- looking at https://directory.fsf.org/wiki/License:NOSL I see the same error there.

I wonder if it's worth keeping "LEDs" as _optional only_ text, on the off chance that someone has used this as a template given that the mistake shows up in both SPDX and FSF's copies.

**Comment by silverhook** [comment]
> It might have come into SPDX by way of the FSF's license list -- looking at https://directory.fsf.org/wiki/License:NOSL I see the same error there.

Might make sense to let FSF know about that as well.

> I wonder if it's worth keeping "LEDs" as optional only text, on the off chance that someone has used this as a template given that the mistake shows up in both SPDX and FSF's copies.

Worth considering/discussing, yes.

Although a [very lazy search on GitHub](https://github.com/search?q=%22the+terms+of+this+License+and+distribute+the+Larger+Work+as+a+single+LEDs+product.%22&type=Code) coughs up only 73 results, most of which seem to be tooling to find this license or store it in a BoM.

**Comment by jlovejoy** [comment]
if I understand you comment about the 73 results, seems like that tilts toward adding optional tag?

**Comment by swinslow** [comment]
@jlovejoy I agree -- I think it's worth keeping this in but as optional, and perhaps indicating it also in the Notes for the license.

**Comment by swinslow** [comment]
Added #999 to fix this and add explanatory note.
