### ISSUE TITLE
Templated BSD-3-Clause-LBNL

### ISSUE THREAD

**Issue by isuruf** [spdx/license-list-XML#994]
https://github.com/pcdshub/pcdsdevices/blob/master/LICENSE.md is similar to BSD-3-Clause-LBNL except for some names. Can BSD-3-Clause-LBNL be changed to reflect a class of licenses instead of specific to one copyright holder?

**Comment by swinslow** [comment]
@isuruf Good catch and thanks -- I tend to agree that BSD-3-Clause-LBNL should be templated in a way that's similar to how BSD-3-Clause is templated. (i.e. move copyright text into the copyright field, and add templating for references to the copyright holders in the middle of the license text)

I'm in favor of making this change. Can other SPDX legal team participants weigh in either with a +1 or else comments to the contrary if they have concerns?

**Comment by jlovejoy** [comment]
I guess my question is: do we need templating? that is, is this license used in the wild with different name in clause 3 and the last paragraph?

While templating those aspects makes sense from a theoretical point of view - if, in practice, no one else is using the license, then it's not necessary. 

(copyright notice has its own matching guideline rule, so that's already accommodated for differences)

**Comment by swinslow** [comment]
@jlovejoy yes -- I think the issue is that the existing [BSD-3-Clause-LBNL](https://spdx.org/licenses/BSD-3-Clause-LBNL.html) names LBNL specifically in the copyright notice + clause 3 + last paragraph. But the one that was [linked to above](https://github.com/pcdshub/pcdsdevices/blob/master/LICENSE.md) names Stanford SLAC in those places but otherwise uses the same license text. (I am assuming; I haven't run a diff myself yet to confirm, but from a first glance it looks the same.)

So I think this is a real example of differences being used in practice, where markup is warranted.

**Comment by isuruf** [comment]
If you add the following diff to the LBNL text, you get the license I linked above with only whitespace changes.

```diff
--- lbnl.txt    2020-03-26 13:12:28.544880388 -0500
+++ slac.txt    2020-03-26 13:16:18.760878303 -0500
@@ -1,5 +1,5 @@
-Copyright (c) 2003, The Regents of the University of California, through Lawrence
-Berkeley National Laboratory (subject to receipt of any required approvals
+Copyright (c) 2018, The Board of Trustees of the Leland Stanford Junior
+University, through SLAC National Accelerator Laboratory (subject to receipt of any required approvals
 from the U.S. Dept. of Energy). All rights reserved. Redistribution and use
 in source and binary forms, with or without modification, are permitted provided
 that the following conditions are met:
@@ -11,7 +11,7 @@
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 
-(3) Neither the name of the University of California, Lawrence Berkeley National
+(3) Neither the name of the Leland Stanford Junior University, SLAC National Accelerator
 Laboratory, U.S. Dept. of Energy nor the names of its contributors may be
 used to endorse or promote products derived from this software without specific
 prior written permission.
@@ -19,7 +19,7 @@
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
-ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
+ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER, THE UNITED STATES GOVERNMENT, OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
@@ -32,7 +32,7 @@
 You are under no obligation whatsoever to provide any bug fixes, patches,
 or upgrades to the features, functionality or performance of the source code
 ("Enhancements") to anyone; however, if you choose to make your Enhancements
-available either publicly, or directly to Lawrence Berkeley National Laboratory,
+available either publicly, or directly to SLAC National Accelerator Laboratory,
 without imposing a separate written license agreement for such Enhancements,
 then you hereby grant the following license: a non-exclusive, royalty-free
 perpetual license to install, use, modify, prepare derivative works, incorporate
```

**Comment by swinslow** [comment]
Thanks for the diff @isuruf. I'm supportive of adding this templating (similar to how baseline BSD-3-Clause handles this). I can prepare a patch to the files in the license list repo if there's similar support from others on the SPDX legal team. @jlovejoy any objections?

**Comment by swinslow** [comment]
PR added at #998 to implement these markup edits.

**Comment by isuruf** [comment]
Thanks
