### ISSUE TITLE
New license request: BUSL-1.1

### ISSUE THREAD

**Issue by adamretter** [spdx/license-list-XML#995]
**1.** License Name: Business Source License 1.1
**2.** Short identifier: BSL-1.1
**3.** License Author or steward: Adam Retter
**4.** Comments: This is a Source Available license, not an Open Source license. However it is in use and its adoption is growing. IMHO Source Available code needs even clearer licensing than Open Source as users can access the source code publicly (e.g. GitHub), but it has use restrictions.

Software using this license:

1. CockroachDB - https://github.com/cockroachdb/cockroach/blob/master/licenses/BSL.txt
2. Sentry.io - https://github.com/getsentry/sentry/blob/master/LICENSE
3. Materialize - https://github.com/MaterializeInc/materialize/blob/master/LICENSE
4. MariaDB Max Scale - https://github.com/mariadb-corporation/MaxScale/blob/2.4/LICENSE24.TXT
5. ZeroTier - https://github.com/zerotier/ZeroTierOne/blob/master/LICENSE.txt
6. FusionDB - https://fusiondb.com

Related blog posts about BSL:
1. http://monty-says.blogspot.com/2016/08/applying-business-source-licensing-bsl.html
2. https://blog.adamretter.org.uk/business-source-license-adoption/
**5.** Standard License Header: Copyright (c) ${date} ${organization}

Use of this software is governed by the Business Source License included
in the LICENSE file and at www.mariadb.com/bsl11.

Change Date: ${change-date}

On the date above, in accordance with the Business Source License, use
of this software will be governed by the ${change-license}.
**6.** URL: https://mariadb.com/bsl11/
**7.** OSI Status: Not Submitted

**Comment by zvr** [comment]
The name "BSL" is already being used for Boost Software License: https://spdx.org/licenses/BSL-1.0.html

**Comment by adamretter** [comment]
@zvr Ah okay, somehow I missed that! Perhaps we could use `BUSL-1.1`

**Comment by jlovejoy** [comment]
I think MongoDB is the license steward. @adamretter - do you work for or represent them

**Comment by swinslow** [comment]
Discussed on 2020-05-07 legal team call, agreed that the license steward should be looped into the discussion on whether this should be added (if that's different from the submitter of this issue).

**Comment by adamretter** [comment]
@jlovejoy @swinslow I believe the "steward" if there is one, would be MariaDB (not MongoDB) - as they created the license.

**Comment by jlovejoy** [comment]
we will work on contacting someone at MariaDB

**Comment by adamretter** [comment]
@jlovejoy Any updates?

**Comment by adamretter** [comment]
This may or may-not also be of interest - https://blog.adamretter.org.uk/business-source-license-adoption/

**Comment by esplinr** [comment]
My project also uses the BUSL, so I created a PR to help the process along.

**Comment by swinslow** [comment]
We are checking with contacts at MariaDB to get their input on this. @esplinr thanks for the PR, will review for 3.11 in line with getting MariaDB feedback on whether this should be added to the list.

**Comment by jlovejoy** [comment]
discussed on 30th July call re: acceptance criteria: agreed it meets main criteria, but want to be sure steward is aware

issue on how to accommodate variability in license - namely additional grants - and how tools will handle that - be sure to run by tech team folks for input (and examples of use cases). This could be accommodated in a license expression by way of "WITH LicenseRef" but we don't have LicenseRef option for exceptions yet, but coming for 3.0
should also be dealt with (in context of SPDX spec) with License Comments

**Comment by niftylettuce** [comment]
Would love to see this implemented!  Thanks for your work everyone, I'm using this license on @SpamScanner and @ForwardEmail.

**Comment by jlovejoy** [comment]
reached out to a network I'm on for MariaDB contact...

**Comment by jlovejoy** [comment]
have found a contact at MariaDB and emailed them with link to issue and asked for review

**Comment by jlovejoy** [comment]
#1074 is prepared already for this

**Comment by swinslow** [comment]
Keeping open for comment from MariaDB, if not will merge on next legal team call in 2 weeks

**Comment by swinslow** [comment]
@jlovejoy I haven't seen any comment from MariaDB, so will plan to merge #1074 during the call today -- let us know if there's any reason we shouldn't proceed. Thanks!

**Comment by jlovejoy** [comment]
@swinslow - I've reached out to them again to let them know we are prepping for the next release this week. will comment here if/when I get a response

**Comment by swinslow** [comment]
Okay, I'll wait until tomorrow afternoon and then will merge if we haven't heard back by then.

**Comment by swinslow** [comment]
I've merged #1074 now, thank you @esplinr!

**Comment by adamretter** [comment]
Thank you everyone :-)
