### ISSUE TITLE
Should CC Licenses Also Include "Human-Readable" Summary?

### ISSUE THREAD

**Issue by bagasme** [spdx/license-list-XML#996]
## Description

This issue came from go-gitea/gitea#9105.

CC (Creative Commons) licenses text on this repo are all full legal code. On outside world, however, many users are simply link to its "human-readable summary". For example: [CC-BY-SA summary](https://creativecommons.org/licenses/by-sa/4.0/) instead of [its full legal code](https://creativecommons.org/licenses/by-sa/4.0/legalcode).

Maybe we can add such summaries to this repo, like:

```
(CC-BY-SA)

summary goes here

full legal code here
```

**Comment by goneall** [comment]
Transferring this issue to LicenseListXML - this could be resolved by adding optional text at the beginning of the CC-BY licenses with the summary text.

**Comment by jlovejoy** [comment]
do most people simply link to the "human-readable summary" or are people actually including this a the license text with their content?  If not, I'm not sure it matters, as the argument I'd see for adding it would be so that scanning tools could identify the text and "match" it as representing that license

**Comment by bagasme** [comment]
@jlovejoy i think mostly do the former than the latter.

**Comment by waldyrious** [comment]
FWIW, choosealicense.com [recommends](https://choosealicense.com/licenses/cc-by-4.0/) either using the full text, or merely linking to the summary page, but not including the summary text in the license file (which is what I assume @jlovejoy means by "are people actually including this a the license text with their content?"):

> **How to apply this license**
>
> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. It is also acceptable to solely supply a link to a copy of the license, usually to the [canonical URL for the license](https://creativecommons.org/licenses/by/4.0/).

I'd assume that informs how many will apply these licenses.

**Comment by bagasme** [comment]
> It is also acceptable to solely supply a link to a copy of the license, usually to the canonical URL for the license.

I thought that I mean full license text

**Comment by jlovejoy** [comment]
that is what I meant: to clarify - if people are not providing the text of the human-readable summary in with their content as the "license text" (in quotes, as it's not really the text of the license), then I don't see a reason to add it here.

If they are simply linking to a page that lands on the human-readable summary, which then actually links to the text of the licenses, that's a different thing (and also means we don't need to add it )

does that make sense?

am I missing something?

**Comment by swinslow** [comment]
Discussed on 2020-07-16 legal team call, agreed that the summary itself is distinct from the license. The summary text should not be added to the matching text.

For cross-references, if there is a volunteer from the community to go through and add additional cross-references to the summary pages, we would be open to that, but don't see it as a priority.

**Comment by swinslow** [comment]
No further comments, so closing issue.
